/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/

import Bong.Bong.AlphaValueExt
import Bong.Bong.Basic
import Bong.Bong.Basis
import Bong.Bong.BasisLattice
import Bong.Bong.Binary
import Bong.Bong.BinaryAdaptedBasis
import Bong.Bong.BinaryAdaptedValues
import Bong.Bong.BinaryAdmissibility
import Bong.Bong.BinaryAutomorphism
import Bong.Bong.BinaryDefectCriterion
import Bong.Bong.BinaryDiagonal
import Bong.Bong.BinaryDiagonalReflectionOrders
import Bong.Bong.BinaryDual
import Bong.Bong.BinaryDualModular
import Bong.Bong.BinaryExactRealization
import Bong.Bong.BinaryIntegralSquare
import Bong.Bong.BinaryInvariant
import Bong.Bong.BinaryModelIsometry
import Bong.Bong.BinaryModular
import Bong.Bong.BinaryModularInvariant
import Bong.Bong.BinaryNormalForm
import Bong.Bong.BinaryPrimitiveCoordinates
import Bong.Bong.BinaryRealization
import Bong.Bong.BinaryReflectionCoordinates
import Bong.Bong.BinaryScaledExactRealization
import Bong.Bong.BinaryShearIsometry
import Bong.Bong.BinarySpinorInclusion
import Bong.Bong.BinarySpinorPositiveReduction
import Bong.Bong.BinarySpinorReflectionReduction
import Bong.Bong.BinaryStrictModular
import Bong.Bong.BinaryUniqueness
import Bong.Bong.BinaryValueSet
import Bong.Bong.Classification
import Bong.Bong.ClassificationTransport
import Bong.Bong.CoordinateSegment
import Bong.Bong.DefectArithmetic
import Bong.Bong.DiagonalBinaryRepresentation
import Bong.Bong.DiagonalCodimensionOneCancellation
import Bong.Bong.DiagonalHasseSymbol
import Bong.Bong.DiagonalHeadCancellation
import Bong.Bong.DiagonalLocalClassification
import Bong.Bong.DiagonalQuaternaryComplement
import Bong.Bong.DiagonalRepresentationCons
import Bong.Bong.DiagonalRepresentationParity
import Bong.Bong.DiagonalSquareIsometry
import Bong.Bong.DiagonalTailCancellation
import Bong.Bong.DiagonalTernaryCore
import Bong.Bong.DiagonalTernaryRepresentationObstruction
import Bong.Bong.Dual
import Bong.Bong.Existence
import Bong.Bong.Good
import Bong.Bong.GoodBONGDeepIntegralExtension
import Bong.Bong.GoodBONGPrefixValues
import Bong.Bong.GoodBONGSameRankIntegralImage
import Bong.Bong.GoodBONGScalarAgreement
import Bong.Bong.GoodCons
import Bong.Bong.GoodExistence
import Bong.Bong.GoodMap
import Bong.Bong.HilbertDefectChoice
import Bong.Bong.Invariants
import Bong.Bong.Map
import Bong.Bong.MonotoneDiagonalization
import Bong.Bong.OrthogonalBasis
import Bong.Bong.Prefix
import Bong.Bong.PrefixDeterminant
import Bong.Bong.PrefixIsometry
import Bong.Bong.Properties
import Bong.Bong.QuadraticApproximationExact
import Bong.Bong.Representation
import Bong.Bong.RepresentationDual
import Bong.Bong.Rescale
import Bong.Bong.ResidueDefectProduct
import Bong.Bong.ResidueDefectProductProof
import Bong.Bong.ResidueFieldSize
import Bong.Bong.SectionTwo
import Bong.Bong.Segment
import Bong.Bong.SegmentConstruction
import Bong.Bong.SegmentTransport
import Bong.Bong.SpinorNorm
import Bong.Bong.Structural
import Bong.Bong.Suffix
import Bong.Bong.TruthParity
import Bong.Bong.UnaryDual
import Bong.Bong.ValueIsometry
import Bong.Dyadic.AbsoluteQuadraticDefect
import Bong.Dyadic.Basic
import Bong.Dyadic.CongruenceSubgroup
import Bong.Dyadic.HilbertDefectCriterionProof
import Bong.Dyadic.HilbertDuality
import Bong.Dyadic.HilbertMultiplicativityReduction
import Bong.Dyadic.HilbertSymbol
import Bong.Dyadic.MatrixCongruence
import Bong.Dyadic.NumberFieldCompletion
import Bong.Dyadic.PowerIdealResidueQuotient
import Bong.Dyadic.PrincipalUnitResidueQuotient
import Bong.Dyadic.QuadraticDefect
import Bong.Dyadic.QuadraticDefectHensel
import Bong.Dyadic.QuadraticNewtonRoot
import Bong.Dyadic.ResidueArtinSchreier
import Bong.Dyadic.UnitDefectClassification
import Bong.Dyadic.UnitSquareClass
import Bong.Dyadic.UnitSquareClassOddLayer
import Bong.Dyadic.Valuation
import Bong.Lattice.AdaptedBasis
import Bong.Lattice.AdjoinQuadraticSublattice
import Bong.Lattice.AdjoinVector
import Bong.Lattice.Automorphism
import Bong.Lattice.Basic
import Bong.Lattice.BasisIsometry
import Bong.Lattice.BasisUnits
import Bong.Lattice.BinaryRotationReflection
import Bong.Lattice.BinarySpinorRescale
import Bong.Lattice.DeepRescale
import Bong.Lattice.Determinant
import Bong.Lattice.DeterminantBasis
import Bong.Lattice.DeterminantFormRescaleClass
import Bong.Lattice.DeterminantIsometry
import Bong.Lattice.DeterminantProjection
import Bong.Lattice.DiagonalModular
import Bong.Lattice.Dual
import Bong.Lattice.DualIsometry
import Bong.Lattice.FormRescale
import Bong.Lattice.GlobalNADC
import Bong.Lattice.HyperbolicDiagonal
import Bong.Lattice.HyperbolicDiagonalSpinor
import Bong.Lattice.HyperbolicEichlerTransport
import Bong.Lattice.HyperbolicLatticeInvariants
import Bong.Lattice.HyperbolicLatticeModular
import Bong.Lattice.Ideals
import Bong.Lattice.Isometry
import Bong.Lattice.Jordan
import Bong.Lattice.JordanIsometry
import Bong.Lattice.JordanPrepend
import Bong.Lattice.JordanReverseDual
import Bong.Lattice.LatticeRescaleIsometry
import Bong.Lattice.MaximalNormSplitting
import Bong.Lattice.MixedPairing
import Bong.Lattice.Modular
import Bong.Lattice.ModularCriterion
import Bong.Lattice.ModularIsometry
import Bong.Lattice.ModularMembership
import Bong.Lattice.ModularParameter
import Bong.Lattice.ModularPrimitivePairing
import Bong.Lattice.ModularScale
import Bong.Lattice.ModularSplitting
import Bong.Lattice.ModularVolume
import Bong.Lattice.Negation
import Bong.Lattice.NestedSublattice
import Bong.Lattice.NormGenerator
import Bong.Lattice.NormGeneratorIsometry
import Bong.Lattice.NormGeneratorValues
import Bong.Lattice.NormIdealOrder
import Bong.Lattice.NormIdealOrthogonalProduct
import Bong.Lattice.NormRescale
import Bong.Lattice.OmearaBinaryGeneralPlane
import Bong.Lattice.OmearaChangeOfComplement
import Bong.Lattice.OmearaEvenPlaneNormalization
import Bong.Lattice.OmearaGeneralPlane
import Bong.Lattice.OmearaGeneralPlaneDiagonalization
import Bong.Lattice.OmearaHyperbolicCancellation
import Bong.Lattice.OmearaHyperbolicSpinor
import Bong.Lattice.OmearaHyperbolicTransvection
import Bong.Lattice.OmearaIntegralReflection
import Bong.Lattice.OmearaStableHyperbolicCancellation
import Bong.Lattice.OrthogonalBasis
import Bong.Lattice.OrthogonalDecompositionCons
import Bong.Lattice.OrthogonalDecompositionDual
import Bong.Lattice.OrthogonalDecompositionIdeals
import Bong.Lattice.OrthogonalDecompositionRankSum
import Bong.Lattice.OrthogonalDecompositionScale
import Bong.Lattice.OrthogonalMap
import Bong.Lattice.OrthogonalProductDecomposition
import Bong.Lattice.OrthogonalProductIsometry
import Bong.Lattice.OrthogonalSumRescale
import Bong.Lattice.PowerIdeal
import Bong.Lattice.PrimitiveBinarySpinor
import Bong.Lattice.PrimitiveVector
import Bong.Lattice.Product
import Bong.Lattice.ProjectedIsometry
import Bong.Lattice.Projection
import Bong.Lattice.ProjectionPreimage
import Bong.Lattice.ProjectionScaling
import Bong.Lattice.QuadraticValues
import Bong.Lattice.RankOneNormScale
import Bong.Lattice.RawJordanDecomposition
import Bong.Lattice.Reflection
import Bong.Lattice.ReflectionScaling
import Bong.Lattice.Restriction
import Bong.Lattice.ScaleBasis
import Bong.Lattice.ScaleGenerator
import Bong.Lattice.ScaleTruncation
import Bong.Lattice.ScaleTruncationDual
import Bong.Lattice.ScaleTruncationIsometry
import Bong.Lattice.ScaledHyperbolicMaximal
import Bong.Lattice.SpinorNorm
import Bong.Lattice.SpinorNormIsometry
import Bong.Lattice.SpinorNormMultiplicative
import Bong.Lattice.SpinorNormOrthogonalProduct
import Bong.Lattice.Sum
import Bong.Lattice.Transporter
import Bong.Lattice.Universality
import Bong.Lattice.VolumeRigidity
import Bong.QuadraticSpace.Basic
import Bong.QuadraticSpace.BinaryDiagonal
import Bong.QuadraticSpace.BinaryImproperIsometry
import Bong.QuadraticSpace.BinaryModel
import Bong.QuadraticSpace.Diagonalization
import Bong.QuadraticSpace.FieldDiagonalization
import Bong.QuadraticSpace.HyperbolicPlane
import Bong.QuadraticSpace.Isometry
import Bong.QuadraticSpace.IsometryDeterminant
import Bong.QuadraticSpace.LineOrthogonalSplit
import Bong.QuadraticSpace.OrthogonalExtension
import Bong.QuadraticSpace.OrthogonalMap
import Bong.QuadraticSpace.OrthogonalSum
import Bong.QuadraticSpace.OrthogonalSumCancellation
import Bong.QuadraticSpace.OrthogonalSumDiagonal
import Bong.QuadraticSpace.Reflection
import Bong.QuadraticSpace.ReflectionGeneration
import Bong.QuadraticSpace.RepresentationRange
import Bong.QuadraticSpace.Rescale
import Bong.QuadraticSpace.ScalarExtension
import Bong.QuadraticSpace.SpinorNorm
import Bong.QuadraticSpace.SpinorNormExtension
import Bong.QuadraticSpace.SpinorNormMultiplicative
import Bong.QuadraticSpace.SpinorNormReflection
import Bong.QuadraticSpace.SpinorNormReflectionMultiplication
import Bong.QuadraticSpace.WallForm
import Bong.QuadraticSpace.WallReflectionReduction

/-! Package root for the reusable local quadratic-lattice and BONG foundation -/
