name = "BongTheory"
version = "0.3.0-rc.1"
keywords = ["math"]
defaultTargets = ["Bong", "BongTest"]

[leanOptions]
pp.unicode.fun = true # pretty-prints `fun a ↦ b`
relaxedAutoImplicit = false
weak.linter.mathlibStandardSet = true
maxSynthPendingDepth = 3

[[require]]
name = "mathlib"
scope = "leanprover-community"
rev = "v4.32.1"

[[lean_lib]]
name = "Bong"
globs = ["Bong.*"]

[[lean_lib]]
name = "BongTest"
