/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.Beli2019Lemma714TypeIIFrame

/-!
# Beli (2019), Lemma 7.14(ii): reframing the type-II candidate

The candidate constructed in `Beli2019Lemma714TypeIIAssembly` initially lives
in tail--binary order.  Lemma 7.10 instead uses

`([x_3,...,x_s] perp pi J) perp [x_(s+1),...,x_N]`.

This file maps the candidate through the concrete frame isometry and proves
the literal coordinate formulas for the unchanged prefix, the exceptional
ternary block, and the unchanged suffix.  These formulas are the input to the
two endpoint certificates; no lattice equality is assumed here.
-/

namespace Bong

open Dyadic

universe u v

namespace BONG.GoodBONG

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {q : QuadraticSpace K V} {L : Lattice K V} {n : Nat}

private theorem lemma714TypeIIReframing_two_le_rank (n : Nat) :
    2 ≤ n + 3 := by
  omega

private theorem lemma714TypeIIReframing_ambientVector_castLength
    {m length : Nat} {Q : QuadraticSpace K V} {M : Lattice K V}
    (a : GoodBONG Q M m) (h : m = length) (i : Fin length) :
    (a.castLength h).toBONG.ambientVector i =
      a.toBONG.ambientVector ⟨i.val, by omega⟩ := by
  subst length
  rfl

/-- The one-dimensional line generated by `x_(s+1)` lies in the right
segment beginning with that same vector. -/
theorem lemma714TypeIILineCarrier_le_right
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2
      (lemma714TypeIIReframing_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (U : (b.lemma714Tail S).toBONG.TwoBlockSplitWitness
      (s - 2) (by omega)) :
    (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier ≤
      U.right.carrier := by
  rw [(b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier_eq_segmentCarrier,
    U.right.carrier_eq_segmentCarrier]
  unfold BONG.segmentCarrier
  apply Submodule.span_mono
  rintro z ⟨i, rfl⟩
  let j : Fin ((n + 1) - (s - 2)) := ⟨i.val, by omega⟩
  refine ⟨j, ?_⟩
  apply congrArg (b.lemma714Tail S).toBONG.ambientVector
  apply Fin.ext
  simp only [BONG.segmentVector, BONG.segmentIndex_val, j]

/-- Regard a vector on the exceptional coordinate line as a vector of the
right segment whose head is that line. -/
noncomputable def lemma714TypeIILineToRight
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2
      (lemma714TypeIIReframing_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (U : (b.lemma714Tail S).toBONG.TwoBlockSplitWitness
      (s - 2) (by omega))
    (z : (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier) :
    U.right.carrier :=
  ⟨(z : S.right.carrier),
    b.lemma714TypeIILineCarrier_le_right S s hsTwo hsCurrent U z.property⟩

@[simp]
theorem lemma714TypeIILineToRight_coe
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2
      (lemma714TypeIIReframing_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (U : (b.lemma714Tail S).toBONG.TwoBlockSplitWitness
      (s - 2) (by omega))
    (z : (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier) :
    ((b.lemma714TypeIILineToRight S s hsTwo hsCurrent U z :
        U.right.carrier) : S.right.carrier) = z :=
  rfl

/-- The frame isometry sends a retained selected-prefix vector to the left
coordinate of the first Lemma-7.10 factor. -/
@[simp]
theorem lemma714TypeIIFrameIsometry_apply_prefix
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2
      (lemma714TypeIIReframing_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsBound : s ≤ n + 3)
    (U : (b.lemma714Tail S).toBONG.TwoBlockSplitWitness
      (s - 2) (by omega)) (i : Fin (s - 2)) :
    (b.lemma714TypeIIFrameIsometry S s hsTwo hsBound U).toLinearEquiv
        ((b.lemma714Tail S).toBONG.ambientVector
          ⟨i.val, by omega⟩, 0) =
      (((b.lemma714TypeIISelectedPrefix S s hsTwo hsBound U).toBONG.ambientVector i,
          0), 0) := by
  rw [b.lemma714TypeIIFrameIsometry_apply S s hsTwo hsBound U]
  have hvector :
      (((U.left.bong.ambientVector i : U.left.carrier) : S.right.carrier)) =
        (b.lemma714Tail S).toBONG.ambientVector ⟨i.val, by omega⟩ := by
    simpa only [Nat.zero_add] using U.left.ambientVector_eq i
  rw [← hvector, U.toProductLatticeIsometry_symm_apply_left]
  rfl

/-- The frame isometry sends an exceptional block vector to the binary part
of the first factor and the head line of the right factor. -/
@[simp]
theorem lemma714TypeIIFrameIsometry_apply_block
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2
      (lemma714TypeIIReframing_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (U : (b.lemma714Tail S).toBONG.TwoBlockSplitWitness
      (s - 2) (by omega))
    (z : S.left.carrier ×
      (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier) :
    (b.lemma714TypeIIFrameIsometry S s hsTwo (le_of_lt hsCurrent) U).toLinearEquiv
        (b.lemma714TypeIIEmbedBlockVector S s hsTwo hsCurrent z) =
      ((0, z.1), b.lemma714TypeIILineToRight S s hsTwo hsCurrent U z.2) := by
  rw [b.lemma714TypeIIFrameIsometry_apply S s hsTwo
    (le_of_lt hsCurrent) U]
  change
    (((U.toProductLatticeIsometry.symm.toLinearEquiv
        ((b.lemma714TypeIILineToRight S s hsTwo hsCurrent U z.2 :
          U.right.carrier) : S.right.carrier)).1, z.1),
      (U.toProductLatticeIsometry.symm.toLinearEquiv
        ((b.lemma714TypeIILineToRight S s hsTwo hsCurrent U z.2 :
          U.right.carrier) : S.right.carrier)).2) = _
  rw [U.toProductLatticeIsometry_symm_apply_right]

/-- The frame isometry sends a retained suffix vector to the right factor. -/
@[simp]
theorem lemma714TypeIIFrameIsometry_apply_suffix
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2
      (lemma714TypeIIReframing_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (U : (b.lemma714Tail S).toBONG.TwoBlockSplitWitness
      (s - 2) (by omega)) (j : Fin (n + 3 - s)) :
    (b.lemma714TypeIIFrameIsometry S s hsTwo (le_of_lt hsCurrent) U).toLinearEquiv
        ((b.lemma714Tail S).toBONG.ambientVector
          ⟨s - 2 + j.val, by omega⟩, 0) =
      ((0, 0),
        (b.lemma714TypeIIRightSuffix S s hsTwo hsCurrent U).toBONG.ambientVector j) := by
  rw [b.lemma714TypeIIFrameIsometry_apply S s hsTwo
    (le_of_lt hsCurrent) U]
  let jRaw : Fin ((n + 1) - (s - 2)) := ⟨j.val, by omega⟩
  have hvector := U.right.ambientVector_eq jRaw
  change
    (((U.right.bong.ambientVector jRaw : U.right.carrier) : S.right.carrier)) =
      (b.lemma714Tail S).toBONG.ambientVector
        ⟨s - 2 + j.val, by omega⟩ at hvector
  rw [← hvector, U.toProductLatticeIsometry_symm_apply_right]
  rw [lemma714TypeIIRightSuffix,
    lemma714TypeIIReframing_ambientVector_castLength]
  rfl

/-- The candidate after transport into the exact factor order used by
Lemma 7.10. -/
noncomputable def lemma714TypeIIReframedTarget
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2
      (lemma714TypeIIReframing_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsBound : s ≤ n + 3)
    (U : (b.lemma714Tail S).toBONG.TwoBlockSplitWitness
      (s - 2) (by omega))
    {N : Lattice K (S.right.carrier × S.left.carrier)}
    (target : GoodBONG
      ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
        (q.restrict S.left.carrier S.left.nondegenerate)) N (n + 3)) :
    GoodBONG
      ((((q.restrict S.right.carrier S.right.nondegenerate).restrict
          U.left.carrier U.left.nondegenerate).orthogonalSum
        (q.restrict S.left.carrier S.left.nondegenerate)).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          U.right.carrier U.right.nondegenerate))
      (Lattice.map
        (b.lemma714TypeIIFrameIsometry S s hsTwo hsBound U).toLinearEquiv N)
      (n + 3) :=
  target.map
    (b.lemma714TypeIIFrameIsometry S s hsTwo hsBound U).toQuadraticSpaceIsometry

/-- Reframing carries every candidate vector through the concrete frame
isometry. -/
@[simp]
theorem lemma714TypeIIReframedTarget_ambientVector
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2
      (lemma714TypeIIReframing_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsBound : s ≤ n + 3)
    (U : (b.lemma714Tail S).toBONG.TwoBlockSplitWitness
      (s - 2) (by omega))
    {N : Lattice K (S.right.carrier × S.left.carrier)}
    (target : GoodBONG
      ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
        (q.restrict S.left.carrier S.left.nondegenerate)) N (n + 3))
    (i : Fin (n + 3)) :
    (b.lemma714TypeIIReframedTarget S s hsTwo hsBound U target).toBONG.ambientVector i =
      (b.lemma714TypeIIFrameIsometry S s hsTwo hsBound U).toLinearEquiv
        (target.toBONG.ambientVector i) := by
  change
    (target.toBONG.map
      (b.lemma714TypeIIFrameIsometry S s hsTwo hsBound U).toQuadraticSpaceIsometry).ambientVector
        i = _
  exact BONG.ambientVector_map _ _ _

/-- The unchanged vectors `x_3,...,x_s` form the literal left prefix of the
reframed candidate. -/
@[simp]
theorem lemma714TypeIIReframedTarget_ambientVector_prefix
    [DyadicDiscriminantClassLaws K]
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2
      (lemma714TypeIIReframing_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (U : (b.lemma714Tail S).toBONG.TwoBlockSplitWitness
      (s - 2) (by omega))
    (block : GoodBONG
      ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).nondegenerate))
      (Lattice.product
        (Lattice.rescale (uniformizerUnit K) S.left.lattice)
        (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).lattice) 3)
    {N : Lattice K (S.right.carrier × S.left.carrier)}
    (target : GoodBONG
      ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
        (q.restrict S.left.carrier S.left.nondegenerate)) N (n + 3))
    (htargetVectors : ∀ i, target.toBONG.ambientVector i =
      lemma714TypeIITargetVector b S s hsTwo hsCurrent block i)
    (i : Fin (s - 2)) :
    (b.lemma714TypeIIReframedTarget S s hsTwo (le_of_lt hsCurrent) U target).toBONG.ambientVector
        ⟨i.val, by omega⟩ =
      (((b.lemma714TypeIISelectedPrefix S s hsTwo (le_of_lt hsCurrent) U).toBONG.ambientVector
          i, 0), 0) := by
  rw [b.lemma714TypeIIReframedTarget_ambientVector S s hsTwo
    (le_of_lt hsCurrent) U target, htargetVectors,
    b.lemma714TypeIITargetVector_prefix S s hsTwo hsCurrent block
      (⟨i.val, by omega⟩ : Fin (n + 3)) i.isLt]
  exact b.lemma714TypeIIFrameIsometry_apply_prefix S s hsTwo
    (le_of_lt hsCurrent) U i

/-- The first vector of the exceptional ternary block has the literal
`pi J`--line coordinates in the Lemma-7.10 frame. -/
@[simp]
theorem lemma714TypeIIReframedTarget_ambientVector_block_zero
    [DyadicDiscriminantClassLaws K]
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2
      (lemma714TypeIIReframing_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (U : (b.lemma714Tail S).toBONG.TwoBlockSplitWitness
      (s - 2) (by omega))
    (block : GoodBONG
      ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).nondegenerate))
      (Lattice.product
        (Lattice.rescale (uniformizerUnit K) S.left.lattice)
        (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).lattice) 3)
    {N : Lattice K (S.right.carrier × S.left.carrier)}
    (target : GoodBONG
      ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
        (q.restrict S.left.carrier S.left.nondegenerate)) N (n + 3))
    (htargetVectors : ∀ i, target.toBONG.ambientVector i =
      lemma714TypeIITargetVector b S s hsTwo hsCurrent block i) :
    (b.lemma714TypeIIReframedTarget S s hsTwo (le_of_lt hsCurrent) U target).toBONG.ambientVector
        ⟨s - 2, by omega⟩ =
      ((0, (block.toBONG.ambientVector 0).1),
        b.lemma714TypeIILineToRight S s hsTwo hsCurrent U
          (block.toBONG.ambientVector 0).2) := by
  rw [b.lemma714TypeIIReframedTarget_ambientVector S s hsTwo
    (le_of_lt hsCurrent) U target, htargetVectors,
    b.lemma714TypeIITargetVector_zero S s hsTwo hsCurrent block]
  exact b.lemma714TypeIIFrameIsometry_apply_block S s hsTwo hsCurrent U
    (block.toBONG.ambientVector 0)

/-- The middle vector of the exceptional ternary block has the literal
`pi J`--line coordinates in the Lemma-7.10 frame. -/
@[simp]
theorem lemma714TypeIIReframedTarget_ambientVector_block_one
    [DyadicDiscriminantClassLaws K]
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2
      (lemma714TypeIIReframing_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (U : (b.lemma714Tail S).toBONG.TwoBlockSplitWitness
      (s - 2) (by omega))
    (block : GoodBONG
      ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).nondegenerate))
      (Lattice.product
        (Lattice.rescale (uniformizerUnit K) S.left.lattice)
        (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).lattice) 3)
    {N : Lattice K (S.right.carrier × S.left.carrier)}
    (target : GoodBONG
      ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
        (q.restrict S.left.carrier S.left.nondegenerate)) N (n + 3))
    (htargetVectors : ∀ i, target.toBONG.ambientVector i =
      lemma714TypeIITargetVector b S s hsTwo hsCurrent block i) :
    (b.lemma714TypeIIReframedTarget S s hsTwo (le_of_lt hsCurrent) U target).toBONG.ambientVector
        ⟨s - 1, by omega⟩ =
      ((0, (block.toBONG.ambientVector 1).1),
        b.lemma714TypeIILineToRight S s hsTwo hsCurrent U
          (block.toBONG.ambientVector 1).2) := by
  rw [b.lemma714TypeIIReframedTarget_ambientVector S s hsTwo
    (le_of_lt hsCurrent) U target, htargetVectors,
    b.lemma714TypeIITargetVector_one S s hsTwo hsCurrent block]
  exact b.lemma714TypeIIFrameIsometry_apply_block S s hsTwo hsCurrent U
    (block.toBONG.ambientVector 1)

/-- The last vector of the exceptional ternary block has the literal
`pi J`--line coordinates in the Lemma-7.10 frame. -/
@[simp]
theorem lemma714TypeIIReframedTarget_ambientVector_block_two
    [DyadicDiscriminantClassLaws K]
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2
      (lemma714TypeIIReframing_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (U : (b.lemma714Tail S).toBONG.TwoBlockSplitWitness
      (s - 2) (by omega))
    (block : GoodBONG
      ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).nondegenerate))
      (Lattice.product
        (Lattice.rescale (uniformizerUnit K) S.left.lattice)
        (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).lattice) 3)
    {N : Lattice K (S.right.carrier × S.left.carrier)}
    (target : GoodBONG
      ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
        (q.restrict S.left.carrier S.left.nondegenerate)) N (n + 3))
    (htargetVectors : ∀ i, target.toBONG.ambientVector i =
      lemma714TypeIITargetVector b S s hsTwo hsCurrent block i) :
    (b.lemma714TypeIIReframedTarget S s hsTwo (le_of_lt hsCurrent) U target).toBONG.ambientVector
        ⟨s, hsCurrent⟩ =
      ((0, (block.toBONG.ambientVector 2).1),
        b.lemma714TypeIILineToRight S s hsTwo hsCurrent U
          (block.toBONG.ambientVector 2).2) := by
  rw [b.lemma714TypeIIReframedTarget_ambientVector S s hsTwo
    (le_of_lt hsCurrent) U target, htargetVectors,
    b.lemma714TypeIITargetVector_two S s hsTwo hsCurrent block]
  exact b.lemma714TypeIIFrameIsometry_apply_block S s hsTwo hsCurrent U
    (block.toBONG.ambientVector 2)

/-- After the exceptional ternary block, the candidate retains
`x_(s+2),...,x_N` as the tail of the right Lemma-7.10 factor. -/
@[simp]
theorem lemma714TypeIIReframedTarget_ambientVector_suffix
    [DyadicDiscriminantClassLaws K]
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2
      (lemma714TypeIIReframing_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (U : (b.lemma714Tail S).toBONG.TwoBlockSplitWitness
      (s - 2) (by omega))
    (block : GoodBONG
      ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).nondegenerate))
      (Lattice.product
        (Lattice.rescale (uniformizerUnit K) S.left.lattice)
        (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).lattice) 3)
    {N : Lattice K (S.right.carrier × S.left.carrier)}
    (target : GoodBONG
      ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
        (q.restrict S.left.carrier S.left.nondegenerate)) N (n + 3))
    (htargetVectors : ∀ i, target.toBONG.ambientVector i =
      lemma714TypeIITargetVector b S s hsTwo hsCurrent block i)
    (j : Fin (n + 2 - s)) :
    (b.lemma714TypeIIReframedTarget S s hsTwo (le_of_lt hsCurrent) U target).toBONG.ambientVector
        ⟨s + 1 + j.val, by omega⟩ =
      ((0, 0),
        (b.lemma714TypeIIRightSuffix S s hsTwo hsCurrent U).toBONG.ambientVector
          ⟨j.val + 1, by omega⟩) := by
  rw [b.lemma714TypeIIReframedTarget_ambientVector S s hsTwo
    (le_of_lt hsCurrent) U target, htargetVectors,
    b.lemma714TypeIITargetVector_suffix S s hsTwo hsCurrent block
      (⟨s + 1 + j.val, by omega⟩ : Fin (n + 3))
      (show s < s + 1 + j.val by omega)]
  let jRight : Fin (n + 3 - s) := ⟨j.val + 1, by omega⟩
  have htailIndex :
      (⟨(s + 1 + j.val) - 2, by omega⟩ : Fin (n + 1)) =
        ⟨s - 2 + jRight.val, by omega⟩ := by
    apply Fin.ext
    dsimp only [jRight]
    omega
  rw [htailIndex]
  exact b.lemma714TypeIIFrameIsometry_apply_suffix S s hsTwo hsCurrent U jRight

end BONG.GoodBONG

end Bong
