/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.Beli2009WeightIdealProof
import Bong.Bong.BeliLemma317
import Bong.Bong.DefectArithmetic
import Bong.Dyadic.UnitDefectClassification
import Bong.Lattice.OrthogonalDecompositionIdeals

/-!
# Beli (2009/2010), Lemma 2.11

This file proves the norm-group and weight-ideal formulas for a finite
orthogonal decomposition.  The first part is the basis-free norm-group
calculation; the remaining part supplies the local diagonal weight formula
quoted by Beli from O'Meara, p. 280.
-/

namespace Bong

open Dyadic

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]

namespace Lattice

/-- Multiplication by a nonzero scalar sends a principal fractional ideal to
the principal ideal generated by the product. -/
theorem scalarIdeal_principalIdeal_units (a b : Kˣ) :
    scalarIdeal (a : K) (principalIdeal (K := K) (b : K)) =
      principalIdeal (K := K) ((a * b : Kˣ) : K) := by
  rw [scalarIdeal, principalIdeal, Submodule.map_span]
  change Submodule.span (IntegerRing K)
      (coefficientMulLinearMap (K := K) (a : K) '' {(b : K)}) =
    Submodule.span (IntegerRing K) {((a : K) * (b : K))}
  rw [Set.image_singleton]
  change Submodule.span (IntegerRing K)
      {coefficientMulLinearMap (K := K) (a : K) (b : K)} = _
  rw [coefficientMulLinearMap_apply]

/-- Multiplication by a nonzero scalar shifts the exponent of a power ideal
by the scalar's valuation. -/
theorem scalarIdeal_powerIdeal_units (a : Kˣ) (r : Int) :
    scalarIdeal (a : K) (powerIdeal (K := K) r) =
      powerIdeal (K := K) (ordUnit K a + r) := by
  rw [powerIdeal, scalarIdeal_principalIdeal_units,
    principalIdeal_eq_powerIdeal]
  congr 2
  rw [ordUnit_mul, ordUnit_uniformizerPowerUnit]

/-- The supremum of two fractional power ideals is governed by the smaller
of their two exponents. -/
theorem sup_powerIdeal (r s : Int) :
    powerIdeal (K := K) r ⊔ powerIdeal (K := K) s =
      powerIdeal (K := K) (min r s) := by
  by_cases hrs : r ≤ s
  · rw [min_eq_left hrs, sup_eq_left]
    exact (powerIdeal_le_iff s r).2 hrs
  · have hsr : s ≤ r := le_of_not_ge hrs
    rw [min_eq_right hsr, sup_eq_right]
    exact (powerIdeal_le_iff r s).2 hsr

/-- The ideal `2aO` has exponent `ord(a)+e`. -/
theorem twicePrincipalIdeal_eq_powerIdeal (a : Kˣ) :
    twiceIdeal (principalIdeal (K := K) (a : K)) =
      powerIdeal (K := K) (ordUnit K a + ramificationIndex K) := by
  rw [principalIdeal_eq_powerIdeal, twiceIdeal_powerIdeal]

/-- Multiplication by two is monotone on coefficient ideals. -/
theorem twiceIdeal_mono {I J : CoefficientIdeal (K := K)} (hIJ : I ≤ J) :
    twiceIdeal I ≤ twiceIdeal J := by
  exact Submodule.map_mono hIJ

/-- Away from the square case, `a⁻¹ d(ab)` has the absolute order
`ord(b)+d(ab)`. -/
theorem scaledQuadraticDefectIdeal_eq_powerIdeal_of_ne_top
    (a b : Kˣ) (hfinite : quadraticDefect K (a * b) ≠ ⊤) :
    scalarIdeal ((a⁻¹ : Kˣ) : K) (quadraticDefectIdeal (a * b)) =
      powerIdeal (K := K)
        (ordUnit K b + (quadraticDefect K (a * b)).toNat) := by
  rw [quadraticDefectIdeal, if_neg hfinite,
    scalarIdeal_powerIdeal_units]
  congr 1
  rw [ordUnit_inv, ordUnit_mul]
  rw [Int.ofNat_eq_coe]
  push_cast
  omega

/-- In the square case the absolute quadratic-defect ideal is zero. -/
theorem scaledQuadraticDefectIdeal_eq_bot_of_eq_top
    (a b : Kˣ) (htop : quadraticDefect K (a * b) = ⊤) :
    scalarIdeal ((a⁻¹ : Kˣ) : K) (quadraticDefectIdeal (a * b)) =
      ⊥ := by
  simp [quadraticDefectIdeal, htop, scalarIdeal]

/-! ## O'Meara's diagonal weight calculation (p. 280) -/

/-- Integral values of the binary diagonal form `⟨a,b⟩`, enlarged by
`2aO`.  The hypothesis used below will ensure `bO ⊆ aO`. -/
def binaryDiagonalNormSet (a b : Kˣ) : Set K :=
  {z | ∃ c d : IntegerRing K,
    ∃ y ∈ twiceIdeal (principalIdeal (K := K) (a : K)),
      z = (a : K) * (c : K) ^ 2 +
        (b : K) * (d : K) ^ 2 + y}

/-- Zero belongs to the enlarged binary diagonal value set. -/
theorem zero_mem_binaryDiagonalNormSet (a b : Kˣ) :
    (0 : K) ∈ binaryDiagonalNormSet a b := by
  refine ⟨0, 0, 0, Submodule.zero_mem _, ?_⟩
  simp

/-- The error ideal `2aO` belongs to the enlarged binary value set. -/
theorem twicePrincipalIdeal_subset_binaryDiagonalNormSet (a b : Kˣ) :
    (twiceIdeal (principalIdeal (K := K) (a : K)) : Set K) ⊆
      binaryDiagonalNormSet a b := by
  intro y hy
  exact ⟨0, 0, y, hy, by simp⟩

/-- An integral square multiple of the first diagonal coefficient belongs to
the enlarged binary value set. -/
theorem firstSquare_mem_binaryDiagonalNormSet
    (a b : Kˣ) (c : IntegerRing K) :
    (a : K) * (c : K) ^ 2 ∈ binaryDiagonalNormSet a b := by
  exact ⟨c, 0, 0, Submodule.zero_mem _, by simp⟩

/-- An integral square multiple of the second diagonal coefficient belongs
to the enlarged binary value set. -/
theorem secondSquare_mem_binaryDiagonalNormSet
    (a b : Kˣ) (d : IntegerRing K) :
    (b : K) * (d : K) ^ 2 ∈ binaryDiagonalNormSet a b := by
  exact ⟨0, d, 0, Submodule.zero_mem _, by simp⟩

/-- Multiplying an element of `aO` by two puts it in `2aO`. -/
private theorem two_mul_mem_twicePrincipalIdeal
    (a : Kˣ) {z : K} (hz : z ∈ principalIdeal (K := K) (a : K)) :
    (2 : K) * z ∈ twiceIdeal (principalIdeal (K := K) (a : K)) := by
  exact ⟨z, hz, rfl⟩

/-- If `bO ⊆ aO`, the enlarged binary diagonal value set is additive. -/
theorem add_mem_binaryDiagonalNormSet
    (a b : Kˣ)
    (hba : principalIdeal (K := K) (b : K) ≤
      principalIdeal (K := K) (a : K))
    {z w : K} (hz : z ∈ binaryDiagonalNormSet a b)
    (hw : w ∈ binaryDiagonalNormSet a b) :
    z + w ∈ binaryDiagonalNormSet a b := by
  rcases hz with ⟨c, d, y, hy, rfl⟩
  rcases hw with ⟨c', d', y', hy', rfl⟩
  have hacc' : (a : K) * (c : K) * (c' : K) ∈
      principalIdeal (K := K) (a : K) := by
    have h := mul_mem_principalIdeal_of_mem_integerRing
      (K := K) (a : K) ((c : K) * (c' : K)) (c * c').property
    simpa only [mul_assoc] using h
  have hbdd' : (b : K) * (d : K) * (d' : K) ∈
      principalIdeal (K := K) (a : K) := by
    have hb : (b : K) ∈ principalIdeal (K := K) (a : K) :=
      hba (generator_mem_principalIdeal (b : K))
    have hsmul := (principalIdeal (K := K) (a : K)).smul_mem (d * d') hb
    change ((d * d' : IntegerRing K) : K) * (b : K) ∈
      principalIdeal (K := K) (a : K) at hsmul
    have hdd' : ((d * d' : IntegerRing K) : K) =
        (d : K) * (d' : K) := by
      exact map_mul (algebraMap (IntegerRing K) K) d d'
    rw [hdd'] at hsmul
    simpa only [mul_assoc, mul_comm, mul_left_comm] using hsmul
  have hcrossA : (2 : K) * ((a : K) * (c : K) * (c' : K)) ∈
      twiceIdeal (principalIdeal (K := K) (a : K)) :=
    two_mul_mem_twicePrincipalIdeal a hacc'
  have hcrossB : (2 : K) * ((b : K) * (d : K) * (d' : K)) ∈
      twiceIdeal (principalIdeal (K := K) (a : K)) :=
    two_mul_mem_twicePrincipalIdeal a hbdd'
  let error : K := y + y' -
    (2 : K) * ((a : K) * (c : K) * (c' : K)) -
    (2 : K) * ((b : K) * (d : K) * (d' : K))
  have herror : error ∈
      twiceIdeal (principalIdeal (K := K) (a : K)) := by
    exact (twiceIdeal (principalIdeal (K := K) (a : K))).sub_mem
      ((twiceIdeal (principalIdeal (K := K) (a : K))).sub_mem
        ((twiceIdeal (principalIdeal (K := K) (a : K))).add_mem hy hy')
        hcrossA) hcrossB
  refine ⟨c + c', d + d', error, herror, ?_⟩
  have hcadd : ((c + c' : IntegerRing K) : K) =
      (c : K) + (c' : K) := by
    exact map_add (algebraMap (IntegerRing K) K) c c'
  have hdadd : ((d + d' : IntegerRing K) : K) =
      (d : K) + (d' : K) := by
    exact map_add (algebraMap (IntegerRing K) K) d d'
  change
    (a : K) * (c : K) ^ 2 + (b : K) * (d : K) ^ 2 + y +
      ((a : K) * (c' : K) ^ 2 + (b : K) * (d' : K) ^ 2 + y') =
    (a : K) * ((c + c' : IntegerRing K) : K) ^ 2 +
      (b : K) * ((d + d' : IntegerRing K) : K) ^ 2 + error
  rw [hcadd, hdadd]
  dsimp only [error]
  ring

/-- Multiplication by an integral square preserves the enlarged binary
diagonal value set. -/
theorem integralSquare_mul_mem_binaryDiagonalNormSet
    (a b : Kˣ) {z : K} (hz : z ∈ binaryDiagonalNormSet a b)
    (r : IntegerRing K) :
    (r : K) ^ 2 * z ∈ binaryDiagonalNormSet a b := by
  rcases hz with ⟨c, d, y, hy, rfl⟩
  refine ⟨r * c, r * d, (r : K) ^ 2 * y, ?_, ?_⟩
  · rcases hy with ⟨w, hw, hwy⟩
    refine ⟨(r : K) ^ 2 * w, ?_, ?_⟩
    · have hsmul := (principalIdeal (K := K) (a : K)).smul_mem
          (r ^ 2) hw
      change ((r ^ 2 : IntegerRing K) : K) * w ∈
        principalIdeal (K := K) (a : K) at hsmul
      have hrSq : ((r ^ 2 : IntegerRing K) : K) = (r : K) ^ 2 := by
        exact map_pow (algebraMap (IntegerRing K) K) r 2
      rwa [hrSq] at hsmul
    · change (2 : K) * ((r : K) ^ 2 * w) = (r : K) ^ 2 * y
      rw [← hwy]
      rw [twoMulLinearMap_apply, Algebra.smul_def]
      have htwo : ((2 : IntegerRing K) : K) = (2 : K) := rfl
      change (2 : K) * ((r : K) ^ 2 * w) =
        (r : K) ^ 2 * (((2 : IntegerRing K) : K) * w)
      rw [htwo]
      ring
  · have hrc : ((r * c : IntegerRing K) : K) =
        (r : K) * (c : K) :=
      map_mul (algebraMap (IntegerRing K) K) r c
    have hrd : ((r * d : IntegerRing K) : K) =
        (r : K) * (d : K) :=
      map_mul (algebraMap (IntegerRing K) K) r d
    rw [hrc, hrd]
    ring

/-- If the scaled defect ideal lies strictly above `2aO`, its exponent has
parity opposite to `ord(a)`.  This is the parity calculation in the final
paragraph of Beli's proof of Lemma 2.11. -/
theorem odd_normOrder_add_scaledDefectOrder_of_lt
    (a b : Kˣ) (hab : ordUnit K a ≤ ordUnit K b)
    (hfinite : quadraticDefect K (a * b) ≠ ⊤)
    (hlt : ordUnit K b + (quadraticDefect K (a * b)).toNat <
      ordUnit K a + ramificationIndex K) :
    Odd (ordUnit K a +
      (ordUnit K b + (quadraticDefect K (a * b)).toNat)) := by
  let d : Nat := (quadraticDefect K (a * b)).toNat
  rcases Int.even_or_odd (ordUnit K (a * b)) with heven | hodd
  · rcases heven with ⟨k, hk⟩
    let s : Kˣ := uniformizerPowerUnit K k
    let unitPart : Kˣ := (a * b) / s ^ 2
    have hsOrder : ordUnit K s = k := by
      exact ordUnit_uniformizerPowerUnit k
    have hunitOrder : ordUnit K unitPart = 0 := by
      dsimp only [unitPart]
      rw [div_eq_mul_inv, ordUnit_mul, ordUnit_inv,
        ordUnit_pow, hsOrder]
      omega
    have hunit : IsValuationUnit K (unitPart : K) :=
      (isValuationUnit_iff_ordUnit_eq_zero K unitPart).2 hunitOrder
    have hfactor : unitPart * s ^ 2 = a * b := by
      dsimp only [unitPart]
      exact div_mul_cancel (a * b) (s ^ 2)
    have hdefect : quadraticDefect K unitPart =
        quadraticDefect K (a * b) := by
      have h := quadraticDefect_mul_square K unitPart s
      rw [hfactor] at h
      exact h.symm
    have hdLtInt : (d : Int) <
        2 * (ramificationIndex K : Int) := by
      dsimp only [d]
      have hePos := ramificationIndex_pos K
      omega
    have hdLtNat : d < 2 * ramificationIndex K := by
      exact_mod_cast hdLtInt
    have hdefectLt : quadraticDefect K unitPart <
        ((2 * ramificationIndex K : Nat) : ℕ∞) := by
      rw [hdefect, ← ENat.coe_toNat hfinite]
      exact_mod_cast hdLtNat
    have hdOdd : Odd d := by
      have h := quadraticDefect_toNat_odd_of_unit_of_lt_two_mul_e
        (K := K) unitPart hunit hdefectLt
      simpa only [hdefect, d] using h
    rcases hdOdd with ⟨m, hm⟩
    have hmInt : (d : Int) = 2 * (m : Int) + 1 := by
      exact_mod_cast hm
    refine ⟨k + (m : Int), ?_⟩
    rw [ordUnit_mul] at hk
    dsimp only [d] at hmInt ⊢
    omega
  · have hzero := quadraticDefect_eq_zero_of_odd_ordUnit
      (K := K) (a * b) hodd
    have hdZero : d = 0 := by
      dsimp only [d]
      rw [hzero]
      rfl
    simpa only [d, hdZero, Nat.cast_zero, add_zero, ordUnit_mul]
      using hodd

/-- For finite defect, the enlarged binary diagonal value set contains a
nonzero value whose order is the absolute defect order
`ord(b)+d(ab)`. -/
theorem exists_binaryDefectGenerator
    (a b : Kˣ) (hab : ordUnit K a ≤ ordUnit K b)
    (hfinite : quadraticDefect K (a * b) ≠ ⊤) :
    ∃ e : Kˣ,
      ordUnit K e = ordUnit K b +
        (quadraticDefect K (a * b)).toNat ∧
      (e : K) ∈ binaryDiagonalNormSet a b := by
  let d : Nat := (quadraticDefect K (a * b)).toNat
  by_cases hdZero : d = 0
  · refine ⟨b, ?_, ?_⟩
    · simp [d, hdZero]
    · simpa using secondSquare_mem_binaryDiagonalNormSet a b 1
  · have hdPos : 0 < d := Nat.pos_of_ne_zero hdZero
    let r : Kˣ := b / a
    have hrDefect : quadraticDefect K r = quadraticDefect K (a * b) := by
      have h := quadraticDefect_mul_square K (a * b) a⁻¹
      have hunit : (a * b) * a⁻¹ ^ 2 = r := by
        apply Units.ext
        dsimp only [r]
        simp only [Units.val_mul, Units.val_pow_eq_pow_val,
          Units.val_inv_eq_inv_val, Units.val_div_eq_div_val]
        field_simp [Units.ne_zero a, Units.ne_zero b]
      rw [hunit] at h
      exact h
    have hrFinite : quadraticDefect K r ≠ ⊤ := by
      rw [hrDefect]
      exact hfinite
    rcases BONG.exists_quadraticApproximation_exact_order r hrFinite with
      ⟨x, hxOrder⟩
    have hxOrder' : ord K (1 - x ^ 2 / (r : K)) =
        ((d : Int) : WithTop Int) := by
      simpa only [d, hrDefect] using hxOrder
    have herrorPos : 0 < ord K (1 - x ^ 2 / (r : K)) := by
      rw [hxOrder']
      exact_mod_cast hdPos
    have hquotOrder : ord K (x ^ 2 / (r : K)) = 0 := by
      have hlt : ord K (1 : K) < ord K (1 - x ^ 2 / (r : K)) := by
        simpa only [ord_one] using herrorPos
      have hsub := (ord K).map_sub_eq_of_lt_left hlt
      have heq : 1 - (1 - x ^ 2 / (r : K)) = x ^ 2 / (r : K) := by
        ring
      rw [heq] at hsub
      simpa only [ord_one] using hsub
    have hxNe : x ≠ 0 := by
      intro hxZero
      subst x
      simp at hquotOrder
    let xu : Kˣ := Units.mk0 x hxNe
    have hrOrder : ordUnit K r = ordUnit K b - ordUnit K a := by
      dsimp only [r]
      rw [div_eq_mul_inv, ordUnit_mul, ordUnit_inv]
      ring
    have hxuOrder : 2 * ordUnit K xu = ordUnit K r := by
      have hquotUnitOrder : ordUnit K (xu ^ 2 / r) = 0 := by
        apply WithTop.coe_injective
        rw [coe_ordUnit]
        have hval : ((xu ^ 2 / r : Kˣ) : K) =
            x ^ 2 / (r : K) := by
          rw [Units.val_div_eq_div_val, Units.val_pow_eq_pow_val]
          rfl
        rw [hval]
        simpa using hquotOrder
      rw [div_eq_mul_inv, ordUnit_mul, ordUnit_inv,
        ordUnit_pow] at hquotUnitOrder
      omega
    have hxuNonneg : 0 ≤ ordUnit K xu := by
      rw [hrOrder] at hxuOrder
      omega
    have hxIntegral : Dyadic.IsIntegral K x := by
      have hxOrderField : ord K x =
          (ordUnit K xu : WithTop Int) := by
        have hxuVal : (xu : K) = x := rfl
        rw [← hxuVal]
        exact (coe_ordUnit K xu).symm
      rw [Dyadic.IsIntegral, hxOrderField]
      exact_mod_cast hxuNonneg
    let c : IntegerRing K :=
      ⟨x, (mem_integerRing_iff K).2 hxIntegral⟩
    let error : K := (b : K) - (a : K) * x ^ 2
    have herrorFactor : error =
        (b : K) * (1 - x ^ 2 / (r : K)) := by
      dsimp only [error, r]
      simp only [Units.val_div_eq_div_val]
      field_simp [Units.ne_zero a, Units.ne_zero b]
    have herrorOrder : ord K error =
        ((ordUnit K b + (d : Int) : Int) : WithTop Int) := by
      rw [herrorFactor, ord_mul, ← coe_ordUnit, hxOrder']
      push_cast
      ring
    have herrorNe : error ≠ 0 := by
      intro hzero
      rw [hzero, ord_zero] at herrorOrder
      exact WithTop.top_ne_coe herrorOrder
    let e : Kˣ := Units.mk0 error herrorNe
    have heOrder : ordUnit K e = ordUnit K b + d := by
      apply WithTop.coe_injective
      rw [coe_ordUnit]
      change ord K error = _
      exact herrorOrder
    have hacSq : (a : K) * (c : K) ^ 2 ∈
        principalIdeal (K := K) (a : K) := by
      have h := mul_mem_principalIdeal_of_mem_integerRing
        (K := K) (a : K) ((c : K) ^ 2) (c ^ 2).property
      exact h
    have htwo : (2 : K) * ((a : K) * (c : K) ^ 2) ∈
        twiceIdeal (principalIdeal (K := K) (a : K)) :=
      two_mul_mem_twicePrincipalIdeal a hacSq
    have heMem : (e : K) ∈ binaryDiagonalNormSet a b := by
      refine ⟨c, 1, -((2 : K) * ((a : K) * (c : K) ^ 2)),
        (twiceIdeal (principalIdeal (K := K) (a : K))).neg_mem htwo, ?_⟩
      change error =
        (a : K) * (c : K) ^ 2 +
          (b : K) * (((1 : IntegerRing K) : K)) ^ 2 +
            -((2 : K) * ((a : K) * (c : K) ^ 2))
      have hone : (((1 : IntegerRing K) : K)) = 1 :=
        map_one (algebraMap (IntegerRing K) K)
      rw [hone]
      dsimp only [error, c]
      ring
    exact ⟨e, by simpa only [d] using heOrder, heMem⟩

/-- The scaled absolute defect ideal is generated, modulo `2aO`, by integral
values of the binary diagonal form `⟨a,b⟩`. -/
theorem scaledQuadraticDefectIdeal_subset_binaryDiagonalNormSet
    (a b : Kˣ) (hab : ordUnit K a ≤ ordUnit K b) :
    (scalarIdeal ((a⁻¹ : Kˣ) : K)
      (quadraticDefectIdeal (a * b)) : Set K) ⊆
      binaryDiagonalNormSet a b := by
  have hba : principalIdeal (K := K) (b : K) ≤
      principalIdeal (K := K) (a : K) := by
    rw [principalIdeal_eq_powerIdeal, principalIdeal_eq_powerIdeal]
    exact (powerIdeal_le_iff _ _).2 hab
  by_cases htop : quadraticDefect K (a * b) = ⊤
  · rw [scaledQuadraticDefectIdeal_eq_bot_of_eq_top a b htop]
    intro z hz
    have hzZero : z = 0 := by simpa using hz
    subst z
    exact zero_mem_binaryDiagonalNormSet a b
  · rw [scaledQuadraticDefectIdeal_eq_powerIdeal_of_ne_top a b htop]
    let D : Int := ordUnit K b + (quadraticDefect K (a * b)).toNat
    let T : Int := ordUnit K a + ramificationIndex K
    intro z hz
    by_cases hTD : T ≤ D
    · apply twicePrincipalIdeal_subset_binaryDiagonalNormSet a b
      rw [twicePrincipalIdeal_eq_powerIdeal]
      exact (powerIdeal_le_iff D T).2 hTD hz
    · have hDT : D < T := lt_of_not_ge hTD
      obtain ⟨e, heOrder, heMem⟩ :=
        exists_binaryDefectGenerator a b hab htop
      have heOrderD : ordUnit K e = D := by
        simpa only [D] using heOrder
      have hparity : Odd (ordUnit K a + D) := by
        exact odd_normOrder_add_scaledDefectOrder_of_lt
          a b hab htop (by simpa only [D, T] using hDT)
      have hDParity : Odd (D - ordUnit K a) := by
        rcases hparity with ⟨k, hk⟩
        refine ⟨k - ordUnit K a, ?_⟩
        omega
      have haux : ∀ m : Nat, ∀ x : K, ∀ (hxZero : x ≠ 0),
          D ≤ ordUnit K (Units.mk0 x hxZero) →
          ordUnit K (Units.mk0 x hxZero) < T →
          Int.toNat (T - ordUnit K (Units.mk0 x hxZero)) = m →
          x ∈ binaryDiagonalNormSet a b := by
        intro m
        induction m using Nat.strong_induction_on with
        | h m ih =>
          intro x hxZero hDx hxT hmeasure
          let xu : Kˣ := Units.mk0 x hxZero
          obtain ⟨g, hgLe, hgMem, hgapEven⟩ :
              ∃ g : Kˣ,
                ordUnit K g ≤ ordUnit K xu ∧
                (g : K) ∈ binaryDiagonalNormSet a b ∧
                Even (ordUnit K xu - ordUnit K g) := by
            rcases Int.even_or_odd
                (ordUnit K xu - ordUnit K a) with hxeven | hxodd
            · refine ⟨a, ?_, ?_, hxeven⟩
              · have haD : ordUnit K a ≤ D := by
                  dsimp only [D]
                  omega
                exact haD.trans hDx
              · simpa using firstSquare_mem_binaryDiagonalNormSet a b 1
            · refine ⟨e, ?_, heMem, ?_⟩
              · rw [heOrderD]
                exact hDx
              · rcases hxodd with ⟨r, hr⟩
                rcases hDParity with ⟨s, hs⟩
                refine ⟨r - s, ?_⟩
                rw [heOrderD]
                omega
          obtain ⟨c, hcApprox⟩ :=
            exists_integral_square_approximation_of_even_order_difference
              g xu hgLe hgapEven
          let base : K := (g : K) * (c : K) ^ 2
          have hbase : base ∈ binaryDiagonalNormSet a b := by
            have hscaled :=
              integralSquare_mul_mem_binaryDiagonalNormSet a b hgMem c
            simpa only [base, mul_comm] using hscaled
          let residual : K := x - base
          by_cases hrZero : residual = 0
          · have hxEq : x = base := by
              exact sub_eq_zero.mp hrZero
            rw [hxEq]
            exact hbase
          · let ru : Kˣ := Units.mk0 residual hrZero
            have hrOrder : ordUnit K xu < ordUnit K ru := by
              apply WithTop.coe_lt_coe.mp
              have hrField : ord K residual =
                  (ordUnit K ru : WithTop Int) := by
                have hruVal : (ru : K) = residual := rfl
                rw [← hruVal]
                exact (coe_ordUnit K ru).symm
              rw [← hrField]
              have hxuVal : (xu : K) = x := rfl
              rw [hxuVal] at hcApprox
              simpa only [residual, base] using hcApprox
            have hDr : D ≤ ordUnit K ru := hDx.trans hrOrder.le
            by_cases hTr : T ≤ ordUnit K ru
            · have hrTwo : residual ∈
                  twiceIdeal (principalIdeal (K := K) (a : K)) := by
                rw [twicePrincipalIdeal_eq_powerIdeal]
                rw [mem_powerIdeal_iff]
                have hrField : ord K residual =
                    (ordUnit K ru : WithTop Int) := by
                  have hruVal : (ru : K) = residual := rfl
                  rw [← hruVal]
                  exact (coe_ordUnit K ru).symm
                rw [hrField]
                exact_mod_cast hTr
              have hrMem :=
                twicePrincipalIdeal_subset_binaryDiagonalNormSet a b hrTwo
              have hsum := add_mem_binaryDiagonalNormSet
                a b hba hbase hrMem
              have hxSum : x = base + residual := by
                dsimp only [residual]
                ring
              rwa [hxSum]
            · have hrT : ordUnit K ru < T := lt_of_not_ge hTr
              have hmeasureX :
                  (T - ordUnit K xu).toNat = m := by
                simpa only [xu] using hmeasure
              have hmeasureR :
                  (T - ordUnit K ru).toNat < m := by
                rw [← hmeasureX]
                exact (Int.toNat_lt_toNat (by omega)).2 (by omega)
              have hrMem := ih
                ((T - ordUnit K ru).toNat) hmeasureR residual hrZero
                hDr hrT rfl
              have hsum := add_mem_binaryDiagonalNormSet
                a b hba hbase hrMem
              have hxSum : x = base + residual := by
                dsimp only [residual]
                ring
              rwa [hxSum]
      by_cases hzZero : z = 0
      · subst z
        exact zero_mem_binaryDiagonalNormSet a b
      · let zu : Kˣ := Units.mk0 z hzZero
        have hDz : D ≤ ordUnit K zu := by
          change z ∈ powerIdeal (K := K) D at hz
          rw [mem_powerIdeal_iff] at hz
          have hzField : ord K z =
              (ordUnit K zu : WithTop Int) := by
            have hzuVal : (zu : K) = z := rfl
            rw [← hzuVal]
            exact (coe_ordUnit K zu).symm
          rw [hzField] at hz
          exact WithTop.coe_le_coe.mp hz
        by_cases hTz : T ≤ ordUnit K zu
        · apply twicePrincipalIdeal_subset_binaryDiagonalNormSet a b
          rw [twicePrincipalIdeal_eq_powerIdeal]
          change z ∈ powerIdeal (K := K) T
          rw [mem_powerIdeal_iff]
          have hzField : ord K z =
              (ordUnit K zu : WithTop Int) := by
            have hzuVal : (zu : K) = z := rfl
            rw [← hzuVal]
            exact (coe_ordUnit K zu).symm
          rw [hzField]
          exact_mod_cast hTz
        · exact haux (T - ordUnit K zu).toNat z hzZero hDz
            (lt_of_not_ge hTz) rfl

/-- A second diagonal coefficient can be approximated by an integral square
multiple of the first, with error in `a⁻¹d(ab)`. -/
theorem exists_integral_binaryDefectApproximation
    (a b : Kˣ) (hab : ordUnit K a ≤ ordUnit K b) :
    ∃ c : IntegerRing K,
      (b : K) - (a : K) * (c : K) ^ 2 ∈
        scalarIdeal ((a⁻¹ : Kˣ) : K)
          (quadraticDefectIdeal (a * b)) := by
  let r : Kˣ := b / a
  have hrDefect : quadraticDefect K r = quadraticDefect K (a * b) := by
    have h := quadraticDefect_mul_square K (a * b) a⁻¹
    have hunit : (a * b) * a⁻¹ ^ 2 = r := by
      apply Units.ext
      dsimp only [r]
      simp only [Units.val_mul, Units.val_pow_eq_pow_val,
        Units.val_inv_eq_inv_val, Units.val_div_eq_div_val]
      field_simp [Units.ne_zero a, Units.ne_zero b]
    rw [hunit] at h
    exact h
  by_cases htop : quadraticDefect K (a * b) = ⊤
  · have hrTop : quadraticDefect K r = ⊤ := by
      rw [hrDefect, htop]
    rcases (quadraticDefect_eq_top_iff_isSquare (K := K) r).mp hrTop with
      ⟨s, hs⟩
    have hrOrder : ordUnit K r = ordUnit K b - ordUnit K a := by
      dsimp only [r]
      rw [div_eq_mul_inv, ordUnit_mul, ordUnit_inv]
      ring
    have hsOrder : ordUnit K r = 2 * ordUnit K s := by
      rw [hs, ordUnit_mul]
      ring
    have hsNonneg : 0 ≤ ordUnit K s := by
      omega
    have hsIntegral : Dyadic.IsIntegral K (s : K) := by
      rw [Dyadic.IsIntegral, ← coe_ordUnit]
      exact_mod_cast hsNonneg
    let c : IntegerRing K :=
      ⟨(s : K), (mem_integerRing_iff K).2 hsIntegral⟩
    refine ⟨c, ?_⟩
    have hsVal : (r : K) = (s : K) ^ 2 := by
      have hval := congrArg Units.val hs
      simpa only [Units.val_mul, pow_two] using hval
    have hrVal : (r : K) = (b : K) / (a : K) := by
      simp only [r, Units.val_div_eq_div_val]
    have hbEq : (b : K) = (a : K) * (s : K) ^ 2 := by
      calc
        (b : K) = (a : K) * ((b : K) / (a : K)) := by
          field_simp [Units.ne_zero a]
        _ = (a : K) * (r : K) := by rw [hrVal]
        _ = (a : K) * (s : K) ^ 2 := by rw [hsVal]
    rw [scaledQuadraticDefectIdeal_eq_bot_of_eq_top a b htop]
    change (b : K) - (a : K) * (s : K) ^ 2 ∈ (⊥ : CoefficientIdeal (K := K))
    rw [hbEq, sub_self]
    exact Submodule.zero_mem _
  · let d : Nat := (quadraticDefect K (a * b)).toNat
    by_cases hdZero : d = 0
    · refine ⟨0, ?_⟩
      rw [scaledQuadraticDefectIdeal_eq_powerIdeal_of_ne_top a b htop]
      have hzero : (((0 : IntegerRing K) : K)) = (0 : K) := rfl
      rw [hzero, zero_pow (by norm_num : (2 : Nat) ≠ 0), mul_zero, sub_zero]
      change (b : K) ∈ powerIdeal (K := K)
        (ordUnit K b + (quadraticDefect K (a * b)).toNat)
      rw [mem_powerIdeal_iff, ← coe_ordUnit]
      dsimp only [d] at hdZero
      rw [hdZero]
      simp
    · have hdPos : 0 < d := Nat.pos_of_ne_zero hdZero
      have hrFinite : quadraticDefect K r ≠ ⊤ := by
        rw [hrDefect]
        exact htop
      rcases BONG.exists_quadraticApproximation_exact_order r hrFinite with
        ⟨x, hxOrder⟩
      have hxOrder' : ord K (1 - x ^ 2 / (r : K)) =
          ((d : Int) : WithTop Int) := by
        simpa only [d, hrDefect] using hxOrder
      have herrorPos : 0 < ord K (1 - x ^ 2 / (r : K)) := by
        rw [hxOrder']
        exact_mod_cast hdPos
      have hquotOrder : ord K (x ^ 2 / (r : K)) = 0 := by
        have hlt : ord K (1 : K) <
            ord K (1 - x ^ 2 / (r : K)) := by
          simpa only [ord_one] using herrorPos
        have hsub := (ord K).map_sub_eq_of_lt_left hlt
        have heq : 1 - (1 - x ^ 2 / (r : K)) =
            x ^ 2 / (r : K) := by ring
        rw [heq] at hsub
        simpa only [ord_one] using hsub
      have hxNe : x ≠ 0 := by
        intro hxZero
        subst x
        simp at hquotOrder
      let xu : Kˣ := Units.mk0 x hxNe
      have hrOrder : ordUnit K r = ordUnit K b - ordUnit K a := by
        dsimp only [r]
        rw [div_eq_mul_inv, ordUnit_mul, ordUnit_inv]
        ring
      have hxuOrder : 2 * ordUnit K xu = ordUnit K r := by
        have hquotUnitOrder : ordUnit K (xu ^ 2 / r) = 0 := by
          apply WithTop.coe_injective
          rw [coe_ordUnit]
          have hval : ((xu ^ 2 / r : Kˣ) : K) =
              x ^ 2 / (r : K) := by
            rw [Units.val_div_eq_div_val, Units.val_pow_eq_pow_val]
            rfl
          rw [hval]
          simpa using hquotOrder
        rw [div_eq_mul_inv, ordUnit_mul, ordUnit_inv,
          ordUnit_pow] at hquotUnitOrder
        omega
      have hxuNonneg : 0 ≤ ordUnit K xu := by
        rw [hrOrder] at hxuOrder
        omega
      have hxIntegral : Dyadic.IsIntegral K x := by
        have hxField : ord K x =
            (ordUnit K xu : WithTop Int) := by
          have hxuVal : (xu : K) = x := rfl
          rw [← hxuVal]
          exact (coe_ordUnit K xu).symm
        rw [Dyadic.IsIntegral, hxField]
        exact_mod_cast hxuNonneg
      let c : IntegerRing K :=
        ⟨x, (mem_integerRing_iff K).2 hxIntegral⟩
      refine ⟨c, ?_⟩
      let error : K := (b : K) - (a : K) * x ^ 2
      have hfactor : error =
          (b : K) * (1 - x ^ 2 / (r : K)) := by
        dsimp only [error, r]
        simp only [Units.val_div_eq_div_val]
        field_simp [Units.ne_zero a, Units.ne_zero b]
      have herrorOrder : ord K error =
          ((ordUnit K b + (d : Int) : Int) : WithTop Int) := by
        rw [hfactor, ord_mul, ← coe_ordUnit, hxOrder']
        push_cast
        ring
      rw [scaledQuadraticDefectIdeal_eq_powerIdeal_of_ne_top a b htop]
      change error ∈ powerIdeal (K := K)
        (ordUnit K b + (quadraticDefect K (a * b)).toNat)
      rw [mem_powerIdeal_iff, herrorOrder]

/-- The ideal occurring in O'Meara's binary diagonal formula:
`a⁻¹ d(ab) + 2aO`. -/
noncomputable def binaryDiagonalWeightIdeal (a b : Kˣ) :
    CoefficientIdeal (K := K) :=
  scalarIdeal ((a⁻¹ : Kˣ) : K) (quadraticDefectIdeal (a * b)) ⊔
    twiceIdeal (principalIdeal (K := K) (a : K))

/-- Integral-square cosets modulo an ideal containing `2aO` are additive. -/
theorem add_mem_integralSquareCoset_of_twicePrincipal_le
    (a : Kˣ) (w : CoefficientIdeal (K := K))
    (htwo : twiceIdeal (principalIdeal (K := K) (a : K)) ≤ w)
    {z z' : K}
    (hz : z ∈ integralSquareCoset (a : K) w)
    (hz' : z' ∈ integralSquareCoset (a : K) w) :
    z + z' ∈ integralSquareCoset (a : K) w := by
  rcases hz with ⟨c, y, hy, rfl⟩
  rcases hz' with ⟨d, y', hy', rfl⟩
  have hcd : (a : K) * (c : K) * (d : K) ∈
      principalIdeal (K := K) (a : K) := by
    have h := mul_mem_principalIdeal_of_mem_integerRing
      (K := K) (a : K) ((c * d : IntegerRing K) : K) (c * d).property
    have hmul : ((c * d : IntegerRing K) : K) =
        (c : K) * (d : K) :=
      map_mul (algebraMap (IntegerRing K) K) c d
    simpa only [hmul, mul_assoc] using h
  have hcross : (2 : K) * ((a : K) * (c : K) * (d : K)) ∈ w :=
    htwo (two_mul_mem_twicePrincipalIdeal a hcd)
  let error : K := y + y' -
    (2 : K) * ((a : K) * (c : K) * (d : K))
  have herror : error ∈ w := by
    exact w.sub_mem (w.add_mem hy hy') hcross
  refine ⟨c + d, error, herror, ?_⟩
  have hcadd : ((c + d : IntegerRing K) : K) =
      (c : K) + (d : K) :=
    map_add (algebraMap (IntegerRing K) K) c d
  rw [hcadd]
  dsimp only [error]
  ring

/-- Every enlarged integral value of `⟨a,b⟩` lies in
`aO² + a⁻¹d(ab) + 2aO`. -/
theorem binaryDiagonalNormSet_subset_integralSquareCoset
    (a b : Kˣ) (hab : ordUnit K a ≤ ordUnit K b) :
    binaryDiagonalNormSet a b ⊆
      integralSquareCoset (a : K) (binaryDiagonalWeightIdeal a b) := by
  intro z hz
  rcases hz with ⟨c, d, y, hy, rfl⟩
  let defectIdeal : CoefficientIdeal (K := K) :=
    scalarIdeal ((a⁻¹ : Kˣ) : K) (quadraticDefectIdeal (a * b))
  have htwo : twiceIdeal (principalIdeal (K := K) (a : K)) ≤
      binaryDiagonalWeightIdeal a b := by
    change twiceIdeal (principalIdeal (K := K) (a : K)) ≤
      scalarIdeal ((a⁻¹ : Kˣ) : K) (quadraticDefectIdeal (a * b)) ⊔
        twiceIdeal (principalIdeal (K := K) (a : K))
    intro x hx
    exact Submodule.mem_sup_right hx
  have hfirst : (a : K) * (c : K) ^ 2 ∈
      integralSquareCoset (a : K) (binaryDiagonalWeightIdeal a b) := by
    exact ⟨c, 0, Submodule.zero_mem _, by simp⟩
  obtain ⟨u, hu⟩ := exists_integral_binaryDefectApproximation a b hab
  let error : K := ((d ^ 2 : IntegerRing K) : K) *
    ((b : K) - (a : K) * (u : K) ^ 2)
  have herrorDefect : error ∈ defectIdeal := by
    have hsmul := defectIdeal.smul_mem (d ^ 2) hu
    change ((d ^ 2 : IntegerRing K) : K) *
      ((b : K) - (a : K) * (u : K) ^ 2) ∈ defectIdeal at hsmul
    exact hsmul
  have herror : error ∈ binaryDiagonalWeightIdeal a b := by
    exact Submodule.mem_sup_left herrorDefect
  have hsecond : (b : K) * (d : K) ^ 2 ∈
      integralSquareCoset (a : K) (binaryDiagonalWeightIdeal a b) := by
    refine ⟨u * d, error, herror, ?_⟩
    have hud : ((u * d : IntegerRing K) : K) =
        (u : K) * (d : K) :=
      map_mul (algebraMap (IntegerRing K) K) u d
    have hdSq : ((d ^ 2 : IntegerRing K) : K) = (d : K) ^ 2 :=
      map_pow (algebraMap (IntegerRing K) K) d 2
    rw [hud]
    dsimp only [error]
    rw [hdSq]
    ring
  have hyCoset : y ∈
      integralSquareCoset (a : K) (binaryDiagonalWeightIdeal a b) := by
    refine ⟨0, y, htwo hy, ?_⟩
    simp
  exact add_mem_integralSquareCoset_of_twicePrincipal_le a
    (binaryDiagonalWeightIdeal a b) htwo
    (add_mem_integralSquareCoset_of_twicePrincipal_le a
      (binaryDiagonalWeightIdeal a b) htwo hfirst hsecond) hyCoset

/-- Conversely, the binary candidate coset is generated by enlarged integral
values of `⟨a,b⟩`. -/
theorem integralSquareCoset_subset_binaryDiagonalNormSet
    (a b : Kˣ) (hab : ordUnit K a ≤ ordUnit K b) :
    integralSquareCoset (a : K) (binaryDiagonalWeightIdeal a b) ⊆
      binaryDiagonalNormSet a b := by
  have hba : principalIdeal (K := K) (b : K) ≤
      principalIdeal (K := K) (a : K) := by
    rw [principalIdeal_eq_powerIdeal, principalIdeal_eq_powerIdeal]
    exact (powerIdeal_le_iff _ _).2 hab
  rintro z ⟨c, y, hy, rfl⟩
  change y ∈
      scalarIdeal ((a⁻¹ : Kˣ) : K) (quadraticDefectIdeal (a * b)) ⊔
        twiceIdeal (principalIdeal (K := K) (a : K)) at hy
  rcases Submodule.mem_sup.mp hy with ⟨u, hu, v, hv, rfl⟩
  have hfirst := firstSquare_mem_binaryDiagonalNormSet a b c
  have hdefect := scaledQuadraticDefectIdeal_subset_binaryDiagonalNormSet
    a b hab hu
  have htwo := twicePrincipalIdeal_subset_binaryDiagonalNormSet a b hv
  have hsum := add_mem_binaryDiagonalNormSet a b hba
    (add_mem_binaryDiagonalNormSet a b hba hfirst hdefect) htwo
  simpa only [add_assoc] using hsum

/-- O'Meara's binary diagonal calculation in exact set form. -/
theorem binaryDiagonalNormSet_eq_integralSquareCoset
    (a b : Kˣ) (hab : ordUnit K a ≤ ordUnit K b) :
    binaryDiagonalNormSet a b =
      integralSquareCoset (a : K) (binaryDiagonalWeightIdeal a b) := by
  exact Set.Subset.antisymm
    (binaryDiagonalNormSet_subset_integralSquareCoset a b hab)
    (integralSquareCoset_subset_binaryDiagonalNormSet a b hab)

/-! ## Consequences of the proved weight characterization -/

/-- The selected weight ideal, for any lawful implementation of the weight
interface, gives the norm-group square coset. -/
theorem normGroupSet_eq_integralSquareCoset_weightIdeal
    {q : QuadraticSpace K V} {L : Lattice K V}
    [Beli2009WeightIdealData.{u, v} K]
    (a : Kˣ) (ha : IsNormGeneratorValue q L a) :
    normGroupSet q L = integralSquareCoset (a : K) (weightIdeal q L) := by
  have hconditions := (beli2009Lemma210 a ha
    (Beli2009WeightIdealData.weight q L)
    (twoScaleIdeal_le_weightIdeal q L)).mp rfl
  exact hconditions.1

/-- A norm-generator value generates the norm ideal as a principal ideal. -/
theorem normIdeal_eq_principalIdeal_of_isNormGeneratorValue
    {q : QuadraticSpace K V} {L : Lattice K V}
    (a : Kˣ) (ha : IsNormGeneratorValue q L a) :
    normIdeal q L = principalIdeal (K := K) (a : K) := by
  exact ha.2

/-- Every lawful selected weight has the same carrier as the canonical
construction proved in Lemma 2.10. -/
theorem weightIdeal_eq_canonicalWeightIdeal
    {q : QuadraticSpace K V} {L : Lattice K V}
    [Beli2009WeightIdealData.{u, v} K]
    (a : Kˣ) (ha : IsNormGeneratorValue q L a) :
    weightIdeal q L = (canonicalWeightIdeal q L).carrier := by
  have h := (beli2009Lemma210 a ha (canonicalWeightIdeal q L)
    (twoScaleIdeal_le_canonicalWeightIdeal q L)).mpr
      (canonicalWeight_satisfiesWeightIdealConditions ha)
  exact h.symm

/-- Consequently, the order stored by any lawful selected weight is the
canonical weight order. -/
theorem weightIdealOrder_eq_canonicalWeightOrder
    {q : QuadraticSpace K V} {L : Lattice K V}
    [Beli2009WeightIdealData.{u, v} K]
    (a : Kˣ) (ha : IsNormGeneratorValue q L a) :
    weightIdealOrder q L = canonicalWeightOrder q L := by
  apply powerIdeal_order_eq_of_eq (K := K)
  calc
    powerIdeal (K := K) (weightIdealOrder q L) = weightIdeal q L :=
      (weightIdeal_eq_powerIdeal q L).symm
    _ = (canonicalWeightIdeal q L).carrier :=
      weightIdeal_eq_canonicalWeightIdeal a ha
    _ = powerIdeal (K := K) (canonicalWeightOrder q L) := rfl

/-- The norm order is at most the selected weight order. -/
theorem normGeneratorOrder_le_weightIdealOrder
    {q : QuadraticSpace K V} {L : Lattice K V}
    [Beli2009WeightIdealData.{u, v} K]
    (a : Kˣ) (ha : IsNormGeneratorValue q L a) :
    ordUnit K a ≤ weightIdealOrder q L := by
  rw [ordUnit_eq_canonicalNormOrder ha,
    weightIdealOrder_eq_canonicalWeightOrder a ha,
    canonicalWeightOrder_eq ha]
  omega

/-- Enlarging the error ideal enlarges an integral-square coset. -/
theorem integralSquareCoset_mono (a : K)
    {I J : CoefficientIdeal (K := K)} (hIJ : I ≤ J) :
    integralSquareCoset a I ⊆ integralSquareCoset a J := by
  rintro z ⟨c, y, hy, rfl⟩
  exact ⟨c, y, hIJ hy, rfl⟩

/-- An element of the error ideal may be added inside its square coset. -/
theorem add_ideal_mem_integralSquareCoset (a : K)
    (I : CoefficientIdeal (K := K)) {z y : K}
    (hz : z ∈ integralSquareCoset a I) (hy : y ∈ I) :
    z + y ∈ integralSquareCoset a I := by
  rcases hz with ⟨c, w, hw, rfl⟩
  exact ⟨c, w + y, I.add_mem hw hy, by ring⟩

namespace OrthogonalDecomposition

variable {q : QuadraticSpace K V} {L : Lattice K V} {t : Nat}
  [Beli2009WeightIdealData.{u, v} K]

/-- A component norm group maps into the norm group of the orthogonal sum. -/
theorem component_normGroupSet_subset
    (D : OrthogonalDecomposition q L t) (i : Fin t) :
    normGroupSet (D.component i).space (D.component i).lattice ⊆
      normGroupSet q L := by
  rintro z ⟨x, hx, y, hy, rfl⟩
  refine ⟨(x : V), D.component_ambientSubmodule_le i
      ⟨x, hx, rfl⟩, y, ?_, ?_⟩
  · rcases hy with ⟨s, hs, rfl⟩
    refine ⟨s, ?_, rfl⟩
    rw [D.scaleIdeal_eq_iSup_component]
    exact le_iSup
      (fun j ↦ scaleIdeal (D.component j).space
        (D.component j).lattice) i hs
  · rfl

/-- Zero belongs to the finite Minkowski sum of the component norm groups. -/
private theorem zero_mem_indexedComponentNormGroup
    (D : OrthogonalDecomposition q L t) :
    (0 : K) ∈ indexedSetSum (fun i ↦
      normGroupSet (D.component i).space (D.component i).lattice) := by
  refine ⟨fun _ ↦ 0, fun i ↦ zero_mem_normGroupSet
    (D.component i).space (D.component i).lattice, ?_⟩
  simp

/-- The finite Minkowski sum of the component norm groups is additive. -/
private theorem add_mem_indexedComponentNormGroup
    (D : OrthogonalDecomposition q L t) {z w : K}
    (hz : z ∈ indexedSetSum (fun i ↦
      normGroupSet (D.component i).space (D.component i).lattice))
    (hw : w ∈ indexedSetSum (fun i ↦
      normGroupSet (D.component i).space (D.component i).lattice)) :
    z + w ∈ indexedSetSum (fun i ↦
      normGroupSet (D.component i).space (D.component i).lattice) := by
  rcases hz with ⟨x, hx, rfl⟩
  rcases hw with ⟨y, hy, rfl⟩
  refine ⟨fun i ↦ x i + y i, ?_, ?_⟩
  · intro i
    exact add_mem_normGroupSet (D.component i).space
      (D.component i).lattice (hx i) (hy i)
  · rw [Finset.sum_add_distrib]

/-- The right-hand norm-group expression contains zero. -/
private theorem zero_mem_normGroupExpression
    (D : OrthogonalDecomposition q L t) :
    (0 : K) ∈ D.normGroupExpression := by
  refine ⟨0, D.zero_mem_indexedComponentNormGroup,
    0, Submodule.zero_mem _, ?_⟩
  simp

/-- The right-hand norm-group expression is additive. -/
private theorem add_mem_normGroupExpression
    (D : OrthogonalDecomposition q L t) {z w : K}
    (hz : z ∈ D.normGroupExpression)
    (hw : w ∈ D.normGroupExpression) :
    z + w ∈ D.normGroupExpression := by
  rcases hz with ⟨x, hx, y, hy, rfl⟩
  rcases hw with ⟨x', hx', y', hy', rfl⟩
  refine ⟨x + x', D.add_mem_indexedComponentNormGroup hx hx',
    y + y', (twoScaleIdeal q L).add_mem hy hy', ?_⟩
  ring

/-- Adding an element of `2sL` preserves the right-hand expression. -/
private theorem add_twoScale_mem_normGroupExpression
    (D : OrthogonalDecomposition q L t) {z y : K}
    (hz : z ∈ D.normGroupExpression) (hy : y ∈ twoScaleIdeal q L) :
    z + y ∈ D.normGroupExpression := by
  rcases hz with ⟨x, hx, w, hw, rfl⟩
  exact ⟨x, hx, w + y, (twoScaleIdeal q L).add_mem hw hy, by ring⟩

/-- A quadratic value of the ambient lattice belongs to the norm-group
expression attached to an orthogonal decomposition. -/
private theorem quadratic_mem_normGroupExpression
    (D : OrthogonalDecomposition q L t) {x : V} (hx : x ∈ L) :
    q.quadratic x ∈ D.normGroupExpression := by
  have hx' : x ∈ ⨆ i, (D.component i).ambientSubmodule := by
    rw [D.sum_eq]
    exact hx
  clear hx
  induction hx' using Submodule.iSup_induction' with
  | mem i x hxi =>
      rcases hxi with ⟨xi, hxi, rfl⟩
      let values : Fin t → K := fun j ↦
        if h : j = i then
          (D.component i).space.quadratic xi
        else 0
      have hvalues : ∀ j, values j ∈
          normGroupSet (D.component j).space (D.component j).lattice := by
        intro j
        by_cases hji : j = i
        · subst j
          refine ⟨xi, hxi, 0, Submodule.zero_mem _, ?_⟩
          simp [values]
        · simp only [values, dif_neg hji]
          exact zero_mem_normGroupSet (D.component j).space
            (D.component j).lattice
      have hsum : ∑ j, values j =
          (D.component i).space.quadratic xi := by
        classical
        simp [values]
      refine ⟨∑ j, values j, ⟨values, hvalues, rfl⟩,
        0, Submodule.zero_mem _, ?_⟩
      rw [hsum]
      change q.quadratic (xi : V) =
        (D.component i).space.quadratic xi + 0
      rw [add_zero]
      rfl
  | zero => simpa using D.zero_mem_normGroupExpression
  | add x y hx hy hxE hyE =>
      have hxL : x ∈ L := by
        change x ∈ L.toSubmodule
        rw [← D.sum_eq]
        exact hx
      have hyL : y ∈ L := by
        change y ∈ L.toSubmodule
        rw [← D.sum_eq]
        exact hy
      have hcross : (2 : K) * q.bilin x y ∈ twoScaleIdeal q L := by
        refine ⟨q.bilin x y, bilin_mem_scaleIdeal_of_mem q L hxL hyL, ?_⟩
        rfl
      rw [q.quadratic_add]
      exact D.add_twoScale_mem_normGroupExpression
        (D.add_mem_normGroupExpression hxE hyE) hcross

/-- Quadratic values of a finite family of mutually orthogonal component
vectors add without cross terms. -/
private theorem quadratic_sum_component_vectors
    (D : OrthogonalDecomposition q L t)
    (x : ∀ i, (D.component i).carrier) :
    q.quadratic (∑ i, (x i : V)) =
      ∑ i, (D.component i).space.quadratic (x i) := by
  classical
  suffices h : ∀ s : Finset (Fin t),
      q.quadratic (∑ i ∈ s, (x i : V)) =
        ∑ i ∈ s, (D.component i).space.quadratic (x i) by
    simpa using h Finset.univ
  intro s
  induction s using Finset.induction_on with
  | empty => simp
  | @insert i s hi ih =>
      have horth : q.bilin (x i : V) (∑ j ∈ s, (x j : V)) = 0 := by
        rw [map_sum]
        apply Finset.sum_eq_zero
        intro j hj
        have hij : i ≠ j := by
          intro h
          subst j
          exact hi hj
        exact D.orthogonal i j hij (x i) (x j)
      have hqi : q.quadratic (x i : V) =
          (D.component i).space.quadratic (x i) := by
        rfl
      rw [Finset.sum_insert hi, Finset.sum_insert hi,
        q.quadratic_add, horth, ih, hqi]
      ring

/-- Beli's first formula in Lemma 2.11, proved directly from the integral
orthogonal decomposition. -/
theorem normGroupSet_eq_normGroupExpression
    (D : OrthogonalDecomposition q L t) :
    normGroupSet q L = D.normGroupExpression := by
  apply Set.Subset.antisymm
  · rintro z ⟨x, hx, y, hy, rfl⟩
    exact D.add_twoScale_mem_normGroupExpression
      (D.quadratic_mem_normGroupExpression hx) hy
  · rintro z ⟨s, ⟨zv, hzv, rfl⟩, y, hy, rfl⟩
    choose x hx w hw hvalue using hzv
    let xAmbient : Fin t → V := fun i ↦ (x i : V)
    have hxAmbient (i : Fin t) : xAmbient i ∈ L :=
      D.component_ambientSubmodule_le i ⟨x i, hx i, rfl⟩
    have hxSum : (∑ i, xAmbient i) ∈ L := by
      exact Submodule.sum_mem L.toSubmodule fun i _ ↦ hxAmbient i
    have hwAmbient (i : Fin t) : w i ∈ twoScaleIdeal q L := by
      rcases hw i with ⟨r, hr, hri⟩
      refine ⟨r, ?_, hri⟩
      rw [D.scaleIdeal_eq_iSup_component]
      exact le_iSup
        (fun j ↦ scaleIdeal (D.component j).space
          (D.component j).lattice) i (hr)
    have hwSum : (∑ i, w i) ∈ twoScaleIdeal q L :=
      Submodule.sum_mem (twoScaleIdeal q L) fun i _ ↦ hwAmbient i
    refine ⟨∑ i, xAmbient i, hxSum, (∑ i, w i) + y,
      (twoScaleIdeal q L).add_mem hwSum hy, ?_⟩
    have hquad := D.quadratic_sum_component_vectors x
    dsimp only [xAmbient] at hquad ⊢
    simp_rw [hvalue]
    rw [hquad]
    rw [Finset.sum_add_distrib]
    ring

/-! ## The square-coset formula for the orthogonal sum -/

/-- An ambient norm generator has no larger order than any component norm
generator. -/
theorem normGeneratorOrder_le_componentNormGeneratorOrder
    (D : OrthogonalDecomposition q L t)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (ak : Fin t → Kˣ)
    (hak : ∀ i, IsNormGeneratorValue
      (D.component i).space (D.component i).lattice (ak i))
    (i : Fin t) :
    ordUnit K a ≤ ordUnit K (ak i) := by
  have hcomponent :
      normIdeal (D.component i).space (D.component i).lattice ≤
        normIdeal q L := by
    rw [D.normIdeal_eq_iSup_component]
    exact le_iSup
      (fun j ↦ normIdeal (D.component j).space
        (D.component j).lattice) i
  rw [normIdeal_eq_principalIdeal_of_isNormGeneratorValue (ak i) (hak i),
    normIdeal_eq_principalIdeal_of_isNormGeneratorValue a ha,
    principalIdeal_eq_powerIdeal, principalIdeal_eq_powerIdeal] at hcomponent
  exact (powerIdeal_le_iff _ _).mp hcomponent

/-- The ideal `2aO` of an ambient norm generator lies in `2sL`. -/
theorem twicePrincipalIdeal_le_twoScaleIdeal
    (a : Kˣ) (ha : IsNormGeneratorValue q L a) :
    twiceIdeal (principalIdeal (K := K) (a : K)) ≤
      twoScaleIdeal q L := by
  change twiceIdeal (principalIdeal (K := K) (a : K)) ≤
    twiceIdeal (scaleIdeal q L)
  rw [← normIdeal_eq_principalIdeal_of_isNormGeneratorValue a ha]
  exact twiceIdeal_mono (normIdeal_le_scaleIdeal q L)

/-- A component's `2s` ideal maps into the ambient `2s` ideal. -/
theorem component_twoScaleIdeal_le
    (D : OrthogonalDecomposition q L t) (i : Fin t) :
    twoScaleIdeal (D.component i).space (D.component i).lattice ≤
      twoScaleIdeal q L := by
  apply twiceIdeal_mono
  rw [D.scaleIdeal_eq_iSup_component]
  exact le_iSup
    (fun j ↦ scaleIdeal (D.component j).space
      (D.component j).lattice) i

/-- Each component weight is a summand of the ideal in Lemma 2.11. -/
theorem componentWeight_le_weightIdealExpression
    (D : OrthogonalDecomposition q L t) (a : Kˣ)
    (ak : Fin t → Kˣ) (i : Fin t) :
    weightIdeal (D.component i).space (D.component i).lattice ≤
      D.weightIdealExpression a ak := by
  change weightIdeal (D.component i).space (D.component i).lattice ≤
    (⨆ j, weightIdeal (D.component j).space
      (D.component j).lattice) ⊔
      (⨆ j, scalarIdeal ((a⁻¹ : Kˣ) : K)
        (quadraticDefectIdeal (a * ak j))) ⊔ twoScaleIdeal q L
  intro x hx
  exact Submodule.mem_sup_left (Submodule.mem_sup_left
    (le_iSup (fun j ↦ weightIdeal (D.component j).space
      (D.component j).lattice) i hx))

/-- Each scaled component defect is a summand of the ideal in Lemma 2.11. -/
theorem componentDefect_le_weightIdealExpression
    (D : OrthogonalDecomposition q L t) (a : Kˣ)
    (ak : Fin t → Kˣ) (i : Fin t) :
    scalarIdeal ((a⁻¹ : Kˣ) : K)
        (quadraticDefectIdeal (a * ak i)) ≤
      D.weightIdealExpression a ak := by
  change scalarIdeal ((a⁻¹ : Kˣ) : K)
      (quadraticDefectIdeal (a * ak i)) ≤
    (⨆ j, weightIdeal (D.component j).space
      (D.component j).lattice) ⊔
      (⨆ j, scalarIdeal ((a⁻¹ : Kˣ) : K)
        (quadraticDefectIdeal (a * ak j))) ⊔ twoScaleIdeal q L
  intro x hx
  exact Submodule.mem_sup_left (Submodule.mem_sup_right
    (le_iSup (fun j ↦ scalarIdeal ((a⁻¹ : Kˣ) : K)
      (quadraticDefectIdeal (a * ak j))) i hx))

/-- The ambient `2sL` term is a summand of the ideal in Lemma 2.11. -/
theorem twoScaleIdeal_le_weightIdealExpression
    (D : OrthogonalDecomposition q L t) (a : Kˣ)
    (ak : Fin t → Kˣ) :
    twoScaleIdeal q L ≤ D.weightIdealExpression a ak := by
  intro x hx
  exact Submodule.mem_sup_right hx

/-- The binary candidate attached to one component maps into the full
orthogonal-sum candidate. -/
theorem binaryDiagonalWeightIdeal_le_weightIdealExpression
    (D : OrthogonalDecomposition q L t)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (ak : Fin t → Kˣ) (i : Fin t) :
    binaryDiagonalWeightIdeal a (ak i) ≤
      D.weightIdealExpression a ak := by
  change scalarIdeal ((a⁻¹ : Kˣ) : K)
      (quadraticDefectIdeal (a * ak i)) ⊔
      twiceIdeal (principalIdeal (K := K) (a : K)) ≤
    D.weightIdealExpression a ak
  intro x hx
  rcases Submodule.mem_sup.mp hx with ⟨y, hy, z, hz, rfl⟩
  exact (D.weightIdealExpression a ak).add_mem
    (D.componentDefect_le_weightIdealExpression a ak i hy)
    (D.twoScaleIdeal_le_weightIdealExpression a ak
      (twicePrincipalIdeal_le_twoScaleIdeal
        (q := q) (L := L) a ha hz))

/-- The full candidate contains `2aO`; hence its square coset is additive. -/
theorem twicePrincipalIdeal_le_weightIdealExpression
    (D : OrthogonalDecomposition q L t)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (ak : Fin t → Kˣ) :
    twiceIdeal (principalIdeal (K := K) (a : K)) ≤
      D.weightIdealExpression a ak :=
  (twicePrincipalIdeal_le_twoScaleIdeal (q := q) (L := L) a ha).trans
    (D.twoScaleIdeal_le_weightIdealExpression a ak)

/-- A component norm group maps into the ambient square coset with the ideal
predicted by Lemma 2.11. -/
theorem component_normGroupSet_subset_weightIdealExpressionCoset
    (D : OrthogonalDecomposition q L t)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (ak : Fin t → Kˣ)
    (hak : ∀ i, IsNormGeneratorValue
      (D.component i).space (D.component i).lattice (ak i))
    (i : Fin t) :
    normGroupSet (D.component i).space (D.component i).lattice ⊆
      integralSquareCoset (a : K) (D.weightIdealExpression a ak) := by
  intro z hz
  rw [normGroupSet_eq_integralSquareCoset_weightIdeal (ak i) (hak i)] at hz
  rcases hz with ⟨c, w, hw, rfl⟩
  have hab := D.normGeneratorOrder_le_componentNormGeneratorOrder
    a ha ak hak i
  have hsquare : (ak i : K) * (c : K) ^ 2 ∈
      integralSquareCoset (a : K) (binaryDiagonalWeightIdeal a (ak i)) := by
    have hbinary := secondSquare_mem_binaryDiagonalNormSet a (ak i) c
    rw [binaryDiagonalNormSet_eq_integralSquareCoset a (ak i) hab] at hbinary
    exact hbinary
  have hsquare' : (ak i : K) * (c : K) ^ 2 ∈
      integralSquareCoset (a : K) (D.weightIdealExpression a ak) :=
    integralSquareCoset_mono (a : K)
      (D.binaryDiagonalWeightIdeal_le_weightIdealExpression a ha ak i)
      hsquare
  exact add_ideal_mem_integralSquareCoset (a : K)
    (D.weightIdealExpression a ak) hsquare'
    (D.componentWeight_le_weightIdealExpression a ak i hw)

/-- A finite sum of elements in the ambient candidate coset remains in that
coset. -/
private theorem sum_mem_weightIdealExpressionCoset
    (D : OrthogonalDecomposition q L t)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (ak : Fin t → Kˣ) (z : Fin t → K)
    (hz : ∀ i, z i ∈
      integralSquareCoset (a : K) (D.weightIdealExpression a ak)) :
    (∑ i, z i) ∈
      integralSquareCoset (a : K) (D.weightIdealExpression a ak) := by
  classical
  suffices h : ∀ s : Finset (Fin t),
      (∑ i ∈ s, z i) ∈
        integralSquareCoset (a : K) (D.weightIdealExpression a ak) by
    simpa using h Finset.univ
  intro s
  induction s using Finset.induction_on with
  | empty =>
      exact ⟨0, 0, Submodule.zero_mem _, by simp⟩
  | @insert i s hi ih =>
      rw [Finset.sum_insert hi]
      exact add_mem_integralSquareCoset_of_twicePrincipal_le a
        (D.weightIdealExpression a ak)
        (D.twicePrincipalIdeal_le_weightIdealExpression a ha ak)
        (hz i) ih

/-- The orthogonal norm-group expression is contained in the square coset
predicted by Lemma 2.11. -/
theorem normGroupExpression_subset_weightIdealExpressionCoset
    (D : OrthogonalDecomposition q L t)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (ak : Fin t → Kˣ)
    (hak : ∀ i, IsNormGeneratorValue
      (D.component i).space (D.component i).lattice (ak i)) :
    D.normGroupExpression ⊆
      integralSquareCoset (a : K) (D.weightIdealExpression a ak) := by
  rintro z ⟨s, ⟨x, hx, rfl⟩, y, hy, rfl⟩
  have hsum := D.sum_mem_weightIdealExpressionCoset a ha ak x
    (fun i ↦ D.component_normGroupSet_subset_weightIdealExpressionCoset
      a ha ak hak i (hx i))
  exact add_ideal_mem_integralSquareCoset (a : K)
    (D.weightIdealExpression a ak) hsum
    (D.twoScaleIdeal_le_weightIdealExpression a ak hy)

/-- An integral square multiple of the ambient norm generator belongs to the
orthogonal norm-group expression. -/
private theorem normGeneratorSquare_mem_normGroupExpression
    (D : OrthogonalDecomposition q L t)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (c : IntegerRing K) :
    (a : K) * (c : K) ^ 2 ∈ D.normGroupExpression := by
  rw [← D.normGroupSet_eq_normGroupExpression]
  exact normGeneratorValue_integralSquare_mem_normGroupSet ha c

/-- A square multiple of a component norm generator belongs to the ambient
orthogonal norm-group expression. -/
private theorem componentNormGeneratorSquare_mem_normGroupExpression
    (D : OrthogonalDecomposition q L t)
    (ak : Fin t → Kˣ)
    (hak : ∀ i, IsNormGeneratorValue
      (D.component i).space (D.component i).lattice (ak i))
    (i : Fin t) (c : IntegerRing K) :
    (ak i : K) * (c : K) ^ 2 ∈ D.normGroupExpression := by
  rw [← D.normGroupSet_eq_normGroupExpression]
  apply D.component_normGroupSet_subset i
  exact normGeneratorValue_integralSquare_mem_normGroupSet (hak i) c

/-- A selected component weight lies in the ambient norm-group expression. -/
private theorem componentWeight_mem_normGroupExpression
    (D : OrthogonalDecomposition q L t)
    (ak : Fin t → Kˣ)
    (hak : ∀ i, IsNormGeneratorValue
      (D.component i).space (D.component i).lattice (ak i))
    (i : Fin t) {y : K}
    (hy : y ∈ weightIdeal (D.component i).space
      (D.component i).lattice) :
    y ∈ D.normGroupExpression := by
  rw [← D.normGroupSet_eq_normGroupExpression]
  apply D.component_normGroupSet_subset i
  rw [normGroupSet_eq_integralSquareCoset_weightIdeal (ak i) (hak i)]
  exact ⟨0, y, hy, by simp⟩

/-- A scaled component defect lies in the ambient norm-group expression. -/
private theorem componentDefect_mem_normGroupExpression
    (D : OrthogonalDecomposition q L t)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (ak : Fin t → Kˣ)
    (hak : ∀ i, IsNormGeneratorValue
      (D.component i).space (D.component i).lattice (ak i))
    (i : Fin t) {y : K}
    (hy : y ∈ scalarIdeal ((a⁻¹ : Kˣ) : K)
      (quadraticDefectIdeal (a * ak i))) :
    y ∈ D.normGroupExpression := by
  have hab := D.normGeneratorOrder_le_componentNormGeneratorOrder
    a ha ak hak i
  have hbinary := scaledQuadraticDefectIdeal_subset_binaryDiagonalNormSet
    a (ak i) hab hy
  rcases hbinary with ⟨c, d, w, hw, rfl⟩
  have hc := D.normGeneratorSquare_mem_normGroupExpression a ha c
  have hd := D.componentNormGeneratorSquare_mem_normGroupExpression ak hak i d
  have hw' : w ∈ twoScaleIdeal q L :=
    twicePrincipalIdeal_le_twoScaleIdeal (q := q) (L := L) a ha hw
  exact D.add_twoScale_mem_normGroupExpression
    (D.add_mem_normGroupExpression hc hd) hw'

/-- The sum of the component weight ideals lies in the ambient norm-group
expression. -/
private theorem componentWeightSum_subset_normGroupExpression
    (D : OrthogonalDecomposition q L t)
    (ak : Fin t → Kˣ)
    (hak : ∀ i, IsNormGeneratorValue
      (D.component i).space (D.component i).lattice (ak i)) :
    (D.componentWeightSum : Set K) ⊆ D.normGroupExpression := by
  intro y hy
  change y ∈ ⨆ i, weightIdeal (D.component i).space
    (D.component i).lattice at hy
  induction hy using Submodule.iSup_induction' with
  | mem i y hy => exact D.componentWeight_mem_normGroupExpression ak hak i hy
  | zero => exact D.zero_mem_normGroupExpression
  | add x y hx hy hxE hyE => exact D.add_mem_normGroupExpression hxE hyE

/-- The sum of the scaled component defects lies in the ambient norm-group
expression. -/
private theorem componentDefectSum_subset_normGroupExpression
    (D : OrthogonalDecomposition q L t)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (ak : Fin t → Kˣ)
    (hak : ∀ i, IsNormGeneratorValue
      (D.component i).space (D.component i).lattice (ak i)) :
    (D.componentDefectSum a ak : Set K) ⊆ D.normGroupExpression := by
  intro y hy
  change y ∈ ⨆ i, scalarIdeal ((a⁻¹ : Kˣ) : K)
    (quadraticDefectIdeal (a * ak i)) at hy
  induction hy using Submodule.iSup_induction' with
  | mem i y hy =>
      exact D.componentDefect_mem_normGroupExpression a ha ak hak i hy
  | zero => exact D.zero_mem_normGroupExpression
  | add x y hx hy hxE hyE => exact D.add_mem_normGroupExpression hxE hyE

/-- Every element of the candidate weight ideal lies in the ambient
norm-group expression. -/
private theorem weightIdealExpression_subset_normGroupExpression
    (D : OrthogonalDecomposition q L t)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (ak : Fin t → Kˣ)
    (hak : ∀ i, IsNormGeneratorValue
      (D.component i).space (D.component i).lattice (ak i)) :
    (D.weightIdealExpression a ak : Set K) ⊆ D.normGroupExpression := by
  intro y hy
  change y ∈ D.componentWeightSum ⊔ D.componentDefectSum a ak ⊔
    twoScaleIdeal q L at hy
  rcases Submodule.mem_sup.mp hy with ⟨u, hu, v, hv, rfl⟩
  rcases Submodule.mem_sup.mp hu with ⟨w, hw, d, hd, rfl⟩
  exact D.add_twoScale_mem_normGroupExpression
    (D.add_mem_normGroupExpression
      (D.componentWeightSum_subset_normGroupExpression ak hak hw)
      (D.componentDefectSum_subset_normGroupExpression a ha ak hak hd)) hv

/-- The candidate square coset is contained in the orthogonal norm-group
expression. -/
theorem weightIdealExpressionCoset_subset_normGroupExpression
    (D : OrthogonalDecomposition q L t)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (ak : Fin t → Kˣ)
    (hak : ∀ i, IsNormGeneratorValue
      (D.component i).space (D.component i).lattice (ak i)) :
    integralSquareCoset (a : K) (D.weightIdealExpression a ak) ⊆
      D.normGroupExpression := by
  rintro z ⟨c, y, hy, rfl⟩
  exact D.add_mem_normGroupExpression
    (D.normGeneratorSquare_mem_normGroupExpression a ha c)
    (D.weightIdealExpression_subset_normGroupExpression a ha ak hak hy)

/-- O'Meara's p. 280 calculation for a finite orthogonal sum, in the exact
set form needed for Beli's Lemma 2.11. -/
theorem normGroupExpression_eq_weightIdealExpressionCoset
    (D : OrthogonalDecomposition q L t)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (ak : Fin t → Kˣ)
    (hak : ∀ i, IsNormGeneratorValue
      (D.component i).space (D.component i).lattice (ak i)) :
    D.normGroupExpression =
      integralSquareCoset (a : K) (D.weightIdealExpression a ak) := by
  exact Set.Subset.antisymm
    (D.normGroupExpression_subset_weightIdealExpressionCoset a ha ak hak)
    (D.weightIdealExpressionCoset_subset_normGroupExpression a ha ak hak)

/-! ## Power-ideal and parity calculation -/

/-- A power ideal satisfies the ambient weight alternative when it is either
the ambient `2sL` ideal or has order of parity opposite to the ambient norm
order. -/
def SatisfiesAmbientWeightAlternative (a : Kˣ)
    (T I : CoefficientIdeal (K := K)) : Prop :=
  ∃ r : Int, I = powerIdeal (K := K) r ∧
    (I = T ∨ Odd (ordUnit K a + r))

/-- The ambient weight alternative is stable under taking the supremum of two
candidate ideals. -/
theorem satisfiesAmbientWeightAlternative_sup
    (a : Kˣ) {T I J : CoefficientIdeal (K := K)}
    (hI : SatisfiesAmbientWeightAlternative a T I)
    (hJ : SatisfiesAmbientWeightAlternative a T J) :
    SatisfiesAmbientWeightAlternative a T (I ⊔ J) := by
  rcases hI with ⟨r, hIr, hIT | hIodd⟩
  · rcases hJ with ⟨s, hJs, hJT | hJodd⟩
    · refine ⟨min r s, ?_, Or.inl ?_⟩
      · rw [hIr, hJs, sup_powerIdeal]
      · rw [hIT, hJT, sup_idem]
    · have hcarrier : I ⊔ J = powerIdeal (K := K) (min r s) := by
        rw [hIr, hJs, sup_powerIdeal]
      refine ⟨min r s, hcarrier, ?_⟩
      by_cases hrs : r ≤ s
      · refine Or.inl ?_
        rw [hcarrier, min_eq_left hrs]
        exact (hIT.symm.trans hIr).symm
      · exact Or.inr (by
          simpa only [min_eq_right (le_of_not_ge hrs)] using hJodd)
  · rcases hJ with ⟨s, hJs, hJT | hJodd⟩
    · have hcarrier : I ⊔ J = powerIdeal (K := K) (min r s) := by
        rw [hIr, hJs, sup_powerIdeal]
      refine ⟨min r s, hcarrier, ?_⟩
      by_cases hsr : s ≤ r
      · refine Or.inl ?_
        rw [hcarrier, min_eq_right hsr]
        exact (hJT.symm.trans hJs).symm
      · exact Or.inr (by
          simpa only [min_eq_left (le_of_not_ge hsr)] using hIodd)
    · have hcarrier : I ⊔ J = powerIdeal (K := K) (min r s) := by
        rw [hIr, hJs, sup_powerIdeal]
      refine ⟨min r s, hcarrier, Or.inr ?_⟩
      by_cases hrs : r ≤ s
      · simpa only [min_eq_left hrs] using hIodd
      · simpa only [min_eq_right (le_of_not_ge hrs)] using hJodd

/-- A single scaled component defect, together with ambient `2sL`, satisfies
the required power-ideal/parity alternative. -/
theorem componentDefect_sup_twoScale_satisfiesAlternative
    (D : OrthogonalDecomposition q L t)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (ak : Fin t → Kˣ)
    (hak : ∀ i, IsNormGeneratorValue
      (D.component i).space (D.component i).lattice (ak i))
    (i : Fin t) :
    SatisfiesAmbientWeightAlternative a (twoScaleIdeal q L)
      (scalarIdeal ((a⁻¹ : Kˣ) : K)
        (quadraticDefectIdeal (a * ak i)) ⊔ twoScaleIdeal q L) := by
  let di : Int := ordUnit K (ak i) +
    (quadraticDefect K (a * ak i)).toNat
  let T : Int := canonicalTwoScaleOrder q L
  have hab := D.normGeneratorOrder_le_componentNormGeneratorOrder
    a ha ak hak i
  have hT : twoScaleIdeal q L = powerIdeal (K := K) T := by
    simpa only [T] using twoScaleIdeal_eq_powerIdeal_canonicalTwoScaleOrder ha
  by_cases htop : quadraticDefect K (a * ak i) = ⊤
  · have hD := scaledQuadraticDefectIdeal_eq_bot_of_eq_top a (ak i) htop
    refine ⟨T, ?_, Or.inl ?_⟩
    · rw [hD, bot_sup_eq, hT]
    · rw [hD, bot_sup_eq]
  · have hD : scalarIdeal ((a⁻¹ : Kˣ) : K)
        (quadraticDefectIdeal (a * ak i)) =
        powerIdeal (K := K) di := by
      simpa only [di] using
        scaledQuadraticDefectIdeal_eq_powerIdeal_of_ne_top a (ak i) htop
    have hcarrier : scalarIdeal ((a⁻¹ : Kˣ) : K)
          (quadraticDefectIdeal (a * ak i)) ⊔ twoScaleIdeal q L =
        powerIdeal (K := K) (min di T) := by
      rw [hD, hT, sup_powerIdeal]
    refine ⟨min di T, hcarrier, ?_⟩
    by_cases hTdi : T ≤ di
    · refine Or.inl ?_
      rw [hcarrier, min_eq_right hTdi]
      exact hT.symm
    · refine Or.inr ?_
      have hdiT : di < T := lt_of_not_ge hTdi
      have hscaleLeNorm : canonicalScaleOrder q L ≤
          canonicalNormOrder q L := by
        have hle := normIdeal_le_scaleIdeal q L
        rw [normIdeal_eq_powerIdeal_canonicalNormOrder ha,
          scaleIdeal_eq_powerIdeal_canonicalScaleOrder ha,
          powerIdeal_le_iff] at hle
        exact hle
      have hTLe : T ≤ ordUnit K a + ramificationIndex K := by
        dsimp only [T, canonicalTwoScaleOrder]
        rw [ordUnit_eq_canonicalNormOrder ha]
        omega
      have hodd := odd_normOrder_add_scaledDefectOrder_of_lt
        a (ak i) hab htop (by
          simpa only [di] using hdiT.trans_le hTLe)
      simpa only [min_eq_left hdiT.le, di] using hodd

/-- The selected component weight satisfies its own `2s`/parity alternative,
independently of which lawful weight implementation is in scope. -/
theorem componentWeight_eq_twoScale_or_odd
    (D : OrthogonalDecomposition q L t)
    (ak : Fin t → Kˣ)
    (hak : ∀ i, IsNormGeneratorValue
      (D.component i).space (D.component i).lattice (ak i))
    (i : Fin t) :
    weightIdeal (D.component i).space (D.component i).lattice =
        twoScaleIdeal (D.component i).space (D.component i).lattice ∨
      Odd (ordUnit K (ak i) +
        weightIdealOrder (D.component i).space (D.component i).lattice) := by
  have hconditions := (beli2009Lemma210 (ak i) (hak i)
    (Beli2009WeightIdealData.weight (D.component i).space
      (D.component i).lattice)
    (twoScaleIdeal_le_weightIdeal (D.component i).space
      (D.component i).lattice)).mp rfl
  exact hconditions.2

/-- For one component, its weight, scaled defect, and ambient `2sL` together
satisfy the ambient power-ideal/parity alternative. -/
theorem componentWeightDefect_sup_twoScale_satisfiesAlternative
    (D : OrthogonalDecomposition q L t)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (ak : Fin t → Kˣ)
    (hak : ∀ i, IsNormGeneratorValue
      (D.component i).space (D.component i).lattice (ak i))
    (i : Fin t) :
    SatisfiesAmbientWeightAlternative a (twoScaleIdeal q L)
      (weightIdeal (D.component i).space (D.component i).lattice ⊔
        scalarIdeal ((a⁻¹ : Kˣ) : K)
          (quadraticDefectIdeal (a * ak i)) ⊔ twoScaleIdeal q L) := by
  have hdefect := D.componentDefect_sup_twoScale_satisfiesAlternative
    a ha ak hak i
  rcases D.componentWeight_eq_twoScale_or_odd ak hak i with
    hweightTwo | hweightOdd
  · have hweightLeT :
        weightIdeal (D.component i).space (D.component i).lattice ≤
          twoScaleIdeal q L :=
      hweightTwo.le.trans (D.component_twoScaleIdeal_le i)
    have hweightLe :
        weightIdeal (D.component i).space (D.component i).lattice ≤
          scalarIdeal ((a⁻¹ : Kˣ) : K)
            (quadraticDefectIdeal (a * ak i)) ⊔ twoScaleIdeal q L :=
      hweightLeT.trans (by
        intro x hx
        exact Submodule.mem_sup_right hx)
    rw [sup_assoc, sup_eq_right.mpr hweightLe]
    exact hdefect
  · let wi : Int := weightIdealOrder (D.component i).space
      (D.component i).lattice
    by_cases hambientOdd : Odd (ordUnit K a + wi)
    · have hweight : SatisfiesAmbientWeightAlternative a
          (twoScaleIdeal q L)
          (weightIdeal (D.component i).space (D.component i).lattice) := by
        refine ⟨wi, ?_, Or.inr hambientOdd⟩
        simpa only [wi] using
          weightIdeal_eq_powerIdeal (D.component i).space
            (D.component i).lattice
      have hsup := satisfiesAmbientWeightAlternative_sup a hweight hdefect
      simpa only [sup_assoc] using hsup
    · have hambientEven : Even (ordUnit K a + wi) := by
        rcases Int.even_or_odd (ordUnit K a + wi) with heven | hodd
        · exact heven
        · exact False.elim (hambientOdd hodd)
      have hproductOdd : Odd (ordUnit K (a * ak i)) := by
        rcases hweightOdd with ⟨m, hm⟩
        rcases hambientEven with ⟨n, hn⟩
        rw [ordUnit_mul]
        refine ⟨m - n + ordUnit K a, ?_⟩
        dsimp only [wi] at hn
        omega
      have hdefectZero : quadraticDefect K (a * ak i) = 0 :=
        quadraticDefect_eq_zero_of_odd_ordUnit (K := K) (a * ak i)
          hproductOdd
      have hfinite : quadraticDefect K (a * ak i) ≠ ⊤ := by
        rw [hdefectZero]
        exact ENat.zero_ne_top
      have hdefectEq : scalarIdeal ((a⁻¹ : Kˣ) : K)
          (quadraticDefectIdeal (a * ak i)) =
          powerIdeal (K := K) (ordUnit K (ak i)) := by
        rw [scaledQuadraticDefectIdeal_eq_powerIdeal_of_ne_top
          a (ak i) hfinite, hdefectZero]
        simp
      have horder := normGeneratorOrder_le_weightIdealOrder
        (ak i) (hak i)
      have hweightLeDefect :
          weightIdeal (D.component i).space (D.component i).lattice ≤
            scalarIdeal ((a⁻¹ : Kˣ) : K)
              (quadraticDefectIdeal (a * ak i)) := by
        rw [weightIdeal_eq_powerIdeal, hdefectEq]
        exact (powerIdeal_le_iff _ _).2 horder
      rw [sup_eq_right.mpr hweightLeDefect]
      exact hdefect

/-- The weight-plus-defect contribution of one component. -/
noncomputable def componentWeightDefectIdeal
    (D : OrthogonalDecomposition q L t) (a : Kˣ)
    (ak : Fin t → Kˣ) (i : Fin t) : CoefficientIdeal (K := K) :=
  weightIdeal (D.component i).space (D.component i).lattice ⊔
    scalarIdeal ((a⁻¹ : Kˣ) : K)
      (quadraticDefectIdeal (a * ak i))

/-- Finite suprema of the component candidates retain the power-ideal/parity
alternative, with ambient `2sL` as the base case. -/
private theorem finsetComponentWeightDefect_sup_twoScale_satisfiesAlternative
    (D : OrthogonalDecomposition q L t)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (ak : Fin t → Kˣ)
    (hak : ∀ i, IsNormGeneratorValue
      (D.component i).space (D.component i).lattice (ak i))
    (s : Finset (Fin t)) :
    SatisfiesAmbientWeightAlternative a (twoScaleIdeal q L)
      (s.sup (D.componentWeightDefectIdeal a ak) ⊔ twoScaleIdeal q L) := by
  classical
  induction s using Finset.induction_on with
  | empty =>
      have hT : twoScaleIdeal q L = powerIdeal (K := K)
          (canonicalTwoScaleOrder q L) :=
        twoScaleIdeal_eq_powerIdeal_canonicalTwoScaleOrder ha
      have hbase : SatisfiesAmbientWeightAlternative a (twoScaleIdeal q L)
          (twoScaleIdeal q L) :=
        ⟨canonicalTwoScaleOrder q L, hT, Or.inl rfl⟩
      simpa only [Finset.sup_empty, bot_sup_eq] using hbase
  | @insert i s hi ih =>
      have hiAlt := D.componentWeightDefect_sup_twoScale_satisfiesAlternative
        a ha ak hak i
      change SatisfiesAmbientWeightAlternative a (twoScaleIdeal q L)
        (D.componentWeightDefectIdeal a ak i ⊔ twoScaleIdeal q L) at hiAlt
      have hcombined := satisfiesAmbientWeightAlternative_sup a hiAlt ih
      simpa only [Finset.sup_insert, sup_assoc, sup_left_comm, sup_comm,
        sup_idem] using hcombined

/-- The complete ideal in Lemma 2.11 is a power ideal and satisfies the
ambient `2sL`/odd-parity alternative. -/
theorem weightIdealExpression_satisfiesAlternative
    (D : OrthogonalDecomposition q L t)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (ak : Fin t → Kˣ)
    (hak : ∀ i, IsNormGeneratorValue
      (D.component i).space (D.component i).lattice (ak i)) :
    SatisfiesAmbientWeightAlternative a (twoScaleIdeal q L)
      (D.weightIdealExpression a ak) := by
  classical
  have hfin := D.finsetComponentWeightDefect_sup_twoScale_satisfiesAlternative
    a ha ak hak Finset.univ
  rw [Finset.sup_univ_eq_iSup] at hfin
  have hterms : (⨆ i, D.componentWeightDefectIdeal a ak i) =
      (⨆ i, weightIdeal (D.component i).space (D.component i).lattice) ⊔
        (⨆ i, scalarIdeal ((a⁻¹ : Kˣ) : K)
          (quadraticDefectIdeal (a * ak i))) := by
    unfold componentWeightDefectIdeal
    exact iSup_sup_eq
  rw [hterms] at hfin
  change SatisfiesAmbientWeightAlternative a (twoScaleIdeal q L)
    ((⨆ i, weightIdeal (D.component i).space (D.component i).lattice) ⊔
      (⨆ i, scalarIdeal ((a⁻¹ : Kˣ) : K)
        (quadraticDefectIdeal (a * ak i))) ⊔ twoScaleIdeal q L)
  exact hfin

/-- Beli's second formula in Lemma 2.11: the selected ambient weight is the
sum of the component weights, scaled defects, and ambient `2sL`. -/
theorem weightIdeal_eq_weightIdealExpression
    (D : OrthogonalDecomposition q L t)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (ak : Fin t → Kˣ)
    (hak : ∀ i, IsNormGeneratorValue
      (D.component i).space (D.component i).lattice (ak i)) :
    weightIdeal q L = D.weightIdealExpression a ak := by
  rcases D.weightIdealExpression_satisfiesAlternative a ha ak hak with
    ⟨r, hpower, halternative⟩
  let w : OrderedFractionalIdeal K :=
    { carrier := D.weightIdealExpression a ak
      order := r
      carrier_eq_powerIdeal := hpower }
  have hw : twoScaleIdeal q L ≤ w.carrier := by
    change twoScaleIdeal q L ≤ D.weightIdealExpression a ak
    exact D.twoScaleIdeal_le_weightIdealExpression a ak
  have hgroup : normGroupSet q L =
      integralSquareCoset (a : K) w.carrier := by
    change normGroupSet q L =
      integralSquareCoset (a : K) (D.weightIdealExpression a ak)
    rw [D.normGroupSet_eq_normGroupExpression]
    exact D.normGroupExpression_eq_weightIdealExpressionCoset a ha ak hak
  have hconditions : SatisfiesWeightIdealConditions q L a w := by
    constructor
    · exact hgroup
    · change D.weightIdealExpression a ak = twoScaleIdeal q L ∨
        Odd (ordUnit K a + r)
      exact halternative
  have heq := (beli2009Lemma210 a ha w hw).mpr hconditions
  exact heq.symm

/-- Every component weight ideal is contained in the ambient weight ideal.
This is the direct componentwise consequence of Beli's Lemma 2.11 used in
the enlarged-fundamental-lattice argument of Beli (2019), Lemma 5.13. -/
theorem componentWeight_le_weightIdeal
    (D : OrthogonalDecomposition q L t)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (ak : Fin t → Kˣ)
    (hak : ∀ i, IsNormGeneratorValue
      (D.component i).space (D.component i).lattice (ak i))
    (i : Fin t) :
    weightIdeal (D.component i).space (D.component i).lattice ≤
      weightIdeal q L := by
  rw [D.weightIdeal_eq_weightIdealExpression a ha ak hak]
  exact D.componentWeight_le_weightIdealExpression a ak i

/-- Beli (2009/2010), Lemma 2.11, with both formulas proved. -/
theorem beli2009Lemma211_proof
    (D : OrthogonalDecomposition q L t)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (ak : Fin t → Kˣ)
    (hak : ∀ i, IsNormGeneratorValue
      (D.component i).space (D.component i).lattice (ak i)) :
    normGroupSet q L = D.normGroupExpression ∧
      weightIdeal q L = D.weightIdealExpression a ak := by
  exact ⟨D.normGroupSet_eq_normGroupExpression,
    D.weightIdeal_eq_weightIdealExpression a ha ak hak⟩

end OrthogonalDecomposition
end Lattice

/-- The unconditional global instance closing Beli's Lemma 2.11 interface. -/
noncomputable instance beli2009OrthogonalIdealLawsProved :
    Beli2009OrthogonalIdealLaws.{u, v} K where
  lemma211 := Lattice.OrthogonalDecomposition.beli2009Lemma211_proof

end Bong
