/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.Beli2009JordanIdeals
import Bong.Lattice.ScaleGenerator

/-!
# O'Meara 93A: the norm group and the weight ideal

This file starts the unconditional proof of Beli (2009/2010), Lemma 2.10.
The first layer records the actual additive structure of
`gL = Q(L) + 2 sL` and the elementary ideal calculations used by the
canonical construction of `wL`.
-/

namespace Bong

open Dyadic

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]

namespace Lattice

/-- Multiplication by two sends a principal coefficient ideal to the
principal ideal generated by twice its generator. -/
theorem twiceIdeal_principalIdeal (a : K) :
    twiceIdeal (principalIdeal (K := K) a) =
      principalIdeal (K := K) ((2 : K) * a) := by
  rw [twiceIdeal, principalIdeal, Submodule.map_span]
  change Submodule.span (IntegerRing K)
      ((twoMulLinearMap (K := K)) '' {a}) =
    Submodule.span (IntegerRing K) {((2 : K) * a)}
  rw [Set.image_singleton]
  congr 2

/-- Changing the sign of a generator does not change its principal
coefficient ideal. -/
theorem principalIdeal_neg (a : K) :
    principalIdeal (K := K) (-a) = principalIdeal (K := K) a := by
  change Submodule.span (IntegerRing K) {-a} =
    Submodule.span (IntegerRing K) {a}
  have hset : ({-a} : Set K) = -({a} : Set K) := by
    ext z
    simp
  rw [hset, Submodule.span_neg]

/-- Multiplication by two shifts the order of a power ideal by the
ramification index. -/
theorem twiceIdeal_powerIdeal (r : Int) :
    twiceIdeal (powerIdeal (K := K) r) =
      powerIdeal (K := K) (r + ramificationIndex K) := by
  rw [powerIdeal, twiceIdeal_principalIdeal]
  let c : Kˣ := Units.mk0
    ((2 : K) * (uniformizerPowerUnit K r : K))
    (mul_ne_zero (OfNat.ofNat_ne_zero 2)
      (Units.ne_zero (uniformizerPowerUnit K r)))
  change principalIdeal (K := K) (c : K) = _
  rw [principalIdeal_eq_powerIdeal c]
  congr 2
  apply WithTop.coe_injective
  rw [coe_ordUnit]
  change ord K ((2 : K) *
    (uniformizerPowerUnit K r : K)) =
      ((r + ramificationIndex K : Int) : WithTop Int)
  rw [ord_mul, ← ramificationIndex_spec, ← coe_ordUnit,
    ordUnit_uniformizerPowerUnit]
  simp [add_comm]

/-- The ideal `2sL` is contained in the norm ideal. -/
theorem twoScaleIdeal_le_normIdeal (q : QuadraticSpace K V)
    (L : Lattice K V) :
    twoScaleIdeal q L ≤ normIdeal q L := by
  rintro z ⟨y, hy, rfl⟩
  exact two_smul_mem_normIdeal q L hy

/-- Every element of `2sL` belongs to the norm group. -/
theorem twoScaleIdeal_subset_normGroupSet (q : QuadraticSpace K V)
    (L : Lattice K V) :
    (twoScaleIdeal q L : Set K) ⊆ normGroupSet q L := by
  intro z hz
  refine ⟨0, L.zero_mem, z, hz, ?_⟩
  simp

/-- Every element of the norm group belongs to the norm ideal. -/
theorem normGroupSet_subset_normIdeal (q : QuadraticSpace K V)
    (L : Lattice K V) :
    normGroupSet q L ⊆ normIdeal q L := by
  rintro z ⟨x, hx, y, hy, rfl⟩
  exact (normIdeal q L).add_mem
    (quadratic_mem_normIdeal_of_mem q L hx)
    (twoScaleIdeal_le_normIdeal q L hy)

/-- The norm group contains zero. -/
theorem zero_mem_normGroupSet (q : QuadraticSpace K V)
    (L : Lattice K V) : (0 : K) ∈ normGroupSet q L := by
  exact twoScaleIdeal_subset_normGroupSet q L (Submodule.zero_mem _)

/-- The norm group is closed under addition. -/
theorem add_mem_normGroupSet (q : QuadraticSpace K V)
    (L : Lattice K V) {z w : K}
    (hz : z ∈ normGroupSet q L) (hw : w ∈ normGroupSet q L) :
    z + w ∈ normGroupSet q L := by
  rcases hz with ⟨x, hx, y, hy, rfl⟩
  rcases hw with ⟨x', hx', y', hy', rfl⟩
  refine ⟨x + x', L.add_mem hx hx',
    y + y' - (2 : K) * q.bilin x x', ?_, ?_⟩
  · apply (twoScaleIdeal q L).sub_mem
      ((twoScaleIdeal q L).add_mem hy hy')
    refine ⟨q.bilin x x',
      bilin_mem_scaleIdeal_of_mem q L hx hx', ?_⟩
    change ((2 : IntegerRing K) : K) * q.bilin x x' =
      (2 : K) * q.bilin x x'
    have htwo : ((2 : IntegerRing K) : K) = (2 : K) := rfl
    rw [htwo]
  · rw [q.quadratic_add]
    change q.quadratic x + y + (q.quadratic x' + y') =
      q.quadratic x + q.quadratic x' +
        (2 : K) * q.bilin x x' +
        (y + y' - (2 : K) * q.bilin x x')
    ring

/-- The norm group is closed under negation. -/
theorem neg_mem_normGroupSet (q : QuadraticSpace K V)
    (L : Lattice K V) {z : K} (hz : z ∈ normGroupSet q L) :
    -z ∈ normGroupSet q L := by
  rcases hz with ⟨x, hx, y, hy, rfl⟩
  refine ⟨x, hx, -y - (2 : K) * q.quadratic x, ?_, ?_⟩
  · apply (twoScaleIdeal q L).sub_mem
      ((twoScaleIdeal q L).neg_mem hy)
    refine ⟨q.quadratic x,
      ?_, ?_⟩
    · change q.bilin x x ∈ scaleIdeal q L
      exact bilin_mem_scaleIdeal_of_mem q L hx hx
    · change ((2 : IntegerRing K) : K) * q.quadratic x =
        (2 : K) * q.quadratic x
      have htwo : ((2 : IntegerRing K) : K) = (2 : K) := rfl
      rw [htwo]
  · change -(q.quadratic x + y) =
      q.quadratic x + (-y - (2 : K) * q.quadratic x)
    ring

/-- The norm group is closed under subtraction. -/
theorem sub_mem_normGroupSet (q : QuadraticSpace K V)
    (L : Lattice K V) {z w : K}
    (hz : z ∈ normGroupSet q L) (hw : w ∈ normGroupSet q L) :
    z - w ∈ normGroupSet q L := by
  rw [sub_eq_add_neg]
  exact add_mem_normGroupSet q L hz (neg_mem_normGroupSet q L hw)

/-- Multiplication by an integral square preserves the norm group. -/
theorem integralSquare_mul_mem_normGroupSet
    (q : QuadraticSpace K V) (L : Lattice K V)
    {z : K} (hz : z ∈ normGroupSet q L) (c : IntegerRing K) :
    (c : K) ^ 2 * z ∈ normGroupSet q L := by
  rcases hz with ⟨x, hx, y, hy, rfl⟩
  refine ⟨c • x, L.smul_mem c hx,
    (c : K) ^ 2 * y, ?_, ?_⟩
  · rcases hy with ⟨s, hs, rfl⟩
    refine ⟨(c : K) ^ 2 * s, ?_, ?_⟩
    · exact (scaleIdeal q L).smul_mem (c ^ 2) hs
    · simp only [twoMulLinearMap_apply, Algebra.smul_def]
      ring
  · rw [← IsScalarTower.algebraMap_smul K c x, q.quadratic_smul]
    rw [mul_add]
    have hcoe : algebraMap (IntegerRing K) K c = (c : K) := rfl
    rw [hcoe]

/-- A norm-generator value and all of its integral-square multiples lie in
the norm group. -/
theorem normGeneratorValue_integralSquare_mem_normGroupSet
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (ha : IsNormGeneratorValue q L a) (c : IntegerRing K) :
    (a : K) * (c : K) ^ 2 ∈ normGroupSet q L := by
  have h := integralSquare_mul_mem_normGroupSet q L ha.1 c
  simpa [mul_comm] using h

/-- An actual norm-generator vector gives O'Meara's scalar norm generator. -/
theorem IsNormGenerator.isNormGeneratorValue
    {q : QuadraticSpace K V} {L : Lattice K V} {x : V}
    (hx : IsNormGenerator q L x) (hne : q.quadratic x ≠ 0) :
    IsNormGeneratorValue q L (Units.mk0 (q.quadratic x) hne) := by
  constructor
  · refine ⟨x, hx.mem, 0, Submodule.zero_mem _, ?_⟩
    simp
  · simpa using hx.normIdeal_eq

/-- O'Meara 93:5: the negative of a scalar norm generator is again a
scalar norm generator. -/
theorem IsNormGeneratorValue.neg
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (ha : IsNormGeneratorValue q L a) :
    IsNormGeneratorValue q L (-a) := by
  constructor
  · simpa using neg_mem_normGroupSet q L ha.1
  · rw [ha.2]
    simpa using (principalIdeal_neg (K := K) (a : K)).symm

/-! ## Canonical orders of the norm and scale ideals -/

/-- There is a nonzero norm-generator value.  This predicate is separated
from a particular choice so that the definitions below also cover the
zero-dimensional lattice. -/
def HasNormGeneratorValue (q : QuadraticSpace K V)
    (L : Lattice K V) : Prop :=
  ∃ a : Kˣ, IsNormGeneratorValue q L a

/-- A canonical norm-generator value when one exists, and `1` in the
zero-dimensional fallback case. -/
noncomputable def canonicalNormGeneratorValue
    (q : QuadraticSpace K V) (L : Lattice K V) : Kˣ := by
  classical
  exact if h : HasNormGeneratorValue q L then Classical.choose h else 1

theorem canonicalNormGeneratorValue_spec
    {q : QuadraticSpace K V} {L : Lattice K V}
    (h : HasNormGeneratorValue q L) :
    IsNormGeneratorValue q L (canonicalNormGeneratorValue q L) := by
  rw [canonicalNormGeneratorValue, dif_pos h]
  exact Classical.choose_spec h

/-- A nonzero scalar generating the norm ideal forces positive rank. -/
theorem finrank_pos_of_isNormGeneratorValue
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (ha : IsNormGeneratorValue q L a) :
    0 < Module.finrank K V := by
  letI : Module.Finite K V := L.moduleFinite
  by_contra hnot
  have hzero : Module.finrank K V = 0 := Nat.eq_zero_of_not_pos hnot
  letI : Subsingleton V := Module.finrank_zero_iff.mp hzero
  have hnormBot : normIdeal q L = ⊥ := by
    apply le_antisymm
    · rw [normIdeal, Submodule.span_le]
      rintro _ ⟨x, rfl⟩
      have hx : (x : V) = 0 := Subsingleton.elim _ _
      simp [hx]
    · exact bot_le
  have haMem : (a : K) ∈ normIdeal q L := by
    rw [ha.2]
    exact generator_mem_principalIdeal (a : K)
  rw [hnormBot] at haMem
  exact Units.ne_zero a (by simpa using haMem)

/-- A nonzero scalar is a scale-generator value when it is represented by
an actual scale-generator pair. -/
def IsScaleGeneratorValue (q : QuadraticSpace K V) (L : Lattice K V)
    (s : Kˣ) : Prop :=
  ∃ x y : V, IsScaleGenerator q L x y ∧
    q.bilin x y = (s : K)

/-- A canonical scale-generator value when one exists, and `1` in the
zero-dimensional fallback case. -/
noncomputable def canonicalScaleGeneratorValue
    (q : QuadraticSpace K V) (L : Lattice K V) : Kˣ := by
  classical
  exact if h : ∃ s : Kˣ, IsScaleGeneratorValue q L s then
      Classical.choose h
    else 1

theorem canonicalScaleGeneratorValue_spec
    {q : QuadraticSpace K V} {L : Lattice K V}
    (h : ∃ s : Kˣ, IsScaleGeneratorValue q L s) :
    IsScaleGeneratorValue q L (canonicalScaleGeneratorValue q L) := by
  rw [canonicalScaleGeneratorValue, dif_pos h]
  exact Classical.choose_spec h

/-- A norm-generator value supplies the positive-rank hypothesis needed
for the canonical scale generator. -/
theorem exists_scaleGeneratorValue_of_isNormGeneratorValue
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (ha : IsNormGeneratorValue q L a) :
    ∃ s : Kˣ, IsScaleGeneratorValue q L s := by
  have hfin := finrank_pos_of_isNormGeneratorValue ha
  rcases exists_isScaleGenerator_of_finrank_pos q L hfin with
    ⟨x, y, hxy, hne⟩
  let s : Kˣ := Units.mk0 (q.bilin x y) hne
  exact ⟨s, x, y, hxy, rfl⟩

/-- The order of the norm ideal, defined canonically whenever the lattice
is nonzero. -/
noncomputable def canonicalNormOrder
    (q : QuadraticSpace K V) (L : Lattice K V) : Int :=
  ordUnit K (canonicalNormGeneratorValue q L)

/-- The order of the scale ideal, defined canonically whenever the lattice
is nonzero. -/
noncomputable def canonicalScaleOrder
    (q : QuadraticSpace K V) (L : Lattice K V) : Int :=
  ordUnit K (canonicalScaleGeneratorValue q L)

/-- The order of `2sL`. -/
noncomputable def canonicalTwoScaleOrder
    (q : QuadraticSpace K V) (L : Lattice K V) : Int :=
  canonicalScaleOrder q L + ramificationIndex K

theorem normIdeal_eq_powerIdeal_canonicalNormOrder
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (ha : IsNormGeneratorValue q L a) :
    normIdeal q L = powerIdeal (K := K) (canonicalNormOrder q L) := by
  have hexists : HasNormGeneratorValue q L := ⟨a, ha⟩
  have hc := canonicalNormGeneratorValue_spec hexists
  calc
    normIdeal q L = principalIdeal (K := K)
        (canonicalNormGeneratorValue q L : K) := hc.2
    _ = powerIdeal (K := K) (canonicalNormOrder q L) := by
      rw [canonicalNormOrder, principalIdeal_eq_powerIdeal]

theorem ordUnit_eq_canonicalNormOrder
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (ha : IsNormGeneratorValue q L a) :
    ordUnit K a = canonicalNormOrder q L := by
  have hexists : HasNormGeneratorValue q L := ⟨a, ha⟩
  have hc := canonicalNormGeneratorValue_spec hexists
  have haIdeal : normIdeal q L = principalIdeal (K := K) (a : K) := ha.2
  have hcIdeal : normIdeal q L = principalIdeal (K := K)
      (canonicalNormGeneratorValue q L : K) := hc.2
  exact (principalIdeal_eq_iff_ordUnit_eq _ _).mp
    (haIdeal.symm.trans hcIdeal)

theorem scaleIdeal_eq_powerIdeal_canonicalScaleOrder
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (ha : IsNormGeneratorValue q L a) :
    scaleIdeal q L = powerIdeal (K := K) (canonicalScaleOrder q L) := by
  have hexists := exists_scaleGeneratorValue_of_isNormGeneratorValue ha
  rcases canonicalScaleGeneratorValue_spec hexists with
    ⟨x, y, hxy, hvalue⟩
  rw [canonicalScaleOrder, ← principalIdeal_eq_powerIdeal
    (canonicalScaleGeneratorValue q L), ← hvalue]
  exact hxy.scaleIdeal_eq

theorem twoScaleIdeal_eq_powerIdeal_canonicalTwoScaleOrder
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (ha : IsNormGeneratorValue q L a) :
    twoScaleIdeal q L =
      powerIdeal (K := K) (canonicalTwoScaleOrder q L) := by
  rw [twoScaleIdeal,
    scaleIdeal_eq_powerIdeal_canonicalScaleOrder ha,
    twiceIdeal_powerIdeal, canonicalTwoScaleOrder]

/-- The norm order is at most the order of `2sL`, i.e. `2sL ⊆ nL`. -/
theorem canonicalNormOrder_le_canonicalTwoScaleOrder
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (ha : IsNormGeneratorValue q L a) :
    canonicalNormOrder q L ≤ canonicalTwoScaleOrder q L := by
  have hle := twoScaleIdeal_le_normIdeal q L
  rw [twoScaleIdeal_eq_powerIdeal_canonicalTwoScaleOrder ha,
    normIdeal_eq_powerIdeal_canonicalNormOrder ha,
    powerIdeal_le_iff] at hle
  exact hle

/-! ## The canonical weight order -/

/-- The finite interval between the norm order and the order of `2sL`. -/
noncomputable def canonicalWeightSearchBound
    (q : QuadraticSpace K V) (L : Lattice K V) : Nat :=
  Int.toNat (canonicalTwoScaleOrder q L - canonicalNormOrder q L)

/-- At offset `n` there is a norm-group element whose order has parity
opposite to the norm order. -/
def HasOppositeParityNormGroupOrderAtOffset
    (q : QuadraticSpace K V) (L : Lattice K V) (n : Nat) : Prop :=
  Odd n ∧ ∃ z : Kˣ,
    (z : K) ∈ normGroupSet q L ∧
      ordUnit K z = canonicalNormOrder q L + (n : Int)

/-- The first opposite-parity norm-group order, with the order of `2sL`
as the terminal fallback.  This is O'Meara's computational description
93:5 of the weight. -/
noncomputable def canonicalWeightOffset
    (q : QuadraticSpace K V) (L : Lattice K V) : Nat := by
  classical
  exact Nat.find (show ∃ n : Nat,
      n = canonicalWeightSearchBound q L ∨
        HasOppositeParityNormGroupOrderAtOffset q L n from
    ⟨canonicalWeightSearchBound q L, Or.inl rfl⟩)

theorem canonicalWeightOffset_spec
    (q : QuadraticSpace K V) (L : Lattice K V) :
    canonicalWeightOffset q L = canonicalWeightSearchBound q L ∨
      HasOppositeParityNormGroupOrderAtOffset q L
        (canonicalWeightOffset q L) := by
  classical
  unfold canonicalWeightOffset
  exact Nat.find_spec (show ∃ n : Nat,
      n = canonicalWeightSearchBound q L ∨
        HasOppositeParityNormGroupOrderAtOffset q L n from
    ⟨canonicalWeightSearchBound q L, Or.inl rfl⟩)

theorem canonicalWeightOffset_le_searchBound
    (q : QuadraticSpace K V) (L : Lattice K V) :
    canonicalWeightOffset q L ≤ canonicalWeightSearchBound q L := by
  classical
  unfold canonicalWeightOffset
  apply Nat.find_le
  exact Or.inl rfl

theorem canonicalWeightSearchBound_cast
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (ha : IsNormGeneratorValue q L a) :
    (canonicalWeightSearchBound q L : Int) =
      canonicalTwoScaleOrder q L - canonicalNormOrder q L := by
  rw [canonicalWeightSearchBound, Int.toNat_of_nonneg]
  exact sub_nonneg.mpr
    (canonicalNormOrder_le_canonicalTwoScaleOrder ha)

/-- The canonical weight order.  The zero-dimensional fallback is `0`;
it is irrelevant to Lemma 2.10, whose hypotheses include a norm generator. -/
noncomputable def canonicalWeightOrder
    (q : QuadraticSpace K V) (L : Lattice K V) : Int := by
  classical
  exact if HasNormGeneratorValue q L then
      canonicalNormOrder q L + (canonicalWeightOffset q L : Int)
    else 0

theorem canonicalWeightOrder_eq
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (ha : IsNormGeneratorValue q L a) :
    canonicalWeightOrder q L =
      canonicalNormOrder q L + (canonicalWeightOffset q L : Int) := by
  rw [canonicalWeightOrder, if_pos (show HasNormGeneratorValue q L from
    ⟨a, ha⟩)]

theorem canonicalWeightOrder_le_twoScaleOrder
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (ha : IsNormGeneratorValue q L a) :
    canonicalWeightOrder q L ≤ canonicalTwoScaleOrder q L := by
  rw [canonicalWeightOrder_eq ha]
  have hoff := canonicalWeightOffset_le_searchBound q L
  have hbound := canonicalWeightSearchBound_cast ha
  have hoffI : (canonicalWeightOffset q L : Int) ≤
      (canonicalWeightSearchBound q L : Int) := by
    exact_mod_cast hoff
  rw [hbound] at hoffI
  omega

/-- The canonical weight ideal as a nonzero fractional power ideal. -/
noncomputable def canonicalWeightIdeal
    (q : QuadraticSpace K V) (L : Lattice K V) :
    OrderedFractionalIdeal K where
  carrier := powerIdeal (K := K) (canonicalWeightOrder q L)
  order := canonicalWeightOrder q L
  carrier_eq_powerIdeal := rfl

theorem scaleIdeal_eq_bot_of_not_hasNormGeneratorValue
    {q : QuadraticSpace K V} {L : Lattice K V}
    (h : ¬HasNormGeneratorValue q L) :
    scaleIdeal q L = ⊥ := by
  letI : Module.Finite K V := L.moduleFinite
  have hzero : Module.finrank K V = 0 := by
    by_contra hne
    have hpos : 0 < Module.finrank K V := Nat.pos_of_ne_zero hne
    rcases exists_isNormGenerator_of_finrank_pos q L hpos with
      ⟨x, hx, han⟩
    let a : Kˣ := Units.mk0 (q.quadratic x) han
    apply h
    refine ⟨a, ?_, ?_⟩
    · refine ⟨x, hx.mem, 0, Submodule.zero_mem _, ?_⟩
      simp [a]
    · simpa [a] using hx.normIdeal_eq
  letI : Subsingleton V := (Module.finrank_zero_iff.mp hzero)
  apply le_antisymm
  · rw [scaleIdeal, Submodule.span_le]
    rintro _ ⟨p, rfl⟩
    have hx : (p.1 : V) = 0 := Subsingleton.elim _ _
    have hy : (p.2 : V) = 0 := Subsingleton.elim _ _
    simp [hx, hy]
  · exact bot_le

theorem twoScaleIdeal_eq_bot_of_not_hasNormGeneratorValue
    {q : QuadraticSpace K V} {L : Lattice K V}
    (h : ¬HasNormGeneratorValue q L) :
    twoScaleIdeal q L = ⊥ := by
  rw [twoScaleIdeal, scaleIdeal_eq_bot_of_not_hasNormGeneratorValue h]
  simp [twiceIdeal]

/-- The canonical weight contains `2sL`, including the zero-dimensional
fallback case. -/
theorem twoScaleIdeal_le_canonicalWeightIdeal
    (q : QuadraticSpace K V) (L : Lattice K V) :
    twoScaleIdeal q L ≤ (canonicalWeightIdeal q L).carrier := by
  classical
  by_cases h : HasNormGeneratorValue q L
  · rcases h with ⟨a, ha⟩
    rw [twoScaleIdeal_eq_powerIdeal_canonicalTwoScaleOrder ha]
    exact (powerIdeal_le_iff _ _).2
      (canonicalWeightOrder_le_twoScaleOrder ha)
  · rw [twoScaleIdeal_eq_bot_of_not_hasNormGeneratorValue h]
    exact bot_le

/-- If the terminal fallback is selected, the canonical weight is exactly
`2sL`. -/
theorem canonicalWeightIdeal_eq_twoScaleIdeal_of_offset_eq
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (ha : IsNormGeneratorValue q L a)
    (hoff : canonicalWeightOffset q L =
      canonicalWeightSearchBound q L) :
    (canonicalWeightIdeal q L).carrier = twoScaleIdeal q L := by
  change powerIdeal (K := K) (canonicalWeightOrder q L) =
    twoScaleIdeal q L
  rw [twoScaleIdeal_eq_powerIdeal_canonicalTwoScaleOrder ha,
    canonicalWeightOrder_eq ha, hoff]
  have hcast := canonicalWeightSearchBound_cast ha
  have hexponent : canonicalNormOrder q L +
      (canonicalWeightSearchBound q L : Int) =
      canonicalTwoScaleOrder q L := by
    omega
  rw [hexponent]

/-- If an opposite-parity order is selected before the terminal fallback,
the norm order plus the weight order is odd. -/
theorem odd_normOrder_add_canonicalWeightOrder_of_offset
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (ha : IsNormGeneratorValue q L a)
    (hopp : HasOppositeParityNormGroupOrderAtOffset q L
      (canonicalWeightOffset q L)) :
    Odd (ordUnit K a + canonicalWeightOrder q L) := by
  rw [ordUnit_eq_canonicalNormOrder ha,
    canonicalWeightOrder_eq ha]
  rcases hopp.1 with ⟨m, hm⟩
  refine ⟨canonicalNormOrder q L + m, ?_⟩
  push_cast
  omega

/-- The canonical weight satisfies the parity/`2sL` alternative in
O'Meara 93A. -/
theorem canonicalWeightIdeal_eq_twoScale_or_odd
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (ha : IsNormGeneratorValue q L a) :
    (canonicalWeightIdeal q L).carrier = twoScaleIdeal q L ∨
      Odd (ordUnit K a + (canonicalWeightIdeal q L).order) := by
  rcases canonicalWeightOffset_spec q L with hoff | hopp
  · exact Or.inl
      (canonicalWeightIdeal_eq_twoScaleIdeal_of_offset_eq ha hoff)
  · exact Or.inr
      (odd_normOrder_add_canonicalWeightOrder_of_offset ha hopp)

/-! ## Square approximation and O'Meara 93:4 -/

/-- If two nonzero scalars have ordered valuations of the same parity, an
integral square multiple of the first agrees with the second to strictly
higher order.  This is the precise residue-field approximation used in
O'Meara 93A. -/
theorem exists_integral_square_approximation_of_even_order_difference
    (a z : Kˣ) (hle : ordUnit K a ≤ ordUnit K z)
    (heven : Even (ordUnit K z - ordUnit K a)) :
    ∃ c : IntegerRing K,
      (ordUnit K z : WithTop Int) <
        ord K ((z : K) - (a : K) * (c : K) ^ 2) := by
  rcases heven with ⟨k, hk⟩
  have hkNonneg : 0 ≤ k := by omega
  let p : Kˣ := uniformizerPowerUnit K k
  let denominator : Kˣ := a * p ^ 2
  let ratio : Kˣ := z / denominator
  have hpOrder : ordUnit K p = k := by
    exact ordUnit_uniformizerPowerUnit k
  have hdenominatorOrder : ordUnit K denominator = ordUnit K z := by
    dsimp [denominator]
    rw [ordUnit_mul, ordUnit_pow, hpOrder]
    omega
  have hratioOrder : ordUnit K ratio = 0 := by
    dsimp [ratio]
    rw [div_eq_mul_inv, ordUnit_mul, ordUnit_inv,
      hdenominatorOrder]
    omega
  have hratioUnit : IsValuationUnit K (ratio : K) :=
    (isValuationUnit_iff_ordUnit_eq_zero K ratio).2 hratioOrder
  rcases exists_unit_squareRoot_mod_maximal K ratio hratioUnit with
    ⟨r, hrUnit, hrError⟩
  have hpOrderField : ord K (p : K) = (k : WithTop Int) := by
    rw [← coe_ordUnit, hpOrder]
  have hprIntegral : Dyadic.IsIntegral K ((p : K) * r) := by
    rw [Dyadic.IsIntegral, ord_mul, hpOrderField, hrUnit]
    have hkTop : (0 : WithTop Int) ≤ (k : WithTop Int) := by
      exact_mod_cast hkNonneg
    simpa using hkTop
  let c : IntegerRing K :=
    ⟨(p : K) * r, (mem_integerRing_iff K).2 hprIntegral⟩
  refine ⟨c, ?_⟩
  have hfactor :
      (z : K) - (a : K) * (c : K) ^ 2 =
        (denominator : K) * ((ratio : K) - r ^ 2) := by
    change (z : K) - (a : K) * ((p : K) * r) ^ 2 =
      ((a * p ^ 2 : Kˣ) : K) *
        (((z / (a * p ^ 2) : Kˣ) : K) - r ^ 2)
    simp only [Units.val_mul, Units.val_pow_eq_pow_val,
      Units.val_div_eq_div_val]
    field_simp [Units.ne_zero a, Units.ne_zero p]
  have herror : IsInMaximalIdeal K ((ratio : K) - r ^ 2) := by
    have hneg : (ratio : K) - r ^ 2 = -(r ^ 2 - (ratio : K)) := by ring
    rw [hneg, IsInMaximalIdeal, ord_neg]
    exact hrError
  by_cases hzero : (ratio : K) - r ^ 2 = 0
  · rw [hfactor, hzero, mul_zero, ord_zero]
    exact WithTop.coe_lt_top _
  · let errorUnit : Kˣ := Units.mk0 ((ratio : K) - r ^ 2) hzero
    have herrorOrder : ord K ((ratio : K) - r ^ 2) =
        (ordUnit K errorUnit : WithTop Int) := by
      simpa [errorUnit] using (coe_ordUnit K errorUnit).symm
    have herrorPos : 0 < ordUnit K errorUnit := by
      apply WithTop.coe_lt_coe.mp
      rw [← herrorOrder]
      exact herror
    have hdenominatorOrderField : ord K (denominator : K) =
        (ordUnit K z : WithTop Int) := by
      rw [← coe_ordUnit, hdenominatorOrder]
    rw [hfactor, ord_mul, hdenominatorOrderField, herrorOrder]
    exact_mod_cast (show ordUnit K z <
      ordUnit K z + ordUnit K errorUnit by omega)

/-- Any witnessed opposite-parity order bounds the first such order selected
by the canonical search. -/
theorem canonicalWeightOffset_le_of_oppositeParityOrder
    {q : QuadraticSpace K V} {L : Lattice K V} {n : Nat}
    (h : HasOppositeParityNormGroupOrderAtOffset q L n) :
    canonicalWeightOffset q L ≤ n := by
  classical
  unfold canonicalWeightOffset
  apply Nat.find_le
  exact Or.inr h

/-- Every nonzero element of the norm group has order at least the norm
order. -/
theorem canonicalNormOrder_le_ordUnit_of_mem_normGroupSet
    {q : QuadraticSpace K V} {L : Lattice K V} {a z : Kˣ}
    (ha : IsNormGeneratorValue q L a)
    (hz : (z : K) ∈ normGroupSet q L) :
    canonicalNormOrder q L ≤ ordUnit K z := by
  have hzIdeal := normGroupSet_subset_normIdeal q L hz
  rw [normIdeal_eq_powerIdeal_canonicalNormOrder ha] at hzIdeal
  change (z : K) ∈ powerIdeal (K := K)
    (canonicalNormOrder q L) at hzIdeal
  rw [mem_powerIdeal_iff, ← coe_ordUnit] at hzIdeal
  exact WithTop.coe_le_coe.mp hzIdeal

/-- O'Meara 93:4 for the canonical weight: every norm-group element is an
integral square multiple of a fixed norm generator modulo the weight ideal. -/
theorem normGroupSet_subset_integralSquareCoset_canonicalWeight
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (ha : IsNormGeneratorValue q L a) :
    normGroupSet q L ⊆
      integralSquareCoset (a : K) (canonicalWeightIdeal q L).carrier := by
  intro z hz
  by_cases hzZero : z = 0
  · subst z
    refine ⟨0, 0, Submodule.zero_mem _, ?_⟩
    simp
  let zUnit : Kˣ := Units.mk0 z hzZero
  let B := canonicalWeightOrder q L
  have haux : ∀ m : Nat, ∀ x : K,
      ∀ (hx : x ∈ normGroupSet q L), ∀ (hxZero : x ≠ 0),
      Int.toNat (B - ordUnit K (Units.mk0 x hxZero)) = m →
      x ∈ integralSquareCoset (a : K)
        (canonicalWeightIdeal q L).carrier := by
    intro m
    induction m using Nat.strong_induction_on with
    | h m ih =>
      intro x hx hxZero hmeasure
      let xu : Kˣ := Units.mk0 x hxZero
      have hnormLe : canonicalNormOrder q L ≤ ordUnit K xu :=
        canonicalNormOrder_le_ordUnit_of_mem_normGroupSet ha hx
      by_cases hweightLe : B ≤ ordUnit K xu
      · refine ⟨0, x, ?_, by simp⟩
        change x ∈ powerIdeal (K := K) B
        rw [mem_powerIdeal_iff]
        have hxOrder : ord K x =
            (ordUnit K xu : WithTop Int) := by
          simpa [xu] using (coe_ordUnit K xu).symm
        rw [hxOrder]
        exact_mod_cast hweightLe
      · have hxLtWeight : ordUnit K xu < B := lt_of_not_ge hweightLe
        have hgapNonneg : 0 ≤ ordUnit K xu - canonicalNormOrder q L := by
          omega
        rcases Int.even_or_odd
            (ordUnit K xu - canonicalNormOrder q L) with heven | hodd
        · obtain ⟨c, hcApprox⟩ :=
            exists_integral_square_approximation_of_even_order_difference
              (a := a) (z := xu)
              (by rw [ordUnit_eq_canonicalNormOrder ha]; exact hnormLe)
              (by rw [ordUnit_eq_canonicalNormOrder ha]; exact heven)
          let y : K := x - (a : K) * (c : K) ^ 2
          have hyGroup : y ∈ normGroupSet q L := by
            exact sub_mem_normGroupSet q L hx
              (normGeneratorValue_integralSquare_mem_normGroupSet ha c)
          by_cases hyZero : y = 0
          · refine ⟨c, 0, Submodule.zero_mem _, ?_⟩
            dsimp [y] at hyZero
            rw [add_zero]
            exact sub_eq_zero.mp hyZero
          · let yu : Kˣ := Units.mk0 y hyZero
            have hyOrder : ordUnit K xu < ordUnit K yu := by
              apply WithTop.coe_lt_coe.mp
              rw [coe_ordUnit, coe_ordUnit]
              simpa [xu, yu, y] using hcApprox
            by_cases hweightLeY : B ≤ ordUnit K yu
            · refine ⟨c, y, ?_, by simp [y]⟩
              change y ∈ powerIdeal (K := K) B
              rw [mem_powerIdeal_iff]
              have hyOrderField : ord K y =
                  (ordUnit K yu : WithTop Int) := by
                simpa [yu] using (coe_ordUnit K yu).symm
              rw [hyOrderField]
              exact_mod_cast hweightLeY
            · have hyLtWeight : ordUnit K yu < B := lt_of_not_ge hweightLeY
              have hmeasureX : (B - ordUnit K xu).toNat = m := by
                simpa [xu] using hmeasure
              have hmeasureY :
                  (B - ordUnit K yu).toNat < m := by
                rw [← hmeasureX]
                exact (Int.toNat_lt_toNat (by omega)).2 (by omega)
              have hyCoset := ih
                ((B - ordUnit K yu).toNat) hmeasureY y hyGroup hyZero rfl
              rcases hyCoset with ⟨d, w, hw, hyEq⟩
              have hcd : ((c + d : IntegerRing K) : K) ^ 2 =
                  (c : K) ^ 2 + (d : K) ^ 2 +
                    (2 : K) * (c : K) * (d : K) := by
                have hcoeC : algebraMap (IntegerRing K) K c = (c : K) := rfl
                have hcoeD : algebraMap (IntegerRing K) K d = (d : K) := rfl
                change (algebraMap (IntegerRing K) K (c + d)) ^ 2 = _
                rw [map_add, hcoeC, hcoeD]
                ring
              let cross : K :=
                (a : K) * ((2 : K) * (c : K) * (d : K))
              have hcrossTwoScale : cross ∈ twoScaleIdeal q L := by
                have haScale : (a : K) ∈ scaleIdeal q L := by
                  exact normIdeal_le_scaleIdeal q L (by
                    rw [ha.2]
                    exact generator_mem_principalIdeal (a : K))
                refine ⟨(c * d) • (a : K),
                  (scaleIdeal q L).smul_mem (c * d) haScale, ?_⟩
                dsimp [cross]
                simp only [twoMulLinearMap_apply, Algebra.smul_def,
                  map_mul]
                have hcoeC : algebraMap (IntegerRing K) K c = (c : K) := rfl
                have hcoeD : algebraMap (IntegerRing K) K d = (d : K) := rfl
                have htwo : algebraMap (IntegerRing K) K
                    (2 : IntegerRing K) = (2 : K) := rfl
                rw [hcoeC, hcoeD, htwo]
                ring
              have hcross : cross ∈
                  (canonicalWeightIdeal q L).carrier :=
                twoScaleIdeal_le_canonicalWeightIdeal q L hcrossTwoScale
              refine ⟨c + d, w - cross,
                (canonicalWeightIdeal q L).carrier.sub_mem hw hcross, ?_⟩
              calc
                x = (a : K) * (c : K) ^ 2 + y := by
                  dsimp [y]
                  ring
                _ = (a : K) * (c : K) ^ 2 +
                    ((a : K) * (d : K) ^ 2 + w) := by rw [hyEq]
                _ = (a : K) * ((c + d : IntegerRing K) : K) ^ 2 +
                    (w - cross) := by
                  rw [hcd]
                  dsimp [cross]
                  ring
        · let n := Int.toNat
              (ordUnit K xu - canonicalNormOrder q L)
          have hnCast : (n : Int) =
              ordUnit K xu - canonicalNormOrder q L := by
            exact Int.toNat_of_nonneg hgapNonneg
          have hnOdd : Odd n := by
            rcases hodd with ⟨k, hk⟩
            have hkNonneg : 0 ≤ k := by omega
            refine ⟨k.toNat, ?_⟩
            have hkCast := Int.toNat_of_nonneg hkNonneg
            omega
          have hnOpposite :
              HasOppositeParityNormGroupOrderAtOffset q L n := by
            refine ⟨hnOdd, xu, ?_, ?_⟩
            · simpa [xu] using hx
            · omega
          have hoffLe :=
            canonicalWeightOffset_le_of_oppositeParityOrder hnOpposite
          dsimp [B] at hxLtWeight
          rw [canonicalWeightOrder_eq ha] at hxLtWeight
          have hnLt : n < canonicalWeightOffset q L := by
            exact_mod_cast (show (n : Int) <
              (canonicalWeightOffset q L : Int) by omega)
          exact False.elim ((not_lt_of_ge hoffLe) hnLt)
  exact haux (Int.toNat (B - ordUnit K zUnit)) z hz hzZero rfl

/-- Every element of the canonical weight ideal belongs to the norm group. -/
theorem canonicalWeightIdeal_subset_normGroupSet
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (ha : IsNormGeneratorValue q L a) :
    ((canonicalWeightIdeal q L).carrier : Set K) ⊆ normGroupSet q L := by
  rcases canonicalWeightOffset_spec q L with hoff | hopp
  · rw [canonicalWeightIdeal_eq_twoScaleIdeal_of_offset_eq ha hoff]
    exact twoScaleIdeal_subset_normGroupSet q L
  · rcases hopp.2 with ⟨b, hbGroup, hbOrder⟩
    let A := canonicalNormOrder q L
    let B := canonicalWeightOrder q L
    let T := canonicalTwoScaleOrder q L
    have hBOrder : ordUnit K b = B := by
      dsimp [B]
      rw [canonicalWeightOrder_eq ha, ← hbOrder]
    have hAOrder : ordUnit K a = A := by
      exact ordUnit_eq_canonicalNormOrder ha
    have hBLeT : B ≤ T := canonicalWeightOrder_le_twoScaleOrder ha
    intro x hxWeight
    by_cases hxZero : x = 0
    · subst x
      exact zero_mem_normGroupSet q L
    let xu : Kˣ := Units.mk0 x hxZero
    have hxWeight' : x ∈ powerIdeal (K := K) B := by
      exact hxWeight
    have hBLeX : B ≤ ordUnit K xu := by
      rw [mem_powerIdeal_iff] at hxWeight'
      have hxOrder : ord K x =
          (ordUnit K xu : WithTop Int) := by
        simpa [xu] using (coe_ordUnit K xu).symm
      rw [hxOrder] at hxWeight'
      exact WithTop.coe_le_coe.mp hxWeight'
    have haux : ∀ m : Nat, ∀ y : K, ∀ (hyZero : y ≠ 0),
        B ≤ ordUnit K (Units.mk0 y hyZero) →
        Int.toNat (T - ordUnit K (Units.mk0 y hyZero)) = m →
        y ∈ normGroupSet q L := by
      intro m
      induction m using Nat.strong_induction_on with
      | h m ih =>
        intro y hyZero hBLeY hmeasure
        let yu : Kˣ := Units.mk0 y hyZero
        by_cases hTLeY : T ≤ ordUnit K yu
        · apply twoScaleIdeal_subset_normGroupSet q L
          rw [twoScaleIdeal_eq_powerIdeal_canonicalTwoScaleOrder ha]
          change y ∈ powerIdeal (K := K) (canonicalTwoScaleOrder q L)
          rw [mem_powerIdeal_iff]
          have hyOrder : ord K y =
              (ordUnit K yu : WithTop Int) := by
            simpa [yu] using (coe_ordUnit K yu).symm
          rw [hyOrder]
          exact_mod_cast hTLeY
        · have hyLtT : ordUnit K yu < T := lt_of_not_ge hTLeY
          rcases Int.even_or_odd (ordUnit K yu - A) with heven | hodd
          · have hALeB : A ≤ B := by
              dsimp [A, B]
              rw [canonicalWeightOrder_eq ha]
              omega
            have hALeY : A ≤ ordUnit K yu := hALeB.trans hBLeY
            obtain ⟨c, hcApprox⟩ :=
              exists_integral_square_approximation_of_even_order_difference
                (a := a) (z := yu) (by rw [hAOrder]; exact hALeY)
                (by rw [hAOrder]; exact heven)
            let r : K := y - (a : K) * (c : K) ^ 2
            have hbase : (a : K) * (c : K) ^ 2 ∈ normGroupSet q L :=
              normGeneratorValue_integralSquare_mem_normGroupSet ha c
            by_cases hrZero : r = 0
            · dsimp [r] at hrZero
              have hyEq : y = (a : K) * (c : K) ^ 2 :=
                sub_eq_zero.mp hrZero
              rwa [hyEq]
            · let ru : Kˣ := Units.mk0 r hrZero
              have hrOrder : ordUnit K yu < ordUnit K ru := by
                apply WithTop.coe_lt_coe.mp
                rw [coe_ordUnit, coe_ordUnit]
                simpa [yu, ru, r] using hcApprox
              have hBLeR : B ≤ ordUnit K ru := le_trans hBLeY hrOrder.le
              have hmeasureY : (T - ordUnit K yu).toNat = m := by
                simpa [yu] using hmeasure
              have hrGroup : r ∈ normGroupSet q L := by
                by_cases hTLeR : T ≤ ordUnit K ru
                · apply twoScaleIdeal_subset_normGroupSet q L
                  rw [twoScaleIdeal_eq_powerIdeal_canonicalTwoScaleOrder ha]
                  change r ∈ powerIdeal (K := K)
                    (canonicalTwoScaleOrder q L)
                  rw [mem_powerIdeal_iff]
                  have hrOrderField : ord K r =
                      (ordUnit K ru : WithTop Int) := by
                    simpa [ru] using (coe_ordUnit K ru).symm
                  rw [hrOrderField]
                  exact_mod_cast hTLeR
                · have hrLtT : ordUnit K ru < T := lt_of_not_ge hTLeR
                  have hmeasureR :
                      (T - ordUnit K ru).toNat < m := by
                    rw [← hmeasureY]
                    exact (Int.toNat_lt_toNat (by omega)).2 (by omega)
                  exact ih ((T - ordUnit K ru).toNat) hmeasureR
                    r hrZero hBLeR rfl
              have hyEq : y = (a : K) * (c : K) ^ 2 + r := by
                dsimp [r]
                ring
              rw [hyEq]
              exact add_mem_normGroupSet q L hbase hrGroup
          · have hoffOdd : Odd (canonicalWeightOffset q L) := hopp.1
            have hgapB : B - A =
                (canonicalWeightOffset q L : Int) := by
              dsimp [A, B]
              rw [canonicalWeightOrder_eq ha]
              omega
            have hgapBOdd : Odd (B - A) := by
              rcases hoffOdd with ⟨k, hk⟩
              refine ⟨(k : Int), ?_⟩
              rw [hgapB]
              exact_mod_cast hk
            have hevenB : Even (ordUnit K yu - B) := by
              rcases hodd with ⟨r, hr⟩
              rcases hgapBOdd with ⟨s, hs⟩
              refine ⟨r - s, ?_⟩
              omega
            obtain ⟨c, hcApprox⟩ :=
              exists_integral_square_approximation_of_even_order_difference
                (a := b) (z := yu) (by rw [hBOrder]; exact hBLeY)
                (by rw [hBOrder]; exact hevenB)
            let r : K := y - (b : K) * (c : K) ^ 2
            have hbase : (b : K) * (c : K) ^ 2 ∈ normGroupSet q L := by
              have h := integralSquare_mul_mem_normGroupSet q L hbGroup c
              simpa [mul_comm] using h
            by_cases hrZero : r = 0
            · dsimp [r] at hrZero
              have hyEq : y = (b : K) * (c : K) ^ 2 :=
                sub_eq_zero.mp hrZero
              rwa [hyEq]
            · let ru : Kˣ := Units.mk0 r hrZero
              have hrOrder : ordUnit K yu < ordUnit K ru := by
                apply WithTop.coe_lt_coe.mp
                rw [coe_ordUnit, coe_ordUnit]
                simpa [yu, ru, r] using hcApprox
              have hBLeR : B ≤ ordUnit K ru := le_trans hBLeY hrOrder.le
              have hmeasureY : (T - ordUnit K yu).toNat = m := by
                simpa [yu] using hmeasure
              have hrGroup : r ∈ normGroupSet q L := by
                by_cases hTLeR : T ≤ ordUnit K ru
                · apply twoScaleIdeal_subset_normGroupSet q L
                  rw [twoScaleIdeal_eq_powerIdeal_canonicalTwoScaleOrder ha]
                  change r ∈ powerIdeal (K := K)
                    (canonicalTwoScaleOrder q L)
                  rw [mem_powerIdeal_iff]
                  have hrOrderField : ord K r =
                      (ordUnit K ru : WithTop Int) := by
                    simpa [ru] using (coe_ordUnit K ru).symm
                  rw [hrOrderField]
                  exact_mod_cast hTLeR
                · have hrLtT : ordUnit K ru < T := lt_of_not_ge hTLeR
                  have hmeasureR :
                      (T - ordUnit K ru).toNat < m := by
                    rw [← hmeasureY]
                    exact (Int.toNat_lt_toNat (by omega)).2 (by omega)
                  exact ih ((T - ordUnit K ru).toNat) hmeasureR
                    r hrZero hBLeR rfl
              have hyEq : y = (b : K) * (c : K) ^ 2 + r := by
                dsimp [r]
                ring
              rw [hyEq]
              exact add_mem_normGroupSet q L hbase hrGroup
    exact haux (Int.toNat (T - ordUnit K xu)) x hxZero hBLeX rfl

/-- O'Meara 93:4 in exact set form for the canonical construction. -/
theorem normGroupSet_eq_integralSquareCoset_canonicalWeight
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (ha : IsNormGeneratorValue q L a) :
    normGroupSet q L =
      integralSquareCoset (a : K) (canonicalWeightIdeal q L).carrier := by
  apply Set.Subset.antisymm
  · exact normGroupSet_subset_integralSquareCoset_canonicalWeight ha
  · rintro z ⟨c, y, hy, rfl⟩
    exact add_mem_normGroupSet q L
      (normGeneratorValue_integralSquare_mem_normGroupSet ha c)
      (canonicalWeightIdeal_subset_normGroupSet ha hy)

/-! ## Uniqueness and Lemma 2.10 -/

/-- Equality of two fractional power ideals forces equality of their
orders. -/
theorem powerIdeal_order_eq_of_eq {r s : Int}
    (h : powerIdeal (K := K) r = powerIdeal (K := K) s) : r = s := by
  apply le_antisymm
  · exact (powerIdeal_le_iff s r).mp h.symm.le
  · exact (powerIdeal_le_iff r s).mp h.le

/-- An element of parity opposite to the norm order must belong to every
candidate ideal occurring in Lemma 2.10. -/
theorem oppositeParity_normGroup_mem_candidateWeight
    {q : QuadraticSpace K V} {L : Lattice K V} {a z : Kˣ}
    (ha : IsNormGeneratorValue q L a)
    (w : OrderedFractionalIdeal K)
    (hgroup : normGroupSet q L = integralSquareCoset (a : K) w.carrier)
    (hzGroup : (z : K) ∈ normGroupSet q L)
    (hodd : Odd (ordUnit K z - ordUnit K a)) :
    (z : K) ∈ w.carrier := by
  rw [hgroup] at hzGroup
  rcases hzGroup with ⟨c, y, hy, hzEq⟩
  have hyEq : y = (z : K) - (a : K) * (c : K) ^ 2 := by
    rw [hzEq]
    ring
  have hyOrderLe : ord K y ≤ ord K (z : K) := by
    by_contra hnot
    have hzLtY : ord K (z : K) < ord K y := lt_of_not_ge hnot
    have htermOrder : ord K ((a : K) * (c : K) ^ 2) =
        ord K (z : K) := by
      have hdom := (ord K).map_sub_eq_of_lt_left hzLtY
      have htermEq : (a : K) * (c : K) ^ 2 = (z : K) - y := by
        rw [hzEq]
        ring
      rw [htermEq]
      exact hdom
    by_cases hcZero : (c : K) = 0
    · rw [hcZero, zero_pow (by norm_num : (2 : Nat) ≠ 0),
        mul_zero, ord_zero] at htermOrder
      rw [← coe_ordUnit] at htermOrder
      exact WithTop.top_ne_coe htermOrder
    · let cu : Kˣ := Units.mk0 (c : K) hcZero
      have hcOrder : ord K (c : K) =
          (ordUnit K cu : WithTop Int) := by
        simpa [cu] using (coe_ordUnit K cu).symm
      rw [ord_mul, ord_pow, ← coe_ordUnit, hcOrder] at htermOrder
      rw [← coe_ordUnit] at htermOrder
      have horderTop :
          ((ordUnit K a + (ordUnit K cu + ordUnit K cu) : Int) :
              WithTop Int) =
            (ordUnit K z : WithTop Int) := by
        simpa only [two_nsmul, WithTop.coe_add] using htermOrder
      have horderIntAdd : ordUnit K a +
          (ordUnit K cu + ordUnit K cu) = ordUnit K z :=
        WithTop.coe_injective horderTop
      have horderInt : ordUnit K a + 2 * ordUnit K cu =
          ordUnit K z := by omega
      rcases hodd with ⟨k, hk⟩
      omega
  rw [w.carrier_eq_powerIdeal, mem_powerIdeal_iff] at hy ⊢
  exact hy.trans hyOrderLe

/-- A candidate weight ideal satisfying the two conditions of Lemma 2.10
is the canonical weight ideal. -/
theorem candidateWeight_eq_canonicalWeight
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (ha : IsNormGeneratorValue q L a)
    (w : OrderedFractionalIdeal K)
    (hw : twoScaleIdeal q L ≤ w.carrier)
    (hconditions : SatisfiesWeightIdealConditions q L a w) :
    w.carrier = (canonicalWeightIdeal q L).carrier := by
  let A := canonicalNormOrder q L
  let B := canonicalWeightOrder q L
  let T := canonicalTwoScaleOrder q L
  let W := w.order
  have hgroup := hconditions.1
  have halternative := hconditions.2
  have hWLeT : W ≤ T := by
    rw [twoScaleIdeal_eq_powerIdeal_canonicalTwoScaleOrder ha,
      w.carrier_eq_powerIdeal, powerIdeal_le_iff] at hw
    exact hw
  have hBLeT : B ≤ T := canonicalWeightOrder_le_twoScaleOrder ha
  have hcandidateSubset : (w.carrier : Set K) ⊆ normGroupSet q L := by
    intro y hy
    rw [hgroup]
    exact ⟨0, y, hy, by simp⟩
  have hWLeB : W ≤ B := by
    rcases canonicalWeightOffset_spec q L with hoff | hopp
    · have hBT : B = T := by
        dsimp [B, T]
        rw [canonicalWeightOrder_eq ha, hoff]
        have hcast := canonicalWeightSearchBound_cast ha
        omega
      omega
    · rcases hopp.2 with ⟨z, hzGroup, hzOrder⟩
      have hzOdd : Odd (ordUnit K z - ordUnit K a) := by
        rw [ordUnit_eq_canonicalNormOrder ha, hzOrder]
        rcases hopp.1 with ⟨k, hk⟩
        refine ⟨(k : Int), ?_⟩
        have hkInt : (canonicalWeightOffset q L : Int) =
            2 * (k : Int) + 1 := by exact_mod_cast hk
        omega
      have hzMem := oppositeParity_normGroup_mem_candidateWeight
        ha w hgroup hzGroup hzOdd
      rw [w.carrier_eq_powerIdeal, mem_powerIdeal_iff,
        ← coe_ordUnit] at hzMem
      have hzOrderB : ordUnit K z = B := by
        dsimp [B]
        rw [canonicalWeightOrder_eq ha, hzOrder]
      rw [hzOrderB] at hzMem
      exact WithTop.coe_le_coe.mp hzMem
  have hBLeW : B ≤ W := by
    rcases halternative with htwo | hoddSum
    · have hWT : W = T := by
        apply powerIdeal_order_eq_of_eq (K := K)
        rw [← w.carrier_eq_powerIdeal,
          ← twoScaleIdeal_eq_powerIdeal_canonicalTwoScaleOrder ha]
        exact htwo
      rw [hWT]
      exact hBLeT
    · let pW : Kˣ := uniformizerPowerUnit K W
      have hpWMemW : (pW : K) ∈ w.carrier := by
        rw [w.carrier_eq_powerIdeal]
        exact generator_mem_principalIdeal _
      have hpWGroup : (pW : K) ∈ normGroupSet q L :=
        hcandidateSubset hpWMemW
      have hALeW : A ≤ W := by
        have hpWNorm := normGroupSet_subset_normIdeal q L hpWGroup
        rw [normIdeal_eq_powerIdeal_canonicalNormOrder ha] at hpWNorm
        change (pW : K) ∈ powerIdeal (K := K) A at hpWNorm
        rw [mem_powerIdeal_iff, ← coe_ordUnit,
          ordUnit_uniformizerPowerUnit] at hpWNorm
        exact WithTop.coe_le_coe.mp hpWNorm
      have hgapNonneg : 0 ≤ W - A := by omega
      let n := Int.toNat (W - A)
      have hnCast : (n : Int) = W - A :=
        Int.toNat_of_nonneg hgapNonneg
      have hgapOdd : Odd (W - A) := by
        rw [ordUnit_eq_canonicalNormOrder ha] at hoddSum
        rcases hoddSum with ⟨k, hk⟩
        refine ⟨k - A, ?_⟩
        omega
      have hnOdd : Odd n := by
        rcases hgapOdd with ⟨k, hk⟩
        have hkNonneg : 0 ≤ k := by omega
        refine ⟨k.toNat, ?_⟩
        have hkCast := Int.toNat_of_nonneg hkNonneg
        omega
      have hnOpposite :
          HasOppositeParityNormGroupOrderAtOffset q L n := by
        refine ⟨hnOdd, pW, hpWGroup, ?_⟩
        rw [ordUnit_uniformizerPowerUnit]
        omega
      have hoffLe :=
        canonicalWeightOffset_le_of_oppositeParityOrder hnOpposite
      dsimp [B]
      rw [canonicalWeightOrder_eq ha]
      exact_mod_cast (show
        (canonicalNormOrder q L : Int) +
            (canonicalWeightOffset q L : Int) ≤ W by
          dsimp [A] at hnCast
          omega)
  have hWB : W = B := le_antisymm hWLeB hBLeW
  rw [w.carrier_eq_powerIdeal]
  change powerIdeal (K := K) W = powerIdeal (K := K) B
  rw [hWB]

/-- The canonical ideal satisfies the two defining conditions in Lemma
2.10. -/
theorem canonicalWeight_satisfiesWeightIdealConditions
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (ha : IsNormGeneratorValue q L a) :
    SatisfiesWeightIdealConditions q L a (canonicalWeightIdeal q L) := by
  constructor
  · exact normGroupSet_eq_integralSquareCoset_canonicalWeight ha
  · exact canonicalWeightIdeal_eq_twoScale_or_odd ha

/-- Beli (2009/2010), Lemma 2.10, proved from O'Meara 93A. -/
theorem weightIdeal_characterization_proof
    {q : QuadraticSpace K V} {L : Lattice K V}
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (w : OrderedFractionalIdeal K)
    (hw : twoScaleIdeal q L ≤ w.carrier) :
    w.carrier = (canonicalWeightIdeal q L).carrier ↔
      SatisfiesWeightIdealConditions q L a w := by
  constructor
  · intro hcarrier
    have horder : w.order = (canonicalWeightIdeal q L).order := by
      apply powerIdeal_order_eq_of_eq (K := K)
      rw [← w.carrier_eq_powerIdeal,
        ← (canonicalWeightIdeal q L).carrier_eq_powerIdeal]
      exact hcarrier
    unfold SatisfiesWeightIdealConditions
    rw [hcarrier, horder]
    exact canonicalWeight_satisfiesWeightIdealConditions ha
  · exact candidateWeight_eq_canonicalWeight ha w hw

/-- The unconditional global instance closing the weight-ideal interface. -/
noncomputable instance beli2009WeightIdealDataProved :
    Beli2009WeightIdealData.{u, v} K where
  weight := canonicalWeightIdeal
  twoScale_le_weight := twoScaleIdeal_le_canonicalWeightIdeal
  characterize := weightIdeal_characterization_proof

end Lattice

end Bong
