/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.Beli2019Lemma712
import Bong.Bong.UnaryModelBONG
import Bong.Lattice.OrthogonalProductIsometry

/-!
# Beli (2019), Lemma 7.14(ii): the type-II ternary block

This file moves the exact ternary BONG supplied by Lemma 7.12(ii) from its
standard unary--binary model to the literal product of the rescaled initial
binary lattice and the unary lattice generated by `x_(s+1)`.

The binary comparison is integral: the discriminant endpoint model uses the
standard shear `1/2`, while the binary diagonal model uses the shear chosen by
the admissibility witness.  Binary shear uniqueness identifies the two
lattices.  No splitting of the lattice after `x_(s+1)` is assumed here.
-/

namespace Bong

open Dyadic

universe u v w

namespace BONG.GoodBONG

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {W : Type w} [AddCommGroup W] [Module K W]
  {q : QuadraticSpace K V} {r : QuadraticSpace K W}
  {J : Lattice K V} {A : Lattice K W}

/-- The standard discriminant endpoint model and the binary factor occurring
in Lemma 7.12 are the same integral lattice up to the canonical shear. -/
theorem standardDiscriminantEndpoint_isIsometric_lemma712Binary
    [laws : DyadicDiscriminantClassLaws K] (p : Kˣ) :
    Lattice.IsIsometric
      (QuadraticSpace.rescaleUnit p
        (QuadraticSpace.binaryModel
          (lemma712DiscriminantParameter (K := K))
          (standardEndpointShear (K := K))))
      (binaryDiagonalModelSpace p
        (p * lemma712DiscriminantParameter (K := K))
        (lemma712_sourceBinaryAdmissible p))
      (binaryModelLattice (K := K))
      (binaryDiagonalModelLattice (K := K)) := by
  let d := lemma712DiscriminantParameter (K := K)
  let hAdmissible := lemma712_sourceBinaryAdmissible p
  have hratio : (p * d) / p = d := by simp
  have hchosenTwo :
      (2 : K) * admissibleBinaryShear ((p * d) / p) hAdmissible ∈
        IntegerRing K :=
    two_mul_admissibleBinaryShear_mem ((p * d) / p) hAdmissible
  have hchosenDiag :
      admissibleBinaryShear ((p * d) / p) hAdmissible ^ 2 + (d : K) ∈
        IntegerRing K := by
    simpa only [hratio] using
      admissibleBinaryShear_sq_add_mem ((p * d) / p) hAdmissible
  have hshear :
      standardEndpointShear (K := K) -
          admissibleBinaryShear ((p * d) / p) hAdmissible ∈ IntegerRing K :=
    binaryShear_sub_mem_integerRing d
      (standardEndpointShear (K := K))
      (admissibleBinaryShear ((p * d) / p) hAdmissible)
      standardEndpointShear_two_integral
      discriminant_standardEndpointShear_diagonal_integral
      hchosenTwo hchosenDiag
  have hmodel := rescaledBinaryModel_isIsometric_of_shear_sub_integral
    p d (standardEndpointShear (K := K))
      (admissibleBinaryShear ((p * d) / p) hAdmissible) hshear
  simpa only [d, hAdmissible, binaryDiagonalModelSpace,
    binaryDiagonalModelLattice, hratio] using hmodel

/-- A binary BONG in the discriminant endpoint class is isometric to the
exact binary factor used in the generalized Lemma 7.12(ii). -/
theorem isIsometric_lemma712Binary_of_discriminantEndpoint
    [laws : DyadicDiscriminantClassLaws K]
    (j : GoodBONG q J 2)
    (hclass : j.toBONG.binaryUnitSquareClass = unitSquareClass K
      (lemma712DiscriminantParameter (K := K))) :
    Lattice.IsIsometric q
      (binaryDiagonalModelSpace (j.valueUnit 0)
        (j.valueUnit 0 * lemma712DiscriminantParameter (K := K))
        (lemma712_sourceBinaryAdmissible (j.valueUnit 0)))
      J (binaryDiagonalModelLattice (K := K)) := by
  rcases j.toBONG.isIsometric_standardEndpointModel
      (lemma712DiscriminantParameter (K := K)) hclass
      standardEndpointShear_two_integral
      discriminant_standardEndpointShear_diagonal_integral with ⟨f⟩
  rcases standardDiscriminantEndpoint_isIsometric_lemma712Binary
      (j.valueUnit 0) with ⟨g⟩
  exact ⟨f.trans g⟩

/-- Local type-II conclusion of Lemma 7.14(ii).  The resulting good BONG is
defined on the literal lattice product `J ⊥ A`, in binary--unary ambient
order, while its values occur in the unary--binary order of the paper. -/
theorem exists_lemma714_typeII_localGoodBONG
    [laws : DyadicDiscriminantClassLaws K]
    [QuadraticDefectLaws K]
    [DyadicUnramifiedNormLaws K]
    [HilbertSymbolLaws K]
    [DyadicDiagonalClassificationLaws K]
    [BONGStructuralLaws.{u, u} K]
    [Beli2009WeightIdealData.{u, u} K]
    [Beli2019UnaryBinaryJordanLaws.{u} K]
    [Beli2009JordanWeightOrderLaws.{u, u} K]
    [Beli2006AlphaLaws.{u, u} K]
    [BeliLemma43ConstructionLaws.{u, u} K]
    [Beli2006SectionTwoLaws.{u, u} K]
    [GoodBONGClassificationLaws.{u, u, u} K]
    (j : GoodBONG q J 2) (x : GoodBONG r A 1)
    (hp : j.order 0 = x.order 0 + 1)
    (hclass : j.toBONG.binaryUnitSquareClass = unitSquareClass K
      (lemma712DiscriminantParameter (K := K)))
    (ε η : Kˣ)
    (hεUnit : IsValuationUnit K (ε : K))
    (hηUnit : IsValuationUnit K (η : K))
    (hεDefect : defectOrder (K := K) ε = (1 : WithTop ℚ))
    (hηDefect : defectOrder (K := K) η =
      (((2 * (ramificationIndex K : ℚ) - 1 : ℚ)) : WithTop ℚ))
    (hhilbert : hilbertSymbol K ε η = -1) :
    ∃ b : GoodBONG (q.orthogonalSum r) (Lattice.product J A) 3,
      ∀ i, b.valueUnit i = lemma712TargetValues (x.valueUnit 0) ε η i := by
  let p := j.valueUnit 0
  let a := x.valueUnit 0
  have hp' : ordUnit K p = ordUnit K a + 1 := by
    dsimp only [p, a, GoodBONG.valueUnit]
    rw [← j.toBONG.order_eq_ordUnit, ← x.toBONG.order_eq_ordUnit]
    exact hp
  rcases exists_beli2019Lemma712_ii_goodBONG a p ε η hp'
      hεUnit hηUnit hεDefect hηDefect hhilbert with
    ⟨model, hmodelValues⟩
  rcases j.isIsometric_lemma712Binary_of_discriminantEndpoint hclass with ⟨fb⟩
  let fu := x.toBONG.unaryModelLatticeIsometry
  let productToModels := fb.orthogonalProductBasic fu
  let swapModels := Lattice.orthogonalProductSwap
    (q := binaryDiagonalModelSpace p
      (p * lemma712DiscriminantParameter (K := K))
      (lemma712_sourceBinaryAdmissible p))
    (r := QuadraticSpace.rescaleUnit a (QuadraticSpace.line K))
    (L := binaryDiagonalModelLattice (K := K))
    (M := unaryModelLattice (K := K))
  let toModel : Lattice.Isometry (q.orthogonalSum r)
      (unaryBinaryModelSpace a p
        (p * lemma712DiscriminantParameter (K := K))
        (lemma712_sourceBinaryAdmissible p))
      (Lattice.product J A) (unaryBinaryModelLattice (K := K)) := by
    simpa only [unaryBinaryModelSpace, unaryBinaryModelLattice] using
      productToModels.trans swapModels
  let result := model.mapLatticeIsometry toModel.symm
  refine ⟨result, ?_⟩
  intro i
  apply Units.ext
  change (model.toBONG.mapLatticeIsometry toModel.symm).value i =
    ((lemma712TargetValues a ε η i : Kˣ) : K)
  rw [BONG.value_mapLatticeIsometry]
  exact congrArg Units.val (hmodelValues i)

end BONG.GoodBONG

end Bong
