/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.Beli2019Lemma714TypeIICriteria
import Bong.Bong.Beli2019Lemma710OrthogonalSum
import Mathlib.LinearAlgebra.FiniteDimensional.Lemmas

/-!
# Beli (2019), Lemma 7.14(ii): the global type-II orthogonal basis

The exceptional ternary BONG lives on `pi J` together with the coordinate
line generated by `x_(s+1)`.  This file inserts its three ambient vectors into
the full tail space, retaining every other tail vector literally.  The result
is an orthogonal field basis with exactly the coefficient list displayed in
the paper.

At this stage the lattice realized by Beli's Lemma 4.3 is intentionally left
unnamed.  Its identification with `pi J perp L_3` is the separate integral
content of Lemma 7.10.
-/

namespace Bong

open Dyadic
open Module

universe u v

namespace BONG.GoodBONG

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {q : QuadraticSpace K V} {L : Lattice K V} {n : Nat}

private theorem lemma714TypeIIGeometry_two_le_rank (n : Nat) : 2 ≤ n + 3 := by
  omega

/-- Embed a vector of the local binary--unary block into tail--binary order.
The unary coordinate is included into the full tail carrier. -/
noncomputable def lemma714TypeIIEmbedBlockVector
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3) :
    (S.left.carrier ×
      (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier) →ₗ[K]
      (S.right.carrier × S.left.carrier) where
  toFun z := ((z.2 : S.right.carrier), z.1)
  map_add' _ _ := rfl
  map_smul' _ _ := rfl

/-- The complete orthogonal vector family
`x_3,...,x_s,y_(s-1),y_s,y_(s+1),x_(s+2),...,x_N` in the concrete ambient
space `L_3 perp pi J`. -/
noncomputable def lemma714TypeIITargetVector
    [DyadicDiscriminantClassLaws K]
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (block : GoodBONG
      ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).nondegenerate))
      (Lattice.product
        (Lattice.rescale (uniformizerUnit K) S.left.lattice)
        (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).lattice) 3) :
    Fin (n + 3) → (S.right.carrier × S.left.carrier) := fun i =>
  if hprefix : i.val < s - 2 then
    ((b.lemma714Tail S).toBONG.ambientVector
      (Fin.mk i.val (by omega)), 0)
  else if hzero : i.val = s - 2 then
    b.lemma714TypeIIEmbedBlockVector S s hsTwo hsCurrent
      (block.toBONG.ambientVector 0)
  else if hone : i.val = s - 1 then
    b.lemma714TypeIIEmbedBlockVector S s hsTwo hsCurrent
      (block.toBONG.ambientVector 1)
  else if htwo : i.val = s then
    b.lemma714TypeIIEmbedBlockVector S s hsTwo hsCurrent
      (block.toBONG.ambientVector 2)
  else
    ((b.lemma714Tail S).toBONG.ambientVector
      (Fin.mk (i.val - 2) (by omega)), 0)

@[simp]
theorem lemma714TypeIITargetVector_prefix
    [DyadicDiscriminantClassLaws K]
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (block : GoodBONG
      ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).nondegenerate))
      (Lattice.product
        (Lattice.rescale (uniformizerUnit K) S.left.lattice)
        (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).lattice) 3)
    (i : Fin (n + 3)) (hi : i.val < s - 2) :
    lemma714TypeIITargetVector b S s hsTwo hsCurrent block i =
      ((b.lemma714Tail S).toBONG.ambientVector
        (Fin.mk i.val (by omega)), 0) := by
  simp [lemma714TypeIITargetVector, hi]

@[simp]
theorem lemma714TypeIITargetVector_zero
    [DyadicDiscriminantClassLaws K]
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (block : GoodBONG
      ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).nondegenerate))
      (Lattice.product
        (Lattice.rescale (uniformizerUnit K) S.left.lattice)
        (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).lattice) 3) :
    lemma714TypeIITargetVector b S s hsTwo hsCurrent block
        (Fin.mk (s - 2) (by omega)) =
      b.lemma714TypeIIEmbedBlockVector S s hsTwo hsCurrent
        (block.toBONG.ambientVector 0) := by
  simp [lemma714TypeIITargetVector]

@[simp]
theorem lemma714TypeIITargetVector_one
    [DyadicDiscriminantClassLaws K]
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (block : GoodBONG
      ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).nondegenerate))
      (Lattice.product
        (Lattice.rescale (uniformizerUnit K) S.left.lattice)
        (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).lattice) 3) :
    lemma714TypeIITargetVector b S s hsTwo hsCurrent block
        (Fin.mk (s - 1) (by omega)) =
      b.lemma714TypeIIEmbedBlockVector S s hsTwo hsCurrent
        (block.toBONG.ambientVector 1) := by
  have hnotPrefix : ¬s - 1 < s - 2 := by omega
  have hnotZero : s - 1 ≠ s - 2 := by omega
  simp [lemma714TypeIITargetVector, hnotPrefix, hnotZero]

@[simp]
theorem lemma714TypeIITargetVector_two
    [DyadicDiscriminantClassLaws K]
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (block : GoodBONG
      ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).nondegenerate))
      (Lattice.product
        (Lattice.rescale (uniformizerUnit K) S.left.lattice)
        (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).lattice) 3) :
    lemma714TypeIITargetVector b S s hsTwo hsCurrent block
        (Fin.mk s hsCurrent) =
      b.lemma714TypeIIEmbedBlockVector S s hsTwo hsCurrent
        (block.toBONG.ambientVector 2) := by
  have hnotPrefix : ¬s < s - 2 := by omega
  have hnotZero : s ≠ s - 2 := by omega
  have hnotOne : s ≠ s - 1 := by omega
  simp [lemma714TypeIITargetVector, hnotPrefix, hnotZero, hnotOne]

@[simp]
theorem lemma714TypeIITargetVector_suffix
    [DyadicDiscriminantClassLaws K]
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (block : GoodBONG
      ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).nondegenerate))
      (Lattice.product
        (Lattice.rescale (uniformizerUnit K) S.left.lattice)
        (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).lattice) 3)
    (i : Fin (n + 3)) (hi : s < i.val) :
    lemma714TypeIITargetVector b S s hsTwo hsCurrent block i =
      ((b.lemma714Tail S).toBONG.ambientVector
        (Fin.mk (i.val - 2) (by omega)), 0) := by
  have hnotPrefix : ¬i.val < s - 2 := by omega
  have hnotZero : i.val ≠ s - 2 := by omega
  have hnotOne : i.val ≠ s - 1 := by omega
  have hnotTwo : i.val ≠ s := by omega
  simp [lemma714TypeIITargetVector, hnotPrefix, hnotZero, hnotOne,
    hnotTwo]

/-- The local block embedding preserves the quadratic form, with the two
orthogonal factors exchanged. -/
theorem quadratic_lemma714TypeIIEmbedBlockVector
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (z : S.left.carrier ×
      (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier) :
    ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
        (q.restrict S.left.carrier S.left.nondegenerate)).quadratic
      (b.lemma714TypeIIEmbedBlockVector S s hsTwo hsCurrent z) =
    ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).nondegenerate)).quadratic z := by
  rw [QuadraticSpace.orthogonalSum_quadratic_apply,
    QuadraticSpace.orthogonalSum_quadratic_apply]
  change q.quadratic (z.2 : S.right.carrier) + q.quadratic z.1 =
    q.quadratic z.1 + q.quadratic (z.2 : S.right.carrier)
  exact add_comm _ _

/-- The block embedding also preserves the bilinear form after exchanging
the two factors. -/
theorem bilin_lemma714TypeIIEmbedBlockVector
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (z w : S.left.carrier ×
      (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier) :
    ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
        (q.restrict S.left.carrier S.left.nondegenerate)).bilin
      (b.lemma714TypeIIEmbedBlockVector S s hsTwo hsCurrent z)
      (b.lemma714TypeIIEmbedBlockVector S s hsTwo hsCurrent w) =
    ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).nondegenerate)).bilin z w := by
  rw [QuadraticSpace.orthogonalSum_bilin_apply,
    QuadraticSpace.orthogonalSum_bilin_apply]
  change q.bilin (z.2 : S.right.carrier) (w.2 : S.right.carrier) +
      q.bilin z.1 w.1 =
    q.bilin z.1 w.1 + q.bilin (z.2 : S.right.carrier) (w.2 : S.right.carrier)
  exact add_comm _ _

/-- A tail basis vector outside the selected coordinate line is orthogonal
to every vector of that line. -/
theorem lemma714Tail_bilin_typeIILine_eq_zero
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (i : Fin (n + 1)) (hi : i.val ≠ s - 2)
    (z : (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier) :
    (q.restrict S.right.carrier S.right.nondegenerate).bilin
      ((b.lemma714Tail S).toBONG.ambientVector i) (z : S.right.carrier) = 0 := by
  let tail := (b.lemma714Tail S).toBONG
  have hz : (z : S.right.carrier) ∈
      Submodule.span K
        (Set.range (tail.segmentVector (s - 2) 1 (by omega))) := by
    have hz' : (z : S.right.carrier) ∈
        (b.lemma714Tail S).toBONG.segmentCarrier (s - 2) 1 (by omega) :=
      (le_of_eq
        (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier_eq_segmentCarrier)
        z.property
    simpa only [tail, segmentCarrier] using hz'
  refine Submodule.span_induction
    (p := fun y _ ↦
      (q.restrict S.right.carrier S.right.nondegenerate).bilin
        (tail.ambientVector i) y = 0) ?_ ?_ ?_ ?_ hz
  · rintro _ ⟨j, rfl⟩
    apply (LinearMap.BilinForm.iIsOrtho_def.mp tail.ambientVector_iIsOrtho)
    intro hij
    apply hi
    have hval := congrArg Fin.val hij
    simp only [segmentIndex_val] at hval
    have hj : j.val = 0 := by omega
    omega
  · simp
  · intro x y _ _ hx hy
    rw [LinearMap.BilinForm.add_right, hx, hy, add_zero]
  · intro a x _ hx
    rw [LinearMap.BilinForm.smul_right, hx]
    simp

/-- A retained tail vector is orthogonal to an embedded block vector whenever
its coordinate is not the replaced line. -/
theorem lemma714Tail_bilin_embedBlock_eq_zero
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (i : Fin (n + 1)) (hi : i.val ≠ s - 2)
    (z : S.left.carrier ×
      (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier) :
    ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
        (q.restrict S.left.carrier S.left.nondegenerate)).bilin
      ((b.lemma714Tail S).toBONG.ambientVector i, 0)
      (b.lemma714TypeIIEmbedBlockVector S s hsTwo hsCurrent z) = 0 := by
  rw [QuadraticSpace.orthogonalSum_bilin_apply]
  change (q.restrict S.right.carrier S.right.nondegenerate).bilin
      ((b.lemma714Tail S).toBONG.ambientVector i) (z.2 : S.right.carrier) +
    (q.restrict S.left.carrier S.left.nondegenerate).bilin 0 z.1 = 0
  rw [b.lemma714Tail_bilin_typeIILine_eq_zero S s hsTwo hsCurrent i hi]
  simp

/-- Orthogonality in the reverse orientation. -/
theorem lemma714EmbedBlock_bilin_tail_eq_zero
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (i : Fin (n + 1)) (hi : i.val ≠ s - 2)
    (z : S.left.carrier ×
      (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier) :
    ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
        (q.restrict S.left.carrier S.left.nondegenerate)).bilin
      (b.lemma714TypeIIEmbedBlockVector S s hsTwo hsCurrent z)
      ((b.lemma714Tail S).toBONG.ambientVector i, 0) = 0 := by
  rw [((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
    (q.restrict S.left.carrier S.left.nondegenerate)).isSymm.eq]
  exact b.lemma714Tail_bilin_embedBlock_eq_zero S s hsTwo hsCurrent i hi z

/-- Two distinct retained tail coordinates remain orthogonal in the product
ambient space. -/
theorem lemma714TailPair_bilin_eq_zero
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (i j : Fin (n + 1)) (hij : i ≠ j) :
    ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
        (q.restrict S.left.carrier S.left.nondegenerate)).bilin
      ((b.lemma714Tail S).toBONG.ambientVector i, 0)
      ((b.lemma714Tail S).toBONG.ambientVector j, 0) = 0 := by
  rw [QuadraticSpace.orthogonalSum_bilin_apply]
  rw [(LinearMap.BilinForm.iIsOrtho_def.mp
    (b.lemma714Tail S).toBONG.ambientVector_iIsOrtho) i j hij]
  simp

/-- Ordered distinct positions in the inserted family are orthogonal.  The
order assumption reduces the interval analysis to the twelve possible
prefix/block/suffix configurations. -/
theorem lemma714TypeIITargetVector_bilin_eq_zero_of_lt
    [DyadicDiscriminantClassLaws K]
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (block : GoodBONG
      ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).nondegenerate))
      (Lattice.product
        (Lattice.rescale (uniformizerUnit K) S.left.lattice)
        (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).lattice) 3)
    (i j : Fin (n + 3)) (hij : i.val < j.val) :
    ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
        (q.restrict S.left.carrier S.left.nondegenerate)).bilin
      (lemma714TypeIITargetVector b S s hsTwo hsCurrent block i)
      (lemma714TypeIITargetVector b S s hsTwo hsCurrent block j) = 0 := by
  by_cases hiprefix : i.val < s - 2
  · rw [lemma714TypeIITargetVector_prefix b S s hsTwo hsCurrent block i hiprefix]
    by_cases hjprefix : j.val < s - 2
    · rw [lemma714TypeIITargetVector_prefix b S s hsTwo hsCurrent block j hjprefix]
      apply b.lemma714TailPair_bilin_eq_zero S
      intro hindex
      have hval := congrArg Fin.val hindex
      change i.val = j.val at hval
      exact (Nat.ne_of_lt hij) hval
    by_cases hjzero : j.val = s - 2
    · rw [show j = (⟨s - 2, by omega⟩ : Fin (n + 3)) from Fin.ext hjzero,
        lemma714TypeIITargetVector_zero]
      let ii : Fin (n + 1) := ⟨i.val, by omega⟩
      have hiLine : ii.val ≠ s - 2 := by
        dsimp only [ii]
        omega
      exact b.lemma714Tail_bilin_embedBlock_eq_zero S s hsTwo hsCurrent
        ii hiLine (block.toBONG.ambientVector 0)
    by_cases hjone : j.val = s - 1
    · rw [show j = (⟨s - 1, by omega⟩ : Fin (n + 3)) from Fin.ext hjone,
        lemma714TypeIITargetVector_one]
      let ii : Fin (n + 1) := ⟨i.val, by omega⟩
      have hiLine : ii.val ≠ s - 2 := by
        dsimp only [ii]
        omega
      exact b.lemma714Tail_bilin_embedBlock_eq_zero S s hsTwo hsCurrent
        ii hiLine (block.toBONG.ambientVector 1)
    by_cases hjtwo : j.val = s
    · rw [show j = (⟨s, hsCurrent⟩ : Fin (n + 3)) from Fin.ext hjtwo,
        lemma714TypeIITargetVector_two]
      let ii : Fin (n + 1) := ⟨i.val, by omega⟩
      have hiLine : ii.val ≠ s - 2 := by
        dsimp only [ii]
        omega
      exact b.lemma714Tail_bilin_embedBlock_eq_zero S s hsTwo hsCurrent
        ii hiLine (block.toBONG.ambientVector 2)
    · have hjsuffix : s < j.val := by omega
      rw [lemma714TypeIITargetVector_suffix b S s hsTwo hsCurrent block j hjsuffix]
      apply b.lemma714TailPair_bilin_eq_zero S
      intro hindex
      have hval := congrArg Fin.val hindex
      change i.val = j.val - 2 at hval
      omega
  by_cases hizero : i.val = s - 2
  · rw [show i = (⟨s - 2, by omega⟩ : Fin (n + 3)) from Fin.ext hizero,
      lemma714TypeIITargetVector_zero]
    by_cases hjone : j.val = s - 1
    · rw [show j = (⟨s - 1, by omega⟩ : Fin (n + 3)) from Fin.ext hjone,
        lemma714TypeIITargetVector_one,
        bilin_lemma714TypeIIEmbedBlockVector]
      exact (LinearMap.BilinForm.iIsOrtho_def.mp
        block.toBONG.ambientVector_iIsOrtho) 0 1 (by decide)
    by_cases hjtwo : j.val = s
    · rw [show j = (⟨s, hsCurrent⟩ : Fin (n + 3)) from Fin.ext hjtwo,
        lemma714TypeIITargetVector_two,
        bilin_lemma714TypeIIEmbedBlockVector]
      exact (LinearMap.BilinForm.iIsOrtho_def.mp
        block.toBONG.ambientVector_iIsOrtho) 0 2 (by decide)
    · have hjsuffix : s < j.val := by omega
      rw [lemma714TypeIITargetVector_suffix b S s hsTwo hsCurrent block j hjsuffix]
      let jj : Fin (n + 1) := ⟨j.val - 2, by omega⟩
      have hjLine : jj.val ≠ s - 2 := by
        dsimp only [jj]
        omega
      exact b.lemma714EmbedBlock_bilin_tail_eq_zero S s hsTwo hsCurrent
        jj hjLine (block.toBONG.ambientVector 0)
  by_cases hione : i.val = s - 1
  · rw [show i = (⟨s - 1, by omega⟩ : Fin (n + 3)) from Fin.ext hione,
      lemma714TypeIITargetVector_one]
    by_cases hjtwo : j.val = s
    · rw [show j = (⟨s, hsCurrent⟩ : Fin (n + 3)) from Fin.ext hjtwo,
        lemma714TypeIITargetVector_two,
        bilin_lemma714TypeIIEmbedBlockVector]
      exact (LinearMap.BilinForm.iIsOrtho_def.mp
        block.toBONG.ambientVector_iIsOrtho) 1 2 (by decide)
    · have hjsuffix : s < j.val := by omega
      rw [lemma714TypeIITargetVector_suffix b S s hsTwo hsCurrent block j hjsuffix]
      let jj : Fin (n + 1) := ⟨j.val - 2, by omega⟩
      have hjLine : jj.val ≠ s - 2 := by
        dsimp only [jj]
        omega
      exact b.lemma714EmbedBlock_bilin_tail_eq_zero S s hsTwo hsCurrent
        jj hjLine (block.toBONG.ambientVector 1)
  by_cases hitwo : i.val = s
  · have hjsuffix : s < j.val := by omega
    rw [show i = (⟨s, hsCurrent⟩ : Fin (n + 3)) from Fin.ext hitwo,
      lemma714TypeIITargetVector_two,
      lemma714TypeIITargetVector_suffix b S s hsTwo hsCurrent block j hjsuffix]
    let jj : Fin (n + 1) := ⟨j.val - 2, by omega⟩
    have hjLine : jj.val ≠ s - 2 := by
      dsimp only [jj]
      omega
    exact b.lemma714EmbedBlock_bilin_tail_eq_zero S s hsTwo hsCurrent
      jj hjLine (block.toBONG.ambientVector 2)
  · have hisuffix : s < i.val := by omega
    have hjsuffix : s < j.val := by omega
    rw [lemma714TypeIITargetVector_suffix b S s hsTwo hsCurrent block i hisuffix,
      lemma714TypeIITargetVector_suffix b S s hsTwo hsCurrent block j hjsuffix]
    apply b.lemma714TailPair_bilin_eq_zero S
    intro hindex
    have hval := congrArg Fin.val hindex
    change i.val - 2 = j.val - 2 at hval
    omega

/-- The complete inserted family is pairwise orthogonal. -/
theorem lemma714TypeIITargetVector_iIsOrtho
    [DyadicDiscriminantClassLaws K]
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (block : GoodBONG
      ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).nondegenerate))
      (Lattice.product
        (Lattice.rescale (uniformizerUnit K) S.left.lattice)
        (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).lattice) 3) :
    ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
      (q.restrict S.left.carrier S.left.nondegenerate)).bilin.iIsOrtho
        (lemma714TypeIITargetVector b S s hsTwo hsCurrent block) := by
  rw [LinearMap.BilinForm.iIsOrtho_def]
  intro i j hij
  have hvalNe : i.val ≠ j.val := by
    intro h
    exact hij (Fin.ext h)
  rcases lt_or_gt_of_ne hvalNe with hlt | hgt
  · exact b.lemma714TypeIITargetVector_bilin_eq_zero_of_lt
      S s hsTwo hsCurrent block i j hlt
  · rw [((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
      (q.restrict S.left.carrier S.left.nondegenerate)).isSymm.eq]
    exact b.lemma714TypeIITargetVector_bilin_eq_zero_of_lt
      S s hsTwo hsCurrent block j i hgt

/-- The inserted global vector family has exactly the target diagonal
coefficient at every position. -/
theorem quadratic_lemma714TypeIITargetVector
    [DyadicDiscriminantClassLaws K]
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (ε η : Kˣ)
    (block : GoodBONG
      ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).nondegenerate))
      (Lattice.product
        (Lattice.rescale (uniformizerUnit K) S.left.lattice)
        (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).lattice) 3)
    (hblockValues : ∀ i, block.valueUnit i =
      lemma712TargetValues (b.valueUnit ⟨s, hsCurrent⟩) ε η i)
    (i : Fin (n + 3)) :
    ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
        (q.restrict S.left.carrier S.left.nondegenerate)).quadratic
      (lemma714TypeIITargetVector b S s hsTwo hsCurrent block i) =
    (lemma714TypeIITargetValues b s hsTwo hsCurrent ε η i : K) := by
  by_cases hprefix : i.val < s - 2
  · rw [lemma714TypeIITargetVector_prefix b S s hsTwo hsCurrent block i hprefix,
      lemma714TypeIITargetValues_prefix b s hsTwo hsCurrent ε η i hprefix,
      QuadraticSpace.orthogonalSum_quadratic_apply]
    rw [(q.restrict S.left.carrier S.left.nondegenerate).quadratic_zero,
      add_zero, (b.lemma714Tail S).toBONG.quadratic_ambientVector,
      ← BONG.coe_valueUnit]
    change ((b.lemma714Tail S).valueUnit ⟨i.val, by omega⟩ : K) =
      (b.valueUnit ⟨i.val + 2, by omega⟩ : K)
    rw [b.lemma714Tail_valueUnit S]
    congr 2
    apply Fin.ext
    change 2 + i.val = i.val + 2
    omega
  by_cases hzero : i.val = s - 2
  · have hi : i = (⟨s - 2, by omega⟩ : Fin (n + 3)) := Fin.ext hzero
    rw [hi]
    rw [lemma714TypeIITargetVector_zero,
      lemma714TypeIITargetValues_zero,
      quadratic_lemma714TypeIIEmbedBlockVector,
      block.toBONG.quadratic_ambientVector]
    change (block.valueUnit 0 : K) =
      (lemma712TargetValues (b.valueUnit ⟨s, hsCurrent⟩) ε η 0 : K)
    rw [hblockValues]
  by_cases hone : i.val = s - 1
  · have hi : i = (⟨s - 1, by omega⟩ : Fin (n + 3)) := Fin.ext hone
    rw [hi]
    rw [lemma714TypeIITargetVector_one,
      lemma714TypeIITargetValues_one,
      quadratic_lemma714TypeIIEmbedBlockVector,
      block.toBONG.quadratic_ambientVector]
    change (block.valueUnit 1 : K) =
      (lemma712TargetValues (b.valueUnit ⟨s, hsCurrent⟩) ε η 1 : K)
    rw [hblockValues]
  by_cases htwo : i.val = s
  · have hi : i = (⟨s, hsCurrent⟩ : Fin (n + 3)) := Fin.ext htwo
    rw [hi]
    rw [lemma714TypeIITargetVector_two,
      lemma714TypeIITargetValues_two,
      quadratic_lemma714TypeIIEmbedBlockVector,
      block.toBONG.quadratic_ambientVector]
    change (block.valueUnit 2 : K) =
      (lemma712TargetValues (b.valueUnit ⟨s, hsCurrent⟩) ε η 2 : K)
    rw [hblockValues]
  · have hsuffix : s < i.val := by omega
    rw [lemma714TypeIITargetVector_suffix b S s hsTwo hsCurrent block i hsuffix,
      lemma714TypeIITargetValues_suffix b s hsTwo hsCurrent ε η i hsuffix,
      QuadraticSpace.orthogonalSum_quadratic_apply]
    rw [(q.restrict S.left.carrier S.left.nondegenerate).quadratic_zero,
      add_zero, (b.lemma714Tail S).toBONG.quadratic_ambientVector,
      ← BONG.coe_valueUnit]
    change ((b.lemma714Tail S).valueUnit ⟨i.val - 2, by omega⟩ : K) =
      (b.valueUnit i : K)
    rw [b.lemma714Tail_valueUnit S]
    congr 2
    apply Fin.ext
    change 2 + (i.val - 2) = i.val
    omega

/-- The full inserted vector family is a basis of `L_3 perp pi J`. -/
noncomputable def lemma714TypeIITargetBasis
    [DyadicDiscriminantClassLaws K]
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (ε η : Kˣ)
    (block : GoodBONG
      ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).nondegenerate))
      (Lattice.product
        (Lattice.rescale (uniformizerUnit K) S.left.lattice)
        (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).lattice) 3)
    (hblockValues : ∀ i, block.valueUnit i =
      lemma712TargetValues (b.valueUnit ⟨s, hsCurrent⟩) ε η i) :
    Basis (Fin (n + 3)) K (S.right.carrier × S.left.carrier) := by
  letI : FiniteDimensional K S.right.carrier :=
    (b.lemma714Tail S).toBONG.basis.finiteDimensional_of_finite
  letI : FiniteDimensional K S.left.carrier :=
    (b.lemma714InitialBinary S).toBONG.basis.finiteDimensional_of_finite
  let family := lemma714TypeIITargetVector b S s hsTwo hsCurrent block
  have horthogonal :=
    b.lemma714TypeIITargetVector_iIsOrtho S s hsTwo hsCurrent block
  have hself : ∀ i,
      ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
        (q.restrict S.left.carrier S.left.nondegenerate)).bilin
          (family i) (family i) ≠ 0 := by
    intro i
    change ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
      (q.restrict S.left.carrier S.left.nondegenerate)).quadratic
        (lemma714TypeIITargetVector b S s hsTwo hsCurrent block i) ≠ 0
    rw [b.quadratic_lemma714TypeIITargetVector S s hsTwo hsCurrent ε η
      block hblockValues i]
    exact Units.ne_zero _
  have hlinear : LinearIndependent K family :=
    LinearMap.BilinForm.linearIndependent_of_iIsOrtho horthogonal hself
  have hcard : Fintype.card (Fin (n + 3)) =
      Module.finrank K (S.right.carrier × S.left.carrier) := by
    rw [Fintype.card_fin, Module.finrank_prod]
    have htail := (b.lemma714Tail S).toBONG.length_eq_finrank
    have hleft := (b.lemma714InitialBinary S).toBONG.length_eq_finrank
    omega
  exact basisOfLinearIndependentOfCardEqFinrank' family hlinear hcard

@[simp]
theorem lemma714TypeIITargetBasis_apply
    [DyadicDiscriminantClassLaws K]
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (ε η : Kˣ)
    (block : GoodBONG
      ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).nondegenerate))
      (Lattice.product
        (Lattice.rescale (uniformizerUnit K) S.left.lattice)
        (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).lattice) 3)
    (hblockValues : ∀ i, block.valueUnit i =
      lemma712TargetValues (b.valueUnit ⟨s, hsCurrent⟩) ε η i)
    (i : Fin (n + 3)) :
    lemma714TypeIITargetBasis b S s hsTwo hsCurrent ε η block hblockValues i =
      lemma714TypeIITargetVector b S s hsTwo hsCurrent block i := by
  simp [lemma714TypeIITargetBasis]

/-- The target basis bundled in the form consumed by Beli's Lemma 4.3. -/
noncomputable def lemma714TypeIIOrthogonalBasisData
    [DyadicDiscriminantClassLaws K]
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (ε η : Kˣ)
    (block : GoodBONG
      ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).nondegenerate))
      (Lattice.product
        (Lattice.rescale (uniformizerUnit K) S.left.lattice)
        (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).lattice) 3)
    (hblockValues : ∀ i, block.valueUnit i =
      lemma712TargetValues (b.valueUnit ⟨s, hsCurrent⟩) ε η i) :
    OrthogonalBasisData
      ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
        (q.restrict S.left.carrier S.left.nondegenerate)) (n + 3) where
  basis := b.lemma714TypeIITargetBasis S s hsTwo hsCurrent ε η block hblockValues
  orthogonal := by
    rw [LinearMap.BilinForm.iIsOrtho_def]
    intro i j hij
    rw [lemma714TypeIITargetBasis_apply, lemma714TypeIITargetBasis_apply]
    exact (LinearMap.BilinForm.iIsOrtho_def.mp
      (b.lemma714TypeIITargetVector_iIsOrtho S s hsTwo hsCurrent block)) i j hij

@[simp]
theorem lemma714TypeIIOrthogonalBasisData_valueUnit
    [DyadicDiscriminantClassLaws K]
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hsCurrent : s < n + 3)
    (ε η : Kˣ)
    (block : GoodBONG
      ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).nondegenerate))
      (Lattice.product
        (Lattice.rescale (uniformizerUnit K) S.left.lattice)
        (b.lemma714TypeIILineSegment S s hsTwo hsCurrent).lattice) 3)
    (hblockValues : ∀ i, block.valueUnit i =
      lemma712TargetValues (b.valueUnit ⟨s, hsCurrent⟩) ε η i)
    (i : Fin (n + 3)) :
    (b.lemma714TypeIIOrthogonalBasisData S s hsTwo hsCurrent ε η block
      hblockValues).valueUnit i =
      lemma714TypeIITargetValues b s hsTwo hsCurrent ε η i := by
  apply Units.ext
  change ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
    (q.restrict S.left.carrier S.left.nondegenerate)).quadratic
      (b.lemma714TypeIITargetBasis S s hsTwo hsCurrent ε η block hblockValues i) = _
  rw [lemma714TypeIITargetBasis_apply,
    b.quadratic_lemma714TypeIITargetVector S s hsTwo hsCurrent ε η block
      hblockValues i]

/-- Beli's numerical criterion realizes the explicit global orthogonal basis
as a good BONG.  The result still carries its initially constructed lattice;
Lemma 7.10 will identify that lattice with the concrete product. -/
theorem exists_lemma714_typeII_targetGoodBONG_of_localBlock
    [laws : DyadicDiscriminantClassLaws K]
    [QuadraticDefectLaws K]
    [BeliLemma43ConstructionLaws.{u, v} K]
    [Beli2006SectionTwoLaws.{u, v} K]
    (b : GoodBONG q L (n + 3)) (R : Int) (s : Nat)
    (D : Lemma714StoppingData b R s)
    (hthird : R + 1 ≤ b.order ⟨2, by omega⟩)
    (hsCurrent : s < n + 3)
    (hcurrent : b.order ⟨s, hsCurrent⟩ = R + 1)
    (ε η : Kˣ)
    (hεUnit : IsValuationUnit K (ε : K))
    (hηUnit : IsValuationUnit K (η : K))
    (hηDefect : defectOrder (K := K) η =
      (((2 * (ramificationIndex K : ℚ) - 1 : ℚ)) : WithTop ℚ))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714TypeIIGeometry_two_le_rank n))
    (block : GoodBONG
      ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
        ((q.restrict S.right.carrier S.right.nondegenerate).restrict
          (b.lemma714TypeIILineSegment S s D.two_le hsCurrent).carrier
          (b.lemma714TypeIILineSegment S s D.two_le hsCurrent).nondegenerate))
      (Lattice.product
        (Lattice.rescale (uniformizerUnit K) S.left.lattice)
        (b.lemma714TypeIILineSegment S s D.two_le hsCurrent).lattice) 3)
    (hblockValues : ∀ i, block.valueUnit i =
      lemma712TargetValues (b.valueUnit ⟨s, hsCurrent⟩) ε η i) :
    ∃ (N : Lattice K (S.right.carrier × S.left.carrier))
        (target : GoodBONG
          ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
            (q.restrict S.left.carrier S.left.nondegenerate)) N (n + 3)),
      (∀ i, target.valueUnit i =
        lemma714TypeIITargetValues b s D.two_le hsCurrent ε η i) ∧
      ∀ i, target.toBONG.ambientVector i =
        lemma714TypeIITargetVector b S s D.two_le hsCurrent block i := by
  let X := b.lemma714TypeIIOrthogonalBasisData S s D.two_le hsCurrent ε η
    block hblockValues
  have hXValues : ∀ i, X.valueUnit i =
      lemma714TypeIITargetValues b s D.two_le hsCurrent ε η i := by
    intro i
    exact b.lemma714TypeIIOrthogonalBasisData_valueUnit S s D.two_le hsCurrent
      ε η block hblockValues i
  have hcriteria : X.SatisfiesGoodBONGCriteria := by
    constructor
    · intro i hi
      unfold OrthogonalBasisData.order
      rw [hXValues i, hXValues ⟨i.val + 2, hi⟩]
      exact b.lemma714TypeIITargetValues_weakTwoStep R s D hthird hsCurrent
        hcurrent ε η hεUnit hηUnit i hi
    · intro i hi
      unfold OrthogonalBasisData.adjacentParameter
      rw [hXValues i, hXValues ⟨i.val + 1, hi⟩]
      exact b.lemma714TypeIITargetValues_adjacentAdmissible R s D hthird
        hsCurrent hcurrent ε η hεUnit hηUnit hηDefect i hi
  rcases (X.hasGoodRealization_iff_beli2006Criteria).2 hcriteria with
    ⟨N, raw, hreal, hgood⟩
  let target : GoodBONG
      ((q.restrict S.right.carrier S.right.nondegenerate).orthogonalSum
        (q.restrict S.left.carrier S.left.nondegenerate)) N (n + 3) :=
    ⟨raw, hgood⟩
  refine ⟨N, target, ?_, ?_⟩
  · intro i
    apply Units.ext
    change raw.value i =
      (lemma714TypeIITargetValues b s D.two_le hsCurrent ε η i : K)
    rw [← X.value_eq_of_isRealizedBy hreal i]
    exact congrArg Units.val (hXValues i)
  · intro i
    calc
      target.toBONG.ambientVector i = X.basis i := hreal i
      _ = lemma714TypeIITargetVector b S s D.two_le hsCurrent block i := by
        exact b.lemma714TypeIITargetBasis_apply S s D.two_le hsCurrent ε η
          block hblockValues i

end BONG.GoodBONG

end Bong
