/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.BeliLemma61
import Bong.Bong.BinaryDefectAdaptedValues

/-!
# Beli (2003), Lemma 6.2

This file records the inverse head rescaling from part (i) and the three
value-set estimates in part (ii).  The notation
`scaledIntegralSquareResidueSet a I` is the literal set `a · 𝒪² + I`.
-/

namespace Bong

open Dyadic

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {q : QuadraticSpace K V} {L : Lattice K V} {n : Nat}

namespace Lattice

/-- The set `a · 𝒪² + I` occurring in Beli's value-set formulas. -/
def scaledIntegralSquareResidueSet
    (a : K) (I : CoefficientIdeal (K := K)) : Set K :=
  {z | ∃ x : IntegerRing K, z - a * (x : K) ^ 2 ∈ I}

@[simp]
theorem mem_scaledIntegralSquareResidueSet_iff
    (a z : K) (I : CoefficientIdeal (K := K)) :
    z ∈ scaledIntegralSquareResidueSet a I ↔
      ∃ x : IntegerRing K, z - a * (x : K) ^ 2 ∈ I :=
  Iff.rfl

/-- Enlarging the error ideal enlarges a scaled square-residue set. -/
theorem scaledIntegralSquareResidueSet_mono
    (a : K) {I J : CoefficientIdeal (K := K)} (hIJ : I ≤ J) :
    scaledIntegralSquareResidueSet a I ⊆
      scaledIntegralSquareResidueSet a J := by
  rintro z ⟨x, hx⟩
  exact ⟨x, hIJ hx⟩

end Lattice

namespace BONG

/-- The BONG obtained by replacing `x₁` with `π⁻¹x₁`. -/
structure HeadInverseRescaleWitness (b : BONG V q L (n + 2)) where
  /-- The enlarged lattice generated by the inversely rescaled BONG. -/
  lattice : Lattice K V
  /-- The actual BONG of the enlarged lattice. -/
  bong : BONG V q lattice (n + 2)
  /-- Exact first vector. -/
  ambientVector_zero :
    bong.ambientVector 0 =
      ((uniformizerPowerUnit K (-1) : Kˣ) : K) • b.ambientVector 0
  /-- Every later vector is unchanged. -/
  ambientVector_succ : ∀ i : Fin (n + 1),
    bong.ambientVector i.succ = b.ambientVector i.succ

/-- The assertion in Lemma 6.2(i). -/
def HeadInverseRescaleExists (b : BONG V q L (n + 2)) : Prop :=
  Nonempty (HeadInverseRescaleWitness b)

namespace HeadInverseRescaleWitness

variable {b : BONG V q L (n + 2)} (w : HeadInverseRescaleWitness b)

/-- The first value is multiplied by `π⁻²`. -/
theorem value_zero :
    w.bong.value 0 =
      ((uniformizerPowerUnit K (-1) : Kˣ) : K) ^ 2 * b.value 0 := by
  rw [← w.bong.quadratic_ambientVector 0, w.ambientVector_zero,
    q.quadratic_smul, b.quadratic_ambientVector]

/-- Every later value is unchanged. -/
theorem value_succ (i : Fin (n + 1)) :
    w.bong.value i.succ = b.value i.succ := by
  rw [← w.bong.quadratic_ambientVector i.succ,
    w.ambientVector_succ, b.quadratic_ambientVector]

/-- The first order drops by two. -/
theorem order_zero : w.bong.order 0 = b.order 0 - 2 := by
  apply WithTop.coe_injective
  rw [w.bong.coe_order, w.value_zero, ord_mul, ord_pow,
    ← coe_ordUnit, ordUnit_uniformizerPowerUnit, ← b.coe_order]
  norm_num
  rw [sub_eq_add_neg, add_comm]

/-- Every later order is unchanged. -/
theorem order_succ (i : Fin (n + 1)) :
    w.bong.order i.succ = b.order i.succ := by
  apply WithTop.coe_injective
  rw [w.bong.coe_order, b.coe_order, w.value_succ]

end HeadInverseRescaleWitness

/-- The common adjacent gap `R₂ - R₁` in Lemma 6.2. -/
noncomputable def lemma62Gap (b : BONG V q L (n + 2)) : Int :=
  b.order 1 - b.order 0

/-- The finite defect used in the low-defect exponent. -/
noncomputable def lemma62DefectNat (b : BONG V q L (n + 2)) : Nat :=
  beliParameterDefectNat K (b.adjacentParameter 0 (by simp))

/-- The cutoff `e - (R₂ - R₁)/2`. -/
noncomputable def lemma62DefectCutoff (b : BONG V q L (n + 2)) : Nat :=
  Int.toNat ((ramificationIndex K : Int) - b.lemma62Gap / 2)

/-- The exponent `R₂ + d(-ε₁ε₂)` in part (ii)(b). -/
noncomputable def lemma62LowExponent (b : BONG V q L (n + 2)) : Int :=
  b.order 1 + (b.lemma62DefectNat : Int)

/-- The exponent `(R₁ + R₂)/2 + e` in part (ii)(c). -/
noncomputable def lemma62HighExponent (b : BONG V q L (n + 2)) : Int :=
  (b.order 0 + b.order 1) / 2 + (ramificationIndex K : Int)

/-- The adjacent parameter has order `R₂ - R₁`. -/
theorem ordUnit_adjacentParameter_zero (b : BONG V q L (n + 2)) :
    ordUnit K (b.adjacentParameter 0 (by simp)) = b.lemma62Gap := by
  unfold adjacentParameter lemma62Gap
  rw [div_eq_mul_inv, ordUnit_mul, ordUnit_inv,
    ← b.order_eq_ordUnit, ← b.order_eq_ordUnit]
  change b.order 1 + -b.order 0 = b.order 1 - b.order 0
  rw [sub_eq_add_neg]

/-- Under the even-gap hypothesis, the natural cutoff is the displayed
integer `e - (R₂ - R₁)/2`. -/
theorem lemma62DefectCutoff_cast (b : BONG V q L (n + 2))
    (heven : Even b.lemma62Gap)
    (hupper : b.lemma62Gap ≤ 2 * (ramificationIndex K : Int)) :
    (b.lemma62DefectCutoff : Int) =
      (ramificationIndex K : Int) - b.lemma62Gap / 2 := by
  rcases heven with ⟨r, hr⟩
  unfold lemma62DefectCutoff
  rw [Int.toNat_of_nonneg]
  omega

/-- Either the original lattice or its inverse head rescaling has property B. -/
def HasPropertyBOrInverse (b : BONG V q L (n + 2))
    (w : HeadInverseRescaleWitness b) : Prop :=
  b.HasPropertyB ∨ w.bong.HasPropertyB

/-- The hypothesis in Lemma 6.2(ii) makes the original BONG good. -/
theorem HasPropertyBOrInverse.isGood
    {b : BONG V q L (n + 2)} {w : HeadInverseRescaleWitness b}
    (hB : b.HasPropertyBOrInverse w) : b.IsGood := by
  rcases hB with hB | hB
  · exact hB.hasPropertyA.isGood
  · intro i hi
    have hstep := hB.twoStep_add_two_le i hi
    by_cases hizero : i.1 = 0
    · have hiEq : i = 0 := Fin.ext hizero
      subst i
      let j : Fin (n + 1) := ⟨1, by omega⟩
      let i2 : Fin (n + 2) := ⟨(0 : Fin (n + 2)).1 + 2, hi⟩
      have hj : j.succ = i2 := by
        apply Fin.ext
        simp [j, i2]
      have htarget : w.bong.order i2 = b.order i2 := by
        calc
          w.bong.order i2 = w.bong.order j.succ :=
            congrArg w.bong.order hj.symm
          _ = b.order j.succ := w.order_succ j
          _ = b.order i2 := congrArg b.order hj
      change b.order 0 ≤ b.order i2
      change w.bong.order 0 + 2 ≤ w.bong.order i2 at hstep
      rw [w.order_zero, htarget] at hstep
      omega
    · have hipos : 0 < i.1 := Nat.pos_of_ne_zero hizero
      let j : Fin (n + 1) := ⟨i.1 - 1, by omega⟩
      let k : Fin (n + 1) := ⟨i.1 + 1, by omega⟩
      have hj : j.succ = i := by
        apply Fin.ext
        simp [j]
        omega
      have hk : k.succ = (⟨i.1 + 2, hi⟩ : Fin (n + 2)) := by
        apply Fin.ext
        simp [k]
      have hsource : w.bong.order i = b.order i := by
        calc
          w.bong.order i = w.bong.order j.succ :=
            congrArg w.bong.order hj.symm
          _ = b.order j.succ := w.order_succ j
          _ = b.order i := congrArg b.order hj
      have htarget :
          w.bong.order ⟨i.1 + 2, hi⟩ = b.order ⟨i.1 + 2, hi⟩ := by
        calc
          w.bong.order ⟨i.1 + 2, hi⟩ = w.bong.order k.succ :=
            congrArg w.bong.order hk.symm
          _ = b.order k.succ := w.order_succ k
          _ = b.order ⟨i.1 + 2, hi⟩ := congrArg b.order hk
      rw [hsource, htarget] at hstep
      omega

end BONG

/-- The remaining integral constructions and induction in Beli (2003),
Lemma 6.2.  This interface has deliberately no default instance. -/
class BeliLemma62Laws
    (K : Type u) [Field K] [CharZero K] [ValuativeRel K]
    [TopologicalSpace K] [DyadicContext K] : Prop where
  inverseHeadRescale
    {V : Type v} [AddCommGroup V] [Module K V]
    {q : QuadraticSpace K V} {L : Lattice K V} {n : Nat}
    (b : BONG V q L (n + 2)) :
    Nonempty (BONG.HeadInverseRescaleWitness b)
  quadraticValues_a
    {V : Type v} [AddCommGroup V] [Module K V]
    {q : QuadraticSpace K V} {L : Lattice K V} {n : Nat}
    (b : BONG V q L (n + 2)) (w : BONG.HeadInverseRescaleWitness b)
    (hB : b.HasPropertyBOrInverse w) (hgap : b.order 0 ≤ b.order 1) :
    Lattice.quadraticValueSet q L ⊆
      Lattice.scaledIntegralSquareResidueSet (b.value 0)
        (Lattice.powerIdeal (K := K) (b.order 1))
  quadraticValues_b
    {V : Type v} [AddCommGroup V] [Module K V]
    {q : QuadraticSpace K V} {L : Lattice K V} {n : Nat}
    (b : BONG V q L (n + 2)) (w : BONG.HeadInverseRescaleWitness b)
    (hB : b.HasPropertyBOrInverse w) (heven : Even b.lemma62Gap)
    (hupper : b.lemma62Gap ≤ 2 * (ramificationIndex K : Int))
    (hdefect : beliParameterDefect K
        (b.adjacentParameter 0 (by simp)) ≤
      (b.lemma62DefectCutoff : ℕ∞)) :
    Lattice.quadraticValueSet q L ⊆
      Lattice.scaledIntegralSquareResidueSet (b.value 0)
        (Lattice.powerIdeal (K := K) b.lemma62LowExponent)
  quadraticValues_c
    {V : Type v} [AddCommGroup V] [Module K V]
    {q : QuadraticSpace K V} {L : Lattice K V} {n : Nat}
    (b : BONG V q L (n + 2)) (w : BONG.HeadInverseRescaleWitness b)
    (hB : b.HasPropertyBOrInverse w) (heven : Even b.lemma62Gap)
    (hupper : b.lemma62Gap ≤ 2 * (ramificationIndex K : Int))
    (hdefect : (b.lemma62DefectCutoff : ℕ∞) ≤
      beliParameterDefect K (b.adjacentParameter 0 (by simp))) :
    Lattice.quadraticValueSet q L ⊆
      Lattice.scaledIntegralSquareResidueSet (b.value 0)
        (Lattice.powerIdeal (K := K) b.lemma62HighExponent)

namespace BONG

variable [BeliLemma62Laws.{u, v} K]

/-- Beli (2003), Lemma 6.2(i). -/
theorem beliLemma62_i (b : BONG V q L (n + 2)) :
    b.HeadInverseRescaleExists :=
  BeliLemma62Laws.inverseHeadRescale b

/-- Beli (2003), Lemma 6.2(ii)(a). -/
theorem beliLemma62_ii_a (b : BONG V q L (n + 2))
    (w : b.HeadInverseRescaleWitness) (hB : b.HasPropertyBOrInverse w)
    (hgap : b.order 0 ≤ b.order 1) :
    Lattice.quadraticValueSet q L ⊆
      Lattice.scaledIntegralSquareResidueSet (b.value 0)
        (Lattice.powerIdeal (K := K) (b.order 1)) :=
  BeliLemma62Laws.quadraticValues_a b w hB hgap

/-- Beli (2003), Lemma 6.2(ii)(b). -/
theorem beliLemma62_ii_b (b : BONG V q L (n + 2))
    (w : b.HeadInverseRescaleWitness) (hB : b.HasPropertyBOrInverse w)
    (heven : Even b.lemma62Gap)
    (hupper : b.lemma62Gap ≤ 2 * (ramificationIndex K : Int))
    (hdefect : beliParameterDefect K
        (b.adjacentParameter 0 (by simp)) ≤
      (b.lemma62DefectCutoff : ℕ∞)) :
    Lattice.quadraticValueSet q L ⊆
      Lattice.scaledIntegralSquareResidueSet (b.value 0)
        (Lattice.powerIdeal (K := K) b.lemma62LowExponent) :=
  BeliLemma62Laws.quadraticValues_b b w hB heven hupper hdefect

/-- Beli (2003), Lemma 6.2(ii)(c). -/
theorem beliLemma62_ii_c (b : BONG V q L (n + 2))
    (w : b.HeadInverseRescaleWitness) (hB : b.HasPropertyBOrInverse w)
    (heven : Even b.lemma62Gap)
    (hupper : b.lemma62Gap ≤ 2 * (ramificationIndex K : Int))
    (hdefect : (b.lemma62DefectCutoff : ℕ∞) ≤
      beliParameterDefect K (b.adjacentParameter 0 (by simp))) :
    Lattice.quadraticValueSet q L ⊆
      Lattice.scaledIntegralSquareResidueSet (b.value 0)
        (Lattice.powerIdeal (K := K) b.lemma62HighExponent) :=
  BeliLemma62Laws.quadraticValues_c b w hB heven hupper hdefect

end BONG

end Bong
