/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.Beli2019Lemma717Cases
import Bong.Bong.Beli2019Lemma715Prefix

/-!
# Beli (2019), Lemma 7.18: coefficient families

Lemma 7.18 replaces every split hyperbolic plane by the index-uniformizer
subplane generated by `t, πu`.  On a good BONG this raises both displayed
orders of such a plane by one.  In type II the initial discriminant plane is
left unchanged.  In type III Corollary 7.13 gives an equivalent BONG in which
only the low, zero-based odd coefficients acquire the square factor `π²`.

This file records those three complete coefficient families and proves their
order and common-suffix properties.  Their realization on the concrete
replacement lattice is separated from these arithmetic identities.
-/

namespace Bong

open Dyadic

universe u v

namespace BONG.GoodBONG

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {q : QuadraticSpace K V} {L : Lattice K V} {n : Nat}

/-- Type-I values: all coefficients in the selected even prefix rise by one
in valuation. -/
noncomputable def lemma718TypeITargetValues
    (a : GoodBONG q L (n + 3)) (s : Nat) : Fin (n + 3) → Kˣ :=
  fun i ↦ if i.val < s then uniformizerUnit K * a.valueUnit i
    else a.valueUnit i

/-- Type-II values: the initial discriminant pair is unchanged, while every
coefficient from the third through the `s`th rises by one. -/
noncomputable def lemma718TypeIITargetValues
    (a : GoodBONG q L (n + 3)) (s : Nat) : Fin (n + 3) → Kˣ :=
  fun i ↦ if 2 ≤ i.val ∧ i.val < s then
      uniformizerUnit K * a.valueUnit i
    else a.valueUnit i

/-- Type-III values: the low entries in the first `s` coefficients acquire
the square factor `π²`; all even positions and the suffix are unchanged. -/
noncomputable def lemma718TypeIIITargetValues
    (a : GoodBONG q L (n + 3)) (s : Nat) : Fin (n + 3) → Kˣ :=
  fun i ↦ if i.val < s ∧ Odd i.val then
      uniformizerUnit K ^ 2 * a.valueUnit i
    else a.valueUnit i

@[simp]
theorem lemma718TypeITargetValues_prefix
    (a : GoodBONG q L (n + 3)) (s : Nat) (i : Fin (n + 3))
    (hi : i.val < s) :
    lemma718TypeITargetValues a s i =
      uniformizerUnit K * a.valueUnit i := by
  simp [lemma718TypeITargetValues, hi]

@[simp]
theorem lemma718TypeITargetValues_suffix
    (a : GoodBONG q L (n + 3)) (s : Nat) (i : Fin (n + 3))
    (hi : s ≤ i.val) :
    lemma718TypeITargetValues a s i = a.valueUnit i := by
  simp [lemma718TypeITargetValues, not_lt.mpr hi]

@[simp]
theorem lemma718TypeIITargetValues_changed
    (a : GoodBONG q L (n + 3)) (s : Nat) (i : Fin (n + 3))
    (hiTwo : 2 ≤ i.val) (his : i.val < s) :
    lemma718TypeIITargetValues a s i =
      uniformizerUnit K * a.valueUnit i := by
  simp [lemma718TypeIITargetValues, hiTwo, his]

@[simp]
theorem lemma718TypeIITargetValues_initial
    (a : GoodBONG q L (n + 3)) (s : Nat) (i : Fin (n + 3))
    (hi : i.val < 2) :
    lemma718TypeIITargetValues a s i = a.valueUnit i := by
  simp [lemma718TypeIITargetValues, show ¬2 ≤ i.val by omega]

@[simp]
theorem lemma718TypeIITargetValues_suffix
    (a : GoodBONG q L (n + 3)) (s : Nat) (i : Fin (n + 3))
    (hi : s ≤ i.val) :
    lemma718TypeIITargetValues a s i = a.valueUnit i := by
  simp [lemma718TypeIITargetValues, show ¬i.val < s by omega]

@[simp]
theorem lemma718TypeIIITargetValues_changed
    (a : GoodBONG q L (n + 3)) (s : Nat) (i : Fin (n + 3))
    (his : i.val < s) (hiOdd : Odd i.val) :
    lemma718TypeIIITargetValues a s i =
      uniformizerUnit K ^ 2 * a.valueUnit i := by
  simp [lemma718TypeIIITargetValues, his, hiOdd]

@[simp]
theorem lemma718TypeIIITargetValues_even
    (a : GoodBONG q L (n + 3)) (s : Nat) (i : Fin (n + 3))
    (hiEven : Even i.val) :
    lemma718TypeIIITargetValues a s i = a.valueUnit i := by
  have hnotOdd : ¬Odd i.val := Nat.not_odd_iff_even.mpr hiEven
  simp [lemma718TypeIIITargetValues, hnotOdd]

@[simp]
theorem lemma718TypeIIITargetValues_suffix
    (a : GoodBONG q L (n + 3)) (s : Nat) (i : Fin (n + 3))
    (hi : s ≤ i.val) :
    lemma718TypeIIITargetValues a s i = a.valueUnit i := by
  simp [lemma718TypeIIITargetValues, show ¬i.val < s by omega]

private theorem ordUnit_uniformizerUnit_eq_one :
    ordUnit K (uniformizerUnit K) = 1 := by
  simpa [uniformizerPowerUnit] using
    (ordUnit_uniformizerPowerUnit (K := K) (1 : Int))

/-- The type-I prefix orders all rise by one. -/
theorem ordUnit_lemma718TypeITargetValues_prefix
    (a : GoodBONG q L (n + 3)) (s : Nat) (i : Fin (n + 3))
    (hi : i.val < s) :
    ordUnit K (lemma718TypeITargetValues a s i) = a.order i + 1 := by
  rw [lemma718TypeITargetValues_prefix a s i hi, ordUnit_mul,
    ordUnit_uniformizerUnit_eq_one]
  have horder := a.toBONG.order_eq_ordUnit i
  change a.order i = ordUnit K (a.valueUnit i) at horder
  rw [← horder]
  omega

/-- The changed type-II orders rise by one. -/
theorem ordUnit_lemma718TypeIITargetValues_changed
    (a : GoodBONG q L (n + 3)) (s : Nat) (i : Fin (n + 3))
    (hiTwo : 2 ≤ i.val) (his : i.val < s) :
    ordUnit K (lemma718TypeIITargetValues a s i) = a.order i + 1 := by
  rw [lemma718TypeIITargetValues_changed a s i hiTwo his, ordUnit_mul,
    ordUnit_uniformizerUnit_eq_one]
  have horder := a.toBONG.order_eq_ordUnit i
  change a.order i = ordUnit K (a.valueUnit i) at horder
  rw [← horder]
  omega

/-- The changed type-III orders rise by two. -/
theorem ordUnit_lemma718TypeIIITargetValues_changed
    (a : GoodBONG q L (n + 3)) (s : Nat) (i : Fin (n + 3))
    (his : i.val < s) (hiOdd : Odd i.val) :
    ordUnit K (lemma718TypeIIITargetValues a s i) = a.order i + 2 := by
  rw [lemma718TypeIIITargetValues_changed a s i his hiOdd,
    ordUnit_mul, ordUnit_pow, ordUnit_uniformizerUnit_eq_one]
  have horder := a.toBONG.order_eq_ordUnit i
  change a.order i = ordUnit K (a.valueUnit i) at horder
  rw [← horder]
  ring

/-- Every type-III coefficient differs from the corresponding source
coefficient by a square.  This is the coefficientwise reason all diagonal
prefixes in Lemma 7.19 are isometric. -/
theorem lemma718TypeIIITargetValues_eq_square_mul
    (a : GoodBONG q L (n + 3)) (s : Nat) (i : Fin (n + 3)) :
    ∃ u : Kˣ, lemma718TypeIIITargetValues a s i =
      u ^ 2 * a.valueUnit i := by
  by_cases hchanged : i.val < s ∧ Odd i.val
  · exact ⟨uniformizerUnit K, by
      simp [lemma718TypeIIITargetValues, hchanged]⟩
  · exact ⟨1, by simp [lemma718TypeIIITargetValues, hchanged]⟩

/-- A realized type-I list has the unchanged suffix beginning at `s`. -/
theorem lemma718_typeI_realized_suffix
    {M : Lattice K V} (a : GoodBONG q L (n + 3))
    (b : GoodBONG q M (n + 3)) (s : Nat)
    (hvalues : ∀ i, b.valueUnit i = lemma718TypeITargetValues a s i)
    (i : Fin (n + 3)) (hi : s ≤ i.val) :
    b.valueUnit i = a.valueUnit i := by
  rw [hvalues i, lemma718TypeITargetValues_suffix a s i hi]

/-- A realized type-II list has the unchanged suffix beginning at `s`. -/
theorem lemma718_typeII_realized_suffix
    {M : Lattice K V} (a : GoodBONG q L (n + 3))
    (b : GoodBONG q M (n + 3)) (s : Nat)
    (hvalues : ∀ i, b.valueUnit i = lemma718TypeIITargetValues a s i)
    (i : Fin (n + 3)) (hi : s ≤ i.val) :
    b.valueUnit i = a.valueUnit i := by
  rw [hvalues i, lemma718TypeIITargetValues_suffix a s i hi]

/-- A realized type-III list has the unchanged suffix beginning at `s`. -/
theorem lemma718_typeIII_realized_suffix
    {M : Lattice K V} (a : GoodBONG q L (n + 3))
    (b : GoodBONG q M (n + 3)) (s : Nat)
    (hvalues : ∀ i, b.valueUnit i = lemma718TypeIIITargetValues a s i)
    (i : Fin (n + 3)) (hi : s ≤ i.val) :
    b.valueUnit i = a.valueUnit i := by
  rw [hvalues i, lemma718TypeIIITargetValues_suffix a s i hi]

end BONG.GoodBONG

end Bong
