/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Dyadic.UnitsCongruentModuloAlgebra
import Bong.Lattice.OmearaOddTernaryModels

/-!
# Norm groups from Beli's component congruence

Beli (2009), Lemma 3.3 compares norm generators `a_k` and `b_k` modulo the
normalized weight `a_k⁻¹ w_k`.  This file proves the valuation-theoretic
bridge from that scalar congruence to equality of O'Meara's norm groups.

The zero normalized-weight case is separated explicitly: then the weight is
the whole norm ideal and the norm group is the norm ideal.  In the positive
case, the square multiplier in `UnitsCongruentModulo` is forced to be a
valuation unit, so it gives the two integral-square congruences needed to
identify the square cosets.
-/

namespace Bong

open Dyadic

namespace Lattice

universe u v w

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {W : Type w} [AddCommGroup W] [Module K W]
  {q : QuadraticSpace K V} {r : QuadraticSpace K W}
  {L : Lattice K V} {M : Lattice K W}

/-- If the error ideal is the principal ideal generated by the leading
coefficient, the integral square coset is just that principal ideal. -/
theorem integralSquareCoset_principal_self (a : Kˣ) :
    integralSquareCoset (a : K) (principalIdeal (K := K) (a : K)) =
      (principalIdeal (K := K) (a : K) : Set K) := by
  ext z
  constructor
  · rintro ⟨c, y, hy, rfl⟩
    apply (principalIdeal (K := K) (a : K)).add_mem _ hy
    rw [principalIdeal, Submodule.mem_span_singleton]
    refine ⟨c ^ 2, ?_⟩
    change (c : K) ^ 2 * (a : K) = (a : K) * (c : K) ^ 2
    ring
  · intro hz
    exact ⟨0, z, hz, by simp⟩

/-- Positive normalized weight turns Beli's square-class congruence into
equality of the two integral square cosets. -/
theorem integralSquareCoset_eq_of_unitsCongruentModulo_normalizedWeight
    (a b : Kˣ) (weightOrder : Int)
    (horder : ordUnit K a = ordUnit K b)
    (hpositive : 0 < weightOrder - ordUnit K a)
    (hcongruent : BONG.GoodBONG.UnitsCongruentModulo a b
      (powerIdeal (K := K) (weightOrder - ordUnit K a))) :
    integralSquareCoset (b : K) (powerIdeal (K := K) weightOrder) =
      integralSquareCoset (a : K) (powerIdeal (K := K) weightOrder) := by
  rcases hcongruent with ⟨s, hs⟩
  let d : Int := weightOrder - ordUnit K a
  let error : K := (b : K) / (a : K) / (s : K) ^ 2 - 1
  have herror : error ∈ powerIdeal (K := K) d := by
    simpa only [error, d] using hs
  have herrorOrder : (d : WithTop Int) ≤ ord K error :=
    (mem_powerIdeal_iff (K := K) d error).1 herror
  have herrorPositive : (0 : WithTop Int) < ord K error := by
    have hd : (0 : WithTop Int) < (d : Int) := by
      exact_mod_cast hpositive
    exact hd.trans_le herrorOrder
  have honeAddOrder : ord K ((1 : K) + error) = 0 := by
    have h := (ord K).map_add_eq_of_lt_left
      (show ord K (1 : K) < ord K error by
        simpa only [ord_one] using herrorPositive)
    simpa only [ord_one] using h
  have hadjusted : (b : K) / (a : K) / (s : K) ^ 2 = 1 + error := by
    dsimp only [error]
    ring
  have hadjustedOrder : ordUnit K (b / a / s ^ 2) = 0 := by
    apply WithTop.coe_injective
    rw [coe_ordUnit]
    simp only [Units.val_div_eq_div_val, Units.val_pow_eq_pow_val]
    rw [hadjusted, honeAddOrder]
    rfl
  have hsOrder : ordUnit K s = 0 := by
    rw [div_eq_mul_inv, div_eq_mul_inv, ordUnit_mul, ordUnit_mul,
      ordUnit_inv, ordUnit_inv, ordUnit_pow, horder] at hadjustedOrder
    omega
  have hsUnit : IsValuationUnit K (s : K) :=
    (isValuationUnit_iff_ordUnit_eq_zero K s).2 hsOrder
  have hsInvUnit : IsValuationUnit K ((s⁻¹ : Kˣ) : K) := by
    rw [isValuationUnit_iff_ordUnit_eq_zero, ordUnit_inv, hsOrder, neg_zero]
  have hsIntegral : (s : K) ∈ IntegerRing K :=
    (mem_integerRing_iff K).2 hsUnit.ge
  have hsInvIntegral : ((s⁻¹ : Kˣ) : K) ∈ IntegerRing K :=
    (mem_integerRing_iff K).2 hsInvUnit.ge
  let sO : IntegerRing K := ⟨s, hsIntegral⟩
  let sInvO : IntegerRing K := ⟨((s⁻¹ : Kˣ) : K), hsInvIntegral⟩
  have hforward : (b : K) - (a : K) * (sO : K) ^ 2 ∈
      powerIdeal (K := K) weightOrder := by
    rw [mem_powerIdeal_iff]
    have hid : (b : K) - (a : K) * (sO : K) ^ 2 =
        ((a : K) * (s : K) ^ 2) * error := by
      dsimp only [sO, error]
      field_simp [Units.ne_zero a, Units.ne_zero s]
    rw [hid, ord_mul, ord_mul, ord_pow, ← coe_ordUnit,
      ← coe_ordUnit, hsOrder]
    have hsum : weightOrder = ordUnit K a + d := by
      dsimp only [d]
      omega
    rw [hsum]
    simpa only [WithTop.coe_add, WithTop.coe_zero, nsmul_zero, add_zero,
      zero_add, add_comm, add_left_comm, add_assoc] using
      add_le_add_left herrorOrder (ordUnit K a : WithTop Int)
  have hreverse : (a : K) - (b : K) * (sInvO : K) ^ 2 ∈
      powerIdeal (K := K) weightOrder := by
    have hscaled := (powerIdeal (K := K) weightOrder).smul_mem
      (-(sInvO ^ 2)) hforward
    have heq : (a : K) - (b : K) * (sInvO : K) ^ 2 =
        (-(sInvO ^ 2) : IntegerRing K) •
          ((b : K) - (a : K) * (sO : K) ^ 2) := by
      rw [Algebra.smul_def]
      dsimp only [sO, sInvO]
      change (a : K) - (b : K) * (((s⁻¹ : Kˣ) : K)) ^ 2 =
        (-((((s⁻¹ : Kˣ) : K)) ^ 2)) *
          ((b : K) - (a : K) * (s : K) ^ 2)
      rw [Units.val_inv_eq_inv_val]
      field_simp [Units.ne_zero s] <;> ring
    rw [heq]
    exact hscaled
  exact integralSquareCoset_eq_of_mutual_integral_square_congruence
    (a : K) (b : K) (powerIdeal (K := K) weightOrder)
      sO sInvO hforward hreverse

/-- Equal norm-generator orders, equal weights, and Beli's component
congruence modulo the normalized weight imply equality of norm groups. -/
theorem normGroupSet_eq_of_unitsCongruentModulo_normalizedWeight
    (a b : Kˣ)
    (ha : IsNormGeneratorValue q L a)
    (hb : IsNormGeneratorValue r M b)
    (horder : ordUnit K a = ordUnit K b)
    (hweight : weightIdeal q L = weightIdeal r M)
    (hcongruent : BONG.GoodBONG.UnitsCongruentModulo a b
      (powerIdeal (K := K)
        (weightIdealOrder q L - ordUnit K a))) :
    normGroupSet r M = normGroupSet q L := by
  have hweightOrder : weightIdealOrder q L = weightIdealOrder r M := by
    apply powerIdeal_order_eq_of_eq (K := K)
    rw [← weightIdeal_eq_powerIdeal q L,
      ← weightIdeal_eq_powerIdeal r M]
    exact hweight
  have hweightLe : weightIdeal q L ≤ principalIdeal (K := K) (a : K) :=
    weightIdeal_le_principalIdeal a ha
  have horderLeWeight : ordUnit K a ≤ weightIdealOrder q L := by
    rw [weightIdeal_eq_powerIdeal, principalIdeal_eq_powerIdeal,
      powerIdeal_le_iff] at hweightLe
    exact hweightLe
  by_cases hzero : weightIdealOrder q L - ordUnit K a = 0
  · have hsourceWeight : weightIdeal q L =
        principalIdeal (K := K) (a : K) := by
      calc
        weightIdeal q L = powerIdeal (K := K) (weightIdealOrder q L) :=
          weightIdeal_eq_powerIdeal q L
        _ = powerIdeal (K := K) (ordUnit K a) := by
          congr 1
          omega
        _ = principalIdeal (K := K) (a : K) :=
          (principalIdeal_eq_powerIdeal a).symm
    have htargetWeight : weightIdeal r M =
        principalIdeal (K := K) (b : K) := by
      calc
        weightIdeal r M = weightIdeal q L := hweight.symm
        _ = principalIdeal (K := K) (a : K) := hsourceWeight
        _ = principalIdeal (K := K) (b : K) :=
          (principalIdeal_eq_iff_ordUnit_eq a b).2 horder
    rw [normGroupSet_eq_integralSquareCoset_weightIdeal b hb,
      normGroupSet_eq_integralSquareCoset_weightIdeal a ha,
      htargetWeight, hsourceWeight,
      integralSquareCoset_principal_self,
      integralSquareCoset_principal_self]
    exact congrArg (fun I : CoefficientIdeal (K := K) ↦ (I : Set K))
      ((principalIdeal_eq_iff_ordUnit_eq b a).2 horder.symm)
  · have hpositive : 0 < weightIdealOrder q L - ordUnit K a := by
      omega
    rw [normGroupSet_eq_integralSquareCoset_weightIdeal b hb,
      normGroupSet_eq_integralSquareCoset_weightIdeal a ha,
      weightIdeal_eq_powerIdeal, weightIdeal_eq_powerIdeal,
      ← hweightOrder]
    exact integralSquareCoset_eq_of_unitsCongruentModulo_normalizedWeight
      a b (weightIdealOrder q L) horder hpositive hcongruent

/-- Equality of norm groups recovers Beli's congruence between any two norm
generators of the same order, modulo the normalized source weight.  This is
the reverse implication used in Lemma 3.3. -/
theorem unitsCongruentModulo_normalizedWeight_of_normGroupSet_eq
    (a b : Kˣ)
    (ha : IsNormGeneratorValue q L a)
    (hb : IsNormGeneratorValue r M b)
    (horder : ordUnit K a = ordUnit K b)
    (hgroup : normGroupSet r M = normGroupSet q L) :
    BONG.GoodBONG.UnitsCongruentModulo a b
      (powerIdeal (K := K) (weightIdealOrder q L - ordUnit K a)) := by
  let d : Int := weightIdealOrder q L - ordUnit K a
  have hweightLe : weightIdeal q L ≤ principalIdeal (K := K) (a : K) :=
    weightIdeal_le_principalIdeal a ha
  have horderLeWeight : ordUnit K a ≤ weightIdealOrder q L := by
    rw [weightIdeal_eq_powerIdeal, principalIdeal_eq_powerIdeal,
      powerIdeal_le_iff] at hweightLe
    exact hweightLe
  by_cases hzero : d = 0
  · have hratioOrder : ordUnit K (b / a) = 0 := by
      rw [div_eq_mul_inv, ordUnit_mul, ordUnit_inv, ← horder]
      omega
    refine ⟨1, ?_⟩
    have hmem : ((b / a : Kˣ) : K) - 1 ∈
        powerIdeal (K := K) (0 : Int) := by
      rw [mem_powerIdeal_iff]
      have hsum := min_ord_le_ord_add K ((b / a : Kˣ) : K) (-1 : K)
      rw [← coe_ordUnit, hratioOrder, ord_neg, ord_one] at hsum
      simpa [sub_eq_add_neg] using hsum
    have hd0 : weightIdealOrder q L - ordUnit K a = 0 := by
      simpa only [d] using hzero
    simpa only [Units.val_div_eq_div_val, Units.val_one, one_pow, div_one,
      hd0] using hmem
  · have hpositive : 0 < d := by
      dsimp only [d] at hzero ⊢
      omega
    have hbSource : (b : K) ∈ normGroupSet q L := by
      rw [← hgroup]
      exact hb.1
    rw [normGroupSet_eq_integralSquareCoset_weightIdeal a ha] at hbSource
    rcases hbSource with ⟨c, y, hy, hby⟩
    have hyPower : y ∈ powerIdeal (K := K) (weightIdealOrder q L) := by
      rw [← weightIdeal_eq_powerIdeal q L]
      exact hy
    have hyOrder : ((weightIdealOrder q L : Int) : WithTop Int) ≤ ord K y :=
      (mem_powerIdeal_iff (K := K) (weightIdealOrder q L) y).1 hyPower
    have haLtWeightInt : ordUnit K a < weightIdealOrder q L := by
      dsimp only [d] at hpositive
      omega
    have haLtWeight : (ordUnit K a : WithTop Int) <
        ((weightIdealOrder q L : Int) : WithTop Int) := by
      exact_mod_cast haLtWeightInt
    have haLtY : (ordUnit K a : WithTop Int) < ord K y :=
      haLtWeight.trans_le hyOrder
    have hcIntegral : (0 : WithTop Int) ≤ ord K (c : K) := by
      exact (mem_integerRing_iff K).1 c.property
    have hcUnitOrder : ord K (c : K) = 0 := by
      by_contra hne
      have hcPositive : (0 : WithTop Int) < ord K (c : K) :=
        lt_of_le_of_ne hcIntegral (Ne.symm hne)
      have hcSquarePositive : (0 : WithTop Int) < ord K ((c : K) ^ 2) := by
        by_cases hcZero : (c : K) = 0
        · simp [hcZero]
        · let cu : Kˣ := Units.mk0 (c : K) hcZero
          have hcPositiveInt : 0 < ordUnit K cu := by
            apply WithTop.coe_lt_coe.mp
            calc
              (0 : WithTop Int) < ord K (c : K) := hcPositive
              _ = (ordUnit K cu : WithTop Int) := by
                simpa only [cu, Units.val_mk0] using (coe_ordUnit K cu).symm
          have hcOrd : ord K (c : K) = (ordUnit K cu : WithTop Int) := by
            simpa only [cu, Units.val_mk0] using (coe_ordUnit K cu).symm
          rw [ord_pow, hcOrd]
          exact_mod_cast (show 0 < 2 * ordUnit K cu by omega)
      have hyDivPositive : (0 : WithTop Int) < ord K (y / (a : K)) := by
        by_cases hyZero : y = 0
        · simp [hyZero]
        · let yu : Kˣ := Units.mk0 y hyZero
          have haLtYInt : ordUnit K a < ordUnit K yu := by
            apply WithTop.coe_lt_coe.mp
            calc
              (ordUnit K a : WithTop Int) < ord K y := haLtY
              _ = (ordUnit K yu : WithTop Int) := by
                simpa only [yu, Units.val_mk0] using (coe_ordUnit K yu).symm
          rw [div_eq_mul_inv, ord_mul, AddValuation.map_inv,
            show ord K y = (ordUnit K yu : WithTop Int) by
              simpa only [yu, Units.val_mk0] using (coe_ordUnit K yu).symm,
            ← coe_ordUnit]
          exact_mod_cast (sub_pos.mpr haLtYInt)
      have hratioPositive : (0 : WithTop Int) < ord K ((b : K) / (a : K)) := by
        have hsum := isInMaximalIdeal_add K hcSquarePositive hyDivPositive
        have hratioEq : (b : K) / (a : K) =
            (c : K) ^ 2 + y / (a : K) := by
          rw [hby]
          field_simp [Units.ne_zero a]
        rw [hratioEq]
        exact hsum
      have hratioZero : ord K ((b : K) / (a : K)) = 0 := by
        rw [← Units.val_div_eq_div_val, ← coe_ordUnit,
          show ordUnit K (b / a) = 0 by
            rw [div_eq_mul_inv, ordUnit_mul, ordUnit_inv, ← horder]
            omega]
        simp
      rw [hratioZero] at hratioPositive
      exact lt_irrefl 0 hratioPositive
    have hcNe : (c : K) ≠ 0 := by
      intro hc
      rw [hc, ord_zero] at hcUnitOrder
      exact WithTop.top_ne_coe hcUnitOrder
    let s : Kˣ := Units.mk0 (c : K) hcNe
    refine ⟨s, ?_⟩
    rw [mem_powerIdeal_iff]
    have herror : (b : K) / (a : K) / (s : K) ^ 2 - 1 =
        y / ((a : K) * (c : K) ^ 2) := by
      dsimp only [s]
      simp only [Units.val_mk0]
      rw [hby]
      field_simp [Units.ne_zero a, hcNe]
      ring
    rw [herror, div_eq_mul_inv, ord_mul, AddValuation.map_inv,
      ord_mul, ord_pow, ← coe_ordUnit, hcUnitOrder]
    have hshift := add_le_add_right hyOrder
      (-(ordUnit K a : WithTop Int))
    have hleft :
        ((weightIdealOrder q L - ordUnit K a : Int) : WithTop Int) =
          -(ordUnit K a : WithTop Int) +
            (weightIdealOrder q L : WithTop Int) := by
      norm_cast
      ring
    rw [hleft]
    simpa only [WithTop.coe_zero, nsmul_zero, add_zero, zero_add, neg_zero,
      add_comm, add_left_comm, add_assoc] using hshift

namespace JordanDecomposition

/-- Build O'Meara's complete fundamental type from matched component ranks,
scales, weights, and Beli's normalized-weight congruences between chosen
fundamental norm generators. -/
noncomputable def sameFundamentalTypeOfNormalizedWeightCongruence
    {t : Nat} (J : JordanDecomposition q L t)
    (H : JordanDecomposition r M t)
    (a b : Fin t → Kˣ)
    (ha : ∀ i, IsNormGeneratorValue q (J.fundamentalLattice i) (a i))
    (hb : ∀ i, IsNormGeneratorValue r (H.fundamentalLattice i) (b i))
    (hrank : ∀ i, H.componentRank i = J.componentRank i)
    (hscale : ∀ i, H.fundamentalScaleOrder i =
      J.fundamentalScaleOrder i)
    (horder : ∀ i, ordUnit K (a i) = ordUnit K (b i))
    (hweight : ∀ i, J.fundamentalWeightOrder i =
      H.fundamentalWeightOrder i)
    (hcongruent : ∀ i, BONG.GoodBONG.UnitsCongruentModulo (a i) (b i)
      (powerIdeal (K := K)
        (J.fundamentalWeightOrder i - ordUnit K (a i)))) :
    SameFundamentalType J H where
  indexEquiv := Equiv.refl _
  index_val := fun _ ↦ rfl
  componentRank_eq := hrank
  scaleOrder_eq := hscale
  normGroup_eq := by
    intro i
    unfold fundamentalNormGroup
    apply normGroupSet_eq_of_unitsCongruentModulo_normalizedWeight
      (a i) (b i) (ha i) (hb i) (horder i)
    · rw [weightIdeal_eq_powerIdeal, weightIdeal_eq_powerIdeal]
      exact congrArg (powerIdeal (K := K)) (hweight i)
    · simpa only [fundamentalWeightOrder] using hcongruent i

end JordanDecomposition

end Lattice

end Bong
