/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.BeliTheoremOneForward
import Bong.Lattice.NormGeneratorValues

/-!
# Beli (2003), Lemma 6.1

This file packages the lattice obtained by multiplying the first BONG vector
by a power of the uniformizer.  The threshold description in Lemma 6.1(ii)
is stated as an exact carrier equality.  The equivalence between the first
threshold and failure to be a norm generator is proved from principal ideals.
-/

namespace Bong

open Dyadic

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {q : QuadraticSpace K V} {L : Lattice K V} {n : Nat}

namespace BONG

/-- A BONG obtained by multiplying only its first vector by `pi^k`. -/
structure HeadRescaleWitness (b : BONG V q L (n + 2)) (k : Nat) where
  /-- The lattice generated by the rescaled BONG. -/
  lattice : Lattice K V
  /-- The actual BONG after rescaling. -/
  bong : BONG V q lattice (n + 2)
  /-- Exact first vector. -/
  ambientVector_zero :
    bong.ambientVector 0 =
      ((uniformizerPowerUnit K (k : Int) : Kˣ) : K) • b.ambientVector 0
  /-- Every remaining vector is unchanged. -/
  ambientVector_succ : ∀ i : Fin (n + 1),
    bong.ambientVector i.succ = b.ambientVector i.succ

/-- The assertion that the rescaled BONG in Lemma 6.1 exists. -/
def HeadRescaleExists (b : BONG V q L (n + 2)) (k : Nat) : Prop :=
  Nonempty (HeadRescaleWitness b k)

/-- The binary initial segment `⟨π^k x₁, x₂⟩` occurring in the
hypotheses of Beli (2003), Lemma 6.1(i),(ii).  The paper only assumes this
binary lattice exists; existence of the full rescaled BONG is a conclusion of
the proof, not part of the hypothesis. -/
structure HeadBinaryRescaleWitness (b : BONG V q L (n + 2)) (k : Nat) where
  /-- The nondegenerate span of the first two ambient BONG vectors. -/
  carrier : Submodule K V
  /-- Nondegeneracy of the restricted binary quadratic space. -/
  nondegenerate : (q.bilin.restrict carrier).Nondegenerate
  /-- The binary lattice on the initial two-dimensional carrier. -/
  lattice : Lattice K carrier
  /-- Its BONG has the requested rescaled first vector and unchanged second
  vector. -/
  bong : BONG carrier (q.restrict carrier nondegenerate) lattice 2
  /-- Exact rescaled first ambient vector. -/
  ambientVector_zero :
    (bong.ambientVector 0 : V) =
      ((uniformizerPowerUnit K (k : Int) : Kˣ) : K) • b.ambientVector 0
  /-- Exact unchanged second ambient vector. -/
  ambientVector_one :
    (bong.ambientVector 1 : V) = b.ambientVector 1

/-- Literal meaning of Beli's notation `⟨π^k x₁,x₂⟩ exists`. -/
def HeadBinaryRescaleExists (b : BONG V q L (n + 2)) (k : Nat) : Prop :=
  Nonempty (HeadBinaryRescaleWitness b k)

/-- The exact threshold sublattice in Lemma 6.1(ii). -/
structure HeadDepthWitness (b : BONG V q L (n + 2)) (k : Nat)
    extends HeadRescaleWitness b k where
  /-- Its vectors are exactly the original vectors above the norm threshold. -/
  mem_lattice_iff : ∀ x : V,
    x ∈ lattice ↔
      x ∈ L ∧
        ((b.order 0 + 2 * (k : Int) - 1 : Int) : WithTop Int) ≤
          ord K (q.quadratic x)
  /-- The rescaled BONG remains good. -/
  good : bong.IsGood

/-- The two alternatives in Lemma 6.1(iii). -/
noncomputable def HeadRescaleCriterion (b : BONG V q L (n + 2)) : Prop :=
  let gap := b.order 1 - b.order 0
  2 * (ramificationIndex K : Int) + 1 ≤ gap ∨
    (-(2 * (ramificationIndex K : Int)) < gap ∧ Even gap ∧
      ((((ramificationIndex K : ℚ) - (gap : ℚ) / 2) : ℚ) : WithTop ℚ) <
        b.normalizedAdjacentDefectOrder 0)

/-- A lattice vector is a norm generator exactly at the minimal norm order. -/
theorem isNormGenerator_iff_ord_quadratic_eq_head
    (b : BONG V q L (n + 1)) (x : V) (hx : x ∈ L) :
    Lattice.IsNormGenerator q L x ↔
      ord K (q.quadratic x) = (b.order 0 : WithTop Int) := by
  have hhead : Lattice.normIdeal q L =
      Lattice.principalIdeal (K := K) (b.value 0) := by
    simpa [b.value_zero_eq_quadratic_head] using
      b.head_isNormGenerator.normIdeal_eq
  have hxIdeal := Lattice.quadratic_mem_normIdeal_of_mem q L hx
  rw [hhead] at hxIdeal
  have hminimum : (b.order 0 : WithTop Int) ≤ ord K (q.quadratic x) := by
    rw [b.coe_order]
    exact Lattice.ord_le_of_mem_principalIdeal (b.value_ne_zero 0) hxIdeal
  constructor
  · intro hgenerator
    by_cases hxzero : q.quadratic x = 0
    · have hheadMem :=
        Lattice.quadratic_mem_normIdeal_of_mem q L
          b.head_isNormGenerator.mem
      rw [hgenerator.normIdeal_eq, hxzero,
        Lattice.principalIdeal] at hheadMem
      exact (b.head_isAnisotropic (by simpa using hheadMem)).elim
    · let xu : Kˣ := Units.mk0 (q.quadratic x) hxzero
      have hideal : Lattice.principalIdeal (K := K) (xu : K) =
          Lattice.principalIdeal (K := K) (b.valueUnit 0 : K) := by
        exact hgenerator.normIdeal_eq.symm.trans hhead
      have hunit :=
        (Lattice.principalIdeal_eq_iff_isValuationUnit_div
          xu (b.valueUnit 0)).1 hideal
      rw [isValuationUnit_iff_ordUnit_eq_zero] at hunit
      have hord : ordUnit K xu = b.order 0 := by
        have hvalueOrder := b.order_eq_ordUnit 0
        simp only [div_eq_mul_inv, ordUnit_mul, ordUnit_inv] at hunit
        omega
      change ord K (xu : K) = (b.order 0 : WithTop Int)
      rw [← coe_ordUnit K xu, hord]
  · intro horder
    have hxzero : q.quadratic x ≠ 0 := by
      intro hxzero
      rw [hxzero, ord_zero] at horder
      exact WithTop.top_ne_coe horder
    let xu : Kˣ := Units.mk0 (q.quadratic x) hxzero
    have hord : ordUnit K xu = b.order 0 := by
      apply WithTop.coe_injective
      rw [coe_ordUnit]
      simpa [xu] using horder
    have hunit : IsValuationUnit K
        (((xu / b.valueUnit 0 : Kˣ) : K)) := by
      rw [isValuationUnit_iff_ordUnit_eq_zero]
      simp [div_eq_mul_inv, hord]
    have hideal : Lattice.principalIdeal (K := K) (xu : K) =
        Lattice.principalIdeal (K := K) (b.valueUnit 0 : K) :=
      (Lattice.principalIdeal_eq_iff_isValuationUnit_div
        xu (b.valueUnit 0)).2 hunit
    exact ⟨hx, hhead.trans hideal.symm⟩

/-- Non-norm-generators are exactly the vectors one order above the minimum. -/
theorem mem_and_not_isNormGenerator_iff_ord_ge_head_add_one
    (b : BONG V q L (n + 1)) (x : V) :
    (x ∈ L ∧ ¬Lattice.IsNormGenerator q L x) ↔
      (x ∈ L ∧
        ((b.order 0 + 1 : Int) : WithTop Int) ≤ ord K (q.quadratic x)) := by
  constructor
  · rintro ⟨hx, hnot⟩
    refine ⟨hx, ?_⟩
    have hminimum : (b.order 0 : WithTop Int) ≤ ord K (q.quadratic x) := by
      have hxIdeal := Lattice.quadratic_mem_normIdeal_of_mem q L hx
      rw [b.head_isNormGenerator.normIdeal_eq,
        ← b.value_zero_eq_quadratic_head] at hxIdeal
      rw [b.coe_order]
      exact Lattice.ord_le_of_mem_principalIdeal (b.value_ne_zero 0) hxIdeal
    by_cases hxzero : q.quadratic x = 0
    · simp [hxzero]
    · let xu : Kˣ := Units.mk0 (q.quadratic x) hxzero
      have hordx : ord K (q.quadratic x) =
          (ordUnit K xu : WithTop Int) := by
        simpa [xu] using (coe_ordUnit K xu).symm
      rw [hordx] at hminimum ⊢
      norm_cast at hminimum ⊢
      have hne : ordUnit K xu ≠ b.order 0 := by
        intro heq
        apply hnot
        apply (b.isNormGenerator_iff_ord_quadratic_eq_head x hx).2
        rw [hordx, heq]
      omega
  · rintro ⟨hx, hthreshold⟩
    refine ⟨hx, ?_⟩
    intro hgenerator
    have horder :=
      (b.isNormGenerator_iff_ord_quadratic_eq_head x hx).1 hgenerator
    rw [horder] at hthreshold
    have hbad : b.order 0 + 1 ≤ b.order 0 :=
      WithTop.coe_le_coe.mp hthreshold
    omega

end BONG

/-- The integral head-rescaling steps in Beli (2003), Lemma 6.1. -/
class BeliLemma61Laws
    (K : Type u) [Field K] [CharZero K] [ValuativeRel K]
    [TopologicalSpace K] [DyadicContext K] : Prop where
  headDepth
    {V : Type v} [AddCommGroup V] [Module K V]
    {q : QuadraticSpace K V} {L : Lattice K V} {n k : Nat}
    (b : BONG V q L (n + 2)) (hgood : b.IsGood)
    (hexists : b.HeadBinaryRescaleExists k)
    (hthird : ∀ _h : 1 ≤ n,
      b.order 0 + 2 * (k : Int) ≤ b.order ⟨2, by omega⟩) :
    Nonempty (BONG.HeadDepthWitness b k)
  headRescale_of_criterion
    {V : Type v} [AddCommGroup V] [Module K V]
    {q : QuadraticSpace K V} {L : Lattice K V} {n : Nat}
    (b : BONG V q L (n + 2)) :
    b.HeadRescaleCriterion → b.HeadBinaryRescaleExists 1

namespace BONG

variable [BeliLemma61Laws.{u, v} K]

/-- Beli (2003), Lemma 6.1(ii). -/
theorem beliLemma61_ii (b : BONG V q L (n + 2)) (hgood : b.IsGood)
    (k : Nat) (hexists : b.HeadBinaryRescaleExists k)
    (hthird : ∀ _h : 1 ≤ n,
      b.order 0 + 2 * (k : Int) ≤ b.order ⟨2, by omega⟩) :
    Nonempty (HeadDepthWitness b k) :=
  BeliLemma61Laws.headDepth b hgood hexists hthird

/-- Beli (2003), Lemma 6.1(i), including the exact carrier. -/
theorem beliLemma61_i (b : BONG V q L (n + 2)) (hgood : b.IsGood)
    (hexists : b.HeadBinaryRescaleExists 1)
    (hthird : ∀ _h : 1 ≤ n,
      b.order 0 + 2 ≤ b.order ⟨2, by omega⟩) :
    ∃ w : HeadDepthWitness b 1,
      ∀ x : V, x ∈ w.lattice ↔
        x ∈ L ∧ ¬Lattice.IsNormGenerator q L x := by
  rcases b.beliLemma61_ii hgood 1 hexists (by simpa using hthird) with ⟨w⟩
  refine ⟨w, ?_⟩
  intro x
  rw [w.mem_lattice_iff]
  have hthreshold :
      ((b.order 0 + 2 * ((1 : Nat) : Int) - 1 : Int) : WithTop Int) =
        ((b.order 0 + 1 : Int) : WithTop Int) := by
    congr 1
    omega
  rw [hthreshold]
  exact (b.mem_and_not_isNormGenerator_iff_ord_ge_head_add_one x).symm

/-- Beli (2003), Lemma 6.1(iii). -/
theorem beliLemma61_iii (b : BONG V q L (n + 2))
    (hcriterion : b.HeadRescaleCriterion) :
    b.HeadBinaryRescaleExists 1 ∧
      (b.HasPropertyB → ∀ _h : 1 ≤ n,
        b.order 0 + 2 ≤ b.order ⟨2, by omega⟩) := by
  refine ⟨BeliLemma61Laws.headRescale_of_criterion b hcriterion, ?_⟩
  intro hB hn
  let i : Fin (n + 2) := ⟨0, by omega⟩
  have hi : i.1 + 2 < n + 2 := by
    simp only [i]
    omega
  have h := hB.twoStep_add_two_le i hi
  simpa [i] using h

end BONG

end Bong
