/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.Beli2019PrimeIndexBasis
import Bong.Bong.Beli2019Lemma718NormalForms
import Bong.Bong.BinaryDiagonalExactBONG
import Bong.Bong.BinaryHyperbolicEndpoint
import Bong.Bong.GoodMap
import Bong.QuadraticSpace.HyperbolicPlane

/-!
# Beli (2019), Lemma 7.18: the index-uniformizer hyperbolic block

For the standard hyperbolic lattice generated by `t, u`, this file constructs
the literal sublattice generated by `t, πu`.  It proves that the inclusion has
index `𝔭`, identifies the resulting quadratic space, and transports an exact
good BONG with values

`π^(R+1), -π^(R-2e+1)`.

This is the atomic geometric step in the construction of the replacement
lattice `N ⊆ M` in Lemma 7.18.
-/

namespace Bong

open Dyadic Module

namespace Lattice

universe u v w

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {W : Type w} [AddCommGroup W] [Module K W]

/-- Taking the lattice spanned by a mapped basis is the same as mapping its
basis lattice. -/
theorem basisLattice_map_linearEquiv {ι : Type*} [Finite ι]
    (b : Basis ι K V) (e : V ≃ₗ[K] W) :
    map e (basisLattice b) = basisLattice (b.map e) := by
  apply Lattice.ext
  ext y
  change y ∈ map e (basisLattice b) ↔ y ∈ basisLattice (b.map e)
  rw [mem_map_iff,
    mem_basisLattice_iff_repr_mem_integerRing,
    mem_basisLattice_iff_repr_mem_integerRing,
    Basis.map_repr]
  rfl

end Lattice

namespace QuadraticSpace

universe u

variable {K : Type u} [Field K]

/-- Scale the second coordinate of a binary space by a nonzero scalar. -/
noncomputable def hyperbolicSecondScaleLinearEquiv (t : Kˣ) :
    (Fin 2 → K) ≃ₗ[K] (Fin 2 → K) where
  toFun x := ![x 0, (t : K) * x 1]
  invFun y := ![y 0, ((t⁻¹ : Kˣ) : K) * y 1]
  left_inv x := by
    funext i
    fin_cases i
    · rfl
    · simp [Units.ne_zero]
  right_inv y := by
    funext i
    fin_cases i
    · rfl
    · simp [Units.ne_zero]
  map_add' x y := by
    funext i
    fin_cases i <;> simp <;> ring
  map_smul' c x := by
    funext i
    fin_cases i <;> simp <;> ring

/-- Scaling the second coordinate carries `H_(s t)` isometrically to `H_s`. -/
noncomputable def hyperbolicSecondScaleIsometry (s t : Kˣ) :
    Isometry (hyperbolicPlane (s * t)) (hyperbolicPlane s) where
  toLinearEquiv := hyperbolicSecondScaleLinearEquiv t
  map_bilin x y := by
    rw [hyperbolicPlane_bilin_apply, hyperbolicPlane_bilin_apply]
    change (s : K) *
        (x 0 * ((t : K) * y 1) + (t : K) * x 1 * y 0) =
      ((s * t : Kˣ) : K) * (x 0 * y 1 + x 1 * y 0)
    simp only [Units.val_mul]
    ring

end QuadraticSpace

namespace Lattice

universe u

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]

/-- The coordinate of the second standard vector in the finrank-indexed
binary-model basis. -/
noncomputable def hyperbolicSecondIndex :
    Fin (finrank K (Fin 2 → K)) :=
  BONG.binaryModelIndexEquiv (K := K) 1

/-- Scaling the second coordinate of the binary-model basis agrees with
mapping that basis by `hyperbolicSecondScaleLinearEquiv π`. -/
theorem coordinateScaleBasis_binaryModel_second_eq_map :
    coordinateScaleBasis (BONG.binaryModelFinrankBasis (K := K))
        (hyperbolicSecondIndex (K := K)) =
      (BONG.binaryModelFinrankBasis (K := K)).map
        (QuadraticSpace.hyperbolicSecondScaleLinearEquiv
          (uniformizerUnit K)) := by
  ext j x
  by_cases hj : j = hyperbolicSecondIndex (K := K)
  · subst j
    rw [coordinateScaleBasis_apply_same, Basis.map_apply]
    fin_cases x
    · simp [BONG.binaryModelFinrankBasis, BONG.binaryModelBasis,
        QuadraticSpace.hyperbolicSecondScaleLinearEquiv,
        hyperbolicSecondIndex, coe_uniformizerUnit]
    · simp [BONG.binaryModelFinrankBasis, BONG.binaryModelBasis,
        QuadraticSpace.hyperbolicSecondScaleLinearEquiv,
        hyperbolicSecondIndex, coe_uniformizerUnit]
  · rw [coordinateScaleBasis_apply_of_ne _ hj, Basis.map_apply]
    let k : Fin 2 := (BONG.binaryModelIndexEquiv (K := K)).symm j
    have hjk : j = BONG.binaryModelIndexEquiv (K := K) k := by
      simp [k]
    have hk : k ≠ 1 := by
      intro hk
      apply hj
      rw [hjk, hk]
      rfl
    have hk0 : k = 0 := by
      apply Fin.ext
      have hkval : k.val ≠ 1 := by
        intro hval
        apply hk
        apply Fin.ext
        simpa using hval
      omega
    rw [hjk, hk0]
    fin_cases x <;>
      simp [BONG.binaryModelFinrankBasis, BONG.binaryModelBasis,
        QuadraticSpace.hyperbolicSecondScaleLinearEquiv]

/-- The standard binary lattice with its second basis vector multiplied by
the selected uniformizer. -/
noncomputable def hyperbolicIndexPLattice : Lattice K (Fin 2 → K) :=
  basisLattice
    (coordinateScaleBasis (BONG.binaryModelFinrankBasis (K := K))
      (hyperbolicSecondIndex (K := K)))

/-- The index-`𝔭` hyperbolic lattice is the image of the standard lattice
under second-coordinate scaling. -/
theorem hyperbolicIndexPLattice_eq_map :
    hyperbolicIndexPLattice (K := K) =
      map
        (QuadraticSpace.hyperbolicSecondScaleLinearEquiv
          (uniformizerUnit K))
        (hyperbolicPlaneLattice (K := K)) := by
  rw [hyperbolicIndexPLattice,
    coordinateScaleBasis_binaryModel_second_eq_map,
    ← basisLattice_map_linearEquiv]
  congr 1
  rw [BONG.basisLattice_binaryModelFinrankBasis]
  rfl

/-- Multiplying the second hyperbolic basis vector by `π` gives a literal
index-`𝔭` inclusion. -/
theorem hyperbolicIndexPInclusion (s : Kˣ) :
    Beli2019IndexPInclusion (QuadraticSpace.hyperbolicPlane s)
      (hyperbolicPlaneLattice (K := K))
      (hyperbolicIndexPLattice (K := K)) := by
  have h := indexPInclusion_coordinateScaleBasis
    (QuadraticSpace.hyperbolicPlane s)
    (BONG.binaryModelFinrankBasis (K := K))
    (hyperbolicSecondIndex (K := K))
  rw [BONG.basisLattice_binaryModelFinrankBasis] at h
  exact h

/-- The standard lattice in `H_(sπ)` is isometric to the index-`𝔭`
sublattice of the standard lattice in `H_s`. -/
noncomputable def hyperbolicIndexPIsometry (s : Kˣ) :
    Isometry
      (QuadraticSpace.hyperbolicPlane (s * uniformizerUnit K))
      (QuadraticSpace.hyperbolicPlane s)
      (hyperbolicPlaneLattice (K := K))
      (hyperbolicIndexPLattice (K := K)) where
  toLinearEquiv :=
    QuadraticSpace.hyperbolicSecondScaleLinearEquiv
      (uniformizerUnit K)
  map_bilin :=
    (QuadraticSpace.hyperbolicSecondScaleIsometry
      s (uniformizerUnit K)).map_bilin
  map_mem x := by
    rw [hyperbolicIndexPLattice_eq_map]
    exact (map_mem_map_iff
      (QuadraticSpace.hyperbolicSecondScaleLinearEquiv
        (uniformizerUnit K))
      (hyperbolicPlaneLattice (K := K)) x).symm

end Lattice

namespace BONG

universe u

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]

/-- The high coefficient of a hyperbolic block after replacing `u` by
`πu`. -/
noncomputable def lemma718IndexPHigh (R : Int) : Kˣ :=
  uniformizerPowerUnit K (R + 1)

/-- The low coefficient of a hyperbolic block after replacing `u` by
`πu`. -/
noncomputable def lemma718IndexPLow (R : Int) : Kˣ :=
  -(uniformizerPowerUnit K
    (R - 2 * (ramificationIndex K : Int) + 1))

/-- The ratio of the two replacement coefficients has the required
negative-quarter square class. -/
theorem lemma718IndexPParameter_eq (R : Int) :
    lemma718IndexPLow (K := K) R /
        lemma718IndexPHigh (K := K) R =
      uniformizerPowerUnit K
          (-(2 * (ramificationIndex K : Int))) * (-1) := by
  unfold lemma718IndexPLow lemma718IndexPHigh
  calc
    (-(uniformizerPowerUnit K
        (R - 2 * (ramificationIndex K : Int) + 1))) /
        uniformizerPowerUnit K (R + 1) =
      -(uniformizerPowerUnit K
        (R - 2 * (ramificationIndex K : Int) + 1) /
          uniformizerPowerUnit K (R + 1)) := by
      exact neg_div _ _
    _ = -(uniformizerPowerUnit K
        (-(2 * (ramificationIndex K : Int)))) := by
      congr 1
      unfold uniformizerPowerUnit
      rw [div_eq_mul_inv, ← zpow_neg, ← zpow_add]
      congr 1
      omega
    _ = uniformizerPowerUnit K
          (-(2 * (ramificationIndex K : Int))) * (-1) := by
      simp

/-- The exact replacement coefficient pair defines an integral binary
diagonal model. -/
theorem lemma718IndexPParameter_admissible (R : Int) :
    IsBinaryParameterAdmissible
      (lemma718IndexPLow (K := K) R /
        lemma718IndexPHigh (K := K) R) := by
  let c : K :=
    (uniformizerPowerUnit K (-(ramificationIndex K : Int)) : K)
  have hcOrder : ord K c =
      ((-(ramificationIndex K : Int) : Int) : WithTop Int) := by
    change ord K
      ((uniformizerPowerUnit K (-(ramificationIndex K : Int)) : K)) = _
    rw [← coe_ordUnit, ordUnit_uniformizerPowerUnit]
  refine ⟨c, ?_, ?_⟩
  · apply (mem_integerRing_iff K).2
    rw [Dyadic.IsIntegral, ord_mul, ← ramificationIndex_spec, hcOrder]
    norm_num
  · have hparameter := lemma718IndexPParameter_eq (K := K) R
    have hcSq :
        c ^ 2 =
          (uniformizerPowerUnit K
            (-(2 * (ramificationIndex K : Int))) : K) := by
      have hunitSq :
          uniformizerPowerUnit K (-(ramificationIndex K : Int)) ^ 2 =
            uniformizerPowerUnit K
              (-(2 * (ramificationIndex K : Int))) := by
        unfold uniformizerPowerUnit
        rw [pow_two, ← zpow_add]
        congr 1
        ring
      simpa [c] using congrArg Units.val hunitSq
    have hparameterK := congrArg Units.val hparameter
    rw [hcSq, hparameterK]
    simp

/-- The exact binary good BONG used for the replacement block. -/
noncomputable def lemma718IndexPModelGoodBONG (R : Int) :
    GoodBONG
      (binaryDiagonalModelSpace
        (lemma718IndexPHigh (K := K) R)
        (lemma718IndexPLow (K := K) R)
        (lemma718IndexPParameter_admissible (K := K) R))
      (binaryDiagonalModelLattice (K := K)) 2 :=
  binaryDiagonalExactGoodBONG
    (lemma718IndexPHigh (K := K) R)
    (lemma718IndexPLow (K := K) R)
    (lemma718IndexPParameter_admissible (K := K) R)

/-- The exact replacement model is in the negative-quarter binary square
class. -/
theorem lemma718IndexPModel_binaryUnitSquareClass (R : Int) :
    (lemma718IndexPModelGoodBONG (K := K) R).toBONG.binaryUnitSquareClass =
      unitSquareClass K (negativeQuarterUnit K) := by
  let b := lemma718IndexPModelGoodBONG (K := K) R
  change unitSquareClass K (b.valueUnit 1 / b.valueUnit 0) = _
  rw [show b.valueUnit 0 = lemma718IndexPHigh (K := K) R by
      simpa [b, lemma718IndexPModelGoodBONG] using
        binaryDiagonalExactGoodBONG_valueUnit
          (lemma718IndexPHigh (K := K) R)
          (lemma718IndexPLow (K := K) R)
          (lemma718IndexPParameter_admissible (K := K) R) 0,
    show b.valueUnit 1 = lemma718IndexPLow (K := K) R by
      simpa [b, lemma718IndexPModelGoodBONG] using
        binaryDiagonalExactGoodBONG_valueUnit
          (lemma718IndexPHigh (K := K) R)
          (lemma718IndexPLow (K := K) R)
          (lemma718IndexPParameter_admissible (K := K) R) 1,
    lemma718IndexPParameter_eq]
  apply unitSquareClass_uniformizerPower_mul_eq_negativeQuarter
  · change ord K ((-1 : Kˣ) : K) = 0
    simp
  · rfl
  · exact ⟨1, by simp⟩

/-- The exact replacement model is the standard lattice in the hyperbolic
plane of scale `π^(R+1-e)`. -/
theorem lemma718IndexPModel_isIsometric_hyperbolic (R : Int) :
    Lattice.IsIsometric
      (binaryDiagonalModelSpace
        (lemma718IndexPHigh (K := K) R)
        (lemma718IndexPLow (K := K) R)
        (lemma718IndexPParameter_admissible (K := K) R))
      (QuadraticSpace.hyperbolicPlane
        (uniformizerPowerUnit K
          (R + 1 - ramificationIndex K)))
      (binaryDiagonalModelLattice (K := K))
      (Lattice.hyperbolicPlaneLattice (K := K)) := by
  let b := lemma718IndexPModelGoodBONG (K := K) R
  have h := b.toBONG.isIsometric_hyperbolicPlane_of_binaryUnitSquareClass_eq_negativeQuarter
    (lemma718IndexPModel_binaryUnitSquareClass (K := K) R)
  have hOrderDef :
      b.toBONG.order (0 : Fin 2) = b.order (0 : Fin 2) := rfl
  rw [hOrderDef] at h
  simpa [b, lemma718IndexPModelGoodBONG,
    lemma718IndexPHigh] using h

/-- Multiplication by one additional uniformizer increments the selected
uniformizer exponent. -/
theorem lemma718_uniformizerPowerUnit_mul_uniformizerUnit (z : Int) :
    uniformizerPowerUnit K z * uniformizerUnit K =
      uniformizerPowerUnit K (z + 1) := by
  unfold uniformizerPowerUnit
  calc
    uniformizerUnit K ^ z * uniformizerUnit K =
        uniformizerUnit K ^ z * uniformizerUnit K ^ (1 : Int) := by
      rw [zpow_one]
    _ = uniformizerUnit K ^ (z + 1) := by
      rw [← zpow_add]

/-- A concrete isometry from the exact replacement model to the literal
index-`𝔭` sublattice of the original hyperbolic plane. -/
noncomputable def lemma718IndexPModelToLattice (R : Int) :
    Lattice.Isometry
      (binaryDiagonalModelSpace
        (lemma718IndexPHigh (K := K) R)
        (lemma718IndexPLow (K := K) R)
        (lemma718IndexPParameter_admissible (K := K) R))
      (QuadraticSpace.hyperbolicPlane
        (uniformizerPowerUnit K
          (R - ramificationIndex K)))
      (binaryDiagonalModelLattice (K := K))
      (Lattice.hyperbolicIndexPLattice (K := K)) := by
  let f := Classical.choice
    (lemma718IndexPModel_isIsometric_hyperbolic (K := K) R)
  let g₀ := Lattice.hyperbolicIndexPIsometry
    (uniformizerPowerUnit K (R - ramificationIndex K))
  have hscale :
      uniformizerPowerUnit K (R - ramificationIndex K) *
          uniformizerUnit K =
        uniformizerPowerUnit K
          (R + 1 - ramificationIndex K) := by
    rw [lemma718_uniformizerPowerUnit_mul_uniformizerUnit]
    congr 1
    omega
  have g :
      Lattice.Isometry
        (QuadraticSpace.hyperbolicPlane
          (uniformizerPowerUnit K
            (R + 1 - ramificationIndex K)))
        (QuadraticSpace.hyperbolicPlane
          (uniformizerPowerUnit K
            (R - ramificationIndex K)))
        (Lattice.hyperbolicPlaneLattice (K := K))
        (Lattice.hyperbolicIndexPLattice (K := K)) := by
    simpa only [g₀, hscale] using g₀
  exact f.trans g

/-- The literal index-`𝔭` hyperbolic sublattice, equipped with the exact good
BONG asserted for one replacement block in Lemma 7.18. -/
noncomputable def lemma718IndexPHyperbolicGoodBONG (R : Int) :
    GoodBONG
      (QuadraticSpace.hyperbolicPlane
        (uniformizerPowerUnit K
          (R - ramificationIndex K)))
      (Lattice.hyperbolicIndexPLattice (K := K)) 2 :=
  (lemma718IndexPModelGoodBONG (K := K) R).mapLatticeIsometry
    (lemma718IndexPModelToLattice (K := K) R)

@[simp]
theorem lemma718IndexPHyperbolicGoodBONG_valueUnit
    (R : Int) (i : Fin 2) :
    (lemma718IndexPHyperbolicGoodBONG (K := K) R).valueUnit i =
      ![lemma718IndexPHigh (K := K) R,
        lemma718IndexPLow (K := K) R] i := by
  rw [lemma718IndexPHyperbolicGoodBONG,
    GoodBONG.valueUnit_mapLatticeIsometry]
  exact binaryDiagonalExactGoodBONG_valueUnit
    (lemma718IndexPHigh (K := K) R)
    (lemma718IndexPLow (K := K) R)
    (lemma718IndexPParameter_admissible (K := K) R) i

/-- The geometric replacement block comes with its required literal
index-`𝔭` inclusion into the original hyperbolic lattice. -/
theorem lemma718IndexPHyperbolicInclusion (R : Int) :
    Beli2019IndexPInclusion
      (QuadraticSpace.hyperbolicPlane
        (uniformizerPowerUnit K (R - ramificationIndex K)))
      (Lattice.hyperbolicPlaneLattice (K := K))
      (Lattice.hyperbolicIndexPLattice (K := K)) :=
  Lattice.hyperbolicIndexPInclusion
    (uniformizerPowerUnit K (R - ramificationIndex K))

end BONG

end Bong
