/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/

import Bong.Bong.Representation
import Bong.Lattice.Sum

/-!
# A common integral envelope for an ambient representation

An ambient quadratic-space representation need not carry the source lattice
into the given target lattice.  For Beli's unequal-rank completion argument we
enlarge the target lattice by the integral image of the source lattice.  The
result is still a full finitely generated lattice because the original target
lattice already spans the ambient vector space.
-/

namespace Bong

open Dyadic

universe u v w

namespace Lattice

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {W : Type w} [AddCommGroup W] [Module K W]
  {q : QuadraticSpace K V} {r : QuadraticSpace K W}

/-- The full lattice generated by `L` and the image of `M` under an ambient
quadratic-space representation. -/
noncomputable def representationEnvelope
    (f : QuadraticSpace.Representation r q)
    (L : Lattice K V) (M : Lattice K W) : Lattice K V where
  toSubmodule := L.toSubmodule ⊔ M.toSubmodule.map
    (f.toLinearMap.restrictScalars (IntegerRing K))
  fg := L.fg.sup (M.fg.map
    (f.toLinearMap.restrictScalars (IntegerRing K)))
  span_eq_top := by
    apply top_unique
    intro x _
    have hx : x ∈ Submodule.span K (L.toSubmodule : Set V) := by
      rw [L.span_eq_top]
      exact Submodule.mem_top
    exact Submodule.span_mono (fun _ hy ↦ Submodule.mem_sup_left hy) hx

/-- The original target lattice lies in its representation envelope. -/
theorem le_representationEnvelope
    (f : QuadraticSpace.Representation r q)
    (L : Lattice K V) (M : Lattice K W) :
    L ≤ representationEnvelope f L M :=
  fun _ hx ↦ Submodule.mem_sup_left hx

/-- The ambient map is integral after passing to the representation
envelope. -/
noncomputable def Representation.ofAmbientToEnvelope
    (f : QuadraticSpace.Representation r q)
    (L : Lattice K V) (M : Lattice K W) :
    Lattice.Representation r q M (representationEnvelope f L M) where
  toLinearMap := f.toLinearMap
  injective := f.injective
  map_bilin := f.map_bilin
  map_mem {x} hx := by
    apply Submodule.mem_sup_right
    exact Submodule.mem_map_of_mem hx

end Lattice

end Bong
