/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.Beli2019Lemma714TypeIIBlock
import Bong.Bong.Beli2019Lemma714RescaledBinary
import Bong.Bong.Beli2019Lemma714BoundaryOrders

/-!
# Beli (2019), Lemma 7.14(ii): locating the type-II block

The exceptional unary vector is the one-entry segment at zero-based index
`s` of the original BONG, or index `s - 2` of the tail after the initial
binary split.  This file verifies that its order is one below the first value
of `πJ` and transports the initial discriminant endpoint class to `πJ`.
-/

namespace Bong

open Dyadic

universe u v

namespace BONG.GoodBONG

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {q : QuadraticSpace K V} {L : Lattice K V} {n : Nat}

private theorem lemma714Two_le_rank (n : Nat) : 2 ≤ n + 3 := by
  omega

/-- The good BONG on the initial binary factor. -/
noncomputable def lemma714InitialBinary
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714Two_le_rank n)) :
    GoodBONG (q.restrict S.left.carrier S.left.nondegenerate)
      S.left.lattice 2 :=
  S.left.toGoodBONG b.good

/-- The good BONG on the full tail after the initial binary factor. -/
noncomputable def lemma714Tail
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714Two_le_rank n)) :
    GoodBONG (q.restrict S.right.carrier S.right.nondegenerate)
      S.right.lattice (n + 1) :=
  (S.right.toGoodBONG b.good).castLength (by omega)

@[simp]
theorem lemma714Tail_order
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714Two_le_rank n))
    (i : Fin (n + 1)) :
    (b.lemma714Tail S).order i = b.order ⟨2 + i.val, by omega⟩ := by
  rw [lemma714Tail, order_castLength]
  change S.right.bong.order ⟨i.val, by omega⟩ = _
  rw [S.right.order_eq]
  rfl

@[simp]
theorem lemma714Tail_valueUnit
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714Two_le_rank n))
    (i : Fin (n + 1)) :
    (b.lemma714Tail S).valueUnit i =
      b.valueUnit ⟨2 + i.val, by omega⟩ := by
  rw [lemma714Tail, valueUnit_castLength]
  change S.right.bong.valueUnit ⟨i.val, by omega⟩ = _
  rw [S.right.valueUnit_eq]
  rfl

/-- The literal unary segment generated by the paper's vector `x_(s+1)`. -/
noncomputable def lemma714TypeIILineSegment
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714Two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hs : s < n + 3) :
    SegmentWitness (b.lemma714Tail S).toBONG (s - 2) 1 (by omega) :=
  (b.lemma714Tail S).toBONG.segmentWitness (s - 2) 1 (by omega)

/-- The one-entry segment at `s` bundled as a good BONG. -/
noncomputable def lemma714TypeIILine
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714Two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hs : s < n + 3) :
    GoodBONG
      ((q.restrict S.right.carrier S.right.nondegenerate).restrict
        (b.lemma714TypeIILineSegment S s hsTwo hs).carrier
        (b.lemma714TypeIILineSegment S s hsTwo hs).nondegenerate)
      (b.lemma714TypeIILineSegment S s hsTwo hs).lattice 1 :=
  (b.lemma714TypeIILineSegment S s hsTwo hs).toGoodBONG
    (b.lemma714Tail S).good

@[simp]
theorem lemma714TypeIILine_order_zero
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714Two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hs : s < n + 3) :
    (b.lemma714TypeIILine S s hsTwo hs).order 0 =
      b.order ⟨s, hs⟩ := by
  change (b.lemma714TypeIILineSegment S s hsTwo hs).bong.order 0 = _
  rw [SegmentWitness.order_eq]
  change (b.lemma714Tail S).order
      ((b.lemma714TypeIILineSegment S s hsTwo hs).sourceIndex 0) = _
  rw [b.lemma714Tail_order S]
  congr 1
  apply Fin.ext
  change 2 + (s - 2 + 0) = s
  omega

@[simp]
theorem lemma714TypeIILine_valueUnit_zero
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714Two_le_rank n))
    (s : Nat) (hsTwo : 2 ≤ s) (hs : s < n + 3) :
    (b.lemma714TypeIILine S s hsTwo hs).valueUnit 0 =
      b.valueUnit ⟨s, hs⟩ := by
  change (b.lemma714TypeIILineSegment S s hsTwo hs).bong.valueUnit 0 = _
  rw [SegmentWitness.valueUnit_eq]
  change (b.lemma714Tail S).valueUnit
      ((b.lemma714TypeIILineSegment S s hsTwo hs).sourceIndex 0) = _
  rw [b.lemma714Tail_valueUnit S]
  congr 1
  apply Fin.ext
  simp only [SegmentWitness.sourceIndex_val]
  omega

/-- The initial binary factor has the same endpoint class as the first two
entries of the original BONG. -/
theorem lemma714InitialBinary_binaryUnitSquareClass
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714Two_le_rank n)) :
    (b.lemma714InitialBinary S).toBONG.binaryUnitSquareClass =
      b.toBONG.adjacentUnitSquareClass (0 : Fin (n + 3)) (by simp) := by
  change S.left.bong.binaryUnitSquareClass =
    b.toBONG.adjacentUnitSquareClass (0 : Fin (n + 3)) (by simp)
  unfold BONG.binaryUnitSquareClass BONG.binaryParameter
    BONG.adjacentUnitSquareClass BONG.adjacentParameter
  apply congrArg (unitSquareClass K)
  rw [S.left.valueUnit_eq, S.left.valueUnit_eq]
  have hzero : S.left.sourceIndex (0 : Fin 2) =
      (0 : Fin (n + 3)) := by
    apply Fin.ext
    rfl
  have hone : S.left.sourceIndex (1 : Fin 2) =
      (1 : Fin (n + 3)) := by
    apply Fin.ext
    rfl
  rw [hzero, hone]
  congr 2

/-- The rescaled initial binary factor inherits the paper's discriminant
endpoint square class. -/
theorem lemma714RescaledInitialBinary_discriminantClass
    [laws : DyadicDiscriminantClassLaws K]
    (b : GoodBONG q L (n + 3))
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714Two_le_rank n))
    (hdiscriminant : b.toBONG.adjacentUnitSquareClass
      (0 : Fin (n + 3)) (by simp) = unitSquareClass K
        (lemma712DiscriminantParameter (K := K))) :
    ((b.lemma714InitialBinary S).lemma714RescaledBinary).toBONG.binaryUnitSquareClass =
      unitSquareClass K (lemma712DiscriminantParameter (K := K)) := by
  rw [lemma714RescaledBinary_binaryUnitSquareClass,
    b.lemma714InitialBinary_binaryUnitSquareClass S, hdiscriminant]

/-- The exact exceptional ternary block in Lemma 7.14(ii), now attached to
the actual initial binary split and the actual vector `x_(s+1)`. -/
theorem exists_lemma714_typeII_actualLocalBlock
    [laws : DyadicDiscriminantClassLaws K]
    [QuadraticDefectLaws K]
    [DyadicUnramifiedNormLaws K]
    [HilbertSymbolLaws K]
    [DyadicDiagonalClassificationLaws K]
    [BONGStructuralLaws.{u, u} K]
    [Beli2009WeightIdealData.{u, u} K]
    [Beli2019UnaryBinaryJordanLaws.{u} K]
    [Beli2009JordanWeightOrderLaws.{u, u} K]
    [Beli2006AlphaLaws.{u, u} K]
    [BeliLemma43ConstructionLaws.{u, u} K]
    [Beli2006SectionTwoLaws.{u, u} K]
    [GoodBONGClassificationLaws.{u, u, u} K]
    (b : GoodBONG q L (n + 3)) (R : Int) (s : Nat)
    (D : Lemma714StoppingData b R s)
    (hfirst : b.order ⟨0, by omega⟩ = R)
    (hII : Lemma714IsTypeII b R s)
    (S : TwoBlockSplitWitness b.toBONG 2 (lemma714Two_le_rank n))
    (hdiscriminant : b.toBONG.adjacentUnitSquareClass
      (0 : Fin (n + 3)) (by simp) = unitSquareClass K
        (lemma712DiscriminantParameter (K := K)))
    (ε η : Kˣ)
    (hεUnit : IsValuationUnit K (ε : K))
    (hηUnit : IsValuationUnit K (η : K))
    (hεDefect : defectOrder (K := K) ε = (1 : WithTop ℚ))
    (hηDefect : defectOrder (K := K) η =
      (((2 * (ramificationIndex K : ℚ) - 1 : ℚ)) : WithTop ℚ))
    (hhilbert : hilbertSymbol K ε η = -1) :
    let hs := Classical.choose hII
    let line := b.lemma714TypeIILine S s D.two_le hs
    ∃ block : GoodBONG
        ((q.restrict S.left.carrier S.left.nondegenerate).orthogonalSum
          ((q.restrict S.right.carrier S.right.nondegenerate).restrict
            (b.lemma714TypeIILineSegment S s D.two_le hs).carrier
            (b.lemma714TypeIILineSegment S s D.two_le hs).nondegenerate))
        (Lattice.product
          (Lattice.rescale (uniformizerUnit K) S.left.lattice)
          (b.lemma714TypeIILineSegment S s D.two_le hs).lattice) 3,
      ∀ i, block.valueUnit i =
        lemma712TargetValues (line.valueUnit 0) ε η i := by
  let hs : s < n + 3 := Classical.choose hII
  have hsOrder : b.order ⟨s, hs⟩ = R + 1 :=
    Classical.choose_spec hII
  let j := b.lemma714InitialBinary S
  let pj := j.lemma714RescaledBinary
  let line := b.lemma714TypeIILine S s D.two_le hs
  have hj0 : j.order 0 = R := by
    calc
      j.order 0 = b.order (S.left.sourceIndex 0) := S.left.order_eq 0
      _ = b.order 0 := by congr 1
      _ = R := hfirst
  have hp : pj.order 0 = line.order 0 + 1 := by
    rw [show pj = j.lemma714RescaledBinary by rfl,
      lemma714RescaledBinary_order, hj0]
    rw [show line = b.lemma714TypeIILine S s D.two_le hs by rfl,
      b.lemma714TypeIILine_order_zero S s D.two_le hs, hsOrder]
    omega
  have hclass : pj.toBONG.binaryUnitSquareClass = unitSquareClass K
      (lemma712DiscriminantParameter (K := K)) := by
    exact b.lemma714RescaledInitialBinary_discriminantClass S hdiscriminant
  simpa only [hs, line, j, pj] using
    pj.exists_lemma714_typeII_localGoodBONG line hp hclass ε η
      hεUnit hηUnit hεDefect hηDefect hhilbert

end BONG.GoodBONG

end Bong
