/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.BinaryDiagonal
import Bong.Lattice.BasisUnits
import Bong.Lattice.NormGeneratorValues
import Bong.Lattice.PowerIdeal
import Bong.Lattice.QuadraticValues

/-!
# Quadratic values of normalized binary BONG lattices

The positive-order case of Beli (2003), Corollary 3.10 is a direct diagonal
calculation.  If the first BONG value is `1` and its order does not exceed the
second order, every lattice value is an integral square modulo the principal
ideal generated by the second BONG value.
-/

namespace Bong

open Dyadic
open Module

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {q : QuadraticSpace K V} {L : Lattice K V}

namespace BONG

/-- The quadratic value of a vector in binary BONG coordinates. -/
theorem quadratic_eq_binaryBasis_repr (b : BONG V q L 2) (z : V) :
    q.quadratic z =
      (b.basis.repr z 0) ^ 2 * b.value 0 +
        (b.basis.repr z 1) ^ 2 * b.value 1 := by
  have hz := b.basis.sum_repr z
  rw [Fin.sum_univ_two] at hz
  calc
    q.quadratic z = q.quadratic
        ((b.basis.repr z 0) • b.basis 0 +
          (b.basis.repr z 1) • b.basis 1) :=
      congrArg q.quadratic hz.symm
    _ = (b.basis.repr z 0) ^ 2 * b.value 0 +
        (b.basis.repr z 1) ^ 2 * b.value 1 := by
      rw [q.quadratic_add, q.quadratic_smul,
        q.quadratic_smul]
      have hvalueZero : q.quadratic (b.basis 0) = b.value 0 := by
        change q.quadratic (b.ambientVector 0) = b.value 0
        exact b.quadratic_ambientVector 0
      have hvalueOne : q.quadratic (b.basis 1) = b.value 1 := by
        change q.quadratic (b.ambientVector 1) = b.value 1
        exact b.quadratic_ambientVector 1
      have horth : q.bilin (b.basis 0) (b.basis 1) = 0 := by
        apply (LinearMap.BilinForm.iIsOrtho_def.mp b.ambientVector_iIsOrtho)
        decide
      rw [hvalueZero, hvalueOne,
        LinearMap.BilinForm.smul_left,
        LinearMap.BilinForm.smul_right, horth]
      ring

/-- Ideal-valued form of Beli (2003), Corollary 3.10(a). -/
theorem quadraticValueSet_subset_integralSquareResidueSet_value_one
    (b : BONG V q L 2) (hvalue : b.value 0 = 1)
    (horder : b.order 0 ≤ b.order 1) :
    Lattice.quadraticValueSet q L ⊆
      Lattice.integralSquareResidueSet
        (Lattice.principalIdeal (K := K) (b.value 1)) := by
  intro z hz
  rw [Lattice.mem_quadraticValueSet_iff] at hz
  rcases hz with ⟨x, hx, rfl⟩
  have hxBasis : x ∈ Lattice.basisLattice b.basis := by
    rw [← b.lattice_eq_basisLattice_of_order_le horder]
    exact hx
  have hxIntegral :=
    (Lattice.mem_basisLattice_iff_repr_mem_integerRing b.basis x).1 hxBasis
  let a : IntegerRing K := ⟨b.basis.repr x 0, hxIntegral 0⟩
  let c : IntegerRing K := ⟨b.basis.repr x 1, hxIntegral 1⟩
  refine ⟨a, ?_⟩
  rw [b.quadratic_eq_binaryBasis_repr, hvalue, mul_one]
  have hmem :=
    (Lattice.principalIdeal (K := K) (b.value 1)).smul_mem
      (c ^ 2) (Lattice.generator_mem_principalIdeal (b.value 1))
  change
    (b.basis.repr x 0) ^ 2 +
          (b.basis.repr x 1) ^ 2 * b.value 1 -
        (b.basis.repr x 0) ^ 2 ∈
      Lattice.principalIdeal (K := K) (b.value 1)
  convert hmem using 1 <;> simp [c, Algebra.smul_def, mul_comm]

/-- Positive binary order supplies the order hypothesis in Corollary 3.10(a). -/
theorem quadraticValueSet_subset_of_normalized_binaryOrderGap_pos
    (b : BONG V q L 2) (hvalue : b.value 0 = 1)
    (hgap : 0 < b.binaryOrderGap) :
    Lattice.quadraticValueSet q L ⊆
      Lattice.integralSquareResidueSet
        (Lattice.principalIdeal (K := K) (b.value 1)) := by
  apply b.quadraticValueSet_subset_integralSquareResidueSet_value_one hvalue
  rw [binaryOrderGap] at hgap
  omega

/-- Corollary 3.10(a) in Beli's original `𝔭ᴿ` notation. -/
theorem quadraticValueSet_subset_powerIdeal_of_normalized_binaryOrderGap_pos
    (b : BONG V q L 2) (hvalue : b.value 0 = 1)
    (hgap : 0 < b.binaryOrderGap) :
    Lattice.quadraticValueSet q L ⊆
      Lattice.integralSquareResidueSet
        (Lattice.powerIdeal (K := K) b.binaryOrderGap) := by
  have hzero : b.order 0 = 0 := by
    apply WithTop.coe_injective
    rw [b.coe_order, hvalue, ord_one]
    rfl
  have hone : b.order 1 = b.binaryOrderGap := by
    rw [binaryOrderGap, hzero]
    omega
  have hideal :
      Lattice.principalIdeal (K := K) (b.value 1) =
        Lattice.powerIdeal (K := K) b.binaryOrderGap := by
    calc
      Lattice.principalIdeal (K := K) (b.value 1) =
          Lattice.powerIdeal (K := K)
            (ordUnit K (b.valueUnit 1)) :=
        Lattice.principalIdeal_eq_powerIdeal (b.valueUnit 1)
      _ = Lattice.powerIdeal (K := K) b.binaryOrderGap := by
        rw [← b.order_eq_ordUnit, hone]
  simpa [hideal] using
    b.quadraticValueSet_subset_of_normalized_binaryOrderGap_pos
      hvalue hgap

/-- For a normalized binary BONG, norm-generator values are exactly the
valuation-unit part of the full quadratic value set. -/
theorem normGeneratorValueSet_eq_quadraticValueSet_inter
    (b : BONG V q L 2) (hvalue : b.value 0 = 1) :
    Lattice.normGeneratorValueSet q L =
      Lattice.quadraticValueSet q L ∩
        {a | IsValuationUnit K a} := by
  apply Lattice.normGeneratorValueSet_eq_quadraticValueSet_inter
    b.head_isNormGenerator b.head_isAnisotropic
  rw [← b.value_zero_eq_quadratic_head]
  exact hvalue

/-- The norm-generator part of Corollary 3.10(a), used in Lemma 3.11. -/
theorem normGeneratorValueSet_subset_of_normalized_binaryOrderGap_pos
    (b : BONG V q L 2) (hvalue : b.value 0 = 1)
    (hgap : 0 < b.binaryOrderGap) :
    Lattice.normGeneratorValueSet q L ⊆
      Lattice.integralSquareResidueSet
        (Lattice.principalIdeal (K := K) (b.value 1)) := by
  intro a ha
  apply b.quadraticValueSet_subset_of_normalized_binaryOrderGap_pos
    hvalue hgap
  rw [Lattice.mem_quadraticValueSet_iff]
  rcases ha with ⟨x, hx, rfl⟩
  exact ⟨x, hx.mem, rfl⟩

end BONG

end Bong
