/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.BasisLattice
import Bong.Bong.BinarySpinorInclusion
import Bong.Bong.SegmentConstruction
import Bong.Lattice.BasisUnits

/-!
# Integral-square shifts of binary BONGs

Multiplying the second vector of a binary BONG by an integral nonzero scalar
replaces its projected unary lattice by a sublattice.  Pulling that sublattice
back while keeping the first norm generator gives the lattice inclusion used
in Beli (2003), Lemma 3.8.  The binary parameter is multiplied by the square
of the scalar, and the integral spinor-norm image can only decrease.
-/

namespace Bong

open Dyadic
open Module

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {q : QuadraticSpace K V} {L : Lattice K V}

namespace BONG

/-- The unary tail basis obtained by multiplying the original tail vector by
an arbitrary nonzero scalar. -/
noncomputable def binaryScaledTailBasis (b : BONG V q L 2) (s : Kˣ) :
    Basis (Fin 1) K (q.vectorOrthogonal b.head) :=
  s • b.tail.basis

/-- The integral lattice generated by the scaled unary tail basis. -/
noncomputable def binaryScaledTailLattice (b : BONG V q L 2) (s : Kˣ) :
    Lattice K (q.vectorOrthogonal b.head) :=
  Lattice.basisLattice (b.binaryScaledTailBasis s)

private theorem binaryScaledTailBasis_iIsOrtho
    (b : BONG V q L 2) (s : Kˣ) :
    (q.orthogonalSpace b.head b.head_isAnisotropic).bilin.iIsOrtho
      (b.binaryScaledTailBasis s) := by
  rw [LinearMap.BilinForm.iIsOrtho_def]
  intro i j hij
  exact (hij (Subsingleton.elim i j)).elim

private theorem binaryScaledTailBasis_quadratic_ne_zero
    (b : BONG V q L 2) (s : Kˣ) :
    (q.orthogonalSpace b.head b.head_isAnisotropic).quadratic
      (b.binaryScaledTailBasis s 0) ≠ 0 := by
  rw [binaryScaledTailBasis, Basis.smul_apply,
    Units.smul_def, QuadraticSpace.quadratic_smul]
  exact mul_ne_zero (pow_ne_zero 2 (Units.ne_zero s))
    (by
      change
        (q.orthogonalSpace b.head b.head_isAnisotropic).quadratic
          (b.tail.ambientVector 0) ≠ 0
      rw [quadratic_ambientVector]
      exact b.tail.value_ne_zero 0)

/-- The canonical unary BONG carried by the scaled tail lattice. -/
noncomputable def binaryScaledTailBONG (b : BONG V q L 2) (s : Kˣ) :
    BONG (q.vectorOrthogonal b.head)
      (q.orthogonalSpace b.head b.head_isAnisotropic)
      (b.binaryScaledTailLattice s) 1 :=
    BONG.ofOrthogonalBasisFinOne
    (q.orthogonalSpace b.head b.head_isAnisotropic)
    (b.binaryScaledTailBasis s)
    (binaryScaledTailBasis_iIsOrtho b s)
    (binaryScaledTailBasis_quadratic_ne_zero b s)

@[simp]
theorem binaryScaledTailBONG_ambientVector_zero
    (b : BONG V q L 2) (s : Kˣ) :
    (b.binaryScaledTailBONG s).ambientVector 0 =
      b.binaryScaledTailBasis s 0 := by
  simpa [binaryScaledTailBONG, binaryScaledTailLattice] using
    ambientVector_ofOrthogonalBasisFinOne
      (q.orthogonalSpace b.head b.head_isAnisotropic)
      (b.binaryScaledTailBasis s)
      (binaryScaledTailBasis_iIsOrtho b s)
      (binaryScaledTailBasis_quadratic_ne_zero b s) 0

/-- An integral scalar makes the scaled unary tail a sublattice of the
original projected tail. -/
theorem binaryScaledTailLattice_le (b : BONG V q L 2) (s : Kˣ)
    (hs : (s : K) ∈ IntegerRing K) :
    b.binaryScaledTailLattice s ≤
      L.projectedLattice q b.head b.head_isAnisotropic := by
  calc
    b.binaryScaledTailLattice s =
        Lattice.rescale s (Lattice.basisLattice b.tail.basis) := by
      rw [binaryScaledTailLattice, binaryScaledTailBasis,
        Lattice.rescale_basisLattice]
    _ ≤ Lattice.basisLattice b.tail.basis :=
      Lattice.rescale_le_self_of_mem_integerRing s _ hs
    _ = L.projectedLattice q b.head b.head_isAnisotropic :=
      b.tail.lattice_eq_basisLattice.symm

/-- The binary sublattice obtained by keeping the first norm generator and
scaling the projected unary tail by an integral scalar. -/
noncomputable def binaryIntegralSquareSubLattice
    (b : BONG V q L 2) (s : Kˣ) (hs : (s : K) ∈ IntegerRing K) :
    Lattice K V :=
  Lattice.projectionPreimage q L b.head b.head_isAnisotropic
    b.head_isNormGenerator.mem (b.binaryScaledTailLattice s)
    (b.binaryScaledTailLattice_le s hs)

/-- The BONG of the integral-square sublattice, with the same first vector
and the scaled unary BONG as its tail. -/
noncomputable def binaryIntegralSquareSubBONG
    (b : BONG V q L 2) (s : Kˣ) (hs : (s : K) ∈ IntegerRing K) :
    BONG V q (b.binaryIntegralSquareSubLattice s hs) 2 :=
  BONG.prependProjectionPreimage b.head_isNormGenerator
    (b.binaryScaledTailLattice s) (b.binaryScaledTailLattice_le s hs)
    (b.binaryScaledTailBONG s)

/-- The integral-square construction really produces a sublattice. -/
theorem binaryIntegralSquareSubLattice_le
    (b : BONG V q L 2) (s : Kˣ) (hs : (s : K) ∈ IntegerRing K) :
    b.binaryIntegralSquareSubLattice s hs ≤ L :=
  Lattice.projectionPreimage_le q L b.head b.head_isAnisotropic
    b.head_isNormGenerator.mem (b.binaryScaledTailLattice s)
    (b.binaryScaledTailLattice_le s hs)

@[simp]
theorem binaryIntegralSquareSubBONG_head
    (b : BONG V q L 2) (s : Kˣ) (hs : (s : K) ∈ IntegerRing K) :
    (b.binaryIntegralSquareSubBONG s hs).head = b.head := by
  rw [← ambientVector_zero_eq_head]
  exact ambientVector_prependProjectionPreimage_zero
    b.head_isNormGenerator (b.binaryScaledTailLattice s)
      (b.binaryScaledTailLattice_le s hs) (b.binaryScaledTailBONG s)

@[simp]
theorem binaryScaledTailBONG_value_zero
    (b : BONG V q L 2) (s : Kˣ) :
    (b.binaryScaledTailBONG s).value 0 =
      (s : K) ^ 2 * b.tail.value 0 := by
  rw [← quadratic_ambientVector,
    binaryScaledTailBONG_ambientVector_zero,
    binaryScaledTailBasis, Basis.smul_apply,
    Units.smul_def, QuadraticSpace.quadratic_smul]
  congr 1
  change
    (q.orthogonalSpace b.head b.head_isAnisotropic).quadratic
        (b.tail.ambientVector 0) = b.tail.value 0
  exact quadratic_ambientVector b.tail 0

@[simp]
theorem binaryIntegralSquareSubBONG_value_zero
    (b : BONG V q L 2) (s : Kˣ) (hs : (s : K) ∈ IntegerRing K) :
    (b.binaryIntegralSquareSubBONG s hs).value 0 = b.value 0 := by
  change q.quadratic (b.binaryIntegralSquareSubBONG s hs).head = _
  rw [binaryIntegralSquareSubBONG_head, ← b.value_zero_eq_quadratic_head]

@[simp]
theorem binaryIntegralSquareSubBONG_ambientVector_one
    (b : BONG V q L 2) (s : Kˣ) (hs : (s : K) ∈ IntegerRing K) :
    (b.binaryIntegralSquareSubBONG s hs).ambientVector 1 =
      (s : K) • b.ambientVector 1 := by
  calc
    (b.binaryIntegralSquareSubBONG s hs).ambientVector 1 =
        ((b.binaryScaledTailBONG s).ambientVector 0 : V) := by
      simpa [binaryIntegralSquareSubBONG,
        binaryIntegralSquareSubLattice] using
        ambientVector_prependProjectionPreimage_succ
          b.head_isNormGenerator (b.binaryScaledTailLattice s)
          (b.binaryScaledTailLattice_le s hs)
          (b.binaryScaledTailBONG s) 0
    _ = (s : K) • b.ambientVector 1 := by
      rw [binaryScaledTailBONG_ambientVector_zero,
        binaryScaledTailBasis, Basis.smul_apply, Units.smul_def]
      change (s : K) • (b.tail.ambientVector 0 : V) =
        (s : K) • b.ambientVector 1
      rw [coe_ambientVector_tail]
      congr 2

@[simp]
theorem binaryIntegralSquareSubBONG_value_one
    (b : BONG V q L 2) (s : Kˣ) (hs : (s : K) ∈ IntegerRing K) :
    (b.binaryIntegralSquareSubBONG s hs).value 1 =
      (s : K) ^ 2 * b.value 1 := by
  rw [← quadratic_ambientVector,
    binaryIntegralSquareSubBONG_ambientVector_one,
    QuadraticSpace.quadratic_smul, quadratic_ambientVector]

/-- Scaling the second BONG vector by `s` multiplies the binary parameter by
`s²`. -/
theorem binaryIntegralSquareSubBONG_binaryParameter
    (b : BONG V q L 2) (s : Kˣ) (hs : (s : K) ∈ IntegerRing K) :
    (b.binaryIntegralSquareSubBONG s hs).binaryParameter =
      b.binaryParameter * s ^ 2 := by
  apply Units.ext
  simp only [Units.val_mul]
  rw [coe_binaryParameter, coe_binaryParameter,
    binaryIntegralSquareSubBONG_value_zero,
    binaryIntegralSquareSubBONG_value_one]
  field_simp [b.value_ne_zero 0]
  simpa using (mul_comm ((s : K) ^ 2) (b.value 1))

/-- Beli 2003, Lemma 3.8: an integral-square parameter shift is realized by
a binary sublattice, so its integral spinor-norm image is contained in the
original image. -/
theorem spinorNormImage_binaryIntegralSquareSubLattice_subset
    (b : BONG V q L 2) (s : Kˣ) (hs : (s : K) ∈ IntegerRing K) :
    Lattice.spinorNormImage
        (q := q) (L := b.binaryIntegralSquareSubLattice s hs) ⊆
      Lattice.spinorNormImage (q := q) (L := L) := by
  apply Lattice.spinorNormImage_subset_of_binary_commonHead
    (b.binaryIntegralSquareSubBONG s hs) b
  · exact b.binaryIntegralSquareSubBONG_head s hs
  · exact b.binaryIntegralSquareSubLattice_le s hs

/-- Existential form of Beli 2003, Lemma 3.8, exposing the shifted parameter
and the induced spinor-norm inclusion. -/
theorem exists_binaryBONG_parameter_mul_integral_square
    (b : BONG V q L 2) (s : Kˣ) (hs : (s : K) ∈ IntegerRing K) :
    ∃ (M : Lattice K V) (c : BONG V q M 2),
      M ≤ L ∧ c.head = b.head ∧
        c.binaryParameter = b.binaryParameter * s ^ 2 ∧
        Lattice.spinorNormImage (q := q) (L := M) ⊆
          Lattice.spinorNormImage (q := q) (L := L) := by
  exact ⟨b.binaryIntegralSquareSubLattice s hs,
    b.binaryIntegralSquareSubBONG s hs,
    b.binaryIntegralSquareSubLattice_le s hs,
    b.binaryIntegralSquareSubBONG_head s hs,
    b.binaryIntegralSquareSubBONG_binaryParameter s hs,
    b.spinorNormImage_binaryIntegralSquareSubLattice_subset s hs⟩

end BONG

end Bong
