/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.BinaryDefectCriterion
import Bong.Bong.OrthogonalBasis

/-!
# Exact binary BONG models

The explicit Gram model has a canonical orthogonal second vector.  This file
uses that vector, rather than an arbitrary one-dimensional norm generator, to
obtain a BONG whose two values are exactly `1` and `a`.
-/

namespace Bong

open Dyadic
open Module

universe u

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]

namespace BONG

/-- The canonical second vector in the orthogonal complement of the first
standard vector of the binary model. -/
def binaryModelOrthogonalSecond (a : Kˣ) (c : K) :
    (QuadraticSpace.binaryModel a c).vectorOrthogonal
      QuadraticSpace.binaryModelFirst :=
  ⟨QuadraticSpace.binaryModelSecond -
      c • QuadraticSpace.binaryModelFirst,
    (QuadraticSpace.binaryModel a c).mem_vectorOrthogonal_iff
      QuadraticSpace.binaryModelFirst _ |>.2
        (QuadraticSpace.binaryModel_bilin_first_second_sub a c)⟩

@[simp]
theorem coe_binaryModelOrthogonalSecond (a : Kˣ) (c : K) :
    (binaryModelOrthogonalSecond a c : Fin 2 → K) =
      QuadraticSpace.binaryModelSecond -
        c • QuadraticSpace.binaryModelFirst :=
  rfl

theorem binaryModelOrthogonalSecond_ne_zero (a : Kˣ) (c : K) :
    binaryModelOrthogonalSecond a c ≠ 0 := by
  intro hzero
  have hcoe : QuadraticSpace.binaryModelSecond (K := K) -
      c • QuadraticSpace.binaryModelFirst (K := K) =
        (0 : Fin 2 → K) :=
    by
      change (binaryModelOrthogonalSecond a c : Fin 2 → K) = 0
      simpa using congrArg Subtype.val hzero
  have hvalue :=
    QuadraticSpace.binaryModel_quadratic_second_sub a c
  rw [hcoe] at hvalue
  have haZero : (a : K) = 0 := by simpa using hvalue.symm
  exact Units.ne_zero a haZero

/-- The canonical one-dimensional basis of the model orthogonal complement. -/
noncomputable def binaryModelOrthogonalBasis (a : Kˣ) (c : K) :
    Basis (Fin 1) K
      ((QuadraticSpace.binaryModel a c).vectorOrthogonal
        QuadraticSpace.binaryModelFirst) := by
  let q : QuadraticSpace K (Fin 2 → K) :=
    QuadraticSpace.binaryModel a c
  let x : Fin 2 → K := QuadraticSpace.binaryModelFirst
  let w : q.vectorOrthogonal x := binaryModelOrthogonalSecond a c
  have hli : LinearIndependent K (fun _ : Fin 1 => w) :=
    linearIndependent_unique_iff.mpr
      (binaryModelOrthogonalSecond_ne_zero a c)
  have hdim : Module.finrank K (q.vectorOrthogonal x) = 1 := by
    have h : Module.finrank K (q.vectorOrthogonal x) + 1 = 2 := by
      calc
        Module.finrank K (q.vectorOrthogonal x) + 1 =
            Module.finrank K (Fin 2 → K) :=
          q.finrank_vectorOrthogonal
            (binaryModelFirst_isAnisotropic a c)
        _ = 2 := by simp
    omega
  exact basisOfLinearIndependentOfCardEqFinrank'
    (fun _ : Fin 1 => w) hli (by simpa [q, x] using hdim.symm)

@[simp]
theorem binaryModelOrthogonalBasis_apply (a : Kˣ) (c : K)
    (i : Fin 1) :
    binaryModelOrthogonalBasis a c i =
      binaryModelOrthogonalSecond a c := by
  rw [binaryModelOrthogonalBasis]
  simp

@[simp]
theorem binaryModelOrthogonalSecond_quadratic (a : Kˣ) (c : K) :
    ((QuadraticSpace.binaryModel a c).orthogonalSpace
      QuadraticSpace.binaryModelFirst
      (binaryModelFirst_isAnisotropic a c)).quadratic
        (binaryModelOrthogonalSecond a c) = (a : K) := by
  exact QuadraticSpace.binaryModel_quadratic_second_sub a c

/-- Projection of the second standard vector is the canonical orthogonal
second vector. -/
theorem binaryModel_projection_second (a : Kˣ) (c : K) :
    (QuadraticSpace.binaryModel a c).projectionToOrthogonal
        QuadraticSpace.binaryModelFirst
        (binaryModelFirst_isAnisotropic a c)
        QuadraticSpace.binaryModelSecond =
      binaryModelOrthogonalSecond a c := by
  apply Subtype.ext
  rw [QuadraticSpace.projectionToOrthogonal_coe,
    QuadraticSpace.orthogonalProjection_apply]
  simp

/-- The projected standard model lattice is generated by the canonical
orthogonal second vector. -/
theorem binaryModel_projectedLattice :
    (binaryModelLattice (K := K)).projectedLattice
        (QuadraticSpace.binaryModel a c)
        QuadraticSpace.binaryModelFirst
        (binaryModelFirst_isAnisotropic a c) =
      Lattice.basisLattice (binaryModelOrthogonalBasis a c) := by
  apply Lattice.ext
  change
    (Submodule.span (IntegerRing K)
        (Set.range (binaryModelBasis (K := K)))).map
        (((QuadraticSpace.binaryModel a c).projectionToOrthogonal
          QuadraticSpace.binaryModelFirst
          (binaryModelFirst_isAnisotropic a c)).restrictScalars
            (IntegerRing K)) =
      Submodule.span (IntegerRing K)
        (Set.range (binaryModelOrthogonalBasis a c))
  rw [Submodule.map_span]
  apply le_antisymm
  · rw [Submodule.span_le]
    rintro _ ⟨_, ⟨i, rfl⟩, rfl⟩
    refine Fin.cases ?_ (fun j => ?_) i
    · change
        (QuadraticSpace.binaryModel a c).projectionToOrthogonal
            QuadraticSpace.binaryModelFirst
            (binaryModelFirst_isAnisotropic a c)
            (binaryModelBasis (K := K) 0) ∈ _
      rw [binaryModelBasis_zero]
      have hzero :
          (QuadraticSpace.binaryModel a c).projectionToOrthogonal
              QuadraticSpace.binaryModelFirst
              (binaryModelFirst_isAnisotropic a c)
              QuadraticSpace.binaryModelFirst = 0 := by
        apply Subtype.ext
        exact (QuadraticSpace.binaryModel a c).orthogonalProjection_self
          (binaryModelFirst_isAnisotropic a c)
      rw [hzero]
      exact Submodule.zero_mem _
    · have hj : j = 0 := Subsingleton.elim j 0
      subst j
      change
        (QuadraticSpace.binaryModel a c).projectionToOrthogonal
            QuadraticSpace.binaryModelFirst
            (binaryModelFirst_isAnisotropic a c)
            (binaryModelBasis (K := K) 1) ∈ _
      rw [binaryModelBasis_one, binaryModel_projection_second]
      exact Submodule.subset_span
        ⟨0, binaryModelOrthogonalBasis_apply a c 0⟩
  · rw [Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    have hi : i = 0 := Subsingleton.elim i 0
    subst i
    apply Submodule.subset_span
    refine ⟨QuadraticSpace.binaryModelSecond,
      ⟨1, binaryModelBasis_one⟩, ?_⟩
    change
      (QuadraticSpace.binaryModel a c).projectionToOrthogonal
          QuadraticSpace.binaryModelFirst
          (binaryModelFirst_isAnisotropic a c)
          QuadraticSpace.binaryModelSecond =
        binaryModelOrthogonalBasis a c 0
    rw [binaryModel_projection_second,
      binaryModelOrthogonalBasis_apply]

/-- The exact binary model BONG, with values `1` and `a`. -/
noncomputable def binaryExactModelBONG
    (a : Kˣ) (c : K)
    (htwo : (2 : K) * c ∈ IntegerRing K)
    (hdiag : c ^ 2 + (a : K) ∈ IntegerRing K) :
    BONG (Fin 2 → K) (QuadraticSpace.binaryModel a c)
      (binaryModelLattice (K := K)) 2 := by
  let q : QuadraticSpace K (Fin 2 → K) :=
    QuadraticSpace.binaryModel a c
  let x : Fin 2 → K := QuadraticSpace.binaryModelFirst
  let tailQ := q.orthogonalSpace x
    (binaryModelFirst_isAnisotropic a c)
  let tailBasis := binaryModelOrthogonalBasis a c
  have htailOrthogonal : tailQ.bilin.iIsOrtho tailBasis := by
    rw [LinearMap.BilinForm.iIsOrtho_def]
    intro i j hij
    exact (hij (Subsingleton.elim i j)).elim
  have htailNe : tailQ.quadratic (tailBasis 0) ≠ 0 := by
    rw [binaryModelOrthogonalBasis_apply,
      binaryModelOrthogonalSecond_quadratic]
    exact Units.ne_zero a
  let tailBONG := ofOrthogonalBasisFinOne tailQ tailBasis
    htailOrthogonal htailNe
  exact BONG.cons x
    (binaryModelFirst_isNormGenerator a c htwo hdiag)
    (binaryModelFirst_isAnisotropic a c)
    (tailBONG.castLattice
      (binaryModel_projectedLattice (a := a) (c := c)).symm)

@[simp]
theorem binaryExactModelBONG_ambientVector_zero
    (a : Kˣ) (c : K)
    (htwo : (2 : K) * c ∈ IntegerRing K)
    (hdiag : c ^ 2 + (a : K) ∈ IntegerRing K) :
    (binaryExactModelBONG a c htwo hdiag).ambientVector 0 =
      QuadraticSpace.binaryModelFirst := by
  rw [binaryExactModelBONG, ambientVector_cons_zero]

@[simp]
theorem binaryExactModelBONG_ambientVector_one
    (a : Kˣ) (c : K)
    (htwo : (2 : K) * c ∈ IntegerRing K)
    (hdiag : c ^ 2 + (a : K) ∈ IntegerRing K) :
    (binaryExactModelBONG a c htwo hdiag).ambientVector 1 =
      QuadraticSpace.binaryModelSecond -
        c • QuadraticSpace.binaryModelFirst := by
  change
    (binaryExactModelBONG a c htwo hdiag).ambientVector
        (Fin.succ 0) = _
  rw [binaryExactModelBONG, ambientVector_cons_succ,
    ambientVector_castLattice,
    ambientVector_ofOrthogonalBasisFinOne,
    binaryModelOrthogonalBasis_apply]
  rfl

@[simp]
theorem binaryExactModelBONG_value_zero
    (a : Kˣ) (c : K)
    (htwo : (2 : K) * c ∈ IntegerRing K)
    (hdiag : c ^ 2 + (a : K) ∈ IntegerRing K) :
    (binaryExactModelBONG a c htwo hdiag).value 0 = 1 := by
  rw [← quadratic_ambientVector,
    binaryExactModelBONG_ambientVector_zero]
  exact QuadraticSpace.binaryModel_quadratic_first a c

@[simp]
theorem binaryExactModelBONG_value_one
    (a : Kˣ) (c : K)
    (htwo : (2 : K) * c ∈ IntegerRing K)
    (hdiag : c ^ 2 + (a : K) ∈ IntegerRing K) :
    (binaryExactModelBONG a c htwo hdiag).value 1 = (a : K) := by
  rw [← quadratic_ambientVector,
    binaryExactModelBONG_ambientVector_one]
  exact QuadraticSpace.binaryModel_quadratic_second_sub a c

@[simp]
theorem binaryExactModelBONG_binaryParameter
    (a : Kˣ) (c : K)
    (htwo : (2 : K) * c ∈ IntegerRing K)
    (hdiag : c ^ 2 + (a : K) ∈ IntegerRing K) :
    (binaryExactModelBONG a c htwo hdiag).binaryParameter = a := by
  apply Units.ext
  rw [coe_binaryParameter, binaryExactModelBONG_value_zero,
    binaryExactModelBONG_value_one, div_one]

/-- Operational admissibility is exactly realization by an explicit BONG
whose scalar parameter is `a` itself, not merely its refined square class. -/
theorem isBinaryParameterAdmissible_iff_exists_exactModelBONG
    (a : Kˣ) :
    IsBinaryParameterAdmissible a ↔
      ∃ (c : K)
        (htwo : (2 : K) * c ∈ IntegerRing K)
        (hdiag : c ^ 2 + (a : K) ∈ IntegerRing K),
        (binaryExactModelBONG a c htwo hdiag).binaryParameter = a := by
  constructor
  · rintro ⟨c, htwo, hdiag⟩
    exact ⟨c, htwo, hdiag,
      binaryExactModelBONG_binaryParameter a c htwo hdiag⟩
  · rintro ⟨c, htwo, hdiag, _⟩
    exact ⟨c, htwo, hdiag⟩

/-- Constructive normalized form of Beli 2003, Lemma 3.6. -/
theorem IsBinaryParameterAdmissible.exists_exactModelBONG
    {a : Kˣ} (ha : IsBinaryParameterAdmissible a) :
    ∃ (c : K)
      (htwo : (2 : K) * c ∈ IntegerRing K)
      (hdiag : c ^ 2 + (a : K) ∈ IntegerRing K),
      (binaryExactModelBONG a c htwo hdiag).value 0 = 1 ∧
        (binaryExactModelBONG a c htwo hdiag).value 1 = (a : K) ∧
        (binaryExactModelBONG a c htwo hdiag).binaryParameter = a := by
  rcases ha with ⟨c, htwo, hdiag⟩
  exact ⟨c, htwo, hdiag, by simp⟩

end BONG

end Bong
