/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.BinaryModular
import Bong.Bong.BinaryDiagonal
import Bong.Lattice.ModularVolume
import Bong.Lattice.NormRescale

/-!
# Binary BONG invariants on modular lattices

For a binary BONG on an `a`-modular lattice, its relative order is twice the
difference between the modular scale order and its first value order.  This is
the numerical core of Beli (2003), Lemma 3.3(iii).
-/

namespace Bong

open Dyadic
open Module

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {q : QuadraticSpace K V} {L : Lattice K V}

namespace BONG

/-- On an `a`-modular binary lattice, `R(L) = 2 ord(a) - 2 R₁`. -/
theorem binaryOrderGap_eq_of_isModular (b : BONG V q L 2)
    (a : Kˣ) (hmodular : Lattice.IsModular q L a) :
    b.binaryOrderGap = 2 * ordUnit K a - 2 * b.order 0 := by
  have hvolume := hmodular.volumeOrder_eq
  rw [← b.length_eq_finrank] at hvolume
  rw [← b.binaryRelativeOrder_eq_orderGap,
    binaryRelativeOrder, hvolume]
  norm_num

/-- The relative order of a modular binary lattice is even. -/
theorem even_binaryOrderGap_of_isModular (b : BONG V q L 2)
    (a : Kˣ) (hmodular : Lattice.IsModular q L a) :
    Even b.binaryOrderGap := by
  refine ⟨ordUnit K a - b.order 0, ?_⟩
  rw [b.binaryOrderGap_eq_of_isModular a hmodular]
  ring

/-- Equivalently, twice the modular scale order is the sum of the two BONG
orders. -/
theorem two_mul_modularOrder_eq_order_add (b : BONG V q L 2)
    (a : Kˣ) (hmodular : Lattice.IsModular q L a) :
    2 * ordUnit K a = b.order 0 + b.order 1 := by
  have hgap := b.binaryOrderGap_eq_of_isModular a hmodular
  rw [binaryOrderGap] at hgap
  omega

/-- The second BONG order of an `a`-modular binary lattice is
`2 ord(a) - R₁`. -/
theorem order_one_eq_of_isModular (b : BONG V q L 2)
    (a : Kˣ) (hmodular : Lattice.IsModular q L a) :
    b.order 1 = 2 * ordUnit K a - b.order 0 := by
  have hsum := b.two_mul_modularOrder_eq_order_add a hmodular
  omega

/-- The normalized binary parameter has order `2 ord(a) - 2 R₁`. -/
theorem binaryParameterOrder_eq_of_isModular (b : BONG V q L 2)
    (a : Kˣ) (hmodular : Lattice.IsModular q L a) :
    b.binaryParameterOrder =
      2 * ordUnit K a - 2 * b.order 0 := by
  rw [b.binaryParameterOrder_eq_orderGap,
    b.binaryOrderGap_eq_of_isModular a hmodular]

/-- The two BONG orders of a modular binary lattice have the same parity. -/
theorem orders_modEq_two_of_isModular (b : BONG V q L 2)
    (a : Kˣ) (hmodular : Lattice.IsModular q L a) :
    b.order 0 ≡ b.order 1 [ZMOD 2] := by
  rw [Int.modEq_iff_dvd]
  simpa [binaryOrderGap] using
    (b.even_binaryOrderGap_of_isModular a hmodular).two_dvd

/-- Scaling the BONG head by the inverse modular parameter gives a norm
generator of the dual lattice. -/
theorem inverseModularParameter_smul_head_isNormGenerator_dual
    (b : BONG V q L 2) (a : Kˣ)
    (hmodular : Lattice.IsModular q L a) :
    Lattice.IsNormGenerator q (Lattice.dualLattice q L)
      ((a⁻¹ : Kˣ) • b.head) :=
  hmodular.normGenerator_dual b.head_isNormGenerator

/-- The dual norm generator supplied by modularity has order `-R₂`. -/
theorem ord_quadratic_inverseModularParameter_smul_head
    (b : BONG V q L 2) (a : Kˣ)
    (hmodular : Lattice.IsModular q L a) :
    ord K (q.quadratic (((a⁻¹ : Kˣ) : K) • b.head)) =
      ((-b.order 1 : Int) : WithTop Int) := by
  have hsum := b.two_mul_modularOrder_eq_order_add a hmodular
  rw [q.quadratic_smul, ord_mul, ord_pow,
    ← coe_ordUnit, ordUnit_inv,
    ← b.value_zero_eq_quadratic_head, ← b.coe_order]
  norm_cast
  simp only [nsmul_eq_mul]
  omega

/-- The norm ideal of the dual modular lattice is generated by the scaled
head whose order is `-R₂`. -/
theorem normIdeal_dualLattice_eq_principal_inverseModularParameter_smul_head
    (b : BONG V q L 2) (a : Kˣ)
    (hmodular : Lattice.IsModular q L a) :
    Lattice.normIdeal q (Lattice.dualLattice q L) =
      Lattice.principalIdeal (K := K)
        (q.quadratic (((a⁻¹ : Kˣ) : K) • b.head)) :=
  (b.inverseModularParameter_smul_head_isNormGenerator_dual
    a hmodular).normIdeal_eq

/-- In a modular binary lattice, the first BONG value has order at least the
modular parameter.  This is the ideal inclusion `nL ⊆ sL` expressed
without choosing a separate generator of the scale ideal. -/
theorem modularOrder_le_order_zero (b : BONG V q L 2)
    (a : Kˣ) (hmodular : Lattice.IsModular q L a) :
    ordUnit K a ≤ b.order 0 := by
  have hdualMem :=
    (b.inverseModularParameter_smul_head_isNormGenerator_dual
      a hmodular).mem
  rw [Lattice.mem_dualLattice_iff] at hdualMem
  have hpair := hdualMem b.head b.head_isNormGenerator.mem
  have hintegral :
      (((a⁻¹ : Kˣ) : K) * q.quadratic b.head) ∈
        IntegerRing K := by
    simpa only [Units.smul_def, LinearMap.BilinForm.smul_left,
      QuadraticSpace.quadratic, smul_eq_mul] using hpair
  have hord := (mem_integerRing_iff K).1 hintegral
  change (0 : WithTop Int) ≤
      ord K (((a⁻¹ : Kˣ) : K) * q.quadratic b.head) at hord
  rw [ord_mul, ← coe_ordUnit, ordUnit_inv,
    ← b.value_zero_eq_quadratic_head, ← b.coe_order] at hord
  have hord' : 0 ≤ -ordUnit K a + b.order 0 :=
    WithTop.coe_le_coe.mp (by simpa using hord)
  omega

/-- Every modular binary BONG has nonpositive relative order. -/
theorem binaryOrderGap_nonpos_of_isModular (b : BONG V q L 2)
    (a : Kˣ) (hmodular : Lattice.IsModular q L a) :
    b.binaryOrderGap ≤ 0 := by
  rw [b.binaryOrderGap_eq_of_isModular a hmodular]
  have hle := b.modularOrder_le_order_zero a hmodular
  omega

/-- Equivalently, the first BONG order of a modular binary lattice is at
least the second. -/
theorem order_one_le_order_zero_of_isModular (b : BONG V q L 2)
    (a : Kˣ) (hmodular : Lattice.IsModular q L a) :
    b.order 1 ≤ b.order 0 := by
  have hgap := b.binaryOrderGap_nonpos_of_isModular a hmodular
  rw [binaryOrderGap] at hgap
  omega

/-- For a binary BONG, modularity at its first value forces zero order gap. -/
theorem binaryOrderGap_eq_zero_of_isModular_value_zero
    (b : BONG V q L 2)
    (hmodular : Lattice.IsModular q L (b.valueUnit 0)) :
    b.binaryOrderGap = 0 := by
  rw [b.binaryOrderGap_eq_of_isModular (b.valueUnit 0) hmodular,
    ← b.order_eq_ordUnit]
  ring

/-- In the nonnegative (hence diagonal) branch, modularity at the first value
is equivalent to zero relative order. -/
theorem isModular_value_zero_iff_binaryOrderGap_eq_zero_of_nonneg
    (b : BONG V q L 2) (hgap : 0 ≤ b.binaryOrderGap) :
    Lattice.IsModular q L (b.valueUnit 0) ↔
      b.binaryOrderGap = 0 := by
  constructor
  · exact b.binaryOrderGap_eq_zero_of_isModular_value_zero
  · intro hzero
    have hlattice := b.lattice_eq_basisLattice_of_binaryOrderGap_nonneg hgap
    have hq0 : q.quadratic (b.basis 0) = b.value 0 :=
      b.quadratic_ambientVector 0
    have hq1 : q.quadratic (b.basis 1) = b.value 1 :=
      b.quadratic_ambientVector 1
    have hne0 : q.quadratic (b.basis 0) ≠ 0 := by
      rw [hq0]
      exact b.value_ne_zero 0
    have hne1 : q.quadratic (b.basis 1) ≠ 0 := by
      rw [hq1]
      exact b.value_ne_zero 1
    have horder : ord K (q.quadratic (b.basis 0)) =
        ord K (q.quadratic (b.basis 1)) := by
      rw [hq0, hq1]
      rw [← b.coe_order, ← b.coe_order]
      apply congrArg ((↑) : Int → WithTop Int)
      rw [binaryOrderGap] at hzero
      omega
    have hmodBasis : Lattice.IsModular q
        (Lattice.basisLattice b.basis) (b.valueUnit 0) := by
      have hraw := Lattice.isModular_basisLattice_fin_two_of_ord_eq
        q b.basis b.ambientVector_iIsOrtho hne0 hne1 horder
      have hunit : Units.mk0 (q.quadratic (b.basis 0)) hne0 =
          b.valueUnit 0 := by
        apply Units.ext
        rw [coe_valueUnit]
        exact hq0
      rw [hunit] at hraw
      exact hraw
    exact Eq.mpr
      (congrArg (fun M => Lattice.IsModular q M (b.valueUnit 0)) hlattice)
      hmodBasis

end BONG

end Bong
