/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.BinaryPrimitiveCoordinates
import Bong.Bong.BinarySpinorGroupFormula
import Bong.Dyadic.QuadraticDefectHensel

/-!
# Binary spinor norms above the `4e` boundary

This file proves the range called Proposition 2.1 in Xu (1993).  For the
diagonal binary lattice `X² + aY²`, when `ord(a) > 4e`, every primitive
integral reflection has value in one of the two square classes `1` and `a`,
and both classes occur.  Thus its proper integral spinor image is the cyclic
subgroup generated by the class of `a`.
-/

namespace Bong

open Dyadic

universe u v

namespace Dyadic

/-- Every field square class has exponent two. -/
theorem squareClass_sq_eq_one
    {K : Type u} [Field K] (a : Kˣ) :
    squareClass K a ^ 2 = 1 := by
  unfold squareClass
  rw [← map_pow]
  apply (QuotientGroup.eq_one_iff (a ^ 2)).2
  exact (Subgroup.mem_square).2 ⟨a, pow_two a⟩

/-- A cyclic subgroup generated by an element of order at most two consists
of the identity and the generator. -/
theorem mem_zpowers_iff_eq_one_or_eq_of_sq_eq_one
    {G : Type v} [Group G] {g x : G} (hg : g ^ 2 = 1) :
    x ∈ Subgroup.zpowers g ↔ x = 1 ∨ x = g := by
  let H : Subgroup G := {
    carrier := {x | x = 1 ∨ x = g}
    one_mem' := Or.inl rfl
    mul_mem' := by
      rintro a b ha hb
      rcases ha with ha | ha <;> rcases hb with hb | hb
      · subst a; subst b; exact Or.inl (one_mul 1)
      · subst a; subst b; exact Or.inr (one_mul g)
      · subst a; subst b; exact Or.inr (mul_one g)
      · subst a; subst b; exact Or.inl (by simpa [pow_two] using hg)
    inv_mem' := by
      rintro a ha
      rcases ha with ha | ha
      · subst a; exact Or.inl inv_one
      · subst a; exact Or.inr (inv_eq_of_mul_eq_one_right
          (by simpa [pow_two] using hg)) }
  have hH : Subgroup.zpowers g = H := by
    apply le_antisymm
    · rw [Subgroup.zpowers_le]
      exact Or.inr rfl
    · intro a ha
      change a = 1 ∨ a = g at ha
      rcases ha with ha | ha
      · simpa [ha] using (Subgroup.zpowers g).one_mem
      · simpa [ha] using Subgroup.mem_zpowers g
  rw [hH]
  rfl

/-- Membership in the cyclic square-class subgroup has the expected
two-element description. -/
theorem mem_cyclicSquareClassSubgroup_iff
    {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
    [TopologicalSpace K] [DyadicContext K]
    (a : Kˣ) (A : SquareClass K) :
    A ∈ cyclicSquareClassSubgroup K a ↔
      A = 1 ∨ A = squareClass K a := by
  exact mem_zpowers_iff_eq_one_or_eq_of_sq_eq_one
    (squareClass_sq_eq_one a)

/-- A square unit represents the identity square class. -/
theorem squareClass_eq_one_of_isSquare
    {K : Type u} [Field K] (a : Kˣ) (ha : IsSquare a) :
    squareClass K a = 1 := by
  apply (QuotientGroup.eq_one_iff a).2
  exact ha

/-- If `b / a` is a square, then `a` and `b` represent the same square
class. -/
theorem squareClass_eq_of_div_isSquare
    {K : Type u} [Field K] (a b : Kˣ)
    (h : IsSquare (b / a)) :
    squareClass K b = squareClass K a := by
  change QuotientGroup.mk' (Subgroup.square Kˣ) b =
    QuotientGroup.mk' (Subgroup.square Kˣ) a
  rw [QuotientGroup.mk'_eq_mk']
  have hinv : IsSquare (a / b) := by
    simpa [div_eq_mul_inv, mul_comm] using h.inv
  rcases hinv with ⟨s, hs⟩
  refine ⟨s ^ 2, ?_, ?_⟩
  · exact (Subgroup.mem_square).2 ⟨s, pow_two s⟩
  · rw [pow_two, ← hs]
    simp [div_eq_mul_inv, mul_comm]

end Dyadic

namespace BONG

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]

/-- In the diagonal binary model the value is `x² + ay²`. -/
theorem binaryModel_zero_quadratic_apply (a : Kˣ)
    (z : Fin 2 → K) :
    (QuadraticSpace.binaryModel a 0).quadratic z =
      z 0 ^ 2 + (a : K) * z 1 ^ 2 := by
  simp [QuadraticSpace.binaryModel_quadratic_apply]

/-- The order of an integral nonzero coordinate is nonnegative. -/
private theorem coordinate_ordUnit_nonneg
    {x : K} (hx : x ∈ IntegerRing K) (hx0 : x ≠ 0) :
    0 ≤ ordUnit K (Units.mk0 x hx0) :=
  Lattice.ordUnit_nonneg_of_mem_integerRing (Units.mk0 x hx0) hx

/-- If the first coordinate has order at most `e`, normalization by its
square is a principal unit deeper than `2e`. -/
private theorem squareClass_diagonalValue_eq_one_of_first_order_le_e
    (a : Kˣ)
    (hR : 4 * (ramificationIndex K : Int) < ordUnit K a)
    {x y : K} (hx0 : x ≠ 0)
    (hxOrder : ordUnit K (Units.mk0 x hx0) ≤
      (ramificationIndex K : Int))
    (hyIntegral : y ∈ IntegerRing K)
    (hq0 : x ^ 2 + (a : K) * y ^ 2 ≠ 0) :
    squareClass K (Units.mk0 (x ^ 2 + (a : K) * y ^ 2) hq0) = 1 := by
  let xu : Kˣ := Units.mk0 x hx0
  let qU : Kˣ := Units.mk0 (x ^ 2 + (a : K) * y ^ 2) hq0
  have hxOrder' : ordUnit K xu ≤ (ramificationIndex K : Int) := by
    simpa [xu] using hxOrder
  by_cases hy0 : y = 0
  · have hqU : qU = xu ^ 2 := by
      apply Units.ext
      simp [qU, xu, hy0]
    apply squareClass_eq_one_of_isSquare qU
    rw [hqU]
    exact ⟨xu, pow_two xu⟩
  let yu : Kˣ := Units.mk0 y hy0
  have hyOrder : 0 ≤ ordUnit K yu :=
    coordinate_ordUnit_nonneg hyIntegral hy0
  let uK : K := 1 + (a : K) * (y / x) ^ 2
  have hfactor :
      x ^ 2 + (a : K) * y ^ 2 = x ^ 2 * uK := by
    dsimp [uK]
    field_simp [hx0]
  have hu0 : uK ≠ 0 := by
    intro hu
    apply hq0
    rw [hfactor, hu, mul_zero]
  let u : Kˣ := Units.mk0 uK hu0
  let error : Kˣ := a * (yu / xu) ^ 2
  have herrorOrder :
      ordUnit K error =
        ordUnit K a +
          2 * ordUnit K yu - 2 * ordUnit K xu := by
    simp [error, div_eq_mul_inv]
    ring
  have huSub : (u : K) - 1 = (error : K) := by
    simp only [u, uK, error, xu, yu, Units.val_mk0,
      Units.val_mul, Units.val_pow_eq_pow_val,
      Units.val_div_eq_div_val]
    ring
  have hdeep :
      (((2 * ramificationIndex K : ℕ) : ℤ) : WithTop ℤ) <
        ord K ((u : K) - 1) := by
    have hdeepInt :
        2 * (ramificationIndex K : Int) <
          ordUnit K a +
            2 * ordUnit K yu - 2 * ordUnit K xu := by
      omega
    rw [huSub, ← coe_ordUnit, herrorOrder]
    exact_mod_cast hdeepInt
  have huSquare : IsSquare u :=
    isSquare_of_ord_sub_one_gt_two_mul_e K u hdeep
  have hqU : qU = xu ^ 2 * u := by
    apply Units.ext
    simpa only [qU, xu, u, Units.val_mk0,
      Units.val_mul, Units.val_pow_eq_pow_val] using hfactor
  apply squareClass_eq_one_of_isSquare qU
  rw [hqU]
  exact (show IsSquare (xu ^ 2) from ⟨xu, pow_two xu⟩).mul huSquare

/-- If the second coordinate is a unit and the first coordinate has order at
least `R-e`, normalization by `a` and the second-coordinate square is a
principal unit deeper than `2e`. -/
private theorem squareClass_diagonalValue_eq_parameter_of_second_unit
    (a : Kˣ)
    (hR : 4 * (ramificationIndex K : Int) < ordUnit K a)
    {x y : K} (hx0 : x ≠ 0) (hy0 : y ≠ 0)
    (hyUnit : IsValuationUnit K y)
    (hxOrder : ordUnit K a - (ramificationIndex K : Int) ≤
      ordUnit K (Units.mk0 x hx0))
    (hq0 : x ^ 2 + (a : K) * y ^ 2 ≠ 0) :
    squareClass K (Units.mk0 (x ^ 2 + (a : K) * y ^ 2) hq0) =
      squareClass K a := by
  let xu : Kˣ := Units.mk0 x hx0
  let yu : Kˣ := Units.mk0 y hy0
  have hxOrder' : ordUnit K a - (ramificationIndex K : Int) ≤
      ordUnit K xu := by
    simpa [xu] using hxOrder
  have hyOrder : ordUnit K yu = 0 :=
    (isValuationUnit_iff_ordUnit_eq_zero K yu).1 (by simpa [yu] using hyUnit)
  let qU : Kˣ := Units.mk0 (x ^ 2 + (a : K) * y ^ 2) hq0
  let uK : K := 1 + (a : K)⁻¹ * (x / y) ^ 2
  have hfactor :
      x ^ 2 + (a : K) * y ^ 2 =
        (a : K) * y ^ 2 * uK := by
    dsimp [uK]
    field_simp [hy0, Units.ne_zero a]
    ring
  have hu0 : uK ≠ 0 := by
    intro hu
    apply hq0
    rw [hfactor, hu, mul_zero]
  let u : Kˣ := Units.mk0 uK hu0
  let error : Kˣ := a⁻¹ * (xu / yu) ^ 2
  have herrorOrder :
      ordUnit K error =
        -ordUnit K a +
          2 * ordUnit K xu - 2 * ordUnit K yu := by
    simp [error, div_eq_mul_inv]
    ring
  have huSub : (u : K) - 1 = (error : K) := by
    simp only [u, uK, error, xu, yu, Units.val_mk0,
      Units.val_inv_eq_inv_val, Units.val_mul,
      Units.val_pow_eq_pow_val, Units.val_div_eq_div_val]
    ring
  have hdeep :
      (((2 * ramificationIndex K : ℕ) : ℤ) : WithTop ℤ) <
        ord K ((u : K) - 1) := by
    have hdeepInt :
        2 * (ramificationIndex K : Int) <
          -ordUnit K a +
            2 * ordUnit K xu - 2 * ordUnit K yu := by
      omega
    rw [huSub, ← coe_ordUnit, herrorOrder, hyOrder]
    rw [hyOrder] at hdeepInt
    exact_mod_cast hdeepInt
  have huSquare : IsSquare u :=
    isSquare_of_ord_sub_one_gt_two_mul_e K u hdeep
  have hqU : qU / a = yu ^ 2 * u := by
    apply Units.ext
    have hfactor' := hfactor
    simp only [qU, xu, yu, u, Units.val_div_eq_div_val,
      Units.val_mk0, Units.val_mul, Units.val_pow_eq_pow_val]
    rw [hfactor']
    field_simp [Units.ne_zero a]
  apply squareClass_eq_of_div_isSquare a qU
  rw [hqU]
  exact (show IsSquare (yu ^ 2) from ⟨yu, pow_two yu⟩).mul huSquare

/-- The square class of a primitive integral-reflection value in
`X² + aY²`, above the `4e` boundary, is either `1` or `a`. -/
theorem squareClass_binaryDiagonal_of_primitive_integral_of_four_e_lt
    (a : Kˣ)
    (hR : 4 * (ramificationIndex K : Int) < ordUnit K a)
    {z : Fin 2 → K}
    (hz : (QuadraticSpace.binaryModel a 0).IsAnisotropic z)
    (hzMem : z ∈ binaryModelLattice (K := K))
    (hzPrimitive : z ∉ Lattice.rescale (uniformizerUnit K)
      (binaryModelLattice (K := K)))
    (hzIntegral : Lattice.IsIntegralReflection
      (q := QuadraticSpace.binaryModel a 0)
      (L := binaryModelLattice (K := K)) hz) :
    squareClass K (Units.mk0
        ((QuadraticSpace.binaryModel a 0).quadratic z) hz) = 1 ∨
    squareClass K (Units.mk0
        ((QuadraticSpace.binaryModel a 0).quadratic z) hz) =
        squareClass K a := by
  have hzCoords := (mem_binaryModelLattice_iff z).1 hzMem
  have hprimitive :=
    (primitive_binaryModelLattice_iff_coordinate_unit z hzMem).1
      hzPrimitive
  have hcoefficients :=
    (isIntegralReflection_binaryDiagonal_iff_of_primitive
      a hz hzMem hzPrimitive).1 hzIntegral
  have hqFormula := binaryModel_zero_quadratic_apply a z
  have hq0 : z 0 ^ 2 + (a : K) * z 1 ^ 2 ≠ 0 := by
    rw [← hqFormula]
    exact hz
  rcases hprimitive with hxUnit | hyUnit
  · have hx0 : z 0 ≠ 0 := by
      intro hx
      rw [hx, IsValuationUnit, ord_zero] at hxUnit
      exact WithTop.top_ne_zero hxUnit
    have hxOrder : ordUnit K (Units.mk0 (z 0) hx0) = 0 :=
      (isValuationUnit_iff_ordUnit_eq_zero K
        (Units.mk0 (z 0) hx0)).1 (by simpa using hxUnit)
    left
    simpa only [hqFormula] using
      squareClass_diagonalValue_eq_one_of_first_order_le_e
        a hR hx0 (by rw [hxOrder]; positivity) (hzCoords 1) hq0
  · have hy0 : z 1 ≠ 0 := by
      intro hy
      rw [hy, IsValuationUnit, ord_zero] at hyUnit
      exact WithTop.top_ne_zero hyUnit
    by_cases hx0 : z 0 = 0
    · right
      let yu : Kˣ := Units.mk0 (z 1) hy0
      have hunit :
          Units.mk0
              ((QuadraticSpace.binaryModel a 0).quadratic z) hz =
            a * yu ^ 2 := by
        apply Units.ext
        change (QuadraticSpace.binaryModel a 0).quadratic z =
          (a : K) * (yu : K) ^ 2
        rw [hqFormula]
        simp [hx0, yu]
      rw [hunit]
      exact squareClass_mul_square K a yu
    let xu : Kˣ := Units.mk0 (z 0) hx0
    let yu : Kˣ := Units.mk0 (z 1) hy0
    have hyOrder : ordUnit K yu = 0 :=
      (isValuationUnit_iff_ordUnit_eq_zero K yu).1
        (by simpa [yu] using hyUnit)
    have hxNonneg : 0 ≤ ordUnit K xu :=
      coordinate_ordUnit_nonneg (hzCoords 0) hx0
    by_cases hxSmall : ordUnit K xu ≤ (ramificationIndex K : Int)
    · left
      simpa only [hqFormula] using
        squareClass_diagonalValue_eq_one_of_first_order_le_e
          a hR hx0 (by simpa [xu] using hxSmall) (hzCoords 1) hq0
    · have hxLarge : (ramificationIndex K : Int) < ordUnit K xu :=
        lt_of_not_ge hxSmall
      let qU : Kˣ := Units.mk0
        (z 0 ^ 2 + (a : K) * z 1 ^ 2) hq0
      have hxOrdTop : ord K (z 0) =
          (ordUnit K xu : WithTop Int) := by
        simpa [xu] using (coe_ordUnit K xu).symm
      have hqOrdTop : ord K (z 0 ^ 2 + (a : K) * z 1 ^ 2) =
          (ordUnit K qU : WithTop Int) := by
        simpa [qU] using (coe_ordUnit K qU).symm
      let twoU : Kˣ := Units.mk0 (2 : K) (by norm_num)
      let coefficient : Kˣ := twoU * xu * qU⁻¹
      have hcoefficientMem : (coefficient : K) ∈ IntegerRing K := by
        have hfirst := hcoefficients.1
        rw [hqFormula] at hfirst
        simpa only [coefficient, twoU, xu, qU,
          Units.val_mul, Units.val_mk0, Units.val_inv_eq_inv_val,
          div_eq_mul_inv, mul_assoc] using hfirst
      have hcoefficientNonneg : 0 ≤ ordUnit K coefficient :=
        Lattice.ordUnit_nonneg_of_mem_integerRing coefficient
          hcoefficientMem
      have htwoOrder :
          ordUnit K twoU = (ramificationIndex K : Int) := by
        apply WithTop.coe_injective
        rw [coe_ordUnit, ramificationIndex_spec]
        rfl
      have hcoefficientOrder :
          ordUnit K coefficient =
            (ramificationIndex K : Int) + ordUnit K xu -
              ordUnit K qU := by
        simp only [coefficient, ordUnit_mul, ordUnit_inv, htwoOrder]
        omega
      have hqUpper :
          ordUnit K qU ≤
            (ramificationIndex K : Int) + ordUnit K xu := by
        rw [hcoefficientOrder] at hcoefficientNonneg
        omega
      have hxHigh :
          ordUnit K a - (ramificationIndex K : Int) ≤
            ordUnit K xu := by
        by_contra hnot
        have hxBelow : ordUnit K xu <
            ordUnit K a - (ramificationIndex K : Int) :=
          lt_of_not_ge hnot
        rcases lt_trichotomy (2 * ordUnit K xu) (ordUnit K a) with
          hlt | heq | hgt
        · have hterms :
              ord K (z 0 ^ 2) <
                ord K ((a : K) * z 1 ^ 2) := by
            calc
              ord K (z 0 ^ 2) =
                  ((2 * ordUnit K xu : Int) : WithTop Int) := by
                rw [ord_pow, hxOrdTop]
                norm_cast
              _ < (ordUnit K a : WithTop Int) := by
                exact_mod_cast hlt
              _ = ord K ((a : K) * z 1 ^ 2) := by
                rw [ord_mul, ord_pow, hyUnit, ← coe_ordUnit K a]
                simp
          have hsum := (ord K).map_add_eq_of_lt_left hterms
          have hqOrder : ordUnit K qU = 2 * ordUnit K xu := by
            apply WithTop.coe_injective
            rw [← hqOrdTop, hsum, ord_pow, hxOrdTop]
            norm_cast
          rw [hqOrder] at hqUpper
          omega
        · have hminimum :=
              min_ord_le_ord_add K (z 0 ^ 2)
                ((a : K) * z 1 ^ 2)
          have hqLower : ordUnit K a ≤ ordUnit K qU := by
            apply WithTop.coe_le_coe.mp
            calc
              (ordUnit K a : WithTop Int) =
                  min (ord K (z 0 ^ 2))
                    (ord K ((a : K) * z 1 ^ 2)) := by
                rw [ord_pow, ord_mul, ord_pow, hyUnit,
                  hxOrdTop, ← coe_ordUnit K a]
                norm_cast
                simp [two_nsmul, heq]
              _ ≤ ord K (z 0 ^ 2 + (a : K) * z 1 ^ 2) := hminimum
              _ = (ordUnit K qU : WithTop Int) := hqOrdTop
          omega
        · have hterms :
              ord K ((a : K) * z 1 ^ 2) <
                ord K (z 0 ^ 2) := by
            calc
              ord K ((a : K) * z 1 ^ 2) =
                  (ordUnit K a : WithTop Int) := by
                rw [ord_mul, ord_pow, hyUnit, ← coe_ordUnit K a]
                simp
              _ < ((2 * ordUnit K xu : Int) : WithTop Int) := by
                exact_mod_cast hgt
              _ = ord K (z 0 ^ 2) := by
                rw [ord_pow, hxOrdTop]
                norm_cast
          have hsum := (ord K).map_add_eq_of_lt_right hterms
          have hqOrder : ordUnit K qU = ordUnit K a := by
            apply WithTop.coe_injective
            rw [← hqOrdTop, hsum, ord_mul, ord_pow, hyUnit,
              ← coe_ordUnit K a]
            simp
          rw [hqOrder] at hqUpper
          omega
      right
      simpa only [hqFormula] using
        squareClass_diagonalValue_eq_parameter_of_second_unit
          a hR hx0 hy0 hyUnit (by simpa [xu] using hxHigh) hq0

/-- Xu (1993), Proposition 2.1: above `4e`, the proper integral spinor image
of the diagonal binary lattice is generated by the determinant parameter. -/
theorem spinorNormImage_binaryDiagonal_eq_cyclic_of_four_e_lt
    (a : Kˣ)
    (hR : 4 * (ramificationIndex K : Int) < ordUnit K a) :
    Lattice.spinorNormImage
        (q := QuadraticSpace.binaryModel a 0)
        (L := binaryModelLattice (K := K)) =
      (cyclicSquareClassSubgroup K a : Set (SquareClass K)) := by
  have heNonneg : 0 ≤ (ramificationIndex K : Int) := by positivity
  have haOrderNonneg : 0 ≤ ordUnit K a := by omega
  have haIntegral : (a : K) ∈ IntegerRing K := by
    apply (mem_integerRing_iff K).2
    change (0 : WithTop Int) ≤ ord K (a : K)
    rw [← coe_ordUnit]
    exact_mod_cast haOrderNonneg
  have htwo : (2 : K) * 0 ∈ IntegerRing K := by simp
  have hdiag : (0 : K) ^ 2 + (a : K) ∈ IntegerRing K := by
    simpa using haIntegral
  change
    (Lattice.spinorNormImageSubgroup
        (q := QuadraticSpace.binaryModel a 0)
        (L := binaryModelLattice (K := K)) : Set (SquareClass K)) =
      (cyclicSquareClassSubgroup K a : Set (SquareClass K))
  ext A
  constructor
  · intro hA
    change A ∈ Lattice.spinorNormImage
      (q := QuadraticSpace.binaryModel a 0)
      (L := binaryModelLattice (K := K)) at hA
    rw [spinorNormImage_binaryModel_eq_primitiveReflectionClassSet
      a 0 htwo hdiag] at hA
    rcases hA with ⟨z, hz, hzMem, hzPrimitive,
      hfirst, hsecond, hclass⟩
    have hzIntegral : Lattice.IsIntegralReflection
        (q := QuadraticSpace.binaryModel a 0)
        (L := binaryModelLattice (K := K)) hz :=
      (isIntegralReflection_binaryModel_iff_of_primitive
        a 0 hz hzMem hzPrimitive).2 ⟨hfirst, hsecond⟩
    have hor :=
      squareClass_binaryDiagonal_of_primitive_integral_of_four_e_lt
        a hR hz hzMem hzPrimitive hzIntegral
    apply (mem_cyclicSquareClassSubgroup_iff a A).2
    rcases hor with hone | ha
    · exact Or.inl (hclass.symm.trans hone)
    · exact Or.inr (hclass.symm.trans ha)
  · intro hA
    rcases (mem_cyclicSquareClassSubgroup_iff a A).1 hA with
      rfl | rfl
    · exact (Lattice.spinorNormImageSubgroup
        (q := QuadraticSpace.binaryModel a 0)
        (L := binaryModelLattice (K := K))).one_mem
    · change squareClass K a ∈ Lattice.spinorNormImage
        (q := QuadraticSpace.binaryModel a 0)
        (L := binaryModelLattice (K := K))
      rw [spinorNormImage_binaryModel_eq_primitiveReflectionClassSet
        a 0 htwo hdiag]
      let e₁ : Fin 2 → K := QuadraticSpace.binaryModelSecond
      have he₁ :
          (QuadraticSpace.binaryModel a 0).IsAnisotropic e₁ := by
        simp [e₁, QuadraticSpace.IsAnisotropic]
      have he₁Mem : e₁ ∈ binaryModelLattice (K := K) := by
        exact binaryModelSecond_mem a 0
      have he₁Primitive :
          e₁ ∉ Lattice.rescale (uniformizerUnit K)
            (binaryModelLattice (K := K)) := by
        apply (primitive_binaryModelLattice_iff_coordinate_unit
          e₁ he₁Mem).2
        right
        simp [e₁, QuadraticSpace.binaryModelSecond,
          IsValuationUnit]
      have htwoIntegral : (2 : K) ∈ IntegerRing K := by
        apply (mem_integerRing_iff K).2
        exact (ord_two_pos K).le
      have he₁Zero : e₁ 0 = 0 := by
        simp [e₁, QuadraticSpace.binaryModelSecond]
      have he₁One : e₁ 1 = 1 := by
        simp [e₁, QuadraticSpace.binaryModelSecond]
      have hvalue :
          (QuadraticSpace.binaryModel a 0).quadratic e₁ = (a : K) := by
        simp [e₁]
      refine ⟨e₁, he₁, he₁Mem, he₁Primitive, ?_, ?_, ?_⟩
      · rw [he₁Zero, he₁One, hvalue]
        simp
      · rw [he₁Zero, he₁One, hvalue]
        simpa [Units.ne_zero a] using htwoIntegral
      · have hunit : Units.mk0
              ((QuadraticSpace.binaryModel a 0).quadratic e₁) he₁ = a := by
          apply Units.ext
          simpa only [Units.val_mk0] using hvalue
        rw [hunit]

/-- The same high-order formula for an arbitrary binary BONG. -/
theorem spinorNormImage_eq_cyclic_of_four_e_lt
    {V : Type v} [AddCommGroup V] [Module K V]
    {q : QuadraticSpace K V} {L : Lattice K V}
    (b : BONG V q L 2)
    (hR : 4 * (ramificationIndex K : Int) < b.binaryOrderGap) :
    Lattice.spinorNormImage (q := q) (L := L) =
      (cyclicSquareClassSubgroup K b.binaryParameter :
        Set (SquareClass K)) := by
  have hnonneg : 0 ≤ b.binaryOrderGap := by
    have heNonneg : 0 ≤ (ramificationIndex K : Int) := by positivity
    omega
  rw [b.spinorNormImage_eq_diagonal_of_binaryOrderGap_nonneg hnonneg]
  apply spinorNormImage_binaryDiagonal_eq_cyclic_of_four_e_lt
  change 4 * (ramificationIndex K : Int) < b.binaryParameterOrder
  rwa [b.binaryParameterOrder_eq_orderGap]

/-- Proposition 2.1 supplies exactly the first branch of Beli's
representative-valued binary spinor formula. -/
theorem spinorNormImage_eq_beliSpinorGroupRepresentative_of_four_e_lt
    {V : Type v} [AddCommGroup V] [Module K V]
    {q : QuadraticSpace K V} {L : Lattice K V}
    (b : BONG V q L 2)
    (hR : 4 * (ramificationIndex K : Int) < b.binaryOrderGap) :
    Lattice.spinorNormImage (q := q) (L := L) =
      (beliSpinorGroupRepresentative K b.binaryParameter :
        Set (SquareClass K)) := by
  have hparameterOrder :
      4 * (ramificationIndex K : Int) <
        ordUnit K b.binaryParameter := by
    change 4 * (ramificationIndex K : Int) < b.binaryParameterOrder
    rwa [b.binaryParameterOrder_eq_orderGap]
  have hquarter : unitSquareClass K b.binaryParameter ≠
      unitSquareClass K (negativeQuarterUnit K) := by
    intro hclass
    have horder := ordUnit_eq_of_unitSquareClass_eq (K := K) hclass
    rw [ordUnit_negativeQuarterUnit] at horder
    have heNonneg : 0 ≤ (ramificationIndex K : Int) := by positivity
    omega
  rw [b.spinorNormImage_eq_cyclic_of_four_e_lt hR]
  symm
  exact congrArg (fun H : Subgroup (SquareClass K) =>
    (H : Set (SquareClass K)))
      (beliSpinorGroupRepresentative_caseI K b.binaryParameter
        b.binaryParameter_isBinaryParameterAdmissible hquarter
        hparameterOrder)

end BONG

end Bong
