/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.BinaryStrictModular
import Bong.Lattice.NormGeneratorValues

/-!
# Quadratic values in the BONG-adapted integral basis

This file treats the modular branches of Beli (2003), Corollary 3.10 at the
level before valuation estimates.  Every value of a normalized binary lattice
is an integral square modulo the ideal generated by the mixed term `2B(x,y)`
and the second adapted diagonal term `Q(y)`.
-/

namespace Bong

open Dyadic
open Module

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {q : QuadraticSpace K V} {L : Lattice K V}

namespace BONG

/-- Every lattice vector has two integral coordinates in the BONG-adapted
basis. -/
theorem exists_binaryIntegralBasis_coefficients
    (b : BONG V q L 2) {z : V} (hz : z ∈ L) :
    ∃ a c : IntegerRing K,
      z = (a : K) • b.head + (c : K) • b.binarySecondVector := by
  let zL : L.toSubmodule := ⟨z, hz⟩
  let a : IntegerRing K :=
    b.binaryIntegralBasis.repr zL (Sum.inl Unit.unit)
  let c : IntegerRing K :=
    b.binaryIntegralBasis.repr zL (Sum.inr 0)
  refine ⟨a, c, ?_⟩
  have hrepr := b.binaryIntegralBasis.sum_repr zL
  rw [Fintype.sum_sum_type, Fintype.sum_unique,
    Fin.sum_univ_one] at hrepr
  have hcoe := congrArg Subtype.val hrepr
  have hdecomp :
      z = a • b.head + c • b.binarySecondVector := by
    simpa [zL, a, c, b.coe_binaryIntegralBasis_inl,
      b.coe_binaryIntegralBasis_inr] using hcoe.symm
  change z =
    algebraMap (IntegerRing K) K a • b.head +
      algebraMap (IntegerRing K) K c • b.binarySecondVector
  rw [IsScalarTower.algebraMap_smul K,
    IsScalarTower.algebraMap_smul K]
  exact hdecomp

/-- The ideal containing the non-square terms in the adapted binary value
formula. -/
noncomputable def binaryValueErrorIdeal (b : BONG V q L 2) :
    Lattice.CoefficientIdeal (K := K) :=
  Lattice.principalIdeal (K := K)
      ((2 : K) * b.binaryMixedPairing) ⊔
    Lattice.principalIdeal (K := K)
      (q.quadratic b.binarySecondVector)

/-- Adapted-coordinate form of the value formula used in Corollary 3.10. -/
theorem quadratic_eq_of_binaryIntegralBasis_coefficients
    (b : BONG V q L 2) (a c : IntegerRing K) :
    q.quadratic
        ((a : K) • b.head + (c : K) • b.binarySecondVector) =
      (a : K) ^ 2 * b.value 0 +
        (c : K) ^ 2 * q.quadratic b.binarySecondVector +
        2 * (a : K) * (c : K) * b.binaryMixedPairing := by
  rw [q.quadratic_add, q.quadratic_smul, q.quadratic_smul,
    b.value_zero_eq_quadratic_head,
    LinearMap.BilinForm.smul_left,
    LinearMap.BilinForm.smul_right]
  simp only [binaryMixedPairing]
  ring

/-- Ideal-valued common core of Corollary 3.10(b,c). -/
theorem quadraticValueSet_subset_binaryValueErrorIdeal
    (b : BONG V q L 2) (hvalue : b.value 0 = 1) :
    Lattice.quadraticValueSet q L ⊆
      Lattice.integralSquareResidueSet b.binaryValueErrorIdeal := by
  intro z hz
  rw [Lattice.mem_quadraticValueSet_iff] at hz
  rcases hz with ⟨x, hx, rfl⟩
  rcases b.exists_binaryIntegralBasis_coefficients hx with
    ⟨a, c, rfl⟩
  refine ⟨a, ?_⟩
  rw [b.quadratic_eq_of_binaryIntegralBasis_coefficients, hvalue, mul_one]
  have hcrossGenerator :
      (2 : K) * b.binaryMixedPairing ∈
        Lattice.principalIdeal (K := K)
          ((2 : K) * b.binaryMixedPairing) :=
    Lattice.generator_mem_principalIdeal _
  have hcross :=
    (Lattice.principalIdeal (K := K)
      ((2 : K) * b.binaryMixedPairing)).smul_mem
        (a * c) hcrossGenerator
  change
    ((a : K) * (c : K)) * ((2 : K) * b.binaryMixedPairing) ∈
      Lattice.principalIdeal (K := K)
        ((2 : K) * b.binaryMixedPairing) at hcross
  have hdiagGenerator :
      q.quadratic b.binarySecondVector ∈
        Lattice.principalIdeal (K := K)
          (q.quadratic b.binarySecondVector) :=
    Lattice.generator_mem_principalIdeal _
  have hdiag :=
    (Lattice.principalIdeal (K := K)
      (q.quadratic b.binarySecondVector)).smul_mem
        (c ^ 2) hdiagGenerator
  change
    (c : K) ^ 2 * q.quadratic b.binarySecondVector ∈
      Lattice.principalIdeal (K := K)
        (q.quadratic b.binarySecondVector) at hdiag
  have hdiagSup :
      (c : K) ^ 2 * q.quadratic b.binarySecondVector ∈
        b.binaryValueErrorIdeal := by
    exact (show
      Lattice.principalIdeal (K := K)
          (q.quadratic b.binarySecondVector) ≤
        b.binaryValueErrorIdeal from le_sup_right) hdiag
  have hcrossSup :
      ((a : K) * (c : K)) *
          ((2 : K) * b.binaryMixedPairing) ∈
        b.binaryValueErrorIdeal := by
    exact (show
      Lattice.principalIdeal (K := K)
          ((2 : K) * b.binaryMixedPairing) ≤
        b.binaryValueErrorIdeal from le_sup_left) hcross
  have hsum := (b.binaryValueErrorIdeal).add_mem hdiagSup hcrossSup
  convert hsum using 1
  ring

/-- The norm-generator values satisfy the same adapted error-ideal bound. -/
theorem normGeneratorValueSet_subset_binaryValueErrorIdeal
    (b : BONG V q L 2) (hvalue : b.value 0 = 1) :
    Lattice.normGeneratorValueSet q L ⊆
      Lattice.integralSquareResidueSet b.binaryValueErrorIdeal := by
  intro z hz
  apply b.quadraticValueSet_subset_binaryValueErrorIdeal hvalue
  rw [Lattice.mem_quadraticValueSet_iff]
  rcases hz with ⟨x, hx, rfl⟩
  exact ⟨x, hx.mem, rfl⟩

/-- The binary error ideal is bounded by any principal ideal containing both
of its displayed generators. -/
theorem binaryValueErrorIdeal_le_principalIdeal
    (b : BONG V q L 2) {t : K}
    (hcross : (2 : K) * b.binaryMixedPairing ∈
      Lattice.principalIdeal (K := K) t)
    (hdiag : q.quadratic b.binarySecondVector ∈
      Lattice.principalIdeal (K := K) t) :
    b.binaryValueErrorIdeal ≤
      Lattice.principalIdeal (K := K) t := by
  rw [binaryValueErrorIdeal, sup_le_iff]
  constructor
  · rw [Lattice.principalIdeal, Submodule.span_le]
    simpa using hcross
  · rw [Lattice.principalIdeal, Submodule.span_le]
    simpa using hdiag

/-- Valuation bounds on the two adapted coefficients bound the binary error
ideal. -/
theorem binaryValueErrorIdeal_le_principalIdeal_of_ord_le
    (b : BONG V q L 2) (t : K) (ht : t ≠ 0)
    (hcross : ord K t ≤ ord K ((2 : K) * b.binaryMixedPairing))
    (hdiag : ord K t ≤
      ord K (q.quadratic b.binarySecondVector)) :
    b.binaryValueErrorIdeal ≤
      Lattice.principalIdeal (K := K) t := by
  apply b.binaryValueErrorIdeal_le_principalIdeal
  · exact Lattice.mem_principalIdeal_of_ord_le ht hcross
  · exact Lattice.mem_principalIdeal_of_ord_le ht hdiag

/-- Valuation form of the common implication in Corollary 3.10(b,c). -/
theorem quadraticValueSet_subset_integralSquareResidueSet_of_error_ord_le
    (b : BONG V q L 2) (hvalue : b.value 0 = 1)
    (t : K) (ht : t ≠ 0)
    (hcross : ord K t ≤ ord K ((2 : K) * b.binaryMixedPairing))
    (hdiag : ord K t ≤
      ord K (q.quadratic b.binarySecondVector)) :
    Lattice.quadraticValueSet q L ⊆
      Lattice.integralSquareResidueSet
        (Lattice.principalIdeal (K := K) t) := by
  exact (b.quadraticValueSet_subset_binaryValueErrorIdeal hvalue).trans
    (Lattice.integralSquareResidueSet_mono
      (b.binaryValueErrorIdeal_le_principalIdeal_of_ord_le
        t ht hcross hdiag))

end BONG

end Bong
