/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.JordanEffectiveNorm
import Bong.Lattice.NormRescale
import Bong.Lattice.ScaleTruncation

/-!
# Intrinsic interpretation of the effective Jordan norm

This file identifies the finite minimum called `jordanEffectiveNormOrderAt`
with the order of the norm ideal of O'Meara's intrinsic scale truncation
`L^r = L ∩ π^r L♯`.  Consequently the effective norm order is independent
of the chosen Jordan decomposition.
-/

namespace Bong

open Dyadic
open Module

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {q : QuadraticSpace K V} {L : Lattice K V} {t : Nat}

namespace Lattice.JordanDecomposition

/-- The norm ideal of one rescaled Jordan component is the power ideal at
its adjusted norm order. -/
theorem normIdeal_rescale_component_eq_powerIdeal
    (J : JordanDecomposition q L t) (r : Int) (i : Fin t) :
    normIdeal (J.component i).space
        (Lattice.rescale (J.scaleTruncationFactor r i)
          (J.component i).lattice) =
      powerIdeal (K := K)
        (JordanProfileOrder.adjustedAt
          (fun j ↦ ordUnit K (J.scaleGenerator j))
          (fun j ↦ ordUnit K (J.normGenerator j)) r i) := by
  rw [normIdeal_rescale_eq_principal_of_finrank_pos
      (J.component_finrank_pos i) (J.scaleTruncationFactor r i)
      (J.normGenerator i) (J.normIdeal_eq i),
    principalIdeal_eq_powerIdeal]
  congr 1
  rw [ordUnit_mul, ordUnit_pow,
    J.ordUnit_scaleTruncationFactor]
  simp only [JordanProfileOrder.adjustedAt]
  by_cases hscale : ordUnit K (J.scaleGenerator i) < r
  · rw [if_pos hscale, max_eq_right]
    · omega
    · omega
  · rw [if_neg hscale, max_eq_left]
    · omega
    · omega

/-- The norm ideal of the intrinsic scale truncation is generated by the
uniformizer at the effective Jordan norm order. -/
theorem normIdeal_scaleTruncation_eq_powerIdeal
    (J : JordanDecomposition q L t) (anchor : Fin t) (r : Int) :
    normIdeal q (scaleTruncation q L r) =
      powerIdeal (K := K) (BONG.jordanEffectiveNormOrderAt J anchor r) := by
  rw [J.scaleTruncation_eq_componentwiseRescaleLattice,
    (J.toOrthogonalDecomposition.componentwiseRescale
      (J.scaleTruncationFactor r)).normIdeal_eq_iSup_component]
  change (⨆ i, normIdeal (J.component i).space
      (Lattice.rescale (J.scaleTruncationFactor r i)
        (J.component i).lattice)) = _
  simp_rw [J.normIdeal_rescale_component_eq_powerIdeal]
  exact iSup_powerIdeal_fin_eq_inf'
    (fun i ↦ JordanProfileOrder.adjustedAt
      (fun j ↦ ordUnit K (J.scaleGenerator j))
      (fun j ↦ ordUnit K (J.normGenerator j)) r i) anchor

/-- Effective norm orders computed from any two nonempty Jordan
decompositions of the same lattice agree at every target scale. -/
theorem effectiveNormOrderAt_eq
    {s : Nat} (J : JordanDecomposition q L t)
    (H : JordanDecomposition q L s) (a : Fin t) (b : Fin s) (r : Int) :
    BONG.jordanEffectiveNormOrderAt J a r =
      BONG.jordanEffectiveNormOrderAt H b r := by
  have hideal :
      powerIdeal (K := K) (BONG.jordanEffectiveNormOrderAt J a r) =
        powerIdeal (K := K) (BONG.jordanEffectiveNormOrderAt H b r) :=
    (J.normIdeal_scaleTruncation_eq_powerIdeal a r).symm.trans
      (H.normIdeal_scaleTruncation_eq_powerIdeal b r)
  apply le_antisymm
  · exact (powerIdeal_le_iff _ _).mp hideal.ge
  · exact (powerIdeal_le_iff _ _).mp hideal.le

end Lattice.JordanDecomposition

end Bong
