/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/

import Bong.Bong.BasisLattice

/-!
# Diagonalization of BONGs with nondecreasing orders

Beli (2003), Corollaries 3.4(ii) and 4.4(i), imply that a BONG whose
orders are nondecreasing is an actual orthogonal integral basis.  The proof
below gives the same conclusion directly from the recursive norm-generator
definition of a BONG: the first value generates the norm of the basis
lattice, and the projected tail is handled inductively.
-/

namespace Bong

open Dyadic Module

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {q : QuadraticSpace K V} {L : Lattice K V}

namespace BONG

private theorem value_mem_headPrincipalIdeal {n : Nat}
    (b : BONG V q L (n + 1))
    (hmin : ∀ i : Fin (n + 1), b.order 0 ≤ b.order i)
    (i : Fin (n + 1)) :
    b.value i ∈ Lattice.principalIdeal (K := K) (b.value 0) := by
  apply Lattice.mem_principalIdeal_of_ord_le (b.value_ne_zero 0)
  calc
    ord K (b.value 0) = (b.order 0 : WithTop Int) :=
      (b.coe_order 0).symm
    _ ≤ (b.order i : WithTop Int) := WithTop.coe_le_coe.mpr (hmin i)
    _ = ord K (b.value i) := b.coe_order i

/-- If the first BONG order is minimal, its head also generates the norm
ideal of the lattice spanned by the full orthogonal BONG basis. -/
theorem head_isNormGenerator_basisLattice_of_order_minimal {n : Nat}
    (b : BONG V q L (n + 1))
    (hmin : ∀ i : Fin (n + 1), b.order 0 ≤ b.order i) :
    Lattice.IsNormGenerator q (Lattice.basisLattice b.basis) b.head := by
  constructor
  · rw [← b.ambientVector_zero_eq_head]
    exact Submodule.subset_span ⟨0, rfl⟩
  · rw [b.normIdeal_basisLattice]
    apply le_antisymm
    · rw [Submodule.span_le]
      rintro _ ⟨i, rfl⟩
      rw [← b.value_zero_eq_quadratic_head]
      exact b.value_mem_headPrincipalIdeal hmin i
    · rw [Lattice.principalIdeal, Submodule.span_le]
      rintro _ ha
      rw [Set.mem_singleton_iff] at ha
      subst ha
      exact Submodule.subset_span ⟨0, b.value_zero_eq_quadratic_head⟩

/-- A BONG with nondecreasing orders is the integral lattice generated by
its displayed orthogonal basis. -/
theorem lattice_eq_basisLattice_of_order_monotone {n : Nat}
    (b : BONG V q L (n + 1))
    (hmono : ∀ i j : Fin (n + 1), i ≤ j → b.order i ≤ b.order j) :
    L = Lattice.basisLattice b.basis := by
  induction n generalizing V q L with
  | zero =>
      simpa using b.lattice_eq_basisLattice
  | succ n ih =>
      have hmin : ∀ i : Fin (n + 2), b.order 0 ≤ b.order i := by
        intro i
        exact hmono 0 i (Fin.zero_le i)
      have htailMono : ∀ i j : Fin (n + 1), i ≤ j →
          b.tail.order i ≤ b.tail.order j := by
        intro i j hij
        rw [b.order_tail, b.order_tail]
        exact hmono i.succ j.succ (Fin.succ_le_succ_iff.mpr hij)
      have htail := ih b.tail htailMono
      have hprojection :
          L.projectedLattice q b.head b.head_isAnisotropic =
            (Lattice.basisLattice b.basis).projectedLattice q b.head
              b.head_isAnisotropic := by
        rw [b.projectedLattice_basisLattice]
        exact htail
      apply Lattice.eq_of_normIdeal_eq_of_projectedLattice_eq
        q L (Lattice.basisLattice b.basis) b.head
        b.head_isNormGenerator
        (b.head_isNormGenerator_basisLattice_of_order_minimal hmin)
        b.head_isAnisotropic
      · rw [b.head_isNormGenerator.normIdeal_eq,
          (b.head_isNormGenerator_basisLattice_of_order_minimal hmin).normIdeal_eq]
      · exact hprojection

end BONG

end Bong
