/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.AdjoinVector
import Bong.Lattice.ModularSplitting

/-!
# Enlarging one summand of an orthogonal lattice decomposition

If `L = J ⊥ C` and a vector in the carrier of `J` is adjoined to `L`, the
new lattice is obtained by adjoining that vector to `J` while leaving `C`
unchanged.  This is the common-complement argument in Beli (2019), Lemma 5.1.
-/

namespace Bong

open Dyadic

namespace Lattice

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {q : QuadraticSpace K V} {L M : Lattice K V}

namespace QuadraticSublattice

/-- Enlarge only the integral lattice of a quadratic sublattice. -/
noncomputable def adjoinVector (C : QuadraticSublattice q) (x : C.carrier) :
    QuadraticSublattice q where
  carrier := C.carrier
  nondegenerate := C.nondegenerate
  lattice := Lattice.adjoinVector C.lattice x

@[simp]
theorem adjoinVector_carrier (C : QuadraticSublattice q) (x : C.carrier) :
    (C.adjoinVector x).carrier = C.carrier :=
  rfl

/-- The original component is contained in its one-vector enlargement. -/
theorem ambientSubmodule_le_adjoinVector
    (C : QuadraticSublattice q) (x : C.carrier) :
    C.ambientSubmodule ≤ (C.adjoinVector x).ambientSubmodule := by
  rintro _ ⟨y, hy, rfl⟩
  exact ⟨y, Lattice.le_adjoinVector C.lattice x hy, rfl⟩

/-- The adjoined component vector belongs to the enlarged ambient module. -/
theorem coe_mem_adjoinVector_ambientSubmodule
    (C : QuadraticSublattice q) (x : C.carrier) :
    (x : V) ∈ (C.adjoinVector x).ambientSubmodule :=
  ⟨x, Lattice.mem_adjoinVector C.lattice x, rfl⟩

/-- The enlarged component is generated by the old ambient component and the
adjoined ambient vector. -/
theorem ambientSubmodule_adjoinVector_le
    (C : QuadraticSublattice q) (x : C.carrier)
    (P : Submodule (IntegerRing K) V)
    (hC : C.ambientSubmodule ≤ P) (hx : (x : V) ∈ P) :
    (C.adjoinVector x).ambientSubmodule ≤ P := by
  change (Lattice.adjoinVector C.lattice x).toSubmodule.map
      ((Submodule.subtype C.carrier).restrictScalars (IntegerRing K)) ≤ P
  rintro z ⟨y, hy, rfl⟩
  have hy' : y ∈ Lattice.adjoinVector C.lattice x := hy
  rw [Lattice.mem_adjoinVector_iff] at hy'
  obtain ⟨w, hw, a, rfl⟩ := hy'
  have hwP : (w : V) ∈ P := hC ⟨w, hw, rfl⟩
  have haxP := P.smul_mem a hx
  change ((w + a • x : C.carrier) : V) ∈ P
  rw [Submodule.coe_add, Submodule.coe_smul_of_tower]
  exact P.add_mem hwP haxP

end QuadraticSublattice

/-- Enlarge the first component of a two-term orthogonal decomposition. -/
noncomputable def OrthogonalDecomposition.adjoinFirst
    (D : OrthogonalDecomposition q L 2) (x : (D.component 0).carrier) :
    OrthogonalDecomposition q
      (Lattice.adjoinVector L (x : V)) 2 where
  component := pairComponents ((D.component 0).adjoinVector x) (D.component 1)
  orthogonal := by
    intro i j hij y z
    fin_cases i <;> fin_cases j
    · exact False.elim (hij rfl)
    · exact D.orthogonal 0 1 (by decide) y z
    · exact D.orthogonal 1 0 (by decide) y z
    · exact False.elim (hij rfl)
  sum_eq := by
    apply le_antisymm
    · apply iSup_le
      intro i
      fin_cases i
      · apply QuadraticSublattice.ambientSubmodule_adjoinVector_le
        · exact ((le_iSup (fun j ↦ (D.component j).ambientSubmodule) 0).trans_eq
            D.sum_eq).trans (Lattice.le_adjoinVector L (x : V))
        · exact Lattice.mem_adjoinVector L (x : V)
      · exact (le_iSup (fun j ↦ (D.component j).ambientSubmodule) 1).trans_eq
          D.sum_eq |>.trans (Lattice.le_adjoinVector L (x : V))
    · intro z hz
      have hz' : z ∈ Lattice.adjoinVector L (x : V) := hz
      rw [Lattice.mem_adjoinVector_iff] at hz'
      obtain ⟨y, hy, a, rfl⟩ := hz'
      have hL : L.toSubmodule ≤
          ⨆ i, (pairComponents ((D.component 0).adjoinVector x)
            (D.component 1) i).ambientSubmodule := by
        rw [← D.sum_eq]
        apply iSup_mono
        intro i
        fin_cases i
        · exact QuadraticSublattice.ambientSubmodule_le_adjoinVector _ _
        · exact le_rfl
      have hx : (x : V) ∈
          ⨆ i, (pairComponents ((D.component 0).adjoinVector x)
            (D.component 1) i).ambientSubmodule := by
        have hle := le_iSup
          (fun i : Fin 2 ↦
            (pairComponents ((D.component 0).adjoinVector x)
              (D.component 1) i).ambientSubmodule) 0
        exact hle
          (QuadraticSublattice.coe_mem_adjoinVector_ambientSubmodule _ _)
      exact Submodule.add_mem _ (hL hy) (Submodule.smul_mem _ a hx)

end Lattice

end Bong
