/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Dyadic.Valuation
import Bong.QuadraticSpace.Basic
import Mathlib.Algebra.Module.Lattice
import Mathlib.LinearAlgebra.Span.Basic
import Mathlib.RingTheory.Finiteness.Basic
import Mathlib.RingTheory.Valuation.Discrete.Basic

/-!
# Lattices over a dyadic local field

A lattice is a finitely generated module over the valuation ring whose scalar
extension spans the ambient vector space.  We store both conditions explicitly;
in particular, arbitrary submodules of the ambient vector space are not silently
treated as lattices.
-/

namespace Bong

namespace Dyadic

variable (K : Type*) [Field K] [CharZero K] [ValuativeRel K] [TopologicalSpace K]
  [DyadicContext K]

/-- The valuation ring determined by the normalized additive valuation. -/
noncomputable abbrev IntegerRing :=
  (AddValuation.toValuation (ord K)).valuationSubring

@[simp]
theorem mem_integerRing_iff {x : K} : x ∈ IntegerRing K ↔ IsIntegral K x := by
  change
    Multiplicative.ofAdd (OrderDual.toDual (ord K x)) ≤
        Multiplicative.ofAdd (OrderDual.toDual 0) ↔
      0 ≤ ord K x
  simp only [Multiplicative.ofAdd_le, OrderDual.toDual_le_toDual]

/-- The normalized valuation ring is a principal ideal ring. -/
noncomputable instance integerRingIsPrincipalIdealRing :
    IsPrincipalIdealRing (IntegerRing K) :=
  Valuation.valuationSubring_isPrincipalIdealRing
    (AddValuation.toValuation (ord K))

end Dyadic

open Dyadic

variable (K : Type*) (V : Type*) [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K] [AddCommGroup V] [Module K V]

/-- A full finitely generated module over the valuation ring of `K`. -/
structure Lattice where
  /-- The underlying module over the valuation ring. -/
  toSubmodule : Submodule (IntegerRing K) V
  /-- A lattice is finitely generated over the valuation ring. -/
  fg : toSubmodule.FG
  /-- Extending scalars from the valuation ring to `K` fills the ambient space. -/
  span_eq_top : Submodule.span K (toSubmodule : Set V) = ⊤

namespace Lattice

variable {K : Type*} {V : Type*} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K] [AddCommGroup V] [Module K V]

/-- A unit of the valuation ring has additive valuation zero in the field. -/
theorem isValuationUnit_coe_integerRingUnit (a : (IntegerRing K)ˣ) :
    IsValuationUnit K ((a : IntegerRing K) : K) := by
  have ha := (Valuation.Integers.isUnit_iff_valuation_eq_one
    (Valuation.integer.integers (AddValuation.toValuation (ord K)))).mp
      a.isUnit
  change ord K ((a : IntegerRing K) : K) = 0
  change Multiplicative.ofAdd
      (OrderDual.toDual (ord K ((a : IntegerRing K) : K))) =
    Multiplicative.ofAdd (OrderDual.toDual 0) at ha
  have ha' := congrArg Multiplicative.toAdd ha
  exact congrArg OrderDual.ofDual ha'

instance : SetLike (Lattice K V) V where
  coe L := L.toSubmodule
  coe_injective L M h := by
    have hsub : L.toSubmodule = M.toSubmodule := by
      apply Submodule.ext
      exact Set.ext_iff.mp h
    cases L with
    | mk L hfg hspan =>
      cases M with
      | mk M hfg' hspan' =>
        dsimp at hsub
        subst M
        rfl

@[simp]
theorem mem_toSubmodule {L : Lattice K V} {x : V} : x ∈ L.toSubmodule ↔ x ∈ L :=
  Iff.rfl

@[ext]
theorem ext {L M : Lattice K V} (h : L.toSubmodule = M.toSubmodule) : L = M := by
  exact SetLike.coe_injective (congrArg (fun N : Submodule (IntegerRing K) V ↦ (N : Set V)) h)

/-- The full lattice integrally generated by a field basis. -/
noncomputable def basisLattice {ι : Type*} [Finite ι]
    (b : Module.Basis ι K V) : Lattice K V where
  toSubmodule := Submodule.span (IntegerRing K) (Set.range b)
  fg := Submodule.fg_span (Set.toFinite (Set.range b))
  span_eq_top := by
    rw [Submodule.span_span_of_tower, b.span_eq]

/-- Reindexing a field basis does not change its integral basis lattice. -/
theorem basisLattice_reindex {ι κ : Type*} [Finite ι] [Finite κ]
    (b : Module.Basis ι K V) (e : ι ≃ κ) :
    basisLattice (b.reindex e) = basisLattice b := by
  apply Lattice.ext
  change Submodule.span (IntegerRing K) (Set.range (b.reindex e)) =
    Submodule.span (IntegerRing K) (Set.range b)
  congr 1
  ext x
  constructor
  · rintro ⟨i, rfl⟩
    exact ⟨e.symm i, by simp⟩
  · rintro ⟨i, rfl⟩
    exact ⟨e i, by simp⟩

instance : LE (Lattice K V) where
  le L M := L.toSubmodule ≤ M.toSubmodule

theorem le_def {L M : Lattice K V} : L ≤ M ↔ L.toSubmodule ≤ M.toSubmodule :=
  Iff.rfl

@[simp]
theorem zero_mem (L : Lattice K V) : (0 : V) ∈ L :=
  L.toSubmodule.zero_mem

theorem add_mem {L : Lattice K V} {x y : V} (hx : x ∈ L) (hy : y ∈ L) : x + y ∈ L :=
  L.toSubmodule.add_mem hx hy

theorem neg_mem {L : Lattice K V} {x : V} (hx : x ∈ L) : -x ∈ L :=
  L.toSubmodule.neg_mem hx

theorem sub_mem {L : Lattice K V} {x y : V} (hx : x ∈ L) (hy : y ∈ L) : x - y ∈ L :=
  L.toSubmodule.sub_mem hx hy

theorem smul_mem (L : Lattice K V) (a : IntegerRing K) {x : V} (hx : x ∈ L) : a • x ∈ L :=
  L.toSubmodule.smul_mem a hx

/-- The lattice generated over the valuation ring by a finite spanning set. -/
noncomputable def ofFinset (s : Finset V) (hspan : Submodule.span K (s : Set V) = ⊤) :
    Lattice K V where
  toSubmodule := Submodule.span (IntegerRing K) (s : Set V)
  fg := ⟨s, rfl⟩
  span_eq_top := by
    rw [Submodule.span_span_of_tower, hspan]

@[simp]
theorem toSubmodule_ofFinset (s : Finset V) (hspan : Submodule.span K (s : Set V) = ⊤) :
    (ofFinset s hspan).toSubmodule = Submodule.span (IntegerRing K) (s : Set V) :=
  rfl

theorem subset_ofFinset (s : Finset V) (hspan : Submodule.span K (s : Set V) = ⊤) :
    (s : Set V) ⊆ ofFinset s hspan :=
  Submodule.subset_span

/-- Every lattice spans its ambient vector space over `K`. -/
theorem spans (L : Lattice K V) : Submodule.span K (L : Set V) = ⊤ :=
  L.span_eq_top

/-- A full finitely generated lattice makes its ambient vector space finite-dimensional. -/
theorem moduleFinite (L : Lattice K V) : Module.Finite K V :=
  Module.Finite.of_fg_top (by
      rw [← L.span_eq_top]
      exact L.fg.span)

/-- Compatibility with mathlib's predicate for a full finitely generated lattice. -/
instance toSubmoduleIsLattice (L : Lattice K V) :
    L.toSubmodule.IsLattice K where
  fg := L.fg
  span_eq_top := L.span_eq_top

/-- The index type of a chosen integral basis of a lattice. -/
abbrev BasisIndex (L : Lattice K V) :=
  Module.Free.ChooseBasisIndex (IntegerRing K) L.toSubmodule

/-- A chosen basis of the lattice over the valuation ring. -/
noncomputable def integralBasis (L : Lattice K V) :
    Module.Basis L.BasisIndex (IntegerRing K) L.toSubmodule :=
  Module.Free.chooseBasis (IntegerRing K) L.toSubmodule

/-- The integral basis, extended to a field basis of the ambient vector space. -/
noncomputable def ambientBasis (L : Lattice K V) :
    Module.Basis L.BasisIndex K V :=
  L.integralBasis.extendOfIsLattice K

@[simp]
theorem ambientBasis_apply (L : Lattice K V) (i : L.BasisIndex) :
    L.ambientBasis i = (L.integralBasis i : V) :=
  Module.Basis.extendOfIsLattice_apply K L.integralBasis i

/-- The lattice is the integral span of its chosen ambient basis. -/
theorem toSubmodule_eq_span_ambientBasis (L : Lattice K V) :
    L.toSubmodule =
      Submodule.span (IntegerRing K) (Set.range L.ambientBasis) := by
  apply le_antisymm
  · intro x hx
    have hx' : (⟨x, hx⟩ : L.toSubmodule) ∈
        Submodule.span (IntegerRing K) (Set.range L.integralBasis) := by
      rw [L.integralBasis.span_eq]
      trivial
    rw [Submodule.mem_span_range_iff_exists_fun] at hx' ⊢
    rcases hx' with ⟨f, hf⟩
    refine ⟨f, ?_⟩
    simpa using congrArg Subtype.val hf
  · rw [Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    simp

/-- A chosen identification of the integral basis index with the ambient finrank. -/
noncomputable def basisIndexEquivFin (L : Lattice K V) :
    L.BasisIndex ≃ Fin (Module.finrank K V) := by
  letI := Fintype.ofFinite L.BasisIndex
  apply Fintype.equivOfCardEq
  simpa using (Module.finrank_eq_card_basis L.ambientBasis).symm

/-- The chosen integral basis, reindexed by the ambient finrank. -/
noncomputable def standardIntegralBasis (L : Lattice K V) :
    Module.Basis (Fin (Module.finrank K V)) (IntegerRing K) L.toSubmodule :=
  L.integralBasis.reindex L.basisIndexEquivFin

/-- The chosen integral basis, reindexed by `Fin (finrank K V)`. -/
noncomputable def standardAmbientBasis (L : Lattice K V) :
    Module.Basis (Fin (Module.finrank K V)) K V :=
  L.ambientBasis.reindex L.basisIndexEquivFin

@[simp]
theorem coe_standardIntegralBasis_apply (L : Lattice K V)
    (i : Fin (Module.finrank K V)) :
    (L.standardIntegralBasis i : V) = L.standardAmbientBasis i := by
  simp [standardIntegralBasis, standardAmbientBasis]

/-- Integral and ambient coordinates agree after applying the scalar inclusion. -/
theorem algebraMap_standardIntegralBasis_repr (L : Lattice K V)
    (y : L.toSubmodule) (i : Fin (Module.finrank K V)) :
    ((L.standardIntegralBasis.repr y i : IntegerRing K) : K) =
      L.standardAmbientBasis.repr (y : V) i := by
  have hsum :
      ∑ j, ((L.standardIntegralBasis.repr y j : IntegerRing K) : K) •
          L.standardAmbientBasis j = (y : V) := by
    have hO :
        ∑ j, (L.standardIntegralBasis.repr y j : IntegerRing K) •
            L.standardAmbientBasis j = (y : V) := by
      have h := congrArg Subtype.val (L.standardIntegralBasis.sum_repr y)
      simpa only [Submodule.coe_sum, Submodule.coe_smul_of_tower,
        coe_standardIntegralBasis_apply] using h
    calc
      ∑ j, ((L.standardIntegralBasis.repr y j : IntegerRing K) : K) •
          L.standardAmbientBasis j =
          ∑ j, (L.standardIntegralBasis.repr y j : IntegerRing K) •
            L.standardAmbientBasis j := by
        apply Finset.sum_congr rfl
        intro j _
        exact IsScalarTower.algebraMap_smul
          (R := IntegerRing K) (A := K) (M := V) _ _
      _ = (y : V) := hO
  have hrepr := congrArg (fun z : V ↦ L.standardAmbientBasis.repr z i) hsum
  simpa [Finsupp.single_apply] using hrepr

/-- Reindexing does not change the integral span of the chosen basis. -/
theorem toSubmodule_eq_span_standardAmbientBasis (L : Lattice K V) :
    L.toSubmodule =
      Submodule.span (IntegerRing K) (Set.range L.standardAmbientBasis) := by
  rw [standardAmbientBasis, Module.Basis.range_reindex]
  exact L.toSubmodule_eq_span_ambientBasis

end Lattice

end Bong
