/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.Determinant
import Bong.Lattice.Projection
import Mathlib.Algebra.Exact.Basic
import Mathlib.LinearAlgebra.Basis.Exact
import Mathlib.LinearAlgebra.Determinant

/-!
# Determinants and projection along a norm generator

This file proves the one-step determinant identity in Beli's Lemma 2.1.
For a norm generator `x` of `L`, the projection sequence

`𝒪 → L → pr_(x⊥) L`

is split exact.  An integral basis adapted to this sequence differs by a
determinant-one shear from the orthogonal basis consisting of `x` and a basis
of the projected lattice.  Its Gram determinant is therefore

`Q(x) * det (pr_(x⊥) L)`.

Changing from the adapted integral basis to the chosen integral basis of `L`
contributes the square of a valuation-ring unit, which disappears in Beli's
refined determinant class.
-/

namespace Bong

open Dyadic
open Module

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]

namespace Lattice

/-- An element whose square is integral over the valuation ring is integral. -/
theorem mem_integerRing_of_sq_mem_integerRing {a : K}
    (ha : a ^ 2 ∈ IntegerRing K) : a ∈ IntegerRing K := by
  rw [mem_integerRing_iff] at ha ⊢
  change 0 ≤ ord K (a ^ 2) at ha
  change 0 ≤ ord K a
  rw [ord_pow] at ha
  exact (nsmul_nonneg_iff two_ne_zero).mp ha

/-- Orthogonal projection restricted to the source and target lattices. -/
noncomputable def projectionMap (q : QuadraticSpace K V) (L : Lattice K V)
    (x : V) (hx : q.IsAnisotropic x) :
    L.toSubmodule →ₗ[IntegerRing K] (L.projectedLattice q x hx).toSubmodule where
  toFun y := ⟨q.projectionToOrthogonal x hx y,
    projection_mem_projectedLattice q L x hx y.property⟩
  map_add' y z := by
    apply Subtype.ext
    exact (q.projectionToOrthogonal x hx).map_add y z
  map_smul' a y := by
    apply Subtype.ext
    exact ((q.projectionToOrthogonal x hx).restrictScalars
      (IntegerRing K)).map_smul a y

@[simp]
theorem projectionMap_coe (q : QuadraticSpace K V) (L : Lattice K V)
    (x : V) (hx : q.IsAnisotropic x) (y : L.toSubmodule) :
    ((projectionMap q L x hx y :
      (L.projectedLattice q x hx).toSubmodule) : q.vectorOrthogonal x) =
        q.projectionToOrthogonal x hx y :=
  rfl

/-- The integral line in `L` generated by a lattice vector. -/
noncomputable def lineMap (L : Lattice K V) (x : V) (hx : x ∈ L) :
    IntegerRing K →ₗ[IntegerRing K] L.toSubmodule where
  toFun a := ⟨a • x, L.smul_mem a hx⟩
  map_add' a b := by
    apply Subtype.ext
    exact add_smul a b x
  map_smul' a b := by
    apply Subtype.ext
    exact mul_smul a b x

@[simp]
theorem lineMap_coe (L : Lattice K V) (x : V) (hx : x ∈ L)
    (a : IntegerRing K) : (lineMap L x hx a : V) = a • x :=
  rfl

theorem lineMap_injective (q : QuadraticSpace K V) (L : Lattice K V)
    (x : V) (generator : IsNormGenerator q L x)
    (anisotropic : q.IsAnisotropic x) :
    Function.Injective (lineMap L x generator.mem) := by
  intro a b hab
  apply Subtype.ext
  apply mul_right_cancel₀ anisotropic
  have hbilin := congrArg (fun y : L.toSubmodule ↦ q.bilin x (y : V)) hab
  change q.bilin x ((a : K) • x) = q.bilin x ((b : K) • x) at hbilin
  simpa only [LinearMap.BilinForm.smul_right,
    QuadraticSpace.quadratic] using hbilin

theorem projectionMap_surjective (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (anisotropic : q.IsAnisotropic x) :
    Function.Surjective (projectionMap q L x anisotropic) := by
  intro y
  rcases y.property with ⟨z, hz, hzy⟩
  exact ⟨⟨z, hz⟩, Subtype.ext hzy⟩

/-- Exactness of the norm-generator line followed by orthogonal projection. -/
theorem exact_lineMap_projectionMap (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (generator : IsNormGenerator q L x)
    (anisotropic : q.IsAnisotropic x) :
    Function.Exact (lineMap L x generator.mem)
      (projectionMap q L x anisotropic) := by
  intro y
  constructor
  · intro hy
    let a : K := q.bilin x (y : V) / q.quadratic x
    have hyW := congrArg
      (fun z : (L.projectedLattice q x anisotropic).toSubmodule ↦
        ((z : q.vectorOrthogonal x) : V)) hy
    have hya : (y : V) = a • x := by
      change q.orthogonalProjection x y = 0 at hyW
      rw [q.orthogonalProjection_apply] at hyW
      exact sub_eq_zero.mp hyW
    have hqy :
        q.quadratic (y : V) ∈ principalIdeal (K := K) (q.quadratic x) := by
      rw [← generator.normIdeal_eq]
      exact quadratic_mem_normIdeal q L y
    rw [principalIdeal, Submodule.mem_span_singleton] at hqy
    rcases hqy with ⟨c, hc⟩
    have hca : algebraMap (IntegerRing K) K c = a ^ 2 := by
      apply mul_right_cancel₀ anisotropic
      calc
        algebraMap (IntegerRing K) K c * q.quadratic x =
            q.quadratic (y : V) := by
          simpa only [Algebra.smul_def] using hc
        _ = q.quadratic (a • x) := congrArg q.quadratic hya
        _ = a ^ 2 * q.quadratic x := q.quadratic_smul a x
    have ha2 : a ^ 2 ∈ IntegerRing K := by
      rw [← hca]
      exact c.property
    let aO : IntegerRing K :=
      ⟨a, mem_integerRing_of_sq_mem_integerRing ha2⟩
    refine ⟨aO, Subtype.ext ?_⟩
    change (aO : K) • x = (y : V)
    exact hya.symm
  · rintro ⟨a, rfl⟩
    apply Subtype.ext
    change q.projectionToOrthogonal x anisotropic ((a : K) • x) = 0
    rw [map_smul]
    have hx0 : q.projectionToOrthogonal x anisotropic x = 0 := by
      apply Subtype.ext
      exact q.orthogonalProjection_self anisotropic
    rw [hx0, smul_zero]

private noncomputable def projectionLift (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (anisotropic : q.IsAnisotropic x)
    (i : Fin (finrank K (q.vectorOrthogonal x))) : L.toSubmodule :=
  Classical.choose (projectionMap_surjective q L x anisotropic
    ((L.projectedLattice q x anisotropic).standardIntegralBasis i))

private theorem projectionMap_lift (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (anisotropic : q.IsAnisotropic x)
    (i : Fin (finrank K (q.vectorOrthogonal x))) :
    projectionMap q L x anisotropic (projectionLift q L x anisotropic i) =
      (L.projectedLattice q x anisotropic).standardIntegralBasis i :=
  Classical.choose_spec (projectionMap_surjective q L x anisotropic
    ((L.projectedLattice q x anisotropic).standardIntegralBasis i))

private noncomputable def projectionSection (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (anisotropic : q.IsAnisotropic x) :
    (L.projectedLattice q x anisotropic).toSubmodule →ₗ[IntegerRing K]
      L.toSubmodule :=
  (L.projectedLattice q x anisotropic).standardIntegralBasis.constr
    (IntegerRing K) (projectionLift q L x anisotropic)

private theorem projectionMap_comp_projectionSection
    (q : QuadraticSpace K V) (L : Lattice K V) (x : V)
    (anisotropic : q.IsAnisotropic x) :
    projectionMap q L x anisotropic ∘ₗ projectionSection q L x anisotropic =
      LinearMap.id := by
  apply (L.projectedLattice q x anisotropic).standardIntegralBasis.ext
  intro i
  rw [LinearMap.comp_apply, projectionSection, Basis.constr_basis,
    projectionMap_lift, LinearMap.id_apply]

/-- The integral splitting determined by a norm generator and orthogonal
projection. -/
noncomputable def splittingEquiv (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (generator : IsNormGenerator q L x)
    (anisotropic : q.IsAnisotropic x) :
    L.toSubmodule ≃ₗ[IntegerRing K]
      IntegerRing K × (L.projectedLattice q x anisotropic).toSubmodule :=
  (((exact_lineMap_projectionMap q L x generator anisotropic).splitSurjectiveEquiv
    (lineMap_injective q L x generator anisotropic))
      ⟨projectionSection q L x anisotropic,
        projectionMap_comp_projectionSection q L x anisotropic⟩).1

/-- The splitting identifies the distinguished line with the first factor
and orthogonal projection with the second factor. -/
theorem splittingEquiv_spec (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (generator : IsNormGenerator q L x)
    (anisotropic : q.IsAnisotropic x) :
    lineMap L x generator.mem =
        (splittingEquiv q L x generator anisotropic).symm.toLinearMap ∘ₗ
          LinearMap.inl (IntegerRing K) (IntegerRing K)
            (L.projectedLattice q x anisotropic).toSubmodule ∧
      projectionMap q L x anisotropic =
        LinearMap.snd (IntegerRing K) (IntegerRing K)
          (L.projectedLattice q x anisotropic).toSubmodule ∘ₗ
            (splittingEquiv q L x generator anisotropic).toLinearMap :=
  (((exact_lineMap_projectionMap q L x generator anisotropic).splitSurjectiveEquiv
    (lineMap_injective q L x generator anisotropic))
      ⟨projectionSection q L x anisotropic,
        projectionMap_comp_projectionSection q L x anisotropic⟩).2

/-- An integral basis of `L` adapted to the norm-generator projection. -/
noncomputable def adaptedIntegralBasis (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (generator : IsNormGenerator q L x)
    (anisotropic : q.IsAnisotropic x) :
    Basis (Unit ⊕ Fin (finrank K (q.vectorOrthogonal x)))
      (IntegerRing K) L.toSubmodule :=
  ((Basis.singleton Unit (IntegerRing K)).prod
    (L.projectedLattice q x anisotropic).standardIntegralBasis).map
      (splittingEquiv q L x generator anisotropic).symm

@[simp]
theorem adaptedIntegralBasis_inl (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (generator : IsNormGenerator q L x)
    (anisotropic : q.IsAnisotropic x) (i : Unit) :
    (adaptedIntegralBasis q L x generator anisotropic (Sum.inl i) : V) = x := by
  have hb :
      ((Basis.singleton Unit (IntegerRing K)).prod
          (L.projectedLattice q x anisotropic).standardIntegralBasis)
          (Sum.inl i) = (1, 0) := by
    apply Prod.ext
    · rw [Basis.prod_apply_inl_fst, Basis.singleton_apply]
    · rw [Basis.prod_apply_inl_snd]
  have h := LinearMap.congr_fun
    (splittingEquiv_spec q L x generator anisotropic).1
      (1 : IntegerRing K)
  rw [adaptedIntegralBasis, Basis.map_apply, hb]
  have heq :
      (splittingEquiv q L x generator anisotropic).symm (1, 0) =
        lineMap L x generator.mem 1 := by
    change
      ((splittingEquiv q L x generator anisotropic).symm.toLinearMap)
          ((LinearMap.inl (IntegerRing K) (IntegerRing K)
            (L.projectedLattice q x anisotropic).toSubmodule) 1) =
        lineMap L x generator.mem 1
    exact h.symm
  calc
    ((splittingEquiv q L x generator anisotropic).symm (1, 0) : V) =
        (lineMap L x generator.mem 1 : V) := congrArg Subtype.val heq
    _ = x := by rw [lineMap_coe, one_smul]

@[simp]
theorem projectionMap_adaptedIntegralBasis_inr (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (generator : IsNormGenerator q L x)
    (anisotropic : q.IsAnisotropic x)
    (i : Fin (finrank K (q.vectorOrthogonal x))) :
    projectionMap q L x anisotropic
        (adaptedIntegralBasis q L x generator anisotropic (Sum.inr i)) =
      (L.projectedLattice q x anisotropic).standardIntegralBasis i := by
  have hb :
      ((Basis.singleton Unit (IntegerRing K)).prod
          (L.projectedLattice q x anisotropic).standardIntegralBasis)
          (Sum.inr i) =
        (0, (L.projectedLattice q x anisotropic).standardIntegralBasis i) := by
    apply Prod.ext
    · rw [Basis.prod_apply_inr_fst]
    · rw [Basis.prod_apply_inr_snd]
  rw [(splittingEquiv_spec q L x generator anisotropic).2]
  rw [LinearMap.comp_apply, adaptedIntegralBasis, Basis.map_apply, hb]
  change
    ((splittingEquiv q L x generator anisotropic)
      ((splittingEquiv q L x generator anisotropic).symm
        (0, (L.projectedLattice q x anisotropic).standardIntegralBasis i))).2 = _
  exact congrArg Prod.snd
    ((splittingEquiv q L x generator anisotropic).apply_symm_apply
      (0, (L.projectedLattice q x anisotropic).standardIntegralBasis i))

private noncomputable def adaptedAmbientBasis (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (generator : IsNormGenerator q L x)
    (anisotropic : q.IsAnisotropic x) :
    Basis (Unit ⊕ Fin (finrank K (q.vectorOrthogonal x))) K V :=
  (adaptedIntegralBasis q L x generator anisotropic).extendOfIsLattice K

@[simp]
private theorem adaptedAmbientBasis_inl (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (generator : IsNormGenerator q L x)
    (anisotropic : q.IsAnisotropic x) (i : Unit) :
    adaptedAmbientBasis q L x generator anisotropic (Sum.inl i) = x := by
  rw [adaptedAmbientBasis, Basis.extendOfIsLattice_apply]
  exact adaptedIntegralBasis_inl q L x generator anisotropic i

@[simp]
private theorem projectionToOrthogonal_adaptedAmbientBasis_inr
    (q : QuadraticSpace K V) (L : Lattice K V) (x : V)
    (generator : IsNormGenerator q L x) (anisotropic : q.IsAnisotropic x)
    (i : Fin (finrank K (q.vectorOrthogonal x))) :
    q.projectionToOrthogonal x anisotropic
        (adaptedAmbientBasis q L x generator anisotropic (Sum.inr i)) =
      (L.projectedLattice q x anisotropic).standardAmbientBasis i := by
  have h := congrArg
    (fun z : (L.projectedLattice q x anisotropic).toSubmodule ↦
      (z : q.vectorOrthogonal x))
    (projectionMap_adaptedIntegralBasis_inr q L x generator anisotropic i)
  simpa only [projectionMap_coe, adaptedAmbientBasis,
    Basis.extendOfIsLattice_apply, coe_standardIntegralBasis_apply] using h

omit [CharZero K] [ValuativeRel K] [TopologicalSpace K] [DyadicContext K] in
private theorem isCompl_line_vectorOrthogonal (q : QuadraticSpace K V)
    (x : V) (anisotropic : q.IsAnisotropic x) :
    IsCompl (K ∙ x) (q.vectorOrthogonal x) := by
  constructor
  · rw [disjoint_iff]
    exact q.span_singleton_inf_vectorOrthogonal_eq_bot anisotropic
  · rw [codisjoint_iff]
    exact q.span_singleton_sup_vectorOrthogonal_eq_top anisotropic

private noncomputable def orthogonalAmbientBasis (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (anisotropic : q.IsAnisotropic x) :
    Basis (Unit ⊕ Fin (finrank K (q.vectorOrthogonal x))) K V :=
  (((Basis.singleton Unit K).map
      (LinearEquiv.toSpanNonzeroSingleton K V x anisotropic.ne_zero)).prod
    (L.projectedLattice q x anisotropic).standardAmbientBasis).map
      ((K ∙ x).prodEquivOfIsCompl (q.vectorOrthogonal x)
        (isCompl_line_vectorOrthogonal q x anisotropic))

@[simp]
private theorem orthogonalAmbientBasis_inl (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (anisotropic : q.IsAnisotropic x)
    (i : Unit) : orthogonalAmbientBasis q L x anisotropic (Sum.inl i) = x := by
  simp [orthogonalAmbientBasis, Submodule.coe_prodEquivOfIsCompl']

@[simp]
private theorem orthogonalAmbientBasis_inr (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (anisotropic : q.IsAnisotropic x)
    (i : Fin (finrank K (q.vectorOrthogonal x))) :
    orthogonalAmbientBasis q L x anisotropic (Sum.inr i) =
      (L.projectedLattice q x anisotropic).standardAmbientBasis i := by
  simp [orthogonalAmbientBasis, Submodule.coe_prodEquivOfIsCompl']

private noncomputable def orthogonalGramMatrix (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (anisotropic : q.IsAnisotropic x) :
    Matrix (Unit ⊕ Fin (finrank K (q.vectorOrthogonal x)))
      (Unit ⊕ Fin (finrank K (q.vectorOrthogonal x))) K :=
  LinearMap.BilinForm.toMatrix (orthogonalAmbientBasis q L x anisotropic) q.bilin

private theorem det_orthogonalGramMatrix (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (anisotropic : q.IsAnisotropic x) :
    (orthogonalGramMatrix q L x anisotropic).det =
      q.quadratic x *
        determinant (q.orthogonalSpace x anisotropic)
          (L.projectedLattice q x anisotropic) := by
  let A : Matrix Unit Unit K := fun _ _ ↦ q.quadratic x
  let D := integralGramMatrix (q.orthogonalSpace x anisotropic)
    (L.projectedLattice q x anisotropic)
  have hmatrix : orthogonalGramMatrix q L x anisotropic =
      Matrix.fromBlocks A 0 0 D := by
    ext i j
    rcases i with i | i <;> rcases j with j | j
    · simp [orthogonalGramMatrix, A, LinearMap.BilinForm.toMatrix_apply,
        QuadraticSpace.quadratic]
    · have hj :=
        ((L.projectedLattice q x anisotropic).standardAmbientBasis j).property
      rw [orthogonalGramMatrix, LinearMap.BilinForm.toMatrix_apply,
        orthogonalAmbientBasis_inl, orthogonalAmbientBasis_inr,
        Matrix.fromBlocks_apply₁₂]
      change q.bilin x
        ((L.projectedLattice q x anisotropic).standardAmbientBasis j :
          q.vectorOrthogonal x) = 0
      exact (q.mem_vectorOrthogonal_iff x _).mp hj
    · have hi :=
        ((L.projectedLattice q x anisotropic).standardAmbientBasis i).property
      rw [orthogonalGramMatrix, LinearMap.BilinForm.toMatrix_apply,
        orthogonalAmbientBasis_inl, orthogonalAmbientBasis_inr,
        Matrix.fromBlocks_apply₂₁]
      change q.bilin
        ((L.projectedLattice q x anisotropic).standardAmbientBasis i :
          q.vectorOrthogonal x) x = 0
      rw [q.isSymm.eq]
      exact (q.mem_vectorOrthogonal_iff x _).mp hi
    · simp [orthogonalGramMatrix, D, LinearMap.BilinForm.toMatrix_apply,
        integralGramMatrix_apply]
  rw [hmatrix, Matrix.det_fromBlocks_zero₂₁, Matrix.det_unique]
  rfl

private theorem adaptedAmbientBasis_inr_decomposition
    (q : QuadraticSpace K V) (L : Lattice K V) (x : V)
    (generator : IsNormGenerator q L x) (anisotropic : q.IsAnisotropic x)
    (i : Fin (finrank K (q.vectorOrthogonal x))) :
    adaptedAmbientBasis q L x generator anisotropic (Sum.inr i) =
      (q.bilin x (adaptedAmbientBasis q L x generator anisotropic (Sum.inr i)) /
        q.quadratic x) • x +
        (L.projectedLattice q x anisotropic).standardAmbientBasis i := by
  have hp := congrArg Subtype.val
    (projectionToOrthogonal_adaptedAmbientBasis_inr
      q L x generator anisotropic i)
  change q.orthogonalProjection x
      (adaptedAmbientBasis q L x generator anisotropic (Sum.inr i)) =
    ((L.projectedLattice q x anisotropic).standardAmbientBasis i :
      q.vectorOrthogonal x) at hp
  rw [q.orthogonalProjection_apply] at hp
  rw [← hp]
  abel

private noncomputable def adaptedGramMatrix (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (generator : IsNormGenerator q L x)
    (anisotropic : q.IsAnisotropic x) :
    Matrix (Unit ⊕ Fin (finrank K (q.vectorOrthogonal x)))
      (Unit ⊕ Fin (finrank K (q.vectorOrthogonal x))) K :=
  LinearMap.BilinForm.toMatrix
    (adaptedAmbientBasis q L x generator anisotropic) q.bilin

private theorem det_toMatrix_orthogonal_adapted (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (generator : IsNormGenerator q L x)
    (anisotropic : q.IsAnisotropic x) :
    ((orthogonalAmbientBasis q L x anisotropic).toMatrix
      (adaptedAmbientBasis q L x generator anisotropic)).det = 1 := by
  let bO := orthogonalAmbientBasis q L x anisotropic
  let bA := adaptedAmbientBasis q L x generator anisotropic
  let P := bO.toMatrix bA
  let B : Matrix Unit (Fin (finrank K (q.vectorOrthogonal x))) K :=
    fun i j ↦ P (Sum.inl i) (Sum.inr j)
  have hP : P = Matrix.fromBlocks 1 B 0 1 := by
    ext i j
    rcases i with i | i <;> rcases j with j | j
    · cases i
      cases j
      rw [Matrix.fromBlocks_apply₁₁]
      change bO.repr (bA (Sum.inl Unit.unit)) (Sum.inl Unit.unit) = _
      have hcol : bA (Sum.inl Unit.unit) = bO (Sum.inl Unit.unit) := by
        simp [bA, bO]
      rw [hcol]
      simp
    · rfl
    · cases j
      rw [Matrix.fromBlocks_apply₂₁]
      change bO.repr (bA (Sum.inl Unit.unit)) (Sum.inr i) = 0
      have hcol : bA (Sum.inl Unit.unit) = bO (Sum.inl Unit.unit) := by
        simp [bA, bO]
      rw [hcol]
      simp
    · rw [Matrix.fromBlocks_apply₂₂, Matrix.one_apply]
      change bO.repr (bA (Sum.inr j)) (Sum.inr i) = _
      rw [adaptedAmbientBasis_inr_decomposition]
      have hvec :
          (q.bilin x (bA (Sum.inr j)) / q.quadratic x) • x +
              ((L.projectedLattice q x anisotropic).standardAmbientBasis j : V) =
            (q.bilin x (bA (Sum.inr j)) / q.quadratic x) •
                bO (Sum.inl Unit.unit) + bO (Sum.inr j) := by
        rw [orthogonalAmbientBasis_inl, orthogonalAmbientBasis_inr]
      rw [hvec]
      simp [Finsupp.single_apply]
      by_cases hij : i = j
      · subst j
        simp
      · simp [hij, Ne.symm hij]
  change P.det = 1
  rw [hP, Matrix.det_fromBlocks_zero₂₁, Matrix.det_one, Matrix.det_one, mul_one]

private theorem det_adaptedGramMatrix (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (generator : IsNormGenerator q L x)
    (anisotropic : q.IsAnisotropic x) :
    (adaptedGramMatrix q L x generator anisotropic).det =
      q.quadratic x *
        determinant (q.orthogonalSpace x anisotropic)
          (L.projectedLattice q x anisotropic) := by
  let bO := orthogonalAmbientBasis q L x anisotropic
  let bA := adaptedAmbientBasis q L x generator anisotropic
  let P := bO.toMatrix bA
  have hmatrix : P.transpose * orthogonalGramMatrix q L x anisotropic * P =
      adaptedGramMatrix q L x generator anisotropic := by
    exact LinearMap.BilinForm.toMatrix_mul_basis_toMatrix bO bA q.bilin
  have hP : P.det = 1 :=
    det_toMatrix_orthogonal_adapted q L x generator anisotropic
  rw [← hmatrix, Matrix.det_mul, Matrix.det_mul, Matrix.det_transpose, hP,
    one_mul, mul_one]
  exact det_orthogonalGramMatrix q L x anisotropic

/-- Integral change of basis from `b` to the lattice's chosen standard basis. -/
noncomputable def integralBasisChangeMatrix
    (L : Lattice K V)
    (b : Basis (Fin (finrank K V)) (IntegerRing K) L.toSubmodule) :
    Matrix (Fin (finrank K V)) (Fin (finrank K V)) (IntegerRing K) :=
  LinearMap.toMatrix b L.standardIntegralBasis
    (LinearEquiv.refl (IntegerRing K) L.toSubmodule)

theorem integralBasisChangeMatrix_map
    (L : Lattice K V)
    (b : Basis (Fin (finrank K V)) (IntegerRing K) L.toSubmodule) :
    (algebraMap (IntegerRing K) K).mapMatrix
        (integralBasisChangeMatrix L b) =
      L.standardAmbientBasis.toMatrix (b.extendOfIsLattice K) := by
  ext i j
  simp [integralBasisChangeMatrix, Basis.toMatrix_apply,
    algebraMap_standardIntegralBasis_repr, Basis.extendOfIsLattice_apply]

theorem isUnit_det_integralBasisChangeMatrix
    (L : Lattice K V)
    (b : Basis (Fin (finrank K V)) (IntegerRing K) L.toSubmodule) :
    IsUnit (integralBasisChangeMatrix L b).det := by
  exact LinearEquiv.isUnit_det
    (LinearEquiv.refl (IntegerRing K) L.toSubmodule) b L.standardIntegralBasis

theorem det_gramMatrix_integralBasis (q : QuadraticSpace K V)
    (L : Lattice K V)
    (b : Basis (Fin (finrank K V)) (IntegerRing K) L.toSubmodule) :
    (LinearMap.BilinForm.toMatrix (b.extendOfIsLattice K) q.bilin).det =
      determinant q L *
        ((((integralBasisChangeMatrix L b).det : IntegerRing K) : K) ^ 2) := by
  let A := integralBasisChangeMatrix L b
  let P := L.standardAmbientBasis.toMatrix (b.extendOfIsLattice K)
  have hP : (algebraMap (IntegerRing K) K).mapMatrix A = P :=
    integralBasisChangeMatrix_map L b
  have hmatrix : P.transpose * integralGramMatrix q L * P =
      LinearMap.BilinForm.toMatrix (b.extendOfIsLattice K) q.bilin := by
    exact LinearMap.BilinForm.toMatrix_mul_basis_toMatrix
      L.standardAmbientBasis (b.extendOfIsLattice K) q.bilin
  have hdet :
      (LinearMap.BilinForm.toMatrix (b.extendOfIsLattice K) q.bilin).det =
        determinant q L * P.det ^ 2 := by
    change
      (LinearMap.BilinForm.toMatrix (b.extendOfIsLattice K) q.bilin).det =
        (integralGramMatrix q L).det * P.det ^ 2
    rw [← hmatrix]
    simp only [Matrix.det_mul, Matrix.det_transpose]
    ring
  have hPdet : ((A.det : IntegerRing K) : K) = P.det := by
    change algebraMap (IntegerRing K) K A.det = P.det
    rw [RingHom.map_det, hP]
  rw [hdet, hPdet]

private noncomputable def adaptedIndexEquivFin (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (generator : IsNormGenerator q L x)
    (anisotropic : q.IsAnisotropic x) :
    (Unit ⊕ Fin (finrank K (q.vectorOrthogonal x))) ≃ Fin (finrank K V) := by
  apply Fintype.equivOfCardEq
  simpa using (Module.finrank_eq_card_basis
    (adaptedAmbientBasis q L x generator anisotropic)).symm

private noncomputable def adaptedStandardIntegralBasis
    (q : QuadraticSpace K V) (L : Lattice K V) (x : V)
    (generator : IsNormGenerator q L x) (anisotropic : q.IsAnisotropic x) :
    Basis (Fin (finrank K V)) (IntegerRing K) L.toSubmodule :=
  (adaptedIntegralBasis q L x generator anisotropic).reindex
    (adaptedIndexEquivFin q L x generator anisotropic)

private theorem extend_adaptedStandardIntegralBasis
    (q : QuadraticSpace K V) (L : Lattice K V) (x : V)
    (generator : IsNormGenerator q L x) (anisotropic : q.IsAnisotropic x) :
    (adaptedStandardIntegralBasis q L x generator anisotropic).extendOfIsLattice K =
      (adaptedAmbientBasis q L x generator anisotropic).reindex
        (adaptedIndexEquivFin q L x generator anisotropic) := by
  ext i
  simp [adaptedStandardIntegralBasis, adaptedAmbientBasis,
    Basis.extendOfIsLattice_apply]

private theorem det_adaptedStandardGramMatrix (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (generator : IsNormGenerator q L x)
    (anisotropic : q.IsAnisotropic x) :
    (LinearMap.BilinForm.toMatrix
      ((adaptedStandardIntegralBasis q L x generator anisotropic).extendOfIsLattice K)
        q.bilin).det = (adaptedGramMatrix q L x generator anisotropic).det := by
  let e := adaptedIndexEquivFin q L x generator anisotropic
  have hb := extend_adaptedStandardIntegralBasis q L x generator anisotropic
  rw [hb]
  have hmatrix :
      LinearMap.BilinForm.toMatrix
          ((adaptedAmbientBasis q L x generator anisotropic).reindex e) q.bilin =
        Matrix.reindex e e (adaptedGramMatrix q L x generator anisotropic) := by
    ext i j
    simp [adaptedGramMatrix, LinearMap.BilinForm.toMatrix_apply]
  rw [hmatrix]
  exact Matrix.det_reindex_self e
    (adaptedGramMatrix q L x generator anisotropic)

private theorem determinant_adapted_eq_mul_sq (q : QuadraticSpace K V)
    (L : Lattice K V) (x : V) (generator : IsNormGenerator q L x)
    (anisotropic : q.IsAnisotropic x) :
    q.quadratic x *
        determinant (q.orthogonalSpace x anisotropic)
          (L.projectedLattice q x anisotropic) =
      determinant q L *
        ((((integralBasisChangeMatrix L
          (adaptedStandardIntegralBasis q L x generator anisotropic)).det :
            IntegerRing K) : K) ^ 2) := by
  rw [← det_adaptedGramMatrix q L x generator anisotropic,
    ← det_adaptedStandardGramMatrix q L x generator anisotropic]
  exact det_gramMatrix_integralBasis q L
    (adaptedStandardIntegralBasis q L x generator anisotropic)

/-- Removing a norm-generator line subtracts its quadratic order from the
exact lattice volume order.  The integral change-of-basis determinant in the
projection splitting is a valuation unit, so its square contributes zero. -/
theorem volumeOrder_eq_ordUnit_add_projection
    (q : QuadraticSpace K V) (L : Lattice K V) (x : V)
    (generator : IsNormGenerator q L x) (anisotropic : q.IsAnisotropic x) :
    volumeOrder q L =
      ordUnit K (Units.mk0 (q.quadratic x) anisotropic) +
        volumeOrder (q.orthogonalSpace x anisotropic)
          (L.projectedLattice q x anisotropic) := by
  let b := adaptedStandardIntegralBasis q L x generator anisotropic
  let A := integralBasisChangeMatrix L b
  have hAunit : IsUnit A.det := isUnit_det_integralBasisChangeMatrix L b
  let uO : (IntegerRing K)ˣ := hAunit.unit
  let uK : Kˣ := Units.map (algebraMap (IntegerRing K) K) uO
  have huK : IsValuationUnit K (uK : K) := by
    simpa [uK] using isValuationUnit_coe_integerRingUnit uO
  have hfield := determinant_adapted_eq_mul_sq q L x generator anisotropic
  have hord := congrArg (ord K) hfield
  have huKord : ord K (uK : K) = 0 := huK
  have hdetUnit :
      (((integralBasisChangeMatrix L b).det : IntegerRing K) : K) =
        (uK : K) := by
    simp [A, uO, uK, hAunit.unit_spec]
  rw [ord_mul, ord_mul, hdetUnit, ord_pow, huKord,
    nsmul_zero, add_zero] at hord
  apply WithTop.coe_injective
  rw [coe_volumeOrder, WithTop.coe_add, coe_ordUnit, Units.val_mk0,
    coe_volumeOrder]
  exact hord.symm

/--
Beli's one-step refined determinant identity, proved without an additional
local-law assumption.
-/
theorem determinantClass_projection_of_normGenerator
    (q : QuadraticSpace K V) (L : Lattice K V) (x : V)
    (generator : IsNormGenerator q L x) (anisotropic : q.IsAnisotropic x) :
    determinantClass q L =
      unitSquareClass K (Units.mk0 (q.quadratic x) anisotropic) *
        determinantClass (q.orthogonalSpace x anisotropic)
          (L.projectedLattice q x anisotropic) := by
  let b := adaptedStandardIntegralBasis q L x generator anisotropic
  let A := integralBasisChangeMatrix L b
  have hAunit : IsUnit A.det := isUnit_det_integralBasisChangeMatrix L b
  let uO : (IntegerRing K)ˣ := hAunit.unit
  let uK : Kˣ := Units.map (algebraMap (IntegerRing K) K) uO
  have huK : IsValuationUnit K (uK : K) := by
    simpa [uK] using isValuationUnit_coe_integerRingUnit uO
  have hfield := determinant_adapted_eq_mul_sq q L x generator anisotropic
  have hunit :
      Units.mk0 (q.quadratic x) anisotropic *
          determinantUnit (q.orthogonalSpace x anisotropic)
            (L.projectedLattice q x anisotropic) =
        determinantUnit q L * uK ^ 2 := by
    apply Units.ext
    change
      q.quadratic x *
          determinant (q.orthogonalSpace x anisotropic)
            (L.projectedLattice q x anisotropic) =
        determinant q L * (uK : K) ^ 2
    simpa [A, b, uO, uK, hAunit.unit_spec] using hfield
  change
    unitSquareClass K (determinantUnit q L) =
      unitSquareClass K (Units.mk0 (q.quadratic x) anisotropic) *
        unitSquareClass K
          (determinantUnit (q.orthogonalSpace x anisotropic)
            (L.projectedLattice q x anisotropic))
  calc
    unitSquareClass K (determinantUnit q L) =
        unitSquareClass K (determinantUnit q L * uK ^ 2) :=
      (unitSquareClass_mul_unit_square K
        (determinantUnit q L) uK huK).symm
    _ = unitSquareClass K
          (Units.mk0 (q.quadratic x) anisotropic *
            determinantUnit (q.orthogonalSpace x anisotropic)
              (L.projectedLattice q x anisotropic)) :=
      congrArg (unitSquareClass K) hunit.symm
    _ = unitSquareClass K (Units.mk0 (q.quadratic x) anisotropic) *
          unitSquareClass K
            (determinantUnit (q.orthogonalSpace x anisotropic)
              (L.projectedLattice q x anisotropic)) :=
      unitSquareClass_mul K _ _

end Lattice

end Bong
