/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.Basis
import Bong.Dyadic.UnitSquareClass
import Bong.Lattice.Ideals

/-!
# Determinant and volume of a quadratic lattice

The chosen integral basis of a lattice is extended to a field basis and used
to form its Gram determinant.  Beli's determinant is its class modulo squares
of valuation units, while its volume is the corresponding principal
coefficient ideal.

The ordinary field square class is proved to agree with the product of the
values of every BONG.  The stronger refined equality modulo valuation-unit
squares is the integral content of Beli's Lemma 2.1 and is kept separate from
this purely ambient change-of-basis calculation.
-/

namespace Bong

open Dyadic
open Module

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]

namespace Lattice

/-- The Gram matrix in the chosen integral ambient basis. -/
noncomputable def integralGramMatrix (q : QuadraticSpace K V)
    (L : Lattice K V) :
    Matrix (Fin (finrank K V)) (Fin (finrank K V)) K :=
  LinearMap.BilinForm.toMatrix L.standardAmbientBasis q.bilin

@[simp]
theorem integralGramMatrix_apply (q : QuadraticSpace K V)
    (L : Lattice K V) (i j : Fin (finrank K V)) :
    integralGramMatrix q L i j =
      q.bilin (L.standardAmbientBasis i) (L.standardAmbientBasis j) :=
  LinearMap.BilinForm.toMatrix_apply L.standardAmbientBasis q.bilin i j

/-- A representative of the determinant of the quadratic lattice. -/
noncomputable def determinant (q : QuadraticSpace K V) (L : Lattice K V) : K :=
  Matrix.det (integralGramMatrix q L)

/-- Nondegeneracy makes the chosen determinant representative nonzero. -/
theorem determinant_ne_zero (q : QuadraticSpace K V) (L : Lattice K V) :
    determinant q L ≠ 0 := by
  exact (LinearMap.BilinForm.nondegenerate_iff_det_ne_zero
    L.standardAmbientBasis).mp q.nondegenerate

/-- The Gram determinant of a zero-dimensional lattice is one. -/
@[simp]
theorem determinant_eq_one_of_subsingleton (q : QuadraticSpace K V)
    (L : Lattice K V) (hV : Subsingleton V) : determinant q L = 1 := by
  letI : Module.Finite K V := L.moduleFinite
  letI : Subsingleton V := hV
  have hfinrank : finrank K V = 0 := Module.finrank_zero_iff.mpr inferInstance
  letI : IsEmpty (Fin (finrank K V)) :=
    ⟨fun i ↦ Nat.not_lt_zero i.1 (hfinrank ▸ i.2)⟩
  exact Matrix.det_isEmpty

/-- The nonzero determinant representative. -/
noncomputable def determinantUnit (q : QuadraticSpace K V)
    (L : Lattice K V) : Kˣ :=
  Units.mk0 (determinant q L) (determinant_ne_zero q L)

@[simp]
theorem coe_determinantUnit (q : QuadraticSpace K V) (L : Lattice K V) :
    (determinantUnit q L : K) = determinant q L :=
  rfl

@[simp]
theorem determinantUnit_eq_one_of_subsingleton (q : QuadraticSpace K V)
    (L : Lattice K V) (hV : Subsingleton V) : determinantUnit q L = 1 := by
  apply Units.ext
  exact determinant_eq_one_of_subsingleton q L hV

/-- Beli's determinant class, modulo squares of valuation units. -/
noncomputable def determinantClass (q : QuadraticSpace K V)
    (L : Lattice K V) : UnitSquareClass K :=
  unitSquareClass K (determinantUnit q L)

@[simp]
theorem determinantClass_eq_one_of_subsingleton (q : QuadraticSpace K V)
    (L : Lattice K V) (hV : Subsingleton V) : determinantClass q L = 1 := by
  rw [determinantClass, determinantUnit_eq_one_of_subsingleton q L hV]
  exact unitSquareClass_one K

/-- The volume ideal generated by a determinant representative. -/
noncomputable def volumeIdeal (q : QuadraticSpace K V) (L : Lattice K V) :
    CoefficientIdeal (K := K) :=
  principalIdeal (K := K) (determinant q L)

/-- Equal refined determinant classes generate the same volume ideal. -/
theorem volumeIdeal_eq_of_determinantClass_eq (q : QuadraticSpace K V)
    (L M : Lattice K V) (h : determinantClass q L = determinantClass q M) :
    volumeIdeal q L = volumeIdeal q M := by
  change
    unitSquareClass K (determinantUnit q L) =
      unitSquareClass K (determinantUnit q M) at h
  change
    QuotientGroup.mk' (valuationUnitSquareSubgroup K) (determinantUnit q L) =
      QuotientGroup.mk' (valuationUnitSquareSubgroup K) (determinantUnit q M) at h
  rw [QuotientGroup.mk'_eq_mk'] at h
  rcases h with ⟨z, hz, hdet⟩
  rw [mem_valuationUnitSquareSubgroup_iff] at hz
  rcases hz with ⟨u, hu, hu2⟩
  subst z
  have huSquare : IsValuationUnit K (((u ^ 2 : Kˣ) : K)) := by
    change ord K ((u : K) ^ 2) = 0
    change ord K (u : K) = 0 at hu
    rw [ord_pow, hu]
    simp
  have hdet' := congrArg (fun a : Kˣ ↦ (a : K)) hdet
  change
    determinant q L * (((u ^ 2 : Kˣ) : K)) = determinant q M at hdet'
  change
    principalIdeal (K := K) (determinant q L) =
      principalIdeal (K := K) (determinant q M)
  calc
    principalIdeal (K := K) (determinant q L) =
        principalIdeal (K := K) (determinant q L * (((u ^ 2 : Kˣ) : K))) :=
      (principalIdeal_mul_eq_of_isValuationUnit
        (determinant q L) (u ^ 2) huSquare).symm
    _ = principalIdeal (K := K) (determinant q M) :=
      congrArg (principalIdeal (K := K)) hdet'

theorem determinant_mem_volumeIdeal (q : QuadraticSpace K V)
    (L : Lattice K V) : determinant q L ∈ volumeIdeal q L :=
  generator_mem_principalIdeal (determinant q L)

/-- The integral order of the lattice volume. -/
noncomputable def volumeOrder (q : QuadraticSpace K V) (L : Lattice K V) : Int :=
  (ord K (determinant q L)).untop
    ((ord_eq_top_iff K).not.mpr (determinant_ne_zero q L))

@[simp]
theorem coe_volumeOrder (q : QuadraticSpace K V) (L : Lattice K V) :
    (volumeOrder q L : WithTop Int) = ord K (determinant q L) :=
  WithTop.coe_untop _ _

/--
The product of the values of a BONG is the chosen lattice determinant times
the square of a change-of-basis determinant.  This witness-level statement is
the form needed when a congruence theorem supplies a particular determinant
representative, as in O'Meara 93:28(i).
-/
theorem exists_valueProduct_eq_determinantUnit_mul_square
    {q : QuadraticSpace K V} {L : Lattice K V} {n : Nat}
    (b : BONG V q L n) :
    ∃ p : Kˣ, b.valueProduct = determinantUnit q L * p ^ 2 := by
  have hn := b.length_eq_finrank
  subst n
  let P : Matrix (Fin (finrank K V)) (Fin (finrank K V)) K :=
    L.standardAmbientBasis.toMatrix b.basis
  have hmatrix :
      P.transpose * integralGramMatrix q L * P = b.gramMatrix := by
    exact LinearMap.BilinForm.toMatrix_mul_basis_toMatrix
      L.standardAmbientBasis b.basis q.bilin
  have hdet :
      b.gramDeterminant = determinant q L * Matrix.det P ^ 2 := by
    rw [BONG.gramDeterminant, determinant, ← hmatrix]
    simp only [Matrix.det_mul, Matrix.det_transpose]
    ring
  have hP : Matrix.det P ≠ 0 := by
    intro hzero
    have hb : b.gramDeterminant ≠ 0 := by
      exact (LinearMap.BilinForm.nondegenerate_iff_det_ne_zero b.basis).mp
        q.nondegenerate
    apply hb
    rw [hdet, hzero]
    simp
  let p : Kˣ := Units.mk0 (Matrix.det P) hP
  have hv : b.valueProduct = determinantUnit q L * p ^ 2 := by
    apply Units.ext
    change (b.valueProduct : K) = determinant q L * Matrix.det P ^ 2
    rw [← b.gramDeterminant_eq_valueProduct]
    exact hdet
  exact ⟨p, hv⟩

/--
The determinant representative and every BONG value product determine the
same ordinary square class of the ambient quadratic space.
-/
theorem determinantSquareClass_eq_valueProduct {q : QuadraticSpace K V}
    {L : Lattice K V} {n : Nat} (b : BONG V q L n) :
    squareClass K (determinantUnit q L) = squareClass K b.valueProduct := by
  rcases exists_valueProduct_eq_determinantUnit_mul_square b with ⟨p, hv⟩
  rw [hv]
  exact (squareClass_mul_square K (determinantUnit q L) p).symm

/-- Forgetting the integral refinement recovers the BONG's ambient square class. -/
theorem determinantClass_toSquareClass_eq_valueProduct
    {q : QuadraticSpace K V} {L : Lattice K V} {n : Nat}
    (b : BONG V q L n) :
    unitSquareClassToSquareClass K (determinantClass q L) =
      squareClass K b.valueProduct :=
  determinantSquareClass_eq_valueProduct b

end Lattice

end Bong
