/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.DeterminantIsometry
import Bong.Lattice.MixedPairing
import Bong.QuadraticSpace.HyperbolicPlane

/-!
# Invariants of the standard scaled hyperbolic lattice

For the standard lattice in `H_s`, the norm ideal is generated by `2s` and
the refined determinant class is represented by `-s²`.
-/

namespace Bong

open Dyadic Module

namespace Lattice

universe u

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]

/-- The norm ideal of the standard lattice in `H_s` is generated by `2s`. -/
theorem normIdeal_hyperbolicPlaneLattice (s : Kˣ) :
    normIdeal (QuadraticSpace.hyperbolicPlane s)
        (hyperbolicPlaneLattice (K := K)) =
      principalIdeal (K := K) (2 * (s : K)) := by
  apply le_antisymm
  · apply normIdeal_le_of_quadratic_mem
    intro x hx
    rw [QuadraticSpace.hyperbolicPlane_quadratic_apply]
    apply mul_mem_principalIdeal_of_mem_integerRing
    have hx' : ∀ i, x i ∈ IntegerRing K := by
      rw [hyperbolicPlaneLattice,
        mem_basisLattice_iff_repr_mem_integerRing] at hx
      simpa using hx
    exact (IntegerRing K).mul_mem _ _ (hx' 0) (hx' 1)
  · rw [principalIdeal, Submodule.span_le, Set.singleton_subset_iff]
    let e0 : Fin 2 → K := Pi.single 0 1
    let e1 : Fin 2 → K := Pi.single 1 1
    have he0 : e0 ∈ hyperbolicPlaneLattice (K := K) := by
      rw [hyperbolicPlaneLattice,
        mem_basisLattice_iff_repr_mem_integerRing]
      simp [e0]
    have he1 : e1 ∈ hyperbolicPlaneLattice (K := K) := by
      rw [hyperbolicPlaneLattice,
        mem_basisLattice_iff_repr_mem_integerRing]
      simp [e1]
    have hvalue := quadratic_mem_normIdeal_of_mem
      (QuadraticSpace.hyperbolicPlane s)
      (hyperbolicPlaneLattice (K := K))
      ((hyperbolicPlaneLattice (K := K)).add_mem he0 he1)
    rw [QuadraticSpace.hyperbolicPlane_quadratic_apply] at hvalue
    simpa [e0, e1] using hvalue

/-- The refined Gram-determinant class of the standard lattice in `H_s` is
represented by `-s²`. -/
theorem determinantClass_hyperbolicPlaneLattice (s : Kˣ) :
    determinantClass (QuadraticSpace.hyperbolicPlane s)
        (hyperbolicPlaneLattice (K := K)) =
      unitSquareClass K ((-1 : Kˣ) * s ^ 2) := by
  change determinantClass (QuadraticSpace.hyperbolicPlane s)
      (basisLattice (Pi.basisFun K (Fin 2))) = _
  rw [← unitSquareClass_gramUnitOfBasis_eq_determinantClass
    (QuadraticSpace.hyperbolicPlane s) (Pi.basisFun K (Fin 2))]
  apply congrArg (unitSquareClass K)
  apply Units.ext
  let A := LinearMap.BilinForm.toMatrix (Pi.basisFun K (Fin 2))
    (QuadraticSpace.hyperbolicPlane s).bilin
  have hA : A = !![0, (s : K); (s : K), 0] := by
    ext i j
    fin_cases i <;> fin_cases j <;>
      simp [A, LinearMap.BilinForm.toMatrix_apply,
        QuadraticSpace.hyperbolicPlane_bilin_apply, Pi.basisFun_apply]
  change A.det = (((-1 : Kˣ) * s ^ 2 : Kˣ) : K)
  rw [hA]
  simp [Matrix.det_fin_two_of, pow_two]

end Lattice

end Bong
