/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.Sum

/-!
# Scale and norm ideals of a quadratic lattice

For a lattice `L` in a quadratic space `(V, B)`, the scale is generated by
all `B(x, y)` and the norm is generated by all `Q(x)`.  We represent these
fractional ideals as valuation-ring submodules of the fraction field `K`.

With Beli's convention `Q(x) = B(x, x)`, one has

`nL ⊆ sL` and `2 * sL ⊆ nL`.
-/

namespace Bong

open Dyadic

variable {K : Type*} {V : Type*} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K] [AddCommGroup V] [Module K V]

namespace Lattice

/-- A fractional coefficient ideal, represented as an `𝓞`-submodule of `K`. -/
noncomputable abbrev CoefficientIdeal := Submodule (IntegerRing K) K

/-- The values `B(x, y)` generating the scale ideal. -/
def scaleGenerators (q : QuadraticSpace K V) (L : Lattice K V) : Set K :=
  Set.range fun p : L.toSubmodule × L.toSubmodule ↦ q.bilin (p.1 : V) (p.2 : V)

/-- The values `Q(x)` generating the norm ideal. -/
def normGenerators (q : QuadraticSpace K V) (L : Lattice K V) : Set K :=
  Set.range fun x : L.toSubmodule ↦ q.quadratic (x : V)

/-- The scale ideal `sL`, generated by all bilinear pairings on `L`. -/
noncomputable def scaleIdeal (q : QuadraticSpace K V) (L : Lattice K V) :
    CoefficientIdeal (K := K) :=
  Submodule.span (IntegerRing K) (scaleGenerators q L)

/-- The norm ideal `nL`, generated by all quadratic values on `L`. -/
noncomputable def normIdeal (q : QuadraticSpace K V) (L : Lattice K V) :
    CoefficientIdeal (K := K) :=
  Submodule.span (IntegerRing K) (normGenerators q L)

/-- The principal coefficient ideal generated by `a`. -/
noncomputable def principalIdeal (a : K) : CoefficientIdeal (K := K) :=
  Submodule.span (IntegerRing K) {a}

/-- The unit coefficient ideal `𝓞`. -/
noncomputable def unitIdeal : CoefficientIdeal (K := K) :=
  principalIdeal (K := K) 1

@[simp]
theorem mem_unitIdeal_iff {a : K} : a ∈ unitIdeal (K := K) ↔ a ∈ IntegerRing K := by
  rw [unitIdeal, principalIdeal, Submodule.mem_span_singleton]
  constructor
  · rintro ⟨c, hc⟩
    have hca : (c : K) = a := by simpa [Algebra.smul_def] using hc
    rw [← hca]
    exact c.property
  · intro ha
    refine ⟨⟨a, ha⟩, ?_⟩
    simp [Algebra.smul_def]

theorem mem_unitIdeal_iff_isIntegral {a : K} :
    a ∈ unitIdeal (K := K) ↔ Dyadic.IsIntegral K a :=
  mem_unitIdeal_iff.trans (mem_integerRing_iff K)

theorem bilin_mem_scaleIdeal (q : QuadraticSpace K V) (L : Lattice K V)
    (x y : L.toSubmodule) :
    q.bilin (x : V) (y : V) ∈ scaleIdeal q L :=
  Submodule.subset_span ⟨(x, y), rfl⟩

theorem quadratic_mem_normIdeal (q : QuadraticSpace K V) (L : Lattice K V)
    (x : L.toSubmodule) :
    q.quadratic (x : V) ∈ normIdeal q L :=
  Submodule.subset_span ⟨x, rfl⟩

theorem bilin_mem_scaleIdeal_of_mem (q : QuadraticSpace K V) (L : Lattice K V)
    {x y : V} (hx : x ∈ L) (hy : y ∈ L) : q.bilin x y ∈ scaleIdeal q L :=
  bilin_mem_scaleIdeal q L ⟨x, hx⟩ ⟨y, hy⟩

theorem quadratic_mem_normIdeal_of_mem (q : QuadraticSpace K V) (L : Lattice K V)
    {x : V} (hx : x ∈ L) : q.quadratic x ∈ normIdeal q L :=
  quadratic_mem_normIdeal q L ⟨x, hx⟩

/-- To bound a norm ideal, it is enough to bound every quadratic value on
the lattice. -/
theorem normIdeal_le_of_quadratic_mem (q : QuadraticSpace K V)
    (L : Lattice K V) (I : CoefficientIdeal (K := K))
    (h : ∀ x : V, x ∈ L → q.quadratic x ∈ I) :
    normIdeal q L ≤ I := by
  rw [normIdeal, Submodule.span_le]
  rintro _ ⟨x, rfl⟩
  exact h (x : V) x.property

theorem generator_mem_principalIdeal (a : K) : a ∈ principalIdeal (K := K) a :=
  Submodule.subset_span (Set.mem_singleton a)

/-- Multiplying a generator by a valuation unit does not change its coefficient ideal. -/
theorem principalIdeal_mul_eq_of_isValuationUnit (a : K) (u : Kˣ)
    (hu : IsValuationUnit K (u : K)) :
    principalIdeal (K := K) (a * (u : K)) = principalIdeal (K := K) a := by
  have huIntegral : Dyadic.IsIntegral K (u : K) := by
    rw [Dyadic.IsIntegral, hu]
  have huInv : IsValuationUnit K ((u⁻¹ : Kˣ) : K) := by
    simpa [IsValuationUnit, AddValuation.map_inv, hu]
  have huInvIntegral : Dyadic.IsIntegral K ((u⁻¹ : Kˣ) : K) := by
    rw [Dyadic.IsIntegral, huInv]
  change
    Submodule.span (IntegerRing K) {a * (u : K)} =
      Submodule.span (IntegerRing K) {a}
  apply le_antisymm
  · rw [Submodule.span_le, Set.singleton_subset_iff]
    apply Submodule.mem_span_singleton.mpr
    refine ⟨⟨(u : K), (mem_integerRing_iff K).2 huIntegral⟩, ?_⟩
    simp [Algebra.smul_def, mul_comm]
  · rw [Submodule.span_le, Set.singleton_subset_iff]
    apply Submodule.mem_span_singleton.mpr
    refine ⟨⟨((u⁻¹ : Kˣ) : K), (mem_integerRing_iff K).2 huInvIntegral⟩, ?_⟩
    have h : (u : K)⁻¹ * (a * (u : K)) = a := by
      rw [← mul_assoc, mul_comm (u : K)⁻¹ a, mul_assoc,
        inv_mul_cancel₀ (Units.ne_zero u), mul_one]
    simpa [Algebra.smul_def] using h

/-- Equal nonzero principal ideals have generators differing by a valuation unit. -/
theorem exists_valuationUnit_mul_eq_of_principalIdeal_eq
    (a b : Kˣ)
    (h : principalIdeal (K := K) (a : K) =
      principalIdeal (K := K) (b : K)) :
    ∃ u : Kˣ, IsValuationUnit K (u : K) ∧ u * a = b := by
  change (IntegerRing K ∙ (a : K)) = (IntegerRing K ∙ (b : K)) at h
  rcases Submodule.span_singleton_eq_span_singleton.mp h with ⟨uO, huO⟩
  let u : Kˣ := Units.map (algebraMap (IntegerRing K) K) uO
  refine ⟨u, ?_, ?_⟩
  · change IsValuationUnit K ((uO : IntegerRing K) : K)
    exact isValuationUnit_coe_integerRingUnit uO
  · apply Units.ext
    change uO • (a : K) = (b : K)
    exact huO

/-- Since `Q(x) = B(x, x)`, the norm ideal is contained in the scale ideal. -/
theorem normIdeal_le_scaleIdeal (q : QuadraticSpace K V) (L : Lattice K V) :
    normIdeal q L ≤ scaleIdeal q L := by
  rw [normIdeal, Submodule.span_le]
  rintro _ ⟨x, rfl⟩
  change q.bilin (x : V) (x : V) ∈ scaleIdeal q L
  exact bilin_mem_scaleIdeal q L x x

/-- Multiplication by `2`, viewed as a valuation-ring linear endomorphism of `K`. -/
noncomputable def twoMulLinearMap : K →ₗ[IntegerRing K] K where
  toFun z := (2 : IntegerRing K) • z
  map_add' x y := by simp
  map_smul' a x := by simp [smul_smul, mul_comm]

@[simp]
theorem twoMulLinearMap_apply (z : K) :
    twoMulLinearMap (K := K) z = (2 : IntegerRing K) • z :=
  rfl

/-- The dyadic relation `2 * sL ⊆ nL`, stated elementwise. -/
theorem two_smul_mem_normIdeal (q : QuadraticSpace K V) (L : Lattice K V) {z : K}
    (hz : z ∈ scaleIdeal q L) : (2 : IntegerRing K) • z ∈ normIdeal q L := by
  have hle : scaleIdeal q L ≤ (normIdeal q L).comap (twoMulLinearMap (K := K)) := by
    rw [scaleIdeal, Submodule.span_le]
    rintro _ ⟨p, rfl⟩
    change (2 : IntegerRing K) • q.bilin (p.1 : V) (p.2 : V) ∈ normIdeal q L
    have hxy := quadratic_mem_normIdeal q L (p.1 + p.2)
    have hx := quadratic_mem_normIdeal q L p.1
    have hy := quadratic_mem_normIdeal q L p.2
    have hdiff := (normIdeal q L).sub_mem ((normIdeal q L).sub_mem hxy hx) hy
    convert hdiff using 1
    change
      (2 : IntegerRing K) • q.bilin (p.1 : V) (p.2 : V) =
        q.quadratic ((p.1 : V) + (p.2 : V)) - q.quadratic (p.1 : V) -
          q.quadratic (p.2 : V)
    rw [q.quadratic_add]
    simp only [Algebra.smul_def, map_ofNat]
    ring
  exact hle hz

theorem scaleIdeal_mono (q : QuadraticSpace K V) {L M : Lattice K V} (hLM : L ≤ M) :
    scaleIdeal q L ≤ scaleIdeal q M := by
  rw [scaleIdeal, Submodule.span_le]
  rintro _ ⟨p, rfl⟩
  exact bilin_mem_scaleIdeal q M ⟨p.1, hLM p.1.property⟩ ⟨p.2, hLM p.2.property⟩

theorem normIdeal_mono (q : QuadraticSpace K V) {L M : Lattice K V} (hLM : L ≤ M) :
    normIdeal q L ≤ normIdeal q M := by
  rw [normIdeal, Submodule.span_le]
  rintro _ ⟨x, rfl⟩
  exact quadratic_mem_normIdeal q M ⟨x, hLM x.property⟩

/-!
### Norm ideals of lattice sums
-/

/--
The norm ideal of `L + M` is controlled by the two norm ideals and the mixed
pairings `2 B(L, M)`.
-/
theorem normIdeal_sup_le (q : QuadraticSpace K V) (L M : Lattice K V)
    (I : CoefficientIdeal (K := K))
    (hL : normIdeal q L ≤ I) (hM : normIdeal q M ≤ I)
    (hcross : ∀ x ∈ L, ∀ y ∈ M,
      (2 : IntegerRing K) • q.bilin x y ∈ I) :
    normIdeal q (sup L M) ≤ I := by
  rw [normIdeal, Submodule.span_le]
  rintro _ ⟨z, rfl⟩
  rcases (mem_sup_iff (L := L) (M := M) (z := (z : V))).mp z.property with
    ⟨x, hx, y, hy, hxy⟩
  change q.quadratic (z : V) ∈ I
  rw [← hxy, q.quadratic_add]
  apply I.add_mem (I.add_mem (hL (quadratic_mem_normIdeal_of_mem q L hx))
    (hM (quadratic_mem_normIdeal_of_mem q M hy)))
  simpa only [Algebra.smul_def, map_ofNat] using hcross x hx y hy

/--
If `nM ⊆ nL` and every mixed term `2 B(L, M)` lies in `nL`, then
`n(L + M) = nL`.
-/
theorem normIdeal_sup_eq_left (q : QuadraticSpace K V) (L M : Lattice K V)
    (hM : normIdeal q M ≤ normIdeal q L)
    (hcross : ∀ x ∈ L, ∀ y ∈ M,
      (2 : IntegerRing K) • q.bilin x y ∈ normIdeal q L) :
    normIdeal q (sup L M) = normIdeal q L := by
  apply le_antisymm
  · exact normIdeal_sup_le q L M (normIdeal q L) le_rfl hM hcross
  · exact normIdeal_mono q (le_sup_left L M)

/-- A vector whose quadratic value generates the norm ideal of the lattice. -/
noncomputable def IsNormGenerator (q : QuadraticSpace K V) (L : Lattice K V) (x : V) : Prop :=
  x ∈ L ∧ normIdeal q L = principalIdeal (K := K) (q.quadratic x)

theorem IsNormGenerator.mem {q : QuadraticSpace K V} {L : Lattice K V} {x : V}
    (hx : IsNormGenerator q L x) : x ∈ L :=
  hx.1

theorem IsNormGenerator.normIdeal_eq {q : QuadraticSpace K V} {L : Lattice K V} {x : V}
    (hx : IsNormGenerator q L x) :
    normIdeal q L = principalIdeal (K := K) (q.quadratic x) :=
  hx.2

/-- A norm generator remains one after adjoining a norm-controlled summand. -/
theorem IsNormGenerator.sup_right {q : QuadraticSpace K V} {L M : Lattice K V} {x : V}
    (generator : IsNormGenerator q L x)
    (hM : normIdeal q M ≤ normIdeal q L)
    (hcross : ∀ y ∈ L, ∀ z ∈ M,
      (2 : IntegerRing K) • q.bilin y z ∈ normIdeal q L) :
    IsNormGenerator q (sup L M) x := by
  constructor
  · exact le_sup_left L M generator.mem
  · exact (normIdeal_sup_eq_left q L M hM hcross).trans generator.normIdeal_eq

/-- Norm-integrality means `nL ⊆ 𝓞`. -/
noncomputable def IsNormIntegral (q : QuadraticSpace K V) (L : Lattice K V) : Prop :=
  normIdeal q L ≤ unitIdeal (K := K)

/-- Scale-integrality means `sL ⊆ 𝓞`. -/
noncomputable def IsScaleIntegral (q : QuadraticSpace K V) (L : Lattice K V) : Prop :=
  scaleIdeal q L ≤ unitIdeal (K := K)

theorem IsScaleIntegral.isNormIntegral {q : QuadraticSpace K V} {L : Lattice K V}
    (hL : IsScaleIntegral q L) : IsNormIntegral q L :=
  (normIdeal_le_scaleIdeal q L).trans hL

end Lattice

end Bong
