/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.BeliLemma319
import Bong.Lattice.DeterminantBasis
import Bong.Lattice.ModularCriterion
import Bong.Lattice.ModularSplitting
import Bong.Lattice.OrthogonalDecompositionDual
import Bong.Lattice.ScaleGenerator

/-!
# Unary and binary components at the minimal scale

This is the local construction in O'Meara, Section 91C.  A scale-generator
pair either contains a unary vector whose norm generates the scale, or its
two norms have strictly larger order.  In the latter case the pair has a
nonzero Gram determinant of the expected order and spans a binary modular
sublattice.
-/

namespace Bong

open Dyadic
open Module

namespace Lattice

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]

variable {q : QuadraticSpace K V} {L : Lattice K V} {x y : V}

/-- A quadratic sublattice generated by a field basis of a nondegenerate
subspace. -/
noncomputable def basisQuadraticSublattice
    (P : Submodule K V) (hP : (q.bilin.restrict P).Nondegenerate)
    {ι : Type*} [Finite ι] (b : Basis ι K P) :
    QuadraticSublattice q where
  carrier := P
  nondegenerate := hP
  lattice := basisLattice b

/-- If every vector of the chosen basis lies in the ambient lattice, then
the corresponding component lattice is an integral sublattice. -/
theorem basisQuadraticSublattice_ambientSubmodule_le
    (P : Submodule K V) (hP : (q.bilin.restrict P).Nondegenerate)
    {ι : Type*} [Finite ι] (b : Basis ι K P)
    (hb : ∀ i, (b i : V) ∈ L) :
    (basisQuadraticSublattice P hP b).ambientSubmodule ≤ L.toSubmodule := by
  classical
  change (Submodule.span (IntegerRing K) (Set.range b)).map
      ((Submodule.subtype P).restrictScalars (IntegerRing K)) ≤
    L.toSubmodule
  rintro z ⟨w, hw, rfl⟩
  refine Submodule.span_induction (R := IntegerRing K) (M := P)
    (s := Set.range b)
    (p := fun w _ => (w : V) ∈ L) ?_ ?_ ?_ ?_ hw
  · rintro _ ⟨i, rfl⟩
    exact hb i
  · exact L.zero_mem
  · intro a c _ _ ha hc
    simpa only [Submodule.coe_add] using L.add_mem ha hc
  · intro a w _ hw
    simpa only [Submodule.coe_smul_of_tower] using L.smul_mem a hw

/-- Passing to a quadratic sublattice contained in `L` cannot enlarge the
scale ideal. -/
theorem QuadraticSublattice.scaleIdeal_le_of_ambientSubmodule_le
    (C : QuadraticSublattice q)
    (hCL : C.ambientSubmodule ≤ L.toSubmodule) :
    scaleIdeal C.space C.lattice ≤ scaleIdeal q L := by
  rw [scaleIdeal, Submodule.span_le]
  rintro _ ⟨p, rfl⟩
  exact bilin_mem_scaleIdeal_of_mem q L
    (hCL ⟨p.1, p.1.property, rfl⟩)
    (hCL ⟨p.2, p.2.property, rfl⟩)

/-- Passing to a quadratic sublattice contained in `L` cannot enlarge the
norm ideal. -/
theorem QuadraticSublattice.normIdeal_le_of_ambientSubmodule_le
    (C : QuadraticSublattice q)
    (hCL : C.ambientSubmodule ≤ L.toSubmodule) :
    normIdeal C.space C.lattice ≤ normIdeal q L := by
  rw [normIdeal, Submodule.span_le]
  rintro _ ⟨x, rfl⟩
  change q.quadratic (x : V) ∈ normIdeal q L
  exact quadratic_mem_normIdeal_of_mem q L
    (hCL ⟨x, x.property, rfl⟩)

/-- Pairing containment on the generating field basis of a basis lattice
implies containment of its full scale ideal. -/
theorem scaleIdeal_basisLattice_le_of_basis
    {P : Type*} [AddCommGroup P] [Module K P]
    (r : QuadraticSpace K P) {I : Type*} [Finite I]
    (b : Basis I K P) (J : CoefficientIdeal (K := K))
    (hpair : ∀ i j, r.bilin (b i) (b j) ∈ J) :
    scaleIdeal r (basisLattice b) ≤ J := by
  classical
  rw [scaleIdeal, Submodule.span_le]
  rintro _ ⟨p, rfl⟩
  change r.bilin (p.1 : P) (p.2 : P) ∈ J
  refine Submodule.span_induction
    (p := fun z _ ↦ ∀ w, w ∈
      Submodule.span (IntegerRing K) (Set.range b) → r.bilin z w ∈ J)
      ?_ ?_ ?_ ?_ p.1.property (p.2 : P) p.2.property
  · rintro _ ⟨i, rfl⟩ w hw
    refine Submodule.span_induction
      (p := fun w _ ↦ r.bilin (b i) w ∈ J) ?_ ?_ ?_ ?_ hw
    · rintro _ ⟨j, rfl⟩
      exact hpair i j
    · simp
    · intro w z _ _ hw hz
      simpa only [LinearMap.BilinForm.add_right] using J.add_mem hw hz
    · intro a w _ hw
      have h := J.smul_mem a hw
      rw [← IsScalarTower.algebraMap_smul K a w,
        LinearMap.BilinForm.smul_right]
      simpa only [Algebra.smul_def] using h
  · simp
  · intro z w _ _ hz hw t ht
    simpa only [LinearMap.BilinForm.add_left] using J.add_mem (hz t ht) (hw t ht)
  · intro a z _ hz w hw
    have h := J.smul_mem a (hz w hw)
    rw [← IsScalarTower.algebraMap_smul K a z,
      LinearMap.BilinForm.smul_left]
    simpa only [Algebra.smul_def] using h

/-! ## Unary component -/

/-- The basis of the line generated by a nonzero vector. -/
noncomputable def unarySpanBasis (x : V) (hx : x ≠ 0) :
    Basis (Fin 1) K (K ∙ x) :=
  (Basis.singleton (Fin 1) K).map
    (LinearEquiv.toSpanNonzeroSingleton K V x hx)

@[simp]
theorem coe_unarySpanBasis (x : V) (hx : x ≠ 0) (i : Fin 1) :
    ((unarySpanBasis (K := K) x hx i : K ∙ x) : V) = x := by
  have hi : i = 0 := Subsingleton.elim i 0
  subst i
  simp [unarySpanBasis]

/-- An anisotropic line is nondegenerate. -/
theorem unarySpan_restrict_nondegenerate (hx : q.IsAnisotropic x) :
    (q.bilin.restrict (K ∙ x)).Nondegenerate := by
  let b := unarySpanBasis (K := K) x hx.ne_zero
  apply (LinearMap.BilinForm.nondegenerate_iff_det_ne_zero b).2
  rw [Matrix.det_fin_one]
  simp only [LinearMap.BilinForm.toMatrix_apply,
    LinearMap.BilinForm.restrict_apply, LinearMap.domRestrict_apply]
  simpa only [QuadraticSpace.IsAnisotropic, QuadraticSpace.quadratic,
    b, coe_unarySpanBasis] using hx

/-- The unary lattice `O x` as a quadratic sublattice. -/
noncomputable def unaryScaleComponent (x : V) (hx : q.IsAnisotropic x) :
    QuadraticSublattice q :=
  basisQuadraticSublattice (K ∙ x)
    (unarySpan_restrict_nondegenerate hx)
    (unarySpanBasis (K := K) x hx.ne_zero)

/-- The unary scale component is modular at `Q(x)`. -/
theorem unaryScaleComponent_isModular (hx : q.IsAnisotropic x) :
    IsModular (unaryScaleComponent (q := q) x hx).space
      (unaryScaleComponent (q := q) x hx).lattice
      (Units.mk0 (q.quadratic x) hx) := by
  let b := unarySpanBasis (K := K) x hx.ne_zero
  have horth : (q.bilin.restrict (K ∙ x)).iIsOrtho b := by
    rw [LinearMap.BilinForm.iIsOrtho_def]
    intro i j hij
    exact (hij (Subsingleton.elim i j)).elim
  have hne : ∀ i,
      (q.restrict (K ∙ x) (unarySpan_restrict_nondegenerate hx)).quadratic
        (b i) ≠ 0 := by
    intro i
    simpa only [QuadraticSpace.IsAnisotropic, QuadraticSpace.quadratic,
      QuadraticSpace.restrict,
      LinearMap.BilinForm.restrict_apply, LinearMap.domRestrict_apply,
      b, coe_unarySpanBasis] using hx
  refine isModular_basisLattice_of_iIsOrtho_of_orders_eq
    (q.restrict (K ∙ x) (unarySpan_restrict_nondegenerate hx))
    b horth hne (Units.mk0 (q.quadratic x) hx) ?_
  intro i
  have hi : i = 0 := Subsingleton.elim i 0
  subst i
  congr 2
  simp only [QuadraticSpace.quadratic, QuadraticSpace.restrict,
    LinearMap.BilinForm.restrict_apply, LinearMap.domRestrict_apply,
    b, coe_unarySpanBasis]

/-- If `x` lies in `L`, the unary component generated by it is contained in
`L`. -/
theorem unaryScaleComponent_ambientSubmodule_le
    (hx : q.IsAnisotropic x) (hxL : x ∈ L) :
    (unaryScaleComponent (q := q) x hx).ambientSubmodule ≤ L.toSubmodule := by
  apply basisQuadraticSublattice_ambientSubmodule_le
  intro i
  simpa only [coe_unarySpanBasis] using hxL

/-- The principle of domination for the Gram determinant in O'Meara 91C. -/
theorem ord_binaryGramDeterminant_eq
    (hxy : q.bilin x y ≠ 0)
    (hx : ord K (q.bilin x y) < ord K (q.quadratic x))
    (hy : ord K (q.bilin x y) < ord K (q.quadratic y)) :
    ord K (q.quadratic x * q.quadratic y - q.bilin x y ^ 2) =
      ord K (q.bilin x y ^ 2) := by
  by_cases hqx : q.quadratic x = 0
  · rw [hqx, zero_mul, zero_sub, ord_neg]
  · by_cases hqy : q.quadratic y = 0
    · rw [hqy, mul_zero, zero_sub, ord_neg]
    · let d := Units.mk0 (q.bilin x y) hxy
      let ax := Units.mk0 (q.quadratic x) hqx
      let ay := Units.mk0 (q.quadratic y) hqy
      have hxInt : ordUnit K d < ordUnit K ax := by
        apply WithTop.coe_lt_coe.mp
        simpa [d, ax] using hx
      have hyInt : ordUnit K d < ordUnit K ay := by
        apply WithTop.coe_lt_coe.mp
        simpa [d, ay] using hy
      apply (ord K).map_sub_eq_of_lt_right
      rw [ord_mul, ord_pow]
      change 2 • ord K (d : K) < ord K (ax : K) + ord K (ay : K)
      rw [← coe_ordUnit K ax, ← coe_ordUnit K ay,
        ← coe_ordUnit K d]
      have hsum :
          ((ordUnit K d + ordUnit K d : Int) : WithTop Int) <
            ((ordUnit K ax + ordUnit K ay : Int) : WithTop Int) :=
        WithTop.coe_lt_coe.mpr (add_lt_add hxInt hyInt)
      simpa only [two_nsmul, WithTop.coe_add] using hsum

/-- Under the strict norm inequalities, the binary Gram determinant is
nonzero. -/
theorem binaryGramDeterminant_ne_zero
    (hxy : q.bilin x y ≠ 0)
    (hx : ord K (q.bilin x y) < ord K (q.quadratic x))
    (hy : ord K (q.bilin x y) < ord K (q.quadratic y)) :
    q.quadratic x * q.quadratic y - q.bilin x y ^ 2 ≠ 0 := by
  intro hzero
  have hord := ord_binaryGramDeterminant_eq hxy hx hy
  rw [hzero, ord_zero] at hord
  have hpow : q.bilin x y ^ 2 ≠ 0 := pow_ne_zero 2 hxy
  exact (ord_eq_top_iff K).not.mpr hpow hord.symm

/-- The two vectors in the binary branch of O'Meara 91C are linearly
independent. -/
theorem binaryPair_linearIndependent_of_strict_norm_orders
    (hxy : q.bilin x y ≠ 0)
    (hx : ord K (q.bilin x y) < ord K (q.quadratic x))
    (hy : ord K (q.bilin x y) < ord K (q.quadratic y)) :
    LinearIndependent K (BONG.binaryPairFamily x y) := by
  have hdet := binaryGramDeterminant_ne_zero hxy hx hy
  rw [linearIndependent_fin2]
  constructor
  · intro hyzero
    change y = 0 at hyzero
    apply hxy
    rw [hyzero]
    simp
  · intro a haxy
    change a • y = x at haxy
    apply hdet
    rw [← haxy, q.quadratic_smul,
      LinearMap.BilinForm.smul_left]
    simp [QuadraticSpace.quadratic]
    ring

/-- The restriction of the quadratic form to the strict binary pair is
nondegenerate. -/
theorem binaryPair_restrict_nondegenerate
    (hxy : q.bilin x y ≠ 0)
    (hx : ord K (q.bilin x y) < ord K (q.quadratic x))
    (hy : ord K (q.bilin x y) < ord K (q.quadratic y)) :
    (q.bilin.restrict (BONG.binaryPairSpan (K := K) x y)).Nondegenerate := by
  let hli := binaryPair_linearIndependent_of_strict_norm_orders hxy hx hy
  let b := BONG.binaryPairBasis (K := K) x y hli
  apply (LinearMap.BilinForm.nondegenerate_iff_det_ne_zero b).2
  rw [Matrix.det_fin_two]
  simp only [LinearMap.BilinForm.toMatrix_apply,
    LinearMap.BilinForm.restrict_apply, LinearMap.domRestrict_apply]
  simp only [b, BONG.coe_binaryPairBasis,
    BONG.binaryPairFamily_zero, BONG.binaryPairFamily_one]
  change q.quadratic x * q.quadratic y -
      q.bilin x y * q.bilin y x ≠ 0
  rw [q.isSymm.eq y x]
  simpa [pow_two] using binaryGramDeterminant_ne_zero hxy hx hy

/-- The binary basis lattice has the determinant order forced by its mixed
pairing.  This is the volume calculation in O'Meara 91C. -/
theorem volumeOrder_binaryPairBasis_eq_two_mul_ordUnit
    (hxy : q.bilin x y ≠ 0)
    (hx : ord K (q.bilin x y) < ord K (q.quadratic x))
    (hy : ord K (q.bilin x y) < ord K (q.quadratic y)) :
    volumeOrder
        (q.restrict (BONG.binaryPairSpan (K := K) x y)
          (binaryPair_restrict_nondegenerate hxy hx hy))
        (basisLattice
          (BONG.binaryPairBasis (K := K) x y
            (binaryPair_linearIndependent_of_strict_norm_orders hxy hx hy))) =
      2 * ordUnit K (Units.mk0 (q.bilin x y) hxy) := by
  let P := BONG.binaryPairSpan (K := K) x y
  let hli := binaryPair_linearIndependent_of_strict_norm_orders hxy hx hy
  let hnondeg := binaryPair_restrict_nondegenerate hxy hx hy
  let b : Basis (Fin 2) K P := BONG.binaryPairBasis (K := K) x y hli
  have hfin : finrank K P = 2 := by
    simpa using Module.finrank_eq_card_basis b
  let e : Fin 2 ≃ Fin (finrank K P) := finCongr hfin.symm
  let bfin : Basis (Fin (finrank K P)) K P := b.reindex e
  have hbfin : basisLattice bfin = basisLattice b :=
    basisLattice_reindex b e
  have hmatrix :
      LinearMap.BilinForm.toMatrix bfin (q.bilin.restrict P) =
        Matrix.reindex e e
          (LinearMap.BilinForm.toMatrix b (q.bilin.restrict P)) := by
    ext i j
    simp only [LinearMap.BilinForm.toMatrix_apply, Matrix.reindex_apply,
      Matrix.submatrix_apply, bfin, Basis.coe_reindex, Function.comp_apply]
  have hdet :
      basisGramDeterminant (q.restrict P hnondeg) bfin =
        q.quadratic x * q.quadratic y - q.bilin x y ^ 2 := by
    change (LinearMap.BilinForm.toMatrix bfin (q.bilin.restrict P)).det = _
    rw [hmatrix, Matrix.det_reindex_self, Matrix.det_fin_two]
    simp only [LinearMap.BilinForm.toMatrix_apply,
      LinearMap.BilinForm.restrict_apply, LinearMap.domRestrict_apply]
    change q.bilin (b 0 : V) (b 0 : V) *
        q.bilin (b 1 : V) (b 1 : V) -
      q.bilin (b 0 : V) (b 1 : V) *
        q.bilin (b 1 : V) (b 0 : V) = _
    rw [show (b 0 : V) = x by
        rw [show (b 0 : V) = BONG.binaryPairFamily x y 0 by
          exact BONG.coe_binaryPairBasis x y hli 0]
        exact BONG.binaryPairFamily_zero x y,
      show (b 1 : V) = y by
        rw [show (b 1 : V) = BONG.binaryPairFamily x y 1 by
          exact BONG.coe_binaryPairBasis x y hli 1]
        exact BONG.binaryPairFamily_one x y]
    change q.quadratic x * q.quadratic y -
      q.bilin x y * q.bilin y x = _
    rw [q.isSymm.eq y x, pow_two]
  apply WithTop.coe_injective
  rw [show basisLattice
      (BONG.binaryPairBasis (K := K) x y
        (binaryPair_linearIndependent_of_strict_norm_orders hxy hx hy)) =
      basisLattice bfin by exact hbfin.symm]
  rw [coe_volumeOrder_basisLattice_eq_ord_basisGramDeterminant, hdet,
    ord_binaryGramDeterminant_eq hxy hx hy, ord_pow]
  have hcoe := coe_ordUnit K (Units.mk0 (q.bilin x y) hxy)
  change (((ordUnit K (Units.mk0 (q.bilin x y) hxy) : Int) :
      WithTop Int)) = ord K (q.bilin x y) at hcoe
  rw [← hcoe, two_nsmul]
  rw [show (2 * ordUnit K (Units.mk0 (q.bilin x y) hxy) : Int) =
      ordUnit K (Units.mk0 (q.bilin x y) hxy) +
        ordUnit K (Units.mk0 (q.bilin x y) hxy) by omega,
    WithTop.coe_add]

/-- The binary lattice generated by a strict scale pair. -/
noncomputable def binaryScaleComponent
    (hxy : q.bilin x y ≠ 0)
    (hx : ord K (q.bilin x y) < ord K (q.quadratic x))
    (hy : ord K (q.bilin x y) < ord K (q.quadratic y)) :
    QuadraticSublattice q :=
  basisQuadraticSublattice (BONG.binaryPairSpan (K := K) x y)
    (binaryPair_restrict_nondegenerate hxy hx hy)
    (BONG.binaryPairBasis (K := K) x y
      (binaryPair_linearIndependent_of_strict_norm_orders hxy hx hy))

/-- A binary component generated by two vectors of `L` is contained in `L`. -/
theorem binaryScaleComponent_ambientSubmodule_le
    (hxy : q.bilin x y ≠ 0)
    (hx : ord K (q.bilin x y) < ord K (q.quadratic x))
    (hy : ord K (q.bilin x y) < ord K (q.quadratic y))
    (hxL : x ∈ L) (hyL : y ∈ L) :
    (binaryScaleComponent (q := q) hxy hx hy).ambientSubmodule ≤
      L.toSubmodule := by
  apply basisQuadraticSublattice_ambientSubmodule_le
  intro i
  rw [BONG.coe_binaryPairBasis]
  fin_cases i
  · exact hxL
  · exact hyL

/-- If no norm of a lattice vector generates the scale, each vector in a
scale-generator pair has norm of strictly larger order. -/
theorem IsScaleGenerator.ord_bilin_lt_quadratic_of_no_unary
    (hgen : IsScaleGenerator q L x y) (hxy : q.bilin x y ≠ 0)
    (hnot : ∀ z : V, z ∈ L →
      principalIdeal (K := K) (q.quadratic z) ≠ scaleIdeal q L) :
    ord K (q.bilin x y) < ord K (q.quadratic x) := by
  have hmem : q.quadratic x ∈
      principalIdeal (K := K) (q.bilin x y) := by
    rw [← hgen.scaleIdeal_eq]
    exact bilin_mem_scaleIdeal_of_mem q L hgen.mem_left hgen.mem_left
  have hle := ord_le_of_mem_principalIdeal hxy hmem
  apply lt_of_le_of_ne hle
  intro heq
  apply hnot x hgen.mem_left
  apply le_antisymm
  · rw [hgen.scaleIdeal_eq]
    exact (principalIdeal_le_iff_ord_ge
      (show q.quadratic x ≠ 0 by
        intro hzero
        rw [hzero, ord_zero] at heq
        exact hxy ((ord_eq_top_iff K).mp heq))
      hxy).2 heq.le
  · rw [hgen.scaleIdeal_eq]
    exact (principalIdeal_le_iff_ord_ge hxy
      (show q.quadratic x ≠ 0 by
        intro hzero
        rw [hzero, ord_zero] at heq
        exact hxy ((ord_eq_top_iff K).mp heq))).2 heq.ge

/-- Symmetric form of the strict norm conclusion for the second vector. -/
theorem IsScaleGenerator.ord_bilin_lt_quadratic_right_of_no_unary
    (hgen : IsScaleGenerator q L x y) (hxy : q.bilin x y ≠ 0)
    (hnot : ∀ z : V, z ∈ L →
      principalIdeal (K := K) (q.quadratic z) ≠ scaleIdeal q L) :
    ord K (q.bilin x y) < ord K (q.quadratic y) := by
  have hgen' : IsScaleGenerator q L y x := by
    refine ⟨hgen.mem_right, hgen.mem_left, ?_⟩
    simpa only [q.isSymm.eq y x] using hgen.scaleIdeal_eq
  have hyx : q.bilin y x ≠ 0 := by
    simpa only [q.isSymm.eq y x] using hxy
  simpa only [q.isSymm.eq y x] using
    hgen'.ord_bilin_lt_quadratic_of_no_unary hyx hnot

/-- The strict binary component has scale contained in the principal ideal
generated by its mixed pairing. -/
theorem binaryScaleComponent_scaleIdeal_le
    (hxy : q.bilin x y ≠ 0)
    (hx : ord K (q.bilin x y) < ord K (q.quadratic x))
    (hy : ord K (q.bilin x y) < ord K (q.quadratic y)) :
    scaleIdeal (binaryScaleComponent (q := q) hxy hx hy).space
        (binaryScaleComponent (q := q) hxy hx hy).lattice ≤
      principalIdeal (K := K) (q.bilin x y) := by
  let hli := binaryPair_linearIndependent_of_strict_norm_orders hxy hx hy
  let b := BONG.binaryPairBasis (K := K) x y hli
  change scaleIdeal
      (q.restrict (BONG.binaryPairSpan (K := K) x y)
        (binaryPair_restrict_nondegenerate hxy hx hy))
      (basisLattice b) ≤ _
  apply scaleIdeal_basisLattice_le_of_basis _ b
    (principalIdeal (K := K) (q.bilin x y))
  intro i j
  change q.bilin (b i : V) (b j : V) ∈
    principalIdeal (K := K) (q.bilin x y)
  rw [show (b i : V) = BONG.binaryPairFamily x y i by
      exact BONG.coe_binaryPairBasis x y hli i,
    show (b j : V) = BONG.binaryPairFamily x y j by
      exact BONG.coe_binaryPairBasis x y hli j]
  have hi : i = 0 ∨ i = 1 := by
    have hval : i.val = 0 ∨ i.val = 1 := by omega
    rcases hval with hval | hval
    · exact Or.inl (Fin.ext hval)
    · exact Or.inr (Fin.ext hval)
  have hj : j = 0 ∨ j = 1 := by
    have hval : j.val = 0 ∨ j.val = 1 := by omega
    rcases hval with hval | hval
    · exact Or.inl (Fin.ext hval)
    · exact Or.inr (Fin.ext hval)
  rcases hi with rfl | rfl <;> rcases hj with rfl | rfl
  all_goals simp only [BONG.binaryPairFamily_zero, BONG.binaryPairFamily_one]
  · change q.quadratic x ∈ principalIdeal (K := K) (q.bilin x y)
    exact mem_principalIdeal_of_ord_le hxy hx.le
  · exact generator_mem_principalIdeal (q.bilin x y)
  · rw [q.isSymm.eq y x]
    exact generator_mem_principalIdeal (q.bilin x y)
  · change q.quadratic y ∈ principalIdeal (K := K) (q.bilin x y)
    exact mem_principalIdeal_of_ord_le hxy hy.le

/-- The strict binary component in O'Meara 91C is modular at the mixed
pairing which generates the ambient scale. -/
theorem binaryScaleComponent_isModular
    (hxy : q.bilin x y ≠ 0)
    (hx : ord K (q.bilin x y) < ord K (q.quadratic x))
    (hy : ord K (q.bilin x y) < ord K (q.quadratic y)) :
    IsModular (binaryScaleComponent (q := q) hxy hx hy).space
      (binaryScaleComponent (q := q) hxy hx hy).lattice
      (Units.mk0 (q.bilin x y) hxy) := by
  apply isModular_of_scaleIdeal_le_of_volumeOrder_eq
  · exact binaryScaleComponent_scaleIdeal_le hxy hx hy
  · change volumeOrder
        (q.restrict (BONG.binaryPairSpan (K := K) x y)
          (binaryPair_restrict_nondegenerate hxy hx hy))
        (basisLattice
          (BONG.binaryPairBasis (K := K) x y
            (binaryPair_linearIndependent_of_strict_norm_orders hxy hx hy))) = _
    rw [volumeOrder_binaryPairBasis_eq_two_mul_ordUnit hxy hx hy]
    have hfin : finrank K (BONG.binaryPairSpan (K := K) x y) = 2 := by
      simpa using Module.finrank_eq_card_basis
        (BONG.binaryPairBasis (K := K) x y
          (binaryPair_linearIndependent_of_strict_norm_orders hxy hx hy))
    change 2 * ordUnit K (Units.mk0 (q.bilin x y) hxy) =
      (finrank K (BONG.binaryPairSpan (K := K) x y) : Int) *
        ordUnit K (Units.mk0 (q.bilin x y) hxy)
    rw [hfin]
    norm_num

/-- Data for the first unary or binary modular summand extracted in
O'Meara's proof of Jordan splitting. -/
structure MinimalScaleComponentData
    (q : QuadraticSpace K V) (L : Lattice K V) where
  component : QuadraticSublattice q
  scaleGenerator : Kˣ
  rank_one_or_two : finrank K component.carrier = 1 ∨
    finrank K component.carrier = 2
  contained : component.ambientSubmodule ≤ L.toSubmodule
  modular : IsModular component.space component.lattice scaleGenerator
  ambientScale_le : scaleIdeal q L ≤
    principalIdeal (K := K) (scaleGenerator : K)
  splitting : OrthogonalDecomposition q L 2

/-- O'Meara 91C: every positive-dimensional lattice has a unary or binary
minimal-scale modular summand, and O'Meara 82:15a splits it off. -/
noncomputable def minimalScaleComponentDataOfScaleGenerator
    [FiniteDimensional K V]
    (hgen : IsScaleGenerator q L x y) (hxy : q.bilin x y ≠ 0) :
    MinimalScaleComponentData q L := by
  by_cases hunary : ∃ z : V, z ∈ L ∧
      principalIdeal (K := K) (q.quadratic z) = scaleIdeal q L
  · let z := Classical.choose hunary
    have hzL : z ∈ L := (Classical.choose_spec hunary).1
    have hzscale : principalIdeal (K := K) (q.quadratic z) =
        scaleIdeal q L := (Classical.choose_spec hunary).2
    have hz : q.IsAnisotropic z := by
      intro hzq
      have hzero : principalIdeal (K := K) (q.quadratic z) = ⊥ := by
        rw [hzq, principalIdeal]
        simp
      have hpair : q.bilin x y ∈ scaleIdeal q L :=
        bilin_mem_scaleIdeal_of_mem q L hgen.mem_left hgen.mem_right
      rw [← hzscale, hzero] at hpair
      exact hxy hpair
    let C := unaryScaleComponent (q := q) z hz
    let a := Units.mk0 (q.quadratic z) hz
    have hcontained : C.ambientSubmodule ≤ L.toSubmodule :=
      unaryScaleComponent_ambientSubmodule_le hz hzL
    have hmodular : IsModular C.space C.lattice a :=
      unaryScaleComponent_isModular hz
    have hscale : scaleIdeal q L ≤ principalIdeal (K := K) (a : K) := by
      change scaleIdeal q L ≤ principalIdeal (K := K) (q.quadratic z)
      rw [← hzscale]
    exact {
      component := C
      scaleGenerator := a
      rank_one_or_two := Or.inl (by
        change finrank K (K ∙ z) = 1
        simpa using Module.finrank_eq_card_basis
          (unarySpanBasis (K := K) z hz.ne_zero))
      contained := hcontained
      modular := hmodular
      ambientScale_le := hscale
      splitting := omearaModularSplittingOfScaleIdealLe C hcontained
        hmodular hscale }
  · push Not at hunary
    have hx := hgen.ord_bilin_lt_quadratic_of_no_unary hxy hunary
    have hy := hgen.ord_bilin_lt_quadratic_right_of_no_unary hxy hunary
    let C := binaryScaleComponent (q := q) hxy hx hy
    let a := Units.mk0 (q.bilin x y) hxy
    have hcontained : C.ambientSubmodule ≤ L.toSubmodule :=
      binaryScaleComponent_ambientSubmodule_le hxy hx hy
        hgen.mem_left hgen.mem_right
    have hmodular : IsModular C.space C.lattice a :=
      binaryScaleComponent_isModular hxy hx hy
    have hscale : scaleIdeal q L ≤ principalIdeal (K := K) (a : K) := by
      change scaleIdeal q L ≤ principalIdeal (K := K) (q.bilin x y)
      exact le_of_eq hgen.scaleIdeal_eq
    exact {
      component := C
      scaleGenerator := a
      rank_one_or_two := Or.inr (by
        change finrank K (BONG.binaryPairSpan (K := K) x y) = 2
        simpa using Module.finrank_eq_card_basis
          (BONG.binaryPairBasis (K := K) x y
            (binaryPair_linearIndependent_of_strict_norm_orders hxy hx hy)))
      contained := hcontained
      modular := hmodular
      ambientScale_le := hscale
      splitting := omearaModularSplittingOfScaleIdealLe C hcontained
        hmodular hscale }

end Lattice

end Bong
