/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.Modular

/-!
# The scale ideal of a modular lattice

For a positive-rank `a`-modular lattice, the scale ideal is exactly the
principal ideal generated by `a`.  The reverse inclusion is witnessed by
pairing an integral basis vector with the corresponding bilinear dual vector.
-/

namespace Bong

open Dyadic
open Module

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]

namespace Lattice

/-- Every pairing of an `a`-modular lattice is divisible by `a`. -/
theorem IsModular.scaleIdeal_le_principal
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (hmodular : IsModular q L a) :
    scaleIdeal q L ≤ principalIdeal (K := K) (a : K) := by
  rw [scaleIdeal, Submodule.span_le]
  rintro _ ⟨p, rfl⟩
  change q.bilin (p.1 : V) (p.2 : V) ∈
    principalIdeal (K := K) (a : K)
  have hdual :
      ((a⁻¹ : Kˣ) : K) • (p.1 : V) ∈ dualLattice q L := by
    rw [hmodular]
    exact smul_mem_rescale a⁻¹ L p.1.property
  rw [mem_dualLattice_iff] at hdual
  have hpair := hdual p.2 p.2.property
  let c : IntegerRing K :=
    ⟨((a⁻¹ : Kˣ) : K) * q.bilin (p.1 : V) (p.2 : V), by
      simpa only [LinearMap.BilinForm.smul_left] using hpair⟩
  rw [principalIdeal, Submodule.mem_span_singleton]
  refine ⟨c, ?_⟩
  change (c : K) * (a : K) = q.bilin (p.1 : V) (p.2 : V)
  dsimp [c]
  simp [mul_comm]

/-- A positive-rank `a`-modular lattice has scale ideal `(a)`. -/
theorem IsModular.scaleIdeal_eq_principal
    {q : QuadraticSpace K V} {L : Lattice K V} {a : Kˣ}
    (hmodular : IsModular q L a)
    (hfin : 0 < finrank K V) :
    scaleIdeal q L = principalIdeal (K := K) (a : K) := by
  apply le_antisymm hmodular.scaleIdeal_le_principal
  rw [principalIdeal, Submodule.span_le]
  rintro _ ha
  rw [Set.mem_singleton_iff] at ha
  subst ha
  let i : Fin (finrank K V) := ⟨0, hfin⟩
  let basis := L.standardAmbientBasis
  let dualBasis := q.bilin.dualBasis q.nondegenerate basis
  have hdualMem : dualBasis i ∈ dualLattice q L := by
    change dualBasis i ∈ dualSubmodule q L.toSubmodule
    rw [L.toSubmodule_eq_span_standardAmbientBasis,
      dualSubmodule_eq_bilinDualSubmodule]
    change dualBasis i ∈
      q.bilin.dualSubmodule
        (Submodule.span (IntegerRing K) (Set.range basis))
    rw [q.bilin.dualSubmodule_span_of_basis q.nondegenerate basis]
    exact Submodule.subset_span ⟨i, rfl⟩
  rw [hmodular, mem_rescale_iff] at hdualMem
  rcases hdualMem with ⟨y, hy, hiy⟩
  have hdualPair : q.bilin (dualBasis i) (basis i) = 1 := by
    dsimp [dualBasis]
    rw [LinearMap.BilinForm.apply_dualBasis_left]
    simp
  have hinvPair :
      ((a⁻¹ : Kˣ) : K) * q.bilin y (basis i) = 1 := by
    rw [← hiy] at hdualPair
    simpa only [LinearMap.BilinForm.smul_left] using hdualPair
  have hpair : q.bilin y (basis i) = (a : K) := by
    apply mul_left_cancel₀ (Units.ne_zero a⁻¹)
    rw [hinvPair]
    simp
  rw [← hpair]
  apply bilin_mem_scaleIdeal_of_mem q L hy
  change basis i ∈ L.toSubmodule
  dsimp [basis]
  simpa only [coe_standardIntegralBasis_apply] using
    (L.standardIntegralBasis i).property

end Lattice

end Bong
