/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.Modular
import Bong.Lattice.NormGeneratorValues

/-!
# Norm generators under lattice rescaling

If `x` generates the norm ideal of `L`, then `c x` generates the norm ideal
of `cL`.  For a modular lattice this immediately supplies a norm generator of
the integral dual.
-/

namespace Bong

open Dyadic

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]

namespace Lattice

/-- A norm generator scales together with its lattice. -/
theorem IsNormGenerator.rescale {q : QuadraticSpace K V}
    {L : Lattice K V} {x : V} (generator : IsNormGenerator q L x)
    (c : Kˣ) :
    IsNormGenerator q (rescale c L) ((c : K) • x) := by
  constructor
  · exact smul_mem_rescale c L generator.mem
  · apply le_antisymm
    · rw [normIdeal, Submodule.span_le]
      rintro _ ⟨y, rfl⟩
      have hy : (y : V) ∈ Lattice.rescale c L := y.property
      rw [mem_rescale_iff] at hy
      rcases hy with ⟨z, hz, hcz⟩
      have hzq := quadratic_mem_normIdeal_of_mem q L hz
      rw [generator.normIdeal_eq, principalIdeal,
        Submodule.mem_span_singleton] at hzq
      rcases hzq with ⟨d, hd⟩
      apply Submodule.mem_span_singleton.mpr
      refine ⟨d, ?_⟩
      change d • q.quadratic ((c : K) • x) = q.quadratic (y : V)
      rw [← hcz, q.quadratic_smul, q.quadratic_smul]
      have hd' : (d : K) * q.quadratic x = q.quadratic z := by
        simpa [Algebra.smul_def] using hd
      change (d : K) * ((c : K) ^ 2 * q.quadratic x) =
        (c : K) ^ 2 * q.quadratic z
      rw [← hd']
      ring
    · rw [principalIdeal, Submodule.span_le]
      rintro _ hy
      rw [Set.mem_singleton_iff] at hy
      subst hy
      exact quadratic_mem_normIdeal_of_mem q (Lattice.rescale c L)
        (smul_mem_rescale c L generator.mem)

/-- If the norm ideal of a positive-rank lattice is generated by `n`, then
rescaling the lattice by `c` multiplies that generator by `c^2`.  This
version depends only on the principal ideal, not on a preselected generating
vector. -/
theorem normIdeal_rescale_eq_principal_of_finrank_pos
    {q : QuadraticSpace K V} {L : Lattice K V}
    (hpos : 0 < Module.finrank K V) (c n : Kˣ)
    (hn : normIdeal q L = principalIdeal (K := K) (n : K)) :
    normIdeal q (rescale c L) =
      principalIdeal (K := K) ((c ^ 2 * n : Kˣ) : K) := by
  obtain ⟨x, hx, hxAnisotropic⟩ :=
    exists_isNormGenerator_of_finrank_pos q L hpos
  let d : Kˣ := Units.mk0 (q.quadratic x) hxAnisotropic
  have hd : normIdeal q L = principalIdeal (K := K) (d : K) :=
    hx.normIdeal_eq
  have hdn : Dyadic.ordUnit K d = Dyadic.ordUnit K n :=
    (principalIdeal_eq_iff_ordUnit_eq d n).mp (hd.symm.trans hn)
  have hxScaled := hx.rescale c
  have hxScaledAnisotropic : q.IsAnisotropic ((c : K) • x) := by
    intro hzero
    rw [q.quadratic_smul] at hzero
    exact hxAnisotropic (mul_eq_zero.mp hzero |>.resolve_left
      (pow_ne_zero 2 (Units.ne_zero c)))
  let e : Kˣ := Units.mk0
    (q.quadratic ((c : K) • x)) hxScaledAnisotropic
  have he : normIdeal q (rescale c L) =
      principalIdeal (K := K) (e : K) :=
    hxScaled.normIdeal_eq
  have heq : e = c ^ 2 * d := by
    apply Units.ext
    change q.quadratic ((c : K) • x) =
      (c : K) ^ 2 * q.quadratic x
    exact q.quadratic_smul (c : K) x
  rw [he, heq]
  apply (principalIdeal_eq_iff_ordUnit_eq _ _).2
  simp only [Dyadic.ordUnit_mul, Dyadic.ordUnit_pow, hdn]

/-- In an `a`-modular lattice, scaling a norm generator by `a⁻¹` gives a
norm generator of the integral dual. -/
theorem IsModular.normGenerator_dual {q : QuadraticSpace K V}
    {L : Lattice K V} {a : Kˣ} (hmodular : IsModular q L a)
    {x : V} (generator : IsNormGenerator q L x) :
    IsNormGenerator q (dualLattice q L) ((a⁻¹ : Kˣ) • x) := by
  have hscaled := generator.rescale a⁻¹
  exact Eq.mpr
    (congrArg
      (fun M => IsNormGenerator q M (((a⁻¹ : Kˣ) : K) • x))
      hmodular)
    hscaled

end Lattice

end Bong
