/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.Determinant
import Mathlib.Data.Finset.Max

/-!
# Existence of norm generators

The norm ideal is generated by the quadratic values of the vectors in a fixed
integral basis and their pairwise sums.  Since this is a finite family in a
discretely valued field, a nonzero value of smallest order generates the whole
norm ideal.
-/

namespace Bong

open Dyadic

namespace Lattice

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]

/-- Finite quadratic values sufficient to generate the norm ideal. -/
noncomputable def normValueCandidates (q : QuadraticSpace K V)
    (L : Lattice K V) : Finset K := by
  classical
  exact
    (Finset.univ.image fun i => q.quadratic (L.standardAmbientBasis i)) ∪
      ((Finset.univ.product Finset.univ).image fun ij =>
        q.quadratic
          (L.standardAmbientBasis ij.1 + L.standardAmbientBasis ij.2))

private theorem standardAmbientBasis_mem (L : Lattice K V)
    (i : Fin (Module.finrank K V)) : L.standardAmbientBasis i ∈ L := by
  change L.standardAmbientBasis i ∈ L.toSubmodule
  rw [← L.coe_standardIntegralBasis_apply i]
  exact (L.standardIntegralBasis i).property

private theorem quadratic_basis_mem_candidateSpan
    (q : QuadraticSpace K V) (L : Lattice K V)
    (i : Fin (Module.finrank K V)) :
    q.quadratic (L.standardAmbientBasis i) ∈
      Submodule.span (IntegerRing K) (normValueCandidates q L : Set K) := by
  apply Submodule.subset_span
  simp [normValueCandidates]

private theorem quadratic_basis_add_mem_candidateSpan
    (q : QuadraticSpace K V) (L : Lattice K V)
    (i j : Fin (Module.finrank K V)) :
    q.quadratic
        (L.standardAmbientBasis i + L.standardAmbientBasis j) ∈
      Submodule.span (IntegerRing K) (normValueCandidates q L : Set K) := by
  apply Submodule.subset_span
  simp [normValueCandidates]

private theorem two_bilin_basis_mem_candidateSpan
    (q : QuadraticSpace K V) (L : Lattice K V)
    (i j : Fin (Module.finrank K V)) :
    (2 : IntegerRing K) •
        q.bilin (L.standardAmbientBasis i) (L.standardAmbientBasis j) ∈
      Submodule.span (IntegerRing K) (normValueCandidates q L : Set K) := by
  let I := Submodule.span (IntegerRing K) (normValueCandidates q L : Set K)
  have hi : q.quadratic (L.standardAmbientBasis i) ∈ I :=
    quadratic_basis_mem_candidateSpan q L i
  have hj : q.quadratic (L.standardAmbientBasis j) ∈ I :=
    quadratic_basis_mem_candidateSpan q L j
  have hij : q.quadratic
      (L.standardAmbientBasis i + L.standardAmbientBasis j) ∈ I :=
    quadratic_basis_add_mem_candidateSpan q L i j
  have hdiff := I.sub_mem (I.sub_mem hij hi) hj
  convert hdiff using 1
  rw [q.quadratic_add]
  simp only [Algebra.smul_def, map_ofNat]
  ring

private theorem two_bilin_mem_candidateSpan_of_mem_span
    (q : QuadraticSpace K V) (L : Lattice K V) (y z : V)
    (hy : y ∈ Submodule.span (IntegerRing K)
      (Set.range L.standardAmbientBasis))
    (hz : z ∈ Submodule.span (IntegerRing K)
      (Set.range L.standardAmbientBasis)) :
    (2 : IntegerRing K) • q.bilin y z ∈
      Submodule.span (IntegerRing K) (normValueCandidates q L : Set K) := by
  let S : Set V := Set.range L.standardAmbientBasis
  let I := Submodule.span (IntegerRing K) (normValueCandidates q L : Set K)
  refine Submodule.span_induction
    (p := fun y _ => ∀ z, z ∈ Submodule.span (IntegerRing K) S →
      (2 : IntegerRing K) • q.bilin y z ∈ I) ?_ ?_ ?_ ?_ hy z hz
  · rintro _ ⟨i, rfl⟩
    intro z hz
    refine Submodule.span_induction
      (p := fun z _ => (2 : IntegerRing K) •
        q.bilin (L.standardAmbientBasis i) z ∈ I) ?_ ?_ ?_ ?_ hz
    · rintro _ ⟨j, rfl⟩
      exact two_bilin_basis_mem_candidateSpan q L i j
    · simp
    · intro z w _ _ hz hw
      simpa only [LinearMap.BilinForm.add_right, smul_add] using I.add_mem hz hw
    · intro a z _ hz
      have h := I.smul_mem a hz
      rw [← IsScalarTower.algebraMap_smul K a z,
        LinearMap.BilinForm.smul_right]
      convert h using 1
      simp only [Algebra.smul_def, map_ofNat]
      ring
  · intro z _
    simp
  · intro y w _ _ hy hw z hz
    simpa only [LinearMap.BilinForm.add_left, smul_add] using
      I.add_mem (hy z hz) (hw z hz)
  · intro a y _ hy z hz
    have h := I.smul_mem a (hy z hz)
    rw [← IsScalarTower.algebraMap_smul K a y,
      LinearMap.BilinForm.smul_left]
    convert h using 1
    simp only [Algebra.smul_def, map_ofNat]
    ring

/-- The finite candidate values generate the norm ideal. -/
theorem normIdeal_eq_span_normValueCandidates (q : QuadraticSpace K V)
    (L : Lattice K V) :
    normIdeal q L =
      Submodule.span (IntegerRing K) (normValueCandidates q L : Set K) := by
  let S : Set V := Set.range L.standardAmbientBasis
  let I := Submodule.span (IntegerRing K) (normValueCandidates q L : Set K)
  apply le_antisymm
  · rw [normIdeal, Submodule.span_le]
    rintro _ ⟨y, rfl⟩
    have hy : (y : V) ∈ Submodule.span (IntegerRing K) S := by
      rw [← L.toSubmodule_eq_span_standardAmbientBasis]
      exact y.property
    refine Submodule.span_induction
      (p := fun y _ => q.quadratic y ∈ I) ?_ ?_ ?_ ?_ hy
    · rintro _ ⟨i, rfl⟩
      exact quadratic_basis_mem_candidateSpan q L i
    · simp [I]
    · intro y z hy hz hqy hqz
      rw [q.quadratic_add]
      apply I.add_mem (I.add_mem hqy hqz)
      simpa only [Algebra.smul_def, map_ofNat] using
        two_bilin_mem_candidateSpan_of_mem_span q L y z hy hz
    · intro a y _ hqy
      rw [← IsScalarTower.algebraMap_smul K a y, q.quadratic_smul]
      let a2 : IntegerRing K := a ^ 2
      have h := I.smul_mem a2 hqy
      simpa only [a2, Algebra.smul_def, map_pow] using h
  · rw [Submodule.span_le]
    intro a ha
    change a ∈ normValueCandidates q L at ha
    simp only [normValueCandidates, Finset.mem_union, Finset.mem_image,
      Finset.mem_univ, true_and] at ha
    rcases ha with ⟨i, hi⟩ | ⟨ij, _, hij⟩
    · rw [← hi]
      exact quadratic_mem_normIdeal_of_mem q L (standardAmbientBasis_mem L i)
    · rw [← hij]
      apply quadratic_mem_normIdeal_of_mem q L
      exact L.add_mem (standardAmbientBasis_mem L ij.1)
        (standardAmbientBasis_mem L ij.2)

/-- Every candidate is the quadratic value of an actual lattice vector. -/
theorem exists_vector_of_mem_normValueCandidates
    (q : QuadraticSpace K V) (L : Lattice K V) {a : K}
    (ha : a ∈ normValueCandidates q L) :
    ∃ x : V, x ∈ L ∧ q.quadratic x = a := by
  classical
  simp only [normValueCandidates, Finset.mem_union, Finset.mem_image,
    Finset.mem_univ, true_and] at ha
  rcases ha with ⟨i, hi⟩ | ⟨ij, _, hij⟩
  · exact ⟨L.standardAmbientBasis i, standardAmbientBasis_mem L i, hi⟩
  · exact ⟨L.standardAmbientBasis ij.1 + L.standardAmbientBasis ij.2,
      L.add_mem (standardAmbientBasis_mem L ij.1)
        (standardAmbientBasis_mem L ij.2), hij⟩

/-- A positive-dimensional lattice has a nonzero candidate norm value. -/
theorem exists_mem_normValueCandidates_ne_zero
    (q : QuadraticSpace K V) (L : Lattice K V)
    (hfin : 0 < Module.finrank K V) :
    ∃ a ∈ normValueCandidates q L, a ≠ 0 := by
  classical
  letI : Nonempty (Fin (Module.finrank K V)) :=
    Fin.pos_iff_nonempty.mp hfin
  by_contra hexists
  push Not at hexists
  have hpair : ∀ i j : Fin (Module.finrank K V),
      q.bilin (L.standardAmbientBasis i) (L.standardAmbientBasis j) = 0 := by
    intro i j
    have hi : q.quadratic (L.standardAmbientBasis i) = 0 :=
      hexists _ (by simp [normValueCandidates])
    have hj : q.quadratic (L.standardAmbientBasis j) = 0 :=
      hexists _ (by simp [normValueCandidates])
    have hij : q.quadratic
        (L.standardAmbientBasis i + L.standardAmbientBasis j) = 0 :=
      hexists _ (by simp [normValueCandidates])
    have hadd := q.quadratic_add
      (L.standardAmbientBasis i) (L.standardAmbientBasis j)
    rw [hi, hj, hij] at hadd
    have hmul : (2 : K) *
        q.bilin (L.standardAmbientBasis i) (L.standardAmbientBasis j) = 0 := by
      simpa using hadd.symm
    exact (mul_eq_zero.mp hmul).resolve_left (by norm_num)
  have hmatrix : integralGramMatrix q L = 0 := by
    ext i j
    rw [integralGramMatrix_apply, hpair i j]
    rfl
  apply determinant_ne_zero q L
  rw [determinant, hmatrix, Matrix.det_zero]

/-- A larger valuation means divisibility by the smaller-valuation element. -/
theorem mem_principalIdeal_of_ord_le {a b : K} (ha : a ≠ 0)
    (hord : ord K a ≤ ord K b) :
    b ∈ principalIdeal (K := K) a := by
  by_cases hb : b = 0
  · subst b
    exact Submodule.zero_mem _
  have hintegral : Dyadic.IsIntegral K (b / a) := by
    let ua : Kˣ := Units.mk0 a ha
    let ub : Kˣ := Units.mk0 b hb
    have hfinite :
        ((ordUnit K ua : Int) : WithTop Int) ≤
          ((ordUnit K ub : Int) : WithTop Int) := by
      simpa [ua, ub] using hord
    have hint : ordUnit K ua ≤ ordUnit K ub :=
      WithTop.coe_le_coe.mp hfinite
    rw [Dyadic.IsIntegral, div_eq_mul_inv, ord_mul, AddValuation.map_inv]
    have hbOrd : ord K b = ((ordUnit K ub : Int) : WithTop Int) := by
      simpa [ub] using (coe_ordUnit K ub).symm
    have haOrd : ord K a = ((ordUnit K ua : Int) : WithTop Int) := by
      simpa [ua] using (coe_ordUnit K ua).symm
    have heq : ord K b + -(ord K a) =
        (((ordUnit K ub - ordUnit K ua : Int) : WithTop Int)) := by
      rw [hbOrd, haOrd]
      simp [sub_eq_add_neg]
    rw [heq]
    exact_mod_cast sub_nonneg.mpr hint
  rw [principalIdeal, Submodule.mem_span_singleton]
  refine ⟨⟨b / a, (mem_integerRing_iff K).2 hintegral⟩, ?_⟩
  change (b / a) * a = b
  exact div_mul_cancel₀ b ha

/-- Membership in a nonzero principal coefficient ideal bounds valuation
from below. -/
theorem ord_le_of_mem_principalIdeal {a b : K} (ha : a ≠ 0)
    (hb : b ∈ principalIdeal (K := K) a) : ord K a ≤ ord K b := by
  rw [principalIdeal, Submodule.mem_span_singleton] at hb
  rcases hb with ⟨c, hc⟩
  have hca : algebraMap (IntegerRing K) K c * a = b := by
    simpa only [Algebra.smul_def] using hc
  rw [← hca, ord_mul]
  have hcIntegral :
      Dyadic.IsIntegral K (algebraMap (IntegerRing K) K c) :=
    (mem_integerRing_iff K).1 c.property
  calc
    ord K a = 0 + ord K a := by simp
    _ ≤ ord K (algebraMap (IntegerRing K) K c) + ord K a :=
      by simpa [add_comm] using
        add_le_add_right hcIntegral (ord K a)

/-- Inclusion of nonzero principal coefficient ideals is exactly reverse
valuation order. -/
theorem principalIdeal_le_iff_ord_ge {a b : K} (ha : a ≠ 0) (hb : b ≠ 0) :
    principalIdeal (K := K) a ≤ principalIdeal (K := K) b ↔
      ord K b ≤ ord K a := by
  constructor
  · intro h
    exact ord_le_of_mem_principalIdeal hb
      (h (generator_mem_principalIdeal a))
  · intro h
    rw [principalIdeal, Submodule.span_le]
    rintro _ haMem
    rw [Set.mem_singleton_iff] at haMem
    subst haMem
    exact mem_principalIdeal_of_ord_le hb h

/-- Every positive-dimensional quadratic lattice has an anisotropic norm generator. -/
theorem exists_isNormGenerator_of_finrank_pos
    (q : QuadraticSpace K V) (L : Lattice K V)
    (hfin : 0 < Module.finrank K V) :
    ∃ x : V, IsNormGenerator q L x ∧ q.IsAnisotropic x := by
  classical
  obtain ⟨a, ha, hane⟩ :=
    exists_mem_normValueCandidates_ne_zero q L hfin
  let S := (normValueCandidates q L).filter fun z => z ≠ 0
  have hS : S.Nonempty := ⟨a, by simp [S, ha, hane]⟩
  obtain ⟨m, hmS, hmin⟩ :=
    Finset.exists_min_image S (fun z => ord K z) hS
  have hm : m ∈ normValueCandidates q L := (Finset.mem_filter.mp hmS).1
  have hmne : m ≠ 0 := (Finset.mem_filter.mp hmS).2
  obtain ⟨x, hxL, hqx⟩ :=
    exists_vector_of_mem_normValueCandidates q L hm
  refine ⟨x, ⟨hxL, ?_⟩, ?_⟩
  · rw [hqx, normIdeal_eq_span_normValueCandidates]
    apply le_antisymm
    · rw [Submodule.span_le]
      intro b hb
      change b ∈ normValueCandidates q L at hb
      by_cases hbne : b = 0
      · subst b
        exact Submodule.zero_mem _
      apply mem_principalIdeal_of_ord_le hmne
      exact hmin b (by simp [S, hb, hbne])
    · rw [principalIdeal]
      apply Submodule.span_mono
      simpa using hm
  · change q.quadratic x ≠ 0
    rw [hqx]
    exact hmne

/-- The norm ideal of a positive-dimensional nondegenerate lattice is nonzero. -/
theorem normIdeal_ne_bot_of_finrank_pos
    (q : QuadraticSpace K V) (L : Lattice K V)
    (hfin : 0 < Module.finrank K V) : normIdeal q L ≠ ⊥ := by
  obtain ⟨a, ha, hane⟩ :=
    exists_mem_normValueCandidates_ne_zero q L hfin
  intro hbot
  have haNorm : a ∈ normIdeal q L := by
    rw [normIdeal_eq_span_normValueCandidates]
    exact Submodule.subset_span ha
  rw [hbot] at haNorm
  exact hane haNorm

/-- In positive dimension every norm generator is anisotropic. -/
theorem IsNormGenerator.isAnisotropic_of_finrank_pos
    {q : QuadraticSpace K V} {L : Lattice K V} {x : V}
    (generator : IsNormGenerator q L x)
    (hfin : 0 < Module.finrank K V) : q.IsAnisotropic x := by
  intro hzero
  apply normIdeal_ne_bot_of_finrank_pos q L hfin
  rw [generator.normIdeal_eq, hzero, principalIdeal]
  simp

end Lattice

end Bong
