/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.Beli2009NormGeneratorSignsProof
import Bong.Bong.Beli2009OrthogonalIdealProof
import Bong.Lattice.OmearaBinaryWeightCoordinates
import Bong.Lattice.OmearaGeneralPlaneChangeOfComplement
import Bong.Lattice.OmearaHighRankModularSplitting
import Bong.Lattice.OmearaNormPreservingBinarySplitting

/-!
# O'Meara 93:18(ii): the even-parity unimodular case

This file closes the even-parity branch of O'Meara's Example 93:18.  The
proof follows the printed argument: split a norm-preserving binary plane,
put it in the weight coordinates of 93:10, change its complement twice,
use perfection of the residue field, and normalize the resulting deep even
plane by 93:11.
-/

namespace Bong

open Dyadic Module

namespace Lattice

universe u v w

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {W : Type w} [AddCommGroup W] [Module K W]

/-- The parity alternative in the definition of the weight forces the
terminal value `wL = 2sL` when the displayed sum of orders is even. -/
theorem weightIdeal_eq_twoScaleIdeal_of_even
    [Beli2009WeightIdealData.{u, v} K]
    {q : QuadraticSpace K V} {L : Lattice K V}
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (heven : Even (ordUnit K a + weightIdealOrder q L)) :
    weightIdeal q L = twoScaleIdeal q L := by
  have hconditions := (beli2009Lemma210 a ha
    (Beli2009WeightIdealData.weight q L)
    (twoScaleIdeal_le_weightIdeal q L)).mp rfl
  rcases hconditions.2 with htwo | hodd
  · exact htwo
  · exact (Int.not_odd_iff_even.mpr heven hodd).elim

/-- In a unimodular lattice, `2sL` is the principal ideal generated by
`2`. -/
theorem twoScaleIdeal_eq_principalIdeal_two_of_unimodular
    {q : QuadraticSpace K V} {L : Lattice K V}
    (hmodular : IsModular q L (1 : Kˣ))
    (hpos : 0 < finrank K V) :
    twoScaleIdeal q L = principalIdeal (K := K) (2 : K) := by
  rw [twoScaleIdeal, hmodular.scaleIdeal_eq_principal hpos,
    twiceIdeal_principalIdeal]
  simp

/-- Elements of `2sL` in a positive-rank unimodular lattice have an
integral half. -/
theorem exists_integral_half_of_mem_twoScaleIdeal_unimodular
    {q : QuadraticSpace K V} {L : Lattice K V}
    (hmodular : IsModular q L (1 : Kˣ))
    (hpos : 0 < finrank K V) {y : K}
    (hy : y ∈ twoScaleIdeal q L) :
    ∃ eta : K, eta ∈ IntegerRing K ∧ y = (2 : K) * eta := by
  rw [twoScaleIdeal_eq_principalIdeal_two_of_unimodular
    hmodular hpos, principalIdeal, Submodule.mem_span_singleton] at hy
  let etaO : IntegerRing K := Classical.choose hy
  have heta := Classical.choose_spec hy
  refine ⟨(etaO : K), etaO.property, ?_⟩
  change y = (2 : K) * (etaO : K)
  have heta' : (etaO : K) * (2 : K) = y := by
    exact heta
  rw [← heta']
  ring

/-- The selected weight order of an even-parity unimodular lattice is the
ramification index `ord(2)`. -/
theorem weightIdealOrder_eq_ramificationIndex_of_unimodular_even
    [Beli2009WeightIdealData.{u, v} K]
    {q : QuadraticSpace K V} {L : Lattice K V}
    (hmodular : IsModular q L (1 : Kˣ))
    (hpos : 0 < finrank K V)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (heven : Even (ordUnit K a + weightIdealOrder q L)) :
    weightIdealOrder q L = (ramificationIndex K : Int) := by
  let two : Kˣ := Units.mk0 (2 : K) (by norm_num)
  have htwoOrder : ordUnit K two = (ramificationIndex K : Int) := by
    apply WithTop.coe_injective
    rw [coe_ordUnit]
    exact (ramificationIndex_spec K).symm
  apply powerIdeal_order_eq_of_eq (K := K)
  calc
    powerIdeal (K := K) (weightIdealOrder q L) =
        weightIdeal q L := (weightIdeal_eq_powerIdeal q L).symm
    _ = twoScaleIdeal q L :=
      weightIdeal_eq_twoScaleIdeal_of_even a ha heven
    _ = principalIdeal (K := K) (2 : K) :=
      twoScaleIdeal_eq_principalIdeal_two_of_unimodular hmodular hpos
    _ = powerIdeal (K := K) (ordUnit K two) := by
      simpa only [two, Units.val_mk0] using
        (principalIdeal_eq_powerIdeal two)
    _ = powerIdeal (K := K) (ramificationIndex K : Int) := by
      rw [htwoOrder]

/-- An even general O'Meara plane has norm ideal contained in `2O`. -/
theorem normIdeal_evenGeneralPlane_le_principalIdeal_two
    (eta zeta : K)
    (heta : eta ∈ IntegerRing K) (hzeta : zeta ∈ IntegerRing K)
    (hnondegenerate : ((2 : K) * eta) * ((2 : K) * zeta) ≠ 1) :
    normIdeal
        (QuadraticSpace.omearaGeneralPlane
          ((2 : K) * eta) ((2 : K) * zeta) hnondegenerate)
        (hyperbolicPlaneLattice (K := K)) ≤
      principalIdeal (K := K) (2 : K) := by
  let p := QuadraticSpace.omearaGeneralPlane
    ((2 : K) * eta) ((2 : K) * zeta) hnondegenerate
  apply normIdeal_le_of_quadratic_mem
  intro x hx
  have hxCoordinates := (mem_omearaPlaneLattice_iff x).mp hx
  let c : K := eta * x 0 ^ 2 + x 0 * x 1 + zeta * x 1 ^ 2
  have hc : c ∈ IntegerRing K := by
    have hx0 : x 0 ∈ IntegerRing K := hxCoordinates.1
    have hx1 : x 1 ∈ IntegerRing K := hxCoordinates.2
    exact (IntegerRing K).toSubring.add_mem
      ((IntegerRing K).toSubring.add_mem
        ((IntegerRing K).toSubring.mul_mem heta
          ((IntegerRing K).toSubring.pow_mem hx0 2))
        ((IntegerRing K).toSubring.mul_mem hx0 hx1))
      ((IntegerRing K).toSubring.mul_mem hzeta
        ((IntegerRing K).toSubring.pow_mem hx1 2))
  rw [principalIdeal, Submodule.mem_span_singleton]
  refine ⟨⟨c, hc⟩, ?_⟩
  change c * (2 : K) = p.quadratic x
  rw [QuadraticSpace.quadratic,
    QuadraticSpace.omearaGeneralPlane_bilin_apply]
  dsimp only [p, c]
  ring

/-- The Gram determinant of an even general plane is a valuation unit. -/
theorem evenGeneralPlane_determinant_isValuationUnit
    (eta zeta : K)
    (heta : eta ∈ IntegerRing K) (hzeta : zeta ∈ IntegerRing K) :
    IsValuationUnit K
      (((2 : K) * eta) * ((2 : K) * zeta) - 1) := by
  have hetaMax : IsInMaximalIdeal K ((2 : K) * eta) :=
    isInMaximalIdeal_mul_isIntegral K (two_isInMaximalIdeal K)
      ((mem_integerRing_iff K).1 heta)
  have hzetaIntegral : (2 : K) * zeta ∈ IntegerRing K :=
    (IntegerRing K).toSubring.mul_mem (by norm_num) hzeta
  have hproductMax : IsInMaximalIdeal K
      (((2 : K) * eta) * ((2 : K) * zeta)) :=
    isInMaximalIdeal_mul_isIntegral K hetaMax
      ((mem_integerRing_iff K).1 hzetaIntegral)
  have hone := isValuationUnit_one_add_of_isInMaximalIdeal
    (isInMaximalIdeal_neg hproductMax)
  rw [show ((2 : K) * eta) * ((2 : K) * zeta) - 1 =
      -(1 + -(((2 : K) * eta) * ((2 : K) * zeta))) by ring,
    IsValuationUnit, ord_neg]
  exact hone

/-- A norm-generator vector whose order has the same parity as `ord(2)`
can be multiplied by an integral uniformizer square so that its value is
exactly twice a valuation unit. -/
structure TwiceUnitNormVectorData
    (q : QuadraticSpace K V) (L : Lattice K V) where
  vector : V
  vector_mem : vector ∈ L
  epsilon : Kˣ
  epsilon_unit : IsValuationUnit K (epsilon : K)
  quadratic_eq : q.quadratic vector = (2 : K) * (epsilon : K)

/-- Construct the scaled vector in the preceding statement. -/
noncomputable def twiceUnitNormVectorData
    {q : QuadraticSpace K V} {L : Lattice K V} (x : V)
    (hx : IsNormGenerator q L x) (hxne : q.quadratic x ≠ 0)
    (hle : ordUnit K (Units.mk0 (q.quadratic x) hxne) ≤
      (ramificationIndex K : Int))
    (hmod : Int.ModEq 2 (ramificationIndex K : Int)
      (ordUnit K (Units.mk0 (q.quadratic x) hxne))) :
    TwiceUnitNormVectorData q L := by
  let b : Kˣ := Units.mk0 (q.quadratic x) hxne
  let hexists := exists_nat_eq_add_two_mul_of_le_modEq_two hle hmod
  let k : Nat := Classical.choose hexists
  have hk : (ramificationIndex K : Int) =
      ordUnit K (Units.mk0 (q.quadratic x) hxne) + 2 * (k : Int) :=
    Classical.choose_spec hexists
  let c : Kˣ := uniformizerPowerUnit K (k : Int)
  have hcIntegral : (c : K) ∈ IntegerRing K :=
    uniformizerPowerUnit_nat_mem_integerRing k
  let cO : IntegerRing K := ⟨c, hcIntegral⟩
  let two : Kˣ := Units.mk0 (2 : K) (by norm_num)
  have htwoOrder : ordUnit K two = (ramificationIndex K : Int) := by
    apply WithTop.coe_injective
    rw [coe_ordUnit]
    exact (ramificationIndex_spec K).symm
  let epsilon : Kˣ := b * c ^ 2 / two
  have hk' : (ramificationIndex K : Int) =
      ordUnit K b + 2 * (k : Int) := by
    simpa only [b] using hk
  have hepsilonOrder : ordUnit K epsilon = 0 := by
    dsimp only [epsilon]
    rw [div_eq_mul_inv, ordUnit_mul, ordUnit_inv,
      ordUnit_mul, ordUnit_pow, ordUnit_uniformizerPowerUnit,
      htwoOrder]
    omega
  have hepsilonUnit : IsValuationUnit K (epsilon : K) :=
    (isValuationUnit_iff_ordUnit_eq_zero K epsilon).2 hepsilonOrder
  let z : V := (c : K) • x
  have hzMem : z ∈ L := by
    change (cO : K) • x ∈ L
    exact L.smul_mem cO hx.mem
  have hzQuadratic : q.quadratic z = (2 : K) * (epsilon : K) := by
    dsimp only [z]
    rw [q.quadratic_smul]
    have hepsilonValue : (epsilon : K) =
        q.quadratic x * (c : K) ^ 2 / (2 : K) := by
      simp [epsilon, b, two, div_eq_mul_inv]
    rw [hepsilonValue]
    field_simp
  exact
    { vector := z
      vector_mem := hzMem
      epsilon := epsilon
      epsilon_unit := hepsilonUnit
      quadratic_eq := hzQuadratic }

/-- In the norm-preserving binary splitting of an even-parity unimodular
lattice, both component weights are their respective `2s` ideals. -/
theorem normPreservingBinary_component_weightIdeal_eq_twoScale
    [Beli2009WeightIdealData.{u, v} K]
    {q : QuadraticSpace K V} {L : Lattice K V}
    (hmodular : IsModular q L (1 : Kˣ))
    (hrank : 3 ≤ finrank K V)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (hweight : weightIdeal q L = twoScaleIdeal q L)
    (D : NormPreservingBinaryModularSplittingData q L (1 : Kˣ))
    (i : Fin 2) :
    weightIdeal (D.decomposition.component i).space
        (D.decomposition.component i).lattice =
      twoScaleIdeal (D.decomposition.component i).space
        (D.decomposition.component i).lattice := by
  letI : Module.Finite K V := L.moduleFinite
  let J := D.decomposition.component 0
  let C := D.decomposition.component 1
  letI : Module.Finite K J.carrier := J.lattice.moduleFinite
  letI : Module.Finite K C.carrier := C.lattice.moduleFinite
  have htotal :=
    D.decomposition.pairProductLatticeIsometry.toLinearEquiv.finrank_eq
  have hCpos : 0 < finrank K C.carrier := by
    change finrank K (J.carrier × C.carrier) = finrank K V at htotal
    rw [Module.finrank_prod, D.first_rank] at htotal
    omega
  have hpos (j : Fin 2) :
      0 < finrank K (D.decomposition.component j).carrier := by
    fin_cases j
    · change 0 < finrank K J.carrier
      rw [D.first_rank]
      omega
    · change 0 < finrank K C.carrier
      exact hCpos
  let hgenExists (j : Fin 2) :=
    exists_isNormGenerator_of_finrank_pos
      (D.decomposition.component j).space
      (D.decomposition.component j).lattice (hpos j)
  let x (j : Fin 2) := Classical.choose (hgenExists j)
  have hxgen (j : Fin 2) : IsNormGenerator
      (D.decomposition.component j).space
      (D.decomposition.component j).lattice (x j) :=
    (Classical.choose_spec (hgenExists j)).1
  have hxne (j : Fin 2) :
      (D.decomposition.component j).space.quadratic (x j) ≠ 0 :=
    (Classical.choose_spec (hgenExists j)).2
  let ak (j : Fin 2) : Kˣ := Units.mk0
    ((D.decomposition.component j).space.quadratic (x j)) (hxne j)
  have hak (j : Fin 2) : IsNormGeneratorValue
      (D.decomposition.component j).space
      (D.decomposition.component j).lattice (ak j) := by
    exact (hxgen j).isNormGeneratorValue (hxne j)
  have hformula := D.decomposition.weightIdeal_eq_weightIdealExpression
    a ha ak hak
  have hcomponentLe := D.decomposition.componentWeight_le_weightIdealExpression
    a ak i
  rw [← hformula, hweight] at hcomponentLe
  have hcomponentModular : IsModular
      (D.decomposition.component i).space
      (D.decomposition.component i).lattice (1 : Kˣ) := by
    fin_cases i
    · exact D.first_modular
    · exact D.complement_modular
  have htwoEq :
      twoScaleIdeal (D.decomposition.component i).space
          (D.decomposition.component i).lattice =
        twoScaleIdeal q L := by
    unfold twoScaleIdeal
    rw [hcomponentModular.scaleIdeal_eq_principal (hpos i),
      hmodular.scaleIdeal_eq_principal (by omega)]
  apply le_antisymm
  · rw [htwoEq]
    exact hcomponentLe
  · exact twoScaleIdeal_le_weightIdeal
      (D.decomposition.component i).space
      (D.decomposition.component i).lattice

/-! ## Assembly of O'Meara 93:18(ii) -/

set_option maxHeartbeats 3000000 in

/-- O'Meara 93:18(ii).  A unimodular lattice of rank at least three whose
norm and weight orders have even sum contains an integral hyperbolic plane.
All choices in the printed proof are constructed here; no classification
or local-law parameter occurs in the statement. -/
noncomputable def omeara9318iiData
    {q : QuadraticSpace K V} {L : Lattice K V}
    (hmodular : IsModular q L (1 : Kˣ))
    (hrank : 3 ≤ finrank K V)
    (a : Kˣ) (ha : IsNormGeneratorValue q L a)
    (heven : Even (ordUnit K a + weightIdealOrder q L)) :
    Omeara9318vData q L (1 : Kˣ) := by
  letI : Module.Finite K V := L.moduleFinite
  have hpos : 0 < finrank K V := by omega
  have hweight : weightIdeal q L = twoScaleIdeal q L :=
    weightIdeal_eq_twoScaleIdeal_of_even a ha heven
  have hweightOrder : weightIdealOrder q L =
      (ramificationIndex K : Int) :=
    weightIdealOrder_eq_ramificationIndex_of_unimodular_even
      hmodular hpos a ha heven
  let S := NormPreservingBinaryModularSplittingData.normPreservingBinaryModularSplittingData
    q L (1 : Kˣ) hmodular hrank
  let J := S.decomposition.component 0
  let C := S.decomposition.component 1
  letI : Module.Finite K J.carrier := J.lattice.moduleFinite
  letI : Module.Finite K C.carrier := C.lattice.moduleFinite
  have htotal := S.decomposition.pairProductLatticeIsometry.toLinearEquiv.finrank_eq
  have hCpos : 0 < finrank K C.carrier := by
    change finrank K (J.carrier × C.carrier) = finrank K V at htotal
    rw [Module.finrank_prod, S.first_rank] at htotal
    omega
  let hxJExists := exists_isNormGenerator_of_finrank_pos
    J.space J.lattice (by rw [S.first_rank]; omega)
  let xJ : J.carrier := Classical.choose hxJExists
  have hxJ : IsNormGenerator J.space J.lattice xJ :=
    (Classical.choose_spec hxJExists).1
  have hxJne : J.space.quadratic xJ ≠ 0 :=
    (Classical.choose_spec hxJExists).2
  let hxCExists := exists_isNormGenerator_of_finrank_pos
    C.space C.lattice hCpos
  let xC : C.carrier := Classical.choose hxCExists
  have hxC : IsNormGenerator C.space C.lattice xC :=
    (Classical.choose_spec hxCExists).1
  have hxCne : C.space.quadratic xC ≠ 0 :=
    (Classical.choose_spec hxCExists).2
  let gamma : Kˣ := Units.mk0 (C.space.quadratic xC) hxCne
  have hgammaC : IsNormGeneratorValue C.space C.lattice gamma :=
    hxC.isNormGeneratorValue hxCne
  have hgammaAmbient : IsNormGeneratorValue q L gamma := by
    constructor
    · exact S.decomposition.component_normGroupSet_subset 1 hgammaC.1
    · exact S.complement_normIdeal_eq.symm.trans hgammaC.2
  have hJweight : weightIdeal J.space J.lattice =
      twoScaleIdeal J.space J.lattice := by
    exact normPreservingBinary_component_weightIdeal_eq_twoScale
      hmodular hrank a ha hweight S 0
  have hCweight : weightIdeal C.space C.lattice =
      twoScaleIdeal C.space C.lattice := by
    exact normPreservingBinary_component_weightIdeal_eq_twoScale
      hmodular hrank a ha hweight S 1
  have hCtwo : twoScaleIdeal C.space C.lattice = twoScaleIdeal q L := by
    unfold twoScaleIdeal
    rw [S.complement_modular.scaleIdeal_eq_principal hCpos,
      hmodular.scaleIdeal_eq_principal hpos]
  have hgroupEq : normGroupSet C.space C.lattice = normGroupSet q L := by
    calc
      normGroupSet C.space C.lattice =
          integralSquareCoset (gamma : K)
            (weightIdeal C.space C.lattice) :=
        normGroupSet_eq_integralSquareCoset_weightIdeal gamma hgammaC
      _ = integralSquareCoset (gamma : K) (weightIdeal q L) := by
        rw [hCweight, hweight, hCtwo]
      _ = normGroupSet q L :=
        (normGroupSet_eq_integralSquareCoset_weightIdeal
          gamma hgammaAmbient).symm
  have hxJValue : IsNormGeneratorValue J.space J.lattice
      (Units.mk0 (J.space.quadratic xJ) hxJne) :=
    hxJ.isNormGeneratorValue hxJne
  have hxJAmbient : J.space.quadratic xJ ∈ normGroupSet q L := by
    exact S.decomposition.component_normGroupSet_subset 0 hxJValue.1
  have hnegativeAmbient : -J.space.quadratic xJ ∈ normGroupSet q L :=
    neg_mem_normGroupSet q L hxJAmbient
  have hnegativeC : -J.space.quadratic xJ ∈
      normGroupSet C.space C.lattice := by
    rw [hgroupEq]
    exact hnegativeAmbient
  let z : C.carrier := Classical.choose hnegativeC
  have hzSpec := Classical.choose_spec hnegativeC
  have hzMem : z ∈ C.lattice := hzSpec.1
  let hyExists := hzSpec.2
  let y : K := Classical.choose hyExists
  have hySpec := Classical.choose_spec hyExists
  have hyMem : y ∈ twoScaleIdeal C.space C.lattice := hySpec.1
  have hnegativeEq : -J.space.quadratic xJ =
      C.space.quadratic z + y := hySpec.2
  have hnegativeY : -y ∈ twoScaleIdeal C.space C.lattice :=
    (twoScaleIdeal C.space C.lattice).neg_mem hyMem
  let hetaExists :=
    exists_integral_half_of_mem_twoScaleIdeal_unimodular
      S.complement_modular hCpos hnegativeY
  let eta : K := Classical.choose hetaExists
  have hetaIntegral : eta ∈ IntegerRing K :=
    (Classical.choose_spec hetaExists).1
  have hetaEq : -y = (2 : K) * eta :=
    (Classical.choose_spec hetaExists).2
  have hnewCoefficient : J.space.quadratic xJ + C.space.quadratic z =
      (2 : K) * eta := by
    calc
      J.space.quadratic xJ + C.space.quadratic z = -y := by
        linear_combination -hnegativeEq
      _ = (2 : K) * eta := hetaEq
  let B := omeara9310BinaryWeightData J.space J.lattice xJ
    S.first_modular S.first_rank hxJ hJweight
  have hJscale : scaleIdeal J.space J.lattice =
      principalIdeal (K := K) (1 : K) :=
    S.first_modular.scaleIdeal_eq_principal (by rw [S.first_rank]; omega)
  have hfirstIntegral : J.space.quadratic xJ ∈ IntegerRing K := by
    change J.space.bilin xJ xJ ∈ IntegerRing K
    apply mem_integerRing_of_mul_mem_principalIdeal
      (one_ne_zero : (1 : K) ≠ 0)
    simpa only [one_mul, ← hJscale] using
      (bilin_mem_scaleIdeal_of_mem J.space J.lattice hxJ.mem hxJ.mem)
  have hsecondIntegral : (2 : K) * B.zeta ∈ IntegerRing K :=
    (IntegerRing K).toSubring.mul_mem (by norm_num) B.zeta_integral
  have hnewIntegral : J.space.quadratic xJ + C.space.quadratic z ∈
      IntegerRing K := by
    rw [hnewCoefficient]
    exact (IntegerRing K).toSubring.mul_mem (by norm_num) hetaIntegral
  have hnewDetUnit : IsValuationUnit K
      ((J.space.quadratic xJ + C.space.quadratic z) *
          ((2 : K) * B.zeta) - 1) := by
    rw [hnewCoefficient]
    exact evenGeneralPlane_determinant_isValuationUnit
      eta B.zeta hetaIntegral B.zeta_integral
  have hnewNe :
      (J.space.quadratic xJ + C.space.quadratic z) *
          ((2 : K) * B.zeta) ≠ 1 := by
    exact sub_ne_zero.mp (ne_zero_of_isValuationUnit hnewDetUnit)
  let expose : Isometry q (J.space.orthogonalSum C.space) L
      (product J.lattice C.lattice) :=
    S.decomposition.pairProductLatticeIsometry.symm
  let coordinates : Isometry (J.space.orthogonalSum C.space)
      ((QuadraticSpace.omearaGeneralPlane
        (J.space.quadratic xJ) ((2 : K) * B.zeta)
          B.nondegenerate).orthogonalSum C.space)
      (product J.lattice C.lattice)
      (product (hyperbolicPlaneLattice (K := K)) C.lattice) :=
    B.isometry.orthogonalProductBasic
      (Isometry.refl C.space C.lattice)
  let displayed0 := expose.trans coordinates
  have hdisplayed0Modular : IsModular
      ((QuadraticSpace.omearaGeneralPlane
        (J.space.quadratic xJ) ((2 : K) * B.zeta)
          B.nondegenerate).orthogonalSum C.space)
      (product (hyperbolicPlaneLattice (K := K)) C.lattice)
      (1 : Kˣ) :=
    hmodular.mapLatticeIsometry displayed0
  let Eraw := omearaGeneralPlaneChangeOfComplement
    C.space C.lattice (J.space.quadratic xJ) ((2 : K) * B.zeta)
      B.nondegenerate z hfirstIntegral hsecondIntegral hzMem
      hnewIntegral hnewDetUnit hdisplayed0Modular
  let E : OmearaGeneralPlaneChangeOfComplementData
      C.space C.lattice (J.space.quadratic xJ) ((2 : K) * B.zeta)
        B.nondegenerate z hnewNe := by
    simpa only using Eraw
  let displayed1 := displayed0.trans E.displayedIsometry
  let P₁ := E.decomposition.component 0
  let C₁ := E.decomposition.component 1
  letI : Module.Finite K P₁.carrier := P₁.lattice.moduleFinite
  letI : Module.Finite K C₁.carrier := C₁.lattice.moduleFinite
  have hP₁rank : finrank K P₁.carrier = 2 := by
    have h := E.first.toLinearEquiv.finrank_eq
    simpa only [Module.finrank_fin_fun] using h
  have htotal₁ := E.decomposition.pairProductLatticeIsometry.toLinearEquiv.finrank_eq
  have hC₁pos : 0 < finrank K C₁.carrier := by
    change finrank K (P₁.carrier × C₁.carrier) =
      finrank K ((Fin 2 → K) × C.carrier) at htotal₁
    rw [Module.finrank_prod, Module.finrank_prod, hP₁rank,
      Module.finrank_fin_fun] at htotal₁
    omega
  have hC₁modular : IsModular C₁.space C₁.lattice (1 : Kˣ) :=
    E.decomposition.component_modular_of_ambient hdisplayed0Modular 1
  have hP₁normLe : normIdeal P₁.space P₁.lattice ≤
      principalIdeal (K := K) (2 : K) := by
    have hmodel : normIdeal
          (QuadraticSpace.omearaGeneralPlane
            (J.space.quadratic xJ + C.space.quadratic z)
            ((2 : K) * B.zeta) hnewNe)
          (hyperbolicPlaneLattice (K := K)) ≤
        principalIdeal (K := K) (2 : K) := by
      simpa only [hnewCoefficient] using
        (normIdeal_evenGeneralPlane_le_principalIdeal_two
          eta B.zeta hetaIntegral B.zeta_integral (by
            simpa only [hnewCoefficient] using hnewNe))
    have hnormEq : normIdeal P₁.space P₁.lattice =
        normIdeal
          (QuadraticSpace.omearaGeneralPlane
            (J.space.quadratic xJ + C.space.quadratic z)
            ((2 : K) * B.zeta) hnewNe)
          (hyperbolicPlaneLattice (K := K)) := by
      symm
      rw [← E.first.map_eq]
      exact normIdeal_map_isometry E.first.toQuadraticSpaceIsometry
        P₁.lattice
    rw [hnormEq]
    exact hmodel
  have hC₁two : twoScaleIdeal C₁.space C₁.lattice =
      principalIdeal (K := K) (2 : K) :=
    twoScaleIdeal_eq_principalIdeal_two_of_unimodular
      hC₁modular hC₁pos
  have hP₁normLeC₁ : normIdeal P₁.space P₁.lattice ≤
      normIdeal C₁.space C₁.lattice := by
    exact hP₁normLe.trans (hC₁two.symm.le.trans
      (twoScaleIdeal_le_normIdeal C₁.space C₁.lattice))
  have hC₁normEqDisplayed : normIdeal C₁.space C₁.lattice =
      normIdeal
        ((QuadraticSpace.omearaGeneralPlane
          (J.space.quadratic xJ) ((2 : K) * B.zeta)
            B.nondegenerate).orthogonalSum C.space)
        (product (hyperbolicPlaneLattice (K := K)) C.lattice) := by
    have hsup :=
      NormPreservingBinaryModularSplittingData.normIdeal_eq_sup_components
        E.decomposition
    rw [sup_eq_right.mpr hP₁normLeC₁] at hsup
    exact hsup.symm
  have hdisplayedNormEq : normIdeal
      ((QuadraticSpace.omearaGeneralPlane
        (J.space.quadratic xJ) ((2 : K) * B.zeta)
          B.nondegenerate).orthogonalSum C.space)
      (product (hyperbolicPlaneLattice (K := K)) C.lattice) =
      normIdeal q L := by
    rw [← displayed0.map_eq]
    exact normIdeal_map_isometry displayed0.toQuadraticSpaceIsometry L
  have hC₁normEq : normIdeal C₁.space C₁.lattice = normIdeal q L :=
    hC₁normEqDisplayed.trans hdisplayedNormEq
  let hx₁Exists := exists_isNormGenerator_of_finrank_pos
    C₁.space C₁.lattice hC₁pos
  let x₁ : C₁.carrier := Classical.choose hx₁Exists
  have hx₁ : IsNormGenerator C₁.space C₁.lattice x₁ :=
    (Classical.choose_spec hx₁Exists).1
  have hx₁ne : C₁.space.quadratic x₁ ≠ 0 :=
    (Classical.choose_spec hx₁Exists).2
  let a₁ : Kˣ := Units.mk0 (C₁.space.quadratic x₁) hx₁ne
  have ha₁Order : ordUnit K a₁ = ordUnit K a := by
    apply (principalIdeal_eq_iff_ordUnit_eq a₁ a).mp
    exact hx₁.normIdeal_eq.symm.trans (hC₁normEq.trans ha.2)
  have haOrderLe : ordUnit K a ≤ (ramificationIndex K : Int) := by
    have hle := normGeneratorOrder_le_weightIdealOrder a ha
    rw [hweightOrder] at hle
    exact hle
  have ha₁OrderLe : ordUnit K a₁ ≤
      (ramificationIndex K : Int) := by
    rw [ha₁Order]
    exact haOrderLe
  have heven' : Even (ordUnit K a + (ramificationIndex K : Int)) := by
    simpa only [hweightOrder] using heven
  have hmoda : Int.ModEq 2 (ramificationIndex K : Int) (ordUnit K a) := by
    rw [Int.modEq_iff_dvd]
    rcases heven' with ⟨k, hk⟩
    refine ⟨-(k - ordUnit K a), ?_⟩
    omega
  have hmoda₁ : Int.ModEq 2 (ramificationIndex K : Int)
      (ordUnit K a₁) := by
    rw [ha₁Order]
    exact hmoda
  let T := twiceUnitNormVectorData x₁ hx₁ hx₁ne
    ha₁OrderLe hmoda₁
  by_cases hetaDeep : IsInMaximalIdeal K eta
  · let normalizeRaw := Classical.choice
      (omeara9311_deep_even_plane_isIsometric
        eta B.zeta hetaIntegral hetaDeep B.zeta_integral
          (by simpa only [hnewCoefficient] using hnewNe))
    let normalize : Isometry
        (QuadraticSpace.omearaGeneralPlane
          (J.space.quadratic xJ + C.space.quadratic z)
          ((2 : K) * B.zeta) hnewNe)
        (QuadraticSpace.hyperbolicPlane (1 : Kˣ))
        (hyperbolicPlaneLattice (K := K))
        (hyperbolicPlaneLattice (K := K)) := by
      simpa only [hnewCoefficient] using normalizeRaw
    let finalDisplayed := displayed1.trans
      (normalize.orthogonalProductBasic
        (Isometry.refl C₁.space C₁.lattice))
    exact Omeara9318vData.ofDisplayedIsometry
      C₁.space C₁.lattice hmodular finalDisplayed
  · have hetaUnit : IsValuationUnit K eta := by
      by_contra hnot
      exact hetaDeep
        (isInMaximalIdeal_of_mem_integerRing_of_not_isValuationUnit
          hetaIntegral hnot)
    have hetaNe : eta ≠ 0 := ne_zero_of_isValuationUnit hetaUnit
    let etaU : Kˣ := Units.mk0 eta hetaNe
    let u : Kˣ := -etaU / T.epsilon
    have hetaUOrder : ordUnit K etaU = 0 := by
      apply WithTop.coe_injective
      rw [coe_ordUnit]
      exact hetaUnit
    have hTepsilonOrder : ordUnit K T.epsilon = 0 :=
      (isValuationUnit_iff_ordUnit_eq_zero K T.epsilon).mp
        T.epsilon_unit
    have huOrder : ordUnit K u = 0 := by
      dsimp only [u]
      rw [div_eq_mul_inv, ordUnit_mul, ordUnit_inv, ordUnit_neg,
        hetaUOrder, hTepsilonOrder]
      omega
    have huUnit : IsValuationUnit K (u : K) :=
      (isValuationUnit_iff_ordUnit_eq_zero K u).2 huOrder
    let htExists := exists_unit_squareRoot_mod_maximal K u huUnit
    let t : K := Classical.choose htExists
    have htUnit : IsValuationUnit K t :=
      (Classical.choose_spec htExists).1
    have htApprox : IsInMaximalIdeal K (t ^ 2 - (u : K)) :=
      (Classical.choose_spec htExists).2
    have htIntegral : t ∈ IntegerRing K :=
      (mem_integerRing_iff K).2 htUnit.ge
    let tO : IntegerRing K := ⟨t, htIntegral⟩
    let z₁ : C₁.carrier := t • T.vector
    have hz₁Mem : z₁ ∈ C₁.lattice := by
      change (tO : K) • T.vector ∈ C₁.lattice
      exact C₁.lattice.smul_mem tO T.vector_mem
    have hz₁Quadratic : C₁.space.quadratic z₁ =
        (2 : K) * ((T.epsilon : K) * t ^ 2) := by
      dsimp only [z₁]
      rw [C₁.space.quadratic_smul, T.quadratic_eq]
      ring
    let eta₁ : K := eta + (T.epsilon : K) * t ^ 2
    have heta₁Integral : eta₁ ∈ IntegerRing K := by
      exact (IntegerRing K).toSubring.add_mem hetaIntegral
        ((IntegerRing K).toSubring.mul_mem
          ((mem_integerRing_iff K).2 T.epsilon_unit.ge)
          ((IntegerRing K).toSubring.pow_mem htIntegral 2))
    have heta₁Eq : eta₁ =
        (T.epsilon : K) * (t ^ 2 - (u : K)) := by
      have huValue : (u : K) = -eta / (T.epsilon : K) := by
        simp [u, etaU, div_eq_mul_inv]
      rw [huValue]
      dsimp only [eta₁]
      field_simp [Units.ne_zero T.epsilon]
      ring
    have heta₁Deep : IsInMaximalIdeal K eta₁ := by
      rw [heta₁Eq]
      exact isIntegral_mul_isInMaximalIdeal K
        ((mem_integerRing_iff K).2 T.epsilon_unit.ge) htApprox
    have hsecondCoefficient : (2 : K) * eta +
        C₁.space.quadratic z₁ = (2 : K) * eta₁ := by
      rw [hz₁Quadratic]
      dsimp only [eta₁]
      ring
    have hsecondNewIntegral : (2 : K) * eta +
        C₁.space.quadratic z₁ ∈ IntegerRing K := by
      rw [hsecondCoefficient]
      exact (IntegerRing K).toSubring.mul_mem (by norm_num) heta₁Integral
    have hsecondDetUnit : IsValuationUnit K
        (((2 : K) * eta + C₁.space.quadratic z₁) *
          ((2 : K) * B.zeta) - 1) := by
      rw [hsecondCoefficient]
      exact evenGeneralPlane_determinant_isValuationUnit
        eta₁ B.zeta heta₁Integral B.zeta_integral
    have hsecondNe :
        ((2 : K) * eta + C₁.space.quadratic z₁) *
          ((2 : K) * B.zeta) ≠ 1 :=
      sub_ne_zero.mp (ne_zero_of_isValuationUnit hsecondDetUnit)
    let Eeven : Isometry
        ((QuadraticSpace.omearaGeneralPlane
          (J.space.quadratic xJ) ((2 : K) * B.zeta)
            B.nondegenerate).orthogonalSum C.space)
        ((QuadraticSpace.omearaGeneralPlane
          ((2 : K) * eta) ((2 : K) * B.zeta)
            (by simpa only [hnewCoefficient] using hnewNe)).orthogonalSum
          C₁.space)
        (product (hyperbolicPlaneLattice (K := K)) C.lattice)
        (product (hyperbolicPlaneLattice (K := K)) C₁.lattice) := by
      simpa only [hnewCoefficient] using E.displayedIsometry
    let displayed1Even := displayed0.trans Eeven
    have hdisplayed1Modular : IsModular
        ((QuadraticSpace.omearaGeneralPlane
          ((2 : K) * eta) ((2 : K) * B.zeta)
            (by simpa only [hnewCoefficient] using hnewNe)).orthogonalSum
          C₁.space)
        (product (hyperbolicPlaneLattice (K := K)) C₁.lattice)
        (1 : Kˣ) :=
      hdisplayed0Modular.mapLatticeIsometry Eeven
    let Fraw := omearaGeneralPlaneChangeOfComplement
      C₁.space C₁.lattice ((2 : K) * eta) ((2 : K) * B.zeta)
        (by simpa only [hnewCoefficient] using hnewNe) z₁
        ((IntegerRing K).toSubring.mul_mem (by norm_num) hetaIntegral)
        hsecondIntegral hz₁Mem hsecondNewIntegral hsecondDetUnit
        hdisplayed1Modular
    let F : OmearaGeneralPlaneChangeOfComplementData
        C₁.space C₁.lattice ((2 : K) * eta) ((2 : K) * B.zeta)
          (by simpa only [hnewCoefficient] using hnewNe) z₁ hsecondNe := by
      simpa only using Fraw
    let C₂ := F.decomposition.component 1
    let normalizeRaw := Classical.choice
      (omeara9311_deep_even_plane_isIsometric
        eta₁ B.zeta heta₁Integral heta₁Deep B.zeta_integral
          (by simpa only [hsecondCoefficient] using hsecondNe))
    let normalize : Isometry
        (QuadraticSpace.omearaGeneralPlane
          ((2 : K) * eta + C₁.space.quadratic z₁)
          ((2 : K) * B.zeta) hsecondNe)
        (QuadraticSpace.hyperbolicPlane (1 : Kˣ))
        (hyperbolicPlaneLattice (K := K))
        (hyperbolicPlaneLattice (K := K)) := by
      simpa only [hsecondCoefficient] using normalizeRaw
    let finalDisplayed := displayed1Even.trans
      (F.displayedIsometry.trans
        (normalize.orthogonalProductBasic
          (Isometry.refl C₂.space C₂.lattice)))
    exact Omeara9318vData.ofDisplayedIsometry
      C₂.space C₂.lattice hmodular finalDisplayed

end Lattice

end Bong
