/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.OmearaSaturationFundamentalType
import Bong.Lattice.Omeara9328StepEightInvariants
import Bong.Lattice.BlockOrthogonalPairDistribution
import Bong.Lattice.ScaleTruncationIsometry

/-!
# Common componentwise adjunction of Jordan decompositions

O'Meara's reduction to saturated splittings does not replace the two given
splittings independently.  A saturated splitting of the source is adjoined
componentwise to both sides.  This file constructs that common adjunction
and proves its fundamental norm groups and saturation properties.
-/

namespace Bong

open Dyadic Module

namespace Lattice.JordanDecomposition

universe u v w x

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {W : Type w} [AddCommGroup W] [Module K W]
  {q : QuadraticSpace K V} {r : QuadraticSpace K W}
  {L : Lattice K V} {M : Lattice K W} {n : Nat}

/-- Carrier of the componentwise orthogonal adjunction. -/
abbrev commonAdjunctionCarrier
    (P : JordanDecomposition q L (n + 2))
    (J : JordanDecomposition r M (n + 2))
    (i : Fin (n + 2)) :=
  (P.component i).carrier × (J.component i).carrier

/-- Form of one componentwise orthogonal adjunction. -/
noncomputable def commonAdjunctionForm
    (P : JordanDecomposition q L (n + 2))
    (J : JordanDecomposition r M (n + 2))
    (i : Fin (n + 2)) :
    QuadraticSpace K (commonAdjunctionCarrier P J i) :=
  (P.component i).space.orthogonalSum (J.component i).space

/-- Lattice of one componentwise orthogonal adjunction. -/
noncomputable def commonAdjunctionLattice
    (P : JordanDecomposition q L (n + 2))
    (J : JordanDecomposition r M (n + 2))
    (i : Fin (n + 2)) :
    Lattice K (commonAdjunctionCarrier P J i) :=
  product (P.component i).lattice (J.component i).lattice

/-- The second component is modular at the first decomposition's displayed
scale whenever the two decompositions have the same fundamental type. -/
theorem SameFundamentalType.right_modular_at_left_scale
    {P : JordanDecomposition q L (n + 2)}
    {J : JordanDecomposition r M (n + 2)}
    (F : SameFundamentalType P J) (i : Fin (n + 2)) :
    IsModular (J.component i).space (J.component i).lattice
      (P.scaleGenerator i) :=
  (J.modular i).of_principalIdeal_eq
    (SameFundamentalType.componentScaleIdeal_eq_sameIndex P J i F)

/-- Every adjoined component is modular at the common left-hand scale. -/
theorem commonAdjunction_modular
    (P : JordanDecomposition q L (n + 2))
    (J : JordanDecomposition r M (n + 2))
    (F : SameFundamentalType P J) (i : Fin (n + 2)) :
    IsModular (commonAdjunctionForm P J i)
      (commonAdjunctionLattice P J i) (P.scaleGenerator i) :=
  (P.modular i).orthogonalProduct (F.right_modular_at_left_scale i)

/-- The common intrinsic generator is a norm generator on the right-hand
fundamental scale layer as well. -/
theorem SameFundamentalType.leftGenerator_isNormGeneratorValue_right
    {P : JordanDecomposition q L (n + 2)}
    {J : JordanDecomposition r M (n + 2)}
    (F : SameFundamentalType P J) (i : Fin (n + 2)) :
    IsNormGeneratorValue r (J.fundamentalLattice i)
      (P.fundamentalNormGenerator i) :=
  isNormGeneratorValue_of_normGroupSet_eq
    (P.fundamentalNormGenerator_spec i)
    (by
      have h := F.normGroup_eq i
      simpa only [fundamentalNormGroup,
        F.indexEquiv_apply_eq_self] using h.symm)
    (J.exists_fundamentalNormGenerator i)

/-- If the common splitting is saturated, its component dominates the norm
ideal of the right-hand component. -/
theorem commonAdjunction_right_normIdeal_le_left
    (P : JordanDecomposition q L (n + 2))
    (J : JordanDecomposition r M (n + 2))
    (F : SameFundamentalType P J)
    (i : Fin (n + 2)) :
    normIdeal (J.component i).space (J.component i).lattice ≤
      principalIdeal (K := K) (P.fundamentalNormGenerator i : K) := by
  exact (J.componentNormIdeal_le_fundamental i).trans_eq
    (F.leftGenerator_isNormGeneratorValue_right i).2

/-- The norm ideal of an adjoined component is generated by the common
fundamental norm generator. -/
theorem commonAdjunction_normIdeal_eq
    (P : JordanDecomposition q L (n + 2))
    (J : JordanDecomposition r M (n + 2))
    (F : SameFundamentalType P J) (hP : P.IsSaturated)
    (i : Fin (n + 2)) :
    normIdeal (commonAdjunctionForm P J i)
        (commonAdjunctionLattice P J i) =
      principalIdeal (K := K) (P.fundamentalNormGenerator i : K) := by
  have hmem : (P.fundamentalNormGenerator i : K) ∈
      normGroupSet (P.component i).space (P.component i).lattice := by
    rw [hP i]
    exact (P.fundamentalNormGenerator_spec i).1
  have hleft := P.fundamentalNormGenerator_isComponentNormGenerator i hmem
  rw [commonAdjunctionForm, commonAdjunctionLattice,
    normIdeal_orthogonalProduct, hleft.2]
  exact sup_eq_left.mpr (P.commonAdjunction_right_normIdeal_le_left J F i)

/-- Jordan decomposition on the coordinate product of all common
componentwise adjunctions. -/
noncomputable def commonAdjunctionJordan
    (P : JordanDecomposition q L (n + 2))
    (J : JordanDecomposition r M (n + 2))
    (F : SameFundamentalType P J) (hP : P.IsSaturated) :
    JordanDecomposition
      (BONG.blockOrthogonalForm (n + 1) (commonAdjunctionCarrier P J)
        (commonAdjunctionForm P J))
      (BONG.blockProductLattice (n + 1) (commonAdjunctionCarrier P J)
        (commonAdjunctionLattice P J))
      (n + 2) := by
  letI : ∀ i, Module.Finite K (P.component i).carrier :=
    fun i => (P.component i).lattice.moduleFinite
  letI : ∀ i, Module.Finite K (J.component i).carrier :=
    fun i => (J.component i).lattice.moduleFinite
  exact BONG.blockProductJordanDecomposition
    (commonAdjunctionCarrier P J) (commonAdjunctionForm P J)
    (commonAdjunctionLattice P J) P.scaleGenerator
    P.fundamentalNormGenerator (P.commonAdjunction_modular J F)
    (fun i => (P.commonAdjunction_modular J F i).scaleIdeal_eq_principal
      (by
        rw [Module.finrank_prod]
        have hpos := P.component_finrank_pos i
        omega))
    (P.commonAdjunction_normIdeal_eq J F hP)
    (fun _ _ hij => P.scaleOrder_strict hij)

@[simp]
theorem commonAdjunctionJordan_scaleGenerator
    (P : JordanDecomposition q L (n + 2))
    (J : JordanDecomposition r M (n + 2))
    (F : SameFundamentalType P J) (hP : P.IsSaturated)
    (i : Fin (n + 2)) :
    (P.commonAdjunctionJordan J F hP).scaleGenerator i =
      P.scaleGenerator i :=
  rfl

@[simp]
theorem commonAdjunctionJordan_componentRank
    (P : JordanDecomposition q L (n + 2))
    (J : JordanDecomposition r M (n + 2))
    (F : SameFundamentalType P J) (hP : P.IsSaturated)
    (i : Fin (n + 2)) :
    (P.commonAdjunctionJordan J F hP).componentRank i =
      P.componentRank i + J.componentRank i := by
  letI : Module.Finite K (P.component i).carrier :=
    (P.component i).lattice.moduleFinite
  letI : Module.Finite K (J.component i).carrier :=
    (J.component i).lattice.moduleFinite
  rw [commonAdjunctionJordan,
    BONG.blockProductJordanDecomposition_componentRank]
  exact Module.finrank_prod

/-- Gather the coordinate adjunction into the orthogonal product of the two
original ambient lattices. -/
noncomputable def commonAdjunctionProductIsometry
    (P : JordanDecomposition q L (n + 2))
    (J : JordanDecomposition r M (n + 2)) :
    Isometry
      (BONG.blockOrthogonalForm (n + 1) (commonAdjunctionCarrier P J)
        (commonAdjunctionForm P J))
      (q.orthogonalSum r)
      (BONG.blockProductLattice (n + 1) (commonAdjunctionCarrier P J)
        (commonAdjunctionLattice P J))
      (product L M) :=
  (BONG.blockOrthogonalPairLatticeIsometry
    (fun i => (P.component i).carrier)
    (fun i => (J.component i).carrier)
    (fun i => (P.component i).space)
    (fun i => (J.component i).space)
    (fun i => (P.component i).lattice)
    (fun i => (J.component i).lattice)).trans <|
      (BONG.orthogonalDecompositionProductIsometry
        P.toOrthogonalDecomposition).orthogonalProductBasic
          (BONG.orthogonalDecompositionProductIsometry
            J.toOrthogonalDecomposition)

/-- The common adjunction has the same intrinsic norm group as its saturated
common summand at every fundamental scale. -/
theorem commonAdjunctionJordan_fundamentalNormGroup
    (P : JordanDecomposition q L (n + 2))
    (J : JordanDecomposition r M (n + 2))
    (F : SameFundamentalType P J) (hP : P.IsSaturated)
    (i : Fin (n + 2)) :
    (P.commonAdjunctionJordan J F hP).fundamentalNormGroup i =
      P.fundamentalNormGroup i := by
  let D := P.commonAdjunctionJordan J F hP
  let f := P.commonAdjunctionProductIsometry J
  unfold fundamentalNormGroup fundamentalLattice fundamentalScaleOrder
  rw [P.commonAdjunctionJordan_scaleGenerator J F hP]
  have htransport := normGroupSet_scaleTruncation_eq_of_isometry f
    (ordUnit K (P.scaleGenerator i))
  rw [← htransport, scaleTruncation_orthogonalProduct]
  ext z
  rw [mem_normGroupSet_orthogonalProduct_iff]
  constructor
  · rintro ⟨a, ha, b, hb, rfl⟩
    apply add_mem_normGroupSet q
      (scaleTruncation q L (ordUnit K (P.scaleGenerator i))) ha
    have hgroup := F.normGroup_eq i
    rw [F.indexEquiv_apply_eq_self] at hgroup
    have hscale := F.scaleOrder_eq i
    rw [F.indexEquiv_apply_eq_self] at hscale
    unfold fundamentalNormGroup fundamentalLattice at hgroup
    rw [hscale] at hgroup
    change b ∈ normGroupSet q
      (scaleTruncation q L (P.fundamentalScaleOrder i))
    rw [← hgroup]
    exact hb
  · intro hz
    exact ⟨z, hz, 0, zero_mem_normGroupSet _ _, by simp⟩

/-- A common adjunction by a saturated splitting is saturated on either
right-hand decomposition of the same fundamental type. -/
theorem commonAdjunctionJordan_isSaturated
    (P : JordanDecomposition q L (n + 2))
    (J : JordanDecomposition r M (n + 2))
    (F : SameFundamentalType P J) (hP : P.IsSaturated) :
    (P.commonAdjunctionJordan J F hP).IsSaturated := by
  intro i
  let D := P.commonAdjunctionJordan J F hP
  let componentMap := BONG.blockProductComponentIsometry
    (commonAdjunctionCarrier P J) (commonAdjunctionForm P J)
      (commonAdjunctionLattice P J) i
  calc
    normGroupSet (D.component i).space (D.component i).lattice =
        normGroupSet (commonAdjunctionForm P J i)
          (commonAdjunctionLattice P J i) :=
      normGroupSet_eq_of_latticeIsometry componentMap
    _ = normGroupSet (P.component i).space (P.component i).lattice := by
      change normGroupSet
          ((P.component i).space.orthogonalSum (J.component i).space)
          (product (P.component i).lattice (J.component i).lattice) = _
      have hsubset : normGroupSet (J.component i).space
          (J.component i).lattice ⊆
          normGroupSet (P.component i).space
            (P.component i).lattice := by
        intro z hz
        rw [hP i]
        have hzFund : z ∈ J.fundamentalNormGroup i :=
          J.componentNormGroup_subset_fundamental i hz
        have hgroup := F.normGroup_eq i
        rw [F.indexEquiv_apply_eq_self] at hgroup
        rw [← hgroup]
        exact hzFund
      ext z
      rw [mem_normGroupSet_orthogonalProduct_iff]
      constructor
      · rintro ⟨a, ha, b, hb, rfl⟩
        exact add_mem_normGroupSet (P.component i).space
          (P.component i).lattice ha (hsubset hb)
      · intro hz
        exact ⟨z, hz, 0, zero_mem_normGroupSet _ _, by simp⟩
    _ = P.fundamentalNormGroup i := hP i
    _ = D.fundamentalNormGroup i :=
      (P.commonAdjunctionJordan_fundamentalNormGroup J F hP i).symm

/-- Adjoining the same saturated splitting to two decompositions preserves
their complete fundamental type. -/
noncomputable def SameFundamentalType.commonAdjunction
    {P : JordanDecomposition q L (n + 2)}
    {J : JordanDecomposition r M (n + 2)}
    {W' : Type x} [AddCommGroup W'] [Module K W']
    {r' : QuadraticSpace K W'} {M' : Lattice K W'}
    {H : JordanDecomposition r' M' (n + 2)}
    (FPJ : SameFundamentalType P J)
    (FPH : SameFundamentalType P H)
    (FJH : SameFundamentalType J H)
    (hP : P.IsSaturated) :
    SameFundamentalType (P.commonAdjunctionJordan J FPJ hP)
      (P.commonAdjunctionJordan H FPH hP) where
  indexEquiv := Equiv.refl _
  index_val := fun _ => rfl
  componentRank_eq := by
    intro i
    simp only [Equiv.refl_apply,
      P.commonAdjunctionJordan_componentRank J FPJ hP,
      P.commonAdjunctionJordan_componentRank H FPH hP]
    have h := FJH.componentRank_eq i
    rw [FJH.indexEquiv_apply_eq_self] at h
    omega
  scaleOrder_eq := by
    intro i
    unfold fundamentalScaleOrder
    rfl
  normGroup_eq := by
    intro i
    simp only [Equiv.refl_apply,
      P.commonAdjunctionJordan_fundamentalNormGroup J FPJ hP,
      P.commonAdjunctionJordan_fundamentalNormGroup H FPH hP]

end Lattice.JordanDecomposition

end Bong
