/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.OmearaBinaryExchange
import Bong.Lattice.HyperbolicLatticeInvariants
import Bong.Lattice.Omeara9318OddRankFiveSix
import Bong.Lattice.OmearaModularScaleTruncation
import Bong.Lattice.OmearaStableModularCancellation

/-!
# O'Meara 93:19 from the high-rank hyperbolic splitting

This file formalizes the stable coefficient-shift calculation in 93:19.
The four-dimensional exchange is concrete.  The only input not constructed
inside this file is an explicit 93:18(v) certificate for the rank-at-least-
five modular complement created by that exchange.
-/

namespace Bong

open Dyadic Module

namespace Lattice

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  [laws : DyadicDiscriminantClassLaws K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {q : QuadraticSpace K V} {L : Lattice K V} {s : Kˣ}

/-- Scalar and integrality data in the middle calculation of 93:19. -/
structure Omeara9319ExchangeSetup
    (q : QuadraticSpace K V) (L : Lattice K V) (s : Kˣ) where
  alpha : K
  beta : K
  delta : K
  gamma : K
  alpha_integral : alpha ∈ IntegerRing K
  beta_integral : beta ∈ IntegerRing K
  gamma_integral : gamma ∈ IntegerRing K
  scale_integral : (s : K) ∈ IntegerRing K
  old_determinant_unit : IsValuationUnit K (alpha * beta - 1)
  new_determinant_unit :
    IsValuationUnit K ((alpha + (s : K) * gamma) * beta - 1)
  delta_mem : delta ∈ normGroupSet q L
  delta_eq : delta = (s : K) * gamma

namespace Omeara9319ExchangeSetup

variable (E : Omeara9319ExchangeSetup q L s)

/-- For a positive-rank `s`-modular lattice, the error ideal `2sL` is
the principal ideal generated by `2s`. -/
theorem twoScaleIdeal_eq_principalIdeal_two_mul_of_modular
    {W : Type v} [AddCommGroup W] [Module K W]
    {r : QuadraticSpace K W} {M : Lattice K W} {a : Kˣ}
    (hmodular : IsModular r M a) (hpos : 0 < finrank K W) :
    twoScaleIdeal r M = principalIdeal (K := K) (2 * (a : K)) := by
  rw [twoScaleIdeal, hmodular.scaleIdeal_eq_principal hpos,
    twiceIdeal_principalIdeal]

/-- The original displayed unimodular plane. -/
noncomputable def oldPlane : QuadraticSpace K (Fin 2 → K) :=
  QuadraticSpace.omearaGeneralPlane E.alpha E.beta
    (sub_ne_zero.mp
      (omearaExchange_ne_zero_of_isValuationUnit
        E.old_determinant_unit))

/-- The plane after adding `delta` to its first coefficient. -/
noncomputable def newPlane : QuadraticSpace K (Fin 2 → K) :=
  QuadraticSpace.omearaGeneralPlane
    (E.alpha + (s : K) * E.gamma) E.beta
    (sub_ne_zero.mp
      (omearaExchange_ne_zero_of_isValuationUnit
        E.new_determinant_unit))

/-- The scaled zero-right plane adjoined before the exchange. -/
noncomputable def correctionPlane : QuadraticSpace K (Fin 2 → K) :=
  (QuadraticSpace.omearaPlane E.gamma).rescaleUnit s

/-- The binary modular complement left by the exchange. -/
noncomputable def exchangeComplement : QuadraticSpace K (Fin 2 → K) :=
  QuadraticSpace.omearaExchangeComplement
    E.alpha E.beta E.gamma (s : K) (Units.ne_zero s)
      (sub_ne_zero.mp
        (omearaExchange_ne_zero_of_isValuationUnit
          E.old_determinant_unit))
      (sub_ne_zero.mp
        (omearaExchange_ne_zero_of_isValuationUnit
          E.new_determinant_unit))

/-- The exchange complement is modular at scale `s`. -/
theorem exchangeComplement_modular :
    IsModular E.exchangeComplement
      (hyperbolicPlaneLattice (K := K)) s := by
  exact omearaExchangeComplement_isModular
    E.alpha E.beta E.gamma s E.alpha_integral E.beta_integral
      E.gamma_integral (scale_integral E) E.old_determinant_unit
      E.new_determinant_unit

/-- The exchanged complement together with the original modular lattice is
again `s`-modular. -/
theorem exchangedTail_modular (hL : IsModular q L s) :
    IsModular (E.exchangeComplement.orthogonalSum q)
      (product (hyperbolicPlaneLattice (K := K)) L) s :=
  E.exchangeComplement_modular.orthogonalProduct hL

/-- The concrete four-dimensional exchange in the notation of the setup. -/
noncomputable def binaryExchange :
    Isometry (E.newPlane.orthogonalSum E.exchangeComplement)
      (E.oldPlane.orthogonalSum E.correctionPlane)
      (product (hyperbolicPlaneLattice (K := K))
        (hyperbolicPlaneLattice (K := K)))
      (product (hyperbolicPlaneLattice (K := K))
        (hyperbolicPlaneLattice (K := K))) := by
  exact omearaBinaryExchangeLatticeIsometry
    E.alpha E.beta E.gamma s E.alpha_integral E.beta_integral
      E.gamma_integral (scale_integral E) E.old_determinant_unit
      E.new_determinant_unit

/-- The norm-group correction belongs to the modular scale truncation. -/
theorem delta_mem_truncation (hL : IsModular q L s) :
    E.delta ∈ normGroupSet q (omearaScaleTruncation q L s) := by
  rw [omearaScaleTruncation_eq_of_isModular hL]
  exact E.delta_mem

/-- O'Meara 93:13 changes the adjoined `s A(gamma,0)` into the standard
scaled hyperbolic plane while leaving `L` fixed. -/
noncomputable def correctionPlaneToHyperbolic
    (hL : IsModular q L s) :
    Isometry (E.correctionPlane.orthogonalSum q)
      ((QuadraticSpace.hyperbolicPlane s).orthogonalSum q)
      (product (hyperbolicPlaneLattice (K := K)) L)
      (product (hyperbolicPlaneLattice (K := K)) L) := by
  have hcoefficient :
      0 + ((s⁻¹ : Kˣ) : K) * E.delta = E.gamma := by
    rw [E.delta_eq]
    simp [Units.ne_zero s]
  let shiftRaw := omeara9313 q L s 0 E.delta
    (E.delta_mem_truncation hL)
  let shift : Isometry
      (E.correctionPlane.orthogonalSum q)
      (((QuadraticSpace.omearaPlane (K := K) 0).rescaleUnit s).orthogonalSum q)
      (product (hyperbolicPlaneLattice (K := K)) L)
      (product (hyperbolicPlaneLattice (K := K)) L) := by
    simpa only [correctionPlane, hcoefficient] using shiftRaw
  let identify :=
    (scaledZeroOmearaPlaneLatticeIsometry s).orthogonalProductBasic
      (Isometry.refl q L)
  exact shift.trans identify

/-- O'Meara 93:19 after supplying the concrete 93:18(v) splitting of the
rank-at-least-five modular tail created by the binary exchange.  Every other
map in the proof is explicit: 93:13, the four-dimensional exchange,
reassociation, and 93:14 cancellation. -/
noncomputable def coefficientShiftOf9318v
    (hL : IsModular q L s)
    (D : Omeara9318vData
      (E.exchangeComplement.orthogonalSum q)
      (product (hyperbolicPlaneLattice (K := K)) L) s) :
    Isometry (E.oldPlane.orthogonalSum q)
      (E.newPlane.orthogonalSum (D.decomposition.component 1).space)
      (product (hyperbolicPlaneLattice (K := K)) L)
      (product (hyperbolicPlaneLattice (K := K))
        (D.decomposition.component 1).lattice) := by
  let oldIdentity :=
    Isometry.refl E.oldPlane (hyperbolicPlaneLattice (K := K))
  let newIdentity :=
    Isometry.refl E.newPlane (hyperbolicPlaneLattice (K := K))
  let qIdentity := Isometry.refl q L
  let insertCorrection : Isometry
      (E.oldPlane.orthogonalSum
        ((QuadraticSpace.hyperbolicPlane s).orthogonalSum q))
      (E.oldPlane.orthogonalSum
        (E.correctionPlane.orthogonalSum q))
      (product (hyperbolicPlaneLattice (K := K))
        (product (hyperbolicPlaneLattice (K := K)) L))
      (product (hyperbolicPlaneLattice (K := K))
        (product (hyperbolicPlaneLattice (K := K)) L)) :=
    oldIdentity.orthogonalProductBasic
      (E.correctionPlaneToHyperbolic hL).symm
  let exposeExchange : Isometry
      (E.oldPlane.orthogonalSum
        (E.correctionPlane.orthogonalSum q))
      ((E.oldPlane.orthogonalSum E.correctionPlane).orthogonalSum q)
      (product (hyperbolicPlaneLattice (K := K))
        (product (hyperbolicPlaneLattice (K := K)) L))
      (product
        (product (hyperbolicPlaneLattice (K := K))
          (hyperbolicPlaneLattice (K := K))) L) :=
    orthogonalProductAssoc.symm
  let exchange : Isometry
      ((E.oldPlane.orthogonalSum E.correctionPlane).orthogonalSum q)
      ((E.newPlane.orthogonalSum E.exchangeComplement).orthogonalSum q)
      (product
        (product (hyperbolicPlaneLattice (K := K))
          (hyperbolicPlaneLattice (K := K))) L)
      (product
        (product (hyperbolicPlaneLattice (K := K))
          (hyperbolicPlaneLattice (K := K))) L) :=
    E.binaryExchange.symm.orthogonalProductBasic qIdentity
  let hideExchange : Isometry
      ((E.newPlane.orthogonalSum E.exchangeComplement).orthogonalSum q)
      (E.newPlane.orthogonalSum
        (E.exchangeComplement.orthogonalSum q))
      (product
        (product (hyperbolicPlaneLattice (K := K))
          (hyperbolicPlaneLattice (K := K))) L)
      (product (hyperbolicPlaneLattice (K := K))
        (product (hyperbolicPlaneLattice (K := K)) L)) :=
    orthogonalProductAssoc
  let splitTail : Isometry
      (E.newPlane.orthogonalSum
        (E.exchangeComplement.orthogonalSum q))
      (E.newPlane.orthogonalSum
        ((QuadraticSpace.hyperbolicPlane s).orthogonalSum
          (D.decomposition.component 1).space))
      (product (hyperbolicPlaneLattice (K := K))
        (product (hyperbolicPlaneLattice (K := K)) L))
      (product (hyperbolicPlaneLattice (K := K))
        (product (hyperbolicPlaneLattice (K := K))
          (D.decomposition.component 1).lattice)) :=
    newIdentity.orthogonalProductBasic D.displayedIsometry
  let middle := insertCorrection.trans
    (exposeExchange.trans (exchange.trans (hideExchange.trans splitTail)))
  let sourcePermutation : Isometry
      (E.oldPlane.orthogonalSum
        ((QuadraticSpace.hyperbolicPlane s).orthogonalSum q))
      ((QuadraticSpace.hyperbolicPlane s).orthogonalSum
        (E.oldPlane.orthogonalSum q))
      (product (hyperbolicPlaneLattice (K := K))
        (product (hyperbolicPlaneLattice (K := K)) L))
      (product (hyperbolicPlaneLattice (K := K))
        (product (hyperbolicPlaneLattice (K := K)) L)) :=
    orthogonalProductRotateLeft.trans orthogonalProductAssoc
  let targetPermutation : Isometry
      (E.newPlane.orthogonalSum
        ((QuadraticSpace.hyperbolicPlane s).orthogonalSum
          (D.decomposition.component 1).space))
      ((QuadraticSpace.hyperbolicPlane s).orthogonalSum
        (E.newPlane.orthogonalSum
          (D.decomposition.component 1).space))
      (product (hyperbolicPlaneLattice (K := K))
        (product (hyperbolicPlaneLattice (K := K))
          (D.decomposition.component 1).lattice))
      (product (hyperbolicPlaneLattice (K := K))
        (product (hyperbolicPlaneLattice (K := K))
          (D.decomposition.component 1).lattice)) :=
    orthogonalProductRotateLeft.trans orthogonalProductAssoc
  let stabilized := sourcePermutation.symm.trans
    (middle.trans targetPermutation)
  exact omeara9314_scaled_of_isometric_summand s
    (Isometry.refl (QuadraticSpace.hyperbolicPlane s)
      (hyperbolicPlaneLattice (K := K)))
    (Isometry.refl (QuadraticSpace.hyperbolicPlane s)
      (hyperbolicPlaneLattice (K := K))) stabilized

/-- Removing the displayed rank-two hyperbolic factor from the exchanged
tail leaves a complement of the same rank as the original modular lattice. -/
theorem complement_finrank_of9318v
    (D : Omeara9318vData
      (E.exchangeComplement.orthogonalSum q)
      (product (hyperbolicPlaneLattice (K := K)) L) s) :
    finrank K (D.decomposition.component 1).carrier = finrank K V := by
  letI : Module.Finite K V := L.moduleFinite
  let H := D.decomposition.component 0
  let C := D.decomposition.component 1
  letI : Module.Finite K H.carrier := H.lattice.moduleFinite
  letI : Module.Finite K C.carrier := C.lattice.moduleFinite
  have hHrank : finrank K H.carrier = 2 := by
    calc
      finrank K H.carrier = finrank K (Fin 2 → K) :=
        D.hyperbolic.toLinearEquiv.finrank_eq
      _ = 2 := by simp
  have htotal :=
    D.decomposition.pairProductLatticeIsometry.toLinearEquiv.finrank_eq
  have htotal' : 2 + finrank K C.carrier = 2 + finrank K V := by
    change finrank K (H.carrier × C.carrier) =
      finrank K ((Fin 2 → K) × V) at htotal
    simpa only [Module.finrank_prod, hHrank,
      Module.finrank_fin_fun] using htotal
  exact Nat.add_left_cancel htotal'

/-- The inclusion `gL ⊆ gK` printed in O'Meara 93:19.  Under the
93:18(v) splitting, an element of `gL` becomes a sum of an element of the
scaled hyperbolic norm group and an element of `gK`.  The first summand lies
in `2sO`, which is already contained in `gK`. -/
theorem normGroupSet_subset_complement_of9318v
    (hrank : 3 ≤ finrank K V)
    (D : Omeara9318vData
      (E.exchangeComplement.orthogonalSum q)
      (product (hyperbolicPlaneLattice (K := K)) L) s) :
    normGroupSet q L ⊆
      normGroupSet (D.decomposition.component 1).space
        (D.decomposition.component 1).lattice := by
  let C := D.decomposition.component 1
  have hCpos : 0 < finrank K C.carrier := by
    rw [E.complement_finrank_of9318v D]
    omega
  have hCtwo : twoScaleIdeal C.space C.lattice =
      principalIdeal (K := K) (2 * (s : K)) :=
    twoScaleIdeal_eq_principalIdeal_two_mul_of_modular
      D.complement_modular hCpos
  intro z hz
  have hzTail : z ∈ normGroupSet
      (E.exchangeComplement.orthogonalSum q)
      (product (hyperbolicPlaneLattice (K := K)) L) := by
    rw [mem_normGroupSet_orthogonalProduct_iff]
    exact ⟨0, zero_mem_normGroupSet E.exchangeComplement
      (hyperbolicPlaneLattice (K := K)), z, hz, by simp⟩
  have hzSplit : z ∈ normGroupSet
      ((QuadraticSpace.hyperbolicPlane s).orthogonalSum C.space)
      (product (hyperbolicPlaneLattice (K := K)) C.lattice) := by
    rw [normGroupSet_eq_of_latticeIsometry D.displayedIsometry]
    exact hzTail
  rw [mem_normGroupSet_orthogonalProduct_iff] at hzSplit
  rcases hzSplit with ⟨h, hh, k, hk, rfl⟩
  have hhIdeal : h ∈ principalIdeal (K := K) (2 * (s : K)) := by
    rw [← normIdeal_hyperbolicPlaneLattice s]
    exact normGroupSet_subset_normIdeal
      (QuadraticSpace.hyperbolicPlane s)
      (hyperbolicPlaneLattice (K := K)) hh
  have hhC : h ∈ normGroupSet C.space C.lattice := by
    apply twoScaleIdeal_subset_normGroupSet C.space C.lattice
    rw [hCtwo]
    exact hhIdeal
  exact add_mem_normGroupSet C.space C.lattice hhC hk

/-- Fully constructed output of O'Meara 93:19.  The field `splitting`
records the actual lattice `K`; `shifted` is the claimed integral isometry,
and `normGroup_subset` is the theorem's final `gL ⊆ gK` clause. -/
structure Omeara9319Data
    (E : Omeara9319ExchangeSetup q L s) where
  splitting : Omeara9318vData
    (E.exchangeComplement.orthogonalSum q)
    (product (hyperbolicPlaneLattice (K := K)) L) s
  shifted : Isometry (E.oldPlane.orthogonalSum q)
    (E.newPlane.orthogonalSum (splitting.decomposition.component 1).space)
    (product (hyperbolicPlaneLattice (K := K)) L)
    (product (hyperbolicPlaneLattice (K := K))
      (splitting.decomposition.component 1).lattice)
  normGroup_subset : normGroupSet q L ⊆
    normGroupSet (splitting.decomposition.component 1).space
      (splitting.decomposition.component 1).lattice

/-- O'Meara 93:19 with its 93:18(v) input constructed internally. -/
noncomputable def coefficientShift
    (hL : IsModular q L s) (hrank : 3 ≤ finrank K V) :
    Omeara9319Data E := by
  letI : Module.Finite K V := L.moduleFinite
  let tail := E.exchangeComplement.orthogonalSum q
  let tailLattice : Lattice K ((Fin 2 → K) × V) :=
    product (hyperbolicPlaneLattice (K := K)) L
  have htailRank : 5 ≤ finrank K ((Fin 2 → K) × V) := by
    rw [Module.finrank_prod, Module.finrank_fin_fun]
    omega
  let D : Omeara9318vData tail tailLattice s :=
    omeara9318vDataOfOddRankFiveOrSix
      (omeara9318vOddRankFiveOrSix (K := K)) tail tailLattice s
        (E.exchangedTail_modular hL) htailRank
  exact
    { splitting := D
      shifted := E.coefficientShiftOf9318v hL D
      normGroup_subset := E.normGroupSet_subset_complement_of9318v hrank D }

end Omeara9319ExchangeSetup

end Lattice

end Bong
