/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.OmearaFundamentalIdealMaximal

/-!
# Binary discriminants at an O'Meara fundamental boundary

This file isolates the ``direct calculation from the definition of `f_i`''
used in the necessity proof of O'Meara 93:28.  If one diagonal value belongs
to the left fundamental norm group and the negative of the other belongs to
the right fundamental norm group, then the binary determinant differs from
the negative of a square by an element of the scaled fundamental ideal.

The even case is the substantive one.  The two norm-group square-coset
expansions contribute the product-defect and cross ideals, while the cross
term in the final square is exactly absorbed by the dyadic parity ideal.
-/

namespace Bong

open Dyadic Module

namespace Lattice

universe u

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]

/-- Products of elements in two principal ideals belong to the principal
ideal generated by the product. -/
theorem mul_mem_principalIdeal_mul
    {a b x y : K}
    (hx : x ∈ principalIdeal (K := K) a)
    (hy : y ∈ principalIdeal (K := K) b) :
    x * y ∈ principalIdeal (K := K) (a * b) := by
  rw [principalIdeal, Submodule.mem_span_singleton] at hx hy ⊢
  rcases hx with ⟨c, hc⟩
  rcases hy with ⟨d, hd⟩
  refine ⟨c * d, ?_⟩
  have hcx : algebraMap (IntegerRing K) K c * a = x := by
    simpa only [Algebra.smul_def] using hc
  have hdy : algebraMap (IntegerRing K) K d * b = y := by
    simpa only [Algebra.smul_def] using hd
  change algebraMap (IntegerRing K) K (c * d) * (a * b) = x * y
  rw [map_mul]
  rw [← hcx, ← hdy]
  ring

/-- An integral scalar preserves membership in a coefficient ideal.  This
version lives in the boundary-ideal layer so that the binary calculation
does not depend on the later orthogonalized-basis construction. -/
theorem mul_mem_coefficientIdeal_of_isIntegral_left_boundary
    {a x : K} {I : CoefficientIdeal (K := K)}
    (ha : Dyadic.IsIntegral K a) (hx : x ∈ I) : a * x ∈ I := by
  let aO : IntegerRing K := ⟨a, (mem_integerRing_iff K).2 ha⟩
  have h := I.smul_mem aO hx
  change a * x ∈ I at h
  exact h

/-- At an even valuation, a scalar whose square is divisible by `ab` is
divisible by the half-order ideal. -/
theorem mem_halfPowerIdeal_of_sq_mem_principalIdeal_mul
    (a b : Kˣ) (hEven : Even (ordUnit K a + ordUnit K b))
    {x : K}
    (hx : x ^ 2 ∈ principalIdeal (K := K) ((a * b : Kˣ) : K)) :
    x ∈ powerIdeal (K := K) ((ordUnit K a + ordUnit K b) / 2) := by
  by_cases hzero : x = 0
  · subst x
    exact Submodule.zero_mem _
  · let xu : Kˣ := Units.mk0 x hzero
    have hordx : ord K x = ((ordUnit K xu : Int) : WithTop Int) := by
      symm
      simpa only [xu, Units.val_mk0] using coe_ordUnit K xu
    have hxOrder : ordUnit K a + ordUnit K b ≤ 2 * ordUnit K xu := by
      rw [principalIdeal_eq_powerIdeal, mem_powerIdeal_iff,
        ord_pow, ordUnit_mul, hordx] at hx
      exact_mod_cast hx
    rw [mem_powerIdeal_iff, hordx]
    apply WithTop.coe_le_coe.mpr
    rcases hEven with ⟨m, hm⟩
    omega

namespace JordanDecomposition

universe v

variable {V : Type v} [AddCommGroup V] [Module K V]
  {q : QuadraticSpace K V} {L : Lattice K V} {t : Nat}

/-- The ideal-valued binary determinant calculation underlying Step 1 of
the necessity proof of O'Meara 93:28.

Here `x` is a value in the left fundamental norm group, `-z` is a value in
the right group, and `p` is a pairing at the left scale.  The theorem
constructs the square adjustment whose negative represents the binary
discriminant modulo the scaled fundamental ideal. -/
theorem exists_binaryDeterminant_squareAdjuster_mem_scaledFundamentalIdeal_with_order
    (J : JordanDecomposition q L (t + 1)) (i : Fin t)
    {x z p : K}
    (hx : x ∈ J.fundamentalNormGroup (boundaryLeftIndex i))
    (hz : -z ∈ J.fundamentalNormGroup (boundaryRightIndex i))
    (hp : p ∈ principalIdeal (K := K)
      (J.scaleGenerator (boundaryLeftIndex i) : K)) :
    ∃ r : K,
      x * z - p ^ 2 + r ^ 2 ∈ J.scaledFundamentalIdeal i ∧
      (ordUnit K (J.fundamentalNormGenerator (boundaryLeftIndex i)) <
          ordUnit K (J.fundamentalNormGenerator (boundaryRightIndex i)) →
        ord K p =
          ((J.fundamentalScaleOrder (boundaryLeftIndex i) : Int) :
            WithTop Int) →
        ord K r =
          ((J.fundamentalScaleOrder (boundaryLeftIndex i) : Int) :
            WithTop Int)) := by
  let li : Fin (t + 1) := boundaryLeftIndex i
  let ri : Fin (t + 1) := boundaryRightIndex i
  let a : Kˣ := J.fundamentalNormGenerator li
  let b : Kˣ := J.fundamentalNormGenerator ri
  by_cases hEven : Even (J.boundaryNormOrderSum i)
  · have hEven' : Even (ordUnit K a + ordUnit K b) := by
      simpa only [a, b, li, ri, boundaryNormOrderSum] using hEven
    have hxCoset : x ∈ integralSquareCoset (a : K)
        (J.fundamentalWeightIdeal li) := by
      have hx' : x ∈ normGroupSet q (J.fundamentalLattice li) := by
        simpa only [fundamentalNormGroup, li] using hx
      rw [normGroupSet_eq_integralSquareCoset_weightIdeal a
        (J.fundamentalNormGenerator_spec li)] at hx'
      simpa only [fundamentalWeightIdeal] using hx'
    have hzCoset : -z ∈ integralSquareCoset (b : K)
        (J.fundamentalWeightIdeal ri) := by
      have hz' : -z ∈ normGroupSet q (J.fundamentalLattice ri) := by
        simpa only [fundamentalNormGroup, ri] using hz
      rw [normGroupSet_eq_integralSquareCoset_weightIdeal b
        (J.fundamentalNormGenerator_spec ri)] at hz'
      simpa only [fundamentalWeightIdeal] using hz'
    rcases hxCoset with ⟨c, y, hy, hxy⟩
    rcases hzCoset with ⟨d, w, hw, hzw⟩
    rcases exists_sub_sq_mem_quadraticDefectIdeal (a * b) with
      ⟨s, hs⟩
    let r : K := p + s * (c : K) * (d : K)
    have hdefectScaled :
        -(((a * b : Kˣ) : K) - s ^ 2) * (c : K) ^ 2 * (d : K) ^ 2 ∈
          quadraticDefectIdeal (a * b) := by
      have hscaled := (quadraticDefectIdeal (a * b)).smul_mem
        ((c ^ 2) * (d ^ 2)) hs
      change (((c ^ 2) * (d ^ 2) : IntegerRing K) : K) *
          (((a * b : Kˣ) : K) - s ^ 2) ∈
        quadraticDefectIdeal (a * b) at hscaled
      have hcoe : (((c ^ 2) * (d ^ 2) : IntegerRing K) : K) =
          (c : K) ^ 2 * (d : K) ^ 2 := by norm_cast
      rw [hcoe] at hscaled
      have hneg := (quadraticDefectIdeal (a * b)).neg_mem hscaled
      convert hneg using 1 <;> ring
    have haY : -((a : K) * (c : K) ^ 2 * w) ∈
        scalarIdeal (a : K) (J.fundamentalWeightIdeal ri) := by
      have hraw : (a : K) * (c : K) ^ 2 * w ∈
          scalarIdeal (a : K) (J.fundamentalWeightIdeal ri) := by
        refine ⟨(c ^ 2) • w,
          (J.fundamentalWeightIdeal ri).smul_mem (c ^ 2) hw, ?_⟩
        simp only [coefficientMulLinearMap_apply, Algebra.smul_def]
        rw [ValuationSubring.algebraMap_apply (IntegerRing K) (c ^ 2)]
        have hcPow : ((c ^ 2 : IntegerRing K) : K) = (c : K) ^ 2 := by
          norm_cast
        rw [hcPow]
        ring
      exact (scalarIdeal (a : K)
        (J.fundamentalWeightIdeal ri)).neg_mem hraw
    have hbX : -((b : K) * (d : K) ^ 2 * y) ∈
        scalarIdeal (b : K) (J.fundamentalWeightIdeal li) := by
      have hraw : (b : K) * (d : K) ^ 2 * y ∈
          scalarIdeal (b : K) (J.fundamentalWeightIdeal li) := by
        refine ⟨(d ^ 2) • y,
          (J.fundamentalWeightIdeal li).smul_mem (d ^ 2) hy, ?_⟩
        simp only [coefficientMulLinearMap_apply, Algebra.smul_def]
        rw [ValuationSubring.algebraMap_apply (IntegerRing K) (d ^ 2)]
        have hdPow : ((d ^ 2 : IntegerRing K) : K) = (d : K) ^ 2 := by
          norm_cast
        rw [hdPow]
        ring
      exact (scalarIdeal (b : K)
        (J.fundamentalWeightIdeal li)).neg_mem hraw
    have hXY : -(y * w) ∈
        scalarIdeal (a : K) (J.fundamentalWeightIdeal ri) := by
      have hyPrincipal : y ∈ principalIdeal (K := K) (a : K) :=
        weightIdeal_le_principalIdeal a
          (J.fundamentalNormGenerator_spec li) hy
      rw [principalIdeal, Submodule.mem_span_singleton] at hyPrincipal
      rcases hyPrincipal with ⟨e, he⟩
      have hraw : y * w ∈
          scalarIdeal (a : K) (J.fundamentalWeightIdeal ri) := by
        refine ⟨e • w,
          (J.fundamentalWeightIdeal ri).smul_mem e hw, ?_⟩
        simp only [coefficientMulLinearMap_apply, Algebra.smul_def]
        have he' : algebraMap (IntegerRing K) K e * (a : K) = y := by
          simpa only [Algebra.smul_def] using he
        rw [← he']
        rw [ValuationSubring.algebraMap_apply (IntegerRing K) e]
        ring
      exact (scalarIdeal (a : K)
        (J.fundamentalWeightIdeal ri)).neg_mem hraw
    let core : CoefficientIdeal (K := K) :=
      (quadraticDefectIdeal (a * b) ⊔
        scalarIdeal (a : K) (J.fundamentalWeightIdeal ri)) ⊔
        scalarIdeal (b : K) (J.fundamentalWeightIdeal li)
    have hcore :
        -(((a * b : Kˣ) : K) - s ^ 2) * (c : K) ^ 2 * (d : K) ^ 2 -
              (a : K) * (c : K) ^ 2 * w -
            (b : K) * (d : K) ^ 2 * y - y * w ∈ core := by
      have hD :
          -(((a * b : Kˣ) : K) - s ^ 2) * (c : K) ^ 2 * (d : K) ^ 2 ∈
            core := by
        exact (show quadraticDefectIdeal (a * b) ≤ core from
          _root_.le_sup_left.trans _root_.le_sup_left) hdefectScaled
      have hAY : -((a : K) * (c : K) ^ 2 * w) ∈ core :=
        (show scalarIdeal (a : K) (J.fundamentalWeightIdeal ri) ≤ core from
          _root_.le_sup_right.trans _root_.le_sup_left) haY
      have hBX : -((b : K) * (d : K) ^ 2 * y) ∈ core :=
        (show scalarIdeal (b : K) (J.fundamentalWeightIdeal li) ≤ core from
          _root_.le_sup_right) hbX
      have hYX : -(y * w) ∈ core :=
        (show scalarIdeal (a : K) (J.fundamentalWeightIdeal ri) ≤ core from
          _root_.le_sup_right.trans _root_.le_sup_left) hXY
      convert core.add_mem (core.add_mem (core.add_mem hD hAY) hBX) hYX
        using 1 <;> ring
    have hsPrincipal : s ^ 2 ∈
        principalIdeal (K := K) ((a * b : Kˣ) : K) := by
      have herr := quadraticDefectIdeal_le_principalIdeal (a * b) hs
      have hab := generator_mem_principalIdeal (K := K) ((a * b : Kˣ) : K)
      convert (principalIdeal (K := K) ((a * b : Kˣ) : K)).sub_mem hab herr
        using 1 <;> ring
    have hsHalf : s ∈ powerIdeal (K := K)
        ((ordUnit K a + ordUnit K b) / 2) :=
      mem_halfPowerIdeal_of_sq_mem_principalIdeal_mul a b hEven' hsPrincipal
    have hcdIntegral : Dyadic.IsIntegral K ((c : K) * (d : K)) :=
      isIntegral_mul K c.property d.property
    have hscdHalf : s * (c : K) * (d : K) ∈ powerIdeal (K := K)
        ((ordUnit K a + ordUnit K b) / 2) := by
      have hmul := mul_mem_coefficientIdeal_of_isIntegral_left_boundary
        hcdIntegral hsHalf
      simpa only [mul_assoc, mul_comm, mul_left_comm] using hmul
    have hpPower : p ∈ powerIdeal (K := K) (J.fundamentalScaleOrder li) := by
      have hp' := hp
      rw [principalIdeal_eq_powerIdeal] at hp'
      simpa only [fundamentalScaleOrder, li] using hp'
    have hpairProduct : p * (s * (c : K) * (d : K)) ∈
        powerIdeal (K := K)
          (J.fundamentalScaleOrder li +
            (ordUnit K a + ordUnit K b) / 2) := by
      rw [mem_powerIdeal_iff] at hpPower hscdHalf ⊢
      rw [ord_mul]
      calc
        ((J.fundamentalScaleOrder li +
            (ordUnit K a + ordUnit K b) / 2 : Int) : WithTop Int) =
            (J.fundamentalScaleOrder li : WithTop Int) +
              (((ordUnit K a + ordUnit K b) / 2 : Int) : WithTop Int) := by
                norm_cast
        _ ≤ ord K p + ord K (s * (c : K) * (d : K)) :=
          add_le_add hpPower hscdHalf
    have hparity : (2 : K) * p * (s * (c : K) * (d : K)) ∈
        J.boundaryParityIdeal i := by
      have hpairOrder :
          ((J.fundamentalScaleOrder li +
              (ordUnit K a + ordUnit K b) / 2 : Int) : WithTop Int) ≤
            ord K (p * (s * (c : K) * (d : K))) := by
        simpa only [mem_powerIdeal_iff] using hpairProduct
      unfold boundaryParityIdeal
      rw [twiceIdeal_powerIdeal, mem_powerIdeal_iff]
      have htwo : ord K (2 : K) =
          ((ramificationIndex K : Int) : WithTop Int) :=
        (ramificationIndex_spec K).symm
      have hproductAssoc :
          (2 : K) * p * (s * (c : K) * (d : K)) =
            (2 : K) * (p * (s * (c : K) * (d : K))) := by ring
      rw [hproductAssoc, ord_mul, htwo]
      have hsum : J.boundaryNormOrderSum i =
          ordUnit K a + ordUnit K b := by
        simp only [boundaryNormOrderSum, a, b, li, ri]
      rw [hsum]
      calc
        ((((ordUnit K a + ordUnit K b) / 2 +
              J.fundamentalScaleOrder li) + ramificationIndex K : Int) :
            WithTop Int) =
            (ramificationIndex K : WithTop Int) +
              ((J.fundamentalScaleOrder li +
                (ordUnit K a + ordUnit K b) / 2 : Int) : WithTop Int) := by
                  norm_cast
                  ring
        _ ≤ (ramificationIndex K : WithTop Int) +
            ord K (p * (s * (c : K) * (d : K))) :=
          by simpa only [add_comm] using
            (add_le_add_left hpairOrder
              (ramificationIndex K : WithTop Int))
    have hmain : x * z - p ^ 2 + r ^ 2 ∈
        core ⊔ J.boundaryParityIdeal i := by
      have hcore' : x * z + (s * (c : K) * (d : K)) ^ 2 ∈ core := by
        have hzEq : z = -((b : K) * (d : K) ^ 2 + w) := by
          linear_combination -hzw
        rw [hxy, hzEq]
        have hcoreVal := hcore
        simp only [Units.val_mul] at hcoreVal
        convert hcoreVal using 1 <;> ring
      have hparity' : 2 * p * (s * (c : K) * (d : K)) ∈
          core ⊔ J.boundaryParityIdeal i :=
        (show J.boundaryParityIdeal i ≤
          core ⊔ J.boundaryParityIdeal i from _root_.le_sup_right) hparity
      have hcoreSup : x * z + (s * (c : K) * (d : K)) ^ 2 ∈
          core ⊔ J.boundaryParityIdeal i :=
        (show core ≤ core ⊔ J.boundaryParityIdeal i from
          _root_.le_sup_left) hcore'
      dsimp only [r]
      convert (core ⊔ J.boundaryParityIdeal i).add_mem hcoreSup hparity'
        using 1 <;> ring
    refine ⟨r, ?_, ?_⟩
    · rw [J.scaledFundamentalIdeal_eq_even_formula i hEven]
      simpa only [core, a, b, li, ri] using hmain
    · intro hnormStrict hpExact
      have hnormStrict' : ordUnit K a < ordUnit K b := by
        simpa only [a, b, li, ri] using hnormStrict
      have hscaleLe : J.fundamentalScaleOrder li ≤ ordUnit K a :=
        J.fundamentalScaleOrder_le_normGeneratorOrder li
      have hhalfStrict : J.fundamentalScaleOrder li <
          (ordUnit K a + ordUnit K b) / 2 := by
        rcases hEven' with ⟨m, hm⟩
        omega
      have hcorrectionOrder :
          (((ordUnit K a + ordUnit K b) / 2 : Int) : WithTop Int) ≤
            ord K (s * (c : K) * (d : K)) := by
        simpa only [mem_powerIdeal_iff] using hscdHalf
      have hpLtCorrection : ord K p <
          ord K (s * (c : K) * (d : K)) := by
        rw [hpExact]
        exact (WithTop.coe_lt_coe.mpr hhalfStrict).trans_le hcorrectionOrder
      dsimp only [r]
      exact ((ord K).map_add_eq_of_lt_left hpLtCorrection).trans hpExact
  · have hOdd : Odd (J.boundaryNormOrderSum i) :=
      Int.not_even_iff_odd.mp hEven
    have hxNorm : x ∈ normIdeal q (J.fundamentalLattice li) :=
      normGroupSet_subset_normIdeal q (J.fundamentalLattice li)
        (by simpa only [fundamentalNormGroup, li] using hx)
    have hzNormNeg : -z ∈ normIdeal q (J.fundamentalLattice ri) :=
      normGroupSet_subset_normIdeal q (J.fundamentalLattice ri)
        (by simpa only [fundamentalNormGroup, ri] using hz)
    have hxPrincipal : x ∈ principalIdeal (K := K) (a : K) := by
      rw [← (J.fundamentalNormGenerator_spec li).2]
      exact hxNorm
    have hzPrincipal : z ∈ principalIdeal (K := K) (b : K) := by
      have hzNeg : -z ∈ principalIdeal (K := K) (b : K) := by
        rw [← (J.fundamentalNormGenerator_spec ri).2]
        exact hzNormNeg
      simpa using (principalIdeal (K := K) (b : K)).neg_mem hzNeg
    have hproduct : x * z ∈
        principalIdeal (K := K) (((a * b : Kˣ) : K)) := by
      simpa only [Units.val_mul] using
        (mul_mem_principalIdeal_mul hxPrincipal hzPrincipal)
    refine ⟨p, ?_, ?_⟩
    · rw [J.scaledFundamentalIdeal_eq_principalIdeal_of_odd i hOdd]
      simpa only [sub_add_cancel, Units.val_mul, a, b, li, ri] using
        (show x * z ∈
          principalIdeal (K := K) (((a * b : Kˣ) : K)) from hproduct)
    · intro _ hpExact
      exact hpExact

/-- The existence-only form of the boundary determinant calculation. -/
theorem exists_binaryDeterminant_squareAdjuster_mem_scaledFundamentalIdeal
    (J : JordanDecomposition q L (t + 1)) (i : Fin t)
    {x z p : K}
    (hx : x ∈ J.fundamentalNormGroup (boundaryLeftIndex i))
    (hz : -z ∈ J.fundamentalNormGroup (boundaryRightIndex i))
    (hp : p ∈ principalIdeal (K := K)
      (J.scaleGenerator (boundaryLeftIndex i) : K)) :
    ∃ r : K,
      x * z - p ^ 2 + r ^ 2 ∈ J.scaledFundamentalIdeal i := by
  rcases J.exists_binaryDeterminant_squareAdjuster_mem_scaledFundamentalIdeal_with_order
      i hx hz hp with ⟨r, hr, _⟩
  exact ⟨r, hr⟩

/-- Dividing an error in `s_i² f_i` by the square of the left scale
places the normalized error in `f_i`. -/
theorem normalized_binaryError_mem_fundamentalIdeal
    (J : JordanDecomposition q L (t + 1)) (i : Fin t)
    {D r : K}
    (h : ((J.scaleGenerator (boundaryLeftIndex i) : K) ^ 2) * D +
        r ^ 2 ∈ J.scaledFundamentalIdeal i) :
    D + ((((J.scaleGenerator (boundaryLeftIndex i))⁻¹ : Kˣ) : K) * r) ^ 2 ∈
      J.fundamentalIdeal i := by
  unfold fundamentalIdeal
  refine ⟨((J.scaleGenerator (boundaryLeftIndex i) : K) ^ 2) * D +
      r ^ 2, h, ?_⟩
  simp only [coefficientMulLinearMap_apply, Units.val_pow_eq_pow_val,
    Units.val_inv_eq_inv_val]
  field_simp [Units.ne_zero (J.scaleGenerator (boundaryLeftIndex i))]

end JordanDecomposition

end Lattice

end Bong
