/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.Beli2009WeightIdealProof
import Bong.Lattice.OmearaChangeOfComplement
import Bong.Lattice.ScaleTruncation

/-!
# O'Meara 93:13 for the full norm group

Proposition 93:12 changes the displayed coefficient by a single quadratic
value in the scale truncation.  The norm group is generated additively by
those changes: `2 B(u,v) = Q(u+v)-Q(u)-Q(v)`, with the same identity after
an integral scalar multiplication.  This file carries out that generation
argument and obtains Example 93:13 with its stated norm-group hypothesis.
-/

namespace Bong

open Dyadic

namespace Lattice

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {W : Type v} [AddCommGroup W] [Module K W]

/-- A scalar change that can be absorbed into the displayed scaled O'Meara
plane while leaving the complement lattice fixed. -/
def HasOmearaCoefficientShift
    (r : QuadraticSpace K W) (M : Lattice K W) (s : Kˣ) (delta : K) : Prop :=
  ∀ alpha : K, Nonempty
    (Isometry
      (((QuadraticSpace.omearaPlane
          (alpha + (s⁻¹ : Kˣ) * delta)).rescaleUnit s).orthogonalSum r)
      (((QuadraticSpace.omearaPlane alpha).rescaleUnit s).orthogonalSum r)
      (product (hyperbolicPlaneLattice (K := K)) M)
      (product (hyperbolicPlaneLattice (K := K)) M))

theorem hasOmearaCoefficientShift_zero
    (r : QuadraticSpace K W) (M : Lattice K W) (s : Kˣ) :
    HasOmearaCoefficientShift r M s 0 := by
  intro alpha
  let q := ((QuadraticSpace.omearaPlane alpha).rescaleUnit s).orthogonalSum r
  let L := product (hyperbolicPlaneLattice (K := K)) M
  simpa [HasOmearaCoefficientShift, q, L] using
    (show Nonempty (Isometry q q L L) from ⟨Isometry.refl q L⟩)

theorem HasOmearaCoefficientShift.add
    {r : QuadraticSpace K W} {M : Lattice K W} {s : Kˣ} {delta epsilon : K}
    (hdelta : HasOmearaCoefficientShift r M s delta)
    (hepsilon : HasOmearaCoefficientShift r M s epsilon) :
    HasOmearaCoefficientShift r M s (delta + epsilon) := by
  intro alpha
  let first := Classical.choice
    (hepsilon (alpha + (s⁻¹ : Kˣ) * delta))
  let second := Classical.choice (hdelta alpha)
  let combined := first.trans second
  have hcoefficient :
      alpha + (s⁻¹ : Kˣ) * (delta + epsilon) =
        (alpha + (s⁻¹ : Kˣ) * delta) +
          (s⁻¹ : Kˣ) * epsilon := by ring
  simpa only [hcoefficient] using (show Nonempty _ from ⟨combined⟩)

theorem HasOmearaCoefficientShift.neg
    {r : QuadraticSpace K W} {M : Lattice K W} {s : Kˣ} {delta : K}
    (hdelta : HasOmearaCoefficientShift r M s delta) :
    HasOmearaCoefficientShift r M s (-delta) := by
  intro alpha
  let shiftedAlpha := alpha + (s⁻¹ : Kˣ) * (-delta)
  let forward := Classical.choice (hdelta shiftedAlpha)
  have hcancel : shiftedAlpha + (s⁻¹ : Kˣ) * delta = alpha := by
    dsimp only [shiftedAlpha]
    ring
  simpa only [shiftedAlpha, hcancel] using
    (show Nonempty _ from ⟨forward.symm⟩)

theorem HasOmearaCoefficientShift.sub
    {r : QuadraticSpace K W} {M : Lattice K W} {s : Kˣ} {delta epsilon : K}
    (hdelta : HasOmearaCoefficientShift r M s delta)
    (hepsilon : HasOmearaCoefficientShift r M s epsilon) :
    HasOmearaCoefficientShift r M s (delta - epsilon) := by
  rw [sub_eq_add_neg]
  exact hdelta.add hepsilon.neg

/-- A single quadratic value from `M ∩ M^{s O}` gives an admissible
coefficient shift by Proposition 93:12 after scaling. -/
theorem hasOmearaCoefficientShift_quadratic
    (r : QuadraticSpace K W) (M : Lattice K W) (s : Kˣ)
    (z : W) (hzM : z ∈ M)
    (hzDual : z ∈ dualLattice (r.rescaleUnit s⁻¹) M) :
    HasOmearaCoefficientShift r M s (r.quadratic z) := by
  intro alpha
  exact ⟨omeara9313_represented r M s alpha z hzM hzDual⟩

/-- The scale truncation `M_{s O} = M ∩ M^{s O}` used in 93:13. -/
noncomputable def omearaScaleTruncation
    (r : QuadraticSpace K W) (M : Lattice K W) (s : Kˣ) :
    Lattice K W :=
  inf M (dualLattice (r.rescaleUnit s⁻¹) M)

@[simp]
theorem mem_omearaScaleTruncation_iff
    (r : QuadraticSpace K W) (M : Lattice K W) (s : Kˣ) (z : W) :
    z ∈ omearaScaleTruncation r M s ↔
      z ∈ M ∧ z ∈ dualLattice (r.rescaleUnit s⁻¹) M :=
  Iff.rfl

/-- Twice every element of the scale ideal of `M_{s O}` is generated by
admissible quadratic-value shifts. -/
theorem hasOmearaCoefficientShift_twice_scale
    (r : QuadraticSpace K W) (M : Lattice K W) (s : Kˣ)
    {c : K}
    (hc : c ∈ scaleIdeal r (omearaScaleTruncation r M s)) :
    HasOmearaCoefficientShift r M s ((2 : K) * c) := by
  let T := omearaScaleTruncation r M s
  change c ∈ Submodule.span (IntegerRing K) (scaleGenerators r T) at hc
  have hall : ∀ d : IntegerRing K,
      HasOmearaCoefficientShift r M s ((2 : K) * (d : K) * c) := by
    refine Submodule.span_induction
      (p := fun c _ ↦ ∀ d : IntegerRing K,
        HasOmearaCoefficientShift r M s ((2 : K) * (d : K) * c))
      ?_ ?_ ?_ ?_ hc
    · rintro _ ⟨p, rfl⟩ d
      let u : W := p.1
      let v : W := p.2
      let dv : W := (d : K) • v
      let w : W := u + dv
      have huT : u ∈ T := p.1.property
      have hvT : v ∈ T := p.2.property
      have hdvT : dv ∈ T := by
        change (d : K) • v ∈ T
        have hcoe : algebraMap (IntegerRing K) K d = (d : K) := rfl
        rw [← hcoe, IsScalarTower.algebraMap_smul K d v]
        exact T.smul_mem d hvT
      have hwT : w ∈ T := T.add_mem huT hdvT
      have hu := (mem_omearaScaleTruncation_iff r M s u).mp huT
      have hv := (mem_omearaScaleTruncation_iff r M s v).mp hvT
      have hdv := (mem_omearaScaleTruncation_iff r M s dv).mp hdvT
      have hw := (mem_omearaScaleTruncation_iff r M s w).mp hwT
      have hshiftW := hasOmearaCoefficientShift_quadratic
        r M s w hw.1 hw.2
      have hshiftU := hasOmearaCoefficientShift_quadratic
        r M s u hu.1 hu.2
      have hshiftDV := hasOmearaCoefficientShift_quadratic
        r M s dv hdv.1 hdv.2
      have hcombined := (hshiftW.sub hshiftU).sub hshiftDV
      have hidentity :
          r.quadratic w - r.quadratic u - r.quadratic dv =
            (2 : K) * (d : K) * r.bilin (p.1 : W) (p.2 : W) := by
        dsimp only [w, dv, u, v]
        rw [r.quadratic_add, r.quadratic_smul,
          LinearMap.BilinForm.smul_right]
        ring
      simpa only [hidentity] using hcombined
    · intro d
      simpa only [mul_zero] using hasOmearaCoefficientShift_zero r M s
    · intro x y _ _ hx hy d
      have hcombined := (hx d).add (hy d)
      have hidentity :
          (2 : K) * (d : K) * (x + y) =
            (2 : K) * (d : K) * x + (2 : K) * (d : K) * y := by ring
      simpa only [hidentity] using hcombined
    · intro a x _ hx d
      have hscaled := hx (d * a)
      have hidentity :
          (2 : K) * (d : K) * (a • x) =
            (2 : K) * ((d * a : IntegerRing K) : K) * x := by
        change (2 : K) * (d : K) * ((a : K) * x) = _
        push_cast
        ring
      simpa only [hidentity] using hscaled
  have h := hall 1
  have hidentity : (2 : K) * ((1 : IntegerRing K) : K) * c =
      (2 : K) * c := by
    push_cast
    ring
  simpa only [hidentity] using h

/-- O'Meara 93:13 with its full published hypothesis
`beta ∈ g(M_{s O})`, rather than only a single represented correction. -/
theorem omeara9313_nonempty
    (r : QuadraticSpace K W) (M : Lattice K W) (s : Kˣ) (alpha beta : K)
    (hbeta : beta ∈ normGroupSet r (omearaScaleTruncation r M s)) :
    Nonempty (Isometry
      (((QuadraticSpace.omearaPlane
          (alpha + (s⁻¹ : Kˣ) * beta)).rescaleUnit s).orthogonalSum r)
      (((QuadraticSpace.omearaPlane alpha).rescaleUnit s).orthogonalSum r)
      (product (hyperbolicPlaneLattice (K := K)) M)
      (product (hyperbolicPlaneLattice (K := K)) M)) := by
  rcases hbeta with ⟨z, hzT, c, hc, rfl⟩
  have hz := (mem_omearaScaleTruncation_iff r M s z).mp hzT
  have hquadratic := hasOmearaCoefficientShift_quadratic
    r M s z hz.1 hz.2
  rcases hc with ⟨d, hd, hdc⟩
  subst c
  have htwice := hasOmearaCoefficientShift_twice_scale r M s hd
  have hsum := hquadratic.add htwice
  have htwo : algebraMap (IntegerRing K) K (2 : IntegerRing K) =
      (2 : K) := by
    change ((2 : IntegerRing K) : K) = (2 : K)
    rfl
  simpa only [twoMulLinearMap_apply, Algebra.smul_def, htwo] using hsum alpha

/-- O'Meara 93:13, choosing the integral isometry supplied by the preceding
existence theorem. -/
noncomputable def omeara9313
    (r : QuadraticSpace K W) (M : Lattice K W) (s : Kˣ) (alpha beta : K)
    (hbeta : beta ∈ normGroupSet r (omearaScaleTruncation r M s)) :
    Isometry
      (((QuadraticSpace.omearaPlane
          (alpha + (s⁻¹ : Kˣ) * beta)).rescaleUnit s).orthogonalSum r)
      (((QuadraticSpace.omearaPlane alpha).rescaleUnit s).orthogonalSum r)
      (product (hyperbolicPlaneLattice (K := K)) M)
      (product (hyperbolicPlaneLattice (K := K)) M) :=
  Classical.choice (omeara9313_nonempty r M s alpha beta hbeta)

section OrthogonalProduct

universe w

variable {V : Type w} [AddCommGroup V] [Module K V]

/-- The right scale truncation embeds into the scale truncation of an
orthogonal product. -/
theorem mem_omearaScaleTruncation_orthogonalProduct_right
    (q : QuadraticSpace K V) (L : Lattice K V)
    (r : QuadraticSpace K W) (M : Lattice K W) (s : Kˣ)
    {z : W} (hz : z ∈ omearaScaleTruncation r M s) :
    (0, z) ∈ omearaScaleTruncation (q.orthogonalSum r) (product L M) s := by
  rw [mem_omearaScaleTruncation_iff] at hz ⊢
  constructor
  · exact mem_product_iff.mpr ⟨L.zero_mem, hz.1⟩
  · rw [mem_dualLattice_iff]
    intro x hx
    have hxParts := mem_product_iff.mp hx
    have hzPair :=
      (mem_dualLattice_iff (r.rescaleUnit s⁻¹) M z).mp hz.2 x.2 hxParts.2
    simpa [QuadraticSpace.rescaleUnit_bilin_apply,
      QuadraticSpace.orthogonalSum_bilin_apply] using hzPair

/-- The scale ideal of the right scale truncation embeds in that of the
orthogonal-product scale truncation. -/
theorem scaleIdeal_omearaScaleTruncation_le_orthogonalProduct_right
    (q : QuadraticSpace K V) (L : Lattice K V)
    (r : QuadraticSpace K W) (M : Lattice K W) (s : Kˣ) :
    scaleIdeal r (omearaScaleTruncation r M s) ≤
      scaleIdeal (q.orthogonalSum r)
        (omearaScaleTruncation (q.orthogonalSum r) (product L M) s) := by
  rw [scaleIdeal, Submodule.span_le]
  rintro _ ⟨p, rfl⟩
  have hx := mem_omearaScaleTruncation_orthogonalProduct_right
    q L r M s p.1.property
  have hy := mem_omearaScaleTruncation_orthogonalProduct_right
    q L r M s p.2.property
  have hpair := bilin_mem_scaleIdeal_of_mem
    (q.orthogonalSum r)
    (omearaScaleTruncation (q.orthogonalSum r) (product L M) s) hx hy
  have hvalue :
      (q.orthogonalSum r).bilin (0, (p.1 : W)) (0, (p.2 : W)) =
        r.bilin (p.1 : W) (p.2 : W) := by
    simp only [QuadraticSpace.orthogonalSum_bilin_apply,
      LinearMap.BilinForm.zero_left, zero_add]
  change r.bilin (p.1 : W) (p.2 : W) ∈
    (scaleIdeal (q.orthogonalSum r)
      (omearaScaleTruncation (q.orthogonalSum r) (product L M) s) : Set K)
  rw [← hvalue]
  exact hpair

/-- O'Meara norm groups of scale truncations are monotone under adjoining
an arbitrary orthogonal factor on the left. -/
theorem normGroupSet_omearaScaleTruncation_subset_orthogonalProduct_right
    (q : QuadraticSpace K V) (L : Lattice K V)
    (r : QuadraticSpace K W) (M : Lattice K W) (s : Kˣ) :
    normGroupSet r (omearaScaleTruncation r M s) ⊆
      normGroupSet (q.orthogonalSum r)
        (omearaScaleTruncation (q.orthogonalSum r) (product L M) s) := by
  rintro beta ⟨z, hz, c, hc, rfl⟩
  let T := omearaScaleTruncation r M s
  let T' := omearaScaleTruncation (q.orthogonalSum r) (product L M) s
  have hz' : (0, z) ∈ T' :=
    mem_omearaScaleTruncation_orthogonalProduct_right q L r M s hz
  have htwo : twoScaleIdeal r T ≤
      twoScaleIdeal (q.orthogonalSum r) T' := by
    unfold twoScaleIdeal twiceIdeal
    exact Submodule.map_mono
      (scaleIdeal_omearaScaleTruncation_le_orthogonalProduct_right
        q L r M s)
  refine ⟨(0, z), hz', c, htwo hc, ?_⟩
  simp [QuadraticSpace.orthogonalSum_quadratic_apply]

end OrthogonalProduct

end Lattice

end Bong
