/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.Omeara9328StepEightCancellation
import Bong.Lattice.Omeara9328StabilizationCancellation

/-!
# Aligned Step-8 pairs in O'Meara 93:28

For two saturated Jordan decompositions of the same fundamental type, the
Step-8 insertion on the target is recorded with the *source* scale
generators.  Equal scale orders make these valid modular parameters.  This
small normalization makes all componentwise scale-truncation factors
definitionally common and permits direct transfer of the new fundamental
norm groups.
-/

namespace Bong

open Dyadic Module

namespace Lattice.JordanDecomposition

universe u v w

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {W : Type w} [AddCommGroup W] [Module K W]
  {q : QuadraticSpace K V} {r : QuadraticSpace K W}
  {L : Lattice K V} {M : Lattice K W} {n : Nat}
  {J : JordanDecomposition q L (n + 2)}
  {H : JordanDecomposition r M (n + 2)}

/-- Corresponding Step-8 block scales have equal orders. -/
theorem SameFundamentalType.stepEightScaleGenerator_order_eq
    (F : SameFundamentalType J H) (i : Fin (n + 3)) :
    ordUnit K (H.stepEightScaleGenerator i) =
      ordUnit K (J.stepEightScaleGenerator i) := by
  cases i using Fin.cases with
  | zero =>
      change ordUnit K (H.stepEightScaleGenerator
          ((1 : Fin (n + 3)).succAbove (0 : Fin (n + 2)))) =
        ordUnit K (J.stepEightScaleGenerator
          ((1 : Fin (n + 3)).succAbove (0 : Fin (n + 2))))
      rw [H.stepEightScaleGenerator_old, J.stepEightScaleGenerator_old]
      exact F.scaleGenerator_order_eq_sameIndex 0
  | succ i =>
      cases i using Fin.cases with
      | zero =>
          change ordUnit K (H.stepEightScaleGenerator (1 : Fin (n + 3))) =
            ordUnit K (J.stepEightScaleGenerator (1 : Fin (n + 3)))
          rw [H.stepEightScaleGenerator_inserted,
            J.stepEightScaleGenerator_inserted,
            stepEightScale_order, stepEightScale_order,
            F.scaleGenerator_order_eq_sameIndex 0]
      | succ i =>
          change ordUnit K (H.stepEightScaleGenerator
              ((1 : Fin (n + 3)).succAbove (i.succ : Fin (n + 2)))) =
            ordUnit K (J.stepEightScaleGenerator
              ((1 : Fin (n + 3)).succAbove (i.succ : Fin (n + 2))))
          rw [H.stepEightScaleGenerator_old, J.stepEightScaleGenerator_old]
          exact F.scaleGenerator_order_eq_sameIndex i.succ

/-- The target Step-8 blocks are modular at the exactly aligned source
parameters. -/
theorem SameFundamentalType.targetStepEight_modular
    (F : SameFundamentalType J H) (i : Fin (n + 3)) :
    IsModular (H.stepEightForm i) (H.stepEightLattice i)
      (J.stepEightScaleGenerator i) := by
  apply (H.stepEightModular i).of_principalIdeal_eq
  exact (principalIdeal_eq_iff_ordUnit_eq
    (H.stepEightScaleGenerator i) (J.stepEightScaleGenerator i)).2
      (F.stepEightScaleGenerator_order_eq i)

/-- The target Step-8 scale ideals are generated by the aligned source
parameters. -/
theorem SameFundamentalType.targetStepEight_scaleIdeal_eq
    (F : SameFundamentalType J H) (i : Fin (n + 3)) :
    scaleIdeal (H.stepEightForm i) (H.stepEightLattice i) =
      principalIdeal (K := K) (J.stepEightScaleGenerator i : K) :=
  (F.targetStepEight_modular i).scaleIdeal_eq_principal
    (H.stepEightFinrank_pos i)

/-- Target Step-8 Jordan decomposition with source-aligned scale
generators. -/
noncomputable def SameFundamentalType.targetStepEightJordan
    (F : SameFundamentalType J H)
    (hgap : 1 < ordUnit K (J.scaleGenerator 1) -
      ordUnit K (J.scaleGenerator 0)) :
    JordanDecomposition
      (BONG.blockOrthogonalForm (n + 2) H.stepEightCarrier H.stepEightForm)
      (BONG.blockProductLattice (n + 2)
        H.stepEightCarrier H.stepEightLattice)
      (n + 3) :=
  BONG.blockProductJordanDecomposition H.stepEightCarrier H.stepEightForm
    H.stepEightLattice J.stepEightScaleGenerator H.stepEightNormGeneratorAt
    F.targetStepEight_modular F.targetStepEight_scaleIdeal_eq
    H.stepEightNormIdeal_eq (J.stepEightScaleOrder_strict hgap)

@[simp]
theorem SameFundamentalType.targetStepEightJordan_scaleGenerator
    (F : SameFundamentalType J H)
    (hgap : 1 < ordUnit K (J.scaleGenerator 1) -
      ordUnit K (J.scaleGenerator 0)) (i : Fin (n + 3)) :
    (F.targetStepEightJordan hgap).scaleGenerator i =
      J.stepEightScaleGenerator i :=
  rfl

@[simp]
theorem SameFundamentalType.targetStepEightJordan_componentRank
    (F : SameFundamentalType J H)
    (hgap : 1 < ordUnit K (J.scaleGenerator 1) -
      ordUnit K (J.scaleGenerator 0)) (i : Fin (n + 3)) :
    (F.targetStepEightJordan hgap).componentRank i =
      finrank K (H.stepEightCarrier i) := by
  exact BONG.blockProductJordanDecomposition_componentRank
    H.stepEightCarrier H.stepEightForm H.stepEightLattice
      J.stepEightScaleGenerator H.stepEightNormGeneratorAt
        F.targetStepEight_modular F.targetStepEight_scaleIdeal_eq
          H.stepEightNormIdeal_eq (J.stepEightScaleOrder_strict hgap) i

/-- Saturated corresponding old blocks have the same scalar norm group. -/
theorem SameFundamentalType.oldComponent_normGroupSet_eq
    (F : SameFundamentalType J H)
    (hJ : J.IsSaturated) (hH : H.IsSaturated) (i : Fin (n + 2)) :
    normGroupSet (H.component i).space (H.component i).lattice =
      normGroupSet (J.component i).space (J.component i).lattice := by
  calc
    normGroupSet (H.component i).space (H.component i).lattice =
        H.fundamentalNormGroup i := hH i
    _ = J.fundamentalNormGroup i := by
      have h := F.normGroup_eq i
      rw [F.indexEquiv_apply_eq_self] at h
      exact h
    _ = normGroupSet (J.component i).space
        (J.component i).lattice := (hJ i).symm

/-- Corresponding raw Step-8 blocks have the same scalar norm groups. -/
theorem SameFundamentalType.stepEightBlock_normGroupSet_eq
    (F : SameFundamentalType J H)
    (hJ : J.IsSaturated) (hH : H.IsSaturated) (i : Fin (n + 3)) :
    normGroupSet (H.stepEightForm i) (H.stepEightLattice i) =
      normGroupSet (J.stepEightForm i) (J.stepEightLattice i) := by
  cases i using Fin.cases with
  | zero =>
      change normGroupSet
          (H.stepEightForm
            ((1 : Fin (n + 3)).succAbove (0 : Fin (n + 2))))
          (H.stepEightLattice
            ((1 : Fin (n + 3)).succAbove (0 : Fin (n + 2)))) =
        normGroupSet
          (J.stepEightForm
            ((1 : Fin (n + 3)).succAbove (0 : Fin (n + 2))))
          (J.stepEightLattice
            ((1 : Fin (n + 3)).succAbove (0 : Fin (n + 2))))
      rw [H.stepEightOld_normGroupSet, J.stepEightOld_normGroupSet]
      exact F.oldComponent_normGroupSet_eq hJ hH 0
  | succ i =>
      cases i using Fin.cases with
      | zero =>
          change normGroupSet
              (H.stepEightForm (1 : Fin (n + 3)))
              (H.stepEightLattice (1 : Fin (n + 3))) =
            normGroupSet
              (J.stepEightForm (1 : Fin (n + 3)))
              (J.stepEightLattice (1 : Fin (n + 3)))
          have hstep : ordUnit K H.stepEightScale =
              ordUnit K J.stepEightScale := by
            rw [stepEightScale_order, stepEightScale_order,
              F.scaleGenerator_order_eq_sameIndex 0]
          let f : Isometry
              (H.stepEightForm (1 : Fin (n + 3)))
              (J.stepEightForm (1 : Fin (n + 3)))
              (H.stepEightLattice (1 : Fin (n + 3)))
              (J.stepEightLattice (1 : Fin (n + 3))) :=
            H.stepEightInsertedLatticeIsometry.trans <|
              (scaledHyperbolicChangeScaleIsometry
                H.stepEightScale J.stepEightScale hstep).trans
                  J.stepEightInsertedLatticeIsometry.symm
          exact normGroupSet_eq_of_latticeIsometry f.symm
      | succ i =>
          change normGroupSet
              (H.stepEightForm
                ((1 : Fin (n + 3)).succAbove (i.succ : Fin (n + 2))))
              (H.stepEightLattice
                ((1 : Fin (n + 3)).succAbove (i.succ : Fin (n + 2)))) =
            normGroupSet
              (J.stepEightForm
                ((1 : Fin (n + 3)).succAbove (i.succ : Fin (n + 2))))
              (J.stepEightLattice
                ((1 : Fin (n + 3)).succAbove (i.succ : Fin (n + 2))))
          rw [H.stepEightOld_normGroupSet, J.stepEightOld_normGroupSet]
          exact F.oldComponent_normGroupSet_eq hJ hH i.succ

/-- Corresponding components of the two aligned Step-8 Jordan
decompositions have the same scalar norm group. -/
theorem SameFundamentalType.stepEightJordan_component_normGroupSet_eq
    (F : SameFundamentalType J H)
    (hJ : J.IsSaturated) (hH : H.IsSaturated)
    (hgap : 1 < ordUnit K (J.scaleGenerator 1) -
      ordUnit K (J.scaleGenerator 0)) (i : Fin (n + 3)) :
    normGroupSet ((F.targetStepEightJordan hgap).component i).space
        ((F.targetStepEightJordan hgap).component i).lattice =
      normGroupSet ((J.stepEightJordan hgap).component i).space
        ((J.stepEightJordan hgap).component i).lattice := by
  let fH := BONG.blockProductComponentIsometry
    H.stepEightCarrier H.stepEightForm H.stepEightLattice i
  let fJ := BONG.blockProductComponentIsometry
    J.stepEightCarrier J.stepEightForm J.stepEightLattice i
  calc
    normGroupSet ((F.targetStepEightJordan hgap).component i).space
        ((F.targetStepEightJordan hgap).component i).lattice =
        normGroupSet (H.stepEightForm i) (H.stepEightLattice i) :=
      normGroupSet_eq_of_latticeIsometry fH
    _ = normGroupSet (J.stepEightForm i) (J.stepEightLattice i) :=
      F.stepEightBlock_normGroupSet_eq hJ hH i
    _ = normGroupSet ((J.stepEightJordan hgap).component i).space
        ((J.stepEightJordan hgap).component i).lattice :=
      (normGroupSet_eq_of_latticeIsometry fJ).symm

/-- The aligned raw Step-8 decompositions have equal fundamental norm
groups at every new scale. -/
theorem SameFundamentalType.stepEightJordan_fundamentalNormGroup_eq
    (F : SameFundamentalType J H)
    (hJ : J.IsSaturated) (hH : H.IsSaturated)
    (hgap : 1 < ordUnit K (J.scaleGenerator 1) -
      ordUnit K (J.scaleGenerator 0)) (i : Fin (n + 3)) :
    (F.targetStepEightJordan hgap).fundamentalNormGroup i =
      (J.stepEightJordan hgap).fundamentalNormGroup i := by
  apply fundamentalNormGroup_eq_of_componentwise_eq
    (J := J.stepEightJordan hgap) (H := F.targetStepEightJordan hgap)
  · intro j
    rfl
  · intro j
    rw [(F.targetStepEightJordan hgap).scaleIdeal_eq,
      (J.stepEightJordan hgap).scaleIdeal_eq]
    rfl
  · exact F.stepEightJordan_component_normGroupSet_eq hJ hH hgap

/-- Corresponding component ranks in the aligned Step-8 pair agree. -/
theorem SameFundamentalType.stepEightJordan_componentRank_eq
    (F : SameFundamentalType J H)
    (hgap : 1 < ordUnit K (J.scaleGenerator 1) -
      ordUnit K (J.scaleGenerator 0)) (i : Fin (n + 3)) :
    (F.targetStepEightJordan hgap).componentRank i =
      (J.stepEightJordan hgap).componentRank i := by
  have hzero := F.scaleGenerator_order_eq_sameIndex (0 : Fin (n + 2))
  have hone := F.scaleGenerator_order_eq_sameIndex (1 : Fin (n + 2))
  have hgapH : 1 < ordUnit K (H.scaleGenerator 1) -
      ordUnit K (H.scaleGenerator 0) := by
    omega
  have htargetRaw (j : Fin (n + 3)) :
      (F.targetStepEightJordan hgap).componentRank j =
        (H.stepEightJordan hgapH).componentRank j := by
    rw [F.targetStepEightJordan_componentRank,
      H.stepEightJordan_componentRank]
  cases i using Fin.cases with
  | zero =>
      change (F.targetStepEightJordan hgap).componentRank
          ((1 : Fin (n + 3)).succAbove (0 : Fin (n + 2))) =
        (J.stepEightJordan hgap).componentRank
          ((1 : Fin (n + 3)).succAbove (0 : Fin (n + 2)))
      rw [htargetRaw, H.stepEightJordan_old_componentRank,
        J.stepEightJordan_old_componentRank]
      have h := F.componentRank_eq (0 : Fin (n + 2))
      rwa [F.indexEquiv_apply_eq_self] at h
  | succ i =>
      cases i using Fin.cases with
      | zero =>
          change (F.targetStepEightJordan hgap).componentRank
              (1 : Fin (n + 3)) =
            (J.stepEightJordan hgap).componentRank (1 : Fin (n + 3))
          rw [htargetRaw, H.stepEightJordan_inserted_componentRank,
            J.stepEightJordan_inserted_componentRank]
      | succ i =>
          change (F.targetStepEightJordan hgap).componentRank
              ((1 : Fin (n + 3)).succAbove (i.succ : Fin (n + 2))) =
            (J.stepEightJordan hgap).componentRank
              ((1 : Fin (n + 3)).succAbove (i.succ : Fin (n + 2)))
          rw [htargetRaw, H.stepEightJordan_old_componentRank,
            J.stepEightJordan_old_componentRank]
          have h := F.componentRank_eq (i.succ : Fin (n + 2))
          rwa [F.indexEquiv_apply_eq_self] at h

/-- The raw Step-8 extensions have the same complete fundamental type. -/
noncomputable def SameFundamentalType.stepEight
    (F : SameFundamentalType J H)
    (hJ : J.IsSaturated) (hH : H.IsSaturated)
    (hgap : 1 < ordUnit K (J.scaleGenerator 1) -
      ordUnit K (J.scaleGenerator 0)) :
    SameFundamentalType (J.stepEightJordan hgap)
      (F.targetStepEightJordan hgap) where
  indexEquiv := Equiv.refl (Fin (n + 3))
  index_val := fun _ => rfl
  componentRank_eq := F.stepEightJordan_componentRank_eq hgap
  scaleOrder_eq := by
    intro i
    rfl
  normGroup_eq := F.stepEightJordan_fundamentalNormGroup_eq hJ hH hgap

end Lattice.JordanDecomposition

end Bong
