/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.Omeara9328StepEightSaturated
import Bong.Lattice.Omeara9328AdjunctionAmbient
import Bong.Lattice.Omeara9328StabilizationCancellation
import Bong.Lattice.Omeara9328StepEightCancellation
import Bong.Lattice.Omeara9328RankFourCancellation

/-!
# Closed common-adjunction certificate for O'Meara 93:28, Step 8

This bundle hides the large dependent product presentations generated by
the Step-8 insertion, simultaneous stabilization, 93:21 saturation, and
common adjunction.  It exposes exactly the data needed by the rank-four
reduction and includes the integral descent through all four stages.
-/

namespace Bong

open Dyadic Module

namespace Lattice.JordanDecomposition

universe u

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  [DyadicDiscriminantClassLaws K]
  {V : Type u} [AddCommGroup V] [Module K V]
  {W : Type u} [AddCommGroup W] [Module K W]
  {q : QuadraticSpace K V} {r : QuadraticSpace K W}
  {L : Lattice K V} {M : Lattice K W} {n : Nat}
  {J : JordanDecomposition q L (n + 2)}
  {H : JordanDecomposition r M (n + 2)}

/-- All mathematical output of O'Meara 93:28, Step 8 up to the final
simultaneous rank-four reduction. -/
structure Omeara9328StepEightCommonBundle
    (S : Omeara9328RankFourReductionSystem J H)
    (E : S.StepEightCase) where
  sourceCarrier : Type u
  [sourceAddCommGroup : AddCommGroup sourceCarrier]
  [sourceModule : Module K sourceCarrier]
  targetCarrier : Type u
  [targetAddCommGroup : AddCommGroup targetCarrier]
  [targetModule : Module K targetCarrier]
  sourceForm : QuadraticSpace K sourceCarrier
  targetForm : QuadraticSpace K targetCarrier
  sourceLattice : Lattice K sourceCarrier
  targetLattice : Lattice K targetCarrier
  sourceJordan : JordanDecomposition sourceForm sourceLattice (n + 3)
  targetJordan : JordanDecomposition targetForm targetLattice (n + 3)
  sourceSaturated : sourceJordan.IsSaturated
  targetSaturated : targetJordan.IsSaturated
  fundamentalType : SameFundamentalType sourceJordan targetJordan
  componentRank_atLeastTwo : ∀ i, 2 ≤ sourceJordan.componentRank i
  choice : FundamentalNormGeneratorChoice S.sourceJordan →
    FundamentalNormGeneratorChoice sourceJordan
  conditions : ∀ (A : FundamentalNormGeneratorChoice S.sourceJordan),
    S.sourceJordan.Omeara9328ConditionsWith S.targetJordan A →
      sourceJordan.Omeara9328ConditionsWith targetJordan (choice A)
  ambientOf : q.IsIsometric r → sourceForm.IsIsometric targetForm
  scaleOrder_eq_raw : ∀ i,
    ordUnit K (sourceJordan.scaleGenerator i) =
      ordUnit K ((E.rawSource S).scaleGenerator i)
  unwind : Isometry sourceForm targetForm sourceLattice targetLattice →
    Isometry q r L M

namespace Omeara9328RankFourReductionSystem.StepEightCase

set_option maxHeartbeats 2000000 in
/-- Execute Step 8 and seal all concrete dependent presentations behind the
common-bundle interface. -/
noncomputable def commonBundle
    (S : Omeara9328RankFourReductionSystem J H)
    (E : S.StepEightCase) : Omeara9328StepEightCommonBundle S E := by
  let EJ := E.rawSource S
  let EH := E.rawTarget S
  let F₈ := E.rawFundamentalType S
  let EJS := E.stableSource S
  let EHS := E.stableTarget S
  let FS := E.stableFundamentalType S
  let P := E.saturatedSource S
  let hP := E.saturatedSource_isSaturated S
  let FPJ := E.saturatedToStable S
  let FPH := E.saturatedToTarget S
  let CJ := P.commonAdjunctionJordan EJS FPJ hP
  let CH := P.commonAdjunctionJordan EHS FPH hP
  let FC : SameFundamentalType CJ CH := FPJ.commonAdjunction FPH FS hP
  have hCJ : CJ.IsSaturated :=
    P.commonAdjunctionJordan_isSaturated EJS FPJ hP
  have hCH : CH.IsSaturated :=
    P.commonAdjunctionJordan_isSaturated EHS FPH hP
  have hrankCJ : ∀ i, 2 ≤ CJ.componentRank i := by
    intro i
    change 2 ≤ (P.commonAdjunctionJordan EJS FPJ hP).componentRank i
    rw [commonAdjunctionJordan_componentRank]
    have hi : 3 ≤ EJS.componentRank i := by
      simpa [EJS] using E.stableComponentRank_atLeastThree S i
    omega
  refine {
    sourceCarrier := BONG.BlockProductSpace (n + 2)
      (P.commonAdjunctionCarrier EJS)
    sourceAddCommGroup := inferInstance
    sourceModule := inferInstance
    targetCarrier := BONG.BlockProductSpace (n + 2)
      (P.commonAdjunctionCarrier EHS)
    targetAddCommGroup := inferInstance
    targetModule := inferInstance
    sourceForm := BONG.blockOrthogonalForm (n + 2)
      (P.commonAdjunctionCarrier EJS) (P.commonAdjunctionForm EJS)
    targetForm := BONG.blockOrthogonalForm (n + 2)
      (P.commonAdjunctionCarrier EHS) (P.commonAdjunctionForm EHS)
    sourceLattice := BONG.blockProductLattice (n + 2)
      (P.commonAdjunctionCarrier EJS) (P.commonAdjunctionLattice EJS)
    targetLattice := BONG.blockProductLattice (n + 2)
      (P.commonAdjunctionCarrier EHS) (P.commonAdjunctionLattice EHS)
    sourceJordan := CJ
    targetJordan := CH
    sourceSaturated := hCJ
    targetSaturated := hCH
    fundamentalType := FC
    componentRank_atLeastTwo := hrankCJ
    choice := fun A => (E.stableChoice S A).commonAdjunction FPJ hP
    conditions := fun A C =>
      omeara9328ConditionsWith_commonAdjunction FPJ FPH
        (E.stableChoice S A) hP (E.stableConditions S A C)
    ambientOf := fun ambient =>
      FPJ.commonAdjunctionAmbientIsometry FPH hP (E.stableAmbient S ambient)
    scaleOrder_eq_raw := ?_
    unwind := ?_ }
  · intro i
    calc
      ordUnit K (CJ.scaleGenerator i) = ordUnit K (P.scaleGenerator i) :=
        congrArg (ordUnit K)
          (P.commonAdjunctionJordan_scaleGenerator EJS FPJ hP i)
      _ = ordUnit K (EJS.scaleGenerator i) :=
        (FPJ.scaleGenerator_order_eq_sameIndex i).symm
      _ = ordUnit K (EJ.scaleGenerator i) :=
        congrArg (ordUnit K) (EJ.saturationStableJordan_scaleGenerator i)
  · intro f
    let stableIsometry := P.cancelCommonAdjunction EJS EHS FPJ FPH hP f
    let rawIsometry :=
      isometryOfSaturationStableJordanIsometry EJ EH F₈ stableIsometry
    let hfirst :=
      S.residualFundamentalType.scaleGenerator_order_eq_sameIndex
        (0 : Fin (n + 2))
    exact S.originalIsometryOfResidualIsometry <|
      cancelStepEightInsertion S.sourceJordan S.targetJordan hfirst rawIsometry

/-- Named additive structure on the Step-8 common source. -/
noncomputable instance commonBundleSourceAddCommGroup
    (S : Omeara9328RankFourReductionSystem J H) (E : S.StepEightCase) :
    AddCommGroup (E.commonBundle S).sourceCarrier :=
  (E.commonBundle S).sourceAddCommGroup

/-- Named module structure on the Step-8 common source. -/
noncomputable instance commonBundleSourceModule
    (S : Omeara9328RankFourReductionSystem J H) (E : S.StepEightCase) :
    Module K (E.commonBundle S).sourceCarrier :=
  (E.commonBundle S).sourceModule

/-- Named additive structure on the Step-8 common target. -/
noncomputable instance commonBundleTargetAddCommGroup
    (S : Omeara9328RankFourReductionSystem J H) (E : S.StepEightCase) :
    AddCommGroup (E.commonBundle S).targetCarrier :=
  (E.commonBundle S).targetAddCommGroup

/-- Named module structure on the Step-8 common target. -/
noncomputable instance commonBundleTargetModule
    (S : Omeara9328RankFourReductionSystem J H) (E : S.StepEightCase) :
    Module K (E.commonBundle S).targetCarrier :=
  (E.commonBundle S).targetModule

end Omeara9328RankFourReductionSystem.StepEightCase
end Lattice.JordanDecomposition

end Bong
