/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.Omeara9328EqualOrderTwistAbsorption

/-!
# O'Meara 93:28, Step 6: adjacent normalized norm orders

This file treats the case `U₂ = U₁ + 1` after normalizing the first
Jordan scale.  Under the remaining Step-5 hypothesis `U₁ < e`, the first
weight has order `U₂`.  Perfectness of the residue field then shows that
every scalar in `a₁ O` belongs to the first norm group.  These facts
construct the determinant-correction data used by 93:13 and 93:19.
-/

namespace Bong

open Dyadic Module BONG.GoodBONG

namespace Lattice.JordanDecomposition

universe u v w

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  [DyadicDiscriminantClassLaws K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {W : Type w} [AddCommGroup W] [Module K W]
  {q : QuadraticSpace K V} {r : QuadraticSpace K W}
  {L : Lattice K V} {M : Lattice K W} {n : Nat}
  {J : JordanDecomposition q L (n + 2)}
  {H : JordanDecomposition r M (n + 2)}

namespace Omeara9328RankFourReductionSystem

variable (S : Omeara9328RankFourReductionSystem J H)

/-- In Step 6 the normalized first weight is generated by the normalized
second norm generator. -/
theorem adjacentNormOrder_firstWeightOrder_eq_second
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int)) :
    weightIdealOrder S.sourceFirstNormalized
        (S.sourceJordan.component 0).lattice =
      ordUnit K (S.secondNormalizedNormGeneratorWith A) := by
  let delta := S.secondNormalizedNormGeneratorWith A
  let a := S.firstNormGenerator
  have ha := S.firstNormGenerator_source
  have hnormLe : ordUnit K a ≤
      weightIdealOrder S.sourceFirstNormalized
        (S.sourceJordan.component 0).lattice :=
    normGeneratorOrder_le_weightIdealOrder a ha
  have hdeltaMem : (delta : K) ∈
      normGroupSet S.sourceFirstNormalized
        (S.sourceJordan.component 0).lattice :=
    S.secondNormalizedNormGeneratorWith_mem_sourceFirst A
  have hsumOdd : Odd (ordUnit K a + ordUnit K delta) := by
    refine ⟨ordUnit K a, ?_⟩
    dsimp only [a, delta] at hgap ⊢
    omega
  have hweightLe :
      weightIdealOrder S.sourceFirstNormalized
          (S.sourceJordan.component 0).lattice ≤ ordUnit K delta :=
    weightIdealOrder_le_ordUnit_of_mem_normGroupSet_of_odd
      a delta ha hdeltaMem hsumOdd
  rcases weightIdeal_eq_twoScale_or_odd a ha with hterminal | hodd
  · have hweightRamification :
        weightIdealOrder S.sourceFirstNormalized
            (S.sourceJordan.component 0).lattice =
          (ramificationIndex K : Int) := by
      let two : Kˣ := Units.mk0 (2 : K) (by norm_num)
      have htwoOrder : ordUnit K two =
          (ramificationIndex K : Int) := by
        apply WithTop.coe_injective
        rw [coe_ordUnit]
        exact (ramificationIndex_spec K).symm
      apply powerIdeal_order_eq_of_eq (K := K)
      calc
        powerIdeal (K := K)
            (weightIdealOrder S.sourceFirstNormalized
              (S.sourceJordan.component 0).lattice) =
            weightIdeal S.sourceFirstNormalized
              (S.sourceJordan.component 0).lattice :=
          (weightIdeal_eq_powerIdeal _ _).symm
        _ = twoScaleIdeal S.sourceFirstNormalized
              (S.sourceJordan.component 0).lattice := hterminal
        _ = principalIdeal (K := K) (2 : K) :=
          twoScaleIdeal_eq_principalIdeal_two_of_unimodular
            S.sourceFirstNormalized_unimodular
            (by rw [S.sourceFirstNormalized_finrank]; omega)
        _ = powerIdeal (K := K) (ordUnit K two) := by
          simpa only [two, Units.val_mk0] using
            (principalIdeal_eq_powerIdeal two)
        _ = powerIdeal (K := K) (ramificationIndex K : Int) := by
          rw [htwoOrder]
    dsimp only [a, delta] at hnormLe hweightLe hgap ⊢
    have hterminalOrder := hweightRamification
    omega
  · dsimp only [a, delta] at hnormLe hweightLe hodd hgap ⊢
    rcases hodd with ⟨k, hk⟩
    omega

/-- The intrinsic first fundamental ideal in the adjacent-order case is
the principal ideal generated by the product of the two normalized norm
generators chosen in the reduction system. -/
theorem adjacentNormOrder_firstFundamentalIdeal_eq_normProduct
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1) :
    S.sourceJordan.fundamentalIdeal 0 =
      principalIdeal (K := K)
        (((S.firstNormGenerator *
          S.secondNormalizedNormGeneratorWith A : Kˣ) : K)) := by
  have hcanonicalGap : ordUnit K S.secondNormalizedNormGenerator =
      ordUnit K S.firstNormGenerator + 1 := by
    rw [← S.secondNormalizedNormGeneratorWith_order_eq A]
    exact hgap
  have hintrinsicGap :=
    S.fundamentalNormOrder_eq_add_one_of_normalized_gap_one hcanonicalGap
  have hodd : Odd (S.sourceJordan.boundaryNormOrderSum 0) := by
    refine ⟨ordUnit K (S.sourceJordan.fundamentalNormGenerator 0), ?_⟩
    change ordUnit K (S.sourceJordan.fundamentalNormGenerator 0) +
        ordUnit K (S.sourceJordan.fundamentalNormGenerator 1) = _
    omega
  have hli : boundaryLeftIndex (0 : Fin (n + 1)) =
      (0 : Fin (n + 2)) := by
    ext
    rfl
  have hri : boundaryRightIndex (0 : Fin (n + 1)) =
      (1 : Fin (n + 2)) := by
    ext
    rfl
  calc
    S.sourceJordan.fundamentalIdeal 0 =
        principalIdeal (K := K)
          (((S.sourceJordan.scaleGenerator (boundaryLeftIndex 0))⁻¹ ^ 2 *
            S.sourceJordan.fundamentalNormGenerator (boundaryLeftIndex 0) *
            S.sourceJordan.fundamentalNormGenerator
              (boundaryRightIndex 0) : Kˣ) : K) :=
      S.sourceJordan.fundamentalIdeal_eq_principalIdeal_of_odd 0 hodd
    _ = principalIdeal (K := K)
        (((S.firstNormGenerator *
          S.secondNormalizedNormGeneratorWith A : Kˣ) : K)) := by
      apply (principalIdeal_eq_iff_ordUnit_eq _ _).2
      simp only [ordUnit_mul, ordUnit_pow, ordUnit_inv]
      rw [hli, hri]
      have hsOrder : ordUnit K (S.sourceJordan.scaleGenerator 0) =
          S.sourceJordan.fundamentalScaleOrder 0 := rfl
      rw [hsOrder, S.firstNormGenerator_order,
        S.secondNormalizedNormGeneratorWith_order_eq A,
        S.secondNormalizedNormGenerator_order]
      ring

/-- Witness form of the preceding product formula. -/
theorem exists_firstNormFactor_of_mem_firstFundamentalIdeal_adjacent
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    {z : K} (hz : z ∈ S.sourceJordan.fundamentalIdeal 0) :
    ∃ c : K, c ∈ principalIdeal (K := K)
        (S.firstNormGenerator : K) ∧
      z = (S.secondNormalizedNormGeneratorWith A : K) * c := by
  rw [S.adjacentNormOrder_firstFundamentalIdeal_eq_normProduct A hgap] at hz
  have hscalar :
      scalarIdeal (S.secondNormalizedNormGeneratorWith A : K)
          (principalIdeal (K := K) (S.firstNormGenerator : K)) =
        principalIdeal (K := K)
          ((S.firstNormGenerator *
            S.secondNormalizedNormGeneratorWith A : Kˣ) : K) := by
    simpa only [mul_comm] using
      (scalarIdeal_principalIdeal_units
        (S.secondNormalizedNormGeneratorWith A) S.firstNormGenerator)
  rw [← hscalar] at hz
  rcases hz with ⟨c, hc, hcz⟩
  exact ⟨c, hc, hcz.symm⟩

/-- Perfectness of the residue field upgrades the full principal norm
ideal `a₁ O` to represented values when the weight order is `U₁ + 1`.
This is the scalar step suppressed in O'Meara's phrase “proceed as in
Step 4.” -/
theorem firstNormPrincipalIdeal_subset_sourceFirstNormGroup_adjacent
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int)) :
    ∀ ⦃z : K⦄, z ∈ principalIdeal (K := K)
        (S.firstNormGenerator : K) →
      z ∈ normGroupSet S.sourceFirstNormalized
        (S.sourceJordan.component 0).lattice := by
  intro z hz
  let a := S.firstNormGenerator
  let delta := S.secondNormalizedNormGeneratorWith A
  have ha := S.firstNormGenerator_source
  have hweight := S.adjacentNormOrder_firstWeightOrder_eq_second
    A hgap hfirst
  by_cases hz0 : z = 0
  · subst z
    exact zero_mem_normGroupSet _ _
  let zu : Kˣ := Units.mk0 z hz0
  have horderTop := ord_le_of_mem_principalIdeal (Units.ne_zero a) hz
  have horder : ordUnit K a ≤ ordUnit K zu := by
    apply WithTop.coe_le_coe.mp
    simpa only [coe_ordUnit, zu, Units.val_mk0] using horderTop
  by_cases heven : Even (ordUnit K zu - ordUnit K a)
  · rcases exists_integral_square_approximation_of_even_order_difference
      a zu horder heven with ⟨c, hc⟩
    let y : K := z - (a : K) * (c : K) ^ 2
    have hy : y ∈ weightIdeal S.sourceFirstNormalized
        (S.sourceJordan.component 0).lattice := by
      rw [weightIdeal_eq_powerIdeal, mem_powerIdeal_iff, hweight]
      have hsucc := coe_int_add_one_le_of_lt hc
      have hdeltaLe : ordUnit K delta ≤ ordUnit K zu + 1 := by
        dsimp only [a, delta] at hgap horder ⊢
        omega
      exact (WithTop.coe_le_coe.mpr hdeltaLe).trans (by
        simpa only [y, zu, Units.val_mk0] using hsucc)
    rw [normGroupSet_eq_integralSquareCoset_weightIdeal a ha]
    exact ⟨c, y, hy, by dsimp only [y, a]; ring⟩
  · have hodd : Odd (ordUnit K zu - ordUnit K a) :=
      Int.not_even_iff_odd.mp heven
    rcases hodd with ⟨k, hk⟩
    have hdeltaLe : ordUnit K delta ≤ ordUnit K zu := by
      dsimp only [a, delta] at hgap horder hk ⊢
      omega
    apply weightIdeal_subset_normGroupSet a ha
    rw [weightIdeal_eq_powerIdeal]
    apply (mem_powerIdeal_iff _ _).2
    rw [hweight]
    simpa only [zu, Units.val_mk0, coe_ordUnit] using
      (WithTop.coe_le_coe.mpr hdeltaLe)

/-- The same principal ideal is represented by the normalized target
first component because the two first norm groups agree. -/
theorem firstNormPrincipalIdeal_subset_targetFirstNormGroup_adjacent
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int)) :
    ∀ ⦃z : K⦄, z ∈ principalIdeal (K := K)
        (S.firstNormGenerator : K) →
      z ∈ normGroupSet S.targetFirstNormalized
        (S.targetJordan.component 0).lattice := by
  intro z hz
  rw [← S.firstNormalized_normGroupSet_eq]
  exact S.firstNormPrincipalIdeal_subset_sourceFirstNormGroup_adjacent
    A hgap hfirst hz

/-- Determinant-error package for the adjacent-order case.  Its
coefficient lies in `a₁ O`, hence in both first norm groups; multiplication
by the square of the positive relative scale places it in `a₂ O`, which is
the sharp hypothesis of the subsequent 93:19 exchange. -/
noncomputable def adjacentNormOrderErrorData
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (z : K)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int))
    (hz : z ∈ S.sourceJordan.fundamentalIdeal 0) :
    S.EqualNormOrderErrorData z := by
  let delta := S.secondNormalizedNormGeneratorWith A
  let a := S.firstNormGenerator
  let hexists :=
    S.exists_firstNormFactor_of_mem_firstFundamentalIdeal_adjacent A hgap hz
  let coefficient : K := Classical.choose hexists
  have hcoefficientPrincipal : coefficient ∈
      principalIdeal (K := K) (a : K) :=
    (Classical.choose_spec hexists).1
  have hzEq : z = (delta : K) * coefficient :=
    (Classical.choose_spec hexists).2
  have hcoefficientSource : coefficient ∈
      normGroupSet S.sourceFirstNormalized
        (S.sourceJordan.component 0).lattice :=
    S.firstNormPrincipalIdeal_subset_sourceFirstNormGroup_adjacent
      A hgap hfirst hcoefficientPrincipal
  have hcoefficientTarget : coefficient ∈
      normGroupSet S.targetFirstNormalized
        (S.targetJordan.component 0).lattice :=
    S.firstNormPrincipalIdeal_subset_targetFirstNormGroup_adjacent
      A hgap hfirst hcoefficientPrincipal
  have haIntegral : (a : K) ∈ IntegerRing K :=
    S.firstNormGenerator_integral
  have haNonnegative : (0 : WithTop Int) ≤ ord K (a : K) := by
    exact (mem_integerRing_iff K).1 haIntegral
  have hcoefficientOrder := ord_le_of_mem_principalIdeal
    (Units.ne_zero a) hcoefficientPrincipal
  have hcoefficientIntegral : coefficient ∈ IntegerRing K := by
    rw [mem_integerRing_iff]
    exact haNonnegative.trans hcoefficientOrder
  have hdeltaIntegral : (delta : K) ∈ IntegerRing K := by
    rw [mem_integerRing_iff, Dyadic.IsIntegral, ← coe_ordUnit]
    have haOrderNonnegative : 0 ≤ ordUnit K a := by
      apply WithTop.coe_nonneg.mp
      simpa only [coe_ordUnit] using haNonnegative
    apply WithTop.coe_nonneg.mpr
    dsimp only [a, delta] at hgap haOrderNonnegative ⊢
    omega
  have hrelativeOrderPositive :
      0 < ordUnit K S.relativeSecondScale := by
    have hscaleStrict :
        S.sourceJordan.fundamentalScaleOrder 0 <
          S.sourceJordan.fundamentalScaleOrder 1 :=
      S.sourceJordan.scaleOrder_strict (by simp)
    have hrelative := S.relativeSecondScale_order
    omega
  have hgeneratorOrder : ord K (delta : K) ≤
      ord K ((a : K) * (S.relativeSecondScale : K) ^ 2) := by
    rw [ord_mul, ord_pow, ← coe_ordUnit, ← coe_ordUnit,
      ← coe_ordUnit]
    apply WithTop.coe_le_coe.mpr
    simp only [two_nsmul]
    dsimp only [a, delta] at hgap ⊢
    omega
  have hscaledOrder : ord K (delta : K) ≤
      ord K (coefficient * (S.relativeSecondScale : K) ^ 2) := by
    refine hgeneratorOrder.trans ?_
    simp only [ord_mul, ord_pow]
    simpa only [add_comm] using
      add_le_add_left hcoefficientOrder
        (2 • ord K (S.relativeSecondScale : K))
  have hscaledPrincipal :
      coefficient * (S.relativeSecondScale : K) ^ 2 ∈
        principalIdeal (K := K) (delta : K) :=
    mem_principalIdeal_of_ord_le (Units.ne_zero delta) hscaledOrder
  exact
    { secondGenerator := delta
      coefficient := coefficient
      error_eq := hzEq
      coefficient_integral := hcoefficientIntegral
      coefficient_mem_sourceFirst := hcoefficientSource
      coefficient_mem_targetFirst := hcoefficientTarget
      coefficient_mul_relativeScale_sq_mem_secondGeneratorIdeal :=
        hscaledPrincipal
      secondGenerator_integral := hdeltaIntegral
      secondGenerator_sourceSecond :=
        S.secondNormalizedNormGeneratorWith_source A
      secondGenerator_targetSecond :=
        S.secondNormalizedNormGeneratorWith_target A
      secondGenerator_mem_sourceFirst :=
        S.secondNormalizedNormGeneratorWith_mem_sourceFirst A
      secondGenerator_mem_targetFirst :=
        S.secondNormalizedNormGeneratorWith_mem_targetFirst A }

/-- The Step-6 error data specialized to the determinant congruence from
condition 93:28(i). -/
noncomputable def adjacentOrderErrorData
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int)) :
    S.EqualNormOrderErrorData
      (S.targetFirstCongruenceError A conditions).error :=
  S.adjacentNormOrderErrorData A
    (S.targetFirstCongruenceError A conditions).error hgap hfirst
    (S.targetFirstCongruenceError A conditions).error_mem

/-- The corrected normalized head in Step 6 has determinant class one. -/
theorem adjacentOrder_newHead_determinantClass_eq_one
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int)) :
    let D := S.adjacentOrderErrorData A conditions hgap hfirst
    determinantClass D.newHead D.newHeadLattice = 1 := by
  let C := S.targetFirstCongruenceError A conditions
  let D := S.adjacentOrderErrorData A conditions hgap hfirst
  change determinantClass D.newHead D.newHeadLattice = 1
  apply D.newHead_determinantClass_eq_one C.errorUnit
    C.errorUnit_coe C.errorUnit_isValuationUnit
  change unitSquareClass K
      (determinantUnit S.targetFirstNormalized
        (S.targetJordan.component 0).lattice) =
    unitSquareClass K C.errorUnit
  exact C.unitSquareClass_eq_errorUnit

/-- In the condition-(ii) branch of Step 6, the corrected head represents
a hyperbolic plane. -/
theorem adjacentOrderNewHeadRepresentsHyperbolicOfConditionII
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int))
    (htrigger : S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0)) :
    let D := S.adjacentOrderErrorData A conditions hgap hfirst
    D.newHead.Represents
      (QuadraticSpace.hyperbolicPlane (1 : Kˣ)) := by
  let D := S.adjacentOrderErrorData A conditions hgap hfirst
  change D.newHead.Represents
    (QuadraticSpace.hyperbolicPlane (1 : Kˣ))
  letI : Module.Finite K (S.sourceJordan.component 0).carrier :=
    (S.sourceJordan.component 0).lattice.moduleFinite
  letI : Module.Finite K (S.targetJordan.component 0).carrier :=
    (S.targetJordan.component 0).lattice.moduleFinite
  letI : Module.Finite K (D.headSplit.decomposition.component 1).carrier :=
    D.newHeadLattice.moduleFinite
  rcases S.normalizedConditionIIRepresentation A conditions htrigger with
    ⟨sourceInOldLine⟩
  rcases D.newPlaneRepresentsSecondGenerator with ⟨lineInNewPlane⟩
  let replaceLine :=
    (QuadraticSpace.Representation.refl S.targetFirstNormalized).orthogonalSum
      lineInNewPlane
  let sourceInOldNew := replaceLine.trans sourceInOldLine
  let swap : QuadraticSpace.Isometry
      (S.targetFirstNormalized.orthogonalSum D.exchangeSetup.newPlane)
      D.headAmbient :=
    (orthogonalProductSwap
      (q := S.targetFirstNormalized) (r := D.exchangeSetup.newPlane)
      (L := (S.targetJordan.component 0).lattice)
      (M := hyperbolicPlaneLattice (K := K))).toQuadraticSpaceIsometry
  let targetToSplit := swap.trans
    D.headSplit.displayedIsometry.toQuadraticSpaceIsometry
  have sourceInSplit :
      ((QuadraticSpace.hyperbolicPlane (1 : Kˣ)).orthogonalSum
        D.newHead).Represents S.sourceFirstNormalized :=
    ⟨targetToSplit.toRepresentation.trans sourceInOldNew⟩
  let hyperbolicToZero :=
    (scaledZeroOmearaPlaneLatticeIsometry (K := K) (1 : Kˣ)).symm
      |>.toQuadraticSpaceIsometry
  let pairToTower :=
    (hyperbolicToZero.orthogonalSum hyperbolicToZero).trans
      (twoZeroPlaneProductToTowerTwoSpaceIsometry (K := K))
  let sourceToPair := S.sourceFirstNormalizedHyperbolicTowerIsometry.trans
    pairToTower.symm
  have pairInSplit :
      ((QuadraticSpace.hyperbolicPlane (1 : Kˣ)).orthogonalSum
        D.newHead).Represents
      ((QuadraticSpace.hyperbolicPlane (1 : Kˣ)).orthogonalSum
        (QuadraticSpace.hyperbolicPlane (1 : Kˣ))) :=
    sourceInSplit.trans ⟨sourceToPair.symm.toRepresentation⟩
  exact QuadraticSpace.orthogonalSumLeftCancelRepresents
    (QuadraticSpace.hyperbolicPlane (1 : Kˣ))
    (QuadraticSpace.hyperbolicPlane (1 : Kˣ)) D.newHead pairInSplit

/-- The determinant-one rank-four criterion turns the preceding
representation into the standard hyperbolic tower. -/
theorem adjacentOrderNewHeadIsHyperbolicOfConditionII
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int))
    (htrigger : S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0)) :
    let D := S.adjacentOrderErrorData A conditions hgap hfirst
    D.newHead.IsIsometric
      (QuadraticSpace.scaledZeroOmearaTowerForm (1 : Kˣ) 2) := by
  let D := S.adjacentOrderErrorData A conditions hgap hfirst
  change D.newHead.IsIsometric
    (QuadraticSpace.scaledZeroOmearaTowerForm (1 : Kˣ) 2)
  letI : Module.Finite K (D.headSplit.decomposition.component 1).carrier :=
    D.newHeadLattice.moduleFinite
  have hpair :=
    QuadraticSpace.rankFour_isIsometric_hyperbolicPair_of_determinantClass_eq_one
      D.newHead D.newHeadLattice D.headSplit_complement_finrank
      (S.adjacentOrder_newHead_determinantClass_eq_one
        A conditions hgap hfirst)
      (S.adjacentOrderNewHeadRepresentsHyperbolicOfConditionII
        A conditions hgap hfirst htrigger)
  let hyperbolicToZero :=
    (scaledZeroOmearaPlaneLatticeIsometry (K := K) (1 : Kˣ)).symm
      |>.toQuadraticSpaceIsometry
  let pairToTower :=
    (hyperbolicToZero.orthogonalSum hyperbolicToZero).trans
      (twoZeroPlaneProductToTowerTwoSpaceIsometry (K := K))
  rcases hpair with ⟨f⟩
  exact ⟨f.trans pairToTower⟩

/-- Integral normalized-head alignment in the condition-(ii) branch. -/
noncomputable def adjacentOrderSourceToNewHeadIsometryOfConditionII
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int))
    (htrigger : S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0)) :
    let D := S.adjacentOrderErrorData A conditions hgap hfirst
    Isometry S.sourceFirstNormalized D.newHead
      (S.sourceJordan.component 0).lattice D.newHeadLattice := by
  let D := S.adjacentOrderErrorData A conditions hgap hfirst
  change Isometry S.sourceFirstNormalized D.newHead
    (S.sourceJordan.component 0).lattice D.newHeadLattice
  exact D.sourceToNewHeadIsometryOfHyperbolic
    (S.adjacentOrderNewHeadIsHyperbolicOfConditionII
      A conditions hgap hfirst htrigger)

/-- Install the adjacent-order coefficient shift as a saturated target
Jordan replacement. -/
noncomputable def adjacentOrderJordanReplacement
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int)) :
    Omeara9319JordanReplacement S.targetJordan :=
  (S.adjacentOrderErrorData A conditions hgap hfirst).jordanReplacement

/-- The displayed corrected head maps onto the first component of the
installed replacement. -/
noncomputable def adjacentOrderReplacementHeadIsometry
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int)) :
    let D := S.adjacentOrderErrorData A conditions hgap hfirst
    let R := S.adjacentOrderJordanReplacement A conditions hgap hfirst
    Isometry D.newHeadUnnormalized (R.target.component 0).space
      D.newHeadLattice (R.target.component 0).lattice := by
  let D := S.adjacentOrderErrorData A conditions hgap hfirst
  let R := S.adjacentOrderJordanReplacement A conditions hgap hfirst
  change Isometry D.newHeadUnnormalized (R.target.component 0).space
    D.newHeadLattice (R.target.component 0).lattice
  rw [show R.target = S.targetJordan.replaceFirstPairOfIsometry
      D.firstPairReplacementIsometry
      D.newHeadUnnormalized_modular D.newTailUnnormalized_modular
      D.newHeadUnnormalized_scaleIdeal D.newTailUnnormalized_scaleIdeal
      D.newHeadUnnormalized_normIdeal D.newTailUnnormalized_normIdeal by rfl]
  exact S.targetJordan.replaceFirstPairOfIsometry_leftIsometry
    D.firstPairReplacementIsometry
    D.newHeadUnnormalized_modular D.newTailUnnormalized_modular
    D.newHeadUnnormalized_scaleIdeal D.newTailUnnormalized_scaleIdeal
    D.newHeadUnnormalized_normIdeal D.newTailUnnormalized_normIdeal

/-- Normalize the installed replacement head at the unchanged first
Jordan scale. -/
noncomputable abbrev adjacentOrderTargetFirstNormalized
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int)) :
    QuadraticSpace K
      ((S.adjacentOrderJordanReplacement A conditions hgap hfirst)
        |>.target.component 0).carrier :=
  ((S.adjacentOrderJordanReplacement A conditions hgap hfirst)
    |>.target.component 0).space.rescaleUnit S.firstScale⁻¹

/-- The displayed normalized head is the actual normalized first
component of the installed replacement. -/
noncomputable def adjacentOrderNormalizedHeadIsometry
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int)) :
    let D := S.adjacentOrderErrorData A conditions hgap hfirst
    let R := S.adjacentOrderJordanReplacement A conditions hgap hfirst
    Isometry D.newHead
      (S.adjacentOrderTargetFirstNormalized A conditions hgap hfirst)
      D.newHeadLattice (R.target.component 0).lattice := by
  let D := S.adjacentOrderErrorData A conditions hgap hfirst
  let R := S.adjacentOrderJordanReplacement A conditions hgap hfirst
  let head := S.adjacentOrderReplacementHeadIsometry
    A conditions hgap hfirst
  let scaled := head.rescaleUnitBoth S.firstScale⁻¹
  let collapseRaw := rescaleUnitMulLatticeIsometry D.newHead
    D.newHeadLattice S.firstScale S.firstScale⁻¹
  have hscale : S.firstScale⁻¹ * S.firstScale = (1 : Kˣ) := by simp
  let finish : Isometry (D.newHead.rescaleUnit
      (S.firstScale⁻¹ * S.firstScale)) D.newHead
      D.newHeadLattice D.newHeadLattice := by
    simpa only [hscale] using
      Isometry.rescaleUnitOne D.newHead D.newHeadLattice
  let collapse : Isometry
      (D.newHeadUnnormalized.rescaleUnit S.firstScale⁻¹) D.newHead
      D.newHeadLattice D.newHeadLattice := by
    simpa only [EqualNormOrderErrorData.newHeadUnnormalized] using
      collapseRaw.trans finish
  exact collapse.symm.trans scaled

/-- Any normalized source-to-corrected-head isometry yields an isometry
to the installed replacement head after restoring the first scale. -/
noncomputable def adjacentOrderSourceToReplacementHeadIsometry
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int))
    (head : let D := S.adjacentOrderErrorData A conditions hgap hfirst
      Isometry S.sourceFirstNormalized D.newHead
        (S.sourceJordan.component 0).lattice D.newHeadLattice) :
    let R := S.adjacentOrderJordanReplacement A conditions hgap hfirst
    Isometry (S.sourceJordan.component 0).space (R.target.component 0).space
      (S.sourceJordan.component 0).lattice
      (R.target.component 0).lattice := by
  let R := S.adjacentOrderJordanReplacement A conditions hgap hfirst
  let normalized := head.trans
    (S.adjacentOrderNormalizedHeadIsometry A conditions hgap hfirst)
  let scaled := normalized.rescaleUnitBoth S.firstScale
  let undoSource := undoInverseRescaleLatticeIsometry
    (S.sourceJordan.component 0).space
    (S.sourceJordan.component 0).lattice S.firstScale
  let undoTarget := undoInverseRescaleLatticeIsometry
    (R.target.component 0).space (R.target.component 0).lattice S.firstScale
  exact undoSource.symm.trans (scaled.trans undoTarget)

/-- Package a normalized Step-6 head alignment as the replacement consumed
by the saturated 93:28 induction. -/
noncomputable def adjacentOrderHeadAlignedReplacementOfNormalizedHead
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int))
    (headNormalized :
      let D := S.adjacentOrderErrorData A conditions hgap hfirst
      Isometry S.sourceFirstNormalized D.newHead
        (S.sourceJordan.component 0).lattice D.newHeadLattice) :
    Omeara9328HeadAlignedReplacement S.sourceJordan S.targetJordan A := by
  let R := S.adjacentOrderJordanReplacement A conditions hgap hfirst
  let head := S.adjacentOrderSourceToReplacementHeadIsometry
    A conditions hgap hfirst headNormalized
  let boundary := omeara9328BoundaryZeroConditionsWith_of_headIsometry
    S.sourceJordan R.target A head
  exact R.headAlignedReplacement S.residualFundamentalType A conditions
    boundary head

/-- Condition-(ii) half of O'Meara 93:28, Step 6. -/
noncomputable def adjacentOrderHeadAlignedReplacementOfConditionII
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int))
    (htrigger : S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0)) :
    Omeara9328HeadAlignedReplacement S.sourceJordan S.targetJordan A :=
  S.adjacentOrderHeadAlignedReplacementOfNormalizedHead
    A conditions hgap hfirst
      (S.adjacentOrderSourceToNewHeadIsometryOfConditionII
        A conditions hgap hfirst htrigger)

/-- Negating the strict containment in condition 93:28(ii) in the
adjacent-order case gives the weak weight inequality needed to absorb
both rho-twists into the second component.  This includes the equality
case at the boundary of the condition. -/
theorem adjacentOrder_nontrigger_weight_order
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0)) :
    S.sourceJordan.fundamentalWeightOrder 1 ≤
      2 * (ramificationIndex K : Int) +
        S.sourceJordan.fundamentalScaleOrder 0 -
          ordUnit K S.firstNormGenerator := by
  rw [S.adjacentNormOrder_firstFundamentalIdeal_eq_normProduct A hgap]
    at hnontrigger
  unfold fourNormOverWeightIdealWith at hnontrigger
  rw [show boundaryRightIndex (0 : Fin (n + 1)) =
      (1 : Fin (n + 2)) by ext; rfl,
    principalIdeal_eq_powerIdeal, powerIdeal_lt_iff] at hnontrigger
  simp only [ordUnit_mul] at hnontrigger
  have hdeltaOrder :
      ordUnit K (S.secondNormalizedNormGeneratorWith A) =
        -ordUnit K (J.scaleGenerator 0) + ordUnit K (A.value 1) := by
    unfold secondNormalizedNormGeneratorWith
    simp only [ordUnit_mul, ordUnit_inv,
      Omeara9328RankFourReductionSystem.firstScale,
      S.sourceJordan_scaleGenerator]
  have hscale : S.sourceJordan.fundamentalScaleOrder 0 =
      ordUnit K (J.scaleGenerator 0) := by
    unfold fundamentalScaleOrder
    rw [S.sourceJordan_scaleGenerator]
  rw [hscale]
  omega

/-- A scalar whose order differs evenly from a norm generator and whose
first possible approximation error already lies in the weight ideal is
represented.  This is the perfect-residue-field argument used at the
equality boundary in O'Meara 93:28, Step 6. -/
theorem mem_normGroupSet_of_even_order_difference_of_weight_order_le_succ
    {X : Type*} [AddCommGroup X] [Module K X]
    {p : QuadraticSpace K X} {N : Lattice K X}
    (a z : Kˣ) (ha : IsNormGeneratorValue p N a)
    (hle : ordUnit K a ≤ ordUnit K z)
    (heven : Even (ordUnit K z - ordUnit K a))
    (hweight : weightIdealOrder p N ≤ ordUnit K z + 1) :
    (z : K) ∈ normGroupSet p N := by
  rw [normGroupSet_eq_integralSquareCoset_weightIdeal a ha]
  rcases exists_integral_square_approximation_of_even_order_difference
      a z hle heven with ⟨c, hc⟩
  let y : K := (z : K) - (a : K) * (c : K) ^ 2
  refine ⟨c, y, ?_, ?_⟩
  · rw [weightIdeal_eq_powerIdeal, mem_powerIdeal_iff]
    have hsucc := coe_int_add_one_le_of_lt hc
    exact (WithTop.coe_le_coe.mpr hweight).trans (by
      simpa only [y] using hsucc)
  · dsimp only [y]
    ring

/-- The negative rho-twist belonging to the first norm generator is
represented by the normalized second target component. -/
theorem adjacentOrder_neg_normTwist_mem_targetSecondNormalized
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0)) :
    ((-Lattice.scratch_omearaRhoTwistUnit S.firstNormGenerator : Kˣ) : K) ∈
      normGroupSet S.targetSecondNormalized
        (S.targetJordan.component 1).lattice := by
  apply S.scratch_mem_targetSecondNormalized_of_weight_order_le
  have hnon := S.adjacentOrder_nontrigger_weight_order A hgap hnontrigger
  rw [Lattice.scratch_neg_omearaRhoTwistUnit_order]
  omega

/-- The negative rho-twist belonging to a generator of the corrected
head weight is also represented by the normalized second target
component. -/
theorem adjacentOrder_neg_weightTwist_mem_targetSecondNormalized
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int))
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0))
    (hodd : Odd S.firstNormWeightParity) :
    let D := S.adjacentOrderErrorData A conditions hgap hfirst
    let N := D.newHeadOddDeterminantOneData hodd
      (S.adjacentOrder_newHead_determinantClass_eq_one
        A conditions hgap hfirst)
    ((-Lattice.scratch_omearaRhoTwistUnit N.parameters.b : Kˣ) : K) ∈
      normGroupSet S.targetSecondNormalized
        (S.targetJordan.component 1).lattice := by
  let D := S.adjacentOrderErrorData A conditions hgap hfirst
  let hdet := S.adjacentOrder_newHead_determinantClass_eq_one
    A conditions hgap hfirst
  let N := D.newHeadOddDeterminantOneData hodd hdet
  let x : Kˣ := -Lattice.scratch_omearaRhoTwistUnit N.parameters.b
  let delta := S.secondNormalizedNormGeneratorWith A
  have hnon := S.adjacentOrder_nontrigger_weight_order A hgap hnontrigger
  have hfirstWeight :=
    S.adjacentNormOrder_firstWeightOrder_eq_second A hgap hfirst
  apply mem_normGroupSet_of_even_order_difference_of_weight_order_le_succ
    delta x (S.secondNormalizedNormGeneratorWith_target A)
  · dsimp only [delta, x]
    rw [Lattice.scratch_neg_omearaRhoTwistUnit_order,
      N.parameters_b, ordUnit_uniformizerPowerUnit,
      ← D.newHead_weightIdealOrder_eq_source, hfirstWeight]
    omega
  · dsimp only [delta, x]
    rw [Lattice.scratch_neg_omearaRhoTwistUnit_order,
      N.parameters_b, ordUnit_uniformizerPowerUnit,
      ← D.newHead_weightIdealOrder_eq_source, hfirstWeight]
    refine ⟨(ramificationIndex K : Int) -
      ordUnit K S.firstNormGenerator - 1, ?_⟩
    omega
  · rw [← S.secondNormalized_weightIdealOrder_eq A,
      S.sourceSecondNormalized_weightIdealOrder_eq_fundamental]
    dsimp only [x]
    rw [Lattice.scratch_neg_omearaRhoTwistUnit_order,
      N.parameters_b, ordUnit_uniformizerPowerUnit,
      ← D.newHead_weightIdealOrder_eq_source, hfirstWeight]
    omega

/-- Left rho-twist represented by the corrected normalized tail. -/
theorem adjacentOrderKLeftTwist_mem
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int))
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0))
    (hodd : Odd S.firstNormWeightParity) :
    let D := S.adjacentOrderErrorData A conditions hgap hfirst
    let N := D.newHeadOddDeterminantOneData hodd
      (S.adjacentOrder_newHead_determinantClass_eq_one
        A conditions hgap hfirst)
    ((-Lattice.scratch_omearaRhoTwistUnit N.parameters.a : Kˣ) : K) ∈
      normGroupSet D.newTail D.newTailLattice := by
  let D := S.adjacentOrderErrorData A conditions hgap hfirst
  let hdet := S.adjacentOrder_newHead_determinantClass_eq_one
    A conditions hgap hfirst
  let N := D.newHeadOddDeterminantOneData hodd hdet
  apply D.tailShift.normGroup_subset
  rw [N.parameters_a]
  exact S.adjacentOrder_neg_normTwist_mem_targetSecondNormalized
    A hgap hnontrigger

/-- Right rho-twist represented by the corrected normalized tail. -/
theorem adjacentOrderKRightTwist_mem
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int))
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0))
    (hodd : Odd S.firstNormWeightParity) :
    let D := S.adjacentOrderErrorData A conditions hgap hfirst
    let N := D.newHeadOddDeterminantOneData hodd
      (S.adjacentOrder_newHead_determinantClass_eq_one
        A conditions hgap hfirst)
    ((-Lattice.scratch_omearaRhoTwistUnit N.parameters.b : Kˣ) : K) ∈
      normGroupSet D.newTail D.newTailLattice := by
  let D := S.adjacentOrderErrorData A conditions hgap hfirst
  let hdet := S.adjacentOrder_newHead_determinantClass_eq_one
    A conditions hgap hfirst
  let N := D.newHeadOddDeterminantOneData hodd hdet
  apply D.tailShift.normGroup_subset
  exact S.adjacentOrder_neg_weightTwist_mem_targetSecondNormalized
    A conditions hgap hfirst hnontrigger hodd

/-- Opaque result of the double rho-twist absorption in Step 6. -/
noncomputable def adjacentOrderKRhoTwistAbsorptionData
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int))
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0))
    (hodd : Odd S.firstNormWeightParity) :
    let D := S.adjacentOrderErrorData A conditions hgap hfirst
    let N := D.newHeadOddDeterminantOneData hodd
      (S.adjacentOrder_newHead_determinantClass_eq_one
        A conditions hgap hfirst)
    Lattice.Omeara9318RankFourModelParameters.RhoTwistAbsorptionData
      N.parameters D.newTail D.newTailLattice S.relativeSecondScale := by
  let D := S.adjacentOrderErrorData A conditions hgap hfirst
  let hdet := S.adjacentOrder_newHead_determinantClass_eq_one
    A conditions hgap hfirst
  let N := D.newHeadOddDeterminantOneData hodd hdet
  exact N.parameters.rhoTwistAbsorptionData N.alpha_zero
    D.tailShift.splitting.complement_modular
    D.tailShift_complement_finrank
    S.relativeSecondScale_isInMaximalIdeal
    (S.adjacentOrderKLeftTwist_mem A conditions hgap hfirst
      hnontrigger hodd)
    (S.adjacentOrderKRightTwist_mem A conditions hgap hfirst
      hnontrigger hodd)

/-- In the twisted 93:18(vi) alternative, the corrected target pair is
isometric to the untwisted `J`-head followed by the twice-shifted tail. -/
noncomputable def adjacentOrderKNormalizedPairIsometry
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int))
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0))
    (hodd : Odd S.firstNormWeightParity)
    (hk : let D := S.adjacentOrderErrorData A conditions hgap hfirst
      let N := D.newHeadOddDeterminantOneData hodd
        (S.adjacentOrder_newHead_determinantClass_eq_one
          A conditions hgap hfirst)
      IsIsometric D.newHead N.parameters.kData.space
        D.newHeadLattice N.parameters.kData.lattice) :
    let D := S.adjacentOrderErrorData A conditions hgap hfirst
    let N := D.newHeadOddDeterminantOneData hodd
      (S.adjacentOrder_newHead_determinantClass_eq_one
        A conditions hgap hfirst)
    let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions hgap
      hfirst hnontrigger hodd
    Isometry
      (S.targetFirstNormalized.orthogonalSum S.targetSecondNormalized)
      (N.parameters.jData.space.orthogonalSum B.tailSpace)
      (product (S.targetJordan.component 0).lattice
        (S.targetJordan.component 1).lattice)
      (product N.parameters.jData.lattice B.tailLattice) := by
  let D := S.adjacentOrderErrorData A conditions hgap hfirst
  let hdet := S.adjacentOrder_newHead_determinantClass_eq_one
    A conditions hgap hfirst
  let N := D.newHeadOddDeterminantOneData hodd hdet
  let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions hgap
    hfirst hnontrigger hodd
  let identifyK := (Classical.choice hk).orthogonalProductBasic
    (Isometry.refl D.newTail D.newTailLattice)
  exact D.normalizedPairIsometry.trans (identifyK.trans B.pairIsometry)

set_option maxHeartbeats 3000000 in
/-- The twice-shifted tail still has the coherent second norm generator.
This uses the sharp complement-containment theorem for each 93:19
exchange, rather than the false equal-ideal shortcut unavailable in
adjacent order. -/
theorem adjacentOrderKTail_normGenerator
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int))
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0))
    (hodd : Odd S.firstNormWeightParity) :
    let D := S.adjacentOrderErrorData A conditions hgap hfirst
    let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions hgap
      hfirst hnontrigger hodd
    IsNormGeneratorValue B.tailSpace B.tailLattice D.secondGenerator := by
  let D := S.adjacentOrderErrorData A conditions hgap hfirst
  let hdet := S.adjacentOrder_newHead_determinantClass_eq_one
    A conditions hgap hfirst
  let N := D.newHeadOddDeterminantOneData hodd hdet
  let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions hgap
    hfirst hnontrigger hodd
  have hweight := S.adjacentNormOrder_firstWeightOrder_eq_second
    A hgap hfirst
  have hbOrder : ordUnit K N.parameters.b = ordUnit K D.secondGenerator := by
    change ordUnit K N.parameters.b =
      ordUnit K (S.secondNormalizedNormGeneratorWith A)
    rw [N.parameters_b, ordUnit_uniformizerPowerUnit,
      ← D.newHead_weightIdealOrder_eq_source, hweight]
  have hbIdeal : principalIdeal (K := K) (N.parameters.b : K) =
      principalIdeal (K := K) (D.secondGenerator : K) :=
    (principalIdeal_eq_iff_ordUnit_eq _ _).2 hbOrder
  have hrightTail : N.parameters.kData.rightTail ∈
      principalIdeal (K := K) (D.secondGenerator : K) := by
    rw [← hbIdeal]
    exact N.parameters.kData.rightTailIdeal_le_bIdeal
      (generator_mem_principalIdeal N.parameters.kData.rightTail)
  have hleftTail : N.parameters.kData.leftTail ∈
      principalIdeal (K := K) (D.secondGenerator : K) := by
    rw [← hbIdeal]
    exact N.parameters.kData.leftTailIdeal_le_bIdeal
      (generator_mem_principalIdeal N.parameters.kData.leftTail)
  have hsIntegral : (S.relativeSecondScale : K) ^ 2 ∈ IntegerRing K :=
    (IntegerRing K).toSubring.pow_mem
      ((mem_integerRing_iff K).2
        (le_of_lt S.relativeSecondScale_isInMaximalIdeal)) 2
  have hrightScaleSq : (N.parameters.b : K) *
      (S.relativeSecondScale : K) ^ 2 ∈
        principalIdeal (K := K) (D.secondGenerator : K) := by
    have hbMem : (N.parameters.b : K) ∈
        principalIdeal (K := K) (D.secondGenerator : K) := by
      rw [← hbIdeal]
      exact generator_mem_principalIdeal (N.parameters.b : K)
    let c : IntegerRing K :=
      ⟨(S.relativeSecondScale : K) ^ 2, hsIntegral⟩
    have h := (principalIdeal (K := K)
      (D.secondGenerator : K)).smul_mem c hbMem
    change (S.relativeSecondScale : K) ^ 2 * (N.parameters.b : K) ∈
      principalIdeal (K := K) (D.secondGenerator : K) at h
    simpa only [mul_comm] using h
  have hrelativePositive : 0 < ordUnit K S.relativeSecondScale := by
    have hscaleStrict :
        S.sourceJordan.fundamentalScaleOrder 0 <
          S.sourceJordan.fundamentalScaleOrder 1 :=
      S.sourceJordan.scaleOrder_strict (by simp)
    have hrelative := S.relativeSecondScale_order
    omega
  have hleftScaleSq : (N.parameters.a : K) *
      (S.relativeSecondScale : K) ^ 2 ∈
        principalIdeal (K := K) (D.secondGenerator : K) := by
    apply mem_principalIdeal_of_ord_le (Units.ne_zero D.secondGenerator)
    rw [ord_mul, ord_pow, ← coe_ordUnit, ← coe_ordUnit,
      ← coe_ordUnit]
    apply WithTop.coe_le_coe.mpr
    simp only [two_nsmul]
    rw [N.parameters_a]
    change ordUnit K (S.secondNormalizedNormGeneratorWith A) ≤ _
    omega
  change IsNormGeneratorValue B.tailSpace B.tailLattice D.secondGenerator
  exact B.tailNormGenerator_of D.secondGenerator
    D.tailShift_complement_secondNormGenerator hrightTail hrightScaleSq
    hleftTail hleftScaleSq

/-- The two numerical hypotheses of O'Meara 93:28, Step 6, bundled so the
installation of the corrected first pair does not repeatedly elaborate the
same dependent equalities. -/
structure AdjacentOrderCase
    (A : FundamentalNormGeneratorChoice S.sourceJordan) : Prop where
  hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
    ordUnit K S.firstNormGenerator + 1
  hfirst : ordUnit K S.firstNormGenerator <
    (ramificationIndex K : Int)

/-- Although the corrected head is the twisted `K`-model, the untwisted
`J`-model has exactly the source norm group.  Unimodular classification
therefore gives an integral source-to-`J` isometry. -/
noncomputable def adjacentOrderKSourceToJHeadIsometry
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hodd : Odd S.firstNormWeightParity)
    (hk : let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
      let N := D.newHeadOddDeterminantOneData hodd
        (S.adjacentOrder_newHead_determinantClass_eq_one
          A conditions C.hgap C.hfirst)
      IsIsometric D.newHead N.parameters.kData.space
        D.newHeadLattice N.parameters.kData.lattice) :
    let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
    let N := D.newHeadOddDeterminantOneData hodd
      (S.adjacentOrder_newHead_determinantClass_eq_one
        A conditions C.hgap C.hfirst)
    Isometry S.sourceFirstNormalized N.parameters.jData.space
      (S.sourceJordan.component 0).lattice
      N.parameters.jData.lattice := by
  let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
  let hdet := S.adjacentOrder_newHead_determinantClass_eq_one
    A conditions C.hgap C.hfirst
  let N := D.newHeadOddDeterminantOneData hodd hdet
  change Isometry S.sourceFirstNormalized N.parameters.jData.space
    (S.sourceJordan.component 0).lattice N.parameters.jData.lattice
  let kIso := Classical.choice hk
  have hgroup :
      normGroupSet S.sourceFirstNormalized
          (S.sourceJordan.component 0).lattice =
        normGroupSet N.parameters.jData.space
          N.parameters.jData.lattice := by
    calc
      normGroupSet S.sourceFirstNormalized
          (S.sourceJordan.component 0).lattice =
          normGroupSet D.newHead D.newHeadLattice :=
        D.newHead_normGroupSet_eq_source
      _ = normGroupSet N.parameters.kData.space
          N.parameters.kData.lattice :=
        normGroupSet_eq_of_latticeIsometry kIso.symm
      _ = integralSquareCoset (N.parameters.a : K)
          (principalIdeal (K := K) (N.parameters.b : K)) :=
        N.parameters.k_normGroupSet_eq
      _ = normGroupSet N.parameters.jData.space
          N.parameters.jData.lattice :=
        N.parameters.j_normGroupSet_eq.symm
  let fieldIso := S.sourceFirstNormalizedHyperbolicTowerIsometry.trans
    (N.parameters.jSpaceToHyperbolicTowerIsometry N.alpha_zero).symm
  exact latticeIsometryToUnimodularModel
    S.sourceFirstNormalized_unimodular N.parameters.jData.isModular
    fieldIso hgroup

/-- The untwisted Step-6 head restored to the original first Jordan scale. -/
noncomputable abbrev adjacentOrderKHeadUnnormalized
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hodd : Odd S.firstNormWeightParity) :
    let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
    let N := D.newHeadOddDeterminantOneData hodd
      (S.adjacentOrder_newHead_determinantClass_eq_one
        A conditions C.hgap C.hfirst)
    QuadraticSpace K ((Fin 2 → K) × (Fin 2 → K)) := by
  let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
  let hdet := S.adjacentOrder_newHead_determinantClass_eq_one
    A conditions C.hgap C.hfirst
  let N := D.newHeadOddDeterminantOneData hodd hdet
  exact N.parameters.jData.space.rescaleUnit S.firstScale

/-- The twice-shifted Step-6 tail restored to the original second Jordan
scale. -/
noncomputable abbrev adjacentOrderKTailUnnormalized
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0))
    (hodd : Odd S.firstNormWeightParity) :
    let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions C.hgap
      C.hfirst hnontrigger hodd
    QuadraticSpace K B.Tail := by
  let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions C.hgap
    C.hfirst hnontrigger hodd
  exact B.tailSpace.rescaleUnit S.firstScale

/-- Undo the common first-scale normalization on the complete Step-6 pair
after both rho-twists have been absorbed. -/
noncomputable def adjacentOrderKOriginalPairIsometry
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0))
    (hodd : Odd S.firstNormWeightParity)
    (hk : let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
      let N := D.newHeadOddDeterminantOneData hodd
        (S.adjacentOrder_newHead_determinantClass_eq_one
          A conditions C.hgap C.hfirst)
      IsIsometric D.newHead N.parameters.kData.space
        D.newHeadLattice N.parameters.kData.lattice) :
    let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
    let N := D.newHeadOddDeterminantOneData hodd
      (S.adjacentOrder_newHead_determinantClass_eq_one
        A conditions C.hgap C.hfirst)
    let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions C.hgap
      C.hfirst hnontrigger hodd
    Isometry
      ((S.targetJordan.component 0).space.orthogonalSum
        (S.targetJordan.component 1).space)
      ((S.adjacentOrderKHeadUnnormalized A conditions C hodd).orthogonalSum
        (S.adjacentOrderKTailUnnormalized A conditions C
          hnontrigger hodd))
      (product (S.targetJordan.component 0).lattice
        (S.targetJordan.component 1).lattice)
      (product N.parameters.jData.lattice B.tailLattice) := by
  let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
  let hdet := S.adjacentOrder_newHead_determinantClass_eq_one
    A conditions C.hgap C.hfirst
  let N := D.newHeadOddDeterminantOneData hodd hdet
  let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions C.hgap
    C.hfirst hnontrigger hodd
  let normalized := S.adjacentOrderKNormalizedPairIsometry A conditions
    C.hgap C.hfirst hnontrigger hodd hk
  let scaled := normalized.rescaleUnitBoth S.firstScale
  let distributeSource := rescaleUnitOrthogonalProductIsometry
    S.targetFirstNormalized S.targetSecondNormalized
    (S.targetJordan.component 0).lattice
    (S.targetJordan.component 1).lattice S.firstScale
  let undoFirst : Isometry
      (S.targetFirstNormalized.rescaleUnit S.firstScale)
      (S.targetJordan.component 0).space
      (S.targetJordan.component 0).lattice
      (S.targetJordan.component 0).lattice := by
    simpa only [targetFirstNormalized] using
      undoInverseRescaleLatticeIsometry
        (S.targetJordan.component 0).space
        (S.targetJordan.component 0).lattice S.firstScale
  let undoSecond : Isometry
      (S.targetSecondNormalized.rescaleUnit S.firstScale)
      (S.targetJordan.component 1).space
      (S.targetJordan.component 1).lattice
      (S.targetJordan.component 1).lattice := by
    simpa only [targetSecondNormalized] using
      undoInverseRescaleLatticeIsometry
        (S.targetJordan.component 1).space
        (S.targetJordan.component 1).lattice S.firstScale
  let undoSource := distributeSource.trans
    (undoFirst.orthogonalProductBasic undoSecond)
  let distributeTarget := rescaleUnitOrthogonalProductIsometry
    N.parameters.jData.space B.tailSpace
    N.parameters.jData.lattice B.tailLattice S.firstScale
  exact undoSource.symm.trans (scaled.trans distributeTarget)

theorem adjacentOrderKHeadUnnormalized_modular
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hodd : Odd S.firstNormWeightParity) :
    let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
    let N := D.newHeadOddDeterminantOneData hodd
      (S.adjacentOrder_newHead_determinantClass_eq_one
        A conditions C.hgap C.hfirst)
    IsModular (S.adjacentOrderKHeadUnnormalized A conditions C hodd)
      N.parameters.jData.lattice (S.targetJordan.scaleGenerator 0) := by
  let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
  let hdet := S.adjacentOrder_newHead_determinantClass_eq_one
    A conditions C.hgap C.hfirst
  let N := D.newHeadOddDeterminantOneData hodd hdet
  have h := N.parameters.jData.isModular.rescaleQuadraticUnit S.firstScale
  simpa only [adjacentOrderKHeadUnnormalized,
    S.targetJordan_scaleGenerator,
    Omeara9328RankFourReductionSystem.firstScale, mul_one] using h

theorem adjacentOrderKTailUnnormalized_modular
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0))
    (hodd : Odd S.firstNormWeightParity) :
    let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions C.hgap
      C.hfirst hnontrigger hodd
    IsModular
      (S.adjacentOrderKTailUnnormalized A conditions C hnontrigger hodd)
      B.tailLattice (S.targetJordan.scaleGenerator 1) := by
  let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions C.hgap
    C.hfirst hnontrigger hodd
  have h := B.tailModular.rescaleQuadraticUnit S.firstScale
  simpa only [adjacentOrderKTailUnnormalized,
    EqualNormOrderErrorData.firstScale_mul_relativeSecondScale] using h

theorem adjacentOrderKHeadUnnormalized_scaleIdeal
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hodd : Odd S.firstNormWeightParity) :
    let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
    let N := D.newHeadOddDeterminantOneData hodd
      (S.adjacentOrder_newHead_determinantClass_eq_one
        A conditions C.hgap C.hfirst)
    scaleIdeal (S.adjacentOrderKHeadUnnormalized A conditions C hodd)
        N.parameters.jData.lattice =
      principalIdeal (K := K) (S.targetJordan.scaleGenerator 0 : K) := by
  let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
  let hdet := S.adjacentOrder_newHead_determinantClass_eq_one
    A conditions C.hgap C.hfirst
  let N := D.newHeadOddDeterminantOneData hodd hdet
  exact (S.adjacentOrderKHeadUnnormalized_modular A conditions C hodd)
    |>.scaleIdeal_eq_principal (by
      simp only [Module.finrank_prod, Module.finrank_fin_fun]
      omega)

theorem adjacentOrderKTailUnnormalized_scaleIdeal
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0))
    (hodd : Odd S.firstNormWeightParity) :
    let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions C.hgap
      C.hfirst hnontrigger hodd
    scaleIdeal
        (S.adjacentOrderKTailUnnormalized A conditions C hnontrigger hodd)
        B.tailLattice =
      principalIdeal (K := K) (S.targetJordan.scaleGenerator 1 : K) := by
  let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions C.hgap
    C.hfirst hnontrigger hodd
  exact (S.adjacentOrderKTailUnnormalized_modular A conditions C
    hnontrigger hodd).scaleIdeal_eq_principal (by rw [B.tailFinrank]; omega)

theorem adjacentOrderKHeadUnnormalized_normGenerator
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hodd : Odd S.firstNormWeightParity) :
    let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
    let N := D.newHeadOddDeterminantOneData hodd
      (S.adjacentOrder_newHead_determinantClass_eq_one
        A conditions C.hgap C.hfirst)
    IsNormGeneratorValue
      (S.adjacentOrderKHeadUnnormalized A conditions C hodd)
      N.parameters.jData.lattice
      (S.firstScale * S.firstNormGenerator) := by
  let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
  let hdet := S.adjacentOrder_newHead_determinantClass_eq_one
    A conditions C.hgap C.hfirst
  let N := D.newHeadOddDeterminantOneData hodd hdet
  change IsNormGeneratorValue
    (N.parameters.jData.space.rescaleUnit S.firstScale)
    N.parameters.jData.lattice (S.firstScale * S.firstNormGenerator)
  have h := N.parameters.jData.a_isNormGeneratorValue
    |>.rescaleQuadraticUnit S.firstScale
  simpa only [Omeara9318RankFourModelParameters.jData,
    N.parameters_a] using h

theorem adjacentOrderKTailUnnormalized_normGenerator
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0))
    (hodd : Odd S.firstNormWeightParity) :
    let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
    let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions C.hgap
      C.hfirst hnontrigger hodd
    IsNormGeneratorValue
      (S.adjacentOrderKTailUnnormalized A conditions C hnontrigger hodd)
      B.tailLattice (S.firstScale * D.secondGenerator) := by
  let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
  let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions C.hgap
    C.hfirst hnontrigger hodd
  have h := S.adjacentOrderKTail_normGenerator A conditions C.hgap C.hfirst
    hnontrigger hodd |>.rescaleQuadraticUnit S.firstScale
  simpa only [adjacentOrderKTailUnnormalized] using h

theorem adjacentOrderKHeadUnnormalized_normIdeal
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hodd : Odd S.firstNormWeightParity) :
    let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
    let N := D.newHeadOddDeterminantOneData hodd
      (S.adjacentOrder_newHead_determinantClass_eq_one
        A conditions C.hgap C.hfirst)
    normIdeal (S.adjacentOrderKHeadUnnormalized A conditions C hodd)
        N.parameters.jData.lattice =
      principalIdeal (K := K) (S.targetJordan.normGenerator 0 : K) := by
  let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
  let hdet := S.adjacentOrder_newHead_determinantClass_eq_one
    A conditions C.hgap C.hfirst
  let N := D.newHeadOddDeterminantOneData hodd hdet
  have htarget : IsNormGeneratorValue
      (S.targetJordan.component 0).space
      (S.targetJordan.component 0).lattice
      (S.firstScale * S.firstNormGenerator) := by
    have h := S.firstNormGenerator_target.unscaleQuadraticUnit
    simpa only [targetFirstNormalized, inv_inv] using h
  calc
    normIdeal (S.adjacentOrderKHeadUnnormalized A conditions C hodd)
        N.parameters.jData.lattice =
        principalIdeal (K := K)
          ((S.firstScale * S.firstNormGenerator : Kˣ) : K) :=
      (S.adjacentOrderKHeadUnnormalized_normGenerator
        A conditions C hodd).2
    _ = normIdeal (S.targetJordan.component 0).space
        (S.targetJordan.component 0).lattice := htarget.2.symm
    _ = principalIdeal (K := K) (S.targetJordan.normGenerator 0 : K) :=
      S.targetJordan.normIdeal_eq 0

theorem adjacentOrderKTailUnnormalized_normIdeal
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0))
    (hodd : Odd S.firstNormWeightParity) :
    let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
    let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions C.hgap
      C.hfirst hnontrigger hodd
    normIdeal
        (S.adjacentOrderKTailUnnormalized A conditions C hnontrigger hodd)
        B.tailLattice =
      principalIdeal (K := K) (S.targetJordan.normGenerator 1 : K) := by
  let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
  let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions C.hgap
    C.hfirst hnontrigger hodd
  calc
    normIdeal
        (S.adjacentOrderKTailUnnormalized A conditions C hnontrigger hodd)
        B.tailLattice =
        principalIdeal (K := K)
          ((S.firstScale * D.secondGenerator : Kˣ) : K) :=
      (S.adjacentOrderKTailUnnormalized_normGenerator A conditions C
        hnontrigger hodd).2
    _ = normIdeal (S.targetJordan.component 1).space
        (S.targetJordan.component 1).lattice :=
      D.targetSecond_unscaledNormGenerator.2.symm
    _ = principalIdeal (K := K) (S.targetJordan.normGenerator 1 : K) :=
      S.targetJordan.normIdeal_eq 1

/-- The restored untwisted head contains the old first-component norm
group. -/
theorem targetFirst_normGroupSet_subset_adjacentOrderKHeadUnnormalized
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hodd : Odd S.firstNormWeightParity)
    (hk : let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
      let N := D.newHeadOddDeterminantOneData hodd
        (S.adjacentOrder_newHead_determinantClass_eq_one
          A conditions C.hgap C.hfirst)
      IsIsometric D.newHead N.parameters.kData.space
        D.newHeadLattice N.parameters.kData.lattice) :
    let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
    let N := D.newHeadOddDeterminantOneData hodd
      (S.adjacentOrder_newHead_determinantClass_eq_one
        A conditions C.hgap C.hfirst)
    normGroupSet (S.targetJordan.component 0).space
        (S.targetJordan.component 0).lattice ⊆
      normGroupSet (S.adjacentOrderKHeadUnnormalized A conditions C hodd)
        N.parameters.jData.lattice := by
  let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
  let hdet := S.adjacentOrder_newHead_determinantClass_eq_one
    A conditions C.hgap C.hfirst
  let N := D.newHeadOddDeterminantOneData hodd hdet
  let sourceToJ := S.adjacentOrderKSourceToJHeadIsometry
    A conditions C hodd hk
  have hnormalized :
      normGroupSet S.targetFirstNormalized
          (S.targetJordan.component 0).lattice =
        normGroupSet N.parameters.jData.space
          N.parameters.jData.lattice :=
    S.firstNormalized_normGroupSet_eq.symm.trans
      (normGroupSet_eq_of_latticeIsometry sourceToJ).symm
  change normGroupSet (S.targetJordan.component 0).space
      (S.targetJordan.component 0).lattice ⊆
    normGroupSet (N.parameters.jData.space.rescaleUnit S.firstScale)
      N.parameters.jData.lattice
  intro z hz
  rw [mem_normGroupSet_rescaleQuadraticUnit_iff]
  rw [← hnormalized]
  rw [mem_normGroupSet_rescaleQuadraticUnit_iff]
  simpa only [Units.val_inv_eq_inv_val, inv_inv, ← mul_assoc,
    mul_inv_cancel₀ (Units.ne_zero S.firstScale), one_mul] using hz

/-- The restored twice-shifted tail contains the old second-component norm
group. -/
theorem targetSecond_normGroupSet_subset_adjacentOrderKTailUnnormalized
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0))
    (hodd : Odd S.firstNormWeightParity) :
    let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions C.hgap
      C.hfirst hnontrigger hodd
    normGroupSet (S.targetJordan.component 1).space
        (S.targetJordan.component 1).lattice ⊆
      normGroupSet
        (S.adjacentOrderKTailUnnormalized A conditions C hnontrigger hodd)
        B.tailLattice := by
  let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
  let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions C.hgap
    C.hfirst hnontrigger hodd
  change normGroupSet (S.targetJordan.component 1).space
      (S.targetJordan.component 1).lattice ⊆
    normGroupSet (B.tailSpace.rescaleUnit S.firstScale) B.tailLattice
  intro z hz
  rw [mem_normGroupSet_rescaleQuadraticUnit_iff]
  apply B.normGroup_subset
  apply D.tailShift.normGroup_subset
  rw [mem_normGroupSet_rescaleQuadraticUnit_iff]
  simpa only [Units.val_inv_eq_inv_val, inv_inv, ← mul_assoc,
    mul_inv_cancel₀ (Units.ne_zero S.firstScale), one_mul] using hz

/-- Regard the restored untwisted head and twice-shifted tail as a
decomposition of the original target first-pair sublattice. -/
noncomputable def adjacentOrderKFirstPairReplacementIsometry
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0))
    (hodd : Odd S.firstNormWeightParity)
    (hk : let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
      let N := D.newHeadOddDeterminantOneData hodd
        (S.adjacentOrder_newHead_determinantClass_eq_one
          A conditions C.hgap C.hfirst)
      IsIsometric D.newHead N.parameters.kData.space
        D.newHeadLattice N.parameters.kData.lattice) :
    let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
    let N := D.newHeadOddDeterminantOneData hodd
      (S.adjacentOrder_newHead_determinantClass_eq_one
        A conditions C.hgap C.hfirst)
    let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions C.hgap
      C.hfirst hnontrigger hodd
    Isometry
      ((S.adjacentOrderKHeadUnnormalized A conditions C hodd).orthogonalSum
        (S.adjacentOrderKTailUnnormalized A conditions C hnontrigger hodd))
      S.targetJordan.firstPairSublattice.space
      (product N.parameters.jData.lattice B.tailLattice)
      S.targetJordan.firstPairSublattice.lattice :=
  (S.adjacentOrderKOriginalPairIsometry A conditions C
    hnontrigger hodd hk).symm |>.trans
      (S.targetJordan.toOrthogonalDecomposition
        |>.orthogonalSupLatticeIsometry firstIndex_ne_secondIndex)

set_option maxHeartbeats 3000000 in
/-- Install the nontrigger twisted-model correction as a saturated Jordan
splitting of the original target lattice. -/
noncomputable def adjacentOrderKJordanReplacement
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0))
    (hodd : Odd S.firstNormWeightParity)
    (hk : let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
      let N := D.newHeadOddDeterminantOneData hodd
        (S.adjacentOrder_newHead_determinantClass_eq_one
          A conditions C.hgap C.hfirst)
      IsIsometric D.newHead N.parameters.kData.space
        D.newHeadLattice N.parameters.kData.lattice) :
    Omeara9319JordanReplacement S.targetJordan := by
  let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
  let hdet := S.adjacentOrder_newHead_determinantClass_eq_one
    A conditions C.hgap C.hfirst
  let N := D.newHeadOddDeterminantOneData hodd hdet
  let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions C.hgap
    C.hfirst hnontrigger hodd
  let f := S.adjacentOrderKFirstPairReplacementIsometry A conditions C
    hnontrigger hodd hk
  let hHeadMod := S.adjacentOrderKHeadUnnormalized_modular
    A conditions C hodd
  let hTailMod := S.adjacentOrderKTailUnnormalized_modular
    A conditions C hnontrigger hodd
  let hHeadScale := S.adjacentOrderKHeadUnnormalized_scaleIdeal
    A conditions C hodd
  let hTailScale := S.adjacentOrderKTailUnnormalized_scaleIdeal
    A conditions C hnontrigger hodd
  let hHeadNorm := S.adjacentOrderKHeadUnnormalized_normIdeal
    A conditions C hodd
  let hTailNorm := S.adjacentOrderKTailUnnormalized_normIdeal
    A conditions C hnontrigger hodd
  let T := S.targetJordan.replaceFirstPairOfIsometry f
    hHeadMod hTailMod hHeadScale hTailScale hHeadNorm hTailNorm
  exact
    { target := T
      fundamentalType :=
        S.targetJordan.replaceFirstPairOfIsometry_sameFundamentalType f
          hHeadMod hTailMod hHeadScale hTailScale hHeadNorm hTailNorm
      saturated :=
        S.targetJordan.replaceFirstPairOfIsometry_isSaturated f
          hHeadMod hTailMod hHeadScale hTailScale hHeadNorm hTailNorm
          S.targetJordan_isSaturated
          (S.targetFirst_normGroupSet_subset_adjacentOrderKHeadUnnormalized
            A conditions C hodd hk)
          (S.targetSecond_normGroupSet_subset_adjacentOrderKTailUnnormalized
            A conditions C hnontrigger hodd)
      laterPrefixIsometry := by
        intro k hk'
        exact S.targetJordan.toOrthogonalDecomposition
          |>.replacePair_first_prefixLatticeIsometry
            (S.targetJordan.firstPairDecompositionOfIsometry f) k hk' }

/-- The normalized source head, restored to the first Jordan scale, maps
integrally to the displayed untwisted head. -/
noncomputable def adjacentOrderKSourceToHeadUnnormalizedIsometry
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hodd : Odd S.firstNormWeightParity)
    (hk : let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
      let N := D.newHeadOddDeterminantOneData hodd
        (S.adjacentOrder_newHead_determinantClass_eq_one
          A conditions C.hgap C.hfirst)
      IsIsometric D.newHead N.parameters.kData.space
        D.newHeadLattice N.parameters.kData.lattice) :
    let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
    let N := D.newHeadOddDeterminantOneData hodd
      (S.adjacentOrder_newHead_determinantClass_eq_one
        A conditions C.hgap C.hfirst)
    Isometry (S.sourceJordan.component 0).space
      (S.adjacentOrderKHeadUnnormalized A conditions C hodd)
      (S.sourceJordan.component 0).lattice N.parameters.jData.lattice := by
  let normalized := S.adjacentOrderKSourceToJHeadIsometry
    A conditions C hodd hk
  let scaled := normalized.rescaleUnitBoth S.firstScale
  let undoSource := undoInverseRescaleLatticeIsometry
    (S.sourceJordan.component 0).space
    (S.sourceJordan.component 0).lattice S.firstScale
  exact undoSource.symm.trans scaled

set_option maxHeartbeats 3000000 in
/-- The displayed untwisted head maps onto the actual first component of
the installed Step-6 Jordan replacement. -/
noncomputable def adjacentOrderKReplacementHeadIsometry
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0))
    (hodd : Odd S.firstNormWeightParity)
    (hk : let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
      let N := D.newHeadOddDeterminantOneData hodd
        (S.adjacentOrder_newHead_determinantClass_eq_one
          A conditions C.hgap C.hfirst)
      IsIsometric D.newHead N.parameters.kData.space
        D.newHeadLattice N.parameters.kData.lattice) :
    let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
    let N := D.newHeadOddDeterminantOneData hodd
      (S.adjacentOrder_newHead_determinantClass_eq_one
        A conditions C.hgap C.hfirst)
    let R := S.adjacentOrderKJordanReplacement A conditions C
      hnontrigger hodd hk
    Isometry (S.adjacentOrderKHeadUnnormalized A conditions C hodd)
      (R.target.component 0).space N.parameters.jData.lattice
      (R.target.component 0).lattice := by
  let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
  let hdet := S.adjacentOrder_newHead_determinantClass_eq_one
    A conditions C.hgap C.hfirst
  let N := D.newHeadOddDeterminantOneData hodd hdet
  let B := S.adjacentOrderKRhoTwistAbsorptionData A conditions C.hgap
    C.hfirst hnontrigger hodd
  let f := S.adjacentOrderKFirstPairReplacementIsometry A conditions C
    hnontrigger hodd hk
  let hHeadMod := S.adjacentOrderKHeadUnnormalized_modular
    A conditions C hodd
  let hTailMod := S.adjacentOrderKTailUnnormalized_modular
    A conditions C hnontrigger hodd
  let hHeadScale := S.adjacentOrderKHeadUnnormalized_scaleIdeal
    A conditions C hodd
  let hTailScale := S.adjacentOrderKTailUnnormalized_scaleIdeal
    A conditions C hnontrigger hodd
  let hHeadNorm := S.adjacentOrderKHeadUnnormalized_normIdeal
    A conditions C hodd
  let hTailNorm := S.adjacentOrderKTailUnnormalized_normIdeal
    A conditions C hnontrigger hodd
  let R := S.adjacentOrderKJordanReplacement A conditions C
    hnontrigger hodd hk
  change Isometry (S.adjacentOrderKHeadUnnormalized A conditions C hodd)
    (R.target.component 0).space N.parameters.jData.lattice
    (R.target.component 0).lattice
  rw [show R.target = S.targetJordan.replaceFirstPairOfIsometry f
      hHeadMod hTailMod hHeadScale hTailScale hHeadNorm hTailNorm by rfl]
  exact S.targetJordan.replaceFirstPairOfIsometry_leftIsometry f
    hHeadMod hTailMod hHeadScale hTailScale hHeadNorm hTailNorm

/-- Source head aligned with the actual first component of the installed
nontrigger replacement. -/
noncomputable def adjacentOrderKSourceToReplacementHeadIsometry
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0))
    (hodd : Odd S.firstNormWeightParity)
    (hk : let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
      let N := D.newHeadOddDeterminantOneData hodd
        (S.adjacentOrder_newHead_determinantClass_eq_one
          A conditions C.hgap C.hfirst)
      IsIsometric D.newHead N.parameters.kData.space
        D.newHeadLattice N.parameters.kData.lattice) :
    let R := S.adjacentOrderKJordanReplacement A conditions C
      hnontrigger hodd hk
    Isometry (S.sourceJordan.component 0).space (R.target.component 0).space
      (S.sourceJordan.component 0).lattice (R.target.component 0).lattice :=
  (S.adjacentOrderKSourceToHeadUnnormalizedIsometry
    A conditions C hodd hk).trans
      (S.adjacentOrderKReplacementHeadIsometry A conditions C
        hnontrigger hodd hk)

/-- Complete Step-6 head-alignment object in the nontrigger twisted-model
branch. -/
noncomputable def adjacentOrderHeadAlignedReplacementOfNontriggerK
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0))
    (hodd : Odd S.firstNormWeightParity)
    (hk : let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
      let N := D.newHeadOddDeterminantOneData hodd
        (S.adjacentOrder_newHead_determinantClass_eq_one
          A conditions C.hgap C.hfirst)
      IsIsometric D.newHead N.parameters.kData.space
        D.newHeadLattice N.parameters.kData.lattice) :
    Omeara9328HeadAlignedReplacement S.sourceJordan S.targetJordan A := by
  let R := S.adjacentOrderKJordanReplacement A conditions C
    hnontrigger hodd hk
  let head := S.adjacentOrderKSourceToReplacementHeadIsometry
    A conditions C hnontrigger hodd hk
  let boundary := omeara9328BoundaryZeroConditionsWith_of_headIsometry
    S.sourceJordan R.target A head
  exact R.headAlignedReplacement S.residualFundamentalType A conditions
    boundary head

/-- Nontrigger even-parity subcase of O'Meara 93:28, Step 6. -/
noncomputable def adjacentOrderHeadAlignedReplacementOfNontriggerEven
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (heven : Even S.firstNormWeightParity) :
    Omeara9328HeadAlignedReplacement S.sourceJordan S.targetJordan A := by
  let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
  let hdet := S.adjacentOrder_newHead_determinantClass_eq_one
    A conditions C.hgap C.hfirst
  exact S.adjacentOrderHeadAlignedReplacementOfNormalizedHead
    A conditions C.hgap C.hfirst (D.sourceToNewHeadEvenIsometry heven hdet)

/-- Nontrigger odd-parity subcase when 93:18(vi) selects the untwisted
`J`-model directly. -/
noncomputable def adjacentOrderHeadAlignedReplacementOfNontriggerJ
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hodd : Odd S.firstNormWeightParity)
    (hj : let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
      let N := D.newHeadOddDeterminantOneData hodd
        (S.adjacentOrder_newHead_determinantClass_eq_one
          A conditions C.hgap C.hfirst)
      IsIsometric D.newHead N.parameters.jData.space
        D.newHeadLattice N.parameters.jData.lattice) :
    Omeara9328HeadAlignedReplacement S.sourceJordan S.targetJordan A := by
  let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
  let hdet := S.adjacentOrder_newHead_determinantClass_eq_one
    A conditions C.hgap C.hfirst
  let N := D.newHeadOddDeterminantOneData hodd hdet
  let jIso := Classical.choice hj
  have htower : D.newHead.IsIsometric
      (QuadraticSpace.scaledZeroOmearaTowerForm (1 : Kˣ) 2) :=
    ⟨jIso.toQuadraticSpaceIsometry.trans
      (N.parameters.jSpaceToHyperbolicTowerIsometry N.alpha_zero)⟩
  exact S.adjacentOrderHeadAlignedReplacementOfNormalizedHead
    A conditions C.hgap C.hfirst
      (D.sourceToNewHeadIsometryOfHyperbolic htower)

/-- The non-condition-(ii) half of Step 6: even heads are hyperbolic by
93:18(ii), while odd heads are the two alternatives of 93:18(vi), with the
`K` alternative converted to `J` by two explicit 93:19 shifts. -/
noncomputable def adjacentOrderHeadAlignedReplacementOfNontrigger
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (C : S.AdjacentOrderCase A)
    (hnontrigger : ¬ S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A
        (boundaryRightIndex 0)) :
    Omeara9328HeadAlignedReplacement S.sourceJordan S.targetJordan A := by
  by_cases hodd : Odd S.firstNormWeightParity
  · let D := S.adjacentOrderErrorData A conditions C.hgap C.hfirst
    let hdet := S.adjacentOrder_newHead_determinantClass_eq_one
      A conditions C.hgap C.hfirst
    let N := D.newHeadOddDeterminantOneData hodd hdet
    by_cases hj : IsIsometric D.newHead N.parameters.jData.space
        D.newHeadLattice N.parameters.jData.lattice
    · exact S.adjacentOrderHeadAlignedReplacementOfNontriggerJ
        A conditions C hodd hj
    · have hk := N.isometric_j_or_k.resolve_left hj
      exact S.adjacentOrderHeadAlignedReplacementOfNontriggerK
        A conditions C hnontrigger hodd hk
  · have heven : Even S.firstNormWeightParity :=
      Int.not_odd_iff_even.mp hodd
    exact S.adjacentOrderHeadAlignedReplacementOfNontriggerEven
      A conditions C heven

/-- Complete O'Meara 93:28 Step 6 in the adjacent normalized norm-order
case, with no residual local classification law. -/
noncomputable def adjacentOrderHeadAlignedReplacement
    (A : FundamentalNormGeneratorChoice S.sourceJordan)
    (conditions : S.sourceJordan.Omeara9328ConditionsWith
      S.targetJordan A)
    (hgap : ordUnit K (S.secondNormalizedNormGeneratorWith A) =
      ordUnit K S.firstNormGenerator + 1)
    (hfirst : ordUnit K S.firstNormGenerator <
      (ramificationIndex K : Int)) :
    Omeara9328HeadAlignedReplacement S.sourceJordan S.targetJordan A := by
  let C : S.AdjacentOrderCase A := ⟨hgap, hfirst⟩
  by_cases htrigger : S.sourceJordan.fundamentalIdeal 0 <
      S.sourceJordan.fourNormOverWeightIdealWith A (boundaryRightIndex 0)
  · exact S.adjacentOrderHeadAlignedReplacementOfConditionII
      A conditions C.hgap C.hfirst htrigger
  · exact S.adjacentOrderHeadAlignedReplacementOfNontrigger
      A conditions C htrigger

end Omeara9328RankFourReductionSystem

end Lattice.JordanDecomposition

end Bong
