/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.Omeara9325FundamentalMonotonicity

/-!
# O'Meara 93:27

The middle formula follows immediately from the odd branch of 93:26.  The
two even formulas additionally use the two weight inequalities of 93:25.
The only defect estimate needed in those cases is proved directly from the
square-coset description of a fundamental norm group.
-/

namespace Bong

open Dyadic Module

namespace Lattice.JordanDecomposition

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {q : QuadraticSpace K V} {L : Lattice K V} {t : Nat}

private theorem scalarIdeal_scalarIdeal_eq
    (a b : K) (I : CoefficientIdeal (K := K)) :
    scalarIdeal a (scalarIdeal b I) = scalarIdeal (a * b) I := by
  ext z
  constructor
  · rintro ⟨x, ⟨y, hy, rfl⟩, rfl⟩
    exact ⟨y, hy, by simp only [coefficientMulLinearMap_apply, mul_assoc]⟩
  · rintro ⟨y, hy, rfl⟩
    refine ⟨b * y, ⟨y, hy, rfl⟩, ?_⟩
    simp only [coefficientMulLinearMap_apply, mul_assoc]

/-- If `b` belongs to the norm group generated by `a`, then the defect of
`ab` is absorbed by `a` times the weight.  This is the square-approximation
argument used in the first case of 93:27. -/
theorem quadraticDefectIdeal_mul_le_scalarIdeal_weight_of_mem_normGroup
    (a b : Kˣ) (ha : IsNormGeneratorValue q L a)
    (hb : (b : K) ∈ normGroupSet q L) :
    quadraticDefectIdeal (a * b) ≤
      scalarIdeal (a : K) (weightIdeal q L) := by
  rw [normGroupSet_eq_integralSquareCoset_weightIdeal a ha] at hb
  rcases hb with ⟨c, y, hy, hb⟩
  refine (quadraticDefectIdeal_le_principalIdeal_sub_sq
    (a * b) ((a : K) * (c : K))).trans ?_
  rw [principalIdeal, Submodule.span_singleton_le_iff_mem]
  refine ⟨y, hy, ?_⟩
  simp only [coefficientMulLinearMap_apply]
  change (a : K) * y = (a : K) * (b : K) - ((a : K) * (c : K)) ^ 2
  rw [hb]
  ring

/-- The first formula of 93:27:
`s_i² f_i = a_(i+1) w_i` when `u_(i+1) = u_i`. -/
theorem scaledFundamentalIdeal_eq_rightNorm_mul_leftWeight_of_equal_normOrder
    (J : JordanDecomposition q L (t + 1)) (i : Fin t)
    (hgap : ordUnit K
        (J.fundamentalNormGenerator (boundaryRightIndex i)) =
      ordUnit K (J.fundamentalNormGenerator (boundaryLeftIndex i))) :
    J.scaledFundamentalIdeal i =
      scalarIdeal
        (J.fundamentalNormGenerator (boundaryRightIndex i) : K)
        (J.fundamentalWeightIdeal (boundaryLeftIndex i)) := by
  let li : Fin (t + 1) := boundaryLeftIndex i
  let ri : Fin (t + 1) := boundaryRightIndex i
  let a : Kˣ := J.fundamentalNormGenerator li
  let b : Kˣ := J.fundamentalNormGenerator ri
  have hgap' : ordUnit K b = ordUnit K a := by
    simpa only [a, b, li, ri] using hgap
  have heven : Even (J.boundaryNormOrderSum i) := by
    unfold boundaryNormOrderSum
    change Even (ordUnit K a + ordUnit K b)
    rw [hgap']
    exact ⟨ordUnit K a, by omega⟩
  rw [J.scaledFundamentalIdeal_eq_even_formula i heven]
  change (((quadraticDefectIdeal (a * b) ⊔
        scalarIdeal (a : K) (J.fundamentalWeightIdeal ri)) ⊔
      scalarIdeal (b : K) (J.fundamentalWeightIdeal li)) ⊔
      J.boundaryParityIdeal i) =
    scalarIdeal (b : K) (J.fundamentalWeightIdeal li)
  have hbGroup : (b : K) ∈ J.fundamentalNormGroup li :=
    J.fundamentalNormGroup_anti
      (boundaryLeftIndex_le_rightIndex i)
      (J.fundamentalNormGenerator_spec ri).1
  have hdefect : quadraticDefectIdeal (a * b) ≤
      scalarIdeal (b : K) (J.fundamentalWeightIdeal li) := by
    have h := quadraticDefectIdeal_mul_le_scalarIdeal_weight_of_mem_normGroup
      a b (J.fundamentalNormGenerator_spec li) hbGroup
    change quadraticDefectIdeal (a * b) ≤
      scalarIdeal (a : K) (J.fundamentalWeightIdeal li) at h
    rw [scalarIdeal_units_eq_of_ordUnit_eq a b _ hgap'.symm] at h
    exact h
  have hweights : J.fundamentalWeightOrder li ≤
      J.fundamentalWeightOrder ri := by
    simpa only [li, ri] using
      J.fundamentalWeightOrder_mono_of_even_normOrderGap
        (boundaryLeftIndex_le_rightIndex i)
        (show Even (ordUnit K b - ordUnit K a) by
          rw [hgap']
          exact ⟨0, by omega⟩)
  have hright : scalarIdeal (a : K) (J.fundamentalWeightIdeal ri) ≤
      scalarIdeal (b : K) (J.fundamentalWeightIdeal li) := by
    unfold fundamentalWeightOrder at hweights
    unfold fundamentalWeightIdeal
    rw [weightIdeal_eq_powerIdeal, weightIdeal_eq_powerIdeal,
      scalarIdeal_powerIdeal_units, scalarIdeal_powerIdeal_units,
      powerIdeal_le_iff]
    omega
  have hweightUpper := J.fundamentalWeightOrder_le_twoScaleOrder li
  have hparity : J.boundaryParityIdeal i ≤
      scalarIdeal (b : K) (J.fundamentalWeightIdeal li) := by
    unfold boundaryParityIdeal fundamentalWeightIdeal
    rw [twiceIdeal_powerIdeal, weightIdeal_eq_powerIdeal,
      scalarIdeal_powerIdeal_units, powerIdeal_le_iff]
    unfold fundamentalWeightOrder at hweightUpper
    have hhalf : J.boundaryNormOrderSum i / 2 = ordUnit K a := by
      unfold boundaryNormOrderSum
      change (ordUnit K a + ordUnit K b) / 2 = ordUnit K a
      rw [hgap']
      omega
    rw [hhalf]
    dsimp only [a, b, li, ri] at hweightUpper ⊢
    omega
  apply le_antisymm
  · exact _root_.sup_le
      (_root_.sup_le (_root_.sup_le hdefect hright) le_rfl)
      hparity
  · exact (_root_.le_sup_right :
      scalarIdeal (b : K) (J.fundamentalWeightIdeal li) ≤
        (quadraticDefectIdeal (a * b) ⊔
          scalarIdeal (a : K) (J.fundamentalWeightIdeal ri)) ⊔
          scalarIdeal (b : K) (J.fundamentalWeightIdeal li)).trans
      _root_.le_sup_left

/-- Unscaled form of the first formula in 93:27. -/
theorem fundamentalIdeal_eq_rightNorm_mul_leftWeight_of_equal_normOrder
    (J : JordanDecomposition q L (t + 1)) (i : Fin t)
    (hgap : ordUnit K
        (J.fundamentalNormGenerator (boundaryRightIndex i)) =
      ordUnit K (J.fundamentalNormGenerator (boundaryLeftIndex i))) :
    J.fundamentalIdeal i =
      scalarIdeal
        ((((J.scaleGenerator (boundaryLeftIndex i))⁻¹ ^ 2) *
          J.fundamentalNormGenerator (boundaryRightIndex i) : Kˣ) : K)
        (J.fundamentalWeightIdeal (boundaryLeftIndex i)) := by
  calc
    J.fundamentalIdeal i =
        scalarIdeal
          (((J.scaleGenerator (boundaryLeftIndex i))⁻¹ ^ 2 : Kˣ) : K)
          (scalarIdeal
            (J.fundamentalNormGenerator (boundaryRightIndex i) : K)
            (J.fundamentalWeightIdeal (boundaryLeftIndex i))) := by
      rw [fundamentalIdeal,
        J.scaledFundamentalIdeal_eq_rightNorm_mul_leftWeight_of_equal_normOrder
          i hgap]
    _ = scalarIdeal
        ((((J.scaleGenerator (boundaryLeftIndex i))⁻¹ ^ 2) *
          J.fundamentalNormGenerator (boundaryRightIndex i) : Kˣ) : K)
        (J.fundamentalWeightIdeal (boundaryLeftIndex i)) := by
      rw [scalarIdeal_scalarIdeal_eq]
      rfl

/-- A square-scaled element of the norm group gives the corresponding
unscaled defect bound.  The order hypothesis says that `b / c²` has the
same valuation as `a`. -/
theorem quadraticDefectIdeal_mul_le_scalarIdeal_weight_of_sq_mul_mem_normGroup
    (a b c : Kˣ) (hb : IsNormGeneratorValue q L b)
    (haScaled : (((c ^ 2) * a : Kˣ) : K) ∈ normGroupSet q L)
    (hord : ordUnit K b = ordUnit K a + 2 * ordUnit K c) :
    quadraticDefectIdeal (a * b) ≤
      scalarIdeal (a : K) (weightIdeal q L) := by
  rw [normGroupSet_eq_integralSquareCoset_weightIdeal b hb] at haScaled
  rcases haScaled with ⟨d, y, hy, hscaled⟩
  let quotient : Kˣ := b * c⁻¹ ^ 2
  have hquotientOrder : ordUnit K quotient = ordUnit K a := by
    dsimp only [quotient]
    rw [ordUnit_mul, ordUnit_pow, ordUnit_inv]
    omega
  refine (quadraticDefectIdeal_le_principalIdeal_sub_sq
    (a * b) ((b : K) * (d : K) * (c⁻¹ : Kˣ))).trans ?_
  rw [principalIdeal, Submodule.span_singleton_le_iff_mem]
  rw [← scalarIdeal_units_eq_of_ordUnit_eq quotient a _ hquotientOrder]
  refine ⟨y, hy, ?_⟩
  simp only [coefficientMulLinearMap_apply]
  dsimp only [quotient]
  simp only [Units.val_mul, Units.val_pow_eq_pow_val,
    Units.val_inv_eq_inv_val]
  have hscaled' : (c : K) ^ 2 * (a : K) =
      (b : K) * (d : K) ^ 2 + y := by
    simpa only [Units.val_mul, Units.val_pow_eq_pow_val] using hscaled
  calc
    (b : K) * (c : K)⁻¹ ^ 2 * y =
        (b : K) * (c : K)⁻¹ ^ 2 *
          ((c : K) ^ 2 * (a : K) - (b : K) * (d : K) ^ 2) := by
      rw [hscaled']
      ring
    _ = (a : K) * (b : K) -
        ((b : K) * (d : K) * (c : K)⁻¹) ^ 2 := by
      field_simp [Units.ne_zero c]

/-- The third formula of 93:27:
`s_i² f_i = a_i w_(i+1)` when `u_(i+1) = u_i + 2` and
`s_(i+1) = s_i + 1`. -/
theorem scaledFundamentalIdeal_eq_leftNorm_mul_rightWeight_of_gap_two
    (J : JordanDecomposition q L (t + 1)) (i : Fin t)
    (hnorm : ordUnit K
        (J.fundamentalNormGenerator (boundaryRightIndex i)) =
      ordUnit K (J.fundamentalNormGenerator (boundaryLeftIndex i)) + 2)
    (hscale : J.fundamentalScaleOrder (boundaryRightIndex i) =
      J.fundamentalScaleOrder (boundaryLeftIndex i) + 1) :
    J.scaledFundamentalIdeal i =
      scalarIdeal
        (J.fundamentalNormGenerator (boundaryLeftIndex i) : K)
        (J.fundamentalWeightIdeal (boundaryRightIndex i)) := by
  let li : Fin (t + 1) := boundaryLeftIndex i
  let ri : Fin (t + 1) := boundaryRightIndex i
  let a : Kˣ := J.fundamentalNormGenerator li
  let b : Kˣ := J.fundamentalNormGenerator ri
  have hnorm' : ordUnit K b = ordUnit K a + 2 := by
    simpa only [a, b, li, ri] using hnorm
  have hscale' : J.fundamentalScaleOrder ri =
      J.fundamentalScaleOrder li + 1 := by
    simpa only [li, ri] using hscale
  have heven : Even (J.boundaryNormOrderSum i) := by
    unfold boundaryNormOrderSum
    change Even (ordUnit K a + ordUnit K b)
    rw [hnorm']
    exact ⟨ordUnit K a + 1, by omega⟩
  rw [J.scaledFundamentalIdeal_eq_even_formula i heven]
  change (((quadraticDefectIdeal (a * b) ⊔
        scalarIdeal (a : K) (J.fundamentalWeightIdeal ri)) ⊔
      scalarIdeal (b : K) (J.fundamentalWeightIdeal li)) ⊔
      J.boundaryParityIdeal i) =
    scalarIdeal (a : K) (J.fundamentalWeightIdeal ri)
  let c : Kˣ := uniformizerPowerUnit K
    (J.fundamentalScaleOrder ri - J.fundamentalScaleOrder li)
  have hcOrder : ordUnit K c = 1 := by
    dsimp only [c]
    rw [ordUnit_uniformizerPowerUnit, hscale']
    omega
  have haScaled : (((c ^ 2) * a : Kˣ) : K) ∈
      J.fundamentalNormGroup ri := by
    exact J.fundamentalNormGroup_sq_scale_subset
      (boundaryLeftIndex_le_rightIndex i)
      (J.fundamentalNormGenerator_spec li).1
  have hdefect : quadraticDefectIdeal (a * b) ≤
      scalarIdeal (a : K) (J.fundamentalWeightIdeal ri) := by
    exact quadraticDefectIdeal_mul_le_scalarIdeal_weight_of_sq_mul_mem_normGroup
      a b c (J.fundamentalNormGenerator_spec ri) haScaled (by omega)
  have hweights : J.fundamentalWeightOrder ri -
        2 * J.fundamentalScaleOrder ri ≤
      J.fundamentalWeightOrder li -
        2 * J.fundamentalScaleOrder li := by
    simpa only [li, ri] using
      J.fundamentalWeightOrder_sub_two_scale_anti_of_even_normOrderGap
        (boundaryLeftIndex_le_rightIndex i)
        (show Even (ordUnit K b - ordUnit K a) by
          rw [hnorm']
          exact ⟨1, by omega⟩)
  have hleft : scalarIdeal (b : K) (J.fundamentalWeightIdeal li) ≤
      scalarIdeal (a : K) (J.fundamentalWeightIdeal ri) := by
    unfold fundamentalWeightOrder at hweights
    unfold fundamentalWeightIdeal
    rw [weightIdeal_eq_powerIdeal, weightIdeal_eq_powerIdeal,
      scalarIdeal_powerIdeal_units, scalarIdeal_powerIdeal_units,
      powerIdeal_le_iff]
    omega
  have hweightUpper := J.fundamentalWeightOrder_le_twoScaleOrder ri
  have hparity : J.boundaryParityIdeal i ≤
      scalarIdeal (a : K) (J.fundamentalWeightIdeal ri) := by
    unfold boundaryParityIdeal fundamentalWeightIdeal
    rw [twiceIdeal_powerIdeal, weightIdeal_eq_powerIdeal,
      scalarIdeal_powerIdeal_units, powerIdeal_le_iff]
    change ordUnit K a + J.fundamentalWeightOrder ri ≤
      J.boundaryNormOrderSum i / 2 +
        J.fundamentalScaleOrder li + ramificationIndex K
    have hhalf : J.boundaryNormOrderSum i / 2 = ordUnit K a + 1 := by
      unfold boundaryNormOrderSum
      change (ordUnit K a + ordUnit K b) / 2 = ordUnit K a + 1
      rw [hnorm']
      omega
    rw [hhalf]
    omega
  apply le_antisymm
  · exact _root_.sup_le
      (_root_.sup_le (_root_.sup_le hdefect le_rfl) hleft)
      hparity
  · exact ((_root_.le_sup_right :
      scalarIdeal (a : K) (J.fundamentalWeightIdeal ri) ≤
        quadraticDefectIdeal (a * b) ⊔
          scalarIdeal (a : K) (J.fundamentalWeightIdeal ri)).trans
      _root_.le_sup_left).trans _root_.le_sup_left

/-- Unscaled form of the third formula in 93:27. -/
theorem fundamentalIdeal_eq_leftNorm_mul_rightWeight_of_gap_two
    (J : JordanDecomposition q L (t + 1)) (i : Fin t)
    (hnorm : ordUnit K
        (J.fundamentalNormGenerator (boundaryRightIndex i)) =
      ordUnit K (J.fundamentalNormGenerator (boundaryLeftIndex i)) + 2)
    (hscale : J.fundamentalScaleOrder (boundaryRightIndex i) =
      J.fundamentalScaleOrder (boundaryLeftIndex i) + 1) :
    J.fundamentalIdeal i =
      scalarIdeal
        ((((J.scaleGenerator (boundaryLeftIndex i))⁻¹ ^ 2) *
          J.fundamentalNormGenerator (boundaryLeftIndex i) : Kˣ) : K)
        (J.fundamentalWeightIdeal (boundaryRightIndex i)) := by
  calc
    J.fundamentalIdeal i =
        scalarIdeal
          (((J.scaleGenerator (boundaryLeftIndex i))⁻¹ ^ 2 : Kˣ) : K)
          (scalarIdeal
            (J.fundamentalNormGenerator (boundaryLeftIndex i) : K)
            (J.fundamentalWeightIdeal (boundaryRightIndex i))) := by
      rw [fundamentalIdeal,
        J.scaledFundamentalIdeal_eq_leftNorm_mul_rightWeight_of_gap_two
          i hnorm hscale]
    _ = scalarIdeal
        ((((J.scaleGenerator (boundaryLeftIndex i))⁻¹ ^ 2) *
          J.fundamentalNormGenerator (boundaryLeftIndex i) : Kˣ) : K)
        (J.fundamentalWeightIdeal (boundaryRightIndex i)) := by
      rw [scalarIdeal_scalarIdeal_eq]
      rfl

/-- The second formula of 93:27:
`s_i² f_i = a_i a_(i+1) O` when `u_(i+1) = u_i + 1`. -/
theorem scaledFundamentalIdeal_eq_product_of_normOrder_succ
    (J : JordanDecomposition q L (t + 1)) (i : Fin t)
    (hgap : ordUnit K
        (J.fundamentalNormGenerator (boundaryRightIndex i)) =
      ordUnit K (J.fundamentalNormGenerator (boundaryLeftIndex i)) + 1) :
    J.scaledFundamentalIdeal i =
      principalIdeal (K := K)
        (((J.fundamentalNormGenerator (boundaryLeftIndex i)) *
          J.fundamentalNormGenerator (boundaryRightIndex i) : Kˣ) : K) := by
  apply J.scaledFundamentalIdeal_eq_principalIdeal_of_odd i
  unfold boundaryNormOrderSum
  rw [hgap]
  refine ⟨ordUnit K
    (J.fundamentalNormGenerator (boundaryLeftIndex i)), ?_⟩
  omega

/-- If the left fundamental scale is already normalized to order zero, the
unscaled fundamental ideal is the same product ideal. -/
theorem fundamentalIdeal_eq_product_of_normOrder_succ_of_leftScale_zero
    (J : JordanDecomposition q L (t + 1)) (i : Fin t)
    (hgap : ordUnit K
        (J.fundamentalNormGenerator (boundaryRightIndex i)) =
      ordUnit K (J.fundamentalNormGenerator (boundaryLeftIndex i)) + 1)
    (hscale : J.fundamentalScaleOrder (boundaryLeftIndex i) = 0) :
    J.fundamentalIdeal i =
      principalIdeal (K := K)
        (((J.fundamentalNormGenerator (boundaryLeftIndex i)) *
          J.fundamentalNormGenerator (boundaryRightIndex i) : Kˣ) : K) := by
  have hodd : Odd (J.boundaryNormOrderSum i) := by
    unfold boundaryNormOrderSum
    rw [hgap]
    refine ⟨ordUnit K
      (J.fundamentalNormGenerator (boundaryLeftIndex i)), ?_⟩
    omega
  rw [J.fundamentalIdeal_eq_principalIdeal_of_odd i hodd]
  apply (principalIdeal_eq_iff_ordUnit_eq _ _).mpr
  rw [ordUnit_mul, ordUnit_mul, ordUnit_mul, ordUnit_pow, ordUnit_inv]
  change ordUnit K (J.scaleGenerator (boundaryLeftIndex i)) = 0 at hscale
  rw [hscale]
  omega

end Lattice.JordanDecomposition

end Bong
