/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.DeterminantBasis
import Bong.Lattice.OrthogonalDecompositionProduct

/-!
# Volume orders of orthogonal decompositions

The volume order is additive under an orthogonal product.  Consequently a
two-component orthogonal decomposition has volume order equal to the sum of
the two component volume orders.  This is the determinant calculation used
in O'Meara, Section 82E, and in Beli (2003), Lemma 4.5.
-/

namespace Bong

open Dyadic
open Module

namespace Lattice

universe u v w z

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {W : Type w} [AddCommGroup W] [Module K W]
  {Z : Type z} [AddCommGroup Z] [Module K Z]

/-- The volume-order formula for a basis lattice, with an arbitrary finite
index type. -/
theorem coe_volumeOrder_basisLattice_eq_ord_det_toMatrix
    {ι : Type*} [Fintype ι] [DecidableEq ι]
    (q : QuadraticSpace K V) (b : Basis ι K V) :
    (volumeOrder q (basisLattice b) : WithTop Int) =
      ord K (LinearMap.BilinForm.toMatrix b q.bilin).det := by
  let e : ι ≃ Fin (Module.finrank K V) :=
    Fintype.equivFinOfCardEq (Module.finrank_eq_card_basis b).symm
  let bFin : Basis (Fin (Module.finrank K V)) K V := b.reindex e
  have hb : basisLattice bFin = basisLattice b :=
    basisLattice_reindex b e
  have hmatrix :
      LinearMap.BilinForm.toMatrix bFin q.bilin =
        Matrix.reindex e e (LinearMap.BilinForm.toMatrix b q.bilin) := by
    ext i j
    simp [bFin, LinearMap.BilinForm.toMatrix_apply]
  rw [← hb, coe_volumeOrder_basisLattice_eq_ord_basisGramDeterminant]
  change ord K (LinearMap.BilinForm.toMatrix bFin q.bilin).det = _
  rw [hmatrix, Matrix.det_reindex_self]

/-- The lattice generated by the product of two bases is the product of the
two basis lattices. -/
theorem basisLattice_prod
    {ι κ : Type*} [Finite ι] [Finite κ]
    (b : Basis ι K V) (c : Basis κ K W) :
    basisLattice (b.prod c) = product (basisLattice b) (basisLattice c) := by
  apply Lattice.ext
  ext z
  change z ∈ basisLattice (b.prod c) ↔
    z ∈ product (basisLattice b) (basisLattice c)
  rw [mem_basisLattice_iff_repr_mem_integerRing, mem_product_iff,
    mem_basisLattice_iff_repr_mem_integerRing,
    mem_basisLattice_iff_repr_mem_integerRing]
  constructor
  · intro hz
    exact ⟨fun i ↦ by simpa using hz (Sum.inl i),
      fun j ↦ by simpa using hz (Sum.inr j)⟩
  · rintro ⟨hzLeft, hzRight⟩ (i | j)
    · simpa using hzLeft i
    · simpa using hzRight j

/-- Orthogonal products multiply determinants, hence add volume orders. -/
theorem volumeOrder_orthogonalProduct
    (q : QuadraticSpace K V) (r : QuadraticSpace K W)
    (L : Lattice K V) (M : Lattice K W) :
    volumeOrder (q.orthogonalSum r) (product L M) =
      volumeOrder q L + volumeOrder r M := by
  classical
  let b := L.standardAmbientBasis
  let c := M.standardAmbientBasis
  have hbL : basisLattice b = L := by
    exact basisLattice_standardAmbientBasis L
  have hcM : basisLattice c = M := by
    exact basisLattice_standardAmbientBasis M
  have hLattice : basisLattice (b.prod c) = product L M := by
    rw [basisLattice_prod, hbL, hcM]
  have hmatrix :
      LinearMap.BilinForm.toMatrix (b.prod c) (q.orthogonalSum r).bilin =
        Matrix.fromBlocks
          (LinearMap.BilinForm.toMatrix b q.bilin) 0 0
          (LinearMap.BilinForm.toMatrix c r.bilin) := by
    ext (i | i) (j | j) <;>
      simp [LinearMap.BilinForm.toMatrix_apply,
        QuadraticSpace.orthogonalSum_bilin_apply]
  apply WithTop.coe_injective
  rw [← hLattice,
    coe_volumeOrder_basisLattice_eq_ord_det_toMatrix, hmatrix,
    Matrix.det_fromBlocks_zero₂₁, ord_mul,
    ← coe_volumeOrder_basisLattice_eq_ord_det_toMatrix q b,
    ← coe_volumeOrder_basisLattice_eq_ord_det_toMatrix r c]
  rw [hbL, hcM]
  norm_cast

/-- Integral quadratic isometries preserve the volume order. -/
theorem volumeOrder_eq_of_isometry
    {q : QuadraticSpace K V} {r : QuadraticSpace K W}
    {L : Lattice K V} {M : Lattice K W}
    (f : Isometry q r L M) :
    volumeOrder q L = volumeOrder r M := by
  classical
  let b := L.standardAmbientBasis
  let c := b.map f.toLinearEquiv
  have hbL : basisLattice b = L := by
    exact basisLattice_standardAmbientBasis L
  have hLattice : basisLattice c = M := by
    calc
      basisLattice c = map f.toLinearEquiv (basisLattice b) := by
        apply Lattice.ext
        ext y
        change y ∈ basisLattice c ↔
          y ∈ map f.toLinearEquiv (basisLattice b)
        rw [mem_map_iff, mem_basisLattice_iff_repr_mem_integerRing,
          mem_basisLattice_iff_repr_mem_integerRing]
        simp [c, b]
      _ = map f.toLinearEquiv L := by
        rw [hbL]
      _ = M := f.map_eq
  have hmatrix :
      LinearMap.BilinForm.toMatrix c r.bilin =
        LinearMap.BilinForm.toMatrix b q.bilin := by
    ext i j
    simp [c, LinearMap.BilinForm.toMatrix_apply, f.map_bilin]
  apply WithTop.coe_injective
  rw [← hLattice,
    coe_volumeOrder_basisLattice_eq_ord_det_toMatrix, hmatrix,
    ← coe_volumeOrder_basisLattice_eq_ord_det_toMatrix q b,
    hbL]

namespace OrthogonalDecomposition

variable {q : QuadraticSpace K V} {L : Lattice K V}

/-- The volume order of a two-component orthogonal decomposition is the sum
of the component volume orders. -/
theorem volumeOrder_eq_add_components
    (D : OrthogonalDecomposition q L 2) :
    volumeOrder q L =
      volumeOrder (D.component 0).space (D.component 0).lattice +
        volumeOrder (D.component 1).space (D.component 1).lattice := by
  rw [← volumeOrder_orthogonalProduct]
  exact (volumeOrder_eq_of_isometry D.pairProductLatticeIsometry).symm

end OrthogonalDecomposition

end Lattice

end Bong
