/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.Ideals
import Bong.Lattice.Basic
import Bong.Lattice.NormGenerator
import Bong.Lattice.Projection

/-!
# Ideals of a lattice generated by an orthogonal basis

For an orthogonal field basis, the scale and norm ideals of its integral basis
lattice are both generated by the diagonal quadratic values.  This is the
integral diagonal calculation used in the unary and binary BONG arguments.
-/

namespace Bong

open Dyadic
open Module

universe u v w

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]

namespace Lattice

private theorem bilin_mem_diagonalSpan_of_mem_basisSpan
    {ι : Type w} [Finite ι] (q : QuadraticSpace K V)
    (b : Basis ι K V) (horth : q.bilin.iIsOrtho b)
    {x y : V}
    (hx : x ∈ Submodule.span (IntegerRing K) (Set.range b))
    (hy : y ∈ Submodule.span (IntegerRing K) (Set.range b)) :
    q.bilin x y ∈ Submodule.span (IntegerRing K)
      (Set.range fun i => q.quadratic (b i)) := by
  let S : Set V := Set.range b
  let I : Submodule (IntegerRing K) K :=
    Submodule.span (IntegerRing K)
      (Set.range fun i => q.quadratic (b i))
  refine Submodule.span_induction
    (p := fun x _ => ∀ y, y ∈ Submodule.span (IntegerRing K) S →
      q.bilin x y ∈ I) ?_ ?_ ?_ ?_ hx y hy
  · rintro _ ⟨i, rfl⟩ y hy
    refine Submodule.span_induction
      (p := fun y _ => q.bilin (b i) y ∈ I) ?_ ?_ ?_ ?_ hy
    · rintro _ ⟨j, rfl⟩
      by_cases hij : i = j
      · subst j
        exact Submodule.subset_span ⟨i, rfl⟩
      · rw [(LinearMap.BilinForm.iIsOrtho_def.mp horth) i j hij]
        exact I.zero_mem
    · simp [I]
    · intro y z _ _ hy hz
      simpa only [LinearMap.BilinForm.add_right] using I.add_mem hy hz
    · intro a y _ hy
      have h := I.smul_mem a hy
      rw [← IsScalarTower.algebraMap_smul K a y,
        LinearMap.BilinForm.smul_right]
      simpa only [Algebra.smul_def] using h
  · simp [I]
  · intro x z _ _ hx hz y hy
    simpa only [LinearMap.BilinForm.add_left] using
      I.add_mem (hx y hy) (hz y hy)
  · intro a x _ hx y hy
    have h := I.smul_mem a (hx y hy)
    rw [← IsScalarTower.algebraMap_smul K a x,
      LinearMap.BilinForm.smul_left]
    simpa only [Algebra.smul_def] using h

/-- The scale ideal of an orthogonal basis lattice is generated diagonally. -/
theorem scaleIdeal_basisLattice_of_iIsOrtho
    {ι : Type w} [Finite ι] (q : QuadraticSpace K V)
    (b : Basis ι K V) (horth : q.bilin.iIsOrtho b) :
    scaleIdeal q (basisLattice b) =
      Submodule.span (IntegerRing K)
        (Set.range fun i => q.quadratic (b i)) := by
  apply le_antisymm
  · rw [scaleIdeal, Submodule.span_le]
    rintro _ ⟨p, rfl⟩
    exact bilin_mem_diagonalSpan_of_mem_basisSpan q b horth
      p.1.property p.2.property
  · rw [Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    apply bilin_mem_scaleIdeal_of_mem q (basisLattice b)
    · exact Submodule.subset_span ⟨i, rfl⟩
    · exact Submodule.subset_span ⟨i, rfl⟩

/-- The norm ideal of an orthogonal basis lattice is generated diagonally. -/
theorem normIdeal_basisLattice_of_iIsOrtho
    {ι : Type w} [Finite ι] (q : QuadraticSpace K V)
    (b : Basis ι K V) (horth : q.bilin.iIsOrtho b) :
    normIdeal q (basisLattice b) =
      Submodule.span (IntegerRing K)
        (Set.range fun i => q.quadratic (b i)) := by
  apply le_antisymm
  · rw [← scaleIdeal_basisLattice_of_iIsOrtho q b horth]
    exact normIdeal_le_scaleIdeal q (basisLattice b)
  · rw [Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    exact quadratic_mem_normIdeal_of_mem q (basisLattice b)
      (Submodule.subset_span ⟨i, rfl⟩)

/-- In an orthogonal one-dimensional basis lattice, the basis vector is a
norm generator. -/
theorem isNormGenerator_basisLattice_fin_one
    (q : QuadraticSpace K V) (b : Basis (Fin 1) K V)
    (horth : q.bilin.iIsOrtho b) :
    IsNormGenerator q (basisLattice b) (b 0) := by
  constructor
  · exact Submodule.subset_span ⟨0, rfl⟩
  · rw [normIdeal_basisLattice_of_iIsOrtho q b horth]
    have hrange :
        Set.range (fun i => q.quadratic (b i)) =
          {q.quadratic (b 0)} := by
      ext a
      constructor
      · rintro ⟨i, rfl⟩
        have hi : i = 0 := Subsingleton.elim i 0
        subst i
        rfl
      · intro ha
        rw [Set.mem_singleton_iff] at ha
        exact ⟨0, ha.symm⟩
    rw [hrange, principalIdeal]

/-- For an orthogonal binary basis lattice, a first value of no larger order
is a norm generator. -/
theorem isNormGenerator_basisLattice_fin_two_of_ord_le
    (q : QuadraticSpace K V) (b : Basis (Fin 2) K V)
    (horth : q.bilin.iIsOrtho b)
    (hne : q.quadratic (b 0) ≠ 0)
    (horder : ord K (q.quadratic (b 0)) ≤
      ord K (q.quadratic (b 1))) :
    IsNormGenerator q (basisLattice b) (b 0) := by
  constructor
  · exact Submodule.subset_span ⟨0, rfl⟩
  · rw [normIdeal_basisLattice_of_iIsOrtho q b horth]
    apply le_antisymm
    · rw [Submodule.span_le]
      rintro _ ⟨i, rfl⟩
      refine Fin.cases (generator_mem_principalIdeal (q.quadratic (b 0)))
        (fun j => ?_) i
      have hj : j = 0 := Subsingleton.elim j 0
      subst j
      exact mem_principalIdeal_of_ord_le hne horder
    · rw [principalIdeal, Submodule.span_le]
      rintro _ ha
      rw [Set.mem_singleton_iff] at ha
      subst ha
      exact Submodule.subset_span ⟨0, rfl⟩

/-- Projecting a basis lattice whose tail basis lies in the head orthogonal
complement removes the head vector. -/
theorem projectedLattice_basisLattice_fin_succ
    {n : Nat} (q : QuadraticSpace K V) (b : Basis (Fin (n + 1)) K V)
    (hx : q.IsAnisotropic (b 0))
    (tail : Basis (Fin n) K (q.vectorOrthogonal (b 0)))
    (htail : ∀ i, (tail i : V) = b i.succ) :
    (basisLattice b).projectedLattice q (b 0) hx =
      basisLattice tail := by
  apply Lattice.ext
  change
    (Submodule.span (IntegerRing K) (Set.range b)).map
        ((q.projectionToOrthogonal (b 0) hx).restrictScalars
          (IntegerRing K)) =
      Submodule.span (IntegerRing K) (Set.range tail)
  rw [Submodule.map_span]
  apply le_antisymm
  · rw [Submodule.span_le]
    rintro _ ⟨_, ⟨i, rfl⟩, rfl⟩
    cases i using Fin.cases with
    | zero =>
        change q.projectionToOrthogonal (b 0) hx (b 0) ∈
          Submodule.span (IntegerRing K) (Set.range tail)
        have hzero : q.projectionToOrthogonal (b 0) hx (b 0) = 0 := by
          apply Subtype.ext
          exact q.orthogonalProjection_self hx
        rw [hzero]
        exact Submodule.zero_mem _
    | succ i =>
        rw [← htail i]
        change q.projectionToOrthogonal (b 0) hx (tail i : V) ∈
          Submodule.span (IntegerRing K) (Set.range tail)
        have hself : q.projectionToOrthogonal (b 0) hx (tail i : V) =
            tail i := by
          apply Subtype.ext
          exact q.orthogonalProjection_eq_self (tail i).property
        rw [hself]
        exact Submodule.subset_span ⟨i, rfl⟩
  · rw [Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    apply Submodule.subset_span
    refine ⟨(tail i : V), ⟨i.succ, (htail i).symm⟩, ?_⟩
    apply Subtype.ext
    exact q.orthogonalProjection_eq_self (tail i).property

/-- Projecting a basis lattice removes its head whenever the projections of
the remaining basis vectors form the supplied basis of the orthogonal
complement.  Unlike `projectedLattice_basisLattice_fin_succ`, the original
tail vectors need not themselves be orthogonal to the head. -/
theorem projectedLattice_basisLattice_fin_succ_of_projection
    {n : Nat} (q : QuadraticSpace K V) (b : Basis (Fin (n + 1)) K V)
    (hx : q.IsAnisotropic (b 0))
    (tail : Basis (Fin n) K (q.vectorOrthogonal (b 0)))
    (htail : ∀ i,
      q.projectionToOrthogonal (b 0) hx (b i.succ) = tail i) :
    (basisLattice b).projectedLattice q (b 0) hx =
      basisLattice tail := by
  apply Lattice.ext
  change
    (Submodule.span (IntegerRing K) (Set.range b)).map
        ((q.projectionToOrthogonal (b 0) hx).restrictScalars
          (IntegerRing K)) =
      Submodule.span (IntegerRing K) (Set.range tail)
  rw [Submodule.map_span]
  apply le_antisymm
  · rw [Submodule.span_le]
    rintro _ ⟨_, ⟨i, rfl⟩, rfl⟩
    cases i using Fin.cases with
    | zero =>
        change q.projectionToOrthogonal (b 0) hx (b 0) ∈
          Submodule.span (IntegerRing K) (Set.range tail)
        have hzero : q.projectionToOrthogonal (b 0) hx (b 0) = 0 := by
          apply Subtype.ext
          exact q.orthogonalProjection_self hx
        rw [hzero]
        exact Submodule.zero_mem _
    | succ i =>
        change q.projectionToOrthogonal (b 0) hx (b i.succ) ∈
          Submodule.span (IntegerRing K) (Set.range tail)
        rw [htail i]
        exact Submodule.subset_span ⟨i, rfl⟩
  · rw [Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    apply Submodule.subset_span
    exact ⟨b i.succ, ⟨i.succ, rfl⟩, htail i⟩

/-- Variant of
`projectedLattice_basisLattice_fin_succ_of_projection` in which the chosen
projection vector is propositionally, rather than definitionally, the first
basis vector.  This is useful for bases obtained by duality or reindexing. -/
theorem projectedLattice_basisLattice_fin_succ_of_projection_eq
    {n : Nat} (q : QuadraticSpace K V) (b : Basis (Fin (n + 1)) K V)
    (x : V) (hx : q.IsAnisotropic x)
    (tail : Basis (Fin n) K (q.vectorOrthogonal x))
    (hhead : b 0 = x)
    (htail : ∀ i,
      q.projectionToOrthogonal x hx (b i.succ) = tail i) :
    (basisLattice b).projectedLattice q x hx = basisLattice tail := by
  apply Lattice.ext
  change
    (Submodule.span (IntegerRing K) (Set.range b)).map
        ((q.projectionToOrthogonal x hx).restrictScalars
          (IntegerRing K)) =
      Submodule.span (IntegerRing K) (Set.range tail)
  rw [Submodule.map_span]
  apply le_antisymm
  · rw [Submodule.span_le]
    rintro _ ⟨_, ⟨i, rfl⟩, rfl⟩
    cases i using Fin.cases with
    | zero =>
        change q.projectionToOrthogonal x hx (b 0) ∈
          Submodule.span (IntegerRing K) (Set.range tail)
        rw [hhead]
        have hzero : q.projectionToOrthogonal x hx x = 0 := by
          apply Subtype.ext
          exact q.orthogonalProjection_self hx
        rw [hzero]
        exact Submodule.zero_mem _
    | succ i =>
        change q.projectionToOrthogonal x hx (b i.succ) ∈
          Submodule.span (IntegerRing K) (Set.range tail)
        rw [htail i]
        exact Submodule.subset_span ⟨i, rfl⟩
  · rw [Submodule.span_le]
    rintro _ ⟨i, rfl⟩
    apply Submodule.subset_span
    exact ⟨b i.succ, ⟨i.succ, rfl⟩, htail i⟩

end Lattice

end Bong
