/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.OrthogonalDecompositionPrefix

/-!
# Suffix lattices of integral orthogonal decompositions

This file is the suffix counterpart of `OrthogonalDecompositionPrefix`.
It realizes every numerical suffix as a full lattice in the corresponding
orthogonal carrier and identifies its ambient integral module with the sum of
the selected components.
-/

namespace Bong

open Dyadic Module
open scoped DirectSum

namespace Lattice

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {q : QuadraticSpace K V} {L : Lattice K V} {t : Nat}

namespace OrthogonalDecomposition

variable (D : OrthogonalDecomposition q L t)

/-- The bilinear form restricted to every suffix carrier is nondegenerate. -/
theorem suffixCarrier_nondegenerate (k : Nat) :
    (q.bilin.restrict (D.suffixCarrier k)).Nondegenerate := by
  apply q.bilin.nondegenerate_restrict_of_disjoint_orthogonal q.isSymm.isRefl
  rw [Submodule.disjoint_def]
  intro x hxS hxOrth
  apply q.nondegenerate.1 x
  intro y
  have hy : y ∈ D.prefixCarrier k ⊔ D.suffixCarrier k := by
    rw [D.prefixCarrier_sup_suffixCarrier k]
    trivial
  rw [Submodule.mem_sup] at hy
  rcases hy with ⟨p, hp, s, hs, rfl⟩
  rw [LinearMap.BilinForm.add_right]
  have hxp : q.bilin x p = 0 :=
    q.isSymm.eq x p |>.trans
      (D.bilin_prefixCarrier_suffixCarrier_eq_zero k hp hxS)
  have hxs : q.bilin x s = 0 :=
    q.isSymm.eq x s |>.trans (hxOrth s hs)
  rw [hxp, hxs, add_zero]

/-- The direct sum of the component carriers at or after `k` is canonically
equivalent to the suffix carrier. -/
noncomputable def suffixCarrierDirectSumEquiv (k : Nat) :
    (⨁ i : D.SuffixIndex k, (D.component i.1).carrier) ≃ₗ[K]
      D.suffixCarrier k :=
  (LinearEquiv.ofInjective
      (DFinsupp.lsum ℕ fun i : D.SuffixIndex k ↦
        (D.component i.1).carrier.subtype)
      (D.suffixCarrier_iSupIndep k).dfinsupp_lsum_injective).trans
    (LinearEquiv.ofEq _ _
      (Submodule.iSup_eq_range_dfinsupp_lsum
        (fun i : D.SuffixIndex k ↦
          (D.component i.1).carrier)).symm)

@[simp]
theorem coe_suffixCarrierDirectSumEquiv (k : Nat)
    (x : ⨁ i : D.SuffixIndex k, (D.component i.1).carrier) :
    ((D.suffixCarrierDirectSumEquiv k x : D.suffixCarrier k) : V) =
      DFinsupp.lsum ℕ
        (fun i : D.SuffixIndex k ↦ (D.component i.1).carrier.subtype) x := by
  rfl

/-- Concatenation of the chosen component lattice bases at or after `k`. -/
noncomputable def suffixAmbientBasis (k : Nat) :
    Basis (Σ i : D.SuffixIndex k,
      (D.component i.1).lattice.BasisIndex) K (D.suffixCarrier k) :=
  (DFinsupp.basis fun i : D.SuffixIndex k ↦
    (D.component i.1).lattice.ambientBasis).map
      (D.suffixCarrierDirectSumEquiv k)

@[simp]
theorem coe_suffixAmbientBasis_apply (k : Nat)
    (a : Σ i : D.SuffixIndex k,
      (D.component i.1).lattice.BasisIndex) :
    ((D.suffixAmbientBasis k a : D.suffixCarrier k) : V) =
      ((D.component a.1.1).lattice.ambientBasis a.2 :
        (D.component a.1.1).carrier) := by
  classical
  rw [suffixAmbientBasis, Basis.map_apply,
    suffixCarrierDirectSumEquiv, LinearEquiv.trans_apply,
    LinearEquiv.coe_ofEq_apply]
  simp [DFinsupp.basis]

/-- The full lattice on the suffix carrier generated by the component
integral bases. -/
noncomputable def suffixLattice (k : Nat) :
    Lattice K (D.suffixCarrier k) :=
  basisLattice (D.suffixAmbientBasis k)

/-- The suffix as an actual nondegenerate quadratic sublattice. -/
noncomputable def suffixQuadraticSublattice (k : Nat) :
    QuadraticSublattice q where
  carrier := D.suffixCarrier k
  nondegenerate := D.suffixCarrier_nondegenerate k
  lattice := D.suffixLattice k

@[simp]
theorem suffixQuadraticSublattice_carrier (k : Nat) :
    (D.suffixQuadraticSublattice k).carrier = D.suffixCarrier k :=
  rfl

@[simp]
theorem suffixQuadraticSublattice_lattice (k : Nat) :
    (D.suffixQuadraticSublattice k).lattice = D.suffixLattice k :=
  rfl

@[simp]
theorem suffixLattice_toSubmodule (k : Nat) :
    (D.suffixLattice k).toSubmodule =
      Submodule.span (IntegerRing K) (Set.range (D.suffixAmbientBasis k)) :=
  rfl

/-- The ambient integral module of the constructed suffix is exactly the sum
of the original component lattices at or after the cut. -/
theorem suffixQuadraticSublattice_ambientSubmodule (k : Nat) :
    (D.suffixQuadraticSublattice k).ambientSubmodule =
      D.suffixAmbientSubmodule k := by
  change (D.suffixLattice k).toSubmodule.map
      ((Submodule.subtype (D.suffixCarrier k)).restrictScalars
        (IntegerRing K)) = D.suffixAmbientSubmodule k
  apply le_antisymm
  · rintro x ⟨y, hy, rfl⟩
    change y ∈ (D.suffixLattice k).toSubmodule at hy
    rw [D.suffixLattice_toSubmodule k] at hy
    refine Submodule.span_induction
      (p := fun z _ ↦
        ((z : D.suffixCarrier k) : V) ∈ D.suffixAmbientSubmodule k)
      ?_ ?_ ?_ ?_ hy
    · rintro _ ⟨a, rfl⟩
      apply le_iSup
        (fun i : D.SuffixIndex k ↦
          (D.component i.1).ambientSubmodule) a.1
      rw [(D.component a.1.1).ambientSubmodule_eq_span_ambientBasis]
      apply Submodule.subset_span
      exact ⟨a.2, (D.coe_suffixAmbientBasis_apply k a).symm⟩
    · exact Submodule.zero_mem _
    · intro y z _ _ hy hz
      simpa only [Submodule.coe_add] using
        (D.suffixAmbientSubmodule k).add_mem hy hz
    · intro c z _ hz
      have hcz := (D.suffixAmbientSubmodule k).smul_mem c hz
      simpa only [Submodule.coe_smul_of_tower] using hcz
  · apply iSup_le
    intro i
    rw [(D.component i.1).ambientSubmodule_eq_span_ambientBasis,
      Submodule.span_le]
    rintro _ ⟨j, rfl⟩
    let a : Σ h : D.SuffixIndex k,
        (D.component h.1).lattice.BasisIndex := ⟨i, j⟩
    let y : D.suffixCarrier k := D.suffixAmbientBasis k a
    refine ⟨y, ?_, ?_⟩
    · change y ∈ (D.suffixLattice k).toSubmodule
      rw [D.suffixLattice_toSubmodule k]
      exact Submodule.subset_span ⟨a, rfl⟩
    · exact D.coe_suffixAmbientBasis_apply k a

/-- Membership in the internal suffix lattice is equivalent to ambient
membership in the integral suffix sum. -/
theorem mem_suffixLattice_iff (k : Nat) (x : D.suffixCarrier k) :
    x ∈ D.suffixLattice k ↔
      (x : V) ∈ D.suffixAmbientSubmodule k := by
  rw [← D.suffixQuadraticSublattice_ambientSubmodule k]
  constructor
  · intro hx
    exact ⟨x, hx, rfl⟩
  · rintro ⟨y, hy, hxy⟩
    have : y = x := Subtype.ext hxy
    rwa [← this]

end OrthogonalDecomposition

end Lattice

end Bong
