/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.OrthogonalDecompositionDual
import Bong.Lattice.JordanIsometry
import Bong.Lattice.OrthogonalSublatticeSum

/-!
# Prefixes of integral orthogonal decompositions

O'Meara's classification theorem uses the chains obtained by adjoining the
Jordan components in scale order.  This file constructs those chains as
actual quadratic sublattices.  The construction is intrinsic to an integral
orthogonal decomposition: the carrier is the direct sum of the selected
component carriers and its lattice is generated by the concatenated integral
component bases.
-/

namespace Bong

open Dyadic
open Module
open scoped DirectSum

namespace Lattice

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {q : QuadraticSpace K V} {L : Lattice K V} {t : Nat}

namespace OrthogonalDecomposition

variable (D : OrthogonalDecomposition q L t)

/-- Split a finite supremum at a numerical cut. -/
theorem iSup_fin_lt_sup_iSup_fin_ge {α : Type*} [CompleteLattice α]
    (f : Fin t → α) (k : Nat) :
    (⨆ i : {i : Fin t // i.val < k}, f i.1) ⊔
        (⨆ i : {i : Fin t // k ≤ i.val}, f i.1) =
      ⨆ i : Fin t, f i := by
  apply le_antisymm
  · apply _root_.sup_le
    · apply iSup_le
      intro i
      exact le_iSup f i.1
    · apply iSup_le
      intro i
      exact le_iSup f i.1
  · apply iSup_le
    intro i
    by_cases hi : i.val < k
    · exact le_sup_of_le_left
        (le_iSup (fun j : {j : Fin t // j.val < k} ↦ f j.1) ⟨i, hi⟩)
    · have hi' : k ≤ i.val := Nat.le_of_not_gt hi
      exact le_sup_of_le_right
        (le_iSup (fun j : {j : Fin t // k ≤ j.val} ↦ f j.1) ⟨i, hi'⟩)

/-- Indices lying strictly before the cut `k`. -/
abbrev PrefixIndex
    (_D : OrthogonalDecomposition q L t) (k : Nat) :=
  {i : Fin t // i.val < k}

/-- Indices lying at or after the cut `k`. -/
abbrev SuffixIndex
    (_D : OrthogonalDecomposition q L t) (k : Nat) :=
  {i : Fin t // k ≤ i.val}

/-- The vector subspace generated by the components before `k`. -/
noncomputable def prefixCarrier (k : Nat) : Submodule K V :=
  ⨆ i : D.PrefixIndex k, (D.component i.1).carrier

/-- The vector subspace generated by the components at or after `k`. -/
noncomputable def suffixCarrier (k : Nat) : Submodule K V :=
  ⨆ i : D.SuffixIndex k, (D.component i.1).carrier

/-- The integral sum of the components before `k`, embedded in the ambient
space. -/
noncomputable def prefixAmbientSubmodule (k : Nat) :
    Submodule (IntegerRing K) V :=
  ⨆ i : D.PrefixIndex k, (D.component i.1).ambientSubmodule

/-- The integral sum of the components at or after `k`, embedded in the
ambient space. -/
noncomputable def suffixAmbientSubmodule (k : Nat) :
    Submodule (IntegerRing K) V :=
  ⨆ i : D.SuffixIndex k, (D.component i.1).ambientSubmodule

/-- Restricting the component family to a prefix preserves independence. -/
theorem prefixCarrier_iSupIndep (k : Nat) :
    iSupIndep (fun i : D.PrefixIndex k ↦ (D.component i.1).carrier) := by
  exact D.carrier_iSupIndep.comp Subtype.coe_injective

/-- Restricting the component family to a suffix preserves independence. -/
theorem suffixCarrier_iSupIndep (k : Nat) :
    iSupIndep (fun i : D.SuffixIndex k ↦ (D.component i.1).carrier) := by
  exact D.carrier_iSupIndep.comp Subtype.coe_injective

/-- Prefix and suffix carriers together span the ambient space. -/
theorem prefixCarrier_sup_suffixCarrier (k : Nat) :
    D.prefixCarrier k ⊔ D.suffixCarrier k = ⊤ := by
  unfold prefixCarrier suffixCarrier
  calc
    (⨆ i : {i : Fin t // i.val < k},
        (D.component i.1).carrier) ⊔
        (⨆ i : {i : Fin t // k ≤ i.val},
          (D.component i.1).carrier) =
        ⨆ i : Fin t, (D.component i).carrier :=
      iSup_fin_lt_sup_iSup_fin_ge
        (fun i : Fin t ↦ (D.component i).carrier) k
    _ = ⊤ := D.carrier_iSup_eq_top

/-- Vectors in the prefix carrier are orthogonal to vectors in the suffix
carrier. -/
theorem bilin_prefixCarrier_suffixCarrier_eq_zero (k : Nat)
    {x y : V} (hx : x ∈ D.prefixCarrier k)
    (hy : y ∈ D.suffixCarrier k) :
    q.bilin x y = 0 := by
  induction hx using Submodule.iSup_induction' with
  | mem i x hxi =>
      induction hy using Submodule.iSup_induction' with
      | mem j y hyj =>
          have hij : i.1 ≠ j.1 := by
            intro h
            have hv : i.1.val = j.1.val := congrArg Fin.val h
            omega
          exact D.orthogonal i.1 j.1 hij ⟨x, hxi⟩ ⟨y, hyj⟩
      | zero => simp
      | add y z _ _ hy hz =>
          rw [LinearMap.BilinForm.add_right, hy, hz, add_zero]
  | zero => simp
  | add x z _ _ hx hz =>
      rw [LinearMap.BilinForm.add_left, hx, hz, add_zero]

/-- The prefix and suffix carriers have zero intersection. -/
theorem prefixCarrier_disjoint_suffixCarrier (k : Nat) :
    Disjoint (D.prefixCarrier k) (D.suffixCarrier k) := by
  rw [Submodule.disjoint_def]
  intro x hxP hxS
  apply q.nondegenerate.1 x
  intro y
  have hy : y ∈ D.prefixCarrier k ⊔ D.suffixCarrier k := by
    rw [D.prefixCarrier_sup_suffixCarrier k]
    trivial
  rw [Submodule.mem_sup] at hy
  rcases hy with ⟨p, hp, s, hs, rfl⟩
  rw [LinearMap.BilinForm.add_right]
  have hxp : q.bilin x p = 0 :=
    q.isSymm.eq x p |>.trans
      (D.bilin_prefixCarrier_suffixCarrier_eq_zero k hp hxS)
  have hxs : q.bilin x s = 0 :=
    D.bilin_prefixCarrier_suffixCarrier_eq_zero k hxP hs
  rw [hxp, hxs, add_zero]

/-- The bilinear form restricted to every prefix carrier is nondegenerate. -/
theorem prefixCarrier_nondegenerate (k : Nat) :
    (q.bilin.restrict (D.prefixCarrier k)).Nondegenerate := by
  apply q.bilin.nondegenerate_restrict_of_disjoint_orthogonal q.isSymm.isRefl
  rw [Submodule.disjoint_def]
  intro x hxP hxOrth
  apply q.nondegenerate.1 x
  intro y
  have hy : y ∈ D.prefixCarrier k ⊔ D.suffixCarrier k := by
    rw [D.prefixCarrier_sup_suffixCarrier k]
    trivial
  rw [Submodule.mem_sup] at hy
  rcases hy with ⟨p, hp, s, hs, rfl⟩
  rw [LinearMap.BilinForm.add_right]
  have hxp : q.bilin x p = 0 :=
    q.isSymm.eq x p |>.trans (hxOrth p hp)
  have hxs : q.bilin x s = 0 :=
    D.bilin_prefixCarrier_suffixCarrier_eq_zero k hxP hs
  rw [hxp, hxs, add_zero]

/-- The direct sum of the component carriers before `k` is canonically
equivalent to the prefix carrier. -/
noncomputable def prefixCarrierDirectSumEquiv (k : Nat) :
    (⨁ i : D.PrefixIndex k, (D.component i.1).carrier) ≃ₗ[K]
      D.prefixCarrier k :=
  (LinearEquiv.ofInjective
      (DFinsupp.lsum ℕ fun i : D.PrefixIndex k ↦
        (D.component i.1).carrier.subtype)
      (D.prefixCarrier_iSupIndep k).dfinsupp_lsum_injective).trans
    (LinearEquiv.ofEq _ _
      (Submodule.iSup_eq_range_dfinsupp_lsum
        (fun i : D.PrefixIndex k ↦
          (D.component i.1).carrier)).symm)

@[simp]
theorem coe_prefixCarrierDirectSumEquiv (k : Nat)
    (x : ⨁ i : D.PrefixIndex k, (D.component i.1).carrier) :
    ((D.prefixCarrierDirectSumEquiv k x : D.prefixCarrier k) : V) =
      DFinsupp.lsum ℕ
        (fun i : D.PrefixIndex k ↦ (D.component i.1).carrier.subtype) x := by
  rfl

/-- Concatenation of the chosen component lattice bases before `k`. -/
noncomputable def prefixAmbientBasis (k : Nat) :
    Basis (Σ i : D.PrefixIndex k,
      (D.component i.1).lattice.BasisIndex) K (D.prefixCarrier k) :=
  (DFinsupp.basis fun i : D.PrefixIndex k ↦
    (D.component i.1).lattice.ambientBasis).map
      (D.prefixCarrierDirectSumEquiv k)

@[simp]
theorem coe_prefixAmbientBasis_apply (k : Nat)
    (a : Σ i : D.PrefixIndex k,
      (D.component i.1).lattice.BasisIndex) :
    ((D.prefixAmbientBasis k a : D.prefixCarrier k) : V) =
      ((D.component a.1.1).lattice.ambientBasis a.2 :
        (D.component a.1.1).carrier) := by
  classical
  rw [prefixAmbientBasis, Basis.map_apply,
    prefixCarrierDirectSumEquiv, LinearEquiv.trans_apply,
    LinearEquiv.coe_ofEq_apply]
  simp [DFinsupp.basis]

/-- The full lattice on the prefix carrier generated by the component
integral bases. -/
noncomputable def prefixLattice (k : Nat) :
    Lattice K (D.prefixCarrier k) :=
  basisLattice (D.prefixAmbientBasis k)

/-- The prefix as an actual nondegenerate quadratic sublattice. -/
noncomputable def prefixQuadraticSublattice (k : Nat) :
    QuadraticSublattice q where
  carrier := D.prefixCarrier k
  nondegenerate := D.prefixCarrier_nondegenerate k
  lattice := D.prefixLattice k

@[simp]
theorem prefixQuadraticSublattice_carrier (k : Nat) :
    (D.prefixQuadraticSublattice k).carrier = D.prefixCarrier k :=
  rfl

@[simp]
theorem prefixQuadraticSublattice_lattice (k : Nat) :
    (D.prefixQuadraticSublattice k).lattice = D.prefixLattice k :=
  rfl

@[simp]
theorem prefixLattice_toSubmodule (k : Nat) :
    (D.prefixLattice k).toSubmodule =
      Submodule.span (IntegerRing K) (Set.range (D.prefixAmbientBasis k)) :=
  rfl

/-- The ambient integral module of the constructed prefix is exactly the
sum of the original component lattices before the cut. -/
theorem prefixQuadraticSublattice_ambientSubmodule (k : Nat) :
    (D.prefixQuadraticSublattice k).ambientSubmodule =
      D.prefixAmbientSubmodule k := by
  change (D.prefixLattice k).toSubmodule.map
      ((Submodule.subtype (D.prefixCarrier k)).restrictScalars
        (IntegerRing K)) = D.prefixAmbientSubmodule k
  apply le_antisymm
  · rintro x ⟨y, hy, rfl⟩
    change y ∈ (D.prefixLattice k).toSubmodule at hy
    rw [D.prefixLattice_toSubmodule k] at hy
    refine Submodule.span_induction
      (p := fun z _ ↦
        ((z : D.prefixCarrier k) : V) ∈ D.prefixAmbientSubmodule k)
      ?_ ?_ ?_ ?_ hy
    · rintro _ ⟨a, rfl⟩
      apply le_iSup
        (fun i : D.PrefixIndex k ↦
          (D.component i.1).ambientSubmodule) a.1
      rw [(D.component a.1.1).ambientSubmodule_eq_span_ambientBasis]
      apply Submodule.subset_span
      exact ⟨a.2, (D.coe_prefixAmbientBasis_apply k a).symm⟩
    · exact Submodule.zero_mem _
    · intro y z _ _ hy hz
      simpa only [Submodule.coe_add] using
        (D.prefixAmbientSubmodule k).add_mem hy hz
    · intro c z _ hz
      have hcz := (D.prefixAmbientSubmodule k).smul_mem c hz
      simpa only [Submodule.coe_smul_of_tower] using hcz
  · apply iSup_le
    intro i
    rw [(D.component i.1).ambientSubmodule_eq_span_ambientBasis,
      Submodule.span_le]
    rintro _ ⟨j, rfl⟩
    let a : Σ h : D.PrefixIndex k,
        (D.component h.1).lattice.BasisIndex := ⟨i, j⟩
    let y : D.prefixCarrier k := D.prefixAmbientBasis k a
    refine ⟨y, ?_, ?_⟩
    · change y ∈ (D.prefixLattice k).toSubmodule
      rw [D.prefixLattice_toSubmodule k]
      exact Submodule.subset_span ⟨a, rfl⟩
    · exact D.coe_prefixAmbientBasis_apply k a

/-- Prefix and suffix component lattices together recover the parent
lattice. -/
theorem prefixAmbientSubmodule_sup_suffixAmbientSubmodule (k : Nat) :
    D.prefixAmbientSubmodule k ⊔ D.suffixAmbientSubmodule k =
      L.toSubmodule := by
  unfold prefixAmbientSubmodule suffixAmbientSubmodule
  calc
    (⨆ i : {i : Fin t // i.val < k},
        (D.component i.1).ambientSubmodule) ⊔
        (⨆ i : {i : Fin t // k ≤ i.val},
          (D.component i.1).ambientSubmodule) =
        ⨆ i : Fin t, (D.component i).ambientSubmodule :=
      iSup_fin_lt_sup_iSup_fin_ge
        (fun i : Fin t ↦ (D.component i).ambientSubmodule) k
    _ = L.toSubmodule := D.sum_eq

/-- The integral prefix sum lies in its field-valued prefix carrier. -/
theorem mem_prefixCarrier_of_mem_prefixAmbientSubmodule (k : Nat)
    {x : V} (hx : x ∈ D.prefixAmbientSubmodule k) :
    x ∈ D.prefixCarrier k := by
  induction hx using Submodule.iSup_induction' with
  | mem i x hxi =>
      rcases hxi with ⟨xi, hxiL, rfl⟩
      exact le_iSup
        (fun j : D.PrefixIndex k ↦ (D.component j.1).carrier) i
        xi.property
  | zero => exact Submodule.zero_mem _
  | add x y _ _ hx hy => exact Submodule.add_mem _ hx hy

/-- The integral suffix sum lies in its field-valued suffix carrier. -/
theorem mem_suffixCarrier_of_mem_suffixAmbientSubmodule (k : Nat)
    {x : V} (hx : x ∈ D.suffixAmbientSubmodule k) :
    x ∈ D.suffixCarrier k := by
  induction hx using Submodule.iSup_induction' with
  | mem i x hxi =>
      rcases hxi with ⟨xi, hxiL, rfl⟩
      exact le_iSup
        (fun j : D.SuffixIndex k ↦ (D.component j.1).carrier) i
        xi.property
  | zero => exact Submodule.zero_mem _
  | add x y _ _ hx hy => exact Submodule.add_mem _ hx hy

/-- The integral prefix is precisely the intersection of the parent lattice
with the prefix vector space. -/
theorem mem_prefixAmbientSubmodule_iff (k : Nat) (x : V) :
    x ∈ D.prefixAmbientSubmodule k ↔
      x ∈ L ∧ x ∈ D.prefixCarrier k := by
  constructor
  · intro hx
    refine ⟨?_, D.mem_prefixCarrier_of_mem_prefixAmbientSubmodule k hx⟩
    have hle : D.prefixAmbientSubmodule k ≤ L.toSubmodule :=
      (_root_.le_sup_left : D.prefixAmbientSubmodule k ≤
        D.prefixAmbientSubmodule k ⊔ D.suffixAmbientSubmodule k).trans_eq
          (D.prefixAmbientSubmodule_sup_suffixAmbientSubmodule k)
    exact hle hx
  · rintro ⟨hxL, hxP⟩
    have hxSum : x ∈ D.prefixAmbientSubmodule k ⊔
        D.suffixAmbientSubmodule k := by
      rw [D.prefixAmbientSubmodule_sup_suffixAmbientSubmodule k]
      exact hxL
    rw [Submodule.mem_sup] at hxSum
    rcases hxSum with ⟨p, hp, s, hs, hps⟩
    have hpP : p ∈ D.prefixCarrier k :=
      D.mem_prefixCarrier_of_mem_prefixAmbientSubmodule k hp
    have hsS : s ∈ D.suffixCarrier k :=
      D.mem_suffixCarrier_of_mem_suffixAmbientSubmodule k hs
    have hsP : s ∈ D.prefixCarrier k := by
      have hseq : s = x - p := by
        rw [← hps]
        abel
      rw [hseq]
      exact (D.prefixCarrier k).sub_mem hxP hpP
    have hsZero : s = 0 :=
      Submodule.disjoint_def.mp (D.prefixCarrier_disjoint_suffixCarrier k)
        s hsP hsS
    rw [hsZero, add_zero] at hps
    rwa [← hps]

/-- Membership in the internal prefix lattice is equivalent to ambient
membership in the integral prefix sum. -/
theorem mem_prefixLattice_iff (k : Nat) (x : D.prefixCarrier k) :
    x ∈ D.prefixLattice k ↔
      (x : V) ∈ D.prefixAmbientSubmodule k := by
  rw [← D.prefixQuadraticSublattice_ambientSubmodule k]
  constructor
  · intro hx
    exact ⟨x, hx, rfl⟩
  · rintro ⟨y, hy, hxy⟩
    have : y = x := Subtype.ext hxy
    rwa [← this]

/-! ## Adjoining the next component -/

/-- A prefix together with the component at its cut spans the prefix one
component farther to the right. -/
theorem prefixCarrier_sup_component
    (D : OrthogonalDecomposition q L t) (p : Fin t) :
    D.prefixCarrier p.val ⊔ (D.component p).carrier =
      D.prefixCarrier (p.val + 1) := by
  unfold prefixCarrier
  apply le_antisymm
  · apply _root_.sup_le
    · apply iSup_le
      intro i
      exact le_iSup
        (fun j : D.PrefixIndex (p.val + 1) ↦
          (D.component j.1).carrier) ⟨i.1, by omega⟩
    · exact le_iSup
        (fun j : D.PrefixIndex (p.val + 1) ↦
          (D.component j.1).carrier) ⟨p, by omega⟩
  · apply iSup_le
    intro i
    by_cases hip : i.1.val < p.val
    · exact (le_iSup
        (fun j : D.PrefixIndex p.val ↦ (D.component j.1).carrier)
        ⟨i.1, hip⟩).trans _root_.le_sup_left
    · have hiEq : i.1 = p := by
        apply Fin.ext
        have hi := i.2
        omega
      simpa only [hiEq] using
        (_root_.le_sup_right : (D.component p).carrier ≤
          (⨆ j : D.PrefixIndex p.val,
            (D.component j.1).carrier) ⊔ (D.component p).carrier)

/-- Integral version of `prefixCarrier_sup_component`. -/
theorem prefixAmbientSubmodule_sup_component
    (D : OrthogonalDecomposition q L t) (p : Fin t) :
    D.prefixAmbientSubmodule p.val ⊔ (D.component p).ambientSubmodule =
      D.prefixAmbientSubmodule (p.val + 1) := by
  unfold prefixAmbientSubmodule
  apply le_antisymm
  · apply _root_.sup_le
    · apply iSup_le
      intro i
      exact le_iSup
        (fun j : D.PrefixIndex (p.val + 1) ↦
          (D.component j.1).ambientSubmodule) ⟨i.1, by omega⟩
    · exact le_iSup
        (fun j : D.PrefixIndex (p.val + 1) ↦
          (D.component j.1).ambientSubmodule) ⟨p, by omega⟩
  · apply iSup_le
    intro i
    by_cases hip : i.1.val < p.val
    · exact (le_iSup
        (fun j : D.PrefixIndex p.val ↦
          (D.component j.1).ambientSubmodule)
        ⟨i.1, hip⟩).trans _root_.le_sup_left
    · have hiEq : i.1 = p := by
        apply Fin.ext
        have hi := i.2
        omega
      simpa only [hiEq] using
        (_root_.le_sup_right : (D.component p).ambientSubmodule ≤
          (⨆ j : D.PrefixIndex p.val,
            (D.component j.1).ambientSubmodule) ⊔
              (D.component p).ambientSubmodule)

/-- The prefix before `p` is orthogonal to component `p`. -/
theorem prefix_orthogonal_component
    (D : OrthogonalDecomposition q L t) (p : Fin t)
    (x : (D.prefixQuadraticSublattice p.val).carrier)
    (y : (D.component p).carrier) :
    q.bilin (x : V) (y : V) = 0 := by
  apply D.bilin_prefixCarrier_suffixCarrier_eq_zero p.val x.property
  exact le_iSup
    (fun i : D.SuffixIndex p.val ↦ (D.component i.1).carrier)
    ⟨p, le_rfl⟩ y.property

/-- Concrete integral isometry
`prefix(p) ⊥ component(p) ≅ prefix(p+1)`. -/
noncomputable def prefixComponentLatticeIsometry
    (D : OrthogonalDecomposition q L t) (p : Fin t) :
    Isometry
      ((D.prefixQuadraticSublattice p.val).space.orthogonalSum
        (D.component p).space)
      (D.prefixQuadraticSublattice (p.val + 1)).space
      (product (D.prefixQuadraticSublattice p.val).lattice
        (D.component p).lattice)
      (D.prefixQuadraticSublattice (p.val + 1)).lattice :=
  QuadraticSublattice.orthogonalSumLatticeIsometry
    (D.prefixQuadraticSublattice p.val) (D.component p)
    (D.prefixQuadraticSublattice (p.val + 1))
    (by
      rw [D.prefixQuadraticSublattice_carrier,
        D.prefixQuadraticSublattice_carrier]
      exact D.prefixCarrier_sup_component p)
    (by
      rw [D.prefixQuadraticSublattice_ambientSubmodule,
        D.prefixQuadraticSublattice_ambientSubmodule]
      exact D.prefixAmbientSubmodule_sup_component p)
    (D.prefix_orthogonal_component p)

/-! ## The full-prefix boundary case -/

/-- Taking all components in a finite orthogonal decomposition gives the
whole ambient vector space. -/
theorem fullPrefixCarrier_eq_top
    (D : OrthogonalDecomposition q L t) :
    D.prefixCarrier t = ⊤ := by
  rw [← D.carrier_iSup_eq_top]
  unfold prefixCarrier
  apply le_antisymm
  · apply iSup_le
    intro i
    exact le_iSup (fun j : Fin t ↦ (D.component j).carrier) i.1
  · apply iSup_le
    intro i
    exact le_iSup
      (fun j : D.PrefixIndex t ↦ (D.component j.1).carrier)
      ⟨i, i.isLt⟩

/-- Taking all components also recovers the whole integral lattice in the
ambient space. -/
theorem fullPrefixAmbientSubmodule_eq
    (D : OrthogonalDecomposition q L t) :
    D.prefixAmbientSubmodule t = L.toSubmodule := by
  rw [← D.sum_eq]
  unfold prefixAmbientSubmodule
  apply le_antisymm
  · apply iSup_le
    intro i
    exact le_iSup
      (fun j : Fin t ↦ (D.component j).ambientSubmodule) i.1
  · apply iSup_le
    intro i
    exact le_iSup
      (fun j : D.PrefixIndex t ↦
        (D.component j.1).ambientSubmodule) ⟨i, i.isLt⟩

/-- The inclusion of the full prefix carrier is a linear equivalence onto
the ambient vector space. -/
noncomputable def fullPrefixLinearEquiv
    (D : OrthogonalDecomposition q L t) :
    D.prefixCarrier t ≃ₗ[K] V :=
  LinearEquiv.ofBijective (D.prefixCarrier t).subtype
    ⟨Subtype.val_injective, by
      intro x
      refine ⟨⟨x, ?_⟩, rfl⟩
      rw [D.fullPrefixCarrier_eq_top]
      trivial⟩

/-- The full prefix quadratic sublattice is integrally isometric to the
ambient lattice. -/
noncomputable def fullPrefixLatticeIsometry
    (D : OrthogonalDecomposition q L t) :
    Isometry (D.prefixQuadraticSublattice t).space q
      (D.prefixQuadraticSublattice t).lattice L where
  toLinearEquiv := D.fullPrefixLinearEquiv
  map_bilin _ _ := rfl
  map_mem x := by
    change x ∈ D.prefixLattice t ↔ (x : V) ∈ L
    exact (D.mem_prefixLattice_iff t
      (show D.prefixCarrier t from x)).trans (by
        rw [D.fullPrefixAmbientSubmodule_eq]
        rfl)

/-! ## The one-component boundary case -/

/-- A one-component decomposition identifies its sole component with the
ambient lattice. -/
theorem singleComponent_ambientSubmodule_eq
    (D : OrthogonalDecomposition q L 1) :
    (D.component 0).ambientSubmodule = L.toSubmodule := by
  rw [← D.sum_eq]
  apply le_antisymm
  · exact le_iSup (fun i : Fin 1 ↦ (D.component i).ambientSubmodule) 0
  · apply iSup_le
    intro i
    have hi : i = (0 : Fin 1) := Subsingleton.elim _ _
    simpa [hi]

/-- The carrier of the sole component is the whole ambient vector space. -/
theorem singleComponent_carrier_eq_top
    (D : OrthogonalDecomposition q L 1) :
    (D.component 0).carrier = ⊤ := by
  rw [← D.carrier_iSup_eq_top]
  apply le_antisymm
  · exact le_iSup (fun i : Fin 1 ↦ (D.component i).carrier) 0
  · apply iSup_le
    intro i
    have hi : i = (0 : Fin 1) := Subsingleton.elim _ _
    simpa [hi]

/-- The inclusion of the sole component is a linear equivalence. -/
noncomputable def singleComponentLinearEquiv
    (D : OrthogonalDecomposition q L 1) :
    (D.component 0).carrier ≃ₗ[K] V :=
  LinearEquiv.ofBijective (D.component 0).carrier.subtype
    ⟨Subtype.val_injective, by
      intro x
      refine ⟨⟨x, ?_⟩, rfl⟩
      rw [D.singleComponent_carrier_eq_top]
      trivial⟩

/-- A one-component decomposition gives an integral lattice isometry from
its component to the ambient lattice. -/
noncomputable def singleComponentLatticeIsometry
    (D : OrthogonalDecomposition q L 1) :
    Isometry (D.component 0).space q (D.component 0).lattice L where
  toLinearEquiv := D.singleComponentLinearEquiv
  map_bilin _ _ := rfl
  map_mem x := by
    constructor
    · intro hx
      have hxAmbient : (x : V) ∈ (D.component 0).ambientSubmodule :=
        ⟨x, hx, rfl⟩
      rw [D.singleComponent_ambientSubmodule_eq] at hxAmbient
      exact hxAmbient
    · intro hx
      have hxAmbient : (x : V) ∈ (D.component 0).ambientSubmodule := by
        rw [D.singleComponent_ambientSubmodule_eq]
        exact hx
      rcases hxAmbient with ⟨y, hy, hyx⟩
      have hxy : y = x := Subtype.ext hyx
      simpa [hxy] using hy

section Isometry

universe w

variable {W : Type w} [AddCommGroup W] [Module K W]
  {r : QuadraticSpace K W} {M : Lattice K W}

/-- An ambient lattice isometry maps the prefix carrier onto the prefix
carrier of the transported decomposition. -/
theorem prefixCarrier_mapIsometry
    (f : Lattice.Isometry q r L M) (k : Nat) :
    (D.prefixCarrier k).map f.toLinearEquiv.toLinearMap =
      (D.mapIsometry f).prefixCarrier k := by
  unfold prefixCarrier
  rw [Submodule.map_iSup]
  rfl

/-- The restricted ambient equivalence between corresponding prefix
carriers. -/
noncomputable def prefixCarrierMapEquiv
    (f : Lattice.Isometry q r L M) (k : Nat) :
    D.prefixCarrier k ≃ₗ[K] (D.mapIsometry f).prefixCarrier k :=
  (f.toLinearEquiv.submoduleMap (D.prefixCarrier k)).trans
    (LinearEquiv.ofEq _ _ (D.prefixCarrier_mapIsometry f k))

@[simp]
theorem coe_prefixCarrierMapEquiv
    (f : Lattice.Isometry q r L M) (k : Nat)
    (x : D.prefixCarrier k) :
    ((D.prefixCarrierMapEquiv f k x :
      (D.mapIsometry f).prefixCarrier k) : W) =
        f.toLinearEquiv (x : V) := by
  rfl

/-- The ambient integral prefix sum is transported exactly by an ambient
lattice isometry. -/
theorem prefixAmbientSubmodule_mapIsometry
    (f : Lattice.Isometry q r L M) (k : Nat) :
    (D.mapIsometry f).prefixAmbientSubmodule k =
      (D.prefixAmbientSubmodule k).map
        (f.toLinearEquiv.toLinearMap.restrictScalars (IntegerRing K)) := by
  unfold prefixAmbientSubmodule
  simp_rw [mapIsometry_component,
    QuadraticSublattice.ambientSubmodule_mapIsometry]
  rw [Submodule.map_iSup]

/-- Every integral isometry restricts to an integral isometry between the
corresponding prefix quadratic sublattices. -/
noncomputable def prefixLatticeIsometry
    (f : Lattice.Isometry q r L M) (k : Nat) :
    Lattice.Isometry
      (D.prefixQuadraticSublattice k).space
      ((D.mapIsometry f).prefixQuadraticSublattice k).space
      (D.prefixQuadraticSublattice k).lattice
      ((D.mapIsometry f).prefixQuadraticSublattice k).lattice where
  toLinearEquiv := D.prefixCarrierMapEquiv f k
  map_bilin := by
    intro x y
    exact f.map_bilin (x : V) (y : V)
  map_mem := by
    intro x
    change D.prefixCarrier k at x
    change x ∈ D.prefixLattice k ↔
      D.prefixCarrierMapEquiv f k x ∈
        (D.mapIsometry f).prefixLattice k
    rw [D.mem_prefixLattice_iff k,
      (D.mapIsometry f).mem_prefixLattice_iff k,
      D.prefixAmbientSubmodule_mapIsometry f k]
    change (x : V) ∈ D.prefixAmbientSubmodule k ↔
      f.toLinearEquiv (x : V) ∈
        (D.prefixAmbientSubmodule k).map
          (f.toLinearEquiv.toLinearMap.restrictScalars (IntegerRing K))
    simp

end Isometry

end OrthogonalDecomposition

end Lattice

end Bong
