/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.Jordan
import Mathlib.LinearAlgebra.DirectSum.Basis

/-!
# Duals of integral orthogonal decompositions

This file packages the componentwise dual and reverse reindexing used in
Beli (2003), Lemma 4.8.  The central integral statement is exposed as
`OrthogonalDecomposition.ReverseDualSum`: the embedded dual component
lattices sum to the integral dual of the parent lattice.  Once this equality
is supplied, `reverseDual` constructs the actual orthogonal decomposition of
the dual lattice.
-/

namespace Bong

open Dyadic
open Module
open scoped DirectSum

universe u v

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {q : QuadraticSpace K V} {L : Lattice K V} {t : Nat}

namespace Lattice

namespace QuadraticSublattice

/-- The integral dual of a quadratic sublattice, in the same nondegenerate
carrier. -/
noncomputable def dual (C : QuadraticSublattice q) :
    QuadraticSublattice q where
  carrier := C.carrier
  nondegenerate := C.nondegenerate
  lattice := dualLattice C.space C.lattice

@[simp]
theorem dual_carrier (C : QuadraticSublattice q) :
    C.dual.carrier = C.carrier :=
  rfl

@[simp]
theorem dual_space (C : QuadraticSublattice q) :
    C.dual.space = C.space :=
  rfl

@[simp]
theorem dual_lattice (C : QuadraticSublattice q) :
    C.dual.lattice = dualLattice C.space C.lattice :=
  rfl

@[simp]
theorem dual_dual_lattice (C : QuadraticSublattice q) :
    C.dual.dual.lattice = C.lattice := by
  exact dualLattice_dualLattice C.space C.lattice

/-- The ambient copy of a component lattice is the integral span of its
chosen ambient basis, followed by the carrier inclusion. -/
theorem ambientSubmodule_eq_span_ambientBasis
    (C : QuadraticSublattice q) :
    C.ambientSubmodule =
      Submodule.span (IntegerRing K)
        (Set.range fun i ↦ ((C.lattice.ambientBasis i : C.carrier) : V)) := by
  rw [ambientSubmodule, C.lattice.toSubmodule_eq_span_ambientBasis,
    Submodule.map_span]
  congr 1
  ext x
  constructor
  · rintro ⟨_, ⟨i, rfl⟩, rfl⟩
    exact ⟨i, rfl⟩
  · rintro ⟨i, rfl⟩
    exact ⟨C.lattice.ambientBasis i, ⟨i, rfl⟩, rfl⟩

/-- The ambient copy of the dual component lattice is generated by the
bilinear dual of the chosen component basis. -/
theorem dual_ambientSubmodule_eq_span_dualAmbientBasis
    (C : QuadraticSublattice q) :
    C.dual.ambientSubmodule =
      Submodule.span (IntegerRing K)
        (Set.range fun i ↦
          (((C.space.bilin.dualBasis C.nondegenerate
              C.lattice.ambientBasis) i : C.carrier) : V)) := by
  have hbasis : basisLattice C.lattice.ambientBasis = C.lattice := by
    apply Lattice.ext
    exact C.lattice.toSubmodule_eq_span_ambientBasis.symm
  have hdual : dualLattice C.space C.lattice =
      basisLattice (C.space.bilin.dualBasis C.nondegenerate
        C.lattice.ambientBasis) := by
    calc
      dualLattice C.space C.lattice =
          dualLattice C.space
            (basisLattice C.lattice.ambientBasis) :=
        congrArg (dualLattice C.space) hbasis.symm
      _ = basisLattice (C.space.bilin.dualBasis C.nondegenerate
          C.lattice.ambientBasis) :=
        dualLattice_basisLattice C.space C.lattice.ambientBasis
  rw [ambientSubmodule, dual_lattice, hdual]
  change
    (Submodule.span (IntegerRing K)
      (Set.range (C.space.bilin.dualBasis C.nondegenerate
        C.lattice.ambientBasis))).map
        ((Submodule.subtype C.carrier).restrictScalars (IntegerRing K)) = _
  rw [Submodule.map_span]
  congr 1
  ext x
  constructor
  · rintro ⟨_, ⟨i, rfl⟩, rfl⟩
    exact ⟨i, rfl⟩
  · rintro ⟨i, rfl⟩
    exact ⟨(C.space.bilin.dualBasis C.nondegenerate
      C.lattice.ambientBasis) i, ⟨i, rfl⟩, rfl⟩

end QuadraticSublattice

namespace OrthogonalDecomposition

variable (D : OrthogonalDecomposition q L t)

/-- A vector in the sum of all components other than `i` is orthogonal to
the `i`th carrier. -/
private theorem bilin_eq_zero_of_mem_iSup_ne
    (i : Fin t) {x : V}
    (hx : x ∈ ⨆ j, ⨆ (_ : j ≠ i), (D.component j).carrier)
    (y : (D.component i).carrier) :
    q.bilin x (y : V) = 0 := by
  induction hx using Submodule.iSup_induction' with
  | mem j z hz =>
      induction hz using Submodule.iSup_induction' with
      | mem hji z hz =>
          exact D.orthogonal j i hji ⟨z, hz⟩ y
      | zero => simp
      | add z w _ _ hz hw =>
          rw [LinearMap.BilinForm.add_left, hz, hw, add_zero]
  | zero => simp
  | add z w _ _ hz hw =>
      rw [LinearMap.BilinForm.add_left, hz, hw, add_zero]

/-- The carrier subspaces of an orthogonal decomposition are linearly
independent.  Nondegeneracy of each restricted form rules out an intersection
with the sum of the other mutually orthogonal carriers. -/
theorem carrier_iSupIndep :
    iSupIndep (fun i ↦ (D.component i).carrier) := by
  rw [iSupIndep_def]
  intro i
  rw [Submodule.disjoint_def]
  intro x hxi hxother
  have hpair : ∀ y : (D.component i).carrier,
      q.bilin x (y : V) = 0 :=
    fun y ↦ D.bilin_eq_zero_of_mem_iSup_ne i hxother y
  let xi : (D.component i).carrier := ⟨x, hxi⟩
  have hxiZero : xi = 0 :=
    (D.component i).nondegenerate.1 xi (by
      intro y
      exact hpair y)
  exact congrArg Subtype.val hxiZero

/-- The carrier subspaces of an integral orthogonal decomposition span the
whole ambient vector space over the field. -/
theorem carrier_iSup_eq_top :
    (⨆ i, (D.component i).carrier) = ⊤ := by
  apply top_unique
  rw [← L.span_eq_top, Submodule.span_le]
  intro x hx
  rw [← D.sum_eq] at hx
  induction hx using Submodule.iSup_induction' with
  | mem i z hz =>
      rcases hz with ⟨y, hy, rfl⟩
      exact le_iSup (fun j ↦ (D.component j).carrier) i y.property
  | zero => exact Submodule.zero_mem _
  | add x y _ _ hx hy => exact Submodule.add_mem _ hx hy

/-- The canonical linear equivalence from the direct sum of component
carriers to the ambient vector space. -/
noncomputable def carrierDirectSumEquiv :
    (⨁ i : Fin t, (D.component i).carrier) ≃ₗ[K] V :=
  D.carrier_iSupIndep.linearEquiv D.carrier_iSup_eq_top

/-- Concatenation of the chosen component lattice bases, regarded as a field
basis of the ambient space. -/
noncomputable def componentAmbientBasis :
    Basis (Σ i : Fin t, (D.component i).lattice.BasisIndex) K V :=
  (DFinsupp.basis fun i ↦ (D.component i).lattice.ambientBasis).map
    D.carrierDirectSumEquiv

@[simp]
theorem componentAmbientBasis_apply
    (a : Σ i : Fin t, (D.component i).lattice.BasisIndex) :
    D.componentAmbientBasis a =
      ((D.component a.1).lattice.ambientBasis a.2 :
        (D.component a.1).carrier) := by
  classical
  rw [componentAmbientBasis, Basis.map_apply, carrierDirectSumEquiv,
    iSupIndep.linearEquiv_apply]
  simp [DFinsupp.basis]

/-- Concatenating the chosen integral component bases recovers the original
parent lattice exactly. -/
theorem basisLattice_componentAmbientBasis :
    basisLattice D.componentAmbientBasis = L := by
  apply Lattice.ext
  change Submodule.span (IntegerRing K) (Set.range D.componentAmbientBasis) =
    L.toSubmodule
  rw [← D.sum_eq]
  apply le_antisymm
  · rw [Submodule.span_le]
    rintro _ ⟨a, rfl⟩
    rw [D.componentAmbientBasis_apply]
    apply (le_iSup (fun i ↦ (D.component i).ambientSubmodule) a.1)
    rw [(D.component a.1).ambientSubmodule_eq_span_ambientBasis]
    exact Submodule.subset_span ⟨a.2, rfl⟩
  · apply iSup_le
    intro i
    rw [(D.component i).ambientSubmodule_eq_span_ambientBasis,
      Submodule.span_le]
    rintro _ ⟨j, rfl⟩
    apply Submodule.subset_span
    exact ⟨⟨i, j⟩, by simp⟩

/-- The componentwise bilinear-dual basis vectors, embedded in the ambient
space and indexed in the same dependent sum as `componentAmbientBasis`. -/
noncomputable def componentDualAmbientVector
    (a : Σ i : Fin t, (D.component i).lattice.BasisIndex) : V :=
  (((D.component a.1).space.bilin.dualBasis
      (D.component a.1).nondegenerate
      (D.component a.1).lattice.ambientBasis) a.2 :
    (D.component a.1).carrier)

/-- Componentwise dual basis vectors have the global Kronecker pairing with
the concatenated component basis. -/
theorem bilin_componentDualAmbientVector_componentAmbientBasis
    (a b : Σ i : Fin t, (D.component i).lattice.BasisIndex) :
    q.bilin (D.componentDualAmbientVector a)
        (D.componentAmbientBasis b) =
      if b = a then 1 else 0 := by
  rcases a with ⟨i, ai⟩
  rcases b with ⟨j, bj⟩
  simp only [componentDualAmbientVector, componentAmbientBasis_apply]
  by_cases hij : i = j
  · subst j
    change (D.component i).space.bilin
        (((D.component i).space.bilin.dualBasis
          (D.component i).nondegenerate
          (D.component i).lattice.ambientBasis) ai)
        ((D.component i).lattice.ambientBasis bj) = _
    rw [LinearMap.BilinForm.apply_dualBasis_left]
    simp
  · have hsigma :
        (⟨j, bj⟩ : Σ k : Fin t,
          (D.component k).lattice.BasisIndex) ≠ ⟨i, ai⟩ := by
      intro h
      exact hij (congrArg Sigma.fst h).symm
    rw [if_neg hsigma]
    exact D.orthogonal i j hij _ _

/-- The bilinear dual of the concatenated global basis is obtained by
concatenating the embedded component dual bases. -/
theorem dualBasis_componentAmbientBasis :
    q.bilin.dualBasis q.nondegenerate D.componentAmbientBasis =
      D.componentDualAmbientVector := by
  apply (q.bilin.dualBasis_eq_iff q.nondegenerate
    D.componentAmbientBasis D.componentDualAmbientVector).2
  intro i j
  exact D.bilin_componentDualAmbientVector_componentAmbientBasis i j

/-- The dual of the component at the reversed index. -/
noncomputable def reverseDualComponent (i : Fin t) :
    QuadraticSublattice q :=
  (D.component (Fin.rev i)).dual

@[simp]
theorem reverseDualComponent_carrier (i : Fin t) :
    (D.reverseDualComponent i).carrier =
      (D.component (Fin.rev i)).carrier :=
  rfl

@[simp]
theorem reverseDualComponent_space (i : Fin t) :
    (D.reverseDualComponent i).space =
      (D.component (Fin.rev i)).space :=
  rfl

@[simp]
theorem reverseDualComponent_lattice (i : Fin t) :
    (D.reverseDualComponent i).lattice =
      dualLattice (D.component (Fin.rev i)).space
        (D.component (Fin.rev i)).lattice :=
  rfl

/-- The exact integral identity needed to dualize an orthogonal
decomposition. -/
def ReverseDualSum : Prop :=
  (⨆ i, (D.reverseDualComponent i).ambientSubmodule) =
    (dualLattice q L).toSubmodule

/-- Integral duality commutes with a finite orthogonal decomposition.  The
proof concatenates component integral bases and computes their bilinear dual
basis componentwise. -/
theorem reverseDualSum : D.ReverseDualSum := by
  have hdualLattice : dualLattice q L =
      basisLattice
        (q.bilin.dualBasis q.nondegenerate D.componentAmbientBasis) := by
    calc
      dualLattice q L =
          dualLattice q (basisLattice D.componentAmbientBasis) :=
        congrArg (dualLattice q)
          D.basisLattice_componentAmbientBasis.symm
      _ = basisLattice
          (q.bilin.dualBasis q.nondegenerate
            D.componentAmbientBasis) :=
        dualLattice_basisLattice q D.componentAmbientBasis
  have hdualSubmodule : (dualLattice q L).toSubmodule =
      Submodule.span (IntegerRing K)
        (Set.range D.componentDualAmbientVector) := by
    rw [hdualLattice]
    change Submodule.span (IntegerRing K)
        (Set.range (q.bilin.dualBasis q.nondegenerate
          D.componentAmbientBasis)) = _
    rw [D.dualBasis_componentAmbientBasis]
  change (⨆ i, (D.reverseDualComponent i).ambientSubmodule) =
    (dualLattice q L).toSubmodule
  rw [hdualSubmodule]
  apply le_antisymm
  · apply iSup_le
    intro i
    change (D.component (Fin.rev i)).dual.ambientSubmodule ≤ _
    rw [(D.component (Fin.rev i)).dual_ambientSubmodule_eq_span_dualAmbientBasis,
      Submodule.span_le]
    rintro _ ⟨j, rfl⟩
    apply Submodule.subset_span
    exact ⟨⟨Fin.rev i, j⟩, rfl⟩
  · rw [Submodule.span_le]
    rintro _ ⟨a, rfl⟩
    apply (le_iSup
      (fun i ↦ (D.reverseDualComponent i).ambientSubmodule)
      (Fin.rev a.1))
    change D.componentDualAmbientVector a ∈
      (D.component (Fin.rev (Fin.rev a.1))).dual.ambientSubmodule
    simp only [Fin.rev_rev]
    rw [(D.component a.1).dual_ambientSubmodule_eq_span_dualAmbientBasis]
    exact Submodule.subset_span ⟨a.2, rfl⟩

/-- Reversing the componentwise duals gives an orthogonal decomposition of
the parent dual lattice. -/
noncomputable def reverseDual :
    OrthogonalDecomposition q (dualLattice q L) t where
  component := D.reverseDualComponent
  orthogonal := by
    intro i j hij x y
    exact D.orthogonal (Fin.rev i) (Fin.rev j)
      (fun h ↦ hij (Fin.rev_injective h)) x y
  sum_eq := D.reverseDualSum

@[simp]
theorem reverseDual_component (i : Fin t) :
    D.reverseDual.component i = D.reverseDualComponent i :=
  rfl

/-- Reverse duality preserves each component rank, up to the reversed
indexing. -/
theorem reverseDual_componentRank (i : Fin t) :
    finrank K (D.reverseDual.component i).carrier =
      finrank K (D.component (Fin.rev i)).carrier :=
  rfl

end OrthogonalDecomposition

end Lattice

end Bong
