/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.NormGeneratorValues

/-!
# Powers of the maximal ideal

The chosen uniformizer in `DyadicContext` lets us represent Beli's fractional
ideal `𝔭ʳ` for every integer `r`.  Its membership and inclusion laws are stated
purely in terms of the normalized additive valuation.
-/

namespace Bong

open Dyadic

universe u

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]

namespace Dyadic

/-- The selected uniformizer raised to an arbitrary integral power. -/
noncomputable def uniformizerPowerUnit (K : Type u) [Field K] [CharZero K]
    [ValuativeRel K] [TopologicalSpace K] [DyadicContext K]
    (r : Int) : Kˣ :=
  uniformizerUnit K ^ r

@[simp]
theorem coe_uniformizerPowerUnit (r : Int) :
    (uniformizerPowerUnit K r : K) =
      ((uniformizerUnit K ^ r : Kˣ) : K) :=
  rfl

private theorem int_smul_one_withTop (r : Int) :
    r • (1 : WithTop Int) = (r : WithTop Int) := by
  cases r with
  | ofNat n => simp
  | negSucc n =>
      rw [Int.negSucc_eq, neg_zsmul]
      have hcast : (n : Int) + 1 = ((n + 1 : Nat) : Int) := by omega
      rw [hcast, natCast_zsmul]
      simp

@[simp]
theorem ordUnit_uniformizerPowerUnit (r : Int) :
    ordUnit K (uniformizerPowerUnit K r) = r := by
  apply WithTop.coe_injective
  rw [coe_ordUnit, uniformizerPowerUnit,
    ord_coe_unit_zpow, coe_uniformizerUnit, ord_uniformizer,
    int_smul_one_withTop]

end Dyadic

namespace Lattice

/-- Beli's fractional ideal `𝔭ʳ`, generated by the selected uniformizer to
the integral power `r`. -/
noncomputable def powerIdeal (r : Int) : CoefficientIdeal (K := K) :=
  principalIdeal (K := K) (Dyadic.uniformizerPowerUnit K r : K)

/-- Membership in `𝔭ʳ` is exactly the lower valuation bound `r ≤ ord(a)`. -/
theorem mem_powerIdeal_iff (r : Int) (a : K) :
    a ∈ powerIdeal (K := K) r ↔
      (r : WithTop Int) ≤ ord K a := by
  have hgenerator :
      ord K (Dyadic.uniformizerPowerUnit K r : K) =
        (r : WithTop Int) := by
    rw [← coe_ordUnit,
      Dyadic.ordUnit_uniformizerPowerUnit]
  constructor
  · intro ha
    have h := ord_le_of_mem_principalIdeal
      (Units.ne_zero (Dyadic.uniformizerPowerUnit K r)) ha
    rwa [hgenerator] at h
  · intro ha
    apply mem_principalIdeal_of_ord_le
      (Units.ne_zero (Dyadic.uniformizerPowerUnit K r))
    rwa [hgenerator]

/-- Fractional power ideals are ordered in the reverse direction of their
exponents. -/
theorem powerIdeal_le_iff (r s : Int) :
    powerIdeal (K := K) r ≤ powerIdeal (K := K) s ↔ s ≤ r := by
  constructor
  · intro hrs
    have hmem :
        (Dyadic.uniformizerPowerUnit K r : K) ∈
          powerIdeal (K := K) s :=
      hrs (generator_mem_principalIdeal _)
    rw [mem_powerIdeal_iff] at hmem
    have hr :
        ord K (Dyadic.uniformizerPowerUnit K r : K) =
          (r : WithTop Int) := by
      rw [← coe_ordUnit,
        Dyadic.ordUnit_uniformizerPowerUnit]
    rw [hr] at hmem
    exact WithTop.coe_le_coe.mp hmem
  · intro hsr
    intro a ha
    rw [mem_powerIdeal_iff] at ha ⊢
    have hcast : (s : WithTop Int) ≤ (r : WithTop Int) := by
      exact_mod_cast hsr
    exact hcast.trans ha

/-- Strict inclusion of fractional power ideals reverses strict comparison
of their integral exponents. -/
theorem powerIdeal_lt_iff (r s : Int) :
    powerIdeal (K := K) r < powerIdeal (K := K) s ↔ s < r := by
  rw [lt_iff_le_not_ge, powerIdeal_le_iff,
    powerIdeal_le_iff, lt_iff_le_not_ge]

/-- Every nonzero principal ideal is the power ideal determined by the
valuation of its generator. -/
theorem principalIdeal_eq_powerIdeal (a : Kˣ) :
    principalIdeal (K := K) (a : K) =
      powerIdeal (K := K) (ordUnit K a) := by
  have hpower :
      ord K (Dyadic.uniformizerPowerUnit K (ordUnit K a) : K) =
        ord K (a : K) := by
    rw [← coe_ordUnit,
      Dyadic.ordUnit_uniformizerPowerUnit, coe_ordUnit]
  apply le_antisymm
  · apply (principalIdeal_le_iff_ord_ge
      (Units.ne_zero a)
      (Units.ne_zero
        (Dyadic.uniformizerPowerUnit K (ordUnit K a)))).2
    exact hpower.le
  · apply (principalIdeal_le_iff_ord_ge
      (Units.ne_zero
        (Dyadic.uniformizerPowerUnit K (ordUnit K a)))
      (Units.ne_zero a)).2
    exact hpower.ge

/-- Membership in an ideal properly below a nonzero principal ideal forces
strictly larger valuation than the principal generator. -/
theorem ordUnit_lt_ord_of_mem_of_lt_principalIdeal
    (a : Kˣ) (I : CoefficientIdeal (K := K)) {z : K}
    (hz : z ∈ I) (hI : I < principalIdeal (K := K) (a : K)) :
    (ordUnit K a : WithTop Int) < ord K z := by
  have hlower : (ordUnit K a : WithTop Int) ≤ ord K z := by
    rw [coe_ordUnit]
    exact ord_le_of_mem_principalIdeal (Units.ne_zero a) (hI.le hz)
  by_contra hnot
  have hupper : ord K z ≤ (ordUnit K a : WithTop Int) :=
    le_of_not_gt hnot
  have hzNe : z ≠ 0 := by
    intro hzZero
    subst z
    simp at hupper
  have hprincipal : principalIdeal (K := K) (a : K) ≤
      principalIdeal (K := K) z := by
    apply (principalIdeal_le_iff_ord_ge (Units.ne_zero a) hzNe).2
    rw [← coe_ordUnit]
    exact hupper
  have hzIdeal : principalIdeal (K := K) z ≤ I := by
    rw [principalIdeal, Submodule.span_singleton_le_iff_mem]
    exact hz
  exact hI.2 (hprincipal.trans hzIdeal)

/-- Discreteness of the integral value group: being strictly above an
integer order is equivalent to being at least its successor. -/
theorem coe_int_add_one_le_of_lt {r : Int} {s : WithTop Int}
    (h : (r : WithTop Int) < s) : ((r + 1 : Int) : WithTop Int) ≤ s := by
  by_cases hs : s = ⊤
  · simp [hs]
  · rcases WithTop.ne_top_iff_exists.mp hs with ⟨t, rfl⟩
    apply WithTop.coe_le_coe.mpr
    have hrt : r < t := WithTop.coe_lt_coe.mp h
    omega

/-- The supremum of a nonempty finite family of fractional power ideals is
the power ideal whose exponent is the minimum of the family. -/
theorem iSup_powerIdeal_fin_eq_inf' {t : Nat} (e : Fin t → Int)
    (anchor : Fin t) :
    (⨆ i, powerIdeal (K := K) (e i)) =
      powerIdeal (K := K)
        (Finset.univ.inf' ⟨anchor, Finset.mem_univ anchor⟩ e) := by
  let hnon : (Finset.univ : Finset (Fin t)).Nonempty :=
    ⟨anchor, Finset.mem_univ anchor⟩
  apply le_antisymm
  · apply iSup_le
    intro i
    apply (powerIdeal_le_iff _ _).2
    exact Finset.inf'_le e (Finset.mem_univ i)
  · obtain ⟨i, hi, hmin⟩ :=
      Finset.exists_mem_eq_inf' (s := Finset.univ) hnon e
    have hmin' :
        Finset.univ.inf' ⟨anchor, Finset.mem_univ anchor⟩ e = e i := by
      simpa only using hmin
    rw [hmin']
    exact le_iSup (fun j ↦ powerIdeal (K := K) (e j)) i

end Lattice

end Bong
