/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.ScaledHyperbolicMaximal
import Bong.Lattice.BasisIsometry
import Bong.Lattice.DualIsometry
import Bong.Lattice.DeterminantBasis
import Bong.Lattice.MixedPairing
import Bong.Lattice.ProjectionScaling
import Bong.Lattice.HyperbolicDiagonal
import Bong.Bong.Beli2019Lemma718HyperbolicBlock

/-!
# Norm maximality of scaled hyperbolic plane lattices

This file proves the O'Meara maximality input isolated in
`ScaledHyperbolicMaximalLaws`.  The proof is the elementary rank-two
valuation argument.  If `b₀,b₁` is an integral basis of a lattice whose norm
is contained in that of the standard hyperbolic lattice, choose a basis
vector whose first coordinate has least valuation.  A determinant-free
hyperbolic diagonal isometry then makes both coordinates of both basis
vectors integral.  The first coordinates are integral by the choice of the
minimum; the second coordinates follow from the two diagonal norm values and
the mixed value obtained from `Q(b₀+b₁)`.
-/

namespace Bong

open Dyadic Module

namespace Lattice

universe u v w

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]

/-- Membership in the standard hyperbolic lattice is coordinatewise
integrality. -/
theorem mem_hyperbolicPlaneLattice_iff (x : Fin 2 → K) :
    x ∈ hyperbolicPlaneLattice (K := K) ↔
      x 0 ∈ IntegerRing K ∧ x 1 ∈ IntegerRing K := by
  rw [hyperbolicPlaneLattice,
    mem_basisLattice_iff_repr_mem_integerRing]
  constructor
  · intro h
    exact ⟨by simpa using h 0, by simpa using h 1⟩
  · rintro ⟨h0, h1⟩ i
    fin_cases i <;> simpa

/-- The norm ideal of the standard lattice in `H_s` is generated by `2s`.
This is the normalization used in Beli (2019), Lemma 9.7(ii). -/
theorem normIdeal_hyperbolicPlaneLattice (s : Kˣ) :
    normIdeal (QuadraticSpace.hyperbolicPlane s)
        (hyperbolicPlaneLattice (K := K)) =
      principalIdeal (K := K) (2 * (s : K)) := by
  apply le_antisymm
  · apply normIdeal_le_of_quadratic_mem
    intro x hx
    rw [QuadraticSpace.hyperbolicPlane_quadratic_apply]
    apply mul_mem_principalIdeal_of_mem_integerRing
    exact (IntegerRing K).toSubring.mul_mem
      ((mem_hyperbolicPlaneLattice_iff x).mp hx).1
      ((mem_hyperbolicPlaneLattice_iff x).mp hx).2
  · rw [principalIdeal, Submodule.span_le, Set.singleton_subset_iff]
    let e0 : Fin 2 → K := Pi.single 0 1
    let e1 : Fin 2 → K := Pi.single 1 1
    have he0 : e0 ∈ hyperbolicPlaneLattice (K := K) := by
      rw [mem_hyperbolicPlaneLattice_iff]
      simp [e0]
    have he1 : e1 ∈ hyperbolicPlaneLattice (K := K) := by
      rw [mem_hyperbolicPlaneLattice_iff]
      simp [e1]
    have hvalue := quadratic_mem_normIdeal_of_mem
      (QuadraticSpace.hyperbolicPlane s)
      (hyperbolicPlaneLattice (K := K))
      ((hyperbolicPlaneLattice (K := K)).add_mem he0 he1)
    rw [QuadraticSpace.hyperbolicPlane_quadratic_apply] at hvalue
    simpa [e0, e1] using hvalue

/-- A basis of a binary space has a vector with nonzero first coordinate. -/
theorem basis_exists_apply_zero_ne_zero
    (b : Basis (Fin 2) K (Fin 2 → K)) :
    ∃ i : Fin 2, b i 0 ≠ 0 := by
  by_contra h
  push_neg at h
  let e0 : Fin 2 → K := Pi.single 0 1
  have hsum := b.sum_repr e0
  have hcoord := congrArg (fun x : Fin 2 → K ↦ x 0) hsum
  have hleft : (∑ i, (b.repr e0 i) • b i) 0 = 0 := by
    simp only [Finset.sum_apply, Pi.smul_apply, smul_eq_mul, h, mul_zero,
      Finset.sum_const_zero]
  rw [hleft] at hcoord
  simpa [e0] using hcoord

/-- In a binary basis one may choose a nonzero first coordinate of least
valuation. -/
theorem basis_exists_minimal_first_coordinate
    (b : Basis (Fin 2) K (Fin 2 → K)) :
    ∃ k : Fin 2, b k 0 ≠ 0 ∧
      ∀ i : Fin 2, ord K (b k 0) ≤ ord K (b i 0) := by
  by_cases h0 : b 0 0 = 0
  · have h1 : b 1 0 ≠ 0 := by
      rcases basis_exists_apply_zero_ne_zero b with ⟨i, hi⟩
      fin_cases i
      · exact (hi h0).elim
      · exact hi
    refine ⟨1, h1, ?_⟩
    intro i
    fin_cases i
    · simp [h0]
    · exact le_rfl
  · by_cases hle : ord K (b 0 0) ≤ ord K (b 1 0)
    · refine ⟨0, h0, ?_⟩
      intro i
      fin_cases i
      · exact le_rfl
      · exact hle
    · have h1 : b 1 0 ≠ 0 := by
        intro hz
        apply hle
        simp [hz]
      refine ⟨1, h1, ?_⟩
      intro i
      fin_cases i
      · exact le_of_not_ge hle
      · exact le_rfl

/-- Multiplication by the inverse valuation power of a least-order anchor
makes every element of greater order integral. -/
theorem uniformizerPower_neg_ordUnit_mul_mem_integerRing
    (a : Kˣ) {x : K}
    (h : ord K (a : K) ≤ ord K x) :
    (uniformizerPowerUnit K (-ordUnit K a) : K) * x ∈ IntegerRing K := by
  rw [mem_integerRing_iff, Dyadic.IsIntegral]
  by_cases hx : x = 0
  · simp [hx]
  · let xu : Kˣ := Units.mk0 x hx
    have hfinite : ordUnit K a ≤ ordUnit K xu := by
      apply WithTop.coe_le_coe.mp
      simpa [xu] using h
    rw [ord_mul, ← coe_ordUnit]
    change (0 : WithTop Int) ≤
      ((ordUnit K (uniformizerPowerUnit K (-ordUnit K a)) : Int) :
          WithTop Int) + ord K x
    rw [ordUnit_uniformizerPowerUnit, show ord K x =
        ((ordUnit K xu : Int) : WithTop Int) by simpa [xu] using
          (coe_ordUnit K xu).symm]
    exact_mod_cast (show 0 ≤ -ordUnit K a + ordUnit K xu by omega)

/-- The normalized anchor has valuation zero. -/
theorem normalized_anchor_isValuationUnit (a : Kˣ) :
    IsValuationUnit K
      ((uniformizerPowerUnit K (-ordUnit K a) * a : Kˣ) : K) := by
  apply (isValuationUnit_iff_ordUnit_eq_zero K _).2
  rw [ordUnit_mul, ordUnit_uniformizerPowerUnit]
  omega

/-- Norm containment in the standard hyperbolic lattice says that the
product of the two coordinates of every lattice vector is integral. -/
theorem coordinate_product_mem_integerRing_of_normIdeal_le
    (s : Kˣ) (M : Lattice K (Fin 2 → K))
    (hnorm : normIdeal (QuadraticSpace.hyperbolicPlane s) M ≤
      normIdeal (QuadraticSpace.hyperbolicPlane s)
        (hyperbolicPlaneLattice (K := K)))
    {x : Fin 2 → K} (hx : x ∈ M) :
    x 0 * x 1 ∈ IntegerRing K := by
  have hvalue := hnorm (quadratic_mem_normIdeal_of_mem
    (QuadraticSpace.hyperbolicPlane s) M hx)
  rw [normIdeal_hyperbolicPlaneLattice,
    QuadraticSpace.hyperbolicPlane_quadratic_apply] at hvalue
  exact mem_integerRing_of_mul_mem_principalIdeal
    (mul_ne_zero (by norm_num) (Units.ne_zero s)) hvalue

/-- Polarizing the norm containment gives integrality of the mixed
coordinate sum. -/
theorem mixed_coordinate_sum_mem_integerRing_of_normIdeal_le
    (s : Kˣ) (M : Lattice K (Fin 2 → K))
    (hnorm : normIdeal (QuadraticSpace.hyperbolicPlane s) M ≤
      normIdeal (QuadraticSpace.hyperbolicPlane s)
        (hyperbolicPlaneLattice (K := K)))
    {x y : Fin 2 → K} (hx : x ∈ M) (hy : y ∈ M) :
    x 0 * y 1 + y 0 * x 1 ∈ IntegerRing K := by
  have hsum := coordinate_product_mem_integerRing_of_normIdeal_le
    s M hnorm (M.add_mem hx hy)
  have hxprod := coordinate_product_mem_integerRing_of_normIdeal_le
    s M hnorm hx
  have hyprod := coordinate_product_mem_integerRing_of_normIdeal_le
    s M hnorm hy
  have hdiff := (IntegerRing K).toSubring.sub_mem
    ((IntegerRing K).toSubring.sub_mem hsum hxprod) hyprod
  have heq :
      x 0 * y 1 + y 0 * x 1 =
        (x + y) 0 * (x + y) 1 - x 0 * x 1 - y 0 * y 1 := by
    simp only [Pi.add_apply]
    ring
  rw [heq]
  exact hdiff

/-- The inverse of a valuation unit belongs to the valuation ring. -/
theorem inv_mem_integerRing_of_isValuationUnit (a : Kˣ)
    (ha : IsValuationUnit K (a : K)) :
    ((a⁻¹ : Kˣ) : K) ∈ IntegerRing K := by
  rw [mem_integerRing_iff, Dyadic.IsIntegral, Units.val_inv_eq_inv_val,
    AddValuation.map_inv, ha]
  simp

/-- In the same hyperbolic ambient space, the standard lattice represents
every lattice with contained norm ideal. -/
theorem hyperbolicPlaneLattice_represents_of_normIdeal_le
    (s : Kˣ) (M : Lattice K (Fin 2 → K))
    (hnorm : normIdeal (QuadraticSpace.hyperbolicPlane s) M ≤
      normIdeal (QuadraticSpace.hyperbolicPlane s)
        (hyperbolicPlaneLattice (K := K))) :
    Represents (QuadraticSpace.hyperbolicPlane s)
      (QuadraticSpace.hyperbolicPlane s)
      (hyperbolicPlaneLattice (K := K)) M := by
  let e : Fin 2 ≃ Fin (finrank K (Fin 2 → K)) := finCongr (by simp)
  let b : Basis (Fin 2) K (Fin 2 → K) :=
    M.standardAmbientBasis.reindex e.symm
  have hbasis : basisLattice b = M := by
    calc
      basisLattice b = basisLattice M.standardAmbientBasis :=
        basisLattice_reindex M.standardAmbientBasis e.symm
      _ = M := basisLattice_standardAmbientBasis M
  have hbmem (i : Fin 2) : b i ∈ M := by
    rw [← hbasis]
    exact Submodule.subset_span ⟨i, rfl⟩
  rcases basis_exists_minimal_first_coordinate b with ⟨k, hkne, hkmin⟩
  let a : Kˣ := Units.mk0 (b k 0) hkne
  let t : Kˣ := uniformizerPowerUnit K (-ordUnit K a)
  let u : Kˣ := t * a
  have hu : IsValuationUnit K (u : K) := by
    simpa [u, t] using normalized_anchor_isValuationUnit a
  have huInvMem : ((u⁻¹ : Kˣ) : K) ∈ IntegerRing K :=
    inv_mem_integerRing_of_isValuationUnit u hu
  have hfirst (i : Fin 2) : (t : K) * b i 0 ∈ IntegerRing K := by
    apply uniformizerPower_neg_ordUnit_mul_mem_integerRing a
    simpa [a] using hkmin i
  have hdiagAnchor : b k 0 * b k 1 ∈ IntegerRing K :=
    coordinate_product_mem_integerRing_of_normIdeal_le
      s M hnorm (hbmem k)
  have hsecondAnchor : ((t⁻¹ : Kˣ) : K) * b k 1 ∈ IntegerRing K := by
    have hmul := (IntegerRing K).toSubring.mul_mem huInvMem hdiagAnchor
    change ((t⁻¹ : Kˣ) : K) * b k 1 ∈ (IntegerRing K).toSubring
    have heq :
        ((t⁻¹ : Kˣ) : K) * b k 1 =
          ((u⁻¹ : Kˣ) : K) * (b k 0 * b k 1) := by
      dsimp [u, a]
      simp only [Units.val_mul, Units.val_inv_eq_inv_val,
        Units.val_mk0]
      field_simp [hkne, Units.ne_zero t]
    rw [heq]
    exact hmul
  have hsecond (i : Fin 2) :
      ((t⁻¹ : Kˣ) : K) * b i 1 ∈ IntegerRing K := by
    have hother : b i 0 * b k 1 ∈ IntegerRing K := by
      have hmul := (IntegerRing K).toSubring.mul_mem (hfirst i) hsecondAnchor
      change b i 0 * b k 1 ∈ (IntegerRing K).toSubring
      have heq :
          b i 0 * b k 1 =
            ((t : K) * b i 0) * (((t⁻¹ : Kˣ) : K) * b k 1) := by
        simp only [Units.val_inv_eq_inv_val]
        field_simp [Units.ne_zero t]
      rw [heq]
      exact hmul
    have hmixed : b k 0 * b i 1 + b i 0 * b k 1 ∈ IntegerRing K :=
      mixed_coordinate_sum_mem_integerRing_of_normIdeal_le
        s M hnorm (hbmem k) (hbmem i)
    have hanchorProduct : b k 0 * b i 1 ∈ IntegerRing K := by
      have hsub := (IntegerRing K).toSubring.sub_mem hmixed hother
      change b k 0 * b i 1 ∈ (IntegerRing K).toSubring
      simpa only [add_sub_cancel_right] using hsub
    have hmul := (IntegerRing K).toSubring.mul_mem huInvMem hanchorProduct
    change ((t⁻¹ : Kˣ) : K) * b i 1 ∈ (IntegerRing K).toSubring
    have heq :
        ((t⁻¹ : Kˣ) : K) * b i 1 =
          ((u⁻¹ : Kˣ) : K) * (b k 0 * b i 1) := by
      dsimp [u, a]
      simp only [Units.val_mul, Units.val_inv_eq_inv_val,
        Units.val_mk0]
      field_simp [hkne, Units.ne_zero t]
    rw [heq]
    exact hmul
  let d := hyperbolicDiagonalIsometry s t
  have hbmap (i : Fin 2) : d.toLinearEquiv (b i) ∈
      hyperbolicPlaneLattice (K := K) := by
    rw [mem_hyperbolicPlaneLattice_iff]
    exact ⟨hfirst i, hsecond i⟩
  refine ⟨{
    toLinearMap := d.toLinearEquiv
    injective := d.toLinearEquiv.injective
    map_bilin := d.map_bilin
    map_mem := ?_
  }⟩
  intro x hx
  have hx' : x ∈ basisLattice b := by
    rwa [hbasis]
  change x ∈ Submodule.span (IntegerRing K) (Set.range b) at hx'
  refine Submodule.span_induction
    (p := fun y _ ↦ d.toLinearEquiv y ∈
      hyperbolicPlaneLattice (K := K)) ?_ ?_ ?_ ?_ hx'
  · rintro _ ⟨i, rfl⟩
    exact hbmap i
  · simpa using (hyperbolicPlaneLattice (K := K)).zero_mem
  · intro y z _ _ hy hz
    simpa only [map_add] using
      (hyperbolicPlaneLattice (K := K)).add_mem hy hz
  · intro c y _ hy
    have hsmul := (hyperbolicPlaneLattice (K := K)).smul_mem c hy
    change (c : K) • d.toLinearEquiv y ∈
      hyperbolicPlaneLattice (K := K) at hsmul
    change d.toLinearEquiv ((c : K) • y) ∈
      hyperbolicPlaneLattice (K := K)
    simpa only [map_smul] using hsmul

/-- The standard lattice is norm-maximal in a scaled hyperbolic plane. -/
theorem hyperbolicPlaneLattice_isNormMaximal (s : Kˣ) :
    IsNormMaximal.{u, u, w} (QuadraticSpace.hyperbolicPlane s)
      (hyperbolicPlaneLattice (K := K)) := by
  intro W _ _ r M ambient hnorm
  rcases ambient with ⟨f⟩
  let M' : Lattice K (Fin 2 → K) :=
    map f.toLinearEquiv.symm M
  have hnorm' :
      normIdeal (QuadraticSpace.hyperbolicPlane s) M' ≤
        normIdeal (QuadraticSpace.hyperbolicPlane s)
          (hyperbolicPlaneLattice (K := K)) := by
    have hmap := normIdeal_map_isometry f.symm M
    change normIdeal (QuadraticSpace.hyperbolicPlane s) M' =
      normIdeal r M at hmap
    rw [hmap]
    exact hnorm
  have hstandard :=
    hyperbolicPlaneLattice_represents_of_normIdeal_le s M' hnorm'
  have htransport :
      Represents (QuadraticSpace.hyperbolicPlane s) r M' M := by
    exact ⟨(Bong.Lattice.Isometry.toMap r f.symm M).toRepresentation⟩
  exact hstandard.trans htransport

/-- Multiplication of both coordinates by one field unit. -/
noncomputable def hyperbolicGlobalScaleLinearEquiv (s : Kˣ) :
    (Fin 2 → K) ≃ₗ[K] (Fin 2 → K) where
  toFun x := (s : K) • x
  invFun x := ((s⁻¹ : Kˣ) : K) • x
  left_inv x := by
    simp [smul_smul, Units.ne_zero]
  right_inv x := by
    simp [smul_smul, Units.ne_zero]
  map_add' x y := by simp [smul_add]
  map_smul' c x := by simp [smul_smul, mul_comm]

@[simp]
theorem hyperbolicGlobalScaleLinearEquiv_apply
    (s : Kˣ) (x : Fin 2 → K) (i : Fin 2) :
    hyperbolicGlobalScaleLinearEquiv s x i = (s : K) * x i :=
  rfl

/-- Global scaling by `s` identifies `H_s` with `H_(s⁻¹)`. -/
noncomputable def hyperbolicGlobalScaleIsometry (s : Kˣ) :
    QuadraticSpace.Isometry
      (QuadraticSpace.hyperbolicPlane s)
      (QuadraticSpace.hyperbolicPlane s⁻¹) where
  toLinearEquiv := hyperbolicGlobalScaleLinearEquiv s
  map_bilin x y := by
    rw [QuadraticSpace.hyperbolicPlane_bilin_apply,
      QuadraticSpace.hyperbolicPlane_bilin_apply]
    change ((s⁻¹ : Kˣ) : K) *
        (((s : K) * x 0) * ((s : K) * y 1) +
          ((s : K) * x 1) * ((s : K) * y 0)) = _
    simp only [Units.val_inv_eq_inv_val]
    field_simp [Units.ne_zero s]
    <;> ring

/-- The integral dual of the standard lattice in `H_s` consists exactly of
the vectors whose two coordinates become integral after multiplication by
`s`. -/
theorem mem_dual_hyperbolicPlaneLattice_iff (s : Kˣ)
    (x : Fin 2 → K) :
    x ∈ dualLattice (QuadraticSpace.hyperbolicPlane s)
        (hyperbolicPlaneLattice (K := K)) ↔
      hyperbolicGlobalScaleLinearEquiv s x ∈
        hyperbolicPlaneLattice (K := K) := by
  let e0 : Fin 2 → K := Pi.single 0 1
  let e1 : Fin 2 → K := Pi.single 1 1
  have he0 : e0 ∈ hyperbolicPlaneLattice (K := K) := by
    rw [mem_hyperbolicPlaneLattice_iff]
    simp [e0]
  have he1 : e1 ∈ hyperbolicPlaneLattice (K := K) := by
    rw [mem_hyperbolicPlaneLattice_iff]
    simp [e1]
  rw [mem_dualLattice_iff, mem_hyperbolicPlaneLattice_iff]
  constructor
  · intro h
    constructor
    · have hx0 := h e1 he1
      rw [QuadraticSpace.hyperbolicPlane_bilin_apply] at hx0
      simpa [e1] using hx0
    · have hx1 := h e0 he0
      rw [QuadraticSpace.hyperbolicPlane_bilin_apply] at hx1
      simpa [e0] using hx1
  · rintro ⟨hx0, hx1⟩ y hy
    rw [QuadraticSpace.hyperbolicPlane_bilin_apply]
    rw [mem_hyperbolicPlaneLattice_iff] at hy
    have hleft := (IntegerRing K).toSubring.mul_mem hx0 hy.2
    have hright := (IntegerRing K).toSubring.mul_mem hx1 hy.1
    have hadd := (IntegerRing K).toSubring.add_mem hleft hright
    change (s : K) * (x 0 * y 1 + x 1 * y 0) ∈
      (IntegerRing K).toSubring
    change
      (hyperbolicGlobalScaleLinearEquiv s x) 0 * y 1 +
          (hyperbolicGlobalScaleLinearEquiv s x) 1 * y 0 ∈
        (IntegerRing K).toSubring at hadd
    simp only [hyperbolicGlobalScaleLinearEquiv_apply] at hadd
    rw [show (s : K) * (x 0 * y 1 + x 1 * y 0) =
        (s : K) * x 0 * y 1 + (s : K) * x 1 * y 0 by ring]
    exact hadd

/-- The integral dual of the standard lattice in `H_s` is isometric to the
standard lattice in `H_(s⁻¹)`. -/
noncomputable def dualHyperbolicPlaneLatticeIsometry (s : Kˣ) :
    Isometry
      (QuadraticSpace.hyperbolicPlane s)
      (QuadraticSpace.hyperbolicPlane s⁻¹)
      (dualLattice (QuadraticSpace.hyperbolicPlane s)
        (hyperbolicPlaneLattice (K := K)))
      (hyperbolicPlaneLattice (K := K)) where
  toLinearEquiv := hyperbolicGlobalScaleLinearEquiv s
  map_bilin := (hyperbolicGlobalScaleIsometry s).map_bilin
  map_mem := mem_dual_hyperbolicPlaneLattice_iff s

/-- Norm maximality transports from the standard hyperbolic lattice along a
lattice isometry. -/
theorem IsScaledHyperbolicLattice.isNormMaximal_proof
    {V : Type v} [AddCommGroup V] [Module K V]
    {q : QuadraticSpace K V} {L : Lattice K V}
    (h : IsScaledHyperbolicLattice q L) :
    IsNormMaximal.{u, v, w} q L := by
  rcases h with ⟨R, hscaled⟩
  rcases hscaled with ⟨f⟩
  intro W _ _ r M ambient hnorm
  rcases ambient with ⟨g⟩
  let s : Kˣ := uniformizerPowerUnit K R
  have hambientStandard :
      (QuadraticSpace.hyperbolicPlane s).IsIsometric r :=
    ⟨f.toQuadraticSpaceIsometry.symm.trans g⟩
  have hnormEq :
      normIdeal (QuadraticSpace.hyperbolicPlane s)
          (hyperbolicPlaneLattice (K := K)) =
        normIdeal q L := by
    have hmap := normIdeal_map_isometry f.toQuadraticSpaceIsometry L
    change normIdeal (QuadraticSpace.hyperbolicPlane
        (uniformizerPowerUnit K R)) (map f.toLinearEquiv L) =
      normIdeal q L at hmap
    rw [f.map_eq] at hmap
    simpa [s] using hmap
  have hstandard :
      Represents (QuadraticSpace.hyperbolicPlane s) r
        (hyperbolicPlaneLattice (K := K)) M :=
    hyperbolicPlaneLattice_isNormMaximal s
      hambientStandard (by simpa [hnormEq] using hnorm)
  have hback :
      Represents q (QuadraticSpace.hyperbolicPlane s) L
        (hyperbolicPlaneLattice (K := K)) :=
    ⟨f.symm.toRepresentation⟩
  exact hback.trans hstandard

/-- Integral duality preserves the property of being a scaled standard
hyperbolic lattice. -/
theorem IsScaledHyperbolicLattice.dual_proof
    {V : Type v} [AddCommGroup V] [Module K V]
    {q : QuadraticSpace K V} {L : Lattice K V}
    (h : IsScaledHyperbolicLattice q L) :
    IsScaledHyperbolicLattice q (dualLattice q L) := by
  rcases h with ⟨R, hscaled⟩
  rcases hscaled with ⟨f⟩
  let s : Kˣ := uniformizerPowerUnit K R
  let fd := f.dual
  let g := dualHyperbolicPlaneLatticeIsometry s
  refine ⟨-R, ?_⟩
  have htrans := fd.trans g
  exact ⟨by simpa [s, uniformizerPowerUnit, zpow_neg] using htrans⟩

end Lattice

universe u v w

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]

/-- The unconditional O'Meara maximality instance for all universe levels. -/
noncomputable instance scaledHyperbolicMaximalLawsProved :
    ScaledHyperbolicMaximalLaws.{u, v, w} K where
  normMaximal h := h.isNormMaximal_proof
  dualNormMaximal h := h.dual_proof.isNormMaximal_proof

end Bong
