/- M389 smoke test. -/
import Bong.Bong.Beli2019Lemma69TypeICentralSeedsComplete

#check Bong.BONG.GoodBONG.lemma69_typeI_centralSeedData_of_leftSwitch_zero_from_conditions
#check Bong.BONG.GoodBONG.lemma69_typeI_centralSeedData_from_conditions
#check Bong.BONG.GoodBONG.lemma69_typeI_central_values_from_conditions
#check Bong.BONG.GoodBONG.beli2019Lemma69_ii_typeI_targetValue_from_conditions

#print axioms Bong.BONG.GoodBONG.beli2019Lemma69_ii_typeI_targetValue_from_conditions
