import Bong.Bong.Beli2019Lemma79EvenCrossGap

#check Bong.BONG.GoodBONG.orderGap_previous_le_twoE_of_twoStep
#check Bong.BONG.GoodBONG.crossGap_le_twoE_of_representationOrder_of_sourceGap_le_twoE

#print axioms Bong.BONG.GoodBONG.orderGap_previous_le_twoE_of_twoStep
#print axioms Bong.BONG.GoodBONG.crossGap_le_twoE_of_representationOrder_of_sourceGap_le_twoE
