import Bong.Bong.Beli2019Lemma79EvenTypeICentralSource

#check Bong.BONG.GoodBONG.beli2019Lemma79_typeI_central_even_sourceCapped

#print axioms Bong.BONG.GoodBONG.beli2019Lemma79_typeI_central_even_sourceCapped
