import Bong.Bong.Beli2019Lemma79CaseSixCandidateShift

namespace Bong

namespace BONG.GoodBONG

#check representationHalfGap_le_add_one_of_order_eq_add_one
#check representationPrimaryDefect_le_add_one_of_order_eq_add_one
#check representationSecondaryDefect_le_add_one_of_orderSum_eq
#check representationSecondaryDefect_le_add_one_of_orderSum_eq_add_one
#check lemma79_caseSix_alpha_le_add_one_of_candidate_bounds
#check lemma79_caseSix_of_alphaShift_even_and_sourceOdd
#check lemma79_caseSix_of_gamma_eq_zero_and_current_order

#print axioms representationHalfGap_le_add_one_of_order_eq_add_one
#print axioms representationPrimaryDefect_le_add_one_of_order_eq_add_one
#print axioms representationSecondaryDefect_le_add_one_of_orderSum_eq
#print axioms representationSecondaryDefect_le_add_one_of_orderSum_eq_add_one
#print axioms lemma79_caseSix_alpha_le_add_one_of_candidate_bounds
#print axioms lemma79_caseSix_of_alphaShift_even_and_sourceOdd
#print axioms lemma79_caseSix_of_gamma_eq_zero_and_current_order

end BONG.GoodBONG

end Bong
