import Bong.Bong.Beli2019Lemma79CaseSixInteriorAssembly

namespace Bong

namespace BONG.GoodBONG

#check beli2019Lemma79_typeII_caseSix_alpha_le_add_one
#check beli2019Lemma79_typeIII_caseSix_alpha_le_add_one
#check beli2019Lemma79_typeII_caseSix_firstParity_of_gamma_ge_one
#check beli2019Lemma79_typeIII_caseSix_firstParity_of_gamma_ge_one

#print axioms beli2019Lemma79_typeII_caseSix_alpha_le_add_one
#print axioms beli2019Lemma79_typeIII_caseSix_alpha_le_add_one
#print axioms beli2019Lemma79_typeII_caseSix_firstParity_of_gamma_ge_one
#print axioms beli2019Lemma79_typeIII_caseSix_firstParity_of_gamma_ge_one

end BONG.GoodBONG

end Bong
