import Bong.Bong.Beli2019Lemma79CaseSixSecondParityProfile

namespace Bong

namespace BONG.GoodBONG

#check caseSix_even_of_modEq_two_of_even
#check beli2019Lemma79_typeII_caseSix_targetPrefix_even_of_index_even
#check beli2019Lemma79_typeII_caseSix_targetCurrent_le_thirdFirst_add_one
#check beli2019Lemma79_typeIII_caseSix_sourceRight_le_sourceLeft
#check beli2019Lemma79_typeIII_caseSix_targetCurrent_le_thirdFirst_add_one
#check beli2019Lemma79_typeIII_caseSix_index_odd
#check beli2019Lemma79_typeII_caseSix_secondParity_sameCurrentParity
#check beli2019Lemma79_typeIII_caseSix_secondParity_sameCurrentParity

#print axioms caseSix_even_of_modEq_two_of_even
#print axioms beli2019Lemma79_typeII_caseSix_targetPrefix_even_of_index_even
#print axioms beli2019Lemma79_typeII_caseSix_targetCurrent_le_thirdFirst_add_one
#print axioms beli2019Lemma79_typeIII_caseSix_sourceRight_le_sourceLeft
#print axioms beli2019Lemma79_typeIII_caseSix_targetCurrent_le_thirdFirst_add_one
#print axioms beli2019Lemma79_typeIII_caseSix_index_odd
#print axioms beli2019Lemma79_typeII_caseSix_secondParity_sameCurrentParity
#print axioms beli2019Lemma79_typeIII_caseSix_secondParity_sameCurrentParity

end BONG.GoodBONG

end Bong
