import Bong.Bong.Beli2019Lemma79CaseSixSecondParityTypeII

namespace Bong

namespace BONG.GoodBONG

#check caseSix_odd_of_modEq_two_of_odd
#check caseSix_shiftedPrefix_modEq_of_comparison_odd_and_current_opposite
#check caseSix_thirdPrevious_modEq_typeII_reference
#check beli2019Lemma79_typeII_caseSix_reference_le_thirdFirst
#check beli2019Lemma79_typeII_caseSix_targetPrefix_succ_odd_of_index_odd
#check beli2019Lemma79_typeII_caseSix_secondParity_evenIndex
#check beli2019Lemma79_typeII_caseSix_secondParity_oddIndex
#check beli2019Lemma79_typeII_caseSix_secondParity_oppositeCurrentParity

#print axioms caseSix_odd_of_modEq_two_of_odd
#print axioms caseSix_shiftedPrefix_modEq_of_comparison_odd_and_current_opposite
#print axioms caseSix_thirdPrevious_modEq_typeII_reference
#print axioms beli2019Lemma79_typeII_caseSix_reference_le_thirdFirst
#print axioms beli2019Lemma79_typeII_caseSix_targetPrefix_succ_odd_of_index_odd
#print axioms beli2019Lemma79_typeII_caseSix_secondParity_evenIndex
#print axioms beli2019Lemma79_typeII_caseSix_secondParity_oddIndex
#print axioms beli2019Lemma79_typeII_caseSix_secondParity_oppositeCurrentParity

end BONG.GoodBONG

end Bong
