import Bong.Bong.Beli2019Lemma79CaseSixSecondParityTypeIIIStrictWitness

namespace Bong

namespace BONG.GoodBONG

#check beli2019Lemma79_typeIII_caseSix_secondParity_of_strictWitness
#print axioms beli2019Lemma79_typeIII_caseSix_secondParity_of_strictWitness

end BONG.GoodBONG

end Bong
