import Bong.Bong.Beli2019Lemma79CaseSixSecondParityTypeIIIEndpointStrict

namespace Bong

namespace BONG.GoodBONG

#check caseSix_transportedCoefficient_lt_of_rightEndpoint_lt
#check beli2019Lemma79_typeIII_caseSix_primaryRightCap_lt_one
#check beli2019Lemma79_typeIII_caseSix_secondParity_of_boundaryEndpoint_lt_of_integral
#check beli2019Lemma79_typeIII_caseSix_secondParity_of_boundaryEndpoint_lt_of_nonintegral

#print axioms caseSix_transportedCoefficient_lt_of_rightEndpoint_lt
#print axioms beli2019Lemma79_typeIII_caseSix_primaryRightCap_lt_one
#print axioms beli2019Lemma79_typeIII_caseSix_secondParity_of_boundaryEndpoint_lt_of_integral
#print axioms beli2019Lemma79_typeIII_caseSix_secondParity_of_boundaryEndpoint_lt_of_nonintegral

end BONG.GoodBONG

end Bong
