import Bong.Bong.Beli2019Lemma79RightTailStrictData

namespace Bong

namespace BONG.GoodBONG

#check caseEight_beta_lt_sourceAlpha_of_lt_sourceDefect
#check beli2019Lemma79_typeI_caseEight_strictData
#check beli2019Lemma79_typeII_caseEight_strictData
#check beli2019Lemma79_typeIII_caseEight_strictData

#print axioms caseEight_beta_lt_sourceAlpha_of_lt_sourceDefect
#print axioms beli2019Lemma79_typeI_caseEight_strictData
#print axioms beli2019Lemma79_typeII_caseEight_strictData
#print axioms beli2019Lemma79_typeIII_caseEight_strictData

end BONG.GoodBONG

end Bong
