import Bong.Bong.Beli2019Lemma79RightTailGapOne

namespace Bong

#check intCast_add_one_le_of_even_of_oddRationalInteger
#print axioms intCast_add_one_le_of_even_of_oddRationalInteger

namespace BONG.GoodBONG

#check CaseEightStrictBetaTailConsequences.firstGap_odd_of_target_eq_source_add_one
#check CaseEightStrictBetaTailConsequences.firstAlpha_eq_gap_of_target_eq_source_add_one
#check CaseEightStrictBetaTailConsequences.alphaValue_eq_order_sub_first
#check CaseEightStrictBetaTailConsequences.alphaValue_eq_order_sub_first_of_target_eq_source_add_one

#print axioms CaseEightStrictBetaTailConsequences.firstGap_odd_of_target_eq_source_add_one
#print axioms CaseEightStrictBetaTailConsequences.firstAlpha_eq_gap_of_target_eq_source_add_one
#print axioms CaseEightStrictBetaTailConsequences.alphaValue_eq_order_sub_first
#print axioms CaseEightStrictBetaTailConsequences.alphaValue_eq_order_sub_first_of_target_eq_source_add_one

end BONG.GoodBONG

end Bong
