/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Mathlib.LinearAlgebra.BilinearForm.Orthogonal

/-!
# Quadratic spaces in the BONG convention

Beli writes a quadratic space using a nondegenerate symmetric bilinear form
`B` and sets `Q(x) = B(x, x)`.  Consequently

`Q(x + y) = Q(x) + Q(y) + 2 * B(x, y)`.

This differs by a factor of two from the polar bilinear form attached to a
`QuadraticMap` in mathlib.  We therefore store `B` directly and expose `Q` as
its diagonal, keeping all later lattice formulas aligned with the source.
-/

namespace Bong

open LinearMap (BilinForm)

/-- A quadratic space in Beli's convention `Q(x) = B(x, x)`. -/
structure QuadraticSpace (K : Type*) (V : Type*) [Field K] [AddCommGroup V] [Module K V] where
  /-- The symmetric bilinear form associated with the quadratic space. -/
  bilin : BilinForm K V
  /-- Symmetry of the bilinear form. -/
  isSymm : bilin.IsSymm
  /-- Nondegeneracy of the bilinear form. -/
  nondegenerate : bilin.Nondegenerate

namespace QuadraticSpace

variable {K : Type*} {V : Type*} [Field K] [AddCommGroup V] [Module K V]

/-- The one-dimensional quadratic space with `B(x, y) = x * y`. -/
def line (K : Type*) [Field K] : QuadraticSpace K K where
  bilin := LinearMap.mul K K
  isSymm := ⟨mul_comm⟩
  nondegenerate := by
    constructor
    · intro x hx
      simpa using hx 1
    · intro x hx
      simpa using hx 1

@[simp]
theorem line_bilin_apply (x y : K) : (line K).bilin x y = x * y :=
  rfl

/-- The quadratic value `Q(x) = B(x, x)`. -/
def quadratic (q : QuadraticSpace K V) (x : V) : K :=
  q.bilin x x

@[simp]
theorem line_quadratic (x : K) : (line K).quadratic x = x ^ 2 := by
  simp [quadratic, pow_two]

@[simp]
theorem quadratic_zero (q : QuadraticSpace K V) : q.quadratic 0 = 0 := by
  simp [quadratic]

@[simp]
theorem quadratic_neg (q : QuadraticSpace K V) (x : V) : q.quadratic (-x) = q.quadratic x := by
  simp [quadratic]

@[simp]
theorem quadratic_smul (q : QuadraticSpace K V) (a : K) (x : V) :
    q.quadratic (a • x) = a ^ 2 * q.quadratic x := by
  simp [quadratic, pow_two, mul_assoc]

theorem quadratic_add (q : QuadraticSpace K V) (x y : V) :
    q.quadratic (x + y) = q.quadratic x + q.quadratic y + 2 * q.bilin x y := by
  simp only [quadratic, LinearMap.BilinForm.add_left, LinearMap.BilinForm.add_right]
  rw [q.isSymm.eq y x]
  ring

theorem bilin_eq_polarization [NeZero (2 : K)] (q : QuadraticSpace K V) (x y : V) :
    q.bilin x y = (q.quadratic (x + y) - q.quadratic x - q.quadratic y) / 2 := by
  simpa only [quadratic] using q.isSymm.polarization x y

/-- A vector is anisotropic when its quadratic value is nonzero. -/
def IsAnisotropic (q : QuadraticSpace K V) (x : V) : Prop :=
  q.quadratic x ≠ 0

theorem IsAnisotropic.ne_zero {q : QuadraticSpace K V} {x : V} (hx : q.IsAnisotropic x) :
    x ≠ 0 := by
  intro h
  subst x
  exact hx (quadratic_zero q)

/-- A nonzero finite-dimensional nondegenerate quadratic space over a field
of characteristic different from two contains an anisotropic vector. -/
theorem exists_isAnisotropic_of_finrank_pos [CharZero K]
    [FiniteDimensional K V] (q : QuadraticSpace K V)
    (hpos : 0 < Module.finrank K V) :
    ∃ x : V, q.IsAnisotropic x := by
  obtain ⟨x, hx⟩ := Module.finrank_pos_iff_exists_ne_zero.mp hpos
  have hnot : ¬∀ y : V, q.bilin x y = 0 := by
    intro hzero
    exact hx (q.nondegenerate.1 x hzero)
  push Not at hnot
  obtain ⟨y, hxy⟩ := hnot
  by_cases hxq : q.IsAnisotropic x
  · exact ⟨x, hxq⟩
  by_cases hyq : q.IsAnisotropic y
  · exact ⟨y, hyq⟩
  refine ⟨x + y, ?_⟩
  rw [IsAnisotropic, q.quadratic_add]
  have hxzero : q.quadratic x = 0 := not_ne_iff.mp hxq
  have hyzero : q.quadratic y = 0 := not_ne_iff.mp hyq
  rw [hxzero, hyzero, zero_add, zero_add]
  exact mul_ne_zero (by norm_num) hxy

/-- The right orthogonal complement of a subspace.  Symmetry makes it two-sided. -/
def orthogonalComplement (q : QuadraticSpace K V) (W : Submodule K V) : Submodule K V :=
  q.bilin.orthogonal W

/-- The orthogonal complement of the line generated by `x`. -/
def vectorOrthogonal (q : QuadraticSpace K V) (x : V) : Submodule K V :=
  q.orthogonalComplement (K ∙ x)

@[simp]
theorem mem_vectorOrthogonal_iff (q : QuadraticSpace K V) (x y : V) :
    y ∈ q.vectorOrthogonal x ↔ q.bilin x y = 0 := by
  constructor
  · intro hy
    exact hy x (Submodule.mem_span_singleton_self x)
  · intro hxy z hz
    rcases Submodule.mem_span_singleton.mp hz with ⟨a, rfl⟩
    simp [hxy]

theorem span_singleton_inf_vectorOrthogonal_eq_bot (q : QuadraticSpace K V) {x : V}
    (hx : q.IsAnisotropic x) : K ∙ x ⊓ q.vectorOrthogonal x = ⊥ :=
  LinearMap.BilinForm.span_singleton_inf_orthogonal_eq_bot hx

theorem span_singleton_sup_vectorOrthogonal_eq_top (q : QuadraticSpace K V) {x : V}
    (hx : q.IsAnisotropic x) : K ∙ x ⊔ q.vectorOrthogonal x = ⊤ :=
  LinearMap.BilinForm.span_singleton_sup_orthogonal_eq_top hx

/-- An anisotropic line has a codimension-one orthogonal complement. -/
theorem finrank_vectorOrthogonal [FiniteDimensional K V]
    (q : QuadraticSpace K V) {x : V} (hx : q.IsAnisotropic x) :
    Module.finrank K (q.vectorOrthogonal x) + 1 = Module.finrank K V := by
  have hpos : 0 < Module.finrank K V :=
    Module.finrank_pos_iff_exists_ne_zero.mpr ⟨x, hx.ne_zero⟩
  rw [vectorOrthogonal, orthogonalComplement,
    q.bilin.finrank_orthogonal q.nondegenerate,
    finrank_span_singleton hx.ne_zero]
  omega

/-- Restriction to a subspace on which the form remains nondegenerate. -/
def restrict (q : QuadraticSpace K V) (W : Submodule K V)
    (hW : (q.bilin.restrict W).Nondegenerate) : QuadraticSpace K W where
  bilin := q.bilin.restrict W
  isSymm := q.isSymm.restrict W
  nondegenerate := hW

/-- The quadratic space carried by the orthogonal complement of an anisotropic vector. -/
def orthogonalSpace (q : QuadraticSpace K V) (x : V) (hx : q.IsAnisotropic x) :
    QuadraticSpace K (q.vectorOrthogonal x) :=
  q.restrict (q.vectorOrthogonal x)
    (LinearMap.BilinForm.restrict_nondegenerate_orthogonal_spanSingleton q.bilin
      q.nondegenerate q.isSymm.isRefl hx)

@[simp]
theorem orthogonalSpace_bilin_apply (q : QuadraticSpace K V) (x : V)
    (hx : q.IsAnisotropic x) (y z : q.vectorOrthogonal x) :
    (q.orthogonalSpace x hx).bilin y z = q.bilin y z :=
  rfl

@[simp]
theorem orthogonalSpace_quadratic (q : QuadraticSpace K V) (x : V)
    (hx : q.IsAnisotropic x) (y : q.vectorOrthogonal x) :
    (q.orthogonalSpace x hx).quadratic y = q.quadratic y :=
  rfl

end QuadraticSpace

end Bong
