/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Bong.Existence
import Bong.Bong.DiagonalTernaryCore
import Bong.Bong.DiagonalHeadCancellation

/-!
# Canonical finite diagonal presentations of quadratic spaces

Over the dyadic local fields considered in this project, every
finite-dimensional nondegenerate quadratic space has a BONG after choosing a
full lattice.  The ambient vectors of that BONG form an orthogonal basis.
This file uses that proved construction to package a finite diagonal model,
an explicit isometry to it, and the resulting transport of representation
questions.
-/

namespace Bong

open Dyadic
open Module

namespace QuadraticSpace

universe u v w v' w'

variable {K : Type u} [Field K] [CharZero K] [ValuativeRel K]
  [TopologicalSpace K] [DyadicContext K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {W : Type w} [AddCommGroup W] [Module K W]

/-- The full lattice generated by mathlib's chosen finite basis. -/
noncomputable def diagonalizingLattice
    [FiniteDimensional K V] : Lattice K V :=
  Lattice.basisLattice (Module.finBasis K V)

/-- A chosen BONG of the full diagonalizing lattice. -/
noncomputable def diagonalizingBONG
    [FiniteDimensional K V] (q : QuadraticSpace K V) :
    BONG V q (diagonalizingLattice (K := K) (V := V)) (finrank K V) :=
  BONG.ofLattice q (diagonalizingLattice (K := K) (V := V))

/-- A chosen orthogonal basis of a finite-dimensional quadratic space. -/
noncomputable def orthogonalFinBasis
    [FiniteDimensional K V] (q : QuadraticSpace K V) :
    Basis (Fin (finrank K V)) K V :=
  q.diagonalizingBONG.basis

/-- The chosen basis is orthogonal. -/
theorem orthogonalFinBasis_isOrtho
    [FiniteDimensional K V] (q : QuadraticSpace K V) :
    q.bilin.iIsOrtho (q.orthogonalFinBasis : Fin (finrank K V) → V) := by
  exact q.diagonalizingBONG.ambientVector_iIsOrtho

/-- Every diagonal entry in the chosen orthogonal basis is nonzero. -/
theorem quadratic_orthogonalFinBasis_ne_zero
    [FiniteDimensional K V] (q : QuadraticSpace K V)
    (i : Fin (finrank K V)) :
    q.quadratic (q.orthogonalFinBasis i) ≠ 0 := by
  rw [show q.quadratic (q.orthogonalFinBasis i) =
      q.diagonalizingBONG.value i from
    q.diagonalizingBONG.quadratic_ambientVector i]
  exact q.diagonalizingBONG.value_ne_zero i

/-- The unit-valued diagonal coefficients of the chosen orthogonal basis. -/
noncomputable def diagonalUnits
    [FiniteDimensional K V] (q : QuadraticSpace K V) :
    Fin (finrank K V) → Kˣ :=
  q.diagonalizingBONG.valueUnit

@[simp]
theorem coe_diagonalUnits
    [FiniteDimensional K V] (q : QuadraticSpace K V)
    (i : Fin (finrank K V)) :
    (q.diagonalUnits i : K) = q.quadratic (q.orthogonalFinBasis i) := by
  exact (q.diagonalizingBONG.quadratic_ambientVector i).symm

/-- The chosen finite diagonal model of a quadratic space. -/
noncomputable def diagonalModel
    [FiniteDimensional K V] (q : QuadraticSpace K V) :
    QuadraticSpace K (Fin (finrank K V) → K) :=
  finiteDiagonal (fun i ↦ (q.diagonalUnits i : K))
    (fun i ↦ Units.ne_zero (q.diagonalUnits i))

/-- The Gram matrix in the chosen orthogonal basis is diagonal. -/
theorem toMatrix_orthogonalFinBasis
    [FiniteDimensional K V] (q : QuadraticSpace K V) :
    LinearMap.BilinForm.toMatrix q.orthogonalFinBasis q.bilin =
      Matrix.diagonal (fun i ↦ (q.diagonalUnits i : K)) := by
  exact q.diagonalizingBONG.gramMatrix_eq_diagonal

/-- The coordinate map preserves quadratic values. -/
theorem diagonalModel_quadratic_equivFun
    [FiniteDimensional K V] (q : QuadraticSpace K V) (x : V) :
    q.diagonalModel.quadratic (q.orthogonalFinBasis.equivFun x) =
      q.quadratic x := by
  rw [diagonalModel, finiteDiagonal_quadratic_apply]
  have h := q.diagonalizingBONG.diagonalQuadratic_value_eq
    (q.orthogonalFinBasis.equivFun x)
  simpa [diagonalUnits, orthogonalFinBasis] using h

/-- The coordinate map in the chosen orthogonal basis is a quadratic-space
isometry from `q` to its finite diagonal model. -/
noncomputable def diagonalizationIsometry
    [FiniteDimensional K V] (q : QuadraticSpace K V) :
    Isometry q q.diagonalModel where
  toLinearEquiv := q.orthogonalFinBasis.equivFun
  map_bilin := by
    intro x y
    rw [q.diagonalModel.bilin_eq_polarization,
      q.bilin_eq_polarization]
    rw [show q.orthogonalFinBasis.equivFun x +
        q.orthogonalFinBasis.equivFun y =
          q.orthogonalFinBasis.equivFun (x + y) from
      (map_add q.orthogonalFinBasis.equivFun x y).symm,
      q.diagonalModel_quadratic_equivFun,
      q.diagonalModel_quadratic_equivFun,
      q.diagonalModel_quadratic_equivFun]

/-- A scalar represents the determinant square class of `q` when its product
with the product of the chosen diagonal coefficients is a square.  Using a
product rather than a quotient is equivalent in the square-class group. -/
def IsDeterminantRepresentative
    [FiniteDimensional K V] (q : QuadraticSpace K V) (d : Kˣ) : Prop :=
  IsSquare (d * ∏ i, q.diagonalUnits i)

/-- The product of the chosen diagonal entries is a determinant
representative. -/
theorem isDeterminantRepresentative_diagonalProduct
    [FiniteDimensional K V] (q : QuadraticSpace K V) :
    q.IsDeterminantRepresentative (∏ i, q.diagonalUnits i) := by
  rw [IsDeterminantRepresentative]
  exact ⟨∏ i, q.diagonalUnits i, by simp [pow_two]⟩

/-- Representations of finite diagonal spaces are exactly diagonal
representations of their coefficient lists. -/
theorem finiteDiagonal_represents_iff_diagonalRepresents
    {m n : Nat} (source : Fin m → Kˣ) (target : Fin n → Kˣ) :
    (finiteDiagonal (fun i ↦ (target i : K))
        (fun i ↦ Units.ne_zero (target i))).Represents
      (finiteDiagonal (fun i ↦ (source i : K))
        (fun i ↦ Units.ne_zero (source i))) ↔
      DiagonalRepresents
        (fun i ↦ (source i : K))
        (fun i ↦ (target i : K)) := by
  constructor
  · rintro ⟨f⟩
    refine ⟨f.toLinearMap, f.injective, ?_⟩
    intro x
    simpa only [finiteDiagonal_quadratic_apply] using f.map_quadratic x
  · intro h
    exact DiagonalRepresents.toQuadraticSpaceRepresents
      (fun i ↦ Units.ne_zero (source i))
      (fun i ↦ Units.ne_zero (target i)) h

/-- Isometrically changing both the source and target does not change a
quadratic-space representation question. -/
theorem represents_iff_of_isometries
    {V' : Type v'} [AddCommGroup V'] [Module K V']
    {W' : Type w'} [AddCommGroup W'] [Module K W']
    {q : QuadraticSpace K V} {q' : QuadraticSpace K V'}
    {r : QuadraticSpace K W} {r' : QuadraticSpace K W'}
    (fq : Isometry q q') (fr : Isometry r r') :
    r.Represents q ↔ r'.Represents q' := by
  constructor
  · rintro ⟨h⟩
    exact ⟨fr.toRepresentation.trans
      (h.trans fq.symm.toRepresentation)⟩
  · rintro ⟨h⟩
    exact ⟨fr.symm.toRepresentation.trans
      (h.trans fq.toRepresentation)⟩

/-- Every representation question is equivalent to the diagonal
representation question for the chosen orthogonal coefficient lists. -/
theorem represents_iff_diagonalRepresents
    [FiniteDimensional K V] [FiniteDimensional K W]
    (q : QuadraticSpace K V) (r : QuadraticSpace K W) :
    r.Represents q ↔
      DiagonalRepresents
        (fun i ↦ (q.diagonalUnits i : K))
        (fun i ↦ (r.diagonalUnits i : K)) := by
  exact (represents_iff_of_isometries
      q.diagonalizationIsometry r.diagonalizationIsometry).trans
    (finiteDiagonal_represents_iff_diagonalRepresents
      q.diagonalUnits r.diagonalUnits)

end QuadraticSpace

end Bong
