/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.Lattice.PowerIdeal
import Mathlib.LinearAlgebra.Matrix.BilinearForm
import Mathlib.Tactic.FinCases

/-!
# Scaled hyperbolic planes

The plane with Gram matrix `[[0, s], [s, 0]]` is the field model of
`s A(0, 0)` in Beli's notation.  Its distinguished lattice is generated by
the two standard coordinate vectors.
-/

namespace Bong

open Dyadic
open Module

universe u

variable {K : Type u} [Field K]

namespace QuadraticSpace

/-- The Gram matrix of the hyperbolic plane with mixed coefficient `s`. -/
def hyperbolicPlaneMatrix (s : Kˣ) : Matrix (Fin 2) (Fin 2) K :=
  !![0, (s : K); (s : K), 0]

@[simp]
theorem hyperbolicPlaneMatrix_zero_zero (s : Kˣ) :
    hyperbolicPlaneMatrix s 0 0 = 0 :=
  rfl

@[simp]
theorem hyperbolicPlaneMatrix_zero_one (s : Kˣ) :
    hyperbolicPlaneMatrix s 0 1 = (s : K) :=
  rfl

@[simp]
theorem hyperbolicPlaneMatrix_one_zero (s : Kˣ) :
    hyperbolicPlaneMatrix s 1 0 = (s : K) :=
  rfl

@[simp]
theorem hyperbolicPlaneMatrix_one_one (s : Kˣ) :
    hyperbolicPlaneMatrix s 1 1 = 0 :=
  rfl

theorem hyperbolicPlaneMatrix_isSymm (s : Kˣ) :
    (hyperbolicPlaneMatrix s).IsSymm := by
  ext i j
  fin_cases i <;> fin_cases j <;> rfl

@[simp]
theorem hyperbolicPlaneMatrix_det (s : Kˣ) :
    (hyperbolicPlaneMatrix s).det = -(s : K) ^ 2 := by
  simp [hyperbolicPlaneMatrix, Matrix.det_fin_two_of, pow_two]

/-- The nondegenerate plane with Gram matrix `[[0, s], [s, 0]]`. -/
noncomputable def hyperbolicPlane (s : Kˣ) :
    QuadraticSpace K (Fin 2 → K) where
  bilin := Matrix.toBilin' (hyperbolicPlaneMatrix s)
  isSymm := (Matrix.isSymm_toBilin'_iff_isSymm).2
    (hyperbolicPlaneMatrix_isSymm s)
  nondegenerate :=
    LinearMap.BilinForm.nondegenerate_toBilin'_of_det_ne_zero'
      (hyperbolicPlaneMatrix s) (by simp)

/-- Coordinate formula for the scaled hyperbolic bilinear form. -/
theorem hyperbolicPlane_bilin_apply (s : Kˣ) (x y : Fin 2 → K) :
    (hyperbolicPlane s).bilin x y =
      (s : K) * (x 0 * y 1 + x 1 * y 0) := by
  rw [hyperbolicPlane, Matrix.toBilin'_apply]
  simp only [Fin.sum_univ_two, hyperbolicPlaneMatrix_zero_zero,
    hyperbolicPlaneMatrix_zero_one, hyperbolicPlaneMatrix_one_zero,
    hyperbolicPlaneMatrix_one_one]
  ring

/-- Coordinate formula for the scaled hyperbolic quadratic form. -/
theorem hyperbolicPlane_quadratic_apply (s : Kˣ) (x : Fin 2 → K) :
    (hyperbolicPlane s).quadratic x =
      2 * (s : K) * (x 0 * x 1) := by
  rw [quadratic, hyperbolicPlane_bilin_apply]
  ring

end QuadraticSpace

namespace Lattice

variable [CharZero K] [ValuativeRel K] [TopologicalSpace K]
  [DyadicContext K]

/-- The standard integral lattice in every scaled hyperbolic plane. -/
noncomputable def hyperbolicPlaneLattice : Lattice K (Fin 2 → K) :=
  basisLattice (Pi.basisFun K (Fin 2))

end Lattice

end Bong
