/-
Copyright (c) 2026 BONG Theory contributors. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: BONG Theory contributors
-/
import Bong.QuadraticSpace.SpinorNormReflection

/-!
# Wall-form reduction by an anisotropic residual vector

This file formalizes the reflection step used in Taylor, *The Geometry of
the Classical Groups*, Theorems 11.36 and 11.50.  If an anisotropic vector
`u` lies in the residual space of `f`, composing `f` with reflection in `u`
removes the Wall-orthogonal line generated by `u`.  The remaining residual
Wall space is exactly the right kernel of `chi_f(u, -)`.
-/

namespace Bong

namespace QuadraticSpace

universe u v

variable {K : Type u} [Field K] [CharZero K]
  {V : Type v} [AddCommGroup V] [Module K V]
  {q : QuadraticSpace K V}

/-- Compose an isometry with reflection in `u`, applying the reflection
after the isometry. -/
noncomputable def reflectAfter (f : Isometry q q) (u : V)
    (hu : q.IsAnisotropic u) : Isometry q q :=
  f.trans (q.reflectionIsometry u hu)

@[simp]
theorem reflectAfter_apply (f : Isometry q q) (u : V)
    (hu : q.IsAnisotropic u) (y : V) :
    (reflectAfter f u hu).toLinearEquiv y =
      q.reflectionLinearEquiv u hu (f.toLinearEquiv y) :=
  rfl

/-- Rank-one formula for the residual map after a reflection. -/
theorem residualLinearMap_reflectAfter_apply (f : Isometry q q) (u : V)
    (hu : q.IsAnisotropic u) (y : V) :
    residualLinearMap (reflectAfter f u hu) y =
      residualLinearMap f y +
        (2 * q.bilin u (f.toLinearEquiv y) / q.quadratic u) • u := by
  rw [residualLinearMap_apply, reflectAfter_apply,
    reflectionLinearEquiv_apply, residualLinearMap_apply]
  abel

variable (f : Isometry q q) (u : V) (hu : q.IsAnisotropic u)
  (huResidual : u ∈ residualSpace f)

/-- The residual vector `u`, regarded as a vector of `residualSpace f`. -/
def residualVector : residualSpace f :=
  ⟨u, huResidual⟩

/-- If `u` is already residual for `f`, reflection in `u` cannot enlarge
the residual space. -/
theorem residualSpace_reflectAfter_le
    (huResidual : u ∈ residualSpace f) :
    residualSpace (reflectAfter f u hu) ≤ residualSpace f := by
  intro z hz
  rcases hz with ⟨y, rfl⟩
  rw [residualLinearMap_reflectAfter_apply]
  exact add_mem
    (LinearMap.mem_range_self (residualLinearMap f) y)
    ((residualSpace f).smul_mem _ huResidual)

/-- Inclusion of the reduced residual space into the original residual
space. -/
noncomputable def residualReflectAfterInclusion :
    residualSpace (reflectAfter f u hu) →ₗ[K] residualSpace f :=
  Submodule.inclusion
    (residualSpace_reflectAfter_le (f := f) (u := u) (hu := hu)
      (huResidual := huResidual))

@[simp]
theorem residualReflectAfterInclusion_coe
    (z : residualSpace (reflectAfter f u hu)) :
    (residualReflectAfterInclusion (f := f) (u := u) (hu := hu)
      (huResidual := huResidual) z : V) = z :=
  rfl

/-- The Wall pairing with a residual vector can be read directly from the
coefficient occurring in the reflection formula. -/
theorem wallForm_residualVector_residualMap (y : V) :
    wallForm f (residualVector f u huResidual) (residualMap f y) =
      -(2 * q.bilin u (f.toLinearEquiv y)) := by
  let w : V := residualSection f (residualVector f u huResidual)
  have hw : residualMap f w = residualVector f u huResidual :=
    residualMap_residualSection f _
  have huEq : u = w - f.toLinearEquiv w := by
    have hcoe := congrArg Subtype.val hw
    change w - f.toLinearEquiv w = u at hcoe
    exact hcoe.symm
  calc
    wallForm f (residualVector f u huResidual) (residualMap f y) =
        wallForm f (residualMap f w) (residualMap f y) := by rw [hw]
    _ = 2 * q.bilin w (residualMap f y : V) :=
      wallForm_residualMap_left f w _
    _ = -(2 * q.bilin u (f.toLinearEquiv y)) := by
      rw [residualMap_coe, huEq]
      simp only [LinearMap.BilinForm.sub_right,
        LinearMap.BilinForm.sub_left]
      rw [f.map_bilin]
      ring

/-- Every reduced residual vector is right Wall-orthogonal to `u`. -/
theorem wallForm_residualVector_inclusion_eq_zero
    (z : residualSpace (reflectAfter f u hu)) :
    wallForm f (residualVector f u huResidual)
        (residualReflectAfterInclusion (f := f) (u := u) (hu := hu)
          (huResidual := huResidual) z) = 0 := by
  rcases residualMap_surjective (reflectAfter f u hu) z with ⟨y, rfl⟩
  let c : K :=
    2 * q.bilin u (f.toLinearEquiv y) / q.quadratic u
  have hinclusion :
      residualReflectAfterInclusion (f := f) (u := u) (hu := hu)
          (huResidual := huResidual)
          (residualMap (reflectAfter f u hu) y) =
        residualMap f y + c • residualVector f u huResidual := by
    apply Subtype.ext
    change residualLinearMap (reflectAfter f u hu) y =
      residualLinearMap f y + c • u
    exact residualLinearMap_reflectAfter_apply f u hu y
  rw [hinclusion, map_add, map_smul,
    wallForm_residualVector_residualMap,
    wallForm_self_eq_quadratic]
  change -(2 * q.bilin u (f.toLinearEquiv y)) +
      c * q.quadratic u = 0
  rw [show c * q.quadratic u =
      2 * q.bilin u (f.toLinearEquiv y) by
        exact div_mul_cancel₀ _ hu]
  exact neg_add_cancel _

/-- The residual space after reflection is linearly equivalent to the
right Wall-orthogonal complement of `u`. -/
noncomputable def residualReflectAfterEquivKernel :
    residualSpace (reflectAfter f u hu) ≃ₗ[K]
      LinearMap.ker (wallForm f (residualVector f u huResidual)) := by
  let inclusionToKernel :
      residualSpace (reflectAfter f u hu) →ₗ[K]
        LinearMap.ker (wallForm f (residualVector f u huResidual)) :=
    (residualReflectAfterInclusion (f := f) (u := u) (hu := hu)
      (huResidual := huResidual)).codRestrict _
      (wallForm_residualVector_inclusion_eq_zero f u hu huResidual)
  refine LinearEquiv.ofBijective inclusionToKernel ⟨?_, ?_⟩
  · intro a b hab
    apply Subtype.ext
    exact congrArg
      (fun z : LinearMap.ker
          (wallForm f (residualVector f u huResidual)) =>
        ((z : residualSpace f) : V)) hab
  · intro z
    let y : V := residualSection f z.1
    have hy : residualMap f y = z.1 := residualMap_residualSection f z.1
    have hwall :
        wallForm f (residualVector f u huResidual) (residualMap f y) = 0 := by
      rw [hy]
      exact z.2
    have hpair : q.bilin u (f.toLinearEquiv y) = 0 := by
      rw [wallForm_residualVector_residualMap] at hwall
      have htwoPair : 2 * q.bilin u (f.toLinearEquiv y) = 0 :=
        neg_eq_zero.mp hwall
      exact (mul_eq_zero.mp htwoPair).resolve_left (by norm_num)
    refine ⟨residualMap (reflectAfter f u hu) y, ?_⟩
    apply Subtype.ext
    apply Subtype.ext
    change residualLinearMap (reflectAfter f u hu) y = (z.1 : V)
    rw [residualLinearMap_reflectAfter_apply, hpair]
    simp only [mul_zero, zero_div, zero_smul, add_zero]
    exact congrArg Subtype.val hy

@[simp]
theorem residualReflectAfterEquivKernel_coe
    (z : residualSpace (reflectAfter f u hu)) :
    (((residualReflectAfterEquivKernel f u hu huResidual z :
        LinearMap.ker (wallForm f (residualVector f u huResidual))) :
      residualSpace f) : V) = z :=
  rfl

/-- Under the reduction equivalence, the reduced Wall form is literally
the restriction of the original Wall form. -/
theorem wallForm_reflectAfter_restriction
    (a b : residualSpace (reflectAfter f u hu)) :
    wallForm f
        ((residualReflectAfterEquivKernel f u hu huResidual a :
          LinearMap.ker (wallForm f (residualVector f u huResidual))) :
          residualSpace f)
        ((residualReflectAfterEquivKernel f u hu huResidual b :
          LinearMap.ker (wallForm f (residualVector f u huResidual))) :
          residualSpace f) =
      wallForm (reflectAfter f u hu) a b := by
  rcases residualMap_surjective (reflectAfter f u hu) a with ⟨y, rfl⟩
  let w : V := residualSection f (residualVector f u huResidual)
  let c : K :=
    2 * q.bilin u (f.toLinearEquiv y) / q.quadratic u
  have hw : residualMap f w = residualVector f u huResidual :=
    residualMap_residualSection f _
  have haPreimage :
      residualMap f (y + c • w) =
        residualReflectAfterInclusion (f := f) (u := u) (hu := hu)
          (huResidual := huResidual)
          (residualMap (reflectAfter f u hu) y) := by
    apply Subtype.ext
    change residualLinearMap f (y + c • w) =
      residualLinearMap (reflectAfter f u hu) y
    rw [map_add, map_smul, residualLinearMap_reflectAfter_apply]
    change residualLinearMap f y + c • residualLinearMap f w =
      residualLinearMap f y + c • u
    rw [show residualLinearMap f w = u by
      exact congrArg Subtype.val hw]
  have hbKernel :
      wallForm f (residualVector f u huResidual)
        (residualReflectAfterInclusion (f := f) (u := u) (hu := hu)
          (huResidual := huResidual) b) = 0 :=
    wallForm_residualVector_inclusion_eq_zero f u hu huResidual b
  have hwb : q.bilin w (b : V) = 0 := by
    rw [← hw, wallForm_residualMap_left] at hbKernel
    exact (mul_eq_zero.mp hbKernel).resolve_left (by norm_num)
  calc
    wallForm f
        ((residualReflectAfterEquivKernel f u hu huResidual
          (residualMap (reflectAfter f u hu) y) :
            LinearMap.ker
              (wallForm f (residualVector f u huResidual))) :
          residualSpace f)
        ((residualReflectAfterEquivKernel f u hu huResidual b :
            LinearMap.ker
              (wallForm f (residualVector f u huResidual))) :
          residualSpace f) =
        wallForm f (residualMap f (y + c • w))
          (residualReflectAfterInclusion (f := f) (u := u) (hu := hu)
            (huResidual := huResidual) b) := by
            rw [haPreimage]
            congr 1 <;> apply Subtype.ext <;>
              simp only [residualReflectAfterEquivKernel_coe,
                residualReflectAfterInclusion_coe]
    _ = 2 * q.bilin (y + c • w) (b : V) :=
      wallForm_residualMap_left f _ _
    _ = 2 * q.bilin y (b : V) := by
      simp only [LinearMap.BilinForm.add_left,
        LinearMap.BilinForm.smul_left, hwb, mul_zero, add_zero]
    _ = wallForm (reflectAfter f u hu)
        (residualMap (reflectAfter f u hu) y) b := by
      rw [wallForm_residualMap_left]

end QuadraticSpace

end Bong
